### ISSUE TITLE
Address performance issues with collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1]
Collections are performing badly when it comes to both reads and writes. It's unacceptable for the fetch of 25 items on a collection of 2000 items to take ~10 seconds. Imports are similarly slow. The issue also impacts solr indexing. Things get worse when the number of items grows.

Collections need to be remodeled similar as in https://github.com/OpenConceptLab/ocl_datim/issues/102. It's a bit more complex as we need to account for dynamic reference resolution of concepts and mappings belonging to a collection.

@paynejd, please confirm that I understand the logic correctly. When you create a new version of a collection and have references to concepts and not specific concept versions, then that collection version will be created using a specific concept version (latest at the time of version creation). In other words references will never be evaluated again for a collection version other than HEAD.

@rkorytkowski Sorry that I missed your question here! You are correct in your analysis -- references to HEAD are resolved to a specific concept/mapping version at the time of repo version creation.

**Comment by rkorytkowski** [comment]
Addressed slowly loading pages in presence of the "Add to collection" button. The web code was doing 100+ requests to fetch available collections for a user. Fixed to one request in https://github.com/OpenConceptLab/ocl_web/commit/a326e3f89656a5274053185a4c900d758159e117 and https://github.com/OpenConceptLab/oclapi/commit/e3ce3fac701b86e1de356095c88c14044b6d6154

I'll soon deploy to staging and production.

**Comment by rkorytkowski** [comment]
Deployed the above to staging and production.

**Comment by rkorytkowski** [comment]
@paynejd, I'm ready to merge it in. It's a bigger change, which may result in issues coming up. I'll be addressing them as I notice them, but wanted to make sure there are no demos or bigger imports planned for next week. Please let me know!

**Comment by paynejd** [comment]
Hi Rafal, great progress! We have a 4 week Sprint to deliver new content to
PEPFAR on the staging server. If there's a possibility of interfering with
that, I would suggest that we only deploy if it won't be disruptive to roll
it back in case it doesn't work as expected.

**Comment by rkorytkowski** [comment]
The merge can't be easily rolled back so we need to wait until the sprint ends. When is that?

**Comment by paynejd** [comment]
Our full end-to-end demo is the week of Aug 27, so we would need to wait to
deploy this until week of Sep 3

**Comment by rkorytkowski** [comment]
Are we good to merge it in? When is the next demo or any other work, which requires the staging server?

**Comment by paynejd** [comment]
Rafal- we need to hold off a little longer for this. Going live next week
and then we can pull the trigger. Is there a way we can test a deployment
to a server with data on it before going to staging? For example, making a
copy of staging?

**Comment by rkorytkowski** [comment]
I'll test it locally before merging on stating data. If you mean a public server, then QA may be too weak to handle it. dev.openconceptlab.org is an option, but slightly more work to deploy it there.

**Comment by rkorytkowski** [comment]
BTW aren't you planning to move PEPFAR to production box?

**Comment by paynejd** [comment]
FYI we are planning to deploy PEPFAR to production box and will determine the timeline for that by Monday

**Comment by paynejd** [comment]
I just completed a fresh import of Namibia's FY18 country mappings and the performance difference was enormous! This import consisted of ~450 resources

**Import before Rafal implemented the fix:**
```
[2018-09-09 01:13:59.335484] **** STEP 1 of 12: Download PEPFAR/DATIM-MOH metadata export for specified period from OCL 
...
[2018-09-09 02:01:30.786473] **** IMAP import process complete! 
```

**Import after the fix:**
```
[2018-10-15 12:06:39.140989] **** STEP 1 of 12: Download PEPFAR/DATIM-MOH metadata export for specified period from OCL
...
[2018-10-15 12:12:14.036677] **** IMAP import process complete! 
```

**Summary:**
* Before the fix: 47min 31sec
* After the fix: 5min 35sec
* Difference: 88% reduction in import time (41min 56sec faster)
  * Or, 0.74 seconds per resource vs. 6.3 seconds per resource

**Comment by paynejd** [comment]
this is now unblocked! should we aim to promote next week on your Monday morning? or please suggest another time that works for you when we might expect some downtime.

**Comment by rkorytkowski** [comment]
Great! Let's plan for Monday next week (3-6 am EDT).

**Comment by paynejd** [comment]
Yes sounds good!

**Comment by rkorytkowski** [comment]
Deployed to qa and staging!

**Comment by rkorytkowski** [comment]
@paynejd, please let me know, if you spot any issues. I'll allow at least a week for testing before pushing to production.
