### ISSUE TITLE
Add purge parameter capability to all DELETE calls for resources that can "retire"

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#10]
Currently, DELETE calls only deactivate/retire a resource, effectively hiding it from view. Add a new "purge" parameter to all DELETE calls that actually causes a full DELETE of the resource (from both Mongo and Solr) when set to true.

**Comment by Karuhanga** [comment]
Hey @paynejd,

The docs now indicate that this is supported, is this case?
https://github.com/OpenConceptLab/oclapi/wiki/concepts#retire-concept

**Comment by paynejd** [comment]
@rkorytkowski Has this been implemented? I don't believe that it has

**Comment by rkorytkowski** [comment]
No, it hasn't...

**Comment by paynejd** [comment]
Work on this topic will be addressed in #323 -- closing this out
