### ISSUE TITLE
Move concept/mapping custom attributes into details section

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1001]
See mockup here: 
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/77ca1eff-d6c6-427e-a299-ca77df7bd7e2)

**Comment by snyaggarwal** [comment]
@jamlung-ri is this duplicate of #999 ?

**Comment by jamlung-ri** [comment]
Yeah it is. I went ahead and closed that duplicate out. I'll review this one later.

**Comment by jamlung-ri** [comment]
This is working well in QA, including when looking at Custom Attributes of different formats. [See this as an example](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyCSVSource/concepts/Act/).
