### ISSUE TITLE
Fix display of logos in org header

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1002]
What is the recommendation for fixing the display of an org logo in the header? See how the top/bottom is clipped
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/8774e7e2-f82f-400c-9ea1-9e73c235ec01)

Also, can we create a rounded square with white background, light gray border to hold the logo? This will look a lot cleaner. Something like this:

![image](https://user-images.githubusercontent.com/1189689/135136109-0954a876-9273-49a1-b8e2-bc658b468125.png)

**Comment by jamlung-ri** [comment]
Example logos (each with a link below):
![PEPFAR-Logo-Color-+Tagline+medium](https://user-images.githubusercontent.com/55999682/135264647-1b12a758-e373-4241-a25c-785cd3727554.jpg)
https://cdn2.poz.com/73615_PEPFAR-white.jpg_2bfb9719-27b5-44d7-b54a-478a4c7385c2_x2.jpeg

![1200px-US-PEPFAR-Logo svg](https://user-images.githubusercontent.com/55999682/135264733-0b66a4bf-d498-46b7-af8b-835c58776c56.png)
https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/US-PEPFAR-Logo.svg/1200px-US-PEPFAR-Logo.svg.png

**Comment by jamlung-ri** [comment]
We should be able to use wide, tall, and square logos, but we currently only support wide logos.
