### ISSUE TITLE
Change checkbox column in list views to a fixed width 

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1007]
The width of the checkbox column changes with the screen width and is often very large (See first screenshot below). We want the checkbox column to have a fixed narrow width that doesn't change size based on the width of the screen, more like Gmail (see the 2nd screenshot below)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/a2ffbf10-f133-43f5-80e3-0ab1b2ec9bd7)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/eac3dae9-f875-4753-963c-0d8b5f0aad4b)

**Comment by jamlung-ri** [comment]
This is fixed in QA. We may need to figure out overall table sizing in the future, but that will be in another ticket if needed.
