### ISSUE TITLE
Delete cached exports when deleting repos/repo versions/orgs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#101]
Not positive but with the current set up, is it possible that if I delete a repo version that has a cached export, make some changes in the repo, then create a new repo version with the same version ID, that we do not have code in place to determine that the cached export on S3 is actually not the same. Is that right?

We could include code to delete the cached versions when their resources in OCL are deleted.

We could also add a checksum or some other validation approach to ensure that the cache export is correct.

Or both.

Thoughts?

**Comment by paynejd** [comment]
@rkorytkowski @snyaggarwal Can you confirm whether cached exports are deleted when a repo is deleted? And when a user checks if an export exists for a repo version, how does checking occur? For example, if a repo is deleted and a new one is created with the same ID and same version ID, does the API have a way to know that an old cached export is not the same?

Let's use this ticket to decide if we need to do a small amount of work to make management of cached exports a little bit smarter.

**Comment by snyaggarwal** [comment]
1. Each repo version is exported to a specific path which is tied to last_child_update timestamp. So GET orgs/:org/sources/:source/:version/export will return S3 URL for exported version.
2. On delete of a repo version its exported data from s3 is not deleted.
3. Simplest way is to delete all old (if more than one for the version) exports on delete of version. Ok if I proceed?

**Comment by paynejd** [comment]
Makes sense to me. @rkorytkowski ?

**Comment by snyaggarwal** [comment]
Can I get AWS secret/access keys to test this out?

**Comment by snyaggarwal** [comment]
This is done.
