### ISSUE TITLE
[OCLWEB2][UI] Tab configuration to include filter value part of custom URL

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1010]
Write now tabs can be configured to add custom query parameters in the search results URL.
And custom interactive filters can also be created for each tab using configurations.
We want to extend this to have tab configuration to interpolate filter value directly in URL.
For example, a tab URI is configured as below:
`/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_[:period]/concepts/`
should pick up values from the `period` custom user filter defined in the same tab's configuration.
Also, there should be a defaultURI in the configuration which will be used if the `period` filter has no value.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri This can be achieved by adding the below type configuration in a tab:

```
{
      uri: '/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_[:period]/',
      defaultURI: '/orgs/PEPFAR-Test10b/collections/MER/latest/', # this is required for the case when period filter has no value
      type: 'concepts',
      label: 'Reference Indicators Special',
      fields: [
        {
          display_name: 'Name'
        },
        {
          'extras.Guidance Version': 'Version'
        }
      ],
      layout: 'table',
      default: false,
      filters: {
        concept_class: 'reference indicator',
        'extras.Period': {
          key: 'period',   # key should match with placeholder ([:period]) defined in URI
          url: true,  # makes it applicable in URL and not in query params
          name: 'Period', # can be anything that we want to show on UI
          default: 'FY21',
          options: [
            'FY16',
            'FY17',
            'FY18',
            'FY19',
            'FY20',
            'FY21'
          ]
        },
        'extras.Reporting frequency': {
          name: 'Reporting Frequency',
          options: [
            'Quarterly',
            'Semi-Annually',
            'Annually',
            'Other'
          ]
        }
      },
      page_size: 100,
      query_params: {
        includeExtras: true
      }
    }

```

**Comment by jamlung-ri** [comment]
@snyaggarwal We identified an issue with this. On the [MSP](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true)'s Reference Indicator tab, which has a Period filter that affects the URL and a Reporting Frequency filter that should add a query parameter (e.g. ?extras.Reportingfrequency=Annually), that Reporting Frequency filter appears to be changing the URL. 

![image](https://user-images.githubusercontent.com/55999682/135513339-facdb45f-4be0-4a32-8867-a8090be270fd.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed
