### ISSUE TITLE
Small concept details tweaks

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1013]
Using this concept as an example: https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/sources/MER/concepts/aZrOAEKtXAo/

* All:
  - [x] Change counts in the headers of each section from text (eg `(3)`) to use the same "token" display used on global search:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/e9c2df9b-0cdd-43ca-838c-5289e2604228)
  - [x] A first simple change for a more reactive display: For narrow screen width, move Associations and Collection Membership to below the Attributes (Will be covered in separate ticket)

- [x] Names & Synonyms/Descriptions panels:
  - [x] Group names and descriptions by locale - using the same grouping format used for the "Relationship" column (`mapping.map_type`) in the "Associations" section (see screenshot below)
  * Sort name/description locales in this order:
    - [x] Source default locale (eg `en`) comes first
    - [x] Source supported locales in alphabetic order next
    - [x] Remaining locales in alphabetic order
  - [x] Use same light-gray border between each name/description

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/3d001fd6-d4ca-4916-884f-e25c55210438)

* Associations
  - [x] Add a mouseover "tooltip" to the right of Associations (same as for collection membership) with the message: "Showing only associations in the same source"
  - [x] "Code" and "Name" columns should use the same vertical-align setting (notice "Code" is higher on the screen than "Name")
  - [x] Give the "Action" column a narrow fixed width and align it to the far right -- ideally reduce the width of this column as well to the bare minimum to give more space for text
    - [x] Can reduce the font-size for the Action icon too -- probably make this feel like it's a similar size/weight as the text for each association
  - [x] Ideally reduce vertical spacing even further -- only 5 mappings can fit in the panel, and it most concepts have more than that
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/94ea72b3-5dff-4c7a-9a11-df05c6cd4eb0)

* Collection membership:
  - [x] The old label display I think is on its way out -- Suggest listing these in a table view, grouped by collection ID -- suggest either a comma-separated list of versions, with the "latest released" first; OR, one row per version, with the group collapsed so that only the latest released is visible until it is expanded
  - [x] Modify mouseover tooltip slightly to: "Showing only collections owned by the same organization or user"
    - [ ] QUESTION: How does this list change depending on permissions? If there are private collections in an org, when would they show up here?

* Custom attributes panel:
  - [x] Add count of attributes to the "Attributes" header (same as other sections
  - [x] Top-align the key and value
  - [x] Reduce font-size of the "RAW" display, to be the same size as the JSON text in the "FORMATTED" display
  - [x] Sort custom attributes alphabetically
  - [x] Suggest replacing the "RAW" / "FORMATTED" link with an actual toggle widget that goes back-and-forth between "Raw" and "Formatted"

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/a441f5c7-f39e-4ea0-bd89-c50f562c8a8c)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/abb95fe3-b196-41c8-9d4e-b772a2e81db7)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/75e10aaa-6c52-4376-aca7-2433bd4adb71)

**Comment by jamlung-ri** [comment]
Looking good so far! I was able to verify most things in QA. Looks like there are a couple more things to address @snyaggarwal . Please see the comments below.

>     * Custom attributes panel:
>       
>       * [x]  Top-align the key and value

- [ ] This one still seems to be showing a middle-aligned key. See screenshot, where Codelists is center-aligned.

![image](https://user-images.githubusercontent.com/55999682/136087889-d6438bbb-9d57-4b0b-b0b9-168d9f436cef.png)


>       * [x]  Sort custom attributes alphabetically

- [ ] See screenshot above; it looks like these are not yet sorted alphabetically.

>       * [x]  Suggest replacing the "RAW" / "FORMATTED" link with an actual toggle widget that goes back-and-forth between "Raw" and "Formatted"

- [ ] I now see the "Raw" side of the switch, but can the other side say "Formatted"?

**Comment by snyaggarwal** [comment]
@jamlung-ri Done. Should be available on QA

**Comment by jamlung-ri** [comment]
Awesome! Those are fixed but now there are a couple more small things.

- [ ] Capitalize "formatted" and "raw" (i.e. "Formatted" and "Raw")
- [ ] It looks like the dictionaries are now being displayed horizontally, putting the different entries side by side. These should be listed out vertically. 
     - [ ] Even better, they can be listed out vertically but also have their own fixed height box that you can scroll down in or could scroll past if you aren't interested in that attribtue.
![image](https://user-images.githubusercontent.com/55999682/136197424-15cd60b1-124f-41ed-a914-9d56b4e413eb.png)
