### ISSUE TITLE
Share Button URL bug

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1014]
When you create a filtered list and then Share/copy the URL for the filter, it fails due to an extra # sign:

https://app.openconceptlab.org/##/orgs/CIEL/sources/CIEL/mappings/?q=&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off

Corrected:

https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/mappings/?q=&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off

**Comment by snyaggarwal** [comment]
Fixed
