### ISSUE TITLE
Right align the row expanding arrow and narrow its box

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1015]
The row-expanding arrow on the right side should be aligned to the right side. There should not be much space between the arrow and the right side.

Also, this arrow's box should have a narrow fixed width so that there is little space between it and the adjacent column.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/5dba4fdf-2c32-4079-8c42-404018b4b14c)

**Comment by snyaggarwal** [comment]
done
