### ISSUE TITLE
Consistent spacing between tabs, rather than having a minimum width

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1016]
The spacing between these tabs seems inconsistent, probably because they all have a minimum width, but we want the tabs to be consistently spaced. It should look like the same amount of spacing between _Code Lists_ and _About_ as there is between _Reference Indicators_ and _Data Elements_.

![image](https://user-images.githubusercontent.com/55999682/135617734-63067456-905e-4581-b414-10f41bf846bf.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri the easiest thing to do is to left align them rather than centre.

**Comment by paynejd** [comment]
@snyaggarwal Can we just have a constant left+right padding/margin (eg 15px or 20px) for all tabs and keep them center aligned?
