### ISSUE TITLE
List attributes need to be concatenated with a ", " in between list entries.

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1019]
When showing an attribute that has multiple list entries, they seem to be concatenating into a single string with no separations. 

A good example is in the Period attributes of Data Elements tab of the [MSP](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true)

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/c0f023ec-0a2c-4fe4-ad91-78cd9beea3e3)

**Comment by snyaggarwal** [comment]
Done
