### ISSUE TITLE
Add users to PIH Organization

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1021]
PIH Users need to be able to use the OpenMRS Dictionary Manager. But, right now they cannot use it for PIH things, because there are no members in the PIH Organization. So no one can add their peers to the organization either. 

Please add the following OCL accounts as members to the PIH Organization: 

- mseaton
- ball
- mogoodrich

Thank you!

**Comment by paynejd** [comment]
All done in production!

FYI there are a handful of organizations from the early days of OCL, like PIH, that don't have any members. We already have a ticket to clean all of these up, and just haven't gotten around to it yet. For now, just fixed this one manually.
