### ISSUE TITLE
Normal casing for tabs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1023]
Tabs are currently styled to uppercase all text (`text-transform: uppercase;`) -- let's switch this to just normal casing, which will reduce screen real estate, and allow admins more configuration control. Here are two examples:

## Global Search
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/e26a1274-60c8-4a6c-ac36-4bffe3b371e0)

## User profile page
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/e9fba47c-8e51-404f-9199-fd463575c648)

## Org page
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/be726aad-b88d-4da3-b6ac-1560b435dd49)

## Custom org page
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/7315b238-70a2-4a19-b464-1bf0fe6d8f54)

**Comment by jamlung-ri** [comment]
I verified all of these in QA. Looking good!
