### ISSUE TITLE
Multiple concept versions showing up in source concept list

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1036]
See here, many versions of the same concept are appearing in the results:

https://app.openconceptlab.org/#/orgs/OS4H/sources/OS4H.MASTER/?q=aor&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/3459ba44-6b6d-4bb8-991e-828311a16651)

**Comment by snyaggarwal** [comment]
This is fixed. Closing this.
