### ISSUE TITLE
Automate monthly usage report for Prod/Stg on the first of each month

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1038]
We'd like to automate sending (as email?) the monthly usage report for production & staging on the 1st of each month.

**Comment by snyaggarwal** [comment]
@paynejd We need a list of recipients for this.

**Comment by paynejd** [comment]
Created group: reports@openconceptlab.org

Added members: Sunny, Rafal, Joe, Jon

**Comment by snyaggarwal** [comment]
This is deployed on QA.
The task will run on the 1st of every month to report last month's usage in email for every env. 
Will promote it further.

**Comment by snyaggarwal** [comment]
Deployed everywhere. Closing this.
