### ISSUE TITLE
Names not showing up for concept details

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1040]
Or actually, the dictionary's supported names are all showing up in concept details even though there are no names/synonyms for several of them. See screenshot below.

https://app.openconceptlab.org/#/users/gpotma/sources/GraceTst2/concepts/GraceDiagnosisDemo1/

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/2341bdd4-18e9-49b5-82ed-4beae1abad2c)

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on all environments. Please verify and close this.
