### ISSUE TITLE
LOINC Reload - 2.70 and 2.71

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1043]
We have received both LOINC versions 2.70 and 2.71 from Apelon. Since we already wanted to delete and reload the previous version of LOINC, we are going to use these versions as a test for OCL source versioning. Versions 2.70 and 2.71 will be created and later validated.

**Comment by jamlung-ri** [comment]
LOINC 2.71 seems to have some issues:
* There are multiple duplicate concepts, which appears to have happened when multiple versions were created for a resource and many of them are marked as "latest=true" (import issue?)
* There were some additional mappings that were present in 2.71 that seemed like they were present in 2.70 but were not present in the 2.71 import file (content issue). I can take these up with Apelon.

Duplicate Concept List:

> ERROR: OCL has more than one concept with id "LP73184-1"
> ERROR: OCL has more than one concept with id "LP73184-1"      
> ERROR: OCL has more than one concept with id "LP73184-1"      
> ERROR: OCL has more than one concept with id "LP73184-1"      
> ERROR: OCL has more than one concept with id "LOINC_COMPONENT"
> ERROR: OCL has more than one concept with id "LP248771-0"     
> ERROR: OCL has more than one concept with id "LOINC_COMPONENT"
> ERROR: OCL has more than one concept with id "LOINC_CLASS"
> ERROR: OCL has more than one concept with id "LOINC_CLASS"
> ERROR: OCL has more than one concept with id "LOINC_COMPONENT"
> ERROR: OCL has more than one concept with id "LOINC_COMPONENT"
> ERROR: OCL has more than one concept with id "LP57347-4"
> ERROR: OCL has more than one concept with id "LP57347-4"
> ERROR: OCL has more than one concept with id "LP57347-4"
> ERROR: OCL has more than one concept with id "LP57347-4"
> ERROR: OCL has more than one concept with id "LP72124-8"
> ERROR: OCL has more than one concept with id "PANEL.HEM/BC"
> ERROR: OCL has more than one concept with id "HEM/BC"
> ERROR: OCL has more than one concept with id "DRUG/TOX"

**Comment by snyaggarwal** [comment]
I will take a look at this data. 
There was a bug sometime back that caused this, which is fixed now. I will fix this data.

**Comment by snyaggarwal** [comment]
@jamlung-ri This should be good now.

**Comment by jamlung-ri** [comment]
Things are looking good in LOINC! Next step is to inform Jess at Apelon about the extra mappings. Otherwise, LOINC is in really good shape at the moment.

**Comment by jamlung-ri** [comment]
Next step on this is to talk with the LOINC team, where we can walk them through LOINC in OCL Staging.

**Comment by jamlung-ri** [comment]
> Things are looking good in LOINC! Next step is to inform Jess at Apelon about the extra mappings. Otherwise, LOINC is in really good shape at the moment.

Update: The extra mappings have been retired, and Jess has been informed about them. Otherwise, LOINC 2.70 and 2.71 are done in Staging.
