### ISSUE TITLE
[OCLAPI2] Package updates

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1044]
- [x] kombu from 4.6.11 to 5.1.0
- [x] celery[redis] from 4.4.7 to 5.1.2
- [x] flower from 0.9.5 to 1.0.0

**Comment by paynejd** [comment]
@snyaggarwal Now that you regularly update packages, is there any value in keeping this ticket around? Can we close it?

**Comment by snyaggarwal** [comment]
@paynejd I would suggest keeping this. These three are big upgrades and need some testing.

**Comment by snyaggarwal** [comment]
This was done as part of celery-beat service. Closing this
