### ISSUE TITLE
$cascade for OpenMRS - Automatically add sets (answers, labsets, etc) when parent concept is added to my collection

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1057]
As a user assembling a collection using the OCL Online UI, I want it to be fast to add sets of things into my collection (e.g. a Question with many connected answers; a LabSet ("panel") with many connected labs), so that I can "Add to Collection" a panel concept like CBC (Complete Blood Count #1019) and automatically have all the relevant labs in that panel also added to my collection (e.g. Hematocrit, Platelets, Hemoglobin, etc). 

I actually expected this was already the case because when I click "Add to Collection" I see the modal that confirms that it will "Automatically add associated mappings": 
![image](https://user-images.githubusercontent.com/67400059/138791432-2806ba65-fd7f-44d0-b89f-55430e10264f.png)

(e.g. see 5 min clip of user testing adding a LabSet to a collection here: https://www.loom.com/share/d841edce17b547f8a5a922ed423ce1cd)

**Comment by jamlung-ri** [comment]
We had a Cascading discussion in [today's Arch call](https://docs.google.com/document/d/157ChmfmYLGLEg_fO4cE7oMqtGpL4PchUkEhNfUUMxdo/edit#heading=h.fz3dsfd380vt), which lays out some more specific functionality for $cascade. 

Highlight:

> Proposed method: Implement a new $cascade operation that returns mixed resource types based on the parameters used

> /orgs/CIEL/sources/CIEL/concepts/1234/$cascade?method=sourceToConcepts&cascadeMapTypes=SAME-AS&resourceTypes=concepts,mappings

> Need to consider recursion and hierarchy, and how this aligns with FHIR $subsumes
Would maintain backwards compatibility until we retire the old-style cascade

**Comment by jamlung-ri** [comment]
@snyaggarwal I am going to put this back to In Dev for these changes. We also need to get feedback on the UI piece of this.

Since this is becoming a series of features, we probably need to create a specific epic for this and continue to track the features there.

**Comment by jamlung-ri** [comment]
Turning this into an epic and adding tickets to it

**Comment by jamlung-ri** [comment]
Closing this out since this functionality has been implemented in OCL for some time. Note that there will be an additional set of work for OCLv3, which will be documented here: https://docs.google.com/document/d/1nkSEU4qizs3fk6y8DZ_p_ZP3-8MA2ovgup3b22L5Bn4/edit#heading=h.zbg0nbu53vfv
