### ISSUE TITLE
Easy navigation back to previous pages

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1058]
As a user reviewing content in OCL, I need it to be easy to go back to a previous org/source/collection/concept I was recently viewing, so that I don't have to spend so much time/clicks navigating through the app to go back to a relevant org/source/collection/concept. (The other solution is that I can have a large # of tabs open.)

Video showing user testing where this came up a few times: (Minute 4:00) https://www.loom.com/share/d841edce17b547f8a5a922ed423ce1cd

Suggestion: Could a "Recent" navigation widget be added to the user's navigation bar, similar to the "recent" feature that both [Slack](https://www.howtogeek.com/668154/how-to-quickly-access-your-recent-conversations-on-slack-for-desktop-and-web/#:~:text=To%20access%20your%20most%20recent,most%20recent%20conversations%20in%20order.) and [Spotify](https://support.spotify.com/us/article/listening-history/) now use, so users can simply click "recent" to have one-click navigation back to what they were recently looking at? 
![image](https://user-images.githubusercontent.com/67400059/138792185-1ac07473-41c8-416c-8535-621830940e38.png)

**Comment by snyaggarwal** [comment]
This is available on QA

**Comment by jamlung-ri** [comment]
This is great! I really like that I can open up a new tab for the pages I was previously on. One quick change: can the list be deduplicated? See screenshot where the ocladmin profile page shows up multiple times. 
![image](https://user-images.githubusercontent.com/55999682/141305126-42932f5f-08c6-47fe-a2d8-1dfe0e6d4a41.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri the list is a stack. It works exactly like browser back. From the screenshot above, you visited ocladmin profile and then a source and then back to ocladmin. Its reflecting the same. The path you took.
Also this stack keeps shifting to last 10 visits. 
@jamlung-ri Does this make sense?

**Comment by jamlung-ri** [comment]
Gotcha, yeah that makes sense. In that case, I think we are good to close this. Thanks!
