### ISSUE TITLE
Implement ICD-11 Connector

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1068]
- [ ] Update FHIR Connector to support ICD-11 API
- [ ] Document an example FHIR Connector configuration

Start this as bare bones, and we can make it more sophisticated later on.

**Comment by jamlung-ri** [comment]
Helpful info:

Mockups:
Query Documentation:

What is a Linearization?
Article that summarizes up what a linearization is in the Introduction. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5959961/. Basically, a linearization is like a subset of the ICD-11 Foundation for a certain area of care, and each linearization will consist of a hierarchy that is meaningful to that area of care. MMS is a ICD-11 linearization, and another is the Primary Care linearization, which is under development. ICHI and ICF are others. Seems like each linearization will, when ready, be represented as a CodeSystem resource in the FHIR API.

**Comment by snyaggarwal** [comment]
@jamlung-ri The basic listing/pagination and limited search is deployed on QA env. You can switch to ICD-11 server from the list.
I saw the ICD 11 API doesn't support ConceptMap, so I have removed that using server config.
I am working on to fix/update rest of the navigations first.

**Comment by jamlung-ri** [comment]
This is off to a great start! The CodeSystem and ValueSet listings are looking good, and I was able to do a few searches on CodeSystems and ValueSets. Looking forward to seeing the rest of the navigations!

**Comment by paynejd** [comment]
ICD-11 Connector Query Documentation:
https://docs.google.com/document/d/1x4-QnX_2tqBBnHNH-IilUHdvwTZ8Z5mkb0lKcYooyYk/edit#

@jamlung-ri and @snyaggarwal - please continue to update this document as the ICD-11 Connector is developed. This should end up as the query specification for the connector that will be added to our docs site when ready

**Comment by paynejd** [comment]
Round 1 of this is complete - we'll pick this up again with new tickets soon
