### ISSUE TITLE
"OpenMRS custom validation schema" error incorrectly generated when editing a user source

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#107]
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/2f19a004-4615-431a-bfe1-aeb2618060e6)

**Comment by paynejd** [comment]
@Karuhanga Is this an error that you experienced?

**Comment by Karuhanga** [comment]
Haven't faced this yet.

**Comment by paynejd** [comment]
@snyaggarwal Please note this bug -- was this addressed already in oclapi2?

Note that we will not do any work on this ticket in oclapi1

**Comment by snyaggarwal** [comment]
I couldn't reproduce this in oclapi2

**Comment by aprilcurrier** [comment]
Not Occurring in OCL API 2
