### ISSUE TITLE
OpenMRS custom validation schema should allow duplicate non-preferred synonyms

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1070]
Per @snyaggarwal's comment [here](https://github.com/OpenConceptLab/ocl_issues/issues/1027#issuecomment-953504586), the OpenMRS custom validation code for [`preferred_name_should_be_unique_for_source_and_locale`](https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/custom_validators.py#L73-L78) is enforcing uniqueness of synonyms across _all_ synonyms.

I have [confirmed with the OpenMRS community](https://talk.openmrs.org/t/defining-our-concept-validation-rules-for-ocl/33508/19?u=burke) that preferred synonyms (names marked as preferred in locale) need only be unique amongst all preferred names within that locale – i.e., it is valid for the same synonym to be used on another concept as long it too is not marked as locale preferred.

Please refactor [`preferred_name_should_be_unique_for_source_and_locale`](https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/custom_validators.py#L73-L78) to enforce uniqueness only amongst names marked as preferred within the same locale.

**Comment by snyaggarwal** [comment]
@bmamlin this is deployed on all environments.

**Comment by jamlung-ri** [comment]
We will close this since work has been done.
