### ISSUE TITLE
Multi-tenant Support Vision

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1074]
May include workflows, use cases, goals, and requirements etc.

This will especially involve the hybrid users i.e. Content Managers/Consumers and what they will need to be able to do.

**Comment by paynejd** [comment]
Drafting this here: [DDCC Member State Workflows Nov-2021](https://docs.google.com/presentation/d/1EAJrW87Fmb9G8Qc_czwkTBLyehY7VkfwxJtj_FjGJ3o/edit)

**Comment by jamlung-ri** [comment]
This is being drafted in the [WHO Member State Workflow slide deck](https://docs.google.com/presentation/d/1EAJrW87Fmb9G8Qc_czwkTBLyehY7VkfwxJtj_FjGJ3o/edit?usp=sharing). It will likely require some level of iteration, and we will be presenting this to various community groups for validation and feedback.
