### ISSUE TITLE
More tweaks on the concept details page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1078]
On the Concept Details page, we want a few small tweaks:

* Update the tooltip on the Associations panel to read:
  > The **Associations** section lists hierarchy and mapping associations from the same source.
* Update tooltip on the Collection Membership panel:
  > The **Collection Membership** section only lists collections under the same owner.
* (If not already done) For concept Names & Synonyms and Descriptions, grouping by locale should stay the same as it is, however sorting within each locale needs to be updated slightly. "preferred" names/descriptions should come first within each locale, next sort by name_type/description_type, and then alphabetically.

**Comment by snyaggarwal** [comment]
@paynejd This is done.

**Comment by jamlung-ri** [comment]
This seems to be working well in QA!
