### ISSUE TITLE
Add bulk import response header to indicate the status of import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#108]
Currently the only way to determine if a bulk import is still being processed is this:

```
If response is JSON and has an attribute "state"=="PENDING", then the import is still being processed
```

Would it make sense to implement a response header (or some other method) with the import status?(e.g. "status"=="PENDING" or "COMPLETE" or "ERROR"...)

**Comment by paynejd** [comment]
See #122

**Comment by snyaggarwal** [comment]
Now both get/post bulk-import APIs returns task state in response. The response has following data:
```
task - # task Id
state - task state
username
queue

**Comment by paynejd** [comment]
@sny can you describe what the values look like for "task state"?

**Comment by paynejd** [comment]
Work on this is continuing in #122 -- closing this out.
