### ISSUE TITLE
Collapsed org header

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1081]
Recent updates to the TermBrowser added support for this awesome org overview page:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/89fa53fb-46fb-4adb-b3c8-5ade5035f761)

For other tabs, we want to support a "collapsed" header, where we only show the org ID/name and the tabs, using the header's background color (instead of the image).

Moving forward, we'd like to create a default "Overview" tab for all orgs that has an expanded header, and default to collapsed headers for all other tabs -- this is the same behavior as GitHub. If it's easier, we can go straight to this behavior (which means not creating new configuration options) or we can start by creating collapsed headers as a configuration option.

**Comment by snyaggarwal** [comment]
@paynejd first or text type or about type tabs will have expanded header and rest of the tabs will have collapsed header.
It will be much better if we make the Overview tab for every org.
Do try it out and let me know the feedback

**Comment by jamlung-ri** [comment]
It looks like this is deployed on QA. See here: https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
Yeah, we can close this. It's working well in QA.
