### ISSUE TITLE
Documentation a long-term plan for FHIR implementation and updates in OCL

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1084]
Related to BMGF Output 1.1.a Document a plan for updates to OCL's FHIR service to address activities 1.1.1-1.1.4. The plan will include prioritized tickets to bring OCL's FHIR service up-to-date, align information models, improve compatibility with HAPI FHIR's implementation, and address reported backlog of FHIR-related tickets. The plan will be reviewed with the broader community to ensure alignment on priorities.

Expected Deliverable: Draft a document or spreadsheet that describes planned work on the OCL FHIR service and on FHIR capabilities to be added to the TermBrowser Connectors from Nov-2021 thru Apr-2022, and possibly beyond. This will include requirements based on FHIR v4.0.1 specification, SVCM IHE Profile, WHO DDCC, alignment with HAPI FHIR, alignment of OCL's information model with OCL's FHIR service, and other requirements from the community.

Related to DDCC Output 1.4.1: Documentation of required FHIR terminology capabilities to support DDCC drafted in collaboration with the WHO DDCC project team. It is expected that requirements will be addressed in multiple phases, and that not all requirements will be considered within the scope of this award.

**Comment by paynejd** [comment]
Being drafted here: https://docs.google.com/document/d/1yNM08N1pWFmWfUe7EoSkXRJIH__0Q78e6lEoDObbUjM/edit?usp=sharing
