### ISSUE TITLE
$cascade Operation MVP

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1088]
This ticket captures just the MVP version of $cascade -- additional tickets will be created to capture advanced functionality

**Comment by paynejd** [comment]
Proposed MVP scope for $cascade operator:
* Cascade one level of concepts and mappings, using only mappings (not hierarchy, and not recursive)
* Cascading Method: sourceMappings and sourceToConcepts
* Map type filtering (inclusion or exclusion)
* Use a response format that supports multiple resource types, like FHIR Bundle
* Implement basic pagination with a default sorting

Out of scope:
- Search (not clear if we’ll implement this later)
- Resource type filter
- Filter: omitIfExistsIn=/org/foo/collections/bar/
- Filter: equivalencyMapType=SAME-AS
- Hierarchy
- Recursion

Open questions:
* Does FHIR $subsumes operation impact MVP approach?

What's next?
* Implement ability to add references that use the cascade operator
* Implementing some of the more advanced functionality that is currently out of scope

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on all environments.
by default it will return bundle response and OCL format can be returned by using `?ocl=true`

**Comment by paynejd** [comment]
Closing this out following the demo during today's architecture call -- this is now deployed on all environments. Further work will take place in #1122
