### ISSUE TITLE
Bulk import API performance test

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#109]
Ticket to document performance results and improvements of the new bulk import API feature

**Comment by paynejd** [comment]
Please see #120 for related performance issue

**Comment by rkorytkowski** [comment]
@paynejd, do you have some bigger real life import, which you could share with me?

The one I have is only 50 resources and for such a small import I don't observe performance improvement with parallel execution either passing individual resources or in batches. I'd like to give it a try with a bigger import.

I went ahead and further profiled saving a mapping. It takes 120ms on average and more than half of that time is spent in haystack posting updates to solr in real time. Solr itself is reporting to take only a small percentage of that time so haystack must be the culprit. I need to consider our options. Either we make all haystack updates asynchronous with some celery plugin or completely switch to https://github.com/yougov/mongo-connector

**Comment by paynejd** [comment]
I just emailed a large import script.

Looks like mongo-connector supports Python v3.4+ and we're still on Python
v2.7 :(

I've read that Haystack is notoriously slow too.

**Comment by paynejd** [comment]
Closing this for now
