### ISSUE TITLE
ConceptMap attribute support

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1096]
Some attributes from the DDCC content appear to not be imported properly:
 - [ ] _Source/Target Canonical attributes_ -  DDCC ConceptMaps have two attributes that OCL does not seem to import: `sourceCanonical` and `targetCanonical`
 - [x] _url attribute_ - DDCC's capitalization within the URL attribute seems to be lost when importing into OCL The characters are the same, but the DDCC url capitalizes while the OCL FHIR resource url is all lowercase

**Comment by paynejd** [comment]
this already is covered in the OCL FHIR Core work, so closing htis out
