### ISSUE TITLE
FHIR Capability Planning Document for DDCC

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1097]
Related to DDCC Output 1.4.1: Documentation of required FHIR terminology capabilities to support DDCC drafted in collaboration with the WHO DDCC project team. It is expected that requirements will be addressed in multiple phases, and that not all requirements will be considered within the scope of this award.

**Comment by paynejd** [comment]
Documenting this here: https://docs.google.com/document/d/1yNM08N1pWFmWfUe7EoSkXRJIH__0Q78e6lEoDObbUjM/edit?usp=sharing

**Comment by paynejd** [comment]
This is being captured in #1084. Closing this out
