### ISSUE TITLE
Implement versioned releases for ocl api and web

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#110]
We currently do not have versioned releases for OCL, and this is as good of a time as any to implement that. What would be involved in implementing semantic versioning for both repositories?

**Comment by rkorytkowski** [comment]
Initially we need:
1) Add a build version variable to both API and WEB projects.
2) Set the build version variable when building on CI.
3) Add a new API endpoint to fetch the API version.
4) Display the API and WEB version in UI (maybe in the page footer?).

In separate issues later down the road:
1) Save the API version in db to be able to handle db updates. Apply db updates based on version of code and previous version value written to db.
2) Validate WEB version is compatible with API version. We can base it on e.g. semantics and require that given API x.y.z and WEB x.y.z that x and y must be equal to work together.
3) Introduce a policy and provess for maintenance branches and back porting.

**Comment by paynejd** [comment]
See https://github.com/OpenConceptLab/oclapi/wiki/Release-Notes

**Comment by paynejd** [comment]
cc @rkorytkowski @snyaggarwal @harpatel1 

Can we address these items in the `oclapi2` and `oclweb2` refactor? And create tickets for any remaining activities that we will do following launch?

**Comment by snyaggarwal** [comment]
Lets discuss this in upcoming architecture call

**Comment by rkorytkowski** [comment]
Addressed in referenced issues. We will be creating maintenance releases only for the latest minor version for now so we don't need separate branches for releases yet.
