### ISSUE TITLE
OCL FHIR vs. HAPI FHIR Gap Analysis

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1102]
Related to BMGF Output 1.2: Gap analysis comparing OCL's FHIR service with the HAPI FHIR implementation. The focus of the gap analysis will be on identifying API capabilities required to provide a consistent user experience within the OCL TermBrowser.

This will start as a requirements-level comparison, and we can do a functional comparison later. Once more implementation has been done, we can transition this over to @rkorytkowski.

**Comment by paynejd** [comment]
This is under development here: 
https://docs.google.com/spreadsheets/d/1uP6U50wzKjb_AimO_53zV1gHh383I-n6sybCeBoiuWU/edit#gid=1044086070

**Comment by jamlung-ri** [comment]
This is complete for now but will be brought up again in the future.
