### ISSUE TITLE
Plan for OpenMRS Dict Mgr/OCL TermBrowser integration

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1106]
Related to BMGF output 6.1: Draft plan for improved OpenMRS Dictionary Manager integration with the OCL TermBrowser and Terminology Service. This plan will be developed in direct collaboration between the OCL, OpenMRS and OpenHIE communities.

**Comment by paynejd** [comment]
https://docs.google.com/document/d/1BNSM9voz-5drPJRupSrm_jCp1ZT-M5lEeumdezuduZc/edit#
