### ISSUE TITLE
500 error when attempting to retrieve concepts under a logged in user's collection

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#111]
According to the api wiki [here](https://github.com/OpenConceptLab/oclapi/wiki/collections#list-concepts-referenced-in-a-collection)

I believe this endpoint `GET /user/collections/:collection/[:collectionVersion/]concepts/` is meant to retrieve concepts in a collection under a logged in user.
Hitting it with a correct token for returns a `500` though.

![image](https://user-images.githubusercontent.com/12200860/57289495-29e0a580-70c4-11e9-8e38-8ffd23a0cca0.png)

**Comment by paynejd** [comment]
@snyaggarwal Can you confirm that this issue is addressed in oclapi2?

**Comment by snyaggarwal** [comment]
Already Fixed in oclapi2
