### ISSUE TITLE
Loaded dictionary into OCL needs to support concept complex handler

### ISSUE THREAD

**Issue by mseaton** [OpenConceptLab/ocl_issues#1114]
We have several Concepts in our PIH dictionary that are configured with datatype = "Complex".  For such Concepts, these are ConceptComplex subclasses of Concept, and like the ConceptNumeric subclass, have an extra property that needs to be maintained - this is the ConceptComplex.handler (concept_complex.handler) property.

We need to add the necessary capabilities to the import tool to store this in the extras of an imported Concept where appropriate.

@bmamlin FYI

**Comment by mseaton** [comment]
@bmamlin - I was hoping to complete the subscription module aspect of this feature.  Can I assume that the name of the property in extras will be "handler"?  If not, can you let me know what you choose for this?

**Comment by bmamlin** [comment]
The `ocl_omrs` import tool [now supports concept complex handler](https://github.com/OpenConceptLab/ocl_omrs/commit/bb7569287b3d0d7bf78dc0283da343e6011e2e92). The handler for complex concepts will be stored in a `handler` property within `extras` on OCL.
