### ISSUE TITLE
Retiring a concept not working with DELETE endpoint

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#112]
Please request for more details if necessary, but basically the gist of this issue is attempting to retire a mapping via the `DELETE` endpoint([Retire Concept](https://github.com/OpenConceptLab/oclapi/wiki/concepts#retire-concept)) does returns the same concept without retiring it

Using the update endpoint with a logged in user([Edit Concept](https://github.com/OpenConceptLab/oclapi/wiki/concepts#edit-concept)) with `retired` set to `true` properly retires the concept.

**Comment by paynejd** [comment]
Note #323 -- we will close this ticket and move all future work related to this ticket there.
