### ISSUE TITLE
$cascade operation round 2, incl. recursion

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1122]
Following up on #1088, the next round of work on the $cascade operator will support recursion and hierarchy, and will improve alignment with FHIR.

* Add ability to cascade a concept's hierarchy in addition to mappings -- this will be enabled by default, and the user can control it with the `cascadeHierarchy=true|false` parameter
* Add option for the user to control whether mappings are cascaded -- this is enabled by default: `cascadeMappings=true|false`
* Add option to exclude mappings from the list of resources returned, eg `includeMappings=false`
* Add option to exclude map types, eg `excludeMapTypes=SAME-AS` -- note that this parameter should be ignored if `mapTypes` parameter is present
* Add ability to recursively walk thru a concept's hierarchy and mappings
  * User should have the option to limit the number of levels -- eg `cascadeLevels=0` is the current behavior of no recursion; `cascadeLevels=1` goes to the next level; `cascadeLevels=all` or `*` means do all levels and should be the default behavior
  * Recursion needs to prevent infinite loops, eg. if a concept has already been processed, then don't process it again
  * Recursion should apply the same mapType filters

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA

**Comment by paynejd** [comment]
This query returns 211 resources:
* https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/159615/$cascade/?cascadeLevels=1

These two queries (just including/excluding the same map types) should return a total of 212 resources, right? (Because both are going to include the original concept) But the first one is 173 and the second one is 4, for a total of 177 resources.
* https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/159615/$cascade/?cascadeLevels=1&mapTypes=CONCEPT-SET,Q-AND-A
* https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/159615/$cascade/?cascadeLevels=1&excludeMapTypes=CONCEPT-SET,Q-AND-A

What is causing the mismatch?

**Comment by paynejd** [comment]
@snyaggarwal walked us thru an analysis of cascade recursion that showed that the results above were actually correct. See the image below-- we'll want to add a similar diagram to our documentation. Closing this out and further work will take place in #1131 

![image](https://user-images.githubusercontent.com/1189689/144437527-95978afe-5c60-4fc8-ad2e-d1e7ee4e843a.png)
