### ISSUE TITLE
[UI] Big Source/Collection Async DELETE request

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1128]

**Comment by bmamlin** [comment]
If it helps, from a user experience perspective, after manually re-entering the name of the source/collection to confirm deletion (as the UI currently supports), I would expect the source/collection to appear as "getting deleted", for example:
> <s>Name of Source or Collection Here</s> <kbd>Deleting...</kbd>
with most actions on the source/collection disabled or hidden altogether while its in this state. Once the deletion has completed, the source/collection would disappear altogether.

**Comment by snyaggarwal** [comment]
> If it helps, from a user experience perspective, after manually re-entering the name of the source/collection to confirm deletion (as the UI currently supports), I would expect the source/collection to appear as "getting deleted", for example:
> 
> > Name of Source or Collection Here Deleting...
> 
> with most actions on the source/collection disabled or hidden altogether while its in this state. Once the deletion has completed, the source/collection would disappear altogether.

In addition to the above, the API can decide whether it needs to do async or sync delete based on the count of resources it has. (Async if more than 100?)

**Comment by snyaggarwal** [comment]
More conversation in #661

**Comment by snyaggarwal** [comment]
This is done.
By default its async and we wait for 15 seconds for it to finish otherwise return task id.
