### ISSUE TITLE
Talk with the LOINC team with LOINC demo in Staging

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1129]
Next step on this is to talk with the LOINC team, where we can walk them through LOINC in OCL Staging. We will want a sort of demonstration of how countries would be using this content.

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/1043#issuecomment-974184535_

**Comment by paynejd** [comment]
Tracking this separately
