### ISSUE TITLE
Support "extras" for the mapping resource

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#113]
We need to support the "extras" functionality for mappings in the same way that we do for concepts.

I understand that extras are added just by extending an underlying object in the code (because concepts, sources, collections, and orgs all use it).

**Comment by paynejd** [comment]
@snyaggarwal Did you already implement `extras` support for `mappings` in oclapi2?

Note that no additional work will be done on extras for mappings in oclapi1

**Comment by snyaggarwal** [comment]
implemented.
