### ISSUE TITLE
Add ability to view more than 10 filter options

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1130]
When searching (global or within a specific source/collection), the "More Filters" panel is limited to displaying 10 options per facet. Where possible, we want to add an option to display more options. This will be most useful for "Concept Class", "Datatype" and "Map Type", though it could be helpful for others as well.

For example, it is not possible to use filters view only CIEL concepts of class type "Q-AND-A" or "CONCEPT-SET" using the TermBrowser because neither is in the top 10.

Suggest adding a "More" or "See more options" link underneath the list.

 ![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/2b7d0e26-26ea-463a-9dcb-bad1069d69aa)

**Comment by snyaggarwal** [comment]
@paynejd I checked this and this is a [default size limit by ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-size).
We can increase the limit per attribute, like show top 20 `concept_class` and top 15 `datatype`, but we can't do all.

**Comment by jamlung-ri** [comment]
@snyaggarwal Is it possible to attempt this in this sprint? I wonder if the approach here is to increase the limit for the filtering attributes in the API, but only show the top 10 until the user clicks a "See more" option. Or something like that? If there was a more dynamic way, then that'd be ideal, of course, but if ES won't allow it, then we might have to find a workaround.

**Comment by paynejd** [comment]
v3
