### ISSUE TITLE
Ability to get concept / mappings from a source that are not part of a collection

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#1132]
This is a follow-on from #728.

The requirement, as spelled out there are:

* I should be able to get concepts from a source that are already part of a given collection
* I should be able to get concepts from a source that are not part of a given collection

This was implemented by two search parameters: `collection` and `collectionOwnerUrl`. The combination of `collection` and `collectionOwnerUrl` theoretically should describe a single collection.

However, the problem we've run into [as outlined here](https://github.com/OpenConceptLab/oclapi2/commit/a846b87f9b8b257afc23e1827f4c6728dd787e3a#commitcomment-56402765) is that these two search parameters are combined as individual filters so:

`collection=!Ian's Test` excludes any collection named "Ian's Test" and `collection_owner_url=!/users/ibacher` excludes any collection owned by /users/ibacher.

If I want to exclude only those concepts in the "Ian's Test" collection, I might try to query a source like so: `/concepts?collection=!Ian's Test&collection_owner_url=!/users/ibacher`.

What I'm trying to express is "exclude the concepts from the collection named Ian's Test owned by ibacher", but what this is interpretted as is "exclude the concepts from any collection named Ian's Test or any collection owned by ibacher".

It would be helpful if we could either have these parameters combined or a new paramter, say, collection_url which would allow me to ask for `collection_url=!/users/ibacher/collections/IBT` (i.e. any concepts that are not already a part of this specific collection) or `collection_url=/users/ibacher/collections/IBT` (i.e., only include concepts that are part of this specific collection.

**Comment by snyaggarwal** [comment]
@ibacher Thanks for describing the issue so well!
I will work on this and get back to you once this is done.

**Comment by snyaggarwal** [comment]
@ibacher I have added collection_url you concept/mapping indexes.
so you would be able to this by `?collection_url=/users/ibacher/collections/IBT/` to include and `?collection_url=!/users/ibacher/collections/IBT/` to exclude concepts of a collection.
For this we have to reindex all concepts/mappings in all environments.
The concepts in QA environment are reindexed and mappings are going on (at the time of writing this). You can try it out on QA and let me know the feedback here.
Will soon deploy/reindex this to other environments

**Comment by ibacher** [comment]
@snyaggarwal Thanks for the quick fix! It looks to me as though it's working as expected. Could you deploy this change to staging so we can better test it out (our UI only ever talks to staging or production)?

**Comment by snyaggarwal** [comment]
@ibacher All the environments are re-indexed. This should be available in every environment now.

**Comment by snyaggarwal** [comment]
@ibacher Can you please verify this and close this if things look ok.

**Comment by jamlung-ri** [comment]
@ibacher This fix should be deployed to Staging by now. Please feel free to reopen this ticket if there are any other issues.
