### ISSUE TITLE
Implement overview tab for orgs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1133]
Questions:
* What if there is no defined text?
* What happens to the About text?
* How do we want to apply custom configs -- e.g. currently you could configure both an Overview and an About tab (where Overview is a custom tab)
* What does it look like when you have a newly made organization without any attributes?

Proposed Approach:
* About text now shows up in the Overview tab and we get rid of the About tab
* Admins can still create other custom text tabs, mimicking the old About tab behavior
* Expanded header behavior...

Current Behavior:
* Expanded header shows up on first tab, about tab, and any custom text tabs

Note: some not-basic mockups are available [here](https://docs.google.com/presentation/d/1nkGq1Zx_SDJa-8NblyaHIr5Ot33xKWem-vyTtLjQu1k/edit)

**Comment by jamlung-ri** [comment]
Sunny has already begun development for this, so I will assign him here.

**Comment by jamlung-ri** [comment]
Some additional feedback from today's [Arch call](https://docs.google.com/document/d/157ChmfmYLGLEg_fO4cE7oMqtGpL4PchUkEhNfUUMxdo/edit#heading=h.hjpyk0o1h52x):
* When an org is created but will not get branding, configuration, or About information, we should make the page less blank. GitHub lists popular repositories if available ([OCL](https://github.com/OpenConceptLab/), for example). 
* If no repos are available, then there are just placeholders. (see screenshot) 

![image](https://user-images.githubusercontent.com/55999682/146564990-b61a33b2-b964-4471-8da9-ad33f822789c.png)

**Comment by jamlung-ri** [comment]
@snyaggarwal Given the feedback above, do you think this will be possible?

**Comment by paynejd** [comment]
A note about this:
* The Org Overview is now looking pretty good for orgs that have added some customizations. However, it's not working yet for the most basic use case. 
* >90% of orgs will not edit anything in their org page -- meaning, they've only filled out required fields, have not added about text, logo, banner, etc. they haven't pinned any repositories, and they may only have one or two members.

To wrap up the org overview, we want to make sure that things look good in all of these cases:
* As a user who is looking at an org that I am NOT a member of--
  * Org that has only required attributes, no repos/no pins, no logo, 1 member, no customizations
  * Org that has just one of the following:
    * A few repositories, no pins
    * A few repositories, with 1 or 2 pins
    * About text
    * Filled out many non-required attributes
  * Any combination of the above, plus a customized header (e.g. BG color, banner, etc.)

In general, we want to limit the number of customizations available -- we want things to look good, optionally with an org's custom branding, with as few customizations features as possible.

**Comment by paynejd** [comment]
Alignment of `Pinned` and `About` headers should be the same -- see screenshot:

![image](https://user-images.githubusercontent.com/1189689/147124413-2617260f-5b61-4a3b-9dfa-fb18151d2b55.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
Looks good in QA! Closing this out.
