### ISSUE TITLE
Add References icon

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1134]
can use font-awesome, material or https://fontello.com/ icons

**Comment by jamlung-ri** [comment]
I think it would be fine to do Iconic's Link or FA's Link (see red circles). I don't think either of them are too close to the Mappings icon
![image](https://user-images.githubusercontent.com/55999682/144068440-940af334-6a1e-4ce5-9f54-40ad562fa422.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd references icon is added and can be seen on QA environment.

**Comment by jamlung-ri** [comment]
Looks good to me!

**Comment by snyaggarwal** [comment]
This is deployed everywhere. Closing this out
