### ISSUE TITLE
Authenticated users should be able to view other user profiles

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1135]
Right now, a normal user account receives a 403 if they browse to another user's profile

Anonymous users should not be able to search or view user profiles
* This behavior should be implemented at the API-level
* The TermBrowser should disable the Users tab for anonymous users

Authenticated users should be able to search and view public user attributes and public user sources/collections (and associated pins) and membership to public organizations

@jamlung-ri @snyaggarwal Requirements to add to this?

**Comment by jamlung-ri** [comment]
Nothing else to add at the moment

**Comment by snyaggarwal** [comment]
Linked to a reported bug #1443.

This is available on QA

**Comment by jamlung-ri** [comment]
I was able to log into my personal account, search for some users, and see Rafal's profile in QA, including sources/collections. I also can confirm that the Users tab of Global Search is not appearing when I signed out. This all seems to be working fine to me.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere.
