### ISSUE TITLE
Brief documentation on how to configure errbit for OCL error reporting

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1141]
@snyaggarwal could you draft a brief list of bullet points describing how someone would configure errbit for OCL error reporting if they were installing these services on their own? And, how to disable using a separate error reporting service?

**Comment by paynejd** [comment]
Dropping in a few of the comments I've found so far...

* Configure authentication - e.g. login to Errbit via github account
* for each env, add errbit keys for each service
  * Each service will report to its own application in Errbit.
* wait for errors to occur!

add:
* list of services
* description of where errbit configuration needs to occur in the code

...

**Comment by snyaggarwal** [comment]
1. Errbit Installation:
  - Setup errbit and mongo [standalone mode](https://github.com/errbit/errbit#installation), or
  - Setup [errbit/mongo via docker ](https://hub.docker.com/r/errbit/errbit)
2. Configuring Setup:
  - Configure errbit based on your own requirements using [Errbit Configurations](https://github.com/errbit/errbit/blob/master/docs/configuration.md)
  - Couple of important ones are ERRBIT_HOST, ERRBIT_ADMIN_PASSWORD and ERRBIT_ADMIN_USER
3. Apps Setup:
  - For initial setup -- bundle exec rake errbit:bootstrap
  - Login from ERRBIT_ADMIN_USER
  - Create Apps (per service) using "Add App" button and note down the API KEY.
4. Apps/Services connecting to Errbit:
  - Errbit provides inbuild ROR support and JS support via [airbrake-js](https://github.com/airbrake/airbrake-js)
  - OCL Web (or any JS) application can use airbrake client like [here](https://github.com/errbit/errbit#javascript-error-notifications).
  - For Python3, we have a custom connector [errbitpy3](https://github.com/snyaggarwal/errbit-py3/blob/master/errbitpy3/client.py)

**Comment by paynejd** [comment]
For my understanding- could you explain briefly how we might dockerize/bundle this in a similar way that we have done with other services?

**Comment by snyaggarwal** [comment]
we are using standard errbit images:
- errbit ROR application -- docker image [errbit/errbit:latest](https://hub.docker.com/layers/errbit/errbit/latest/images/sha256-ec903bd6cfb7b6d6e3851ecc78fcfae0bbefa7d094959ae5d86f258639afff0f?context=explore)
- mongo docker image

We spin these as containers in our ECS setup. On local we can just drop this in docker-compose.yml.
