### ISSUE TITLE
Tweaks to collection version and expansion drop-down menus (in breadcrumb)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1144]
For example, in the screenshot below:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/76933f9b-ab1d-4d0a-b684-365ce338556b)

Versions Menu:
* Add "Released" label or icon to the menu (same as in other parts of the app)
* Change color of "HEAD" to gray to indicate that it is not the preferred collection version (suggest changing in other places in the app too, where applicable)
* What is the sort?

Expansions Menu:
* Add "Expansions" header in bold to the top of the drop-down menu
* Replace `(default)` with the little green default icon
* What is the current sort?

**Comment by snyaggarwal** [comment]
@paynejd The sorting on both Versions and Expansions drop down is created by desc.

**Comment by paynejd** [comment]
Few more things:
* Add "Collection Version" header to that sub-menu
* Apply same sort for versions/expansions as the Versions tab -- I think you already did this but with one exception -- `HEAD` should show up on top
* "Default" icon is not showing up in the Expansions menu
* Auto-expand icon is showing up in the breadcrumb menu sometimes when it shouldn't (see this image)
![image](https://user-images.githubusercontent.com/1189689/144857620-9c8c922a-17b0-4a7d-8343-4c48317044bf.png)
* List of expansions on the Versions tab should expand to fit the content (rather than require scrolling)
![image](https://user-images.githubusercontent.com/1189689/144858274-a67a16cc-8bf7-4345-9000-96e3e94b26e0.png)

**Comment by paynejd** [comment]
When no collection version is selected, it automatically selected "HEAD" -- but the expansions breadcrumb is empty -- can we indicate which expansion is being displayed?
![image](https://user-images.githubusercontent.com/1189689/144870272-2a4de221-82ad-4931-b57b-0d28811abb05.png)

**Comment by paynejd** [comment]
"Versions" tab should probably be renamed to "Versions & Expansions"

**Comment by snyaggarwal** [comment]
> * Auto-expand icon is showing up in the breadcrumb menu sometimes when it shouldn't (see this image)
>   ![image](https://user-images.githubusercontent.com/1189689/144857620-9c8c922a-17b0-4a7d-8343-4c48317044bf.png)

@paynejd the above is an indicator of autoexpanded true for the version. I added a tooltip for that also.

Rest of them are good, will be deployed soon

**Comment by paynejd** [comment]
Looking good! I'm confused on just one point-- in the screenshot below, there is an `X Auto Expanded` label in the header, and when I select each of the expansions, it continues to say ` Auto Expanded`. Which of the expansions is "Auto-expanded"? I think there may be confusion between "Auto-generated" and "Auto-expanded"?

![image](https://user-images.githubusercontent.com/1189689/145044651-9369492f-0f50-4491-94ea-634d2576a804.png)

https://app.dev.openconceptlab.org/#/users/paynejd/collections/JonTest/v1.0/expansions/autoexpand-v1.0/versions

**Comment by snyaggarwal** [comment]
that `X Auto Expanded` is to indicate if the collection (HEAD) is auto expanded or not. I think we should just remove it now.

**Comment by paynejd** [comment]
Final steps for this ticket:
- remove the `Auto Expanded` tag from the Collection Header -- this is now captured in the Versions/Expansions tab
- when viewing a collection- the concepts/mappings tabs only seem to work when there is a default expansion -- shouldn't these change to view the selected expansion?
- when I'm signed in as a user that does not have permission to edit a collection, I can see the "Add the first expansion for this collection version" button and I can click on it to open the New Expansion panel -- I'm assuming that I wouldn't be able to actually save a new expansion (but worth confirming this too!)

...then we can close this out

**Comment by paynejd** [comment]
Getting close...
* References tab now throws error-- see this link: https://app.dev.openconceptlab.org/#/users/paynejd/collections/JonTest/v1.0/expansions/newExpansion/references
* Remove versions drop-down on the concepts/mappings/references tabs since it is now duplicative
* The permissions issue may not be fixed yet -- is paynejd@gmail.com an admin user on dev? If yes, could we add that attribute into the user profile (only visible if it's true) so that it is easy to answer that question? If not, then my user was still able to see the "add first expansion" button here: https://app.dev.openconceptlab.org/#/orgs/WHO-DDCC/collections/DDCC-QR-Category-Usage-ValueSet/versions

**Comment by jamlung-ri** [comment]
>     * References tab now throws error-- see this link: https://app.dev.openconceptlab.org/#/users/paynejd/collections/JonTest/v1.0/expansions/newExpansion/references
This appears to be fixed.
> 
>     * Remove versions drop-down on the concepts/mappings/references tabs since it is now duplicative
> 
This change is implemented.

>     * The permissions issue may not be fixed yet -- is [paynejd@gmail.com](mailto:paynejd@gmail.com) an admin user on dev? If yes, could we add that attribute into the user profile (only visible if it's true) so that it is easy to answer that question? If not, then my user was still able to see the "add first expansion" button here: https://app.dev.openconceptlab.org/#/orgs/WHO-DDCC/collections/DDCC-QR-Category-Usage-ValueSet/versions
Looks like this issue is still there. I was able to go to that collection in a private window and see the "create first expansion" button.

**Comment by snyaggarwal** [comment]
@jamlung-ri All the issues in this are fixed

**Comment by jamlung-ri** [comment]
Looking good in Dev! Closing this out.
