### ISSUE TITLE
Implement API to return status of any task in API

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1145]
Right now we can only do this for bulk imports

**Comment by snyaggarwal** [comment]
@paynejd This is available on all environments via Swagger. Please close if all looks good.

**Comment by snyaggarwal** [comment]
Another behavior is needed here to get the result of any task by task ID. Will work on that before closing this.

**Comment by snyaggarwal** [comment]
GET /tasks/<:task_id>/ to get state and gist of task.
GET /tasks/<:task_id/result/ to get full result of the task.

**Comment by snyaggarwal** [comment]
This is deployed on QA. Closing this.
