### ISSUE TITLE
Retrieving concepts from a collection's HEAD returns some previously removed concept references

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#115]
We noticed that occasionally, attempting to remove a concept reference from a  collection does not do this, despite an OK message being returned.

Current offending concepts on the qa server;  
`"/users/admin/sources/553T/concepts/2c3e3972-8cc9-4c12-84bb-68d6b831e7ec/5cd1cf7a5ab3eb01a4855e30/"` from 553T   
and  
`/users/admin/sources/520T2/concepts/b01502a1-e3c2-4f47-a479-50b7f00e4d14/5cd2e0315ab3eb01a4856074/` from 520T2  

Endpoint: `DELETE /users/:user/collections/:collection/references/`

**Comment by Karuhanga** [comment]
After further investigation, it appears the references are indeed deleted from the collection, and hitting the references endpoint(`/users/:user/collections/:collection/references/`) reflects this.

Hitting the get collection concepts endpoint however(`/users/:user/collections/:collection/concepts/`) is what returns these already removed versions of a concept however.

I wonder if this is related to how you add a concept to a collection i.e whether or not you specified the version when adding it.

**Comment by paynejd** [comment]
Can you verify that you are not specifically requesting a collection
version? You probably already are aware of this, but the collection version
is a snapshot at a point in time and only the HEAD is modified after
updating references.

The other possibility is that the data is correctly updated but that for
some reason it is not triggering an update to the index.

**Comment by Karuhanga** [comment]
Not specifying a version points to `HEAD` right? I am not specifying a version so I would expect HEAD to reflect my latest actions.

> The other possibility is that the data is correctly updated but that for some reason it is not triggering an update to the index.

My thoughts exactly.

**Comment by paynejd** [comment]
@snyaggarwal Can you confirm that this issue is addressed in oclapi2?

**Comment by snyaggarwal** [comment]
This has been addressed
