### ISSUE TITLE
Merge Collections Expansions to master

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1164]
Prerequisite:
- [x] @paynejd to run MOH alignment script
- [x] OpenMRS running against dev for a sprint.
- [x] a showcase with OpenMRS?

**Comment by paynejd** [comment]
All prerequisites are done!

@snyaggarwal We are now unblocked to merge dev into master and deploy to QA, where we will do another round of testing before we move everything to staging.

**Comment by jamlung-ri** [comment]
I have done some testing for MER codelists, which were ported over correctly. @paynejd to do some more testing.
