### ISSUE TITLE
Add missing MapTypes to install scripts and deploy to QA/demo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#117]
`Q-AND-A` and `CONCEPT-SET` map types are missing in the default OCL deployment scripts. Can we add these in and deploy to qa and demo?

**Comment by Karuhanga** [comment]
@paynejd I wonder if [this PR](https://github.com/OpenConceptLab/oclapi/pull/550) would help with this?

**Comment by rkorytkowski** [comment]
@Karuhanga , it does fix the issue. Thanks!

**Comment by rkorytkowski** [comment]
Deployed to all environments.
