### ISSUE TITLE
Concept Class dropdown behavior change

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1170]
When trying to create a new concept in the UI, the Concept Class dropdown is difficult to use unless you already know what concept class you are looking for. Can we make it so that it automatically loads all available concept classes and shows it right away, rather than waiting for the user to type multiple characters?

Here is the behavior I am trying to fix: https://www.loom.com/share/48fed90930de490dbfe9298e61d000c5

**Comment by paynejd** [comment]
Thanks Joe! Agree with this, and it also needs to allow users to enter a
value that is not part of the dropdown menu

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Added the following:
1. Concept Class list will be populated in the dropdown.
2. Concept Class can be any free text (other than the dropdown selections) except for OpenMRS custom validation sources.

**Comment by jamlung-ri** [comment]
This is working great in QA now!
