### ISSUE TITLE
Prep MER v2.6 Reference Indicators for import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1172]
The new MER v2.6 guidance was released late 2021 here: https://www.state.gov/wp-content/uploads/2021/09/FY22-MER-2.6-Indicator-Reference-Guide.pdf

We want to move the reference indicator definitions into a spreadsheet format to load into OCL. We're using this spreadsheet: https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit#gid=2053814557

**Comment by jamlung-ri** [comment]
Thanks @paynejd! Is there a specific due date or timeline for this?
