### ISSUE TITLE
Change API version chip at bottom of TermBrowser to link to swagger

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1174]
We'd like the API version chip at bottom of the TermBrowser page to link directly to the OCL API swagger page.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri deployed on QA and DEV

**Comment by jamlung-ri** [comment]
Looks good to me! I can get to the appropriate Swagger environment for each of these.
