### ISSUE TITLE
Dev Environment Regression: GET requests for a non-existing concept return 200

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#1176]
I found this while troubleshooting a failed test for the dictionary manager.

We were relying on a feature where one could GET a concept by ID from a collection, so, e.g., https://api.openconceptlab.org/users/pwargulak/collections/CFL-test-1/concepts/167023/ returns the copy of the CIEL concept 167023 in the CFL-test-1 collection. However, in the Dev environment, this feature doesn't seem to be supported, e.g., so that https://api.dev.openconceptlab.org/users/paynejd/collections/JonTest2/concepts/28711/ actually returns the full list of concepts (as if the /28711/ part didn't exist).

This isn't a key feature for the DM, but we were using it in tests to determine whether or not a concept was already represented in a collection. Is there a better way to ask "does concept X already exist in collection Y"?

(PS I'm not very attached to the existing syntax as it seems inconsistent to refer to a concept in a collection only by its id, since multiple sources can easily define the same concept id for different concepts... I just need some way of verifying that a concept is or is not in a given collection without having to parse and expand all the reeferences)

**Comment by paynejd** [comment]
Flagging as high priority for @snyaggarwal -- suggest also creating a unit test for this for OCL API

**Comment by snyaggarwal** [comment]
@ibacher right now if you want to check if a concept exists in a collection you can do a search on references `?q=`, e.g.:
https://api.dev.openconceptlab.org/users/paynejd/collections/JonTest2/references/?q=/orgs/CIEL/sources/CIEL/concepts/114794/

I will re-instate the API to also be able to do https://api.dev.openconceptlab.org/users/paynejd/collections/JonTest2/concepts/114794/

and in case there are multiple concepts with id 114794 in the collection, you should get 409, and then you should be able to do https://api.dev.openconceptlab.org/users/paynejd/collections/JonTest2/concepts/114794/?uri=/orgs/CIEL/sources/CIEL/concepts/114794/ to resolve the conflict

**Comment by snyaggarwal** [comment]
@ibacher @paynejd this is available on DEV environment.

**Comment by paynejd** [comment]
Also want to implement endpoints to get concepts/mappings directly from an expansion

**Comment by snyaggarwal** [comment]
@ibacher can we close this one?

**Comment by ibacher** [comment]
Yes. Thanks @snyaggarwal!
