### ISSUE TITLE
source/collection summaries show zero results if the actual summary isn't available

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1179]
If a summary for a source/collection version isn't yet available, the TermBrowser displays that there are zero concepts/mappings and one version, which is incorrect -- it should instead display something to indicate that the summary is not yet available/is being loaded/etc.

See screenshot below:
![image](https://user-images.githubusercontent.com/1189689/148284805-bbf04253-5e45-4bde-bac0-101ca17f6150.png)

**Comment by snyaggarwal** [comment]
This is done and deployed on all environments. Closing this
