### ISSUE TITLE
Org Overview Quick Visual Fixes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1184]
There are some minor issues when looking at this org: https://app.staging.openconceptlab.org/#/orgs/WHO-ICD-Test
   - [x] Mouseover the WHO logo (the edit icon) on the Org Overview page has
   messed up formatting -- the logo basically disappears and the banner shows
   up. Can the Edit icon be made white in this situation?
   - [x] Org logo is squashed on the other tabs (i.e. Sources, Collections, Members)-- should maintain aspect ratio

_Originally posted by @paynejd in https://github.com/OpenConceptLab/ocl_issues/issues/814#issuecomment-1007723926_

**Comment by snyaggarwal** [comment]
@jamlung-ri 
1. changing the color of the logo edit button was not solving the problem, as we don't know when to use which color (depending on the background). For now, I have increased the opacity of the logo when hovering on it, give it a try on QA and let me know if it feels better.
2. Aspect ratio -- I have tried to shape the logo in square, try this as well on QA.

**Comment by jamlung-ri** [comment]
>     1. changing the color of the logo edit button was not solving the problem, as we don't know when to use which color (depending on the background). For now, I have increased the opacity of the logo when hovering on it, give it a try on QA and let me know if it feels better.
This is looking much better to me!

>     2. Aspect ratio -- I have tried to shape the logo in square, try this as well on QA.
The aspect ratio seems to be working well now. The logo turns out pretty small, but I don't think that's something we need to be addressing right now.
