### ISSUE TITLE
Collections in UI: Slight Changes to "Add Concept/Reference" feature

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1187]
There are a couple of quick fixes that were suggested by the OpenMRS team that would add good value when managing collections. 

- [x] Adding References: In the sidebar where you can select concepts to add to a collection, let's make it so you can either select an owner, source, concept OR you can just do a search in that window (like what OpenMRS drew up below). 
![image](https://user-images.githubusercontent.com/55999682/150134331-abe62bf2-0c87-4980-9aaa-61567f0d7a51.png)
![image](https://user-images.githubusercontent.com/55999682/150134776-38fcb263-9994-418a-8b06-19a4bf241159.png)

- [x] #1188
![image](https://user-images.githubusercontent.com/55999682/150135457-82614303-57ad-4d8d-b84d-1cb12cac5fb9.png)

@paynejd Feel free to review!

**Comment by jamlung-ri** [comment]
Looks awesome! I love where this is starting. Some issues that I am noticing:

* [ ] Error Message in Global Search: Should say "Please select at least one concept" 
* [ ] Rename buttons - here are some suggestions but not final:
    * "By Global Search" -> "Search Concepts"
    * "By URL" -> "Add Expression" (also, place this button on the right)
    * "By Resource Search" -> "Find a Source/Collection"
* [ ] I'm seeing some resources show up twice, and when selecting one, it selects both on the screen. I think this might be an indexing problem or something though since the duplicate concepts show up in the [API results](https://api.qa.openconceptlab.org/concepts/?q=&page=1&exact_match=off&limit=25&includeRetired=false&verbose=false&sortDesc=_score) too.
 
![image](https://user-images.githubusercontent.com/55999682/150349248-cc787992-51bb-4102-a97c-cb5840c157e3.png)

* (In the future?) When adding an expression, there should probably be some information about what is allowed. This might include a link to the documentation, or maybe we need a video tutorial at some point.

**Comment by snyaggarwal** [comment]
@jamlung-ri can this be closed?

**Comment by jamlung-ri** [comment]
Sure, let's close it. I'll check it in QA once it's deployed.
