### ISSUE TITLE
Ideas for new Operations panel

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1189]
FHIR supports specific operations for each type of resource -- we want to implement those in yellow in the TermBrowser UI:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/efdc9d01-b64f-4c81-a4f6-2804952ae917)

I imagine this to be a panel that pops up on the right of the screen (like the Manage Overview panel, except that it should be at the same level as the body of the page, rather than on top of it).

when viewing a source or collection, we want to add an icon to open up the operations panel pre-populated with the current namespace and source/collection version.

The panel should provide these fields:
* Namespace
  * Org/User (e.g. radio buttons)
  * Search/dropdown to select an org/user
  * Caveat: this needs to support canonical URLs too 
* Repository
  * Source/Collection (Code System, Value Set, Concept Map?)
  * Search/dropdown to select a repo
  * Version selector
* Operation:
  * Dropdown based on the selection: Lookup Code, Validate Code, Translate Code
  * Operation Parameters (we'll define this later)
* Input field, e.g. code to validate/lookup/translate
* Submit/Execute Button
* Request:
  * Option to view/copy the full request query
* Response:
  * For now, maybe just display the raw JSON output of the response?

**Comment by jamlung-ri** [comment]
I imagine this working a lot like Swagger, except there are more dropdowns instead of only text entry, and there is autofill of information based on what page you are on. Once enough information is filled out, then a results window would appear below and it would automatically scroll down to that.

There is some form logic that is required to make this work i.e. the conditions in which each field is enabled, which I am happy to work through if helpful.

Quick example mockup: 
![image](https://user-images.githubusercontent.com/55999682/150580157-9e49f7d6-0b2b-4a3a-8b07-e78821a0bebc.png)

**Comment by jamlung-ri** [comment]
I have been working through the logic and a potential layout for the Operations panel. I do still imagine this appearing a lot like Swagger. See below for the form logic and an example mockup, where you can see both an unpopulated Operations panel from the Global Search and also a pre-populated Operations panel when opening it from a source.

Flow for Operations Panel: https://docs.google.com/document/d/135GycK_fkNna0NHw85DKf0hkLjk-UU5a5BT1Gdh47xg/edit#heading=h.v8t4xdorwdtt
Framer mockup: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/FZ2ZjeV2Q

**Comment by jamlung-ri** [comment]
> Flow for Operations Panel: https://docs.google.com/document/d/135GycK_fkNna0NHw85DKf0hkLjk-UU5a5BT1Gdh47xg/edit#heading=h.v8t4xdorwdtt 
> Framer mockup: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/FZ2ZjeV2Q

These links have been updated with Access Points and an improved mockup where you select the resource before specifying the operation.

**Comment by jamlung-ri** [comment]
This should be ready for implementation, particularly on the CodeSystem $lookup and $validate-code operations.

Example $lookup operation: https://fhir.qa.openconceptlab.org/orgs/WHO-DDCC/CodeSystem/$lookup/?system=http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem&code=image

Example $validate-code: https://fhir.qa.openconceptlab.org/orgs/WHO-DDCC/CodeSystem/$validate-code/?url=http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem&code=image
