### ISSUE TITLE
"Add as Expression" button

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1191]
Following up on #1187, there is one more powerful feature that would help users to manage collections using our Dynamic References features.

When using the Add References feature, a user could do a search (maybe with one or more filters) and select all concepts with the intent of adding a single, powerful expression rather than individual expressions. A user should essentially be able to take the search query, filters, etc. or the source/collection in view and, rather than creating individual expressions, can add the query as a single reference. 

Worth noting that we can already add these expressions using the Add Expressions tab, but this would help users to construct these queries easier.

**Comment by paynejd** [comment]
A first step might be for a user to be able to optionally view the query
expression that the TermBrowser constructed based on their search. Once
we're happy with that, then we could add actions around it -- e.g. copy,
save search, add as expression, etc.

**Comment by jamlung-ri** [comment]
There is a little more to do with this, which we noted in the Arch call from 1/28/2022

**Comment by snyaggarwal** [comment]
@jamlung-ri This should be deployed on QA

**Comment by jamlung-ri** [comment]
Looks like there are some bugs, and we can probably reword the buttons a little bit.

Bugs: 

- [ ] Add as expression does not seem to be working when I first access the page i.e. no filters applied. It lets me go through the Add Mappings prompt, but then it just spins and is never able to add the reference. It eventually gives a 504 Gateway Timeout. Once I applied a filter, however, I was able to add the expression.
![image](https://user-images.githubusercontent.com/55999682/151972717-df5ca341-c3eb-446c-bd2f-2e9ef0d20f66.png)

- [ ] I was also unable to Add Selected concepts. Not sure why, but it just spins on this screen, with no prompts about Adding Mappings. It also eventually gives a 504 Gateway Timeout. 
![image](https://user-images.githubusercontent.com/55999682/151973059-e45288b9-d675-41fd-a567-241ef6151f52.png)



Button rewording and behavior change:
I think it might make more sense if the button works more like this, although we can refine it to whatever makes the most sense.
![Untitled drawing](https://user-images.githubusercontent.com/55999682/151972272-d8d07ece-b21c-473e-a8e2-bda66dcbd941.png)
In this case, if no concepts are selected, then the "Add selected concepts" option would be disabled and greyed out. If concepts are selected (and there is no available expression), then the "Add expression" option would be disabled.

**Comment by snyaggarwal** [comment]
@jamlung-ri This should all be fixed on QA

**Comment by jamlung-ri** [comment]
Cool! One more thing: 

- [ ] Implement the same `Add as Expression` button into the "Find a Source/Collection". This would allow a user to add an expression to get all concepts or mappings from a particular source or collection. This might need something to allow the user to decide whether to add a reference for concepts only, for mappings only, or for both (maybe using a nested dropdown list?).
![image](https://user-images.githubusercontent.com/55999682/152172076-94414cdb-8af1-4361-a896-5233d064c811.png)

![image](https://user-images.githubusercontent.com/55999682/152173735-f5523ea4-11a9-4ee1-a63c-26c3a10a27ef.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA

**Comment by jamlung-ri** [comment]
This is working well! One quick question: should this popup be appearing when adding an expression? I don't think it actually adds mappings, even if the boxes are checked.
![image](https://user-images.githubusercontent.com/55999682/152347574-bc4541d5-0f89-4e87-b3eb-5c0cbc4a36e3.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is something we have discuss, ideally with any expression we should/may have $cascade clubbed

**Comment by snyaggarwal** [comment]
@jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
I think so, We can do a follow-up ticket if needed for the expression $cascade.
