### ISSUE TITLE
FSN error when adding a new concept in a source

### ISSUE THREAD

**Issue by michaelbontyes** [OpenConceptLab/ocl_issues#1197]
Hi, 

It is not possible to create a concept from the Source > Add concept because of a fully specified name error:
https://take.ms/KrLXx

Thank you

@jamlung-ri

**Comment by snyaggarwal** [comment]
@michaelbontyes Thanks for reporting this. The fix is deployed on our QA environment, and will soon be propagated to all other environments.

**Comment by snyaggarwal** [comment]
this is fixed and deployed. Closing this
