### ISSUE TITLE
Outline rules for $cascade determining whether a node is "terminal"

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1198]
@snyaggarwal Please bullet point the rules used by the $cascade algorithm to determine if a node is terminal. Adding to the ticket here is fine -- We'll add this to our documentation.

**Comment by snyaggarwal** [comment]
`terminal` attribute can have three possible values, that indicates three different states:
1. `terminal=null`: the concept is not cascaded given the query params, for example when `cascadeLevels` is not `*`
2. `terminal=true`: the concept is cascaded and there are no entries for the given query params
3. `terminal=false`: the concept is cascaded and either there are entries or it's cascaded elsewhere in the same response.

For the mappings to other sources, we don't have this attribute yet.

**Comment by paynejd** [comment]
Compiling $cascade documentation in this gdoc and closing this ticket out: https://docs.google.com/document/d/1oFlY_wyDarpPdHhfrQM7vbvkDs51hV9qQrMusBQst5A/edit
