### ISSUE TITLE
New Collection URL bug

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1199]
We noticed that, when creating a new collection from the global search page, the preview URL is showing an incorrect URL for where the collection will live.

Video: https://www.loom.com/share/b08376d4000e4cf39a08f811f8573c8e

Image: 

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/6eb3c2bd-ad52-4f02-8e04-6ae89fdb0053)!

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed on QA
