### ISSUE TITLE
Speed up availability of new repository version export to under 20 seconds

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#120]
Creating a new repository version is a very slow process. This is expected for a large source like CIEL, but it takes awhile even for an empty source and for some collections. Creation of a new repo version already runs asynchronously, which is good, but there are many scripts that have to wait until a source version is done processing before it can proceed, so that they can fetch the cached export. For example, creating a new repo version with ~50 concepts and ~80 mappings takes ~90 seconds. For our import script with PEPFAR, this is now the longest running process in the import and hopefully we can get a big speed up here.

Ideally we can speed up the entire process of creating a new repo version, but at minimum we want to reduce the amount of time for an export of a new repo version to be available

The goal is to run creation of new repo version and caching of export in parallel instead of in sequence so that the export can be available even if the new repo version is still processing in the database. This will speed up availability of the cached export, which is when scripts relying on exports can proceed.

We need to review how the API reports that a version is done processing (the `is_processing` flag on a repo version) and how it notifies that an export is being processed or is ready to download to make sure that it is compatible with this change. The current thinking is this:
* Upon POST of a new repo version:
    * the `is_processing` flag for the repo version should immediately be set to `true`
    * attempting to retrieve an export of that repo version will immediately provide a `204 No Content` response indicating that the request URL was valid, but that the export is not yet ready
* The export API will respond with `303 See Other` as soon as the export is ready even if the new repo version is still being processed
* The `is_processing` flag should be modified to `false` only after processing of the new repo version is complete AND after the export is available

This behavior should be backwards compatible with all existing code, but new code can take advantage of exports being available even more quickly.

**Comment by paynejd** [comment]
@rkorytkowski Could you do a quick look at this to see if it is something that we could easily improve? It seems like this might be low hanging fruit

**Comment by paynejd** [comment]
@harpatel1 Please see updated details of this ticket and let us know if questions

**Comment by aprilcurrier** [comment]
Rolling over to next Sprint dev has not been started research on code

**Comment by aprilcurrier** [comment]
60% complete upon rollover

**Comment by harpatel1** [comment]
**Solution Approach:**
While analyzing the code it is determined that processing of new repository and the export already runs in parallel. So we have decided to reduce the import time by processing solr indexes asynchronously by utilizing the `celery_haystack` library.

**Performance measurement:**
To measure the performance I ran one of the PEPFAR's import script locally, the import script has 525 import requests and 23 export requests. I ran this import multiple times in clean state and measured the average time of import.
`Before time - 2 minute 35 seconds`
`After time - 2 minute 2 seconds`

The import time is measured by calculating the time difference between,
1. When celery receives bulk import task
2. When celery completes the last assigned task (By this time all of the solr indexes are already updated)

**Comment by rkorytkowski** [comment]
It's been deployed to QA for initial testing.

**Comment by rkorytkowski** [comment]
I haven't discovered any issues on QA. Let's test on real data on staging.

**Comment by harpatel1** [comment]
Sounds good !!

**Comment by aprilcurrier** [comment]
Harsh to look at more closely in the coming weeks

**Comment by paynejd** [comment]
Change reverted due to regression in handling of concept and mapping versions that resulted in "orphaned" resources (ie. when a newly created resource version is no longer associated with a repository's HEAD).

**Comment by paynejd** [comment]
Flagging this for @snyaggarwal --- based on results of performance testing in oclapi2, you may want to explore background processing of index updates (if you haven't already)
