### ISSUE TITLE
Select owner when creating new collection

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1200]
Currently, when creating a new collection from the Global Search, the user cannot choose who owns the new collection. In the New Collection screen, there should be a field (likely below Short Code) where the user selects who will own the collection, which is a dropdown of their username and any organizations of which they are a member.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
This is working well from the global search now!
