### ISSUE TITLE
Create a more advanced Add References to Collection panel

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1201]
1. List/confirm references to be added
2. Optionally expand a reference to display results inline i.e. Preview window?
3. Expose cascade parameters - filter map types, number of levels, hierarchy, etc.
4. Provide options on what to store – dynamic reference vs. evaluated resources, versioned/versionless, etc.
    - ability to transform to versioned references might be an immediate requirement for the OpenMRS community

**Comment by paynejd** [comment]
Tackling this topic in #1378 -- and closing this ticket out
