### ISSUE TITLE
HotJar integration in TermBrowser

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1207]

**Comment by snyaggarwal** [comment]
Starting with QA, Staging and Production

**Comment by snyaggarwal** [comment]
@paynejd Can you create a hotjar account for OCL and add me there.

**Comment by paynejd** [comment]
Created hotjar account and added @snyaggarwal and @paulsonder

**Comment by snyaggarwal** [comment]
@paynejd I need admin access to the hotjar account.

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA/Staging/Production envs.

**Comment by paynejd** [comment]
cc @paulsonder Can you test this out and let us know if it is working?

**Comment by paulsonder** [comment]
Recordings are performing as expected.

We may wish to consider how much data is cloaked in the recordings, for
example we can't currently see the publicly available content such as ID's
or filter selections, for example, but let's see how this affects any
analysis before we discuss further.

**Comment by snyaggarwal** [comment]
Closing this.
