### ISSUE TITLE
Fix language codes in the locale dropdowns

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1211]
The locale dropdowns are incorrectly listing the language codes. See screenshot below:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/cf44d1ea-bced-4dfa-99e5-e13a57ea5280)

For this one, I typed in "middle" -- each of these is incorrectly labeled as `en`:

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/d32f8f19-41d1-42c1-ba44-f7a5f2e05755)

These lists are using `concept.name.locale` when they should be using `concept.id` -- in other words, the label should be:
```
concept.names[type="Fully Specified"] [concept.id]
```

For example, this locale (https://app.openconceptlab.org/#/orgs/OCL/sources/Locales/concepts/mga/) should be included in the dropdown as `Irish, Middle (900-1200) [mga]`:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/ebfb3781-04c7-4e38-ab38-4a19365402c0)

**Comment by snyaggarwal** [comment]
@paynejd Deployed on QA
