### ISSUE TITLE
Support checksum for more efficient validation and comparison

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1213]
Currently, validation of a bulk import involves either a superficial comparison of concept & mapping counts or the slow and labor intensive task of exporting HEAD and comparing the export to the original import for any inconsistencies. Checksums on resources (concepts, mappings, sources, collections, versions) would allow validation to happen much more efficiently by performing checksums server-side and client-side and focusing efforts on where there are mismatches.

* The checksum algorithm should be explicit and well-documented, so both server and client can reliably come up with the same result.
* Properties that are volatile or internal to OCL (timestamps and internal IDs) should be omitted from the checksum.
* Concepts should also have a checksum that includes their mappings (associations), since most cases of validation will want to ensure mappings are the same for each concept.
* Ignore retired concepts or mappings
* Whenever a resource is altered (including any content of a source/collection or any mapping of a concept), the checksum needs to be recalculated.

**Comment by bmamlin** [comment]
Discussed on [18 Feb 2022 Architecture Call](https://docs.google.com/document/d/157ChmfmYLGLEg_fO4cE7oMqtGpL4PchUkEhNfUUMxdo/edit#):

> * Need a method to quickly compare 2 sets of OCL resources
> * Save a checksum for each concept/mapping version
>     * Must be done in a predictable way (e.g. so that the ordering of extras doesn’t result in a different checksum)
>     * Omit fields like timestamps - the same concept created on 2 different OCL servers should have an identical checksum
> * Save a checksum for each source/collection version using the concept/mapping version checksums
> * eTag - similar idea that helps with caching, allowing a client to quickly know if a resource has changed
> * May also need a checksum that represents a concept’s direct mappings – are the concept’s associations the same?
>     * This would rely on a generic feature to reproducibly generate a checksum from a bundle of resources
>     * Probably would ignore retired concepts/mappings
>     * This means that when a mapping is created/updated/deleted, the from checksum/timestamp for the concept would need to be updated

**Comment by bmamlin** [comment]
I've talked some more with @paynejd about this. Some additional design thoughts:

* Have one checksum for the resource and another checksum for associations (e.g., a concept would have a checksum for its own properties/metadata and a separate checksum for its mappings/children). This would allow quick validation of both the concept and mappings without the ambiguity of whether or not the resource checksum includes mappings.
* A few things are needed to create a predictable checksum:
  1. **A list of properties to exclude** (internal IDs, timestamps, etc.). Exclusion list is probably easier to maintain than inclusion list.
  2. **A deterministic way of sorting properties** for the checksum, since they would all be concatenated in this order and a md5 calculated. All properties and any lists within the properties must have a predefined/predictable/deterministic sorting order for checksums to be robust. The sort order should _not_ depend on internal values (e.g., internal OCL IDs), since checksums need to be calculated by clients _outside_ of OCL and properties & values must be able to be sorted precisely the same way outside of OCL.
  3. **Strict formatting rules.** JSON doesn't lend itself to checksums, since a single difference in whitespace can represent equivalent JSON values but result in different checksum values. Eliminating all non-required whitespace would probably be most robust (i.e., any whitespace that can be removed without changing the JSON value or validity is removed prior to calculating the checksum).

**Comment by bmamlin** [comment]
One of the tricks for calculating checksums on OCL content will be coming up with an algorithm for calculating deterministic checksums for json content. [JSum](https://github.com/fraunhoferfokus/JSum) provides a good example, but changes in the order of array elements will change the checksum. If we can assume order of array elements can be globally ignored, a [small change](https://github.com/bmamlin/JSum/commit/acb1886c52cb1ccabb65be174b26895085b0ba1d) can work without adversely affecting performance:

Benchmark results with array elements sorted (i.e., order of array elements ignored):
```
# benchmark/fixtures/medium.json (77986 bytes)
  fast-json-stable-stringify x 1,998 ops/sec ±0.55% (97 runs sampled)
  json-checksum x 569 ops/sec ±1.61% (94 runs sampled)
  json-hash x 246 ops/sec ±1.03% (90 runs sampled)
  json-stable-stringify x 1,658 ops/sec ±0.47% (99 runs sampled)
  jsum x 2,329 ops/sec ±0.48% (97 runs sampled)

  fastest is jsum

# benchmark/fixtures/small.json (456 bytes)
  fast-json-stable-stringify x 181,876 ops/sec ±0.54% (95 runs sampled)
  json-checksum x 54,776 ops/sec ±0.85% (93 runs sampled)
  json-hash x 21,592 ops/sec ±1.04% (89 runs sampled)
  json-stable-stringify x 138,476 ops/sec ±0.53% (98 runs sampled)
  jsum x 192,428 ops/sec ±0.45% (95 runs sampled)

  fastest is jsum
```

The good news here is [the algorithm is pretty straightforward](https://github.com/bmamlin/JSum/blob/master/index.js#L5-L16), so we could offer versions of the algorithm in node, Java, python, etc. for clients to reliably calculate identical checksums.

**Comment by bmamlin** [comment]
Some additional experimenting running JSum to calculate a digest from a CIEL v2022-08-14 export within a Dockerized node container:

* JSum of full export: 7.9 s (before adding extra sort to ignore array element order, it was 6.5 s)
* JSum of just concepts (`.concepts`) within CIEL export: 1.3 s

I also create another copy of the CIEL export file, changed the order of a few concepts, reordered some concept name arrays, introduced some extra random whitespace, and the JSum digest still matched the original export as expected.

**Comment by bmamlin** [comment]
The good news: I was able to recreate JSum's algorithm in Python:

```python
#/usr/bin/env python
import json
import hashlib

def _serialize(obj):
  if isinstance(obj, list):
    arr = list(map(lambda el: _serialize(el), obj))
    arr.sort()
    return '[' + ','.join(arr) + ']'
  elif (isinstance(obj, dict) and obj != None):
    acc = ''
    keys = list(obj.keys())
    keys.sort()
    acc += json.dumps(keys, separators=[',',':'], ensure_ascii=False)
    for key in keys:
      acc += _serialize(obj[key]) + ','
    return '{' + acc + '}'
  return json.dumps(obj, separators=[',',':'], ensure_ascii=False)
```

and the checksum matches native JSum (in JavaScript). The not as good news: when I test the Python version by calculating a checksum for the CIEL v2022-08-14 export file:

```python
import time
f = open('ocl-prod-ciel-v20220814.json')
data = json.load(f)
start = time.time()
s = _serialize(data)
end = time.time()
print(hashlib.sha256(s.encode()).hexdigest())
print(end - start)
f.close()
```

What native JSum (JavaScript) does in 8 seconds, takes Python 18.6 seconds.  🐌 😞

**Comment by bmamlin** [comment]
Thinking about checksum usage and realizing that we'll probably need to be able to respect ordering of lists for a few properties. For example, the ordering of supported locales for a source/collection technically matters. So, instead of blindly sorting all lists, we might need to have a way of predefined specific JSON paths that should not be sorted during checksum generation (where "sorting during checksum generation" is the way we effectively ignore ordering of lists for checksums).

**Comment by paynejd** [comment]
Itemizing some things that are in scope for this discussion:
- Checksum for a single concept version, without mappings
- Checksum for a single mapping version
- Checksum for a single concept version, with its mappings
- Checksum for a repository version
- Evaluating a diff between 2 resource versions
- Evaluating a diff between 2 repository versions

**Comment by paynejd** [comment]
**Functional requirements**
- Algorithm that can provide a checksum that can be run both inside OCL and outside (e.g. OpenMRS)
- Must be able to recreate the same checksum even if ordering of properties in the JSON is different in a way that does not change the meaning of the resource
  - Must ignore ordering of properties, except possibly for a set of matching properties that are pre-sorted
- Different types of checksums:
  - Checksum for a single concept version, without mappings
  - Checksum for a single mapping version
  - Checksum for a single concept version, with its mappings
  - Checksum for a repository version
- Checksum versions: How checksums are evaluated will change over time -- need to tag checksums with a version (i.e. a prefix) that identifies the checksum version
  - When do we need a new checksum version? If empty attributes are omitted from the checksum calculation, we could add
  - This means that we need to be smart about handling of empty values -- e.g. we wouldn't always omit `false`
- Single algorithm can process checksum for any of the resource types
- Tagging Checksums with "type" and "version"

**MVP:**
- Only input to the algorithm is the resource
- Algorithm already has a list of fields to ignore, include, sort, etc. based on the resource type
- Start with these resource types: Concept version (no mappings), Concept version (with mappings), Mapping version

**Comment by paynejd** [comment]
Pulling together examples here: https://docs.google.com/presentation/d/1MdcEIprgwFFk-owdT42R41XuFHA53CIQF4sLWEZDktk/edit#slide=id.p

**Comment by paynejd** [comment]
Closing this out -- round 2 of work on checksums happening here: #1674
