### ISSUE TITLE
Update tooltip language when adding concepts to a collection

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1214]
When adding concepts to a collection, the popup to cascade is not very clear to users. The popup and tooltip should make it more clear what will be done.

Current popup:

![image](https://user-images.githubusercontent.com/55999682/155011444-fea3084b-16a5-429e-8c10-0d07d8c56b9d.png)

This is currently being planned out [here](https://docs.google.com/document/d/1-0TJozkeNBgNP_tI_hvurqrjjAgfCsA21ZzVIhcf8AU/edit#heading=h.im7ual1b4g80), but the final language will be put into this ticket when it's ready to implement.

**Comment by jamlung-ri** [comment]
@snyaggarwal See here for the final tooltip/prompt language:

Option | Tooltip Language
-- | --
Do not cascade (default) | Add reference(s) to the selected resource(s) ONLY
Cascade to associated mappings in the same source | Add reference(s) to the selected resource(s) AND any of those concepts’ mappings (only if the mapping is in the same source as the concept)
Cascade to associated mappings and target concepts in the same source | Add reference(s) to the selected resource(s) AND any of those concepts’ mappings AND the target concepts of those mappings (only for resources in the same source as the selected resource)

The prompt should still say "Add to collection: ..." and "# selected reference(s)...", and then it should show the options listed in the table above as radio buttons instead of check boxes. Each option can have the tooptip icon, which will show the tooltip language from the table above.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
@snyaggarwal The prompt is looking really good! Looks like there might be a couple issues with the actual behavior though.

- [ ] The "Do not cascade" option is cascading to source mappings (e.g. `PUT | https://api.qa.openconceptlab.org/users/ocladmin/collections/test-joe/references/?cascade=sourceMappings`) - this is the same behavior when selecting "Cascade to associated mappings in the same source"
- [ ] (more related to the Add References screen) When I select a concept and "Add Expression" but then I close out of that and select "Add Selected" instead, it still adds the expression. See this Loom as an example: https://www.loom.com/share/8df8a86ccff444e686d91d732772675b

**Comment by snyaggarwal** [comment]
@jamlung-ri Both the issues are fixed and deployed

**Comment by jamlung-ri** [comment]
Fixed!
