### ISSUE TITLE
Create and Delete Mapping from a Concept Details page

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1217]
Currently, there is no good workflow for making a mapping from a concept that you are viewing, and then specifying which concept you want to map to. We should add an action on the Concept Details page to create a mapping, which brings up the Create Mapping pane with the Concept's details autofilled. 

Another step to this will likely be the ability to search for a concept as the target concept. Currently, you need to already know the ID for a concept that you want to include in the mapping, but we don't allow a user to do a text search to find the target concept and then autofill its details to create the mapping.

**Comment by bmamlin** [comment]
For OpenMRS users (and one of the fundamental reasons for the existence of the Dictionary Manager), it's vitally important to be able to easily edit answers and set members of a concept.

* We would expect answers (Q_AND_A mapping in the world of OCL) for concepts with datatype `Coded` and would not expect them for other datatypes.
* We would expect set members (CONCEPT-SET mapping in OCL) for concept with datatype `None` and would not expect them for other datatypes (although this convention is sometimes abused and there may be some sets that have a `Coded` datatype)
* We would expect to be able to add an answer or a set member inline – i.e., while viewing the list of answers or set members, either having an empty row for the next entry or clicking an "add" button and simply searching for a concept to add to the list without having to navigate through additional dialogs/screens.

**Comment by jamlung-ri** [comment]
I created a mockup and video, which is out for feedback with the OpenMRS squad.

https://www.loom.com/share/470b6f85ac4e4ce1ba7719ed8b6e7ba7 
https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/taSm3b7Aa

**Comment by jamlung-ri** [comment]
Thanks @gracepotma for that example! It helps to see you working through that. I think my mockup needs some work to be more digestible and easier to work through. It isn't very sensitive to OpenMRS lingo/conventions, and it could probably use a more clever way to create connections between concepts.

**Comment by jamlung-ri** [comment]
We discussed this in the OCL Arch call today, and I started writing up some ideas here: https://docs.google.com/document/d/135GycK_fkNna0NHw85DKf0hkLjk-UU5a5BT1Gdh47xg/edit#heading=h.oe7enxz2s5gn

**Comment by jamlung-ri** [comment]
Another mockup is available here: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/WVFFLrN6X

I presented this to the OpenMRS team, and it did land better, but there's still confusion when OCL combines all Associations into a single section when OpenMRS does not see Question/Answer and Set members as Associations. We wonder if there needs to be an "OpenMRS Mode" to display in a way that makes sense to them?

**Comment by jamlung-ri** [comment]
Closing out this ticket as we are putting together a new epic to represent this work. See #1359 and #1361
