### ISSUE TITLE
Synonym search not working for CIEL - index issue?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1218]
If a user wants to find this concept by searching a synonym, the concept is not appearing in the global search. Concept names should be searched when using full text search, correct?

Concept we're looking for: https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/653/

Search that does not return the desired concept: https://app.openconceptlab.org/#/search/?q=SGOT

Another quick note: custom attributes do seem to be searched when using full text search. Should that be occurring? It might be okay but just want to make sure.

**Comment by snyaggarwal** [comment]
deployed on QA. Concepts are getting re-indexed at the time of writing this.

**Comment by jamlung-ri** [comment]
Looks like the SGOT example is now working on QA. I was also able to try a couple other examples, which now work.
