### ISSUE TITLE
Implement $resolveReference API operation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1221]
See details here:
https://docs.google.com/document/d/1zrQOQBC868uRdrZA-mhzvNzsepVYFhHrMDuJU7mKRjY/edit#heading=h.phcf7wbinrvc

**Comment by snyaggarwal** [comment]
```
POST /$resolveReference/
{"url": "/orgs/CIEL/sources/CIEL/", "namespace": "/orgs/CIEL", ...} 
```

**Comment by snyaggarwal** [comment]
@paynejd Added following:
- Added OCL’s standard summary for a repo version when resolved
- Extend to work with collections
- Url can be anything supported as a collection expression – ignore codes, parameters, etc.
```
POST https://api.qa.openconceptlab.org/$resolveReference/
{"url": "/orgs/CIEL/sources/CIEL/concepts/123/", "namespace": "/orgs/CIEL/", "version": "v2021-03-12"}

{
   "reference_type": "canonical",
   "timestamp": "2022-03-01T13:12:18.919301",
   "resolved": true,
   <if resolved==true, repository version summary>
}
```

**Comment by paynejd** [comment]
Should operators (e.g. `$cascade` and `$resolveReference`) work without the trailing slash? It seems that by convention, operators often don't require the slash even if other resources do.

**Comment by paynejd** [comment]
If `version` is omitted, then this incorrectly results in `resolved: false` -- these should both resolve to CIEL's `latest` or `HEAD` -- let's discuss which on our architecture call:
```
{"url": "/orgs/CIEL/sources/CIEL/", "namespace": "/orgs/CIEL/"}
{"url": "/orgs/CIEL/sources/CIEL/"}
```

These both work as expected:
```
{"url": "/orgs/CIEL/sources/CIEL/", "namespace": "/orgs/CIEL/", "version": "v2021-03-12"}
{"url": "/orgs/CIEL/sources/CIEL/", "version": "v2021-03-12"}
```

**Comment by paynejd** [comment]
Testing the canonical URL approach with sources...

This resolves as to the latest released, as expected (Note that we are going to mimic this behavior with the relative URL method, where no version will resolve to latest released):
```
POST https://api.qa.openconceptlab.org/$resolveReference/
{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted"}
```

Specifying version with the pipe or attribute also works:
```
{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted|v1"}
{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted", "version": "v1"}
```

Suggest changing the response format slightly:
```
POST https://api.qa.openconceptlab.org/$resolveReference/
{"url": "/orgs/CIEL/sources/CIEL/concepts/123/", "namespace": "/orgs/CIEL/", "version": "v2021-03-12"}

{
   "reference_type": "relative",
   "timestamp": "2022-03-01T13:12:18.919301",
   "resolved": true,
   "result": {
        "type": "Source Version",    # or Collection Version
       <repository version summary>
    |
}
```

**Comment by paynejd** [comment]
Testing canonical & relative URL approaches with collections:
```
https://api.qa.openconceptlab.org/$resolveReference/
{"url": "http://ocl.org/ValueSet/JonTest2"}
```

**Comment by paynejd** [comment]
Provide error response if invalid `namespace`?

**Comment by paynejd** [comment]
* Consider adding an internal switch in $resolveReference that is set to resolve version-less "relative URLs" to `HEAD` that we can change to `latest` when we're ready -- note that version-less "canonical URLs" should always resolve to `latest`
* Consider adding an optional "namespace" URL parameter that overrides whatever is in the body -- this would make it easier to see how references that have namespaces already set would behave if evaluated using an alternate namesapce

**Comment by snyaggarwal** [comment]
@paynejd I have made a couple of changes:
1. If version is not specified then return latest or HEAD (if latest not there)
2. resolved version summary is nested inside "result"
3. added version type (Source Version or Collection Version)

Lets discuss the rest of them

**Comment by paynejd** [comment]
Add support for submitting several of these at once, supporting the same format as the `data` list when submitting references, e.g.:
```
[
    "/users/ocladmin/collections/JonTest2/",
    {"url": "/users/ocladmin/collections/JonTest2", "version": "HEAD"},
    {"url": "http://ocl.org/ValueSet/JonTest2|HEAD"}
]
```

**Comment by snyaggarwal** [comment]
@paynejd Added the following:
1. `namespace` to be considered only for canonical_url.
2. changed response to return requested info in `request` and `result`.
3. added `resolution_url` in response outside of `request` and `result`. This reflects the url attempted for resolution of expression. (may want to suggest a different name for this)
4. Can consider list of expressions or single expression
5. Can consider expression as string or object.
