### ISSUE TITLE
Change processing of expansions in bulk import scripts to be synchronous

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1225]
Asynchronous processing of expansions can lead to inconsistent results inside a bulk import. Here is an example bulk import script:

1. Create source
2. Create concepts
3. Create collection+auto-expansion with version-less references to those concepts
4. Update concepts
5. Create new collection+auto-expansion with version-less references to those concepts
6. Update concepts
7. Create new collection+auto-expansion with version-less references to those concepts
8. Update concepts
9. Create new collection+auto-expansion with version-less references to those concepts

The result- references will end up pointing to the latest concept version at the time of processing, rather than based on the order that they appear in the bulk import script

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA. Can we do a bit of testing on this?

**Comment by paynejd** [comment]
Tested on QA - this works perfectly!
