### ISSUE TITLE
Support JSON datatype for custom attributes in CSV bulk import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1226]
We recently added support for non-string datatypes in the CSV bulk import. We would like to support the JSON datatype for certain custom attributes.

See here for an example of the workaround that we've been using in a custom import script: https://github.com/pepfar-datim/DASH/blob/fireEngine_measure_report/src/plm_ocl_importer/import.py#L80

**Comment by snyaggarwal** [comment]
@paynejd the above link throws 404

**Comment by paynejd** [comment]
Example workaround:
```
# Process the JSON -- convert feilds with serialized JSON to actual JSON
for resource in json_resource_list:
    if resource['type'] == 'Concept' and resource['concept_class'] == 'Data Element':
        resource["extras"]["profiles"] = json.loads(resource["extras"]["profiles"])
        if verbosity > 2:
            print "data element - resource: " + json.dumps(resource)
    elif resource['type'] == 'Concept' and resource['concept_class'] == 'Category Option':
        resource["extras"]["expressions_resource"] = json.loads(
            resource["extras"]["expressions_resource"])
        resource["extras"]["expressions_questionnaireResponse"] = json.loads(
            resource["extras"]["expressions_questionnaireResponse"])
        if verbosity > 2:
            print ("category option - resource:" + json.dumps(resource))
```

**Comment by paynejd** [comment]
currently supported: ['bool', 'str', 'int', 'float', 'list’]

**Comment by snyaggarwal** [comment]
this is done on ocldev and I have tested this PLM CSV import scripts you sent. You might want to release a new version after some testing.

**Comment by snyaggarwal** [comment]
in order to apply this change the attr needs to be added like below in CSV:
`attr:<name>:<type>`

supported data types --  `['bool', 'str', 'int', 'float', 'list’, 'json']`

**Comment by paynejd** [comment]
Just pushed `ocldev v0.1.89` to pypi with support for the `json` datatype - will test as soon as it is available on QA!
