### ISSUE TITLE
Show canonical URL in source/collection header in the TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1229]
This source has a canonical URL but it is not displayed anywhere in the TermBrowser (unless you try to edit the source):
https://app.qa.openconceptlab.org/#/users/ocladmin/sources/test-joe/ 

Let's always display the canonical URL in the header if it is set -- hide it if it is empty

**Comment by snyaggarwal** [comment]
Done
