### ISSUE TITLE
Retrieving bulk import results times out for large imports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#123]
Here's one I hadn't expected! I have a very large import script with 14,701 resources. I processed it using the bulk import API as part of a larger import process. It appears that it processed successfully. However, as soon as it finished, requesting the import results times out, probably because the results object must be huge. 

```
task_id = '7633372a-4ca6-4a7c-afa4-c8e51132b7a9'
import_results = ocldev.oclfleximporter.OclBulkImporter.get_bulk_import_results(
    task_id=task_id, api_url_root=self.oclenv, api_token=self.oclapitoken,
    delay_seconds=5, max_wait_seconds=0)
```

**Comment by rkorytkowski** [comment]
Was it failing for a short result representation as well?

**Comment by paynejd** [comment]
No, just for very large results.

**Comment by rkorytkowski** [comment]
I meant did you try to request a different format of results than json for
that large import?

**Comment by paynejd** [comment]
Ah yes, that worked fine. For example, the large import file that I shared with you processed correctly, but I was unable to retrieve the full import results, which are required by the script in the next step in the process. I was able to retrieve the summary of the results however.

**Comment by rkorytkowski** [comment]
I need to introduce paging for json results...

**Comment by rkorytkowski** [comment]
@paynejd what is it that you actually need from the json results? Can we simplify the huge json? As it is now it is awkward to apply paging... Ideally, we would flatten it to be just an array of results.

**Comment by paynejd** [comment]
It would definitely be possible to simplify the structure. It's simply
serializing the contents of the OclImportResults object here:
https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclfleximporter.py#L278

You can see an example of how an import result is added to the object:
https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclfleximporter.py#L964

In terms of what data I actually use, all of it, but at different times.
The full version is needed mostly for troubleshooting, so it's good to have
that available. But when I'm processing the results in the middle of a
script, typically I only need a few attributes. Seems like we might
ultimately want to do 2 things:

1. Create a simplified results object with partial information that won't
clog up the system

2. Fix the issue with fetching full import results -- for this, we could
implement paging. Or couldn't we also implement it as a file download that
doesn't have a size limit?

If we go with paging, here is the structure of what's returned. Seems like
the general attributes would be returned every time, and then we would add
a couple more attributes indicating the current page number. We may also
want to switch the results over to an array instead of a dictionary, like
you suggested.
```
{
            'count': 112,
            'num_skipped': 3,
            'total_lines': 115,
            'elapsed_seconds': 261,
            'results': {
                        "<key_result_001>": { .... },
                        "<key_result_002>": { .... },
                        ...
            }
}
```

**Comment by rkorytkowski** [comment]
Since you may need it all I am going to try to serialize the results objects as is to json and have it stored and served instead of serializing on each request.

I'd still recommend creating a simplified version for the purpose of processing results. For that we would need yet another method in import_results to call.

**Comment by rkorytkowski** [comment]
Also do you expect the imports to be larger than what you shared with me? Flower prints task parameters by default and it loads very slowly with such big imports. We may need to limit the size of accepted json and require a zipped version for anything bigger... Similar for responses.

**Comment by paynejd** [comment]
They could definitely get larger than this. We could batch the import
requests on the client side, I suppose. Or the bulk import API could divide
the import request into multiple tasks?

Sounds good regarding defining a simplified version. I'll create a new
ticket for that, but probably won't get to it right away.

**Comment by rkorytkowski** [comment]
I've found a way to limit the output in flower so it will not be needed to limit the size of accepted json. I'll create a separate issue to do that.

**Comment by rkorytkowski** [comment]
Fixed! It should no longer time out as I made serialization to json part of the task and stored results in redis.

**Comment by rkorytkowski** [comment]
@paynejd, I've deployed it to staging for you to try.

**Comment by paynejd** [comment]
is this on the demo server too? i'd like to test a 6MB import file, but the
content is already on staging and would prefer not to delete it. Or is QA
powerful enough to handle this as well?

**Comment by rkorytkowski** [comment]
Both qa and demo are good to test it.

**Comment by paynejd** [comment]
Submitted long import on demo yesterday. Queried the import results today and receiving an exception (see below). I think the demo server may have reset in the middle of the import, so I expect this is an edge case. Want to take a quick look to make sure nothing else is going on? I'm running the import on QA now and will update here with the results.
```
{
    "exception": "None: Max retries exceeded with url: /orgs/PEPFAR/ (Caused by None)"
}
```

**Comment by paynejd** [comment]
Bulk import status on QA appears to be "stuck" with a "PENDING" status. Here's the task_id: `af291bd5-0498-40ad-948c-6e49314e0ebd-paynejd`

**Comment by rkorytkowski** [comment]
We store and send it gzipped. It is automatically unzipped by a client (Postman, browser) on the fly thanks to the Content-Encoding gzip header. Postman is not able to display such big files. Instead of trying to display the results in Postman, you can hit `Send and Download` (click down arrow next to the Send button) or use CURL. 

BTW results are stored only for 24 hours. Do we want to extend that period?

**Comment by rkorytkowski** [comment]
Celery reports status PENDING for unknown or awaiting execution tasks. Tasks for which results have been deleted are unknown. We could try to store valid task ids in memory to differentiate between unknown and awaiting execution, if it's needed. 

I've extended expire time and made celery report STARTED tasks.

**Comment by rkorytkowski** [comment]
Done. It'll be pushed to staging this week.
