### ISSUE TITLE
ValueSet CRUD

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1231]

**Comment by jamlung-ri** [comment]
Testing Log 24 May 2022:
* Goal: Load in this [valueset](https://worldhealthorganization.github.io/ddcc/ValueSet-DDCC-QR-Format-ValueSet.json):
    * Attempt 1: POST raw JSON to https://api.qa.openconceptlab.org/users/ocladmin/ValueSet/ - Outcome: `{    "date": [        "Date has wrong format. Use one of these formats instead: YYYY-MM-DD."    ,    "text": [        "Not a valid string."    ]}`
    * Attempt 2: Alter date and text fields - Outcome: 500 Error (but [ValueSet](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/DDCC-QR-Format-ValueSet/) is created)

@rkorytkowski Changes to make:

- [ ] `date` field should accept all FHIR date and datetime formats
- [ ] `text` field should accept a dictionary, not just a text string
- [ ] Determine why 500 error is returning but the ValueSet is created correctly.

**Comment by snyaggarwal** [comment]
@jamlung-ri @rkorytkowski the [version 4.0.1 of this Collection](https://api.qa.openconceptlab.org/orgs/HL7-Test/collections/account-status/4.0.1/) is pointing to HEAD's expansion as default expansion and thats why TermBrowser is failing. I have fixed TermBrowser to handle it. But API needs investigation on how a version.expansion_url was set to some other versions' default expansion.
