### ISSUE TITLE
FHIR CodeSystem CRUD

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1234]
Part of epic #1166 - this one is now deployed and ready for testing next week

**Comment by jamlung-ri** [comment]
@rkorytkowski I am testing a POST for FHIR CodeSystems into OCL, using FHIR's [account-status](https://www.hl7.org/fhir/codesystem-account-status.json). 

It seems to be failing for a few reasons. I ended up needing to add in an OCL accession ID segment, changing the value for case-sensitive to a string, and then adding properties to the codes. 

Here is the error I was getting:

> {
>     "identifier": [
>         "OCL accession identifier is required: { 'value': '/{owner_type}/{owner_id}/CodeSystem/{code_system_id}' }, 'type': {'coding': [{'code': 'ACSN', 'system': 'http://hl7.org/fhir/v2/0203'}]}}"
>     ],
>     "caseSensitive": [
>         "Not a valid string."
>     ],
>     "concept": [
>         {
>             "property": [
>                 "This field is required."
>             ]
>         },
>         {
>             "property": [
>                 "This field is required."
>             ]
>         },
>         {
>             "property": [
>                 "This field is required."
>             ]
>         },
>         {
>             "property": [
>                 "This field is required."
>             ]
>         },
>         {
>             "property": [
>                 "This field is required."
>             ]
>         }
>     ]
> }

**Comment by jamlung-ri** [comment]
[account-status-modified.txt](https://github.com/OpenConceptLab/ocl_issues/files/8475898/account-status-modified.txt)

Attaching this JSON to show what I had to modify to successfully load int he CodeSystem. [OCL link](https://api.qa.openconceptlab.org/orgs/HL7-Test/CodeSystem/)

**Comment by jamlung-ri** [comment]
CodeSystem CRUD testing log - 25 May 2022
* Goal: Load in a [WHO FHIR IG's CodeSystem](http://build.fhir.org/ig/WorldHealthOrganization/smart-core/CodeSystem-extended-content-codes.html)
    * Attempt 1: Load in [raw JSON](http://build.fhir.org/ig/WorldHealthOrganization/smart-core/CodeSystem-extended-content-codes.json) - Outcome: CodeSystem created, but no codes. Returns messages that says Datatype and Concept_class are required.
    * Attempt 2: Load in modified JSON that adds a property field for datatype and concept_class to each concept - Outcome: CodeSystem created successfully but with some gaps:
        * For each code, the `definition` field was not populated in OCL with the definition provided in the FHIR JSON.
        * The FHIR JSON's `text` and `date` fields were not carried over into OCL.

To Dos: 

- [ ] Auto-assign concept_class and datatype fields to each code when POSTing a codesystem (if not already specified, of course)
- [ ] Fix `definition` field

@rkorytkowski
