### ISSUE TITLE
Hard-code codelist filter in MSP data elements tab on staging

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1238]
The full set of code lists has 100+ options grouped by fiscal year. Selecting one of these should apply a "collection membership" filter. Ideally, we'd like to filter the list of code lists based on the value of the Period filter. For the first pass, though, this can be a static filter with just 20 or so code lists to test the functionality.

**Comment by jamlung-ri** [comment]
Use this spreadsheet: https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit#gid=1885986989

**Comment by jamlung-ri** [comment]
This has been done on Staging, although the list is long enough to take up the entire page. I wonder if we should adjust the filter dropdown to fit longer lists. Ideally, we could also include a simple text search box too, maybe once the list exceeds 10 values?

**Comment by jamlung-ri** [comment]
This work is complete, and we have noted the long filter list need in the [UI document](https://docs.google.com/document/d/1-0TJozkeNBgNP_tI_hvurqrjjAgfCsA21ZzVIhcf8AU/edit#).
