### ISSUE TITLE
TermBrowser mapping incorrectly shows concepts as not being defined in OCL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1239]
Just created a new mapping in my own source that is associating 2 CIEL concepts that are defined. However, the TermBrowser shows that these concepts are not defined. See the following:

https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/sources/test1/mappings/

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/1189689/158195466-cad8b59d-ff39-4bae-8217-904a67a4fe90.png">

**Comment by snyaggarwal** [comment]
@paynejd I am unable to reproduce this. Can you add some steps on how you created this mapping?

**Comment by snyaggarwal** [comment]
@paynejd btw, I updated these mappings (https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/sources/test1/mappings/) and they worked fine, but I still want to know how it got created. So any steps to reproduce would be helpful.

**Comment by paynejd** [comment]
I'm getting inconsistent results. When I look at the mapping in the source, it is showing up correctly (see first screenshot below). When I look at the mapping in the collection, it shows up as if the resources are not defined in OCL (see the 2nd screenshot).

The process I followed was straightforward:
* Browse to my source: https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/sources/test1/
* Click "Add Mapping"
* Form fields:
  * Mapping ID and external ID - blank
  * Map Type: "Q-AND-A"
  * from-concept:
    * from-source-URL: /orgs/CIEL/sources/CIEL/
    * from-concept-url: /orgs/CIEL/sources/CIEL/concepts/163310/
    * from-concept-name: HIV Viral load status
    * from-concept-code: 163310
  * to-concept:
    * to-source-URL: /orgs/CIEL/sources/CIEL/
    * to-concept-url: /orgs/CIEL/sources/CIEL/concepts/163723/
    * to-concept-name: In progress
    * to-concept-code: 163723


<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1189689/158611944-0f630f1f-2236-4ac1-bb41-bbd630d0e615.png">

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1189689/158612189-50647faa-6b2f-4cbf-badf-450b3938b5a2.png">
