### ISSUE TITLE
All direct concept details links in TermBrowser should display concept details

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1241]
These links only show the concept list in the source/collection:
* Collection Versioned and version-less concept details links only show the concept list:
  * https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/concepts/163310/
  * https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/concepts/163310/
* Source versioned link also only shows the concept list:
  * https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/v2021-12-15/concepts/163310/

Note that these 2 do work:
* https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/167023/
* https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/167023/5628683/

**Comment by snyaggarwal** [comment]
@paynejd This is fixed
