### ISSUE TITLE
Extras.exact api query not working as expected

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1245]
I'm trying to filter down using an `extras.exact` filter, which seems to be working well on one query but not another. I am expecting to see only `extras.Reporting+frequency=Annually` but I am seeing "Semi-Annually" appear too. 

- Working query: https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?includeExtras=true&extras.exact.Reporting+frequency=Annually&q=&page=1&concept_class=data+element&limit=100

- Not working query that includes "Semi-Annually" results: https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY21/concepts/?includeExtras=true&extras.exact.Reporting+frequency=Semi-annually&q=&concept_class=reference+indicator

**Comment by snyaggarwal** [comment]
This is fixed, deployed on QA. This needs re-indexing, currently running on QA

**Comment by jamlung-ri** [comment]
QA might not be ready yet but I wanted to note that I am currently not having luck with the queries above.

**Comment by snyaggarwal** [comment]
@jamlung-ri ya it wont work as yet since the re-indexing has not happened. Can you give me an example source where this is reproducible, I will try to re-index just that repo and test

**Comment by jamlung-ri** [comment]
> @jamlung-ri ya it wont work as yet since the re-indexing has not happened. Can you give me an example source where this is reproducible, I will try to re-index just that repo and test

The main one is the PEPFAR source linked below. Will this enable collection queries too, or does the reindexing only affect queries to the source itself?
https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/

**Comment by snyaggarwal** [comment]
both sources and collections of these concepts will be affected. I have triggered indexing for this repo.

**Comment by snyaggarwal** [comment]
@jamlung-ri I created couple of test concepts.
Query for [Annually](https://api.qa.openconceptlab.org/users/ocladmin/sources/asd/concepts/?extras.exact.Reporting+Frequency=Annually&includeExtras=true&brief=true)
Query for [Semi-Annually](https://api.qa.openconceptlab.org/users/ocladmin/sources/asd/concepts/?extras.exact.Reporting+Frequency=Semi-Annually&includeExtras=true&brief=true)

this just means that we need to re-index the existing content.
Will be doing that once we figure out why QA is running so slow.

**Comment by jamlung-ri** [comment]
This seems to be working great now! For the source that was reindexed, I am no longer seeing "Semi-Annually" when querying for "Annually". ([API link](https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?extras.Applicable%20Periods=FY21&extras.exact.Reporting%20frequency=Annually&q=&page=1&exact_match=off&limit=100&verbose=false&concept_class=data%20element&sortDesc=_score&includeExtras=true)) This can be seen in an MSP instance here: https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true if you go to Data Elements tab and change the Reporting Frequency filter to "Annually".

**Comment by snyaggarwal** [comment]
@jamlung-ri This can be closed now once we re-index all the env. I would suggest for faster processing we reindex only the repos we want. Can you let me know in staging/production, which all repos needs to re-index?

**Comment by jamlung-ri** [comment]
The affected repos are only on QA and Staging, luckily. Here's the Staging sources that can be reindexed:
* https://app.staging.openconceptlab.org/#/orgs/PEPFAR-MER/sources/MER/
* https://app.staging.openconceptlab.org/#/orgs/PEPFAR-Test10b/sources/MER/

**Comment by snyaggarwal** [comment]
@jamlung-ri Triggered re-indexing on all three sources. Will update once done.

**Comment by snyaggarwal** [comment]
> The affected repos are only on QA and Staging, luckily. Here's the Staging sources that can be reindexed:
> 
> * https://app.staging.openconceptlab.org/#/orgs/PEPFAR-MER/sources/MER/
> * https://app.staging.openconceptlab.org/#/orgs/PEPFAR-Test10b/sources/MER/
> 
> And on QA:
> 
> * https://app.qa.openconceptlab.org/#/orgs/PEPFAR-MER-FY22/sources/MER/

@jamlung-ri these are all re-indexed.

**Comment by jamlung-ri** [comment]
Everything is working well now on those sources! I think we can close this ticket out.
