### ISSUE TITLE
Draft workflow to update DASH metadata in OCL using the new Bulk Importer interface

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1248]
This process will refer to the OCL staging server - it assumes that an account `datim-admin` was already created and that the user following this process knows the credentials. This process will be finalized (especially Step 2) with the DASH team.

1. Navigate to https://app.staging.openconceptlab.org/ and sign in as `datim-admin` <img width="800" alt="image" src="https://user-images.githubusercontent.com/1189689/158821429-bc3f8d9c-9815-42a9-834a-8a6205a6f47e.png">
2. Importing new source? Updating existing? Deleting existing and importing new?
3. Open the "Apps Menu" in the top-right and select "Bulk Importer" <img width="800" alt="image" src="https://user-images.githubusercontent.com/1189689/158821669-2c8c335f-6c4c-4a8a-ac93-35033314a707.png">
4. Drag/select the DASH CSV bulk import file and click on "Upload" to queue the file for import 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/1189689/158822778-8496f42c-87aa-44a1-ab9f-65179cea25fb.png">
5. The queued import will appear in the "Existing Imports" section on the right side of the page, where you can monitor the status and view the results of the import 
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1189689/158823106-29057c02-6f02-4dc3-9559-4e7e6a31b438.png">

**Comment by pinghuangICF** [comment]
For step 2, we definitely need to update the existing source. We may need to create a new source in the case when test a new mapping while the existing source is still in use.  

Maybe we can create two sources: one for testing, one for finalized.  So only update the existing source should be sufficient (but may need to delete existing and import new source as sometimes we need to add new concepts, so need to make sure updating the existing source works for the new concepts).

**Comment by jamlung-ri** [comment]
@paynejd Please review and, if applicable, close this ticket or remove it from the Oct. 5 sprint.
