### ISSUE TITLE
Password change issue and unable to reset

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#125]
When a user changes his/her password in the OCL web app, that change does not get reflected in the OCL API. Meaning the user can then login to OCL web, but cannot login successfully using the /users/login/ endpoint at the API to get their token. For an example, look at the "pierredane" user account in production.

In addition, the feature in the api.openconceptlab.org/admin/ to reset a user's password in the Django admin interface appears to be disabled, so I was unable to fix it.

**Comment by rkorytkowski** [comment]
Deployed to qa and staging.
