### ISSUE TITLE
Fix display of OCL Mailing List signup form on OCL community site

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1252]
The alignment of the form fields on the mailing list sign up got jumbled at some point! This is happening on the home page and on the mailing list signup page. Hopefully a quick fix...

On home page...
<img width="506" alt="image" src="https://user-images.githubusercontent.com/1189689/158842848-ee460d96-36e7-476d-843c-7613fc4ba295.png">

On sign-up page...
<img width="745" alt="image" src="https://user-images.githubusercontent.com/1189689/158844931-1f4c2e03-7962-424f-8a2f-5babf9acb6a5.png">

**Comment by kaalcumm** [comment]
Added to clickup
