### ISSUE TITLE
Display 2-3 blog entries on OCL home page and change "BLOG" heading into a link

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1253]
The "BLOG" section on the OCL homepage lists a single blog entry. Now that we have a lot more blog posts and many more in the works, we'd like this section to list 2 or 3 blog entries. We may want to reduce the length of each summary so that it doesn't get really large.

Also- do blog posts support an explicit summary that would be displayed here instead of a truncated form of the body of the blog post?

Finally, we'd like to make the "BLOG" heading clickable to take users to the main blog page.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1189689/158843438-bb887d5c-6c3a-4a1b-9275-e015f9964af3.png">

**Comment by kaalcumm** [comment]
Added into clickup to complete
