### ISSUE TITLE
Create "Getting Started" custom tab on MSP page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1256]
Use an adapted version of the content in the Summary, Metadata Sources, and Glossary sections of the draft MSP Metadata 2022 Report:
https://docs.google.com/document/d/1OltLAko205oIR35cgsDUxTKPhjV4MFJlq1eusAbxL5U/edit#

**Comment by jamlung-ri** [comment]
@paynejd See here for the first draft of this tab: https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/get-started?configs=true

**Comment by jamlung-ri** [comment]
Updating this with the latest MER Metadata Report

**Comment by jamlung-ri** [comment]
This is complete for FY22!
