### ISSUE TITLE
Add support for "update_comment" field in bulk import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1258]
We are starting to use the `update_comment` field in import scripts, but that field is not yet supported in the bulk importer.

**Comment by snyaggarwal** [comment]
Added this and deployed on QA.

**Comment by paynejd** [comment]
is this one in staging now?

**Comment by paynejd** [comment]
the `update_comment` did not seem to be loaded correctly in the `PEPFAR-MER-FY22` source -- see here: https://app.staging.openconceptlab.org/#/orgs/PEPFAR-MER-FY22/sources/MER/concepts/TX_CURR/

**Comment by snyaggarwal** [comment]
@paynejd the file you sent me dint have any "update_comment" field. Can you please re-check the import script you mailed.

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?
