### ISSUE TITLE
Performance | Repo HEAD to not contain all resource versions.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1262]

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd One Source HEAD on QA is migrated --
https://app.qa.openconceptlab.org/#/orgs/National-Library-of-Medicine-NLM-/sources/RXNORMR/

Please take a look (there shouldn't be any difference)

**Comment by jamlung-ri** [comment]
@snyaggarwal I have done a spot check of about 10 concepts, and then I did a version export and validated that using the script. Everything seems good.

Next step is to migrate a more complicated source with concept versions: [SNOMED in QA](https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/concepts/). Here is an example concept that has multiple versions: https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/concepts/767524001/ 

After that, we should create a more complicated source with lots of concept versions and source versions, and then we can update that.

**Comment by snyaggarwal** [comment]
@jamlung-ri https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/ is migrated

**Comment by snyaggarwal** [comment]
@jamlung-ri Yes thats good

**Comment by paynejd** [comment]
ready to apply to all of QA?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Applied on all Sources in QA.

**Comment by snyaggarwal** [comment]
@paynejd Is it ok to apply this on entire Staging?

**Comment by paynejd** [comment]
Let’s do it!

**Comment by snyaggarwal** [comment]
@paynejd Triggered on Staging

**Comment by jamlung-ri** [comment]
Need to do testing on this, probably verifying some sources on Staging next week

**Comment by snyaggarwal** [comment]
@paynejd This is deployed everywhere. Closing this out
