### ISSUE TITLE
Unable to retire mappings through app on staging

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1266]
While releasing CIEL v2022-03-19 on staging, I discovered a [couple dozen duplicate mappings](https://github.com/OpenConceptLab/ocl_issues/issues/1257#issuecomment-1075488390). When I tried to retire these mappings manually through the OCL app, I got a "Something bad happened" error. Initially, I thought this was related to recent performance issues on staging; however, further investigation reveals there's a small bug in the UI:

When retiring a mapping through the UI on staging, the app issues an incorrect DELETE request, resulting in a 405 error.

For example, while viewing `/orgs/CIEL/sources/CIEL/mappings/1170682/` on staging, select Manage > Retire Mapping, enter "duplicate" for the reason, click the OK button, and the app incorrectly issues a DELETE on `/` instead of the mapping's URL.

**Comment by snyaggarwal** [comment]
Fixed. Deployed on QA. Will be deployed to Staging soon.

**Comment by snyaggarwal** [comment]
this is fixed and deployed. Closing this.
