### ISSUE TITLE
ES not catching up with DB on Staging

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1268]
It appears that the TermBrowser on Staging is not immediately being updated upon deleting concepts from a collection. The collection in question is this one owned by ocladmin on Staging: https://app.staging.openconceptlab.org/#/users/ocladmin/collections/test1/concepts/

As shown in the video below, references were deleted from the collection, but the deletions do not seem to be happening on the Concepts tab. After some investigation, it seemed like those changes appeared in the [database ](https://api.staging.openconceptlab.org/users/ocladmin/collections/test1/HEAD/expansions/autoexpand-HEAD/concepts/)(e.g. without q=) but not in [Elastic Search](https://api.staging.openconceptlab.org/users/ocladmin/collections/test1/HEAD/expansions/autoexpand-HEAD/concepts/?q=) (e.g. with q=).

See this video, starting at 36:23 - https://iu.mediaspace.kaltura.com/media/t/1_783f19k7

**Comment by snyaggarwal** [comment]
@jamlung-ri Reindexing that expansion did fix the API response (same as DB now).
I am debugging this. Will update soon.

**Comment by snyaggarwal** [comment]
This should be fixed now.

**Comment by snyaggarwal** [comment]
This is deployed on all environments. Closing this
