### ISSUE TITLE
Mappings and Concepts forms not allowing IDs that end with "s"

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1273]
Seems like the Create and Edit Mappings forms in the UI are not allowing To Concept Code values that end with the letter "s". I recorded this behavior in Loom: https://www.loom.com/share/a93918e705c548198f299770d2966c16

This is happening in this source: https://app.qa.openconceptlab.org/#/orgs/NHDD/sources/eCHISDataElements/mappings/

This is also occurring when trying to or edit a new concept that ends with s - see screenshot:
![image](https://user-images.githubusercontent.com/55999682/162276778-8c75bb18-72b6-4fba-b419-ba7f30b1fc48.png)

**Comment by snyaggarwal** [comment]
Fixed and deployed on QA and Staging

**Comment by jamlung-ri** [comment]
This part appears to be fixed, although it might have caused another issue (or at least it led me to discover another one). When editing concepts, I open up the Edit Concept pane and the English locales for the names are not populating by default, so any concept I try to edit required that I reinput the locale on the name. Seems like this is happening with description's locale too.

Example using [this concept](https://api.qa.openconceptlab.org/orgs/NHDD/sources/eCHISDataElements/concepts/fp_new_at_30_to_49/):  
![image](https://user-images.githubusercontent.com/55999682/162433446-6c99624b-9d1f-4abe-80bb-444e979d5bb1.png)

**Comment by jamlung-ri** [comment]
Okay, I can create another ticket for this so we can track it separately. Otherwise, closing this ticket out!
