### ISSUE TITLE
Implement expanded collection references & support for canonical URLs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1275]
Global $resolveReference operation was implemented in #1195 -- Now we want to use the $resolveReference operation to begin supporting canonical URLs as collection references using a new "expanded reference syntax", in addition to supporting the current "inline reference syntax".

Examples:
* Inline reference syntax: 
```
"/orgs/CIEL/sources/CIEL/v2021-03-12/concepts/?datatype=Numeric"
```
* Expanded reference syntax: 
```
{“url”: “http://hl7.org/fhir/CodeSystem/my-codeystem”, “version”: “0.8”, “code”: “1948”, “namespace”: “/orgs/MyOrg/”}
{“url”: “/orgs/CIEL/sources/CIEL/”, “version”: “v2021-03-12”, “code”: “1948”, “namespace”: “/orgs/CIEL/”}
```

**Comment by snyaggarwal** [comment]
current options for submitting references:

1. `{"data": {"expressions": [...]}}`
2. `{"data": {"concepts": [...], "mappings": [....]}}`
3. `{"data": {"uri": "/orgs/MyOrg/sources/MySource/", "concepts": "*", "mappings": "*"}}`

@paynejd we need to talk about how (and how much) do we want to keep things backward compatible?

**Comment by paynejd** [comment]
* Supporting older formats:
  * Pre-process--> Convert old formats to a new format and then process
    * Cascade request parameter should be converted to a field in a reference defaulting to parameters that mimic the old behavior -- 1-level only to `sourcemappings` or `sourcetoconcepts`
  * Support 2 parsers-- old and new style
* Need a method to summarize a reference:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1189689/165751927-291f54f5-e07a-4a3b-9ac4-38df36263c72.png">
* cascade parameters represetned as a reference

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri this is deployed on QA

**Comment by snyaggarwal** [comment]
Some of the rules for expression syntax:
1. expression needs to be a dictionary object `{....}` always
2. expression needs to be inside "data" key -- `{"data": ...}`


Some examples for valid reference expressions:
```
{"data": {“url”: “http://hl7.org/fhir/ValueSet/my-valueset|0.8”, “code”: “1948”}}

{"data": {
  “system”: “http://hl7.org/fhir/CodeSystem/my-codeystem”,
  “version”: “0.8”,
  “namespace”: “...”,
  “filter”: [
    {
      “property”: “datatype”,
      “op”: “=”,
      “value”: “Numeric”
    }
  ],
  “valueSet”: [
    “http://hl7.org/fhir/ValueSet/my-valueset1”,
    “http://hl7.org/fhir/ValueSet/my-valueset2”
  ]
}}

{"data": {
  “system”: “http://hl7.org/fhir/CodeSystem/my-codeystem”,
  “code”: “1948”
}}

{"data": {
  “system”: “http://hl7.org/fhir/CodeSystem/my-codeystem”,
  “concept”: [
    {“code”: “1948”, “display”: “abcd”},
    {“code”: “1234”}
  ],
  “mapping”: [“93”, “urjdk”]
}}

{"data": {
  “system”: “http://hl7.org/fhir/CodeSystem/my-codeystem”,
  “filter”: [...]
}}

{"data": {
  “valueSet”: “http://hl7.org/fhir/ValueSet/my-valueset1”,
  “code”: “1948”
}}

{"data": {
  “valueSet”: “http://hl7.org/fhir/ValueSet/my-valueset1”,
  “filter”: [...]
}}

{"data": {"expressions": ["/orgs/MyOrg/sources/MySource/v1/concepts/1984/"]}}

{"data": {"expressions": ["/orgs/MyOrg/sources/MySource/concepts/1984/6745/"]}}

{"data": {"uri": "/orgs/MyOrg/sources/MySource/<?version>/", "concepts": "*", "mappings": "*"}}

```

**Comment by jamlung-ri** [comment]
I'm doing some initial testing in [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing2/), and I am getting mixed results. No syntax issues so far though, which is good. It seems like the Source/CodeSystem references are resolving correctly, but Collection/ValueSet references are not. See below for the references I am adding via Swagger:

* Outcome - Reference added but does not resolve correctly:
    * `{"data": {"url": "http://hl7.org/fhir/account-status", "code": "unknown"}}`
    * `{"data": {"url": "http://hl7.org/fhir/account-status", "code": "unknown", "version":"4.0.1"}}` (note that this one added two of the same concept. Not sure why, but it might be FHIR related since I loaded this CodeSystem via the old FHIR service.)
    * `{"data": {"system": "http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem", "code": "pdf"}}`
* Outcome - Reference added but not resolved:
    * `{"data": {"valueSet": ["http://joe.aml/testjoe14apr22"]}}` (pointing to [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/testjoe14Apr22/))
    * `{"data": {"valueSet": ["http://worldhealthorganization.github.io/ddcc/ValueSet/DDCC-QR-Format-ValueSet"]}}` (pointing to [this collection](https://app.qa.openconceptlab.org/#/orgs/WHO-DDCC/collections/DDCC-QR-Format-ValueSet/))
    * `{"data": {"valueSet": "http://worldhealthorganization.github.io/ddcc/ValueSet/DDCC-QR-Format-ValueSet", "code": "pdf"}}`
    * `{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric"]}}`
    * `{"data": {"uri": "/users/ocladmin/collections/testjoe14Apr22/", "concepts": "*"}}`
* Reference is not added, returns error
    * `{"data": {"url": ["http://worldhealthorganization.github.io/ddcc/ValueSet/DDCC-QR-Format-ValueSet"]}}`

**Comment by snyaggarwal** [comment]
@jamlung-ri Few more bugs resolved related to valueset resources resolution. I have tested the valid expressions and its working fine now
@jamlung-ri I can see that this resolved correctly:
`{"data": {"system": "http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem", "code": "pdf"}}`

These are invalid expressions:
- `{"data": {"url": "http://hl7.org/fhir/account-status", "code": "unknown"}}` should be `{"data": {"valueset": "http://hl7.org/fhir/account-status", "code": "unknown"}}`
- `{"data": {"url": "http://hl7.org/fhir/account-status", "code": "unknown", "version": "4.0.1"}}` should be `{"data": {"valueset": "http://hl7.org/fhir/account-status|4.0.1", "code": "unknown"}}`
- `{"data": {"uri": "/users/ocladmin/collections/testjoe14Apr22/", "concepts": "*"}}` is an old style expression used only for source concepts/mappings all, its not valid for collections.
- `{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric"]}}` missing trailing `/` should be `{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric/"]}}`

**Comment by paynejd** [comment]
Renamed this ticket to better capture all the work on the expanded reference syntax and bumped this up to 40 points

**Comment by jamlung-ri** [comment]
@snyaggarwal Those issues from above are mostly fixed.

One other issue I am seeing:
* Filtering:
    * `{"data": {"system": "http://test.com/fakeurl", "concepts":"*", "filter": [{"property": "datatype","op": "=","value": "Misc"}]}}` - This seems to be filtering on concept_class instead of datatype. See [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing6/).

**Comment by snyaggarwal** [comment]
@jamlung-ri 
this is fixed `{"data": {"system": "http://test.com/fakeurl", "concepts":"*", "filter": [{"property": "datatype","op": "=","value": "Misc"}]}}`. Added it in [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing6/references)
Note: this dint return any result as the system version doesn't have any "Misc" datatype concepts.

the valid syntax for mappings:
`{"data": {"valueSet": "http://joe.aml/testjoe14apr22|pre-change", "reference_type":"mappings"}}`
I have added it to [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/autoexpand-testing/references/)

**Comment by snyaggarwal** [comment]
@jamlung-ri for newer reference syntax, you dont need to specifiy "*" for concepts/mappings.
For all mappings, add `"reference_type": "mappings"`
`"reference_type": "concepts"` is default

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal. The mappings references are now working as expected, and the "reference_type" field also works. The filter now seems to be working properly too.

There does seem to be one (possibly unrelated) bug though. In [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing8/), I am getting different lists of concepts when using filters vs. not using filters. [Loom video](https://www.loom.com/share/c59d3786ddb54acda490159840e99b65). This may be related to #1268? Or the Mappings reference might be pulling concepts over too, since the concepts in the list with `Retired: FALSE` seem to be coming from [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/testjoe14Apr22/pre-change/), which corresponds with the mapping reference in the canonical-testing8 collection.

**Comment by snyaggarwal** [comment]
this was because previously added references to this collection were not cleaned up and indexed properly in ES. I have fixed that. Re-indexed the concepts for this collection and it looks good now.

**Comment by jamlung-ri** [comment]
This has been working well in my testing, so I am going to close this out. But first, I figure it might be good to list out a few example references that did work for me during my testing:

- Include References:

```
{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/"]}}
{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric/"]}}
{"data": {"system": "http://test.com/fakeurl", "concepts":"*", "filter": [{"property": "concept_class","op": "=","value": "Misc"}]}}
{"data": {"system": "http://test.com/fakeurl", "concepts":"*", "filter": [{"property": "datatype","op": "=","value": "Complex"}]}}
{"data": {"system": "http://test.com/fakeurl", "filter": [{"property": "concept_class","op": "=","value": "Misc"}]}}
{"data": {"system": "http://test.com/fakeurl", "filter": [{"property": "datatype","op": "=","value": "None"}]}}
{"data": {"system": "http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem", "code": "pdf"}}
{"data": {"system": "https://datim.org/CodeSystem/MER", "concept":[{"code": "TX_PVLS"}]}}
{"data": {"uri": "/orgs/CIEL/sources/CIEL/", "concepts": "*", "mappings": "*"}}
{"data": {"uri": "/orgs/MyOrg/sources/MySource/", "concepts": "*", "mappings": "*"}}
{"data": {"url": "http://hl7.org/fhir/account-status", "code": "unknown"}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "code":"new-fake"}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "filter":[{"property": "datatype","op": "=","value": "None"}]}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "mapping":["691723","691721"]}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "mapping":["691723","691721"]}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "version":"pre-change", "mapping":["691723","691721"]}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22"}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22"}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22|pre-change", "mapping":["691723"]}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22|pre-change", "reference_type":"mappings"}}
{"data": {"valueSet": "https://datim.org/ValueSet/MER_REFERENCE_INDICATORS_FY22", "code": "TX_PVLS"}}
```
- Exclude References
```
{"data": {"system": "http://test.com/fakeurl", "code": "numeric", "exclude":true}}
{"data": {"system": "http://test.com/fakeurl", "reference_type":"concepts", "filter": [{"property": "datatype","op": "=","value": "None"}], "exclude":true}}
{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "mapping":["691723","691721"], "exclude":true}}
{"data": {"valueSet": "http://joe.test", "reference_type":"concepts", "filter": [{"property": "datatype","op": "=","value": "None"}], "exclude":true}}
```
