### ISSUE TITLE
Locales not populating in UI

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1277]
When editing concepts, I open up the Edit Concept pane and the English locales for the names are not populating by default, so any concept I try to edit required that I reinput the locale on the name. Seems like this is happening with description's locale too.

Example using [this concept](https://api.qa.openconceptlab.org/orgs/NHDD/sources/eCHISDataElements/concepts/fp_new_at_30_to_49/):  
![image](https://user-images.githubusercontent.com/55999682/162433446-6c99624b-9d1f-4abe-80bb-444e979d5bb1.png)

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/1273#issuecomment-1092797789_

**Comment by jamlung-ri** [comment]
From Sunny: This is a separate issue and it's not consistent. I think it's a race condition between gettings the locales list for dropdown and filling it up with selected. Sometimes when API takes more time to get this locales list this stays empty. I will look into this.

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed on QA/Staging

**Comment by jamlung-ri** [comment]
This is working again. Thanks!
