### ISSUE TITLE
Cannot delete concepts from a collection's Concepts tab

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1278]
A user pointed out that you cannot delete concepts directly from the Concepts tab in a collection on OCL TermBrowser (production). The TermBrowser is attempting to delete the reference to the concept version, not the concept itself. 

Example video: https://www.loom.com/share/065e0298bb5548f1a572a55b5feea262

In the short term, we will want to allow deleting of direct references from the Concepts tab. However, if it is a dynamic reference e.g. `/orgs/CIEL/sources/CIEL/concepts/?q=hiv` , then there will need to be a warning popup that says "Warning: Deleting this reference may affect other concepts. Are you sure you want to delete?" 

In the long term, we will need to take a deeper dive into the collection management workflows and help users understand how deleting concepts and references will work.

**Comment by jamlung-ri** [comment]
This was discussed on today's [Dev call](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.bri4lvxa3ipp), but we need a little more planning with how to handle the deletion and whether it takes place in the references or the expansion. I will put a little more thought into this.

**Comment by jamlung-ri** [comment]
Some scenarios and proposed outcomes are available here: https://docs.google.com/document/d/1z2h65pP934PyQg3_QSVp0pfHQaffwfTlkTDBXSIk5DI/edit#heading=h.w0kmh69gpt0f

We should discuss this in the next Dev call

**Comment by jamlung-ri** [comment]
After going through scenarios, it looks like exclusion references are going to be the next thing we need to support here.

**Comment by jamlung-ri** [comment]
Next step for this, once Exclusion References are supported, is to think about how to offer the different options for "deleting a concept" from a collection. A user needs to be able to have the option to delete the including references only OR to simply add an exclusion for that concept (or that selection of concepts).

General workflow:

1. User selects concept(s) or mapping(s) to remove from collection. (In background, OCL evaluates if the resources are included because of one or more enumerated or dynamic references.)
2. User clicks action button to remove resource(s). (OCL displays a summary of underlying references?)
3. User views summary of references, which shows a display for which references could be deleted and what effects that will have on the collection (e.g. something that tells the user "deleting this reference will also remove 10 other concepts in the collection").
4. User can now select which Remove option to use:
      * "Exclude concept(s)/mapping(s) from collection (Recommended)" - Tooltip: "Excluding a concept/mapping will ensure that it will not appear in the collection. This can be undone by deleting the exclusion reference(s) in the References tab."
      * "Remove reference(s)" - Tooltip: "References will be removed if they are causing the selected resource(s) to appear in the collection. This cannot be undone, but the references can be added again in the References tab."

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
@snyaggarwal This is good! 

One note: The exclude reference is different than the include reference; the exclude reference contains the version but the original include reference does not. @paynejd I'd be interested in your input on this. When you're excluding a concept, does it make more sense to exclude the specific version of the concept, or do you exclude the concept altogether (i.e. without the reference)? Or maybe that should be up to the user?

**Comment by jamlung-ri** [comment]
Mappings bug: It says these mappings are a result of 0 references, so we cannot delete or exclude. See [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/joetest/HEAD/expansions/e4/mappings/).

![image](https://user-images.githubusercontent.com/55999682/168085467-51f6f462-92ec-4259-a2a7-7a97a30305a0.png)

**Comment by snyaggarwal** [comment]
> Mappings bug: It says these mappings are a result of 0 references, so we cannot delete or exclude. See [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/joetest/HEAD/expansions/e4/mappings/). These mappings might be a result of a cascade.
> 
> EDIT: Actually this collection might just be too old to do this testing on.
> 
> ![image](https://user-images.githubusercontent.com/55999682/168085467-51f6f462-92ec-4259-a2a7-7a97a30305a0.png)

@jamlung-ri Yes these [mapping references](https://api.qa.openconceptlab.org/users/ocladmin/collections/joetest/references/881080/) were added in Fed 2022, when we were not directly linking reference and resources.

**Comment by jamlung-ri** [comment]
Props to @snyaggarwal for the smart prompt. It changes which option is recommended based on how many references are there. See example screenshots:

Recommends removing the reference when it's a direct reference:
![image](https://user-images.githubusercontent.com/55999682/168654158-f360ef3d-e989-4da4-89c0-3779fd6512bc.png)

Recommends excluding the concept when it's not a direct reference:
![image](https://user-images.githubusercontent.com/55999682/168654338-3fed4d0e-1dce-4cc7-88e4-6d47408a9e76.png)

**Comment by jamlung-ri** [comment]
@snyaggarwal Any idea why the Execute button is greyed out for the bottom image in the above comment? It seems to be happening pretty inconsistently. This is the collection I am working in: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing/HEAD/expansions/autoexpand-HEAD/concepts/

**Comment by snyaggarwal** [comment]
@jamlung-ri Found a bug in delete reference. It wasn't re-indexing the removed resources. I have fixed that. Do you mind testing it on new collections?

**Comment by jamlung-ri** [comment]
Based on our Dev call today, we need to be defaulting to versionless references, especially when excluding a concept. Also, we will want to show the reference to the user when we're suggesting an exclude reference. Maybe we should also try to make this reference an editable text field so someone could add an exclude reference if they wanted?

**Comment by jamlung-ri** [comment]
> @snyaggarwal Any idea why the Execute button is greyed out for the bottom image in the above comment? It seems to be happening pretty inconsistently. This is the collection I am working in: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing/HEAD/expansions/autoexpand-HEAD/concepts/
> 
> Example where I can Execute: ![image](https://user-images.githubusercontent.com/55999682/168661018-c47989a9-6c1f-47b9-9e7d-a0b6e3c04d97.png)
> 
> But then I left the prompt, selected other concepts, then tried to remove the concept again, and... ![image](https://user-images.githubusercontent.com/55999682/168661209-5660571e-6b9c-4f6c-a71d-6acda5ebe058.png)
> 
> Once this bug is hit, I have to refresh the page to delete any concept(s).

Here's a quick demo of how this bug occurs for me: https://www.loom.com/share/ec3ddb4d2af1487fb2e0287ba3209534

**Comment by jamlung-ri** [comment]
> @jamlung-ri Found a bug in delete reference. It wasn't re-indexing the removed resources. I have fixed that. Do you mind testing it on new collections?

I think I might still be getting the same issue. Wanted to show it in a [Loom video](https://www.loom.com/share/2db8d701584f4117b5171674cf618d34) in case it helps. I testing this using a [new collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing3/references). The "new-fake" concept should be in this collection as a result of two references: one to [this source](https://app.qa.openconceptlab.org/#/users/ocladmin/sources/test-joe/) and one to [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/testjoe14Apr22/).

**Comment by jamlung-ri** [comment]
> @snyaggarwal Any idea why the Execute button is greyed out for the bottom image in the above comment? It seems to be happening pretty inconsistently. This is the collection I am working in: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing/HEAD/expansions/autoexpand-HEAD/concepts/
> ![image](https://user-images.githubusercontent.com/55999682/168661209-5660571e-6b9c-4f6c-a71d-6acda5ebe058.png)

This Execute button issue has been fixed. The concept exclude issue is still having an issue though, which Sunny and I are working on in Slack.

**Comment by snyaggarwal** [comment]
@jamlung-ri and I discussed the remaining issues and options for this.

1. The exclude reference dialog can show a list of resource versions that are added in the collection default expansion, that can be excluded (multi-select)
2. It can also say "All" which would mean exclude all resource versions.
3. The resulting exclude reference would still be one pointing to one or many resource versions selected

cc: @paynejd 

e.g:
1. include reference -> /orgs/MyOrg/sources/MySource/concepts/123/ -- at the time latest_version (uuid=456)
2. exclude reference for a specific version -> /orgs/MyOrg/sources/MySource/concepts/123/456/
3. a new latest version (uuid=457) for the concept is added
4. a new expansion is computed for the same collection, it will 
include -> /orgs/MyOrg/sources/MySource/concepts/123/ -- latest_version (uuid=457)

In case of exclude all it wont,
exclude ALL -> excluding -> /orgs/MyOrg/sources/MySource/concepts/123/ -- all past and future versions are excluding.

**Comment by snyaggarwal** [comment]
This is deployed on QA

**Comment by jamlung-ri** [comment]
@snyaggarwal The UI part of this looks good. Only issue is this:

I try to exclude a concept from [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing6/HEAD/expansions/autoexpand-HEAD/concepts/), and the versionless exclude reference appears here (see screenshot):
![image](https://user-images.githubusercontent.com/55999682/171881982-5180fd99-7268-40b2-879f-99c9a0d8da05.png)

but the actual reference added was just for the single version:
![image](https://user-images.githubusercontent.com/55999682/171882211-31048b6c-43fa-40ca-8791-095b9126c3bf.png)

But strangely, when I exclude a retired concept (i.e. one with more than a single concept version), the versionless exclusion reference is added as expected.
![image](https://user-images.githubusercontent.com/55999682/171882395-fa4845e6-7faa-4e08-818f-eb439df926db.png)

Is this behavior expected? I think we are aiming for all exclude references to be versionless, if I am not mistaken.

**Comment by snyaggarwal** [comment]
@jamlung-ri This was fixed.

**Comment by jamlung-ri** [comment]
Great, it's working well now on QA. I think we're in a good place to close this out, and we'll continue working on the UI as part of the Collection Management UI initiative.
