### ISSUE TITLE
Change chip text from "Delete" to "Remove Reference" when deleting a concept from the Concepts tab of a Collection

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1279]
This will make it more clear to users that we are not actually deleting the concept itself, but instead deleting the reference to the concept.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/32f6d2d6-ae4e-4960-83be-319a5d7f53f6)

**Comment by snyaggarwal** [comment]
This is done and deployed. Closing this out
