### ISSUE TITLE
Operations Panel - Quick rewording

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1282]
Following up on #1222, there are a couple of small changes to wording in the Operations Panel. Would be nice to have this done by the end of April but not the highest priority.

1. "FHIR Server" -> "Server Base URL" 
2. Panel Header: "Operations" -> "Operations (Beta)"

**Comment by snyaggarwal** [comment]
@jamlung-ri deployed on QA/Staging
