### ISSUE TITLE
CIEL Synonym Search for CHF (Congestive Heart Failure) not working

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1283]
There is a [CHF concept](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/119910/) that I should be able to find when searching CIEL but currently cannot. Not sure if this is an index issue or something else.

This concept does appear when searching [congestive heart failure](https://app.openconceptlab.org/#/search/?q=congestive%20heart%20failure) and when searching [another language's synonym](https://app.openconceptlab.org/#/search/?q=congestief%20hartfalen), but it never appears when searching [CHF](https://app.openconceptlab.org/#/search/?q=CHF). 

Loom Video for easy viewing: https://www.loom.com/share/56f5ff9107004b8aad61470c7110529e

**Comment by snyaggarwal** [comment]
@jamlung-ri This is a bug with search query builder for synonyms. I have addressed this. 
It will soon be available on all environments

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed on QA/Staging

**Comment by jamlung-ri** [comment]
Seems to be working! The only potential issue I'm noticing is that the concept is only appearing when the casing is correct i.e. "CHF". The concept does not appear when searching "chf". Is that expected? It might not be what CIEL needs.

**Comment by snyaggarwal** [comment]
Ya we index synonyms in case-sensitive mode (no reason, just the way it was).
In order to do that will have to reindex everything in concepts (around 24 hours in Staging)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on all environments and concepts were re-indexed.

**Comment by jamlung-ri** [comment]
This is working well on Production now. I'll go over it with Andy but for now, let's consider this closed.
