### ISSUE TITLE
Auto-expand HEAD not being updated when deleting a reference

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1290]
While doing testing on canonical_urls today, I have noticed multiple times that deleting a reference in a collection does not seem to be removing the associated concepts from the autoexpand-HEAD expansion. 

Here's an example collection, which only has one concept reference but it retained other concepts in the expansion: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing4/references

Here's the previous version with the old references that stayed in the above expansion: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing4/bad-filters/expansions/autoexpand-bad-filters/

Other collections where this occurred:
* https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing/
* https://app.qa.openconceptlab.org/#/users/ocladmin/collections/canonical-testing3/

**Comment by snyaggarwal** [comment]
Fixed and deployed on QA

**Comment by jamlung-ri** [comment]
This appears to be working now in QA. I will close this for now and reopen if I notice it happening again.
