### ISSUE TITLE
API Development: Exclusion References

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1292]
Exclusion references are just like regular references, except they have an `"Exclude":True` property. Exclusion references are a type of reference, which is separate from include references. Exclusions can be enumerated codes or dynamic, just like Include references. These references are processed after ALL include references are processed.

For example, if all include references yield the following concepts:
`["/users/ocladmin/sources/test-joe/concepts/new-fake/", "/users/ocladmin/sources/test-joe/concepts/numeric/", "/users/ocladmin/sources/test-joe/concepts/435"]`
and all exclude references yield the following concepts: 
`"/users/ocladmin/sources/test-joe/concepts/numeric/", "/users/ocladmin/sources/test-joe/concepts/435"]`
then the final returned concepts in the collection should be:
`["/users/ocladmin/sources/test-joe/concepts/new-fake/"]`

Example syntax of an exclude reference:
```
{
  “exclude”: True,
  “system”: “http://hl7.org/fhir/CodeSystem/my-codeystem”,
  “version”: “0.8”,
  “namespace”: “...”,
  “filter”: [
    {
      “property”: “datatype”,
      “op”: “=”,
      “value”: “Numeric”
    }
  ],
  “valueSet”: [
    “http://hl7.org/fhir/ValueSet/my-valueset1”,
    “http://hl7.org/fhir/ValueSet/my-valueset2”
  ]
}
```

**Comment by snyaggarwal** [comment]
this can be achieved by adding either of the following:
`exclude: true`, or
`include: false`

**Comment by snyaggarwal** [comment]
this is deployed on QA

**Comment by jamlung-ri** [comment]
Testing this out now!

Successes:
1. I was able to exclude a specific concept using this reference: `{"data": {"system": "http://test.com/fakeurl", "code": "numeric", "exclude":true}}`
2. I was able to exclude a set of mappings using this reference: `{"data": {"valueSet": "http://joe.aml/testjoe14apr22", "mapping":["691723","691721"], "exclude":true}}`
3. I was able to exclude multiple concepts using an excluding filter reference: `{"data": {"system": "http://test.com/fakeurl", "reference_type":"concepts", "filter": [{"property": "datatype","op": "=","value": "None"}], "exclude":true}}`
4. I was able to exclude multiple concepts using a *self-referencing reference*: `{"data": {"valueSet": "http://joe.test", "reference_type":"concepts", "filter": [{"property": "datatype","op": "=","value": "None"}], "exclude":true}}` (See [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing2/references) for the example)

Issues:
1. When I added an enumerated reference for mappings that I excluded in a previous reference, those mappings appear in the collection. This should not be the case, however. According to FHIR, we should process all include statements first, then process the excludes. See [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing/references). It seems like we instead are processing references in the order that they are submitted, if I am not mistaken.
     * Upon further inspection, it looks like this only happens in the [autoexpand-HEAD expansion](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing/HEAD/expansions/autoexpand-HEAD/mappings/). In the [new expansion](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing/HEAD/expansions/e1/mappings/) I made, the references evaluated correctly. Perhaps autoexpand-HEAD is processing new references as they are added, rather than fully re-evaluating the collection? 
5. I created a version of my collection that contained exclude references, and it transformed all my exclude references into include references. See the [HEAD version](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing/references) vs. [version 1](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/exclusion-testing/1/expansions/autoexpand-1/references); version 1 should have exclude references but there are include references only.

Questions:
1. Is there a syntax for excluding with a reference expression using OCL's URLs, rather than using a canonical url? I attempted the following reference but it added an Include reference instead of an Exclude reference: `{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric/"], "exclude":true}}`
2. What filter operators do we currently support? We obviously have "=" - anything else? Looking at the [FHIR spec](https://www.hl7.org/fhir/valueset-filter-operator.html), I thought there would be a "not equals", but I suppose that is covered by "not-in"?

**Comment by snyaggarwal** [comment]
@jamlung-ri 
**Issues** - Both the issues you mentioned are bugs. I have fixed these _(to be deployed on QA)_.
**Questions** -- 
1. Well my initial thought was not to add anything in the old style of reference expressions, but I think we might want to support everything, so I have updated the parser and these should work as expected _(to be deployed on QA)_:
`{"data": {"expressions": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric/"], "exclude":true}}`
`{"data": {"concepts": ["/users/ocladmin/collections/testjoe14Apr22/concepts/numeric/"], "mappings": ["/users/ocladmin/collections/testjoe14Apr22/mappings/m1/"], "exclude":true}}`
2. As per the [MVP Requirements](https://docs.google.com/document/d/1zrQOQBC868uRdrZA-mhzvNzsepVYFhHrMDuJU7mKRjY/edit#heading=h.phcf7wbinrvc), we only support `=` and `in` operators. But I think I tested the `!=` and `not-in` operators as well, I will re-check and add the syntax here (if they are working)
