### ISSUE TITLE
Incorporate ValueSet/Collection $validate-code in Operations panel

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1294]
This was just deployed onto QA for OCL FHIR Core

**Comment by snyaggarwal** [comment]
@jamlung-ri Added `FHIR QA (beta)` available in switch server and in operations panel

**Comment by jamlung-ri** [comment]
This new configuration seems to be working well. I have tested CodeSystem operations, which work as expected, and I am also testing ValueSet Operations (see #1232 for details). Closing this ticket out for now
