### ISSUE TITLE
$cascade visualization gets stuck on some concepts

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1299]
$cascade visualization gets stuck here -- probably due to funky characters in the concept ID:

1. Navigate to https://app.qa.openconceptlab.org/#/users/ocladmin/sources/test-sny-s1/
2. Select concept foo/bar
3. Click on the “Associations” icon
4. The window loads infinitely

**Comment by snyaggarwal** [comment]
@paynejd This is done, and will be available after the next deployment on QA

**Comment by snyaggarwal** [comment]
@paynejd can this be closed?
