### ISSUE TITLE
Error in bulk import results -- unable to parse exception

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#130]
When requesting the results of a bulk import, the response is an exception that the server is unable to parse a URL. The exception occurs regardless of the format requested (e.g. json, summary, report). 

Request URL:
```
https://api.staging.openconceptlab.org/manage/bulkimport/?task=a8168634-9dab-4ceb-a17f-b5c9df05bd28-datim-admin&result=json
```

Response: 400 Bad Request
```
{
    "exception": "Failed to parse: http://ap   i.openconceptlab.org:8000/orgs/DATIM-MOH-TZ-FY19/"
}
```

**Comment by rkorytkowski** [comment]
Fixed in https://github.com/OpenConceptLab/oclapi/commit/c17b6d970014a8c3529c00e6975b567beb837cef

**Comment by paynejd** [comment]
thank you for the quick fix Rafal!
