### ISSUE TITLE
Collections Bug: Not bringing over names, descriptions, and attributes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1301]
It seems that a concept that has been added to a collection is not getting the concept's names, attributes, or descriptions. It is not showing up in the UI but does show up when you go to the original source of the concept.

Example: https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing4/concepts/TX_PVLS/ should be getting the [original's](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-MER-FY22/sources/MER/concepts/TX_PVLS/262256/) Names, Descriptions, and Attributes

Another example: The [source CIEL concept](https://app.qa.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/166364/) ([API link](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/166364/)) has names, but the names (plus the descriptions) seem to be lost when adding the [concept to a collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/delete-testing4/concepts/166364/) ([API link](https://api.qa.openconceptlab.org/users/ocladmin/collections/delete-testing4/concepts/166364/)) (unless I add `?verbose=true`).

**Comment by snyaggarwal** [comment]
@jamlung-ri This was a bug with API responding with the wrong serializer. Its fixed, and will be available after the next deployment on QA

**Comment by jamlung-ri** [comment]
This is looking good on QA!
