### ISSUE TITLE
admin user does not have option to create new collection version

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1302]
Signed in as `ocladmin`, I am not given an option to create a new collection version here:
https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/expansions/trying-again/versions

Screenshot below shows the issue...

However, the real issue here is that `versions` in the TermBrowser is being treated as if it is underneath the expansions (see the URL above). If I instead select the `HEAD` version, I am given the `New Version` option. So this is not a permissions issue, it's a UX issue. Versions/Expansions should exist outside of the selected version/expansion, but the UI doesn't support this approach. Flagging this for the UX team to take on as part of Collection Management improvements.

In the meantime, the "New Version" option should be available regardless of the selection as long as the user has permissions.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1189689/169333774-c135dbb1-9a5c-4702-9574-ceff56921bd4.png">

**Comment by paynejd** [comment]
cc @paulsonder See comment above re: UX issue

**Comment by snyaggarwal** [comment]
This is done, and will be available after the next deployment on QA

**Comment by snyaggarwal** [comment]
@paynejd can this be closed?
