### ISSUE TITLE
Concept shows up multiple times in source versions other than HEAD

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1303]
First, I bulk imported this spreadsheet: https://docs.google.com/spreadsheets/d/1x7y7ZsyfUdvSZWlgAnaaFiQ7wNkq2XTxqDzzaw_Y6W0/edit#gid=0

Second, I navigated here: 
https://app.qa.openconceptlab.org/#/orgs/ocl-test/sources/CascadeTest/

When looking at HEAD, the concepts show up correctly:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/37d115fb-00cb-49ef-8daf-c9a28f44cbf3)

When looking at source version `v1` or `v2`, there are two copies of concept `B`:
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/364d5c7f-852b-4861-a3ec-311e8904ba34)

Note that this showed up immediately after import...

**Comment by snyaggarwal** [comment]
@paynejd the [ocldev.OclCsvToJsonConverter](https://github.com/OpenConceptLab/ocldev/blob/3f6d68b8fd65fa305a5703bf12912ace3d467a64/ocldev/oclcsvtojsonconverter.py#L22) doesn't maintain the order of records. It reorders the content.
If you import a json file for the same it works fine (I will send the json file on mail, cant attach here).
I have import this json file on QA -- check [here](https://app.qa.openconceptlab.org/#/orgs/ocl-test-sny/sources/CascadeTest/). 
This looks good to me

**Comment by snyaggarwal** [comment]
This is linked to #1305

**Comment by snyaggarwal** [comment]
#1305 is closed, closing this out as well.
