### ISSUE TITLE
Save resolved repo versions with an expansion

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1307]
* List of repo versions resolved for an expansions should be viewable via API & TermBrowser

**Comment by paynejd** [comment]
* Does the list of repo version need to link to the references? NO
  * You can get this info by looking up the reference

**Comment by snyaggarwal** [comment]
This is available on all environments for new expansions.

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?

**Comment by paynejd** [comment]
@snyaggarwal Can you write migration script to populate this info for existing expansions?

**Comment by snyaggarwal** [comment]
We can write one, but it won't be accurate because things would have changed from when expansions were resolved and now. I thought about it and decided against it because no information is better than inaccurate. What do you think?
