### ISSUE TITLE
Listing concepts in a collection occasionally returns an empty list

### ISSUE THREAD

**Issue by karuhanga** [OpenConceptLab/ocl_issues#131]
Hey @paynejd, @raff,

It appears the endpoint for getting concepts from a collection is returning an empty list every time, even when a collection contains references to these concepts.   

`GET /users/:user/collections/:collection/concepts/`  
`GET /users/:user/collections/:collection/references/?limit=0` shows that these references are part of a collection.

**Comment by Karuhanga** [comment]
This is currently only happening on `qa`.

**Comment by paynejd** [comment]
We've seen this occasionally when the index does not update
correctly. @raff do we need to rebuild the index on QA?

**Comment by Karuhanga** [comment]
I hope this does not spill over to demo/ prod. This seemed to have improved yesterday, but it is happening again today for custom concepts.

**Comment by Karuhanga** [comment]
@paynejd this is now happening on demo.
https://api.demo.openconceptlab.org/users/admin/collections/TR1/ shows there are concepts in the collection, but https://api.demo.openconceptlab.org/users/admin/collections/TR1/concepts/ returns an empty list.

**Comment by paynejd** [comment]
@rkorytkowski can you take a look at this one?

**Comment by paynejd** [comment]
This bug is observed occasionally in oclapi1 and is addressed by rebuilding the search index. We will not be doing any additional work on this in oclapi1 and it will be resolved in the oclapi2 upgrade. Closing.
