### ISSUE TITLE
Use "best match" sorting by default for org search

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1311]
On staging, do a global search for "openmrs" on the orgs tab. The very last result (out of 54) is "OpenMRS Test Org", where 95% of results do not even have the term "openmrs" in their ID or name (meaning "openmrs" doesn't show up at all in the summary results).

By default, sort for orgs should be "best match" based on the full text index. Right now, the default sorted is "Created On" ascending, which isn't very useful.

**Comment by snyaggarwal** [comment]
@paynejd I have added few fixes on this, they are on QA.

**Comment by paynejd** [comment]
not enough data on QA to easily test this -- will give it a go on staging once it is deployed

**Comment by snyaggarwal** [comment]
@paynejd Can you verify this on Staging and close if all looks good

**Comment by snyaggarwal** [comment]
@paynejd Please close this if all look good

**Comment by paynejd** [comment]
Looking good!
