### ISSUE TITLE
Fix locale search

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1312]
We've created & closed several tickets to fix locale search, but still broken. See screenshot below -- searching for "English" brings up several duplicates and they are not sorted. It also leaves lots of results in the dropdown that do not contain the search term at all, like `Czech`. What's the issue that is making this still a problem?

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/1189689/171646215-f2ae9722-2e06-410d-b90e-f8592f34807d.png">

**Comment by snyaggarwal** [comment]
@paynejd Please close this if all it looks good

**Comment by paynejd** [comment]
We'll confirm that this is addressed in the source/collection form work -- closing
