### ISSUE TITLE
After creating collection/source, collection/source lists must refresh

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1313]
If you create a new collection while on the org collections list, the collections list should refresh to show the collection that you just created. Right now, you get a brief notification that says it was submitted/created, but then the notification appears and the new collection is not shown unless you refresh or navigate between tabs again.

The same issue occurs when creating a source...

See screenshot below for where this occurred in the app (this is after a manual refresh):

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/1189689/171646908-0872ac80-0da1-4df5-b4ad-61d8a24d3bb8.png">

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA
