### ISSUE TITLE
Create mapping action from concept selection populates form fields incorrectly

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1315]
When selecting a concept and clicking on "Create Mapping", the "from source url" field incorrectly has a double slash at the end...

Also, if the full concept URL is known, none of the other fields need to be populated. Can't we just populate the concept URL?

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/1189689/171673010-228b35d8-8d82-46e1-8b7f-e5007cbf2c0d.png">

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA

**Comment by paynejd** [comment]
Looking good! In the future, we'll want to add features to the termbrowser that looks up the from-concept-url and provides more info for the user and gives them the option to save selected concept attributes along with the mapping.
