### ISSUE TITLE
Wrong concept/mapping IDs displayed in the collection mappings and references lists

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1316]
Using the termbrowser, I added created to new mappings using sequential auto-IDs, so their IDs are simply `1` and `2`. Mappings are here: https://app.qa.openconceptlab.org/#/orgs/OpenmrsTest/sources/test1/mappings/ (also see `Screenshot A` below..).

After I created these mappings, I selected each in the TermBrowser and added to a collection without cascading. 

Next, I navigated to the collection mappings here: https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/HEAD/expansions/autoexpand-HEAD/mappings/

The ID column appears to be showing the wrong field, because these 2 mappings are shown as `6017235` and `6017237` (see `Screenshot B`). Assuming this is the mapping version ID? 

The same is true for the custom concept that I created using auto UUID: https://app.qa.openconceptlab.org/#/orgs/OpenmrsTest/sources/test1/concepts/ (see `Screenshot C` below). In the collection concepts tab, it is incorrectly showing the concept ID as `939393` (see `Screenshot D`).

Finally, over on the references tab, the IDs for the 3 resources added from /orgs/OpenmrsTest/sources/test1/ are all incorrect, while the resources added from CIEL are correct: https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/references (see `Screenshot E`).

Worth noting that all 3 of these resources are using the new auto-ID feature...

## Screenshot A
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/1189689/171674449-9d7d0b12-e956-44cf-8338-8aa374b472f7.png">

## Screenshot B
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/1189689/171675288-5a0c65c7-2c1e-4191-9fa8-0557da3d0cb9.png">

## Screenshot C
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/1189689/171675604-8c46b261-c60b-4372-ac9f-acdbae61d51f.png">

## Screenshot D
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1189689/171676111-0bba328f-5f17-46ea-892b-1aab62b1e07c.png">

## Screenshot E
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1189689/171676057-ac2d2f3f-ca28-401e-966f-abcbf470ad04.png">

**Comment by snyaggarwal** [comment]
@paynejd I think you mixed up QA and Staging Env :)
In your comment, all the concept/mapping creation happened on QA and you were checking the results in Staging Env.
If you check the QA env in corresponding Collections, things look good to me.

@paynejd Let me know if I misunderstood this.

**Comment by paynejd** [comment]
ugh.... sorry. did this one too fast. you're completely right and this is working correctly!
