### ISSUE TITLE
Support starts with &/or exact match on custom attribute search when criteria includes hyphen

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1321]
https://api.staging.openconceptlab.org/orgs/?limit=200&verbose=true&extras.datim_moh_object=true&extras.datim_moh_period=CS-FY22

For the above query, the `extras.datim_moh_period=CS-FY22` parameter is matching any value in `extras.datim_moh_period` that starts with `CS`  (e.g. “CS-FY20”, “CS-FY21", “CS-funny-guy”, etc.)

Ideally, the default behavior should match anything that contains "CS-FY22"

An "exact match" option for "CS-FY22" could also be useful

**Comment by snyaggarwal** [comment]
fuzzy -- `extras.datim_moh_period=CS-FY*`
exact -- `extras.datim_moh_period=CS-FY22`
(even-more) exact -- `extras.exact.datim_moh_period=CS-FY22`

Hyphens are special characters that the ES tokenizer uses to split into multiple words.
While indexing I have converted hyphens to underscores and same in search.
Will be deploying this soon on QA
