### ISSUE TITLE
Auto-ID | Handling existing sources

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1323]
We set `source.autoid_mapping_mnemonic` default to "sequential", but we dint create DB sequences for existing Sources in environments.
Currently, they will fail while creating Mappings.
Options:
1. Ignore the autoid sequence for the existing sources and let them work the way they were working
2. Write migration for existing sources and create sequences for each source in every environment.

cc @paynejd

**Comment by paynejd** [comment]
Implement/deploy #1 as a quick fix and then implement #2...

**Comment by snyaggarwal** [comment]
Tested the fix (#1) on QA, it works for existing Sources.

**Comment by snyaggarwal** [comment]
Closing this out.
