### ISSUE TITLE
Auto-ID Recommendations for OpenMRS

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1324]
Since OpenMRS will be a key user of the Auto-ID fields, it would be good to include some quick recommendations for them in the Create Source form's tooltips (see the circled part of the screenshot below). 

Text to add:
* For Autoid Concept Mnemonic: "OpenMRS recommends using 'sequential' here."
* For Autoid Mapping Mnemonic: "OpenMRS recommends using 'sequential' here."
* For Autoid Concept External Id: "OpenMRS recommends using 'uuid' here."
* For Autoid Mapping External Id: "OpenMRS recommends using 'uuid' here."

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/13209b1c-e243-4d15-84bb-343847e9e1ac)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere

**Comment by jamlung-ri** [comment]
Looks great! Closing for now. Ellen might give feedback so I'll reopen this ticket if needed.
