### ISSUE TITLE
Option to see list of repository versions that were resolved when creating an expansion

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1326]
Suggestion is to change the "View Expansion Parameters" window to "View Expansion Attributes" with two sections (for now):
* **Expansion Request Parameters**
  * Add an "Info" icon with a tooltip with this description: "The set of expansion request parameters that were used to control how this expansion was evaluated. Each expansion may use a different set of parameters."
  * Display can be the same or possibly improve the formatting if easy enough?
* **Referenced Repository Versions**
  * Display a list of all of the specific repository versions OCL that were used in the evaluation of the expansion
  * Add an "Info" icon with a tooltip with this description: "The set of repository versions that were used in the evaluation of this expansion."

Are there other details that we have about expansions that would be useful to add into this window as well?

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/0b17bdf5-216b-4c75-b86a-29349677bf69)

**Comment by snyaggarwal** [comment]
Blocked by #1307

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?
