### ISSUE TITLE
TermBrowser to indicate IE not supported

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1328]

**Comment by snyaggarwal** [comment]
@jamlung-ri Do you have a device with IE in it to test this?

**Comment by jamlung-ri** [comment]
Yeah, I tested with Internet Explorer on my device but I don't know what version or how up to date it is. It's unable to open up the webpage for https://app.openconceptlab.org/ . Here's the console:

> DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
> app.openconceptlab.org
> 
> HTML1300: Navigation occurred.
> app.openconceptlab.org
> 
> SCRIPT438: Object doesn't support property or method 'startsWith'
> app.openconceptlab.org (1,684)
> 
> SCRIPT1003: Expected ':'
> moment.js (2,155781)
> 
> SCRIPT1002: Syntax error
> lodash.js (2,84)
> 
> SCRIPT1002: Syntax error
> react.js (2,97)
> 
> SCRIPT1002: Syntax error
> 121.js (2,84)
> 
> SCRIPT1002: Syntax error
> main.js (1,4)

**Comment by jamlung-ri** [comment]
@snyaggarwal Is this still relevant?

**Comment by snyaggarwal** [comment]
Closing this.
