### ISSUE TITLE
Make canonical_url a URI instead of URL

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#1329]
To be compliant with FHIR spect we need to accept any URI, e.g. 
urn:oid:2.16.840.1.113883.6.238

We can say that canonical_url must contain a schema in front ended by ':'. If it doesn't then it's a relative URL in OCL.

**Comment by snyaggarwal** [comment]
@rkorytkowski Can we close this?

**Comment by snyaggarwal** [comment]
Closing this out. New bugs/requests will be taken in new ticket.
