### ISSUE TITLE
Limit the size of args being displayed in flower

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#133]
Some tasks may get very big arguments (a few MBs in size). We need to limit the size of arguments being displayed in flower so as to prevent flower from timing out trying to show them in UI.

**Comment by paynejd** [comment]
@rkorytkowski did you already implement this fix?

**Comment by rkorytkowski** [comment]
Not yet. It should be a quick fix. I can do that on Monday.

**Comment by rkorytkowski** [comment]
It's been deployed to qa/demo/staging some time ago.
