### ISSUE TITLE
Change localized_text index to be hash based instead of b-tree

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#1330]
Some names in FHIR are too long for b-tree index (longer by half). We need to make it hash based. We use it for example in uniqueness validator so equality comparator should suffice. How long is the text field for localized_text in DB?

**Comment by rkorytkowski** [comment]
It's enough :) Thanks for checking!

**Comment by snyaggarwal** [comment]
This is done and deployed. Closing this.
