### ISSUE TITLE
Add simple admin panel to user profile page to perform user account support

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1335]
We would like OCL admins to be able to perform basic user account support tasks directly from a user's profile page. Example include:
* Verify user account
* Activate/deactivate user account
* Change/reset password

What other actions an admin might perform? Delete user account?

**Comment by snyaggarwal** [comment]
@paynejd This is available on QA with the following features:
1. Can mark any user whose email verification is pending as a "Verified" User.
2. Can activate/deactivate any user.
3. Can make a user admin or remove admin privileges.
4. Can reset (or set) the password of a user.

Restrictions:
1. Only superuser (like ocladmin) can do these operations
2. A superuser can make someone admin (but not superuser)
3. A superuser can not do any of this for another superuser
4. A superuser cannot make any user a superuser from TermBrowser.

**Comment by paynejd** [comment]
Awesome! This works great. Just one really quick suggestion: can you make it clear that this is admin only? and maybe put it in a red background with warning notices etc.? Thinking similar to the settings box in GitHub where you can delete a repository or do other irreversible things...

**Comment by snyaggarwal** [comment]
@paynejd Can this be closed?

**Comment by snyaggarwal** [comment]
Closing this out
