### ISSUE TITLE
Retired mappings still appearing in Associations Panel

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1339]
On some CIEL concepts like [this one](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/167101/), it looks like there are two sets of mappings that are between the same concepts. In reality, [one set of mappings](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/mappings/2515596/) is retired, and the [other](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/mappings/2732891/) is more current. We just can't tell that from the Associations panel.

Can we add formatting (e.g. strikethrough) for retired mappings? And those mappings should probably be at the bottom of the panel, perhaps hidden until the user clicks something that says "Show ## retired mappings"?

**Comment by snyaggarwal** [comment]
@jamlung-ri Good catch. This looks like a change in $cascade operation.
Currently, its cascading retired/active concepts/mappings as equal, may be we should exclude them by default and add a parameter to include if we need to. And a UI indicator is needed anyways, I will add that.
@paynejd What do you think?

**Comment by paynejd** [comment]
Excluding retired by default sounds like the right approach

**Comment by bmamlin** [comment]
The convention within the OpenMRS community is to hide/omit retired content by default and provide an option to "unhide" it. When it is requested/shown, retired content should easy to distinguish visually. We have typically used ~strikethrough~; although, this can make content harder to read (needing a "hide strikethough" option or limiting strikethrough to part of the content like just code instead of long text like name/description).

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on all environments.
1. added `includeRetired` filter on $cascade operation. By default its false. It will exclude all retired mapping/concept and will not cascade.
2. on UI (associations table and visualisation) added option to includeRetired (by default excluded).
3. Also added indicator by striking through code and making it red in visualisation and table

**Comment by jamlung-ri** [comment]
This appears to be working well. One slight issue: the number of associations seems to be off? See screenshots below to [this collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/mapping-test/HEAD/expansions/autoexpand-HEAD/concepts/) where the blue circled number seems to be too high.
![image](https://user-images.githubusercontent.com/55999682/181000653-778db22b-97c9-4bd8-b1f7-e712a476353b.png)
![image](https://user-images.githubusercontent.com/55999682/181000692-1cf45234-beef-413a-9581-b0eef5fb0dc9.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed and deployed in all environments

**Comment by jamlung-ri** [comment]
Everything is looking good on my end!
