### ISSUE TITLE
Converting references into "plain english"

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1343]
In short, the References tab of a collection can be confusing, so we should enable OCL TermBrowser to translate a reference into something more understandable for less technical users.

Examples:
|                             **Reference**                            | **Link to API example**                                                                      | **Plain English**                                                                                   |
|:--------------------------------------------------------------------:|----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| /orgs/CIEL/sources/CIEL/concepts/703/                                | https://api.qa.openconceptlab.org/users/ocladmin/collections/mapping-test/references/973551/ | Include concept "703" from latest version of CIEL/CIEL                                              |
| /orgs/CIEL/sources/CIEL/concepts/1436/4178/?cascade=sourcetoconcepts | https://api.qa.openconceptlab.org/users/ocladmin/collections/mapping-test/references/974462/ | Include version "4178" of concept "4178" from CIEL/CIEL PLUS its mappings and their target concepts |
| /orgs/WHO-ICD-Test/sources/ICD-10-Test-Small/concepts/?q=hep         | https://api.qa.openconceptlab.org/users/ocladmin/collections/mapping-test/references/974466/ | Include latest concepts from WHO-ICD-Test/ICD-10-Test-Small containing "hep"                        |
| /users/ocladmin/sources/asdfasdf/v1/concepts/                        | https://api.qa.openconceptlab.org/users/ocladmin/collections/mapping-test/references/974467/ | Include concepts from version "v1" of ocladmin/asdfasdf                                             |

**Comment by jamlung-ri** [comment]
This is working well in QA! I did some testing in [this collection](https://api.qa.openconceptlab.org/users/ocladmin/collections/joe-test-02Sep2022/references/?limit=100&verbose=true) with a few various reference types, including some absurd ones. 

The next step here is to incorporate this into the UI somehow. Perhaps a quick and easy thing to do would be to display this translation by default, and provide a switch to change to viewing "raw" reference expressions? @snyaggarwal What do you think about that?

**Comment by snyaggarwal** [comment]
@jamlung-ri Added translation in UI as default in Reference Listing. Also I think, We dont have to show expression, since there is a "copy-expression" option just next to the translation. Also You can click on translation to see the json data.
Let me know what you think. This is available on QA.

**Comment by jamlung-ri** [comment]
This is working great, actually! I think this is the everything we need for this ticket, and it looks good in QA.
