### ISSUE TITLE
Get the latest version for GET /CodeSystem?url=[url]

### ISSUE THREAD

**Issue by mcabello-cens** [OpenConceptLab/ocl_issues#1344]
@paynejd, @rkorytkowski: 

Check this method please in OCLFHIR.Util.OclFhirUtil.java

```
    public Source getLatestSourceByUrl(StringType url, List<String> access) {
        return sourceRepository.findFirstByCanonicalUrlAndPublicAccessInAndIsLatestVersionOrderByCreatedAtDesc(
                url.getValue(), access, false
        );
    }
```

The boolean parameter should be **true** to recover the last public version; Otherwise, you get nothing back
I guess for ValueSet and ConceptMap the same could happen

https://github.com/OpenConceptLab/oclfhir/blob/7aaf924ff1986ebbccab60a05c1d95d4a527f7f2/ocl-fhir-ts/src/main/java/org/openconceptlab/fhir/util/OclFhirUtil.java#L284

https://github.com/OpenConceptLab/oclfhir/blob/7aaf924ff1986ebbccab60a05c1d95d4a527f7f2/ocl-fhir-ts/src/main/java/org/openconceptlab/fhir/util/OclFhirUtil.java#L294

**Comment by paynejd** [comment]
@rkorytkowski Can you confirm that this ticket is addressed in the new OCL FHIR Core?

**Comment by rkorytkowski** [comment]
It's working as expected with the new FHIR core service. It's currently available on QA, but I'll be deploying to staging and production today. I'm closing this issue.
