### ISSUE TITLE
allow repo admin to refresh the repo version summary

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1347]
I think right now this behavior is restricted to ocladmin?

We want to expose this behavior in the version tab for sources & collections

For example, the summary for CIEL v2022-08-14 shows 0 concepts/mappings even though all of the content is there. We want CIEL admins to be able to refresh this directly in the TermBrowser.

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/8fce34f6-fd61-4e31-ba49-e89f3168b617)

Given the number of actions that are piling up for repo versions, should we bundle these into an "Actions" menu that a user accesses by clicking on the vertical ellipsis?

**Comment by snyaggarwal** [comment]
@paynejd this is available on QA

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on all environments. I have triggered it for CIEL versions (wherever required) in staging/production

**Comment by snyaggarwal** [comment]
Deployed on all envs. Closing this out.
