### ISSUE TITLE
Source/Collection Create/Edit Forms

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1348]
Mockups have been created for source and collection editing, which will make it easier for users to understand OCL's source and collection attributes. 

Note that the development of this is a deliverable for Digital Square, due Sep. 12.

See mockups in Zeplin: https://zpl.io/RMLx6w0

Possibly worth noting: Some current UI fields are not addressed in the Mockups. See [this spreadsheet](https://docs.google.com/spreadsheets/d/1VprU2N-p25YhfILFtPuNxEwWQXHyNVwFw3HTJkDObTk/edit) (tab: "Form Tooltip Language") for suggested organization and grouping. Columns "Form", "Section", and "Field" show how I suggest we arrange the fields for now (if they should appear in the UI at all, that is).

**Comment by snyaggarwal** [comment]
@jamlung-ri Moving this story to in-review

**Comment by paulsonder** [comment]
- If I try to save the form without entering any (or partially fill some) of the mandatory fields, I only see one error… could we show all errors?
- Currently, helper text seems to be displayed below the field as standard - I would suggest we show that when the field is focussed, as it looks a little crowded.
- Helper text should also be indented, as per the canonical field - some places it looks like label text
- Could we have 24px height between fields, again, things look a little tight, particularly in the Configuration section.
- Please add 8px spacing between the default language and supported languages button
- The text style in the new visibility drop down should use ‘helper text’ which is 12px, not 14, same for the text in the advanced accordions.
- In Assigning ID's - the OpenMRS text would designed to sit in a small info banner, if the source type Dictionary was selected.
- Would be great to get ‘tooltips’ on Meta and Collection references in Other source attributes
- Title heading size is 24px in the design but 28 on QA
- Meta and Locked date need tooltips in the Collection form

**Comment by snyaggarwal** [comment]
Locales work in #1364

**Comment by paulsonder** [comment]
Have we added something custom for how many options are visible in the locale dropdown when it's focussed? The menu jumps above the field in my browser as it's so long. I think 6 values + the custom code button are enough.

**Comment by jamlung-ri** [comment]
Agreed with Paul. @snyaggarwal Can you make this quick change when you have time? Let's limit the Locales result to 6 + custom code button.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder this is done

**Comment by jamlung-ri** [comment]
@snyaggarwal There is one more fix with the Locales field in #1364. Once that ticket is resolved, then this should be ready for deployment.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
