### ISSUE TITLE
Filter by collectionType combined with a search query when fetching collections not working

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#135]
Hitting an endpoint like this one;
`https://api.qa.openconceptlab.org/collections/?verbose=true&collectionType=Subset&q=Test*`
will return results matching the search query, but which are not filtered by the `collectionType`.

Either of these works OK separately, e.g;
`https://api.qa.openconceptlab.org/collections/?verbose=true&collectionType=Subset`
`https://api.qa.openconceptlab.org/collections/?verbose=true&q=Test*`

**Comment by paynejd** [comment]
@harpatel1 Could you review whether you already resolved this issue based on the work you did in #251 ?

**Comment by harpatel1** [comment]
@paynejd Yes, this would also be resolved by the work done in #251 .

**Comment by paynejd** [comment]
@Karuhanga -- could you test that this now works in QA? We believe that @harpatel1 has resolved the issue in ticket #251
