### ISSUE TITLE
Concepts Menu Dances while loading

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1350]
See video. To reproduce, try searching a concept directly, like 856AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

See how the list wants to load the scroll bar 🕺 🕺 🕺 🕺 

https://user-images.githubusercontent.com/67400059/189001826-91d64af1-4a1f-4cb6-9b62-94f742d2e656.mov

Non urgent but @snyaggarwal thought you might like to fix this as a bug sometime.

**Comment by gracepotma** [comment]
(Side note: I'm surprised it took this long to load this concept. Given it was a very specific search. And this was actually my 4th time refreshing this same page just to reproduce this bug for a screen recording.)

**Comment by snyaggarwal** [comment]
@gracepotma Thanks for reporting this. May I ask for some additional info, like, which browser and version you are using and what is your Operating System (is it windows?)

**Comment by gracepotma** [comment]
Sure! 
OS: macOS Big Sur Version 11.6
Browser: Chrome, Version 104.0.5112.101 (Official Build) (arm64)

**Comment by snyaggarwal** [comment]
@gracepotma This was fixed.
