### ISSUE TITLE
Term Browser Search incorrectly shows "no results" if hyphen is used in ID string

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1351]
It seems there's a bug in OCL search around the use of "-" - when I searched for `ae485e65-2e3f-4297-b35e-c818bbefe894`OCL showed "no results", but when I just search for `c818bbefe894`, I found the Hematology concept right away. 

We had a developer who basically re-created concepts (wrongly) because they got the (wrong) impression after searching for these full UIDs in the OCL search UI and seeing "No Results", they thought OCL had changed the UIDs (!!). 

This does not seem to be a problem for text - e.g. searching `by-proxy` correctly finds a number of relevant terms. 

Video reproduction: https://www.loom.com/share/5aac91b964574fa3802dea0512960e3d

**Comment by gracepotma** [comment]
Re. slow loading time - my connection speed at time of reproduction was not a concern: 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/67400059/189006819-3084faa2-9dd4-4d1f-8776-cdcbdd65cde3.png">

**Comment by snyaggarwal** [comment]
Thanks, @gracepotma for reporting this.
Looks like external_id was not exact searchable. I have made the changes. This should reach to environments soon

**Comment by snyaggarwal** [comment]
@gracepotma this is fixed and deployed on all environments.

**Comment by gracepotma** [comment]
**Wow** Sunny - kudos to you!! Thank you for such a quick turnaround (feels pretty amazing as a reporter). I'll let the OMRS folks who were involved know.
