### ISSUE TITLE
Filters panel not populating with certain search terms

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1352]
It seems like some search characters are causing the facets query to return blank, so the filters panel has no options appearing, even though there are search results returned.

Example search characters:

- "*"
- "#"
- "epstein-" (but note that the "-" character alone does work)

Loom: https://www.loom.com/share/6362299018874c9e8d2b6ea8a97b947f

Example: 
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/72058f43-58b6-4071-b874-43210ed755f0)

**Comment by jamlung-ri** [comment]
@snyaggarwal Has this been fixed? If not, it could probably be done in this sprint if there is time.

**Comment by snyaggarwal** [comment]
@jamlung-ri This should be fixed with new Search. Can you please verify this?

**Comment by jamlung-ri** [comment]
This is working well on Production!
