### ISSUE TITLE
Support `retired` field for mappings in CSV bulk import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1354]
In the JSON bulk import format, there is an optional __action field that you can use to control how a row is processed. The default action if not specified is CREATE_OR_UPDATE, but it supports all of these values: https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclfleximporter.py#L512. If you were using a JSON bulk import script, you would simply set the __action field to DELETE to accomplish what you’re trying to do. However, that field isn’t currently supported in the CSV bulk import format.

**Comment by snyaggarwal** [comment]
@paynejd we do have "retired" option in case of concept/mapping CSV import. Is that different?
For example -- [here](https://github.com/OpenConceptLab/oclapi2/blob/master/core/samples/ocl_csv_with_retired_concepts.csv)

**Comment by snyaggarwal** [comment]
@paynejd 
Just saw the [full list](https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclfleximporter.py#L512) of action types that oclfleximporter supports.
Currently Parallel importer only supports `__action=delete` and it hard deletes org/source/collection but retires concept/mapping.
Adding this to the arch call agenda to understand different action types.

**Comment by paynejd** [comment]
From @paynejd:

> We discussed this on our architecture call and I may not have responded carefully enough. A DELETE request on a concept or mapping actually just sets retired to true. For a source, collection, or org, a DELETE request will actually delete it from the database entirely. If you are trying to retire the concept/mapping, then you can simply add a retired column with the value of True , and that will take care of it. Unfortunately, hard deletes of concepts/mappings are not currently supported at this time. Can you say a little more about what it is that you are trying to do in the bulk import script?

**Comment by paynejd** [comment]
From Lauren Fregosi in OCL slack channel:

>  Our team is exploring deleting mappings because of errors we made in a bulk import file. We're happy to retire a mapping as you described, but neither 'TRUE' 'True' or 'true' in a column 'retired' successfully retires a mapping. Could there be another syntax we haven't tried? Thanks!

**Comment by paynejd** [comment]
To unblock users, we want to add support for the `retired` column for mappings in CSV bulk imports. It should have the same behavior as the `retired` column for concepts. Renamed the ticket to reflect that this is now the acceptance criteria.

Note that we will want to support hard deletes for concepts and mappings in the future, but that we are not planning to implement that behavior at this time.

**Comment by snyaggarwal** [comment]
@paynejd Added this behavior in [ocldev@cedb603](https://github.com/OpenConceptLab/ocldev/commit/cedb6035ba4269db73ef574ba181e1d9ace57901).
Added a [sample CSV](https://github.com/OpenConceptLab/oclapi2/blob/master/core/samples/ocl_csv_with_retired_concepts.csv) for it in oclapi2 and updated [test](https://github.com/OpenConceptLab/oclapi2/blob/master/core/importers/tests.py#L490) around it.

**Comment by paynejd** [comment]
I commented on the pull request. As long as you agree with the comment,
then this looks good -- thanks for such a quick turnaround!

**Comment by jamlung-ri** [comment]
@snyaggarwal I made a comment in reply to your discussion. Probably should include it here too: 
https://github.com/OpenConceptLab/ocldev/commit/cedb6035ba4269db73ef574ba181e1d9ace57901#r85495895

**Comment by jamlung-ri** [comment]
I tried loading the CSV into QA (see [here](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyDemoSource/mappings/)), and this time it was successful. Only note is that there is no visual distinction for the retired mappings, whereas you can easily tell retired concepts using the red strikethough.

**Comment by snyaggarwal** [comment]
added this.

**Comment by jamlung-ri** [comment]
This is working well in QA. The example CSV has been updated with a couple of rows dedicated to retired mappings, and all of them appeared as retired in [this test org](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyDemoSource/mappings/?q=&isTable=true&isList=false&page=1&exactMatch=off&facets={%22retired%22:{%22true%22:true,%22false%22:true}}).

**Comment by snyaggarwal** [comment]
@paynejd Have you released a new version for ocldev after these changes?

**Comment by snyaggarwal** [comment]
this is deployed in production.
