### ISSUE TITLE
Dealing with Extra attributes that are not type "string"

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1356]
We noticed today that displaying an Extra attribute that is an integer/float was not appearing properly on the TermBrowser. Example: https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/mappings/6004405/ plus see screenshot below.

This might have to do with a broader issue, however. If someone were to use the TermBrowser to assign a value to a numeric field, will the TermBrowser store it as type `string` by default? If so, that will be an issue that we should address. This extras.sort_weight field should consistently store the value as a float, even if a user edits it in the TermBrowser, or else it will break the OpenMRS process. 

One thought: This is a good use case for Jon's previous ideas regarding source-level attributes that all concepts will have. This would allow Extra attributes to be consistently formatted across concepts in that source.

cc: @bmamlin @paynejd 

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/cba0a3d0-6129-4288-b6a0-78170071d18c)

**Comment by snyaggarwal** [comment]
@jamlung-ri There was a bug in showing numeric values, I have fixed that, (In raw display everything works fine). The int/floats are stored as int/floats and not strings.

**Comment by jamlung-ri** [comment]
Perfect, this is now looking great. I also tested behavior to respect numeric vs. string values in an Extra attribute, and the field was recognizing numeric vs. string values as expected.

**Comment by snyaggarwal** [comment]
- API doesn't do any sort of type casting on the values of extras.
- TermBrowser tries to convert input into JSON, because the field to enter values in forms is a text field. Other than that no conversion happens.
- ocldev while importing the content from CSV, can convert datatypes bool,int,float,list and json, in the format -- `attr:<name>:<datatype>`

**Comment by jamlung-ri** [comment]
> * API doesn't do any sort of type casting on the values of extras.
> * TermBrowser tries to convert input into JSON, because the field to enter values in forms is a text field. Other than that no conversion happens.
> * ocldev while importing the content from CSV, can convert datatypes bool,int,float,list and json, in the format -- `attr:<name>:<datatype>`

@paynejd Where in the OCL Docs website should this info go? Maybe here? https://docs.openconceptlab.org/en/latest/oclapi/apireference/concepts.html#create-or-update-an-extra

Or do we need to separate this out into multiple sections i.e. one for API, one for TermBrowser, and one for OCL Dev Tools?

**Comment by jamlung-ri** [comment]
Seems like we need a new page for Extra attributes, for the time being at least.

**Comment by paynejd** [comment]
Several OCL resources support extra attributes:
- Concepts
- Mappings
- Sources
- Collections

@snyaggarwal any resources I'm missing?

@jamlung-ri Our API Reference documentation only includes this under concepts right now. Once we have a good extras doc page, then we can remove it from Concepts and add some language/links/etc. to all of the relevant pages.

**Comment by snyaggarwal** [comment]
@paynejd Organization and UserProfile also has `extras`.

**Comment by paynejd** [comment]
do source version and collection version have extras that are separate from
source and collection?

**Comment by jamlung-ri** [comment]
> do source version and collection version have extras that are separate from
source and collection?

@snyaggarwal Related to this, I tried to create a version of a source that has an Extra attribute, and the Extra attribute did not carry over to the source version. See [HEAD version](https://api.qa.openconceptlab.org/orgs/DemoOrg/sources/MyDemoSource/HEAD/) vs. [version v1](https://api.qa.openconceptlab.org/orgs/DemoOrg/sources/MyDemoSource/v1/).

**Comment by snyaggarwal** [comment]
@jamlung-ri This was never implemented and copied from OCLAPI v1.
Do we want to copy extras to new versions of repos?

**Comment by paynejd** [comment]
@jamlung-ri How urgent is this -- can we discuss during dev call tomorrow?

**Comment by jamlung-ri** [comment]
First draft of this documentation is here: https://docs.google.com/document/d/1ofPspfktsXVkNaP3PQzEjcJaW9U1i3r5UMuO0Xz2FvU/edit

@snyaggarwal @paynejd Let me know if you want to review before I post it to OCL Docs tomorrow (i.e. Wednesday Nov. 2)

**Comment by snyaggarwal** [comment]
- [ ] new versions to copy extras from HEAD
- [ ] data migration for existing versions to copy from HEAD

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri this is done on QA

**Comment by jamlung-ri** [comment]
The documentation for this has been posted here: https://docs.openconceptlab.org/en/latest/oclapi/apireference/custom_attributes.html 

Regarding Extra attribute copying, this appears to be working now. I tested it on some PEPFAR collections e.g. [this one](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/collections/MER-R-OPERATING-UNIT-LEVEL-IM-FY2020Q4/versions), which now have extra attributes in their versions. I was also able to create new versions that successfully got the Extras from HEAD. 

@paynejd Anything else here before we move on to Production? I imagine we will need to do the same migration of Extra attributes in Staging and Production, but deferring to @snyaggarwal if that is not the case.

**Comment by snyaggarwal** [comment]
@jamlung-ri The migration will happen automatically as part of the deployment.

**Comment by snyaggarwal** [comment]
this is deployed everywhere.
@jamlung-ri Can we close this?
