### ISSUE TITLE
Quick-Add Mappings in Source

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1359]
Scope:

- When viewing an individual concept, there needs to be a way to quickly add a mapping to another existing concept. 
- If a mapping already exists, then the user can create another mapping using the same map type.

Latest video demonstration: https://www.loom.com/share/aefde013656a4d03baa1e5dcb26ecbdf

**Comment by paynejd** [comment]
@jamlung-ri Any reason to keep this epic around?

**Comment by jamlung-ri** [comment]
Nope, let's close it out!
