### ISSUE TITLE
504 Gateway Timeout when deleting large org

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#136]
When deleting an org with lots of content on QA (the /orgs/PEPFAR/sources/MER-MSP/ org), the org was successfully deleted, but the DELETE request returned 504. The delete request was performed as the root user.

```
DELETE https://api.qa.openconceptlab.org/orgs/PEPFAR/
```
Response:
```
<html>
    <head>
        <title>504 Gateway Time-out</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>504 Gateway Time-out</h1>
        </center>
        <hr>
        <center>nginx/1.10.3 (Ubuntu)</center>
    </body>
</html>
```

**Comment by paynejd** [comment]
@snyaggarwal Please note this bug -- is this already addressed in oclapi2?

**Comment by snyaggarwal** [comment]
The timeout depends upon whats configured at network level (nginx proxy) for APIs.
On my local I could delete PEPFAR in ~50seconds. Assuming prod/non-prod will have more resources than my system so PEPFAR will be ok, but some other bigger orgs might still timeout. We will have to make it async just like export process.

**Comment by snyaggarwal** [comment]
This is now an async task.
