### ISSUE TITLE
Implement Quick-Add Mappings feature in Source

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1363]

**Comment by paulsonder** [comment]
We're currently accepting feedback via this [Maze](https://app.maze.co/report/New-maze-1/3k5jail9ffldel/intro) test.

**Comment by jamlung-ri** [comment]
Note that some changes were made based on feedback in the #ocl-core Slack channel.

**Comment by paulsonder** [comment]
Hey @snyaggarwal, you can find the UI [here](https://zpl.io/Z08mWGd).

**Comment by snyaggarwal** [comment]
@jamlung-ri Can you please add tooltip text for below fields here:
- Relationship Type (Map-Type)
- Source
- Concept

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder @paynejd this is deployed on QA.
The only missing thing is Tooltips. Need the tooltip text.

**Comment by jamlung-ri** [comment]
Thanks Sunny. I'll work on tooltips and get back with you.

Changes to make:

- [ ] When I search for a concept by ID, the best result shows up at the bottom of the list, so I have to scroll down to find it. Can we invert the sort order here? (see screenshot)
- [ ] The "Add New Mapping" button is still there even when I am filling out info for the last mapping, but it doesn't work. Deferring to @paulsonder for the ideal behavior here but I imagine we either need to grey this button out or simply remove it until the mapping is either saved or removed. (see screenshot)
- [ ] When showing the preview for the source, it is currently only showing the ID. Should we show the ID and perhaps a short or full name too?

![image](https://user-images.githubusercontent.com/55999682/202710563-158710ba-613b-4da0-9be0-79b7c2c7f764.png)

**Comment by jamlung-ri** [comment]
Also noticing that I am not getting the option to add a new SAME-AS mapping. I only seem to get the option to add a new Q-AND-A mapping. See screenshot:

![image](https://user-images.githubusercontent.com/55999682/202711473-a44bc191-f341-4491-b0b6-b610dc3b04cf.png)

**Comment by jamlung-ri** [comment]
Future feedback e.g. just to document, not to implement yet:
* Adding a custom relationships type should be possible in the Quick Add workflow, probably following the same process that we used for locales

**Comment by snyaggarwal** [comment]
@jamlung-ri I have fixed/resolved a few comments/feedback. The remaining ones we will need to think/discuss.

**Comment by snyaggarwal** [comment]
@jamlung-ri We need a tooltip on all three fields. Otherwise, it will not look symmetrical or will have to ask Paul to change the design.
What do you think?

**Comment by paulsonder** [comment]
@snyaggarwal It's fine with me if some fields don't have tooltips.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is added

**Comment by jamlung-ri** [comment]
Alright, things are looking pretty good to me. There only seem to be a couple of loose ends to wrap up:

- [ ] Some names for concepts or sources are being truncated. When hovering over a truncated concept or source name, it should show the whole name. @paulsonder Was this something that your tooltip (#1435) would solve?  
- [ ] Just want to make sure that it looks okay when there are 0 associations for a concept. (See screenshot below @paulsonder)

![image](https://user-images.githubusercontent.com/55999682/204838358-e7bfe3f0-1d0b-42a0-b86a-4137435f3f4f.png)

**Comment by paulsonder** [comment]
@jamlung-ri 

1. Yes, that's the idea with the multi-line tooltip. We can have a review of that soon.
2. I think that looks OK for now. We have a ticket for 'empty states' open but not started, I think it'd be good to take a look at that soon.

**Comment by snyaggarwal** [comment]
@jamlung-ri @jamlung-ri @paulsonder Closing this as this is deployed everywhere. Please raise specific tickets for bug/feedbacks on this.
