### ISSUE TITLE
Fix Locales in TermBrowser

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1364]

**Comment by paynejd** [comment]
We are shifting the TB to default to 2-letter language codes (e.g. `en`) with an optional country code (e.g. `en-GB` or `en-gb` -- we haven't committed to a particular casing yet).

However, we have lots of existing data that uses 3-letter codes (e.g. `eng`), and it is very possible that some clients have a 3-letter code requirement, so we need to support non-default codes as a free text field (no dropdown needed for this).

**Comment by jamlung-ri** [comment]
Also linking to #757 since it might encompass the "data fixing" aspect of this work.

**Comment by jamlung-ri** [comment]
Documentation for new Locales approach: https://docs.google.com/document/d/12Jr2HbWFZsxR9_bY2dSTXBn39fAyKZGm2479YoUwqFo/edit

**Comment by bmamlin** [comment]
If it helps,

* [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) defines the combination of [ISO 639-1](https://www.iso.org/iso-639-language-codes.html) 2-letter language codes and [ISO 3316](https://www.iso.org/iso-3166-country-codes.html) country codes
* Java supported locales (e.g., [JDK11 supported locales](https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html)) use the BCP47 combination format, using data from [Unicode's CLDR 33](https://cldr.unicode.org/index/downloads/cldr-33)

**Comment by paynejd** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/1189689/194072646-c5399683-7708-4bcc-94d8-9c4c08dea76a.png">

**Comment by bmamlin** [comment]
From what I recall from today's discussion was:
* We define the set of "standard" language codes following [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt), using 2-letter lowercase language codes from [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) along with regional variants where a hyphen ("-") and a 2-letter capitalized country/region code from [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1).
* We develop a language widget that makes it easy to search and select default and supported languages from the list of standard language codes (e.g., showing code & language name in a lozenge).
* If an existing default/supported language is not in the list of promoted language codes (e.g., "eng"), the code will be shown in an alternative way that indicates it is not one of OCL's standard codes.
* When selecting a language, users's will be able to search & select across OCL's standard language codes and given the option (with confirmation) to add a "free text" code (something like the way GitHub allows issue labelling by promoting existing labels but allowing the creation of a new one when necessary).

**Comment by paulsonder** [comment]
The updated UI can support the above locale / language functionality and can be found [here](https://zpl.io/RMLx6w0).

**Notes**

- The language dropdown options are structured like so: [two digit code] [Label] [four digit code (if such a code exists)].
- If if a user wishes to add a non-standard code(s), the dropdown includes an option that allows them to launch a [modal](https://zpl.io/JEwj019) to complete this task.
- The default language field is a single select field. The Supported languages is multi-select.
- Default language is mandatory, supported languages are not.
- Once selected, languages are displayed as Chips. The default field chip does not include a delete button to indicate another selection must be made the replace it. 
- Chips are [color coded](https://zpl.io/r1nlGGL) according to whether they are two digit or custom. 

@jamlung-ri Could you please review the text in the modal window - I'd suggest we also call out that these are not standard codes but for custom coding but would like your input.

We also need tooltip text, could you draft v1 and we can review in here?

**Comment by jamlung-ri** [comment]
This should also include the API change with regards to Default and Supported Languages. Meaning, the Default language in the API should also be shown in the Supported languages field for sources/collections. However, the UI does not need to duplicate it. 

Example:
* In API:
   * Default language = 'en'
   * Supported languages = 'en','fp','sp'
* As shown in the UI 
   * Default language = 'en'
   * Supported languages = 'fp','sp'

Jon created a ticket for this: #1382

**Comment by jamlung-ri** [comment]
Putting below the text for the individual boxes and components. @paulsonder I welcome your input on this, given that we talked a bit about this in the OCL Dev call this morning. I think it keeps the general spirit of your mockups the same though.

@snyaggarwal Just wanted to note that there are slight differences between the field for Default and Supported Languages when it comes to the modal. See below.

1. In the dropdown where the user can begin entering text and select a language. If no options meet the need, the select `+ Add "[characters in search box]" as custom language code...`
2. A prompt appears to warn user of the risks and to confirm the custom code(s):
   * Prompt title: `Add custom language code`
   * Warning text: `[Alert Icon] OCL is optimized for 2-letter and 4-letter language codes (e.g. “en” or “en-GB”). Only use custom codes if absolutely necessary.` 
3. The user sees the language code (e.g. "eng") that was autofilled into the field, based on their search term from before. This text entry can be changed if desired by the user.
   * Label (when inputting Default Language): `Custom language code`
   * Label (when inputting Supported Languages): `Custom language code(s)`
   * Small text below field (when inputting Supported Languages): `Use a comma or space to separate multiple custom codes`
   * Validation for text field: Letters and “-” are allowed for language codes. Comma and space can be used to separate custom codes if applicable. No other characters e.g. numbers are accepted.
   * Tooltip: Language codes in OCL use the syntax “en” or “en-GB” in accordance with ISO 639-1, with an optional 2-letter country code following BCP47. OCL allows language codes in other formats, however these codes may limit certain features or be incompatible with client systems, like OpenMRS. Letters and “-” are allowed for language codes.

**Comment by paulsonder** [comment]
@snyaggarwal @jamlung-ri What happens if a user wants to add multiple custom codes? Do they need to **add** then **accept** the prompt each time?

**Comment by snyaggarwal** [comment]
I was thinking they can add multiple in one prompt

**Comment by paulsonder** [comment]
I feel like this is an overly complex interaction for what we're hoping should increasingly be an edge case over time.

Users will recognise the component as having the utility to search / filter a list. 

The idea to include inputted text in the '+ Add' label is OK, though I think it encourages the action, rather than the other way round.

I don't think adding multiple codes, comma separated inside the dropdown filter will be a recognised interaction behaviour for our users.

A key UX rule is recognisability over recall and I think this way violates that principle.

**Comment by jamlung-ri** [comment]
@paulsonder I was thinking that the action of adding multiple language codes (separated by comma or space) was part of the "Add custom code" prompt. Is that not the intent in the mockup? (See image below)

I don't think the intent is to change any behaviors from the mockup video or anything. We just wanted to make sure there is adequate language to help users understand why custom locales are discouraged but still enable them to use custom locales if needed. Happy to quickly chat about this if helpful.

![image](https://user-images.githubusercontent.com/55999682/195334060-61a5769e-f5b6-4982-8184-711d07e396a7.png)

**Comment by paynejd** [comment]
> @paynejd For this, we need to first add iso-639-1 locales to all the missing ones.

@snyaggarwal Can you clarify? ISO 639-1 is a shorter list than the 3-letter list. It may make sense for us to publish a new source for the combined ISO 639-1 plus country-codes -- what do you all think?

**Comment by jamlung-ri** [comment]
@snyaggarwal Just an FYI, Paul and I chatted about his concerns with the locales, and I was able to clarify our plans. We are now on the same page. His concern was that we wanted to nix the "Add custom language code" modal (partially due to my use of the word "prompt" instead of "modal").

Anyway, the behavior that we discussed (which should align with what is listed in [this comment above](https://github.com/OpenConceptLab/ocl_issues/issues/1364#issuecomment-1275197943)) is ready for development. Please move forward on this when you are ready.

**Comment by snyaggarwal** [comment]
> > @paynejd For this, we need to first add iso-639-1 locales to all the missing ones.
> 
> @snyaggarwal Can you clarify? ISO 639-1 is a shorter list than the 3-letter list. It may make sense for us to publish a new source for the combined ISO 639-1 plus country-codes -- what do you all think?

@paynejd the current locales list has ISO-639-1 (for example [abk](https://api.openconceptlab.org/orgs/OCL/sources/Locales/concepts/abk/)). We can just add these locales to the missing concepts, or I am ok with a new source for this as well. I would need this before I can finish the UI.

**Comment by paynejd** [comment]
There's a useful compilation of language data files for download here: https://datahub.io/core/language-codes#data

For the MVP, let's use `language-codes.csv`, which is ISO-639-1 2-letter codes

In the future, we may decide to load this directly from HL7 (see https://build.fhir.org/ig/HL7/UTG/CodeSystem-iso639-1.json.html)

### Metadata for import into OCL
**Org:**
* id: `ISO`
* name: `International Organization for Standardization (ISO)`

**Source:**
* ID: `iso639-1` (this is to match FHIR)
* Short name: `Iso6391`
* Full name: `ISO 639-1: Codes for the representation of names of languages -- Part 1: Alpha-2 code`
* Canonical URL: http://terminology.hl7.org/CodeSystem/iso639-1
* Description: "Codes for the Representation of Names of Languages Part 1: Alpha-2 Code. Used as part of the IETF 3066 specification for languages throughout the HL7 specification."

@snyaggarwal Let me know if more info is needed

**Comment by snyaggarwal** [comment]
@paynejd 
1. [Language-code.csv](https://github.com/OpenConceptLab/oclapi2/blob/master/core/samples/language-codes_csv.csv) is added and imported in [ISO / iso639-1](https://app.qa.openconceptlab.org/#/orgs/ISO/sources/iso639-1/) on system start (just like other lookup values)
2. Added API to get default [OCL Locales](https://api.qa.openconceptlab.org/locales/). This is driven from [settings](https://github.com/OpenConceptLab/oclapi2/blob/master/core/settings.py#L404) and can be overridden at the time of deployment.
3. TermBrowser uses /locales/ (default locales) API to fetch locales.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri @paulsonder this is now deployed on QA. Please give it a try.

**Comment by paynejd** [comment]
Why is there a dedicated API for locales rather than just configuring which
source should be used for locales (e.g. a relative URL)?

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed and deployed

**Comment by jamlung-ri** [comment]
Wanting to make a quick note about behavior (not sure if we want to change this or not): 
When you do a custom language code, we allow the user to "Add [code] as custom code"
![image](https://user-images.githubusercontent.com/55999682/197189673-9dd66c1b-242f-4e4f-910c-7acdc4bb8aa5.png)

However, when you click on that option, the text field in the modal is not populated with that code.
![image](https://user-images.githubusercontent.com/55999682/197189771-d54b4ba4-25d7-4e9f-9847-5d48e7b8b88a.png)

@paulsonder @paynejd Do you think the modal's text field should be populated with the code that the user tried to add in the first screenshot?

**Comment by paulsonder** [comment]
The behaviour in the implementation is different from the design.

The design recommends that the user is able to select 'Add custom code'
regardless of their input - this is giving control to users who may not
want to use supported code systems.

The approach on QA is problematic in two ways. A mis-type pushes them to
create a custom code, as there is no 'no results' message and it forces
those wanting to use custom codes to potentially mis-type to expose the
button.

For this version, let's allow users to be explicit by giving simple, clear
paths in the workflow.

The MVP design suggested allowing users to trigger a modal for custom
inputs, I think we should implement that first and iterate as we understand
more about how users interact.

**Comment by paynejd** [comment]
On the modal window:
* Change label from "Custom codes" to "Custom language code"
* Change placeholder from "Enter custom codes" to an example: `e.g. "eng" or "en-GB"`

**Comment by jamlung-ri** [comment]
> The behaviour in the implementation is different from the design. The design recommends that the user is able to select 'Add custom code' regardless of their input - this is giving control to users who may not want to use supported code systems. The approach on QA is problematic in two ways. A mis-type pushes them to create a custom code, as there is no 'no results' message and it forces those wanting to use custom codes to potentially mis-type to expose the button. For this version, let's allow users to be explicit by giving simple, clear paths in the workflow. The MVP design suggested allowing users to trigger a modal for custom inputs, I think we should implement that first and iterate as we understand more about how users interact.

I see what you mean. I think we asked Sunny to make the slight change to help guide users into NOT using custom codes where possible. However, I think the modal window now does that well, since we explain the risks of custom language codes. 

One question @paulsonder: We discussed today that inputting custom language codes should be something that a user does only one at a time, rather than allowing multiple code inputs separated by commas. Do you feel that this behavior change is okay, or will this be an issue? 

@snyaggarwal Can you make the following changes to match Paul's design:
* In the dropdown for Language, there should be a persistent option for "Add custom code" (note that this is not "Add [code] as custom code"
* The dropdown should be limited to 6 options plus this custom code

**Comment by paulsonder** [comment]
re: multiple codes: It feels a bit annoying to keep triggering a modal...
any reason we don't want them to do this?

**Comment by paulsonder** [comment]
My thinking in supporting this is that it's a multi-select, so if the
original component allows for multiple selections, then the custom option
would do too...

**Comment by jamlung-ri** [comment]
@paulsonder Sounds fair, let's allow the user to do this on the Supported Languages modal.

@snyaggarwal Will it be too much effort to have slightly different modal windows for Default Language vs. Supported Languages (in addition to the changes in [this comment](https://github.com/OpenConceptLab/ocl_issues/issues/1364#issuecomment-1286969711))? Since we would not allow multiple Default Languages, then the text will vary slightly between them. And we would be adding the functionality for users to be able to input multiple custom codes separated by commas (as per Paul's original designs).

If that is okay, then I will put the text variations below:
 

|                               | **Default Language Modal Text**                                                                                                                                                                                                                                                                                                             | **Support Language Modal Text**                                                                                                                                   |
|-------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Modal/Prompt title**        | `Add custom language code`                                                                                                                                                                                                                                                                                                                  | `Add custom language code(s)`                                                                                                                                     |
| **Warning text**              | `[Alert Icon] OCL is optimized for 2-letter and 4-letter language codes (e.g. “en” or “en-GB”). Only use custom codes if absolutely necessary.`                                                                                                                                                                                             | (Same as Default Language)                                                                                                                                        |
| **Field Label**               | `Custom language code`                                                                                                                                                                                                                                                                                                                      | `Custom language code(s)`                                                                                                                                         |
| **Small text below field**    | (None)                                                                                                                                                                                                                                                                                                                                      | `Use a comma or space to separate multiple custom codes`                                                                                                          |
| **Validation for text field** | Letters and “-” are allowed for language code. No other characters e.g. numbers are accepted.                                                                                                                                                                                                                                               | Letters and “-” are allowed for language codes. Comma or space can be used to separate custom codes if applicable. No other characters e.g. numbers are accepted. |
| **Tooltip**                   | Language codes in OCL use the syntax “en” or “en-GB” in accordance with ISO 639-1, with an optional 2-letter country code following BCP47. OCL allows language codes in other formats, however these codes may limit certain features or be incompatible with client systems, like OpenMRS. Letters and “-” are allowed for language codes. | (Same as Default Language)                                                                                                                                        |

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done

**Comment by snyaggarwal** [comment]
> > The behaviour in the implementation is different from the design. The design recommends that the user is able to select 'Add custom code' regardless of their input - this is giving control to users who may not want to use supported code systems. The approach on QA is problematic in two ways. A mis-type pushes them to create a custom code, as there is no 'no results' message and it forces those wanting to use custom codes to potentially mis-type to expose the button. For this version, let's allow users to be explicit by giving simple, clear paths in the workflow. The MVP design suggested allowing users to trigger a modal for custom inputs, I think we should implement that first and iterate as we understand more about how users interact.
> 
> I see what you mean. I think we asked Sunny to make the slight change to help guide users into NOT using custom codes where possible. However, I think the modal window now does that well, since we explain the risks of custom language codes.
> 
> One question @paulsonder: We discussed today that inputting custom language codes should be something that a user does only one at a time, rather than allowing multiple code inputs separated by commas. Do you feel that this behavior change is okay, or will this be an issue?
> 
> @snyaggarwal Can you make the following changes to match Paul's design: (and @paulsonder please edit this comment if I missed anything)
> 
> * In the dropdown for Language, there should be a persistent option for "Add custom code" (note that this is not "Add [code] as custom code"
> * The dropdown should be limited to 6 options plus the custom code option

@jamlung-ri @paulsonder this is done

**Comment by paynejd** [comment]
Looks great! Just one bug that I've found:
* `Default Language` allows a user to entry multiple custom codes (see screen shots below)
<img width="612" alt="image" src="https://user-images.githubusercontent.com/1189689/198030857-63480b77-82dd-4b05-82ab-b416dc7871ed.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1189689/198030895-401c1506-e15d-4524-a784-61308a9e585d.png">

**Comment by snyaggarwal** [comment]
@paynejd this will be deployed in few.

**Comment by snyaggarwal** [comment]
@paynejd this is deployed

**Comment by jamlung-ri** [comment]
Things seem to be working well for me on QA!

**Comment by paynejd** [comment]
One tiny change and then please deploy!

Current validation message:
* `Please match the requested format.`
* `Custom language codes may only have letters and hyphens, e.g. "eng"`

**Comment by snyaggarwal** [comment]
@paynejd these messages are coming from browser directly (html5). We can't customise this. Will have to write our own component for this.

**Comment by snyaggarwal** [comment]
Will use helperText from MUI to show a static message with the current message. Get rid of html5 error validation message

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Moving this to ready for deployment

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
