### ISSUE TITLE
OCL v2 Analytics

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1365]
Enhance OCL Analytics using the infrastructure available to us, including Clouwatch, Google Analytics, and OCL's databases.

**Comment by snyaggarwal** [comment]
What we have so far in OCL (tooling + queries):

1. Monthly Usage Report:
    - GET API (/admin/reports/monthly-usage/) returns HTML report
    - Monthly distribution of created/updated/active/inactive/total/lastLogin
2. Authored Report:
    - POST API (/admin/reports/authored/) takes list of usernames and returns JSON
    - Returns content created/updated counted per user.
3. Cloudwatch insights (queries and dashboard):
    - Most frequent users (Users making the most number of API requests)
    - Most common API requests
    - Client Distribution (Different Clients using OCL API)
    - Slowest APIs
    - Most frequent requests by users
    - Request Type distribution (GET/PUT/POST/DELETE)
4. Google Analytics (page views)
5. Hotjar
    - heatmaps
    - user session recordings

**Comment by paynejd** [comment]
Adding to Sunny's list, we also have MailChimp stats about the listserv subscriptions, opt-outs, email campaigns, etc. Here's one example:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/1189689/195597543-cdfb58ab-f83e-43e5-bdfa-07dc2f19024e.png">
