### ISSUE TITLE
Custom Sort/Order of Mappings for a Concept

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1369]

**Comment by paynejd** [comment]
Quick braindump on the API functionality for sorting of mappings:
* Implement a `sort_mappings` boolean attribute that is false by default
* If `sort_mappings` is enabled, then source admins may edit a `mapping.sort_order` double attribute
* If `sort_mappings` is enabled, then both OCL API and TermBrowser should respect that attribute in queries, cascade, etc.
* Note that OpenMRS only supports sorting for certain types of mappings (e.g. answers and set members?)
  * Do we allow dictionary admins to enable sorting for only certain map types?

cc @bmamlin @jamlung-ri

**Comment by bmamlin** [comment]
Some additional sort-related thoughts:
* Sorting applies within a single map type
* We need to be able to import & export a numeric sort weight
* Sorting is done by ascending sort weight (smaller number first)
* Need to support sort weights that are decimals (at least during import)

**Comment by jamlung-ri** [comment]
Note that this is primarily used by OpenMRS with CONCEPT-SET and Q-AND-A map types, but this could potentially apply to any map type.

There should never be two sort weights that are identical within a map type for one concept. For example, you can't have sort weight values 1, 2, 2, and 3. Sort weights can be empty, at least as far as OpenMRS is concerned. Meaning, sort weight is not assigned until the user explicitly applies one. It may be beneficial to auto-assign sort weights any time a mapping is created

Previously, OpenMRS stored the sort weight in an extra attribute. Sort weight value does not have to be any specific value, but you need to be able to reorder all mappings or insert a new mapping in between two others. This is the reason for having decimals.
