### ISSUE TITLE
Incorrect behavior for /users/ and /orgs/ endpoints from web UI

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#137]
An authenticated API user may use the `/users/` and `/orgs/` endpoints, but these are not valid endpoints in the web interface. However, the web UI for `/users/` returns an error, and `/orgs/` returns the JSON API results.

**Comment by rkorytkowski** [comment]
https://qa.openconceptlab.org/orgs/ and https://qa.openconceptlab.org/users/ are valid REST endpoints, which need to be exposed by web for web ajax calls. 

/users/ currently returns 401 for users other than admins
/orgs/ returns a list of orgs for any user including not authenticated

Are you observing a different behavior? Shall we show users to non admins as well?

**Comment by paynejd** [comment]
Shouldn't the ajax calls be using the API endpoints and not the web
endpoints?

**Comment by rkorytkowski** [comment]
We don't store an API token in the browser rather on the UI server, which
does all API requests. I guess it's why devs decided to proxy Ajax calls. I
don't think it makes sense now to fix that for just a few Ajax calls we do
from the UI. Let's call it tech debt.
