### ISSUE TITLE
"Add to collection" failing on a particular CIEL concept - cascade bug?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1370]
Grace Potma was showing me a bug in OCL Production when trying to add a CIEL concept using the $cascade method. When trying to add a concept with class ConvSet ([162553](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/162553/)) using the option to Cascade Mappings + Target Concepts, it appears that most concepts were added into the collection, with the exception of 162553 itself. The error said "Concept fully specified name must be unique for same collection and locale", even though there was not already a concept with that name in the [collection](https://app.openconceptlab.org/#/orgs/openmrs/collections/CIELAllergySet/). See image below for the error. 

My thought is that, because CIEL has mappings to itself, perhaps the Cascade method tried to add the concept twice. In finding the conflict, OCL ended up adding neither. 

[Recording of the issue in action](https://drive.google.com/file/d/1cAY2FD-Unh_6_S0VtlpEeq-7P4fosp02/view?usp=sharing) (pay attention to the Tuberculosis concept 112141 and the Common Food Allergens concept 162553)

Workaround for now: Add the individual concept without using Cascade to Target Concepts

![image (7).png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/37e45311-0280-4c8b-bb34-e64466894de6)

**Comment by snyaggarwal** [comment]
@jamlung-ri I can see [162553 ref](https://app.openconceptlab.org/#/orgs/openmrs/collections/CIELAllergySet/references?q=162553&isTable=true&isList=false&page=1&exactMatch=off) is added to that [collection](https://app.openconceptlab.org/#/orgs/openmrs/collections/CIELAllergySet).
I think, in this case, it tried to add the first concept and was successful and tried again and failed, the response returned is unique references and the success one got removed.
Can you tell me if this make sense?

**Comment by gracepotma** [comment]
Hi @snyaggarwal sorry to bother you but any updates on this issue, or approximate ETA on when the fix will be released? Some folks in the community are asking me about it.

**Comment by snyaggarwal** [comment]
Hey @gracepotma , 
I will be working on this, this week. Will keep you updated on the progress. The expected ETA is this Friday.

**Comment by paynejd** [comment]
cc @snyaggarwal 

I created a new source in QA that we can use to test cascade functionality:
https://app.qa.openconceptlab.org/#/users/ocladmin/sources/CascadeTest/

The source has the following characteristics that we want to test using cascade:
* 2+ levels of hierarchy
* 2+ levels of internal mappings for at least one maptype (e.g. such as Q-AND-A or CONCEPT-SET)
* 1+ levels of internal mappings for at least one other maptype (e.g. _not_ Q-AND-A or CONCEPT-SET)
* 1+ external mappings
* 1+ Self-maps
* 1+ Recursive maps (where a child is associated with a concept higher up in the tree that would cause recursion if the cascade algorithm doesn’t catch it)

**Comment by paynejd** [comment]
Bug:
* Hierarchical results only show up with HEAD or if no source version is specified -- compare these results: 
  * **HEAD** - hierarchical results are included here, even though the hierarchy was defined before releasing any versions; note that this also works if I omit HEAD, which means that Cascade may not be correctly handling `latest` -- https://api.qa.openconceptlab.org/users/ocladmin/sources/CascadeTest/HEAD/concepts/AA/$cascade/?cascadeLevels=1&method=sourceToConcepts&view=hierarchy&includeRetired=false
  * **v3** - hierarchical results are NOT included, even though the hierarchy was defined before releasing any versions -- https://api.qa.openconceptlab.org/users/ocladmin/sources/CascadeTest/v3/concepts/AA/$cascade/?cascadeLevels=1&method=sourceToConcepts&view=hierarchy&includeRetired=false

**Comment by snyaggarwal** [comment]
@gracepotma Apologies, but this was not picked up last week due to some urgent issues. Will try and get this done this week.

**Comment by jamlung-ri** [comment]
@snyaggarwal A small update on this ticket - this past Monday (before the latest Production deployment), Laure from MSF was showing us a similar issue in TermBrowser, and it seemed to perhaps overlap with a validation error from the OpenMRS Validation Schema. 

A question related to this: If someone were to try to add a concept to a collection, plus cascade to its mappings + target concepts, but the OpenMRS Validation Schema returns an error for the original concept, will the cascading aspect still happen? 

Also, I think we require reference expressions to be unique, but do we allow both reference "/orgs/[org]/sources/[source]/concepts/[concept]/" and "/orgs/[org]/sources/[source]/concepts/[concept]/$cascade" to be part of the same collection? I think the answer is no but wanted to check.

**Comment by jamlung-ri** [comment]
I think this has been worked out by this point. I just tested it a bit and didn't find any issues. We've made a lot of fixes to this lately that likely addressed the issue. I think we can close this ticket out.
