### ISSUE TITLE
Association Visualization window bug?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1372]
When viewing a concept in the Hierarchy Visualization on Production, there are some concept nodes that are appearing offscreen, and I am unable to scroll to the right to view those nodes.

This is occurring both in my Firefox and Chrome browsers, but only on some concepts like [A15](https://app.openconceptlab.org/#/orgs/WHO/sources/ICD-10-WHO/concepts/A15/).

This is not a high priority but feel free to look into it this sprint if time allows.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/cddb2ca4-7ce7-49c7-981a-62233e66134f)

**Comment by snyaggarwal** [comment]
deployed this to QA

**Comment by jamlung-ri** [comment]
Using QA to view content from Production, this appears to be fixed and working well.

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
