### ISSUE TITLE
Login via the OCL API says no such user for accounts created before qa reset

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#138]
Trying to login with accounts created before qa or demo are reset fails. The credentials work on the old OCL, albeit with an error page.

**Comment by rkorytkowski** [comment]
Qa and demo reset is supposed to delete all accounts. Could you please give examples of credentials that you found working after reset in old OCL?

**Comment by Karuhanga** [comment]
Username: `karuhanga`
Password: `tM27p!M!zH`

**Comment by HerbertYiga** [comment]
Facing the same error as above and cannot login in the new OCL!!!!

**Comment by rkorytkowski** [comment]
The web service wasn't scheduled to be reset together with API so your user still existed in WEB layer even though it was deleted in API. Fixed it.
