### ISSUE TITLE
Default language should automatically be added to Supported Languages for sources/collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1382]
Requirement: Supported languages should have everything, including the default

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA.

**Comment by jamlung-ri** [comment]
This is working well in QA. In the API, I can see the Default Language in the Supported Languages field, even for sources and collections that I created a while ago. In the UI, I can create a source and only fill out the Default Language field, and that value appears in the Supported Languages field too.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Can we move this to ready for deployment?

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
