### ISSUE TITLE
Fix OCL Docs on ReadTheDocs.org

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1385]
The ocl-docs project on readthedocs.org (https://readthedocs.org/projects/ocl-docs/) is no longer synchronizing with the ocl-docs GitHub repo (https://github.com/OpenConceptLab/ocl-docs).

**Comment by snyaggarwal** [comment]
This is fixed. The new build passed.
"sphinx_markdown_tables" was upgraded.

**Comment by snyaggarwal** [comment]
@paynejd Please verify and close this.
