### ISSUE TITLE
Compile MER FY23 reference indicators into spreadsheet

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1386]
MER FY23 (v2.6.1) Indicator Reference Guide was released in Sep-2022 here: https://datim.zendesk.com/hc/en-us/articles/360000084446-MER-Indicator-Reference-Guides

Same as previous years, we will manually prepare an OCL CSV bulk import file here:
https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit#gid=1201349643

**Comment by jamlung-ri** [comment]
This is complete. [The MER Metadata spreadsheet](https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit#gid=1201349643) has been filled with FY23 content, and the [Key Updates](https://github.com/OpenConceptLab/msp_metadata/wiki/Current-MER-Key-Updates-and-Changes) [sections ](https://github.com/OpenConceptLab/msp_metadata/wiki/Full-List---MER-Key-Updates-and-Changes)of OCL's wiki have been updated.
