### ISSUE TITLE
Setup Celery Beat Service

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1387]
- [x] Local setup
- [x] Infra

**Comment by snyaggarwal** [comment]
@rkorytkowski Blocked due to https://github.com/OpenConceptLab/oclapi2/pull/278#issuecomment-1291535538

**Comment by snyaggarwal** [comment]
@rkorytkowski this is now unblocked as we have [forked flower](https://github.com/snyaggarwal/flower) and merged the fix.

**Comment by rkorytkowski** [comment]
Deployed to QA! Thanks @snyaggarwal for your work on this one!

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
