### ISSUE TITLE
User account/permission issues

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#139]
May be true on other environments, but I experienced these issues on production:
* Received "The system just encountered an error!" when accessing user profile: https://openconceptlab.org/users/datim-admin/
* ocl_web does not show "create new repo version" button even though datim_admin user is a member of the org: https://openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY19/versions/
* I browsed directly to https://openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY19/versions/new/ and was not authorized to create a new source version
* ocl_web does not show button to edit a concept and I was not authorized to edit the concept when browsing directly to the edit page and hitting submit: https://openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY19/concepts/HTS_TST_N_MOH_Age_Agg_Sex_Result/

**Comment by paynejd** [comment]
Quick note: Logged as a superuser (paynejd), I still do not have access to make the above edits via ocl_web

**Comment by Karuhanga** [comment]
This might be causing this(https://github.com/OpenConceptLab/ocl_issues/issues/138) as well.

**Comment by paynejd** [comment]
@snyaggarwal Please note this documented permissions bug as you plan out permissions after the launch of oclapi2

**Comment by aprilcurrier** [comment]
Waiting on est until all requirements are outlined

**Comment by aprilcurrier** [comment]
Closing to be continued in #373
