### ISSUE TITLE
Change 'Org' icon

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1392]
The icon we use to represent an 'Org' is typically the same as the one that indicates 'Home' in other apps.

I'd like to switch it to use: AccountBalanceIcon from '@mui/icons-material/AccountBalance'

This more appropriately represents an institution than the current icon.

<img width="214" alt="Screenshot 2022-10-26 at 11 13 29" src="https://user-images.githubusercontent.com/95474174/197999180-9cf2f437-9bd4-4d5d-a6b2-df2d133fa86d.png">

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Can you please approve this ticket? 
It's a small change in TermBrowser, but does it need to be changed anywhere in the OCL community site/docs?

**Comment by jamlung-ri** [comment]
I searched the Community Site and the Docs, and I could not find any org icons that might be affected. However, we do use the "AccountBalance" icon on the Community Site to designate the OCL Architecture call. We might need to choose another icon for that if we don't want there to be a conflict.
![image](https://user-images.githubusercontent.com/55999682/198286153-aee9a416-e58f-45b0-8e8b-682a5f20fad7.png)

**Comment by paulsonder** [comment]
Good catch @jamlung-ri 

How about this for Architecture call? 

<img width="598" alt="Screenshot 2022-10-27 at 16 04 54" src="https://user-images.githubusercontent.com/95474174/198307277-802c9782-5ffa-4059-808a-8fe29183c636.png">

**Comment by jamlung-ri** [comment]
@paynejd Thoughts on icon switching?

**Comment by paynejd** [comment]
These both look great!

Just FYI, the Architecture call icon would need to be changed on the
Community Site and in the TermBrowser

**Comment by snyaggarwal** [comment]
@paulsonder this is deployed on QA

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
