### ISSUE TITLE
Remove border from owner [chip] in table

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1393]
There doesn't seem to be an obvious reason for the extra emphasis created by placing the owner name in the 'owner' table column inside a chip with a border.

Could we please remove this, leaving the owner icon and name?

I think this will contribute to an altogether simpler aesthetic.

**Comment by snyaggarwal** [comment]
@paulsonder this is added

**Comment by paulsonder** [comment]
Thanks Sunny!

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
