### ISSUE TITLE
Retired concepts seem missing ~Search for CIEL concept 162339 does not work~

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1394]
Steps: See video: https://www.loom.com/share/51fccc25fcb04bdf896f502a5ad7f7c2 

CC @jamlung-ri & @snyaggarwal 

This also does not work if you search for 162339 within the CIEL source itself: 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/67400059/198158791-824d1ba7-9a79-4376-92b2-aba7495689a8.png">

**Comment by gracepotma** [comment]
Okayyyyyy I feel silly - so it seems this is a retired concept - as shown deeper in the concept's UI: 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/67400059/198158916-d2c4035f-d962-4949-bbc2-6c2766c00346.png">

It would help if the "We found 0 Concepts" message perhaps  also said "Consider adjusting the search filter to include Retired concepts" or something to that effect. 

When I turn Retired=true on, the search successfully resolves. 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/67400059/198159042-309fe0bd-f45b-4d44-b022-333657efc03d.png">

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder Perhaps a quick fix here could be that, if the search yields one or more Retired concepts (example in screenshot below), maybe the text `We found 0 Concepts.` could be changed to `We found 0 Concepts. Would you like to view # Retired concept(s)?` where the # is the number of Retired concepts, and the `view # Retired concept(s)` string is hyperlinked to immediately apply the Retired filter. Thoughts?

![image](https://user-images.githubusercontent.com/55999682/198286997-de57bf92-5f12-44c0-81cc-e0d626c21827.png)

**Comment by jamlung-ri** [comment]
@gracepotma Just wanted to note that the OCL Search Experience is its own UI initative that OCL has on our priority list. Even if we cannot make a quick fix here, just note that this is on our radar. :)

**Comment by paulsonder** [comment]
Yep, love that idea Joe. May we could design empty states for the tables?
If retired concepts exist, we can add that hyperlink to display them?

But as a quick fix, I think we can go for it and I'll create a ticket for
empty states for me to pick up as part of the DS epic.

**Comment by gracepotma** [comment]
Sounds great, thank you both!!

**Comment by jamlung-ri** [comment]
@snyaggarwal Are you good to move forward on some quick development here?

**Comment by snyaggarwal** [comment]
@jamlung-ri This is added on QA

**Comment by paulsonder** [comment]
Nice job @snyaggarwal - I've created a ticket for 'empty state' UI that we can prioritise for another sprint.

**Comment by snyaggarwal** [comment]
@jamlung-ri Let me know if this can be moved to Ready for Deployment

**Comment by jamlung-ri** [comment]
Looks great! Let's move it to Ready for Deployment.

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
