### ISSUE TITLE
Split localized_text into 2 tables

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1399]
Separate names and descriptions

**Comment by snyaggarwal** [comment]
Steps:

- [ ] ConceptDescription Model and table with Concept as FK
- [ ] COPY only descriptions from localized_texts (data migration)
- [ ] Create duplicate descriptions entry for the latest version same as Concept (data migration)
- [ ] Rename localized_texts to concept_names
- [ ] Add Concept FK in concept_names and establish one-to-many relationship with duplicate entry for each many-to-many relationship.
- [ ] Code for new relations – tests
- [ ] Delete descriptions from localized_texts
- [ ] Delete descriptions from localized_texts 
- [ ] Drop many-to-many tables concepts_names and concepts_descriptions

**Comment by snyaggarwal** [comment]
@rkorytkowski Raised PR https://github.com/OpenConceptLab/oclapi2/pull/318

**Comment by snyaggarwal** [comment]
Deployed on Staging.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on production. Closing this.

**Comment by paynejd** [comment]
Congratulations!!

Do we need to provide upgrade instructions for orgs that are self-hosting?

**Comment by snyaggarwal** [comment]
these are migrations, so they wont have to do anything. It will take care of itself on restart
