### ISSUE TITLE
Action menu

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1403]
Design documentation for the **Action menu** component.

**Comment by paulsonder** [comment]
Design docs can be found here: [https://zpl.io/RMvdGov](https://zpl.io/RMvdGov)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder This, I think, is done in almost all places. Let me know if I missed any place, for now moving this forward.

**Comment by snyaggarwal** [comment]
this is mostly done everywhere and deployed. Please open specific issues separately, closing this.
