### ISSUE TITLE
Supporting multiple parameters in Expansions

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1406]
When multiple values can be specified within one parameter, what syntax should be used? Ideally, FHIR describes how you might do this.

Examples:
`?system_version[]=https://foo.com&system_version[]=https://bar.com`
or 
`?system_version=https://foo.com,https://bar.com`

**Comment by snyaggarwal** [comment]
this is deployed on QA. Please use below syntax
`?system_version=https://foo.com,https://bar.com`

**Comment by snyaggarwal** [comment]
this is deployed everywhere.

**Comment by snyaggarwal** [comment]
Deployed everywhere. Closing this.
