### ISSUE TITLE
Implement Suggested Sources feature for sources

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1408]
Separating out the implementation of the Preferred sources feature for sources from linked sources and preferred sources for collections. #1188 is now only Linked Sources.

**Comment by jamlung-ri** [comment]
Initial requirements for Preferred Sources can be seen here: https://docs.google.com/document/d/1Yq_H6QHr9ptJ6WUbu0NKNxizsdApsiI_ayDhpnJbEdg/edit#heading=h.lq3bfnivh44z

@paynejd and @paulsonder Please provide initial feedback and comments as needed.

**Comment by jamlung-ri** [comment]
Actually Jon and I discussed this and changed direction a bit to try to make a smarter Source Selector. I want to fix up this documentation a bit more.

**Comment by paulsonder** [comment]
@snyaggarwal Please find the designs with descriptions for the Suggested Sources Action List UI here.

https://zpl.io/Q0xwj49

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Is this ready for development? 
If yes, then can you paste here the link of requirements document.

**Comment by jamlung-ri** [comment]
@snyaggarwal This is ready for development. The full requirements document is here: https://docs.google.com/document/d/1Yq_H6QHr9ptJ6WUbu0NKNxizsdApsiI_ayDhpnJbEdg/edit#heading=h.su5wk7vvt4nb

For the MVP of the Suggested Sources feature: 

- What to create: See [this Zeplin design](https://app.zeplin.io/project/61d73b9f4187e7636b96e741/screen/63873a10d2c272b8c3c990bf) - All three of the components in the design are required for the MVP. Further details for each component:
    - Component "Action menu with filter (focussed)": When clicking on the field to 'select a source', the Suggested Sources list should immediately appear, which is populated with a set of sources, each with a label, using the following order:


> Within the "Suggested Sources" section:
> 1. _Current Source_: The current source that is being accessed and managed by the user. There should only be one source with this label in the Suggested Sources section.
> 2. _Last Used_: The source most recently used as part of a mapping created within this source, excluding the _Current Source_ itself. There can be only one _Last Used_ source. The logic for determining the _Last Source_ should consider these things:
>             
>     * Happy path: The mapping that was created most recently in this source links a concept from the _Current Source_ with a concept from any other source (regardless of which source is the 'to' and and which is the 'from' side of the mapping). That other source should be what appears as the _Last Source_.
>     * Exception: Mappings should not be used to calculate the _Last Used_ source if the 'to' and 'from' concepts of the mapping are both in the _Current Source_. If this happens, go to the next most recently created mapping in the source.
>     * Edge case: If the most recently created mapping in the source does not have the _Current Source_ as either the 'to' and 'from' concept of the mapping, then return the 'to' side of the mapping as the _Last Used_ source. The 'from' side of the mapping should appear in the _Recently Used_ section (see below).
>           
> 3.  _Recently Used_: Similarly to _Last Used_, there can be up to four additional sources that have recently been used as part of a mapping. The same logic as above will apply - the only difference for the _Recently Used_ sources is the label. To be clear, the most recently used source should be labelled with _Last Used_, and then the next most recently used sources should labelled with _Recently Used_.
> 4. _Popular_: If the OCL instance has a "Promoted Sources" configuration, then this will appear in the Suggested Sources list with the _Popular_ label. Only the first four sources of this configuration should be used. Note that this configuration is optional - OCL's environments may not configure this yet. If this is technically complicated, please let us know and ignore this for the Suggested Sources MVP.
> 
> Within the "My sources" section:
> 1. (No label) Other sources that are owned by the user. No more than 5 sources should be included in this section, showing the 5 most recently created or updated sources owned by that user. **Question: Should source owned by the user's orgs appear here also?**


     - Component "Action menu with filter (search loading)": If a user does not find the source they expect in the Suggested Sources list, they will type a character. When searching, this "search loading" state should appear until search results have been returned.
     - Component "Action menu with filter (search results)": Once search results have loaded for the user's query, the first 5 results most relevant to the search term should appear in the list. This may include sources owned by the user.

- Where to implement this: For now, only add this to the Quick-Add Mappings feature in the "Source" selector. In another ticket, this can be added in other "Source" selectors in the TermBrowser.
- Notes: The Suggested Sources list is deduplicated. Meaning, if a source has already been used as the _Last Used_ source, then it should not reappear with the _Popular_ label.

**Comment by paulsonder** [comment]
@paynejd Happy with described approach. 

cc: @snyaggarwal @jamlung-ri

**Comment by jamlung-ri** [comment]
This approach sounds good to me. Thanks for discussing and breaking it out into more feasible chunks!

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd @paulsonder the first cut of this is deployed on QA.

**Comment by jamlung-ri** [comment]
@snyaggarwal This is a great start! Overall, I am finding it working well. A couple things that I am noticing:

- [ ] When I create a mapping to a source that I have not used before, the Source dropdown does not update to show it for the next mapping I want to make unless I reload the concept (i.e. un-select then re-select the concept I am working on). Can the `mapped-sources` API refresh automatically when a mapping is Quick-Added, at least if the new source is not already a part of the Suggested Sources list? 
- [ ] It looks like longer org IDs are getting truncated if they are more than 12 characters. Maybe there should be a hover tooltip for truncated org IDs in the Source dropdown? (See [screenshot](https://user-images.githubusercontent.com/55999682/206530923-bc758e25-d79a-464d-b3b7-df76d32858df.png) where 'International...' is cut off)

**Comment by snyaggarwal** [comment]
> @snyaggarwal This is a great start! Overall, I am finding it working well. A couple things that I am noticing:
> 
> * [x]  When I create a mapping to a source that I have not used before, the Source dropdown does not update to show it for the next mapping I want to make unless I reload the concept (i.e. un-select then re-select the concept I am working on). Can the `mapped-sources` API refresh automatically when a mapping is Quick-Added, at least if the new source is not already a part of the Suggested Sources list?
> * [x]  It looks like longer org IDs are getting truncated if they are more than 12 characters. Maybe there should be a hover tooltip for truncated org IDs in the Source dropdown? (See [screenshot](https://user-images.githubusercontent.com/55999682/206530923-bc758e25-d79a-464d-b3b7-df76d32858df.png) where 'International...' is cut off)

@jamlung-ri these are done

**Comment by jamlung-ri** [comment]
I have tested this a few times and have found a lot of success with it. It makes it so much easier to do the Quick-Add Mappings! I think this is in good shape to deploy.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere.
