### ISSUE TITLE
Hierarchy Display Name Bug in Associations section

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1409]
I noticed that when looking at the hierarchy for an ICD-10 test source (and also in LOINC in Production) that names are not displaying properly for parent/child concept names in the Associations section. It is working fine in the hierarchy on the left side, however.

[ICD-10](https://app.qa.openconceptlab.org/#/orgs/WHO-ICD-Test/sources/ICD-10-Test-Small/concepts/A15/)
![image](https://user-images.githubusercontent.com/55999682/199815005-fbb60233-e363-4032-a82b-2fb78936164f.png)

[LOINC](https://app.openconceptlab.org/#/orgs/Regenstrief/sources/LOINC/concepts/LP14449-0/)
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/b97d9b2e-ed5f-47fe-8016-d561b4ff6399)

**Comment by snyaggarwal** [comment]
There was a typo. This is fixed now.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere. Please close if all look good

**Comment by jamlung-ri** [comment]
Never mind, I needed to clear my cache. Closing this!
