### ISSUE TITLE
CIEL HEAD version on openconceptlab.org showing incorrect date

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#141]
The date shown here(https://openconceptlab.org/orgs/CIEL/sources/CIEL/versions/) on the HEAD version does not look right. Additionally, the most recent CIEL version here is from last year. This does not seem right.

**Comment by paynejd** [comment]
We would need to import the latest version of CIEL -- is the latest version
needed now for the project?

**Comment by Karuhanga** [comment]
Yes, request was made by Darius on the last call.
https://talk.openmrs.org/t/updating-the-ciel-library-urgent/24369
