### ISSUE TITLE
Advice on speeding up PEPFAR indicator mapping exports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#142]
@rkorytkowski -- would like your advice on speeding up PEPFAR's indicator mapping (IMAP) exports.

We have implemented an OpenHIM server with a mediator that provides an API endpoint to download an export of a country's indicator mappings (IMAP). The mediator runs a python script and returns the results as CSV, JSON, XML, or HTML. Here's the relevant code:
* https://github.com/OpenConceptLab/ocl_datim/blob/master/datim/datimimapexport.py#L189
* https://github.com/OpenConceptLab/ocl_datim/blob/master/datim/datimbase.py#L225

OCL stores an IMAP in a series of collections, each collection representing a set of mappings for a single indicator+disaggregate pair. The script fetches the contents of each collection using the OCL export API, which redirects each request to AWS to send a cached export. Requesting a cached export from AWS typically takes 2-3 seconds. Since each IMAP export could be represented by as many as 50 collections in OCL and the cached collection exports are requested from AWS in sequence, this can be an unacceptably long-running process (<1 min for really small IMAPs, or >2 min for larger IMAPs).

There are a few options I've thought of to speed this up:
* Optimize the AWS request --- can we get this request down to <2 sec?
* Run AWS requests in parallel --- what load of simultaneous requests can OCL and AWS handle?
* Cache the IMAP export --- this would reduce processing time for static IMAP exports to a minimal amount of time, but this would not provide any benefit while IMAPs are being created/updated, which is where the primary bottleneck is

Would you be able to take a quick look at this and recommend some approaches to try?

**Comment by maurya** [comment]
Test info - 
For `ZM` country code the whole imap export script took ~`73s` of which the export took ~`70s`
For `DEMO` country code (which has 10 records) the whole imap export script took ~ `11s` of which the export took ~ `8s`

**Comment by paynejd** [comment]
Went with running the exports as async requests using the grequests module. Export time reduced significantly -- thank you both for the advice!
