### ISSUE TITLE
Refactor how OCL FHIR Core $expand interacts with OCL expansions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1422]
Queue up refactoring of how OCL handles $expand request – When do we create a new expansion vs. use an existing one? Should we always persist expansions or do we ever want to just process on the fly? Should FHIR take advantage of OCL’s auto-expand features?

Short-term solution: Disable auto-expand on valuesets created from FHIR, and always create a new expansion for each $expand request

**Comment by rkorytkowski** [comment]
The new behaviour for $extend is:
When you do a GET request to $extend then you are being returned the latest existing expansions that matches your params. If it does not exist then 404 is returned. If you do a POST request to $extend then always a new expansion is created.
