### ISSUE TITLE
New Cascade Option for OpenMRS 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1424]
When adding a concept to the collection and this Cascade prompt appears (see screenshot), there will be a fourth option: "OpenMRS Cascade". 

Tooltip: 
_A specialized cascade option for OpenMRS that, for each selected concept, adds the concept AND all its mappings and any concepts that are answers or set members (i.e. concepts that are associated by a "Q-AND-A" or "CONCEPT-SET" map type) if they are in the same source as the selected concept(s)._

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/ac4d87bb-b215-4aba-b6c5-356fc3ba8331)

Parameters to use in this option:
* `levels = *` (meaning, this should continue cascading until all Q-AND-A and CONCEPT-SET mappings and target concepts are terminal or have already been returned)
* `mapType=CONCEPT-SET,Q-AND-A` (meaning, keep cascading through mappings where the map type is either one of these two types as long as both concepts are part of the same source)
* `returnMapType=*` (meaning, all mappings should be returned for each concept in the results, even if the target of the mapping is outside the original concept's source)

@snyaggarwal This is something that we are hoping to have a quick turnaround time on release. An example of the expected returned concepts/mappings is in [this spreadsheet](https://docs.google.com/spreadsheets/d/1hxRMKVcgrg9LVjzSLbd_rM9R3xN6rtAflvbymXgQzKw/edit#gid=0) (see tab "CIEL:161499")

cc: @paynejd @bmamlin @paulsonder - if anything here needs to be changed, please edit my comment with suggestions or feel free to discuss via Slack. Keep in mind that this is a quick functional solution which will be followed up by more design and UI/UX work in the future.

**Comment by paynejd** [comment]
@snyaggarwal Could you do a quick write out (in this ticket) all of the parameters that are used for each of the existing 3 options? Let's verify that we have the correct behavior for all options and let's also refine the tooltips to make the behavior more clear. For parameters, make sure to include `transformReferences`.

Thank you!

**Comment by paynejd** [comment]
@jamlung-ri Looks good -- only thing that we'll need to add is the `transformReferences` behavior.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA.

**Comment by snyaggarwal** [comment]
@paynejd Do we need to add `transformReferences=true` by default as part of the OpenMRS Cascade option?

**Comment by paynejd** [comment]
@snyaggarwal Yes please enable transformReferences for the Openmrs option.

@snyaggarwal Could you list (in this ticket) the add reference/cascade params that are used for each of the cascade options?

**Comment by snyaggarwal** [comment]
Current Reference add cascade options parameters:
1. Cascade to associated mappings in the same source -- `?method=sourcemappings&cascadeLevels=1`
2. Cascade to associated mappings and target concepts in the same source -- `?method=sourcetoconcepts&cascadeLevels=1`
3. OpenMRS Cascade -- `?method=sourcetoconcepts&cascadeLevels=*&map_types=Q-AND-A,CONCEPT-SET&returnMapTypes=*&transformReferences=resourceVersions`

**Comment by snyaggarwal** [comment]
@paynejd this is now deployed on QA with transform.

**Comment by jamlung-ri** [comment]
I am seeing a bug when adding this reference now. I get a message that says "0 References Added" but the reference does get added into the collection. Loom video: https://www.loom.com/share/bff80c4f468642f7b5720a67c625798f

Also noting that this now creates a static reference i.e. "/orgs/CIEL/sources/CIEL/concepts/664/2442/". This is a result of the `transformReferences=resourceVersions`, right? @paynejd is this intentional that we are pointing to a specific version of the reference instead of pointing to the latest version? If so, the tooltop might need to be updated to reflect that.

One other note: we don't have the translation for this in the References tab (see screenshot and [reference in API](https://api.qa.openconceptlab.org/users/ocladmin/collections/omrs-test/references/974979/)). Since it uses the OpenMRS cascade method, maybe we just say "Include concept xxx from CIEL/CIEL using the OpenMRS Cascade method" ?

![image](https://user-images.githubusercontent.com/55999682/200597651-aa1958e4-6b22-4a9c-a376-89389cfc2011.png)

**Comment by paynejd** [comment]
The OpenMRS cascade method has to transform to all static references, so
there should not be any "cascade" parameters in the references that are
ultimately added to the collection

**Comment by snyaggarwal** [comment]
@paynejd `transform` + `cascade` is currently not resolving to multiple static references. Its currently stays as single [reference](https://api.qa.openconceptlab.org/users/ocladmin/collections/omrs-test/references/974979/) with concepts and mappings resolved to latest versions.

**Comment by paynejd** [comment]
@snyaggarwal At some point, I remember that you documented the order in which each part of a reference is processed -- do you know where this is? Should we recreate that and at it to our documentation? Let's review and see if we need to queue up any work on this.

**Comment by snyaggarwal** [comment]
@paynejd I couldn't find that in any of the ticket in past (but I remember we did create it). I will recreate it.

**Comment by snyaggarwal** [comment]
> I am seeing a bug when adding this reference now. I get a message that says "0 References Added" but the reference does get added into the collection. Loom video: https://www.loom.com/share/bff80c4f468642f7b5720a67c625798f

@jamlung-ri this should be fixed now

**Comment by jamlung-ri** [comment]
> > I am seeing a bug when adding this reference now. I get a message that says "0 References Added" but the reference does get added into the collection. Loom video: https://www.loom.com/share/bff80c4f468642f7b5720a67c625798f
> 
> @jamlung-ri this should be fixed now

This bug is fixed now. We of course are trying to figure out our approach on the Arch call now, but I did want to report another bug that seems to be persisting. It will probably need to be tackled in another ticket though. The exclusion of an individual concept is still clearing out the entire collection. [Example collection](https://app.qa.openconceptlab.org/#/users/ocladmin/collections/omrs-test/) (see screenshot below for the References tab of this collection)
![image](https://user-images.githubusercontent.com/55999682/201353856-3fde919e-4a79-405e-8fd9-5adc923475fa.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Added both:
- OpenMRS cascade will transform the reference into multiple static references (latest versions of concept/mapping) and the response will reflect that in the Reference Result dialog.
- Exclude Reference will only exclude the resource

**Comment by jamlung-ri** [comment]
Both of these are working as expected! I think this is ready for deployment.

**Comment by jamlung-ri** [comment]
@snyaggarwal We're good to move forward with this. 

The OpenMRS call showed us that this new cascade option works but there will be exceptions that people will want to make in the future. We should consider these as part of the "Add to Collection" workflow where you can preview results, edit the references, etc.

**Comment by paynejd** [comment]
@snyaggarwal Final changes for the new cascade option -- these are minor text updates, so no need for review before deploying:
* Please rename the option to: "OpenMRS-compatible Cascade"
* Please update the tooltip with this text:

> A specialized cascade option that adds a concept and all of its mappings, and then recursively adds any of its associated answer or set member concepts (i.e. concepts that are associated by a "Q-AND-A" or "CONCEPT-SET" map type) with all of their mappings, and so on. Resources are only added if they are defined in the same source as the selected concept(s).

**Comment by snyaggarwal** [comment]
Deployed everywhere. Closing this.
