### ISSUE TITLE
Hide Re-Compute Summary button

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1428]
I was looking at [CIEL's versions tab](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/versions) while anonymous in OCL, and the Re-Compute Summary button appears, even though I do not have permissions to perform the action. When I click the button, I am told that I do not have permissions. Should we instead grey out or remove the icon unless you have the appropriate access to edit CIEL? This should apply to all content, of course, not just CIEL.

Screenshot: 
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/d8738381-f763-4157-b4a8-c48db9e0b18e)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed on QA

**Comment by jamlung-ri** [comment]
Looks good. This should be good for deployment then.

**Comment by snyaggarwal** [comment]
Deployed everywhere. Closing this.
