### ISSUE TITLE
Cascade Documentation, round 2

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1429]
We have lots of materials from some of our major new features in 2022 that need to move into OCL Docs or inform planning for what's next.

**Topics:**
* $cascade
* $resolveReference
* Canonical URLs
* $expand operations
* FHIR $expand end points
* References (e.g. static/dynamic)

**Steps**

- [x] Compile what we have (in this ticket)
- [ ] Develop documentation plan/outline -- how are we moving everything that we have into OCL Docs? Are there gaps? Who's going to do what? etc.
- [ ] Compile "What's next?" -- materials mention a lot features/requirements/gaps that we have not yet addressed; let's make sure these move into a place where we don't lose them

**Documentation Structure**
- TB
- OCL-API
- OCL-FHIR

**Materials**
* Relevant Github issues:
  * @snyaggarwal Please add...
* Existing pages on docs.openconceptlab.org:
  * https://docs.openconceptlab.org/en/latest/oclapi/apireference/cascade.html
  * https://docs.openconceptlab.org/en/latest/oclapi/apireference/resolveReference.html 
  * https://docs.openconceptlab.org/en/latest/oclapi/apireference/expansions.html 
* From `Documentation 2022` folder:
  * [Operation: $cascade Documentation Feb-2022](https://docs.google.com/document/d/1oFlY_wyDarpPdHhfrQM7vbvkDs51hV9qQrMusBQst5A/edit#heading=h.ul4xd3yv4jtk) 
  * [Cascade Visual 2022-10-18](https://docs.google.com/spreadsheets/d/1hxRMKVcgrg9LVjzSLbd_rM9R3xN6rtAflvbymXgQzKw/edit?usp=share_link) 
  * [Expansions Documentation Mar-2022](https://docs.google.com/document/d/1z2h65pP934PyQg3_QSVp0pfHQaffwfTlkTDBXSIk5DI/edit#heading=h.b0oixqfm4khu)
  * [OCL Canonical URLs Documentation Feb-2022](https://docs.google.com/document/d/1zrQOQBC868uRdrZA-mhzvNzsepVYFhHrMDuJU7mKRjY/edit?usp=share_link) - also includes a lot of $resolveReference docs

**Comment by paynejd** [comment]
@snyaggarwal Please add links to relevant github tickets into this ticket

**Comment by snyaggarwal** [comment]
Some of the documentations in comments and descriptions, below are the links:
Cascade in nested(hierarchy) response view - https://github.com/OpenConceptLab/ocl_issues/issues/1168#issue-1086432425
hierarchy - https://github.com/OpenConceptLab/ocl_issues/issues/1122#issue-1058698167
visualisation - https://github.com/OpenConceptLab/ocl_issues/issues/1122#issuecomment-984659752
visualisation - terminal node - https://github.com/OpenConceptLab/ocl_issues/issues/1198#issuecomment-1028620771
OpenMRS Cascade - https://github.com/OpenConceptLab/ocl_issues/issues/1131
Reverse cascade - https://github.com/OpenConceptLab/ocl_issues/issues/1183#issuecomment-1008740466
$resolveReference - https://github.com/OpenConceptLab/ocl_issues/issues/1221
More on $resolveReference - https://github.com/OpenConceptLab/ocl_issues/issues/1221#issuecomment-1066404279
Reference expressions types - https://github.com/OpenConceptLab/ocl_issues/issues/1275#issuecomment-1119237917
TB expanded reference structure - https://github.com/OpenConceptLab/ocl_issues/issues/1289

**Comment by paynejd** [comment]
First round of updates to the cascade docs completed as part of #1456 -- second round will be completed as part of this ticket. Updates to include:
* Add new cloning parameters -- `omitIfExistsIn` and `equivalencyMapType` (#1451)
* Add details about how $cascade operates within a source vs. collection
* Add version changes from #1452
* Add a narrative/visual walk-thru similar to the examples here: https://docs.google.com/document/d/1oFlY_wyDarpPdHhfrQM7vbvkDs51hV9qQrMusBQst5A/edit#heading=h.ul4xd3yv4jtk
* Add links to examples that can actually be executed in the operations panel

**Comment by paynejd** [comment]
See updated $cascade docs here: https://docs.openconceptlab.org/en/latest/oclapi/apireference/cascade.html

cc @snyaggarwal
