### ISSUE TITLE
Support DB migrations in background

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#1430]
#1399 needs to do a long running DB migration in background while keeping the system running, which we currently don't support. 

We need to adjust the startup.sh script to be able to pass the "--skip-db-migration" argument. If the argument is not present we should run migrations as part of the startup. If the argument is present we need to fail the startup, if any migrations are not applied.

In addition to that we need a separate script to run db migrations e.g. "migrate-db.sh". It will be run as part of the API deployment pipeline and only once it completes successfully we will start deploying the updated api service.

**Comment by snyaggarwal** [comment]
This is done, further work on this will be in separate tickets. Closing this.
