### ISSUE TITLE
Add API preview to "Add References to Collection" panel

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1436]
Until we have a full-blown preview feature, we'd like to provide the option for a user to see the full API request that will be submitted when they click the "Add" button in the "Add References to Collection" panel. Full details are in this slide and a screenshot is below:
https://docs.google.com/presentation/d/1VV6lOQgAGpF2VlXw3P9emmIx5P_IEkji0P6PbFdhnl4/edit#slide=id.p

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/0b9b4657-915e-4f17-b387-05547a000a0e)

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA

**Comment by paynejd** [comment]
Slight change to the tooltip tooltip for the OpenMRS-compatible cascade:
> Includes associated Mappings and target Concepts from the same source, and recursively adds any of their associated answer and set member concepts and mappings (e.g. Q-AND-A and CONCEPT-SET mappings)

**Comment by snyaggarwal** [comment]
@paynejd  Closing this as this is deployed everywhere. Please raise specific tickets for bug/feedbacks on this.
