### ISSUE TITLE
OpenMRS Cascade bug encountered on Demo

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1437]
I was doing a demonstration on the Demo environment and the OpenMRS Cascade option seemed to be failing. It only adds a single reference even though there are two CONCEPT-SET mappings to [this concept](https://app.demo.openconceptlab.org/#/users/jamlung/sources/Versioned_Content/concepts/8/). The concepts I made have a few versions for that concept, so maybe it has something to do with that?

Video of this bug: https://iu.mediaspace.kaltura.com/media/t/1_2prqioy5/120124211 (Start at 15:40)

Details from my browser: 
`PUT https://api.demo.openconceptlab.org/users/jamlung/collections/Static_collection/references/?cascade={"method":"sourcetoconcepts","cascade_levels":"*","map_types":"Q-AND-A,CONCEPT-SET","return_map_types":"*"}&transformReferences=resourceVersions`

Request:
`{"data":{"expressions":["/users/jamlung/sources/Versioned_Content/concepts/8/"]},"cascade":{"method":"sourcetoconcepts","cascade_levels":"*","map_types":"Q-AND-A,CONCEPT-SET","return_map_types":"*"}}`

Response:
`[{"added":true,"expression":"/users/jamlung/sources/Versioned_Content/concepts/8/110620/","message":"The concept 8 is successfully added to collection Static_collection"}]`

**Comment by snyaggarwal** [comment]
@jamlung-ri This was a miss on the repo version resolution for cascade parameters in references. It was resolving to the latest released in section and while in cascade to HEAD. Fixed this, should be available soon.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed now. Please verify and close.

**Comment by jamlung-ri** [comment]
Fixed! Thanks!
