### ISSUE TITLE
Quick-Remove Mapping (in sources only)

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1439]
In addition to being able to quickly adding a mapping to a concept via the Associations section, a user also should be able to quickly "remove" a mapping (i.e. retire it) from the action menu in the Associations section. 

This should leverage the look and feel from [this Zeplin design](https://zpl.io/noAy8zx). We will only implement this in sources for now but will want to carry it over to collections later. This option should only appear if the user has the proper permissions, of course.

[Screenshot of the action menu I am referencing](https://user-images.githubusercontent.com/55999682/206534499-63a9d660-5a90-44d5-a96b-45ac06697047.png)

(Hopefully this isn't a duplicate ticket - I couldn't find an existing one with Zenhub being down)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done.

**Comment by jamlung-ri** [comment]
This is working well in QA! One note that I was able to remove the mapping, regardless of its direction (i.e. if the concept I am looking at is either the "to" or "from" side of the mapping). I think we're good to deploy to Production.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere, can this be closed?
