### ISSUE TITLE
Implement ability to fetch all collections/ sources owned by a user's orgs

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#144]
Hey guys,
Does this sound like something that would be feasible to implement? And if so, what might the endpoint look like? I've found that this would be important in reducing the number of API calls we have to make to display collections to a user.

**Comment by paynejd** [comment]
@Karuhanga Can you describe why this feature would be useful?

We modeled our API off of the GitHub API, and the GitHub API forces that you access the API either as an anonymous user or from a single user's permissions. In GitHub, orgs are just another type of user, which means that you would not be able to query a list of all the repositories in the orgs that a user has access to. You would need to get the user's repos, or the repos from one org at a time. Putting this restriction in place seems like it simplifies the API architecture, because you only ever consider one user+org permissions at a time.

That said, there could be good reason to implement this. I would think we use the same user endpoints for sources/collections and add an optional request URL parameter that broadens the scope of the repositories retrieved -- e.g. something like this:
```
GET /users/[:user]/sources/?includeOrganizationSources=true
GET /users/[:user]/collections/?includeOrganizationCollections=true
```

**Comment by Karuhanga** [comment]
> That said, there could be good reason to implement this. I would think we use the same user endpoints for sources/collections and add an optional request URL parameter that broadens the scope of the repositories retrieved -- e.g. something like this:
> 
> ```
> GET /users/[:user]/sources/?includeOrganizationSources=true
> GET /users/[:user]/collections/?includeOrganizationCollections=true
> ```

Exactly what I had in mind.

The current behavior is definitely sane and easy to reason about, architecture wise.
The use case for this particular endpoint is in the OCL Client, users don't really care who owns the organization at the time they are managing it. Having a single endpoint retrieving these makes pagination and search much easier.

Without this, we have to resort to an API call per org a user is a part of and handle search and pagination for each of these separately, which is not very intuitive to the user, or have them navigate to the org first.

**Comment by paynejd** [comment]
Thanks for documenting this here Lincoln! I think makes good sense to get
this on the roadmap.

**Comment by Karuhanga** [comment]
Unfortunately, I seem to have encountered some technical limitations with some of the dependencies we are using. In particular this one(https://github.com/django-nonrel/mongodb-engine/issues/140).

A sensible compromise in this case i think will be introducing new endpoints;
- `GET /orgs/sources/`
- `GET /orgs/collections/`

which would at least help reduce the number of API calls from _number of orgs_ to _one_.

**Comment by paynejd** [comment]
@karuhanga To fetch all sources and collections that a user can access, I
would suggest using the existing `/users/:user/` endpoint and adding a
`scope` url parameter where "owner" is the default, or it can be set to
"edit" or "view" to include all sources that a user has edit access to or
all sources that a user can view. I don't love the name `scope` for the URL
parameter, so please let me know if you have other ideas.
For example:
```
# This gets sources owned by the user
/users/johndoe/sources/

# This would get the list of sources that the user can access, including
sources that the user owns
/users/johndoe/sources/?scope=[owner|edit|view]

# Scope
```

**Comment by Karuhanga** [comment]
@paynejd very good design suggestion.
The problem I am encountering here is when I try more complicated queries(especially involving nested ORs) with the orm one of the dependencies crashes.

Doing these with Haystack seems to fail silently which is what prompted this change(https://github.com/OpenConceptLab/oclapi/commit/48eb8669c94736a5bb27d2b87f8d61fe3b73d4db).

Thus my attempt to keep fetching the differently owned resources separately in order to keep the query simple.

**Comment by paynejd** [comment]
@karuhanga - can you make sure that this new functionality is added to the docs? Also just checking, do we have tests for the new functionality?

**Comment by Karuhanga** [comment]
> @Karuhanga - can you make sure that this new functionality is added to the docs? Also just checking, do we have tests for the new functionality?

Yes, the PR included tests for the functionality. I have documented it as well.
