### ISSUE TITLE
Minor Changes to Quick-Add Mappings

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1440]
Hey @snyaggarwal, here are some changes for Quick-Add mappings feature that we hope should not take much time:

- [x]  Text change: "Remove mapping" should be "Retire mapping" in the action menu of the Associations section.
- [x] In the event that a mapping is retired but is appearing in the Associations section, there should be an "Unretire mapping" option. This will be needed if a user accidentally retires the wrong mapping or something like that.
- [x] For inverse mappings, the "Add new [map-type] mapping" option should also show the "-1" e.g. "Add new CONCEPT-SET -1 mapping" (See circled area in screenshot below)

![image](https://user-images.githubusercontent.com/55999682/206729966-a87f5f9b-43b9-4008-b684-91235e9331b6.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done and deployed

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere, can this be closed?
