### ISSUE TITLE
Action Menu name change: "Download" -> "Download Metadata"

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1441]
To make it a little more clear to the user that you are not actually exporting a source/collection, let's change the name of this option from "Download" to "Download Metadata". This should be done in all sources and collections.

![image](https://user-images.githubusercontent.com/55999682/207104658-65294f01-5e9b-44e3-9055-2b3d64775b4a.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
This is working well and can be deployed more broadly.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere.
