### ISSUE TITLE
Error 403: Cannot view a user's Public collection

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1443]
Scenario: I need to view a public collection created by user ruhanga, because one of these collections has become essential in the OpenMRS RefApp, and I want a non-json way to review the content. Ideally I want to move or copy his collection into an OpenMRS-owned public collection. 
 
Steps: 
1. Search for user ruhanga
2. See that hovering over "Public Collections" icon shows "2 public collections"
3. Try clicking on that or on his username in the search results
4. See "403: You do not have permission to perform this action."

Gif: 
https://drive.google.com/file/d/1rK9XQYcuU7oo47QkF6r4_RRm-AW-Js9i/view?usp=drivesdk

**Comment by snyaggarwal** [comment]
Linked to https://github.com/OpenConceptLab/ocl_issues/issues/1135

**Comment by snyaggarwal** [comment]
@gracepotma This is a known issue #1135. I have fixed this and will be available on QA (in few minutes).
It might take a couple of days to reach all the other environments, meanwhile, you can search for public sources/collections and click the results and that should take you to the public source/collection for other users.

**Comment by jamlung-ri** [comment]
@gracepotma Here's an image example of what Sunny described above. Searching "ruhanga" in the topmost search bar will show you public sources and collections from that user. Hopefully this can be a good workaround until the changes are deployed to all environments.

![image](https://user-images.githubusercontent.com/55999682/207327655-b4047eb6-f4d1-4d4c-bebd-ab4542388834.png)

**Comment by snyaggarwal** [comment]
@gracepotma This is now deployed everywhere.

**Comment by gracepotma** [comment]
That was so fast! Thank you so much OCL team. This immediately unblocks us 💪 
Always appreciate how fast you folks respond to my issues <3 Thank you!
