### ISSUE TITLE
Trigger google analytics events for key TermBrowser actions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1445]
Right now, we only track TermBrowser page loads in google analytics.

We want to track:
* Viewing resource details
* Creations
* Updates

**Comment by snyaggarwal** [comment]
- Added Page Views on every route change
- Added events on create/update of all
- Added events on retired/reactivated on concepts/mappings
- Added events for quick mapping

**Comment by snyaggarwal** [comment]
This is deployed everywhere
