### ISSUE TITLE
[TB] System Admin to be able to safely hard delete a user

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1448]

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA

**Comment by paynejd** [comment]
Works great! Only thing: I deleted the user "paynetest" on QA, and after it
deleted it reloaded the same page and gave a 404:
https://app.qa.openconceptlab.org/#/users/paynetest/

Should we redirect it back to global search?

**Comment by snyaggarwal** [comment]
Yep, I think better to redirect back to users listing in global search.

**Comment by snyaggarwal** [comment]
@paynejd Deployed on QA

**Comment by snyaggarwal** [comment]
Deployed.
