### ISSUE TITLE
Implement ability to cascade concepts when adding references to a collection

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#145]
We can already cascade mappings(using `cascadeMappings`) when adding a concept reference to a collection. Would it be possible to implement something similar for concepts, allowing us to cascade them based on the mappings?

That is, if I add a concept reference with `cascadeMappings=true&cascadeConcepts=true`, we would add the concept, its mappings and their `to_concept`s, potentially recursively until an `n`(possibly specified by user) number of levels to avoid possible recursion.

**Comment by paynejd** [comment]
This work is now captured in #190. Adding a note of the additional option of "recursion" there, and closing this as a duplicate.
