### ISSUE TITLE
Implement $cascade omitIfExistsIn & equivalencyMapType parameters

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1451]
Add logic required for cloning to the $cascade operation:
* Implement optional `omitIfExistsIn` and `equivalencyMapType` parameters
  * `omitsIfExistsIn` must resolve to a specific source version (latest if not provided; HEAD is okay if explicit)
  * `equivalencyMapType` - default="SAME-AS", but user can set another value

**Comment by snyaggarwal** [comment]
@paynejd Couple of questions for `omitIfExistsIn`:
- Is $cascade going to just omit the result or should it not cascade the subtree of the result that needs to be omitted? (assuming it's the former)
- What about the unexpanded collection version, should we try to omit concepts/mappings from the list of references by resolving the references first? Right now I have only considered collection versions with default expansion, otherwise, it will be a slow process to cascade, please advise.

**Comment by snyaggarwal** [comment]
Also, @paynejd is there some documentation on `equivalencyMapType` behaviors?

**Comment by snyaggarwal** [comment]
> @paynejd Couple of questions for `omitIfExistsIn`:
> 
> * Is $cascade going to just omit the result or should it not cascade the subtree of the result that needs to be omitted? (assuming it's the former)
> * What about the unexpanded collection version, should we try to omit concepts/mappings from the list of references by resolving the references first? Right now I have only considered collection versions with default expansion, otherwise, it will be a slow process to cascade, please advise.

@paynejd I think we will have to omit the subTree from `$cascade` rather than just the resources.
To explain this, assume the following:
1. `concept1` _--CONCEPT-SET1--_ `concept2` _--CONCEPT-SET2--_ `concept3`
2. `concept2` exists in `/orgs/myOrg/collections/MyCollection/v1/`
3. GET `/concept1/$cascade/?omitIfExistsIn=/orgs/myOrg/collections/MyCollection/v1/` (flat response) will return:
`concept1, CONCEPT-SET1, CONCEPT-SET2, concept3`
4. GET `/concept1/$cascade/?view=hiearchy&omitIfExistsIn=/orgs/myOrg/collections/MyCollection/v1/` (hierarchical response) will return:
`concept1 --> CONCEPT-SET1`
Because `CONCEPT-SET2` and `concept3` were supposed to be nested under `concept2`, it dint know where to place them.

Please advise, if I am understanding this correctly.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri `omitIfExistsIn` is deployed on QA for $cascade API and operation in operation panel.

**Comment by snyaggarwal** [comment]
@jamlung-ri Yep its very hard to understand it like this. May be lets discuss this in today's dev call.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA. I checked the counts of results in your above calls and they are different. Please do let me know if its working as expected.

**Comment by jamlung-ri** [comment]
Great! I was able to complete all three of those tests above. The equivalencyMapType parameter worked when trying to omit a concept that is mapped SAME-AS a CIEL concept. Example: [Original Cascade link](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=%2Fusers%2Focladmin%2Fsources%2Fasdff%2F&equivalencyMapType=&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off) vs. [Cascade with SAME-AS omitted](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=%2Fusers%2Focladmin%2Fsources%2Fasdff%2F&equivalencyMapType=SAME-AS&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off). I also tested comma-separated equivalencyMapType parameters, and I was able to omit CIEL concepts when expected. Example: [Original Cascade link](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=%2Fusers%2Focladmin%2Fsources%2Fasdff%2F&equivalencyMapType=&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off) vs. [Cascade where IS-A and WAS-A are omitted](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=%2Fusers%2Focladmin%2Fsources%2Fasdff%2F&equivalencyMapType=WAS-A,IS-A&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off). This also worked in a collection ([original](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=&equivalencyMapType=&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off) vs. [omitted](https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/161499/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=flat&omitIfExistsIn=%2Fusers%2Focladmin%2Fcollections%2Fomittest3%2F&equivalencyMapType=IS-A,WAS-A&q=direct+coomb&isTable=true&isList=false&page=1&exactMatch=off))!

One note: It appears that equivalencyMapType does not default to using "SAME-AS" when left blank. This means that test #3 above worked, but the omitIfExistsIn parameter needed to specify "SAME-AS". I think this behavior is the right one, but when we implement the Clone operation in OCL, we should make sure that is specifies the equivalencyMapType parameter.

**Comment by jamlung-ri** [comment]
@paynejd Is there any other testing that you can think of to be done here? I'm finding really great success with both of these parameters. May be worth noting that I think some good testing will also happen once we start using these parameters as part of the Clone operation.

**Comment by paynejd** [comment]
Added `omitIfExistsIn` and `equivalencyMapType` to the docs here: https://github.com/OpenConceptLab/ocl-docs/blob/main/docs/source/oclapi/apireference/cascade.md

**Comment by paynejd** [comment]
From my perspective, this is ready for deployment. We'll do final testing once we have some good UI components to work with this in the TermBrowser

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on production.
