### ISSUE TITLE
Implement clone operation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1453]
Once we're happy with the new cascade behavior, then implement a $clone operation, that can accept multiple inputs, eg. references or possibly the results of another operation (e.g. $cascade).
* $clone can result in the creation of concept versions and mapping versions only, and they can be mixed in a single request (as in the results of a cascade operation)

**Comment by snyaggarwal** [comment]
https://docs.google.com/document/d/1w90baJjfdxyYZf-yJozGgzVL2RajYKIkQrmMkHIlFRU/edit#

**Comment by jamlung-ri** [comment]
Copying the comment from #1465: https://github.com/OpenConceptLab/ocl_issues/issues/1465#issuecomment-1428595855

The $clone operation should not allow the user to clone a concept into the same source as the original concept.
