### ISSUE TITLE
Support direct links to Operations Panel with parameter values in the URL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1457]
We want to be able to link users directly to an operation in the Operations panel, with all values passed as part of the URL. Here's the use case:

Cascade is tricky. In our documentation, we want to provide example cascade requests with links to the request embedded in the documentation. The link should open up the TermBrowser directly to the Operations panel with fields preset.

Note that this has to support all cascade input parameters (see #1454)

**Comment by jamlung-ri** [comment]
@snyaggarwal If possible, here's a ticket to try to fit into this Sprint.

**Comment by snyaggarwal** [comment]
this is deployed on QA (except omitIfExistsIn)

**Comment by jamlung-ri** [comment]
@snyaggarwal Can you give a screenshot or something to show where this was implemented in QA? I am not seeing the TermBrowser URL be updated after using the $cascade operation in the Operations panel, and I'm not seeing any sort of Link button in the Operations panel itself.

**Comment by snyaggarwal** [comment]
The way to use this (for now) is if you have the $cascade URL for API for example -- `https://api.qa.openconceptlab.org/users/ocladmin/sources/CascadeTest/concepts/AA/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=hierarchy`

you need to just change two things to make it TB specific URL:
https://**app**.qa.openconceptlab.org/**#**/users/ocladmin/sources/CascadeTest/concepts/AA/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=hierarchy

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on production. Closing this.
