### ISSUE TITLE
Sort Weight in Associations section in TermBrowser

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1458]
Now that #1446 is nearly complete, we need a way for users to sort a concept's mappings in the Associations section of the TermBrowser. See image below for example - for any given map type, we should be able to sort the concepts e.g. sort the Q-AND-A mappings to be in reverse order (i.e. 7 -> 2 -> 1 instead of 1 -> 2 -> 7)

![image](https://user-images.githubusercontent.com/55999682/209215113-8c6a7711-7251-4108-bd48-cc63ff0903c9.png)

Note that this will be working with the sort_weight attribute for mappings, which is left null until the user applies a number to it. Meaning, if concepts 1 and 2 are given a sort weight, then concept 7 maybe should also be given a sort weight? We discussed a bit in [this ticket](https://github.com/OpenConceptLab/ocl_issues/issues/1369#issuecomment-1353062396), and OpenMRS doesn't seem to care if no sort order is applied.

Ideas/Requirements:
* Sorting is applied only within a particular map type, so the user probably only needs to be sorting within a single map type at one time. Meaning, if I start sorting Q-AND-A mappings, I will focus on those and not on SAME-AS mappings.
* Ideally, a user is quick-adding mappings following Paul's designs i.e. with "Add mapping above/below". This is an easy way to silently apply a sort weight. 
    * However, there will be cases where someone creates a mapping outside of the Quick Add feature, so we should ensure that we have a way for users to sort mappings that were created using another method e.g. API.
* Unknown: Is there any use case to "unsort" mappings that have a sort order applied to them? None that I know of.

Hopefully we can crank this one out quickly after we get back from the holidays.

**Comment by jamlung-ri** [comment]
More specific requirements (in addition to those listed above):

* Sorting in the Associations section happens solely within a single map type. For example, you can only sort within Q-AND-A mappings, and there can be no mixing with SAME-AS mappings.
    * Our UI behavior should include some visual cues to make this clear to the user.

* If sort weight is applied to one mapping in Associations section, it should get applied to all of them.
* It should be clear to a user whether or not there is a sort order present for this map type in the Associations section. Meaning, it should be easy to distinguish whether there is a user-specified sort order as opposed to OCL's default sort order.
* If one mapping is missing a sort weight, but the others within that map_type have a sort weight, then there should be a visual indicator to show that one or more sort weights are missing.
* It is unclear if we should be able to "unsort" i.e. purge all sort orders within a map type. If this is something that can be easily built in, then let's do that, but if there's no clear place for it, then let's leave it out for now.

**Comment by jamlung-ri** [comment]
@paulsonder With these requirements above, we should be ready to design this UI behavior. Let me know of any questions that come up, and we can address them.

**Comment by paulsonder** [comment]
@snyaggarwal Please find UI for the Sort mappings feature here: https://zpl.io/xmgvNlR

@jamlung-ri Could you confirm the copy required in the 'save bar' component please?

**Comment by jamlung-ri** [comment]
> @jamlung-ri Could you confirm the copy required in the 'save bar' component please?

@paulsonder Sorry, I'm not following. Did someone ask for there to be a Copy button in the Save bar, or something like that? Maybe there a link that you can specifically point me to?

**Comment by jamlung-ri** [comment]
Summary of changes from today's [OCL Dev call](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.1uyfwjz45trh): 

- [ ] Disable sorting of inverse mappings
- [ ] Sorting should only happen when dragging the Sort icon (6 dots) rather than dragging the whole row
- [ ] Enable Sticky bar for “# changes made…”
- [ ] For Associations sections with multiple map types, the map type being dragged should be highlighted (and other map types lowlighted) when dragging to make it visually clear that you can’t put the mapping in another map type’s section. Should also change the cursor type to indicate that a mapping cannot be dropped outside of its section. “it shows a ‘stop’ icon next to the grabber cursor” ([link](https://www.w3schools.com/cssref/playit.php?filename=playcss_cursor&preval=no-drop))

Other notes:
* TBD - Need a way to indicate that the list is partially sorted. Might visually distinguish the unsorted mappings, or perhaps show one icon next to the “Sorted” icon to indicate that there are unsorted mappings?
* Default sort order for Associations section in TermBrowser: 
    1. Map type, grouped
            * Self-mapping
            * Direct mapping, alphabetical
            * Inverse mapping, alphabetical
    1. Sort weight (starts with numeric values, ends with all null values)
    1. Target source
    1. Target code

**Comment by snyaggarwal** [comment]
@jamlung-ri All the feedbacks are deployed on QA

**Comment by jamlung-ri** [comment]
It's working great! All of the feedback mentioned above seems to be working well. 

One question for @paynejd - when applying a sort weight to one mapping, shouldn't ALL the mappings of that map type be given a sort weight? Currently, it seems like we're only applying a sort weight to the mappings that were directly moved around. I thought that was the intended approach, but I just want to check before having Sunny make that change. 

The thing I don't like about this approach is that it could be confusing for the user. If they switch the position of only two mappings, but OCL applies changes to the rest of the mappings in the list, the user might not understand why so many mappings are being updated.

Showing a visual example - I moved "Hours" and "Minutes" around, but the other mappings e.g. "Seconds" or "Weeks" currently do not get a sort weight applied to them. So the whole map type group won't have sort weights. The only two sorted mappings will be "Hours" and "Minutes".
![image](https://user-images.githubusercontent.com/55999682/220928888-a125ba3d-3c7f-4dd3-aa75-79770265ea60.png)
