### ISSUE TITLE
Add Visualize option in Operations panel, plus enhance visualization panel with new filters

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1459]
Now that `OmitIfExistsIn` and `EquivalencyMapTypes` parameters are working, let's make sure those two parameters are in the Visualize window. Then, let's put the Visualize button in the Operations Panel so that we can better visualize the $cascade operation we're performing.

Also I can suggest a new icon for Visualize

**Comment by jamlung-ri** [comment]
For icons, I would suggest AccountTree, but we're already using that for hierarchy e.g. on the [ICD-10] page (https://app.openconceptlab.org/#/orgs/WHO/sources/ICD-10-WHO/)
![image](https://user-images.githubusercontent.com/55999682/212334052-72e29458-6b36-4d64-b3f9-ef3ccddc6045.png)

If we need to find a separate icon, then the only Material icons that I might be okay with are AltRoute (if it could be rotated 90 degrees)
![image](https://user-images.githubusercontent.com/55999682/212334336-6ec54558-f48d-48a4-9547-9d691a5fea28.png)

or perhaps OpenInBrowser
![image](https://user-images.githubusercontent.com/55999682/212334699-8d75010c-8e64-451a-a3a6-1ac80e0dec98.png)

or perhaps QueryStats
![image](https://user-images.githubusercontent.com/55999682/212335078-5f48c4d6-a32b-43f0-99f6-582904f74372.png)

@snyaggarwal @paynejd @bmamlin Any thoughts on these? Do any seem like they capture the point of this Visualizer?
![image](https://user-images.githubusercontent.com/55999682/212335531-c94e831b-c91d-4982-8252-c8b155c7e21a.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
@snyaggarwal Some notes we took from today's Dev call:
* On the Operations panel, the Visualize icon only shows up when you select “Hierarchical Response”. 
    * Bug - If you Execute without Hierarchical Response selected, then enable Hierarchical Response, then you can still try to “visualize” but it fails, saying “No entries found“

Can we change the UI to fix these issues? I might suggest that the Visualize icon always shows in the Operations panel results, but it is greyed out unless the query response (below the Execute button) is of type "hierarchy". If not, then the icon should be greyed out with the following tooltip language: "Visualize - Only available when using the Hierarchical Response format"

Feel free to adjust the approach where it makes sense.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA

**Comment by jamlung-ri** [comment]
Looking good! I don't have any more feedback for now.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on production. Closing this.
