### ISSUE TITLE
Resizing fails in split view when operations panel is opened

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1460]
On the OCL Arch call today, we noticed that the resizing of the split view panel was breaking the screen when also using the Operations panel.

There will be a recording link for this, so let me know if that is needed, or refer to the recordings in the Arch call notes.

**Comment by snyaggarwal** [comment]
This is deployed on QA

**Comment by snyaggarwal** [comment]
This is deployed on QA

**Comment by jamlung-ri** [comment]
This seems to be working for me on QA!

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on production. Closing this.
