### ISSUE TITLE
Operations panel (at least $cascade) does not work when a concept is selected in global view – but it does work when selected within a source

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1461]
Operations panel (at least $cascade) does not work when a concept is selected in global view – but it does work when selected within a source.

This occurred on the OCL Arch call, in case a recording is needed.

This also appears to be the same issue noted in this comment: https://github.com/OpenConceptLab/ocl_issues/issues/1454#issuecomment-1376168950

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed on QA

**Comment by jamlung-ri** [comment]
Confirmed that this is working in QA! It should be ready to deploy, I think.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on production. Closing this.
