### ISSUE TITLE
Cloning in TermBrowser - Phase 1

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1465]
As described in our Cloning documentation, this ticket will involve implementing a Clone workflow in the TermBrowser, reusing components from the "Add to Collection" workflow in a simpler way.

This work will need to be followed up by a Phase 2 in the future, which will revamp and optimize this process to be more intuitive and useful for users.

**Comment by jamlung-ri** [comment]
Looking at "Add to Collection" components (with screenshots below) that may need major changes:

* "Add to Collection" button will be reused as a "Clone" button. 
![image](https://user-images.githubusercontent.com/55999682/213463703-c7339195-8f6c-423b-b61f-ff962686a8ea.png)

* "Select Collection" list will be reused as a "Select Source" list. This will designate the destination for all the cloned concepts.
![image](https://user-images.githubusercontent.com/55999682/213463906-c37d3f22-5c85-43e0-b621-ef59c61dd827.png)

* "Add References to Collection" dialogue box will be reused as "Clone Concept to Source". This will show the owner and source name that will receive the cloned concepts. This is also where the user will select among several Cascade presets. It will ask the user "Would you like to also clone associated Concepts and Mappings?"
     * Options 1-3: Same options as "Add to Collection", but should replace the word "include" with "clone".
     * Option 4 - "Smart Clone": The only option that leverages `OmitIfExistsIn` to the destination source, with "SAME-AS" as the `EquivalencyMapType`
          * Joe to write new tooltip language for this. Might also want to clarify that duplicate clones may result with Options 1-3
     * Note: API details should still be shown in this box, allowing the user to see the parameters that 
     * (Out of scope) In addition to providing the cascade options, users can separately elect to "skip duplicates" when cloning concepts
     * (Out of scope) Advanced Cloning - enables a user to manually set their own parameters for the cascade
![image](https://user-images.githubusercontent.com/55999682/213464072-a7e2efcf-4237-4207-b9cb-cfc8fe214815.png)

* Results box will now have three sections to display: # of concepts created, # of mappings created, and # of skipped concepts. 
    * I am envisioning this like a [collapsible table](https://mui.com/material-ui/react-table/#collapsible-table), with a collapsed section for each, which the user can expand to see exactly which concepts/mappings were created and which were skipped due to having a concept with a "SAME-AS" mapping in the source already.
![image](https://user-images.githubusercontent.com/55999682/213469332-e93fa5d2-6352-4d96-b09a-c8697bcefe8c.png)

**Comment by jamlung-ri** [comment]
@snyaggarwal Not sure if you have started development on this, but I [mocked up an idea ](https://www.loom.com/share/9df7d739971a4b058dc7566d558ff258)for how this could flow. This is available for feedback in the OCL-core Slack channel. I will update once we feel that the concept is solid.

**Comment by jamlung-ri** [comment]
Feedback from today's OCL Dev call or from Slack:

- [ ] Add “beta” flag/icon to the title of the window
- [ ] Change the default MapTypes to Q-AND-A and CONCEPT-SET
- [ ] “Visualize” button should always respond to the Advanced Settings parameters.
     - [ ] Might want to improve visualization in the case that there are no entries? Maybe just show the single concept.
- [ ] Do we need to preview the results? The API Details is pretty scant.
    - [ ] When success occurs, a new Visualize option should be available that will show the newly cloned concept in your destination source.
        - [ ] New visualization can highlight what was newly created vs. what was skipped
    - [ ] Remove the Results list that shows individual concepts and their concept/mapping counts
- [ ] New approach:
        1. Return the operations to be applied, which can be previewed by the user
        2. Run the operations
        * This would allow you to see the actual changes before applying them
- [ ] Add a toggle row to show the individual results (which should be responsive to any changes in Advanced Settings)
- [ ] Change description at top of window to “This operation will clone the selected concept(s), plus any answers or set members recursively following specified mappings. This will skip any concepts already (SAME-AS) in the destination.”
- [ ] Add a brief warning at the top of advanced options when expanded like: “Caution: changing these settings could yield an incomplete clone (e.g., missing answers or set members).”
- [ ] Make the destination source bold in the pop up, since accidentally cloning into the wrong source could create misery. For example: “2 selected Concept(s) will be cloned into: ocladmin/expanded-reference-testing”

**Comment by jamlung-ri** [comment]
@snyaggarwal Collecting feedback here:

- [ ] Can the beta flag be added around here? 
![image](https://user-images.githubusercontent.com/55999682/216058302-83a9e229-4d5c-4908-b0e2-5d0106fa5021.png)

- [ ] The first time I clone any concept, I get a 500 error, and it appears that the $clone failed. I can try to $clone the same concept again, and it appears to have worked better, but I only see the concept and its SAME-AS mapping back to the original concept. None of the mappings made it over, however. See it happening on [this Loom](https://www.loom.com/share/893d8bb5e33b4f5e9bb8cf97d1f64c34).


One note about behavior - the $clone operation is copying the ID of the concept, rather than following any kind of ID auto-assign logic for the source being cloned into.

**Comment by snyaggarwal** [comment]
@jamlung-ri the 500 error was because the concept had mappings to target concepts that dont exists on OCL.
All of the above feedback is deployed on QA.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal, this is making good progress. The 500 error is not happening anymore, it seems. The basic clone behavior seems to be working well, but it still has some bugs when getting into the more complicated uses.

Here's what I am noticing in this round of testing:

1. The preview of the $clone results via the visualization seems to only be cascading from one of the cloned child concepts, not the original concept that I cloned.
2. The newly cloned concepts did respond to the auto-ID assignment for the concept ID field, but it did not respond to the External ID auto-assignment. Because my [source](https://api.qa.openconceptlab.org/users/ocladmin/sources/clonetest2/) has an external ID assignment (which should give it a UUID in the External ID field), my newly cloned concept should have had a UUID, but it instead kept the original CIEL concept's external ID.
3. I am noticing a particular cloned mapping (which was 2 levels into the cascade) is still pointing back to the original CIEL concept, rather than being cloned itself.

Both of these issues can be seen in this Loom: https://www.loom.com/share/74dea5083c5d4c36abd3c67efc87909d

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed all the above ones.

**Comment by jamlung-ri** [comment]
Great! This is working on my basic Coomb's test example. Worth noting that concept will fail to clone if there is a same-as concept already, even if that concept is retired. We will need to address that in the UI in the future. 

Also, if you clone a clone concept (i.e. a concept that was already cloned from an original concept), it isn't easy to determine which SAME-AS mapping goes back to the original concept and which SAME-AS mapping refers to the clone. This is something I expect we will tackle when we get to the concept modification workflow initiative.

With a really large (99+) convenience set from CIEL, it took about 30 seconds to clone all 24 concepts and ~180 mappings.

**Comment by jamlung-ri** [comment]
This is looking good! It was working properly on QA with some CIEL convenience sets. The preview was responsive to the Advanced parameters, and it was another good way to succinctly list out the individual concepts and mappings that will be getting cloned into your source.

Also, when I tried to reclone the same concepts, the Preview showed that no concepts would be added. In the future, we'll want to say why those concepts didn't make it into the source, but it's fine for now.

**Comment by jamlung-ri** [comment]
@snyaggarwal I found a bug today while pre-demo'ing $clone with Jon. [This concept](https://app.qa.openconceptlab.org/#/users/ocladmin/sources/clonetest4/concepts/15/), which was created via $clone, is not showing the source of its mapping in the Associations section. It's just showing the codes. Is the mapping not resolving correctly? See screenshot for example. 
![image](https://user-images.githubusercontent.com/55999682/217349517-e4914c3b-8f4c-48ed-ad4a-d54b0caca76d.png)

**Comment by paynejd** [comment]
Change title of "Clone (beta)" button to:

**Clone to Source<sup>beta</sup>**

**Comment by snyaggarwal** [comment]
> 

@jamlung-ri Fixed this

**Comment by jamlung-ri** [comment]
@snyaggarwal One bug (or rather, an unexpected behavior) that I noticed. If I try to clone a concept from one of my sources, I can clone it into that same source. That shouldn't be possible for a user - when cloning, the "origination source" and the "destination source" should be different.

We might need to address this in a couple of ways:
1. The $clone operation should not allow the origination and destination sources to match
2. When attempting to clone a concept in the TermBrowser (i.e. you have pressed the "Clone to Source" button), the list of sources that appears should omit the source from which the original concept lives in.

**Comment by jamlung-ri** [comment]
Another bug: When 0 concept or mappings were added (since they all had SAME-AS concepts in the same source), the Status column says Success with a 0. This should say something more accurate like "Failed", I'm thinking. @paynejd Feel free to change that message if you think something else would make more sense.

![image](https://user-images.githubusercontent.com/55999682/218563132-4fc6609a-774b-4d0c-b332-c7fa2ce3ddb0.png)

**Comment by jamlung-ri** [comment]
Some UI feedback from my conversation with Paul Adams today:

- [ ]  The Status column on the left is confusing. Instead, let's have two sections on the right side of the table - a Preview section and a Results section. Within each section, for each concept being cloned, there should be a Visualize icon and a List icon. In the Preview section, it shows the $cascade visual and the list of concepts/mappings to be created. In the Results section, it should also have the same two icons that show the $cascade operation from the newly cloned concept, plus the List of concepts/mappings created as part of the $clone operation. Would this work? Example image:
![image](https://user-images.githubusercontent.com/55999682/218566523-b87992dd-31d2-41d7-8687-b0b0455c797a.png)


- [ ] (Not sure how possible or quick this is) The Map Type fields in the Advanced Settings section could be smarter. Cascade Levels should be a dropdown with numbers like what the Cascade Visualizer uses. The MapTypes, ReturnMapTypes, and ExcludeMapTypes fields could be multi-select dropdowns that contain the mappings that are available for that concept. And the EquivalencyMapType could be populated with mappings that come from the source you are cloning into. Would this be something that could be done with minimal effort e.g. under 4 hours? If not, no problem.

**Comment by snyaggarwal** [comment]
> @snyaggarwal One bug (or rather, an unexpected behavior) that I noticed. If I try to clone a concept from one of my sources, I can clone it into that same source. That shouldn't be possible for a user - when cloning, the "origination source" and the "destination source" should be different.
> 
> We might need to address this in a couple of ways:
> 
> 1. The $clone operation should not allow the origination and destination sources to match
> 2. When attempting to clone a concept in the TermBrowser (i.e. you have pressed the "Clone to Source" button), the list of sources that appears should omit the source from which the original concept lives in.

@jamlung-ri I thought about it and left it to the user because of two reasons:
1. If the user is selecting the same source as clone to then nothing will be cloned.
2. Also, think about the scenario where multiple concepts are selected and one or few of them belong to clone to Source, the exclusion would be difficult in that case.
Lets discuss this in our dev call today.

**Comment by paynejd** [comment]
Change `X` in the "Preview" dialog to go back to the Cloning dialog rather than closing the entire thing out

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1189689/218758878-699d64f0-6893-4b4e-8a40-acf4769631fe.png">

**Comment by snyaggarwal** [comment]
> > @snyaggarwal One bug (or rather, an unexpected behavior) that I noticed. If I try to clone a concept from one of my sources, I can clone it into that same source. That shouldn't be possible for a user - when cloning, the "origination source" and the "destination source" should be different.
> > We might need to address this in a couple of ways:
> > 
> > 1. The $clone operation should not allow the origination and destination sources to match
> > 2. When attempting to clone a concept in the TermBrowser (i.e. you have pressed the "Clone to Source" button), the list of sources that appears should omit the source from which the original concept lives in.
> 
> @jamlung-ri I thought about it and left it to the user because of two reasons:
> 
> 1. If the user is selecting the same source as clone to then nothing will be cloned.
> 2. Also, think about the scenario where multiple concepts are selected and one or few of them belong to clone to Source, the exclusion would be difficult in that case.
>    Lets discuss this in our dev call today.

@jamlung-ri we discussed this in dev call today, and I have added an indicator next to each concept in case source and destination are same.

**Comment by jamlung-ri** [comment]
Summary of changes from today's [OCL Dev call](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.1uyfwjz45trh): 

- [ ] Visually group Advanced Settings fields as follows:
    -  Origination Source(s)
         - Cascade Levels
         - Map Types
         - Return Map Types
         - Exclude Map Types
    -  Destination Source
         - Equivalency Map Type

- [ ] Provide dropdown options for these fields (only run API query if field is clicked):
    -  Cascade Levels - Provide options 1-5 and “All (*)”
    -  Map Types, Exclude Map Types - All are populated from summary API of origination source
    -  Return Map Types - same as above, but also include “All (*)” as a default option
    -  Equivalency Map Type - Populated from map types of destination source (via Summary API), plus SAME-AS, and also allow free text to be inputted

- [ ] For the EquivalencyMapType parameter, SAME-AS should not get any special treatment. All inputs to this parameter will be available for finding equivalence, and the first parameter will be used as the map type between the original and cloned concepts.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
Looking great! A couple of small things:

- [ ] The `MapTypes` and `EquivalencyMapTypes` fields can have the "e.g. Q-AND-A,SAME-AS" text removed, now that there are already examples populated by default.

- [ ] I think the visual groupings could use need a small label above each column, one that says "Origination Source(s)" and one that says "Destination Source".

**Comment by snyaggarwal** [comment]
@jamlung-ri these are also deployed on QA

**Comment by paynejd** [comment]
This looks really good! Only thing that might be missing is tooltips,
though that doesn't need to hold up deployment. What if we create a new
ticket for tooltips and go ahead with moving this forward?

**Comment by jamlung-ri** [comment]
Great, @snyaggarwal this should be ready for deployment!
