### ISSUE TITLE
API ability to generate a summary of map sources for a repository

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1467]
* This should have a summary list of the unique from and to sources used in a repository version, with the option to view the full details when using `verbose=true`
* Also include the counts of mappings for each source grouped by: active/retired and map_type

cc @bmamlin

**Comment by bmamlin** [comment]
It would probably be helpful not only to have count of mappings, but also count of concepts amongst those mappings (e.g., are the 100 mappings to LOINC across 100 concepts or 10?)

We could use this information to generate a list of sources to include in exports (#1115).

Extra credit (aka scope creep): If it was feasible without a ton of additional work, it would be powerful if the summary could be run against any reference, so you could not only get a summary for a source, but also for a subset of the source (e.g., how many of my diagnoses are mapped to CIEL?)

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri This is deployed on QA

**Comment by paynejd** [comment]
cc @bmamlin

Here'a a link to test this:
https://app.qa.openconceptlab.org/#/orgs/CIEL/sources/CIEL/v2021-03-12/summary

<img width="974" alt="image" src="https://user-images.githubusercontent.com/1189689/217531565-22d4e344-4ac8-43ed-9862-8a53ef0d8315.png">

**Comment by paynejd** [comment]
@snyaggarwal If the "Summary" tab is selected, I'd like to be able to change to a different Repository Version and have it stay on the Summary tab

**Comment by paynejd** [comment]
Selected CIEL version `v2021-03-12`, but summary table below still lists `HEAD`. See screenshot...

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/1189689/217573413-21ce8d0e-6894-4bdb-8f62-c427de92078e.png">

**Comment by paynejd** [comment]
Request:
We want an individual row (just a map source, or the combo of a map source and map type) to be a clickable link that would take you directly to the mappings tab with filters already applied.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1189689/217574024-6d9f1187-3a65-40a6-a683-ea4d865d5430.png">

**Comment by paynejd** [comment]
Inclusion of Retired should be a toggle that is disabled by default -- so Overview just lists active concepts/mappings by default and there is no "retired" column in the table below by default. Only show these if someone has enabled the "Include retired" toggle

**Comment by paynejd** [comment]
Wish list: Ability to summarize any search/reference (not just a repo version) --- let's discuss this one separately, but it would be an awesome feature

**Comment by snyaggarwal** [comment]
> Selected CIEL version `v2021-03-12`, but summary table below still lists `HEAD`. See screenshot...
> 
> <img alt="image" width="1604" src="https://user-images.githubusercontent.com/1189689/217573413-21ce8d0e-6894-4bdb-8f62-c427de92078e.png">

HEAD is the version of SNOMED-CT, the mapped source and not the CIEL version you selected

**Comment by jamlung-ri** [comment]
One thing I noticed on QA was that one name type was split out into two numbers. I think it would be unclear to users what this means. Is there some reason that this number was broken out into two numbers? 

![image](https://user-images.githubusercontent.com/55999682/217827415-437a86db-af87-41f7-81ca-5dcea291683f.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri 
I think its empty (or None) nameType.
Can you tell me which Source is this?

**Comment by jamlung-ri** [comment]
That was CIEL on QA. https://app.qa.openconceptlab.org/#/orgs/CIEL/sources/CIEL/summary

**Comment by snyaggarwal** [comment]
@jamlung-ri Added None for it.

**Comment by jamlung-ri** [comment]
@paynejd I haven't followed this work super well, but is there anything needed before this can be deployed alongside cloning?

**Comment by paynejd** [comment]
Let's go ahead and deploy it with follow up tickets:
- add the new summary endpoints to OCL Docs
- create a new ticket for updating the UI/UX
- implement a summary tab for collections (but probably wait until after a round of UI/UX)
