### ISSUE TITLE
Counts of concepts incorrect

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1469]
The count of concepts for CIEL HEAD on Production on the [versions screen](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/versions) shows 53,842 concepts, which is incorrect. The correct number of unretired concepts is 53,850. Clicking on the incorrect number of concepts listed for HEAD takes you to the list of concepts, which paging reports (correctly) as 53,850. I've tried clicking the "Re-compute Summary" button a few times, but the summary of the versions page continues to show 53,482 concepts in HEAD.

**Comment by bmamlin** [comment]
After multiple (at least 3-4) attempts to update the summary for HEAD of CIEL on Production yesterday the concept count remained (incorrectly) at 53,482 on the Versions page. Today, I tried once more clicking the "Re-compute Summary" (∑) button and it worked this time! I'll leave this ticket open until @snyaggarwal has a chance to look at it to see if there's something to fix.

**Comment by snyaggarwal** [comment]
@bmamlin There was a bug in this which I fixed yesterday and thats why the count is correct now.
