### ISSUE TITLE
Users can view public collections that are marked private if the user query is specified

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#147]
Hey guys, I've been looking into adding this functionality(https://github.com/OpenConceptLab/ocl_issues/issues/144), but seemed as though there was some undocumented functionality similar to this, that is using the `user` query param.

However, I've noticed using this param allows users(authenticated or not) to access private collections. This does not seem right. For example;
https://api.qa.openconceptlab.org/collections/?q=Roya*&limit=10&page=1&verbose=true&user=admin
returns some private collections and
https://api.qa.openconceptlab.org/collections/?q=Roya*&limit=10&page=1&verbose=true does not(correct behavior).

Referencing https://github.com/OpenConceptLab/ocl_issues/issues/106 because it seems relevant here.

**Comment by Karuhanga** [comment]
Also, checking that no one depends on the behavior as it currently stands.

**Comment by paynejd** [comment]
FYI @rkorytkowski re: permissions
