### ISSUE TITLE
Draft $clone operation documentation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1472]
Use $cascade as a starting point: https://docs.openconceptlab.org/en/latest/oclapi/apireference/cascade.html

**Comment by jamlung-ri** [comment]
Documentation for this is being compiled here, at this time. https://docs.google.com/document/d/1w90baJjfdxyYZf-yJozGgzVL2RajYKIkQrmMkHIlFRU/edit#heading=h.2y3ejm485xdr

Once reviewed, it will be ready for transference to the OCL Docs site.

**Comment by paynejd** [comment]
While we know this documentation is going to continue to evolve, it's in a great place to move into OCL Docs and is more urgent since $clone behavior is now deployed into production.
