### ISSUE TITLE
Enable SSO in OCL Online staging environment

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1474]

**Comment by paynejd** [comment]
@snyaggarwal Let's wait until we hear from the OpenMRS community re: the Dictionary Manager -- that is the only potential blocker for this

**Comment by paynejd** [comment]
This is unblocked! Please move ahead enabling SSO on staging.

**Comment by snyaggarwal** [comment]
This is done. Closing this.
