### ISSUE TITLE
Update how OCL handles the option to view retired results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1476]
I searched for "Malaria" and clicked on the Organizations tab where there were zero results -- it gives me this response (also see in the screenshot below):
"We found 0 Organizations. Would you like to view 9 Retired Organizations?"

However, when I click on "view 9 retired organizations", I also get zero results because none of those retired orgs match my search criteria.

A couple options:
- Modify the logic so that the search for retired resources applies the current search criteria - this would change the prompt to:
```
We found 0 Organizations that match your search criteria. Would you like to view 3 retired Organizations that match your search criteria?
```

- Or, just prompt to "also search retired Organizations" without showing any numbers -- so don't actually perform a search in advance:
```
We found 0 Organizations that match your search criteria. Would you like to also search retired Organizations?
```

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/52bb9966-2584-47aa-a605-09e3f70596df)

**Comment by snyaggarwal** [comment]
@paynejd This was also a bug, since retired is only there in Concepts and Mappings.
I have removed it from other resources.
