### ISSUE TITLE
Automatically create released CIEL source version with QA/Demo deployments

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#148]
We need to automatically create a source version with "released": True when we redeploy to QA and demo. So, after the CIEL dictionary is imported, run the request below. Second, the date (and hence the ID/description) for the source version will of course change as we update the CIEL dictionary.

`POST /orgs/CIEL/sources/CIEL/versions/`
```
{
    "id": "v2018-06-01",
    "released": true,
    "description": "CIEL release v2018-06-01",
}
```

**Comment by Karuhanga** [comment]
@paynejd would it have been possible to deploy an already released CIEL version?

**Comment by cantwi2019** [comment]
Hi What is the status of this ticket ? When can we expect it to be completed?

**Comment by cantwi2019** [comment]
What is the status of this ticket? when can we expect it to be completed?

**Comment by paynejd** [comment]
@rkorytkowski it looks like QA might have been redeployed and there are now no released versions of CIEL. Could you verify which CIEL version is on QA? Is it possible to automatically create a released version of CIEL upon redeployment?

**Comment by rkorytkowski** [comment]
QA does have the latest CIEL version, however it is not automatically released when redeployed. I can implement that tomorrow.

**Comment by Karuhanga** [comment]
@rkorytkowski  Kindly let us know when you manage to. Thank you.

**Comment by paynejd** [comment]
@karuhanga I have manually released the new source version on QA for now
until the fix is in place. FYI It will be reset after the next deployment

**Comment by rkorytkowski** [comment]
The fix is in place. The export is downloadable, however, there's some issue with concepts/mappings not being properly listed for a new version on the details page. I'll address ASAP.

**Comment by Karuhanga** [comment]
> there's some issue with concepts/mappings not being properly listed for a new version on the details page.

@rkorytkowski any progress on this?

**Comment by Karuhanga** [comment]
This(https://github.com/OpenConceptLab/oclapi/commit/2d365ba133611f901a17eea85c78306f54c60f5b) should address the auto release.
