### ISSUE TITLE
Update CIEL on QA

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1482]

**Comment by paynejd** [comment]
Is this complete?

**Comment by snyaggarwal** [comment]
No its not, will keep this ticket and ask Burke for next release to be updated on QA as well.

**Comment by snyaggarwal** [comment]
Running latest CIEL import on QA. This one is already imported on Staging and Production

**Comment by snyaggarwal** [comment]
Latest CIEL is imported on QA. Closing this.
