### ISSUE TITLE
Quick UI fix on user profile

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1483]
Email address overlaps the main body of content on the user profile page. See screenshot below...

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/0723054d-6d04-4bd0-b1c2-c3f284a5cfbf)

**Comment by snyaggarwal** [comment]
@paynejd This is fixed and deployed on QA

**Comment by jamlung-ri** [comment]
Seems to be fixed, at least with the Company field. I couldn't change my email address easily though, so I was unable to test that.
![image](https://user-images.githubusercontent.com/55999682/220925261-7f5ccf9b-fd80-4411-8ce8-7e6f7aef8aa4.png)
