### ISSUE TITLE
Information Architecture project

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1484]
We're following on Object Oriented UX approach to understanding current and future needs of OCL web users to define a new Information Architecture to guide future design projects.

**Comment by paynejd** [comment]
Just checking- is this ticket still active or should it be closed?

**Comment by paulsonder** [comment]
This project was completed.

**Comment by paynejd** [comment]
Hi Paul- Is the completed information architecture available to view as a
document/web page of some sort?
