### ISSUE TITLE
Redirect chat.openconceptlab.org to ocl.discourse.group

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1488]

**Comment by rkorytkowski** [comment]
@paynejd I need an address for CNAME in the form of <something>.hosted-by-discourse.com
It should have been included in an e-mail when you setup discourse or visible somewhere in discourse settings. Also I will need admin access to discourse to setup the new domain or ask you to follow https://meta.discourse.org/t/configure-your-domain-name-for-hosted-discourse/21827

**Comment by paynejd** [comment]
@rkorytkowski You are now an admin on ocl.discourse.group

It looks like Discourse may have disabled use of your own domain name for new free hosted discourse accounts: See "Where will the site live?" here: https://free.discourse.group/

It looks like we can upgrade to the Standard Hosted plan with a 50% discount ($50/mo) which would let us use our own domain name. But, we also want to integrate with our Single Sign On. The standard plan only supports DiscourseSSO -- is it possible for us to link OCL Online accounts to that? If not, the Business plan supports OpenID SSO -- would we be able to use that? I need to check if they would still offer a 50% discount, which would make it $150/mo.

We also have a short-term option of just redirecting chat.openconceptlab.org to ocl.discourse.group (without SSO), but that isn't too useful...

**Comment by rkorytkowski** [comment]
For now I just setup a redirect. I'll explore SSO options.
