### ISSUE TITLE
Apply beta icon to Operations action menu item

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1489]
Add `beta` superscript to Operations menu item, same as the Clone action button -- both screenshots are below

<img width="189" alt="image" src="https://user-images.githubusercontent.com/1189689/221198598-552929f8-9d21-4467-bd28-443574977807.png">

<img width="185" alt="image" src="https://user-images.githubusercontent.com/1189689/221196067-2b36da9c-78a8-494f-bec5-517c6f91a86f.png">

**Comment by snyaggarwal** [comment]
@paynejd this is added and deployed on QA
