### ISSUE TITLE
Import CIEL v2019-07-01 for all environments

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#149]
@rkorytkowski 

The 2019-Aug CIEL dictionary is ready to be imported into OCL. We will need to import into all environments and update deploy scripts with this. Please address #148 simultaneously.

Import script is in your email inbox...

I am reviewing all mapping sources and lookup tables to verify if any are missing -- will update this ticket if yes.

**Comment by paynejd** [comment]
CIEL imported on production, staging, and demo. QA still remaining.

**Comment by rkorytkowski** [comment]
Imported on all envs.
