### ISSUE TITLE
Unable to delete source in production

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1492]
A user reported trying to Delete this source via the TermBrowser several times: https://app.openconceptlab.org/#/orgs/MSFOCP/sources/ET2

After multiple attempts, all concepts were deleted, but the mappings won't delete.

I tried deleting the source again as `ocladmin` and also could not delete it

No errors seem to be thrown

@snyaggarwal Can you check logs to see what's going on? And can you go ahead and delete the source?

**Comment by paynejd** [comment]
Correction- it looks like it may have thrown an error in celery -- 21 occurrences of this one: https://errbit.openconceptlab.org/apps/61778921e685dd0007ed0153/problems/6374fb86e685dd0007eec684

**Comment by snyaggarwal** [comment]
@paynejd I deleted the source and created a bug card for the errbits we are receiving #1498, will work on it separately.
