### ISSUE TITLE
Improve $cascade UI with $clone components

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1496]
Goal is to update the UI for "Add to Collection" in the TermBrowser, generally borrowing from the $clone UI that is nearly complete (see #1465)

**Comment by jamlung-ri** [comment]
@paynejd @snyaggarwal Can you take a look at this quick and dirty mockup and see if it feels good? If so, I think we can have Sunny start developing it, using mostly the same components and principles from the Clone to Source UI.

https://walkthroughs-stick-016101.framer.app/

**Comment by jamlung-ri** [comment]
@snyaggarwal We discussed this on the Architecture call today a bit. Instead of using the mockup linked above, we just want to start with a simple addition to the "Add to Collection" screen.

See [this drawing](https://docs.google.com/drawings/d/1jQaitzfCkObMuXlJb6ZaHby_81SMt21S0NDK2sZpLlw/edit) for how we think this can look.

Tooltip text: 

> Transforming to static references means that after concepts and mappings are added to your collection, they will not change even if they are updated at the source.
> 
> Uncheck this box to allow dynamic references, which may help you to keep your collection up to date in the future. See this YouTube video for details.

YouTube video link: https://www.youtube.com/watch?v=bl2IilO0Fec&list=PLbjKElEpop-Ubhm5Xz4sQ7u7ugune_CXF&index=2

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on QA.
I have tried to not change the current behavior.
- By default, Transform References is not selected (false).
- When you select OpenMRS cascade, it will be **auto-selected** (with an option to uncheck)
- You can select Transform with any type of cascade operation.

Let me know if any of these behaviors needs to change.

**Comment by jamlung-ri** [comment]
This is working well on QA!

Can the "Transform References" line be indented a bit, just to offset it from the rest of the options?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd this is deployed everywhere. Please close if all looks good.

**Comment by paynejd** [comment]
2 quick things:
- If I click on "OpenMRS cascade" option, then "Transform to static
references" is automatically selected. But then if I switch back to any of
the other options, it stays selected even though it shouldn't be. Clicking
on the other options should probably clear the checkbox
- The tooltip for the OpenMRS cascade option is styled differently than the
tooltip for the "Transform to static references" checkbox (white vs. gray
background) -- should be consistent

**Comment by snyaggarwal** [comment]
@paynejd Added these. Should be available on QA soon

**Comment by jamlung-ri** [comment]
@snyaggarwal I think this is good to go. Jon's suggested changes are now working on QA. Let's deploy it to Prod

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere
