### ISSUE TITLE
FHIR Feedbacks/issues

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1497]
(from Kenya NHDD)

- [x] CodeSystem `$validate-code` is giving false positive response. Returns true for code that dont exists.
- [x] Editing a source to add FHIR field metadata not populating properly
- [x] Could only create codesystem via User endpoint, not via Org endpoint.

**Comment by rkorytkowski** [comment]
@snyaggarwal by chance do you have more info on "Editing a source to add FHIR field metadata not populating properly"? I'm not exactly sure what they tried to do. Were they trying to add FHIR fields via PUT to oclapi sources?

**Comment by snyaggarwal** [comment]
@rkorytkowski They were trying to add values of FHIR fields (like identifier) from TB forms and were not able to search it. I will confirm this again from Kenneth and get the exact json to reproduce this. You can leave this one with me.

**Comment by rkorytkowski** [comment]
Thanks @snyaggarwal! 

"Could only create codesystem via User endpoint, not via Org endpoint." does work properly with the currently deployed version to QA.

**Comment by rkorytkowski** [comment]
The issue with validate-code was that if url was given and source did not exist then it always returned true.

**Comment by snyaggarwal** [comment]
@rkorytkowski Closing this as this was fixed many sprints back.
