### ISSUE TITLE
Index/facet mismatch for hierarchy meaning/custom validation schema

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1499]
On the Sources tab in global search (signed in as ocladmin), there are 716 sources. However, the Custom Validation Schema and Hierarchy Meaning facets have way fewer sources -- see this screenshot:

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/564e9b1a-676d-47ff-badf-dceda419b9c4)

**Comment by paynejd** [comment]
This is also true for "Custom Validation Schema" with collections

**Comment by snyaggarwal** [comment]
@paynejd this is fixed on QA.

**Comment by paynejd** [comment]
Looking good on QA!
