### ISSUE TITLE
super admins should always be able to update sort order

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1502]
As `ocladmin`, the TB did not give me the option to update sorting for a user's source (see screenshot)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/5995b36b-1ed6-4291-a024-41bcda123198)

**Comment by snyaggarwal** [comment]
@paynejd Add Mapping and sort Mappings are available inside the source, not from global search

**Comment by snyaggarwal** [comment]
@paynejd I have made the changes so that everything is available from gloabl search as well.

**Comment by jamlung-ri** [comment]
Confirmed on QA that sorting mappings is available for ocladmin in the global search
