### ISSUE TITLE
?limit=100 is appended to some GET requests

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#151]
?limit=100 is appended to some GET request regardless of whether or not a limit query exists or if it is being added to existing params, leading to situations like;
`/?foo=bar&bar=baz?limit=100`

Noticed this behavior while testing out a fix but I have failed to pin down the actual middle ware that is causing this. I propose adding middleware to revert this change to the url.

Further context;
- I checked and the `?limit=100` is hard coded somewhere since it is not using the dynamic names specified in the settings file.

**Comment by paynejd** [comment]
Can you provide an example of where this is happening when you wouldn't
expect it to?

**Comment by Karuhanga** [comment]
I have made a small modification to a test, here(https://github.com/Karuhanga/oclapi/commit/bcf70803955134041f6492a66768784188b01100).
The logs from that request show the request url as being;
```
INFO 2019/09/12 02:22:50 [middlewares.py:35 process_response()] 0.0435419082642 sec GET /orgs/?verbose=true&limit=10?limit=100 : 200
```

As opposed to the expected;
```
/orgs/?verbose=true&limit=10
```

**Comment by rkorytkowski** [comment]
I don't think the limit itself is an issue here. In fact it should be automatically populated per REST framework config at https://github.com/OpenConceptLab/oclapi/blob/master/ocl/oclapi/settings/common.py#L202-L203

The issue is why the url is in form of ?foo=bar&bar=baz**?**limit=100 instead of ?foo=bar&bar=baz**&**limit=100. It needs further investigation....

**Comment by Karuhanga** [comment]
> The issue is why the url is in form of ?foo=bar&bar=baz?limit=100 instead of ?foo=bar&bar=baz&limit=100. It needs further investigation....

Also, the fact that it is appended regardless of whether or not there is already a limit param.
