### ISSUE TITLE
Bug: Concept appears twice in collection when searching 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1513]
When looking at [this OpenMRS collection](https://app.openconceptlab.org/#/orgs/openmrs/collections/ANCDAK/?q=blurred&isTable=true&isList=false&page=1&exactMatch=off), the Blurred Vision concept appears twice. However, without searching, the concept only appears once in the collection. Is this an index issue?

When searching:
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/29fd3742-61a7-4a97-bc80-ce94162c43b7)

When not searching:
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/c6a7a0bd-d30e-45ae-93c2-fbf04ccae920)

**Comment by snyaggarwal** [comment]
@jamlung-ri I have checked the data in DB, and that looks good. Seems to be an index issue, but reindexing on this dint help. I have to take dump and check if ES is returning duplicate result.

**Comment by jamlung-ri** [comment]
Looks good!
