### ISSUE TITLE
DM to TB redirect to specify origin query parameter

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1515]
In order to detect redirect and show some info to DM users specifically, while redirecting from DM to TB,  add some query param for easy detection, like — 
`https//app.qa.openconceptlab.org?origin=https://openmrs.qa.openconceptlab.org` 
This is more reliable than `document.referrer`

**Comment by snyaggarwal** [comment]
This is done for qa/staging. Will wait for production.

**Comment by jamlung-ri** [comment]
@snyaggarwal One issue I noticed with this experience - if you aren't signed in already when you are redirected, you only get a couple of seconds to read the pop-up before you're redirected to the SSO page. Once you sign in, it does not take you back to read the pop-up.

**Comment by snyaggarwal** [comment]
@jamlung-ri One quick solution to this is to not redirect if the popup is visible. Let me know if that works

**Comment by snyaggarwal** [comment]
@jamlung-ri I have added this for now, to wait for user to click on ok and then it will redirect.

**Comment by jamlung-ri** [comment]
@snyaggarwal That worked great for me!
