### ISSUE TITLE
Change "Members" header to a link on org home page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1519]
NOT URGENT

Similar to GitHub, let's make the "Members" header on the org home page into a link that takes a user directly to the members tab

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/8897db2f-f763-4bb0-8812-e5c941ca556a)

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA/Staging

**Comment by snyaggarwal** [comment]
@paynejd this is deployed everywhere, please close it if all looks good
