### ISSUE TITLE
Prepare for CSV import thru API

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#152]
ocldev.OclStandardCsvToJsonConverter now supports a standard CSV template that can be converted to JSON and imported. Before, you'd have to write instructions in python for each CSV that you wanted to convert to JSON, which was very prohibitive. Just tried out the new approach with the WHO Malaria Elimination community and it simplified the import process tremendously.

We'd like to expose this new functionality via the API in two ways:
1. Use API to convert a standard CSV to OCL-formatted JSON for import
2. Use API to submit a CSV that OCL converts to JSON and bulk imports

I'd like to get input on how we structure the API, and here's my initial thinking:
* Implement new endpoint `/manage/prepareimport/` - this would accept a CSV file and, if successful, return JSON ready to be imported
* Modify existing endpoint `/manage/bulkimport/` to accept either CSV in addition to JSON; if submitting CSV and the conversion to JSON is successful, it would still respond with a task ID (same as now) after the bulk import processing begins. If the conversion to JSON fails, it would respond with error message from the conversion.

The above model seems like it could be extended to support other formats or to support validation of an import before submitting for processing, both of which seem like the right direction to head.

I'm not wedded to this approach though and am curious what others think.

@rkorytkowski @maurya @karuhanga

**Comment by paynejd** [comment]
Including possible implementation approach here as well...

1. Implement new API endpoint to convert CSV to JSON using the standard template

## Parameters
* **verbose** - Includes additional information in the response to help with troubleshooting

Response content-type is normally JSON; but it is TEXT if verbose=True or if an error occurs.
Note however that the output is typically a JSON lines file -- is that a valid content type?
If not, what is your recommendation? One option is to change the output to be a JSON list of
dictionaries. E.g. `[{...}, {...}, {...}]`. This would lead to minor changes to the bulk import
process to be able to support either method (json lines or list of dicts), but that would
be an easy fix.

Example Request:
```
POST /manage/prepareimport
```
Request Body:
```
CSV file...
```

Example code:
```
import json
import ocldev.oclcsvtojsonconverter
import ocldev.oclfleximporter

# Input parameters
csv_filename = 'hl7_AdministrativeGender.csv'  # Use this if loading from file
input_list = []  # Use this if pre-loaded as a list of Python dictionaries, where each key/value pair is a cell in the CSV
verbose = False
csv_processing_method = ocldev.oclcsvtojsonconverter.PROCESS_BY_DEFINITION  # By definition is default. Or PROCESS_BY_ROW

# Process the CSV -- Use one of these
csv_converter = oclcsvtojsonconverter.OclStandardCsvToJsonConverter(input_list=input_list, verbose=verbose)
csv_converter = oclcsvtojsonconverter.OclStandardCsvToJsonConverter(csv_filename=csv_filename, verbose=verbose)
if csv_processing_method == ocldev.oclcsvtojsonconverter.PROCESS_BY_ROW:
	results = csv_converter.process_by_row()
else:
	results = csv_converter.process_by_definition()

# Output as response -- note that otuput happens during processing if verbose is True
if not verbose:
	for result in results:
	    print(json.dumps(result))
```

2. Modify bulkimport API endpoint to accept CSV or JSON
We want to modify the bulkimport API to allow users to submit a bulk import request with CSV
as the body, in addition to maintaining support JSON support. If a user submits a bulk import request
with CSV content-type and CSV content in the body, then run the same code as above and follow up
with actually running the import. If an error occurs during the CSV-to-JSON conversion, then return
the error message with an error response code and content-type of TEXT.

/manage/bulkimport/

**Comment by rkorytkowski** [comment]
It seems right to me. What's the use case for /prepareimport?

**Comment by paynejd** [comment]
The use cases for /prepareimport would be:
1. To verify that the CSV converts to JSON correctly
2. For advanced users -- to convert a CSV to JSON and then modify for
features that are not supported in the CSV representation

**Comment by paynejd** [comment]
Thanks for your feedback on this Rafal. Let's go ahead with implementing the new API endpoint. Closing this ticket out and creating new tickets: #166 and #167
