### ISSUE TITLE
Global search showing content that I don't have permission to see?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1521]
I am seeing content in the global search that I should not have access to. OCL correctly doesn't allow me to see the concept in the side panel, but I don't think I should be seeing it in the search results if I can't access it.

![image](https://user-images.githubusercontent.com/55999682/225911000-b2a7a9ef-1d34-451c-ab17-c0cf9a6bc3a1.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this should be fixed now

**Comment by jamlung-ri** [comment]
Seems good now. Thanks!
