### ISSUE TITLE
Source Version Summary APIs

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1527]
Source Version Summary is painted on TB with various different APIs. There are multiple flavors of summary API right now. We need to come up with better signatures.

#### Current APIs
API | Example | Meaning
-- | -- | --
/summary/ | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/ | Returns counts of concepts/mappings/versions
/summary/?verbose=true | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/?verbose=true | Returns distribution of concepts/mappings important fields (uses ES facets)
/summary/?verbose=true&distribution=to_sources_map_type | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/?verbose=true&distribution=to_sources_map_type | Returns list of target sources that the current source's mappings pointing to, with there distribution by map_type
/summary/?verbose=true&distribution=from_sources_map_type | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/?verbose=true&distribution=from_sources_map_type | Returns list of from sources that the current source's mappings associated from, with there distribution by map_type
/summary/?verbose=true&distribution=from_sources_map_type&sources=source1,source2 | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/?verbose=true&distribution=from_sources_map_type&sources=CIEL | Returns source1 and source2 as from sources that the current source's mappings associated from, with there distribution by map_type
/summary/?verbose=true&distribution=concept_class | https://api.qa.openconceptlab.org/users/ocladmin/sources/123/summary/?verbose=true&distribution=concept_class | Returns concept_class distribution of concepts
/summary/?verbose=true&distribution=datatype |   | Returns datatype distribution of concepts
/summary/?verbose=true&distribution=map_type |   | Returns map_type distribution of mappings
/summary/?verbose=true&distribution=name_type |   | Returns name type distribution of concepts
/summary/?verbose=true&distribution=name_locale |   | Returns Language distribution of concepts

**Comment by snyaggarwal** [comment]
cc @paynejd

**Comment by paynejd** [comment]
@snyaggarwal  is there anything left here other than documentation?

**Comment by snyaggarwal** [comment]
This was done.
