### ISSUE TITLE
Source/Collection API include resources

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1528]
A couple of API endpoints didn't seem to be working during a demo today. @snyaggarwal can you investigate? They did return the source details, but it didn't include concepts or mappings.

* https://api.openconceptlab.org/orgs/NMRS/sources/NMRS/HEAD/?includeConcepts=True&includeMappings=true
* https://api.openconceptlab.org/orgs/NMRS/sources/NMRS/?includeConcepts=True&includeMappings=true

**Comment by jamlung-ri** [comment]
Oh okay. I think it's in our OCL Docs ([link](https://docs.openconceptlab.org/en/latest/oclapi/apireference/sources.html#get-a-single-source)), if I'm understanding correctly.

![image](https://user-images.githubusercontent.com/55999682/228561121-db6d9eee-c872-4a48-a86d-e83dccae049b.png)

**Comment by snyaggarwal** [comment]
Interesting!
It might be the behavior in v1, which we dint port (or missed).
For a bigger source like CIEL, returning all 50k+ concepts and 150K+ mappings will be a too slow/big response.

Adding this to our dev call Future topics.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA

**Comment by snyaggarwal** [comment]
This is deployed everywhere.
@jamlung-ri Please close this once everything looks good.

**Comment by jamlung-ri** [comment]
Looks good on Prod!
