### ISSUE TITLE
Repo-level search returning zero results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1529]
The concept tab for this source has lots of concepts with the phrase "outside":
https://app.openconceptlab.org/#/orgs/NMRS/sources/NMRS_Source/

However, if I do a source-level search for "outside", it returns zero results:
https://app.openconceptlab.org/#/orgs/NMRS/sources/NMRS_Source/?q=outside&isTable=true&isList=false&page=1&exactMatch=off

Same thing happened when doing all source-level searches

**Comment by snyaggarwal** [comment]
Closing this.
