### ISSUE TITLE
Resource selection "action toolbar" should not scroll

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1530]
The "resource selection action toolbar" appears when you select a concept/mapping etc. in a search results list, e.g. `1 Selected, Download, Add to collection, clone`:
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/1189689/228808464-5ee50c3a-0f28-4018-849f-50aa80fb53f3.png">

However, if you scroll down in the search results, the column headers are "sticky", but the action toolbar disappears, e.g.:
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/1189689/228808698-04ebc736-449c-40b1-907c-bab7b1e61c58.png">

In our training workshop, this has been confusing to users.

Can we make the action toolbar "sticky" along with the column headers?

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA

**Comment by paynejd** [comment]
Working great!!

**Comment by snyaggarwal** [comment]
This is deployed everywhere.
