### ISSUE TITLE
Sort UI Bug - Dot Icons not appearing for content owner

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1534]
When a user would search for a concept in their source, select it in the search results, and then view it in the split view, the Sort icons (i.e. the 6 dots next to each mapping) were not appearing. The only way we could see the sort icons were to go to the direct concept URL e.g.  https://app.openconceptlab.org/#/orgs/MSFOCP/sources/MSFOCP/concepts/2305/ . I was also able to replicate this in Production.

Source: https://app.openconceptlab.org/#/orgs/MSFOCP/sources/MSFOCP/?q=anesthesia&isTable=true&isList=false&page=1&exactMatch=off
![image](https://user-images.githubusercontent.com/55999682/230142148-002c070d-096e-43af-b71a-e2688ff19c03.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed everywhere.

**Comment by jamlung-ri** [comment]
Awesome, it's looking good to me on Production. We can close this out now, and I'll check with Laure and reopen this if needed.
