### ISSUE TITLE
Update "auto-expansion" labels

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1536]
Let's consistently use "Auto-Expand" (with the hyphen and this exact casing). This applies in several places:

- Create new collection
- Edit collection
- "Auto-Expanded" and "Auto-Generated" tooltips on the "Versions & Expansions" tab
- New and Edit collection version forms

Are there any other places?

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/bb61239d-17f3-4803-9936-6068094c63fa)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/f2a0aa73-2a63-4d7d-a9e5-c364439bbbcd)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/5462dfca-507f-4597-b85b-063941e4ca4b)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/7893ac75-5782-402c-9673-b0f7fbb18433)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/b7ca5ccb-159b-4ebe-a3d7-abee0459ac50)

**Comment by snyaggarwal** [comment]
Deployed on QA

**Comment by snyaggarwal** [comment]
Deployed everywhere
