### ISSUE TITLE
"Transform to Static References" checkbox not appearing

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1543]
When attempting to add dynamic references to a collection using the "Add References" button in my collection, the option to turn off static references is not appearing. It appears when selecting individual concepts and clicking "Add to collection", which is good, but I also want to make dynamic references in this "Add References" workflow too, if possible.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/07ea7c84-f3e3-487f-9c50-30820de324ee)

**Comment by snyaggarwal** [comment]
@jamlung-ri This was a miss. Added and deployed on QA

**Comment by snyaggarwal** [comment]
This is deployed everywhere
