### ISSUE TITLE
List admin-only features in OCL?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1545]
@snyaggarwal Could you please list out the admin-only features that we currently support in OCL? This could be a good place to start for defining permission groups / roles...

**Comment by snyaggarwal** [comment]
Below are the features that can only be done by an OCL Admin
- HEAD Export
- User Management
- Delete custom configuration
- Concept/Mapping & their Version hard delete
- Resource indexing
- Monthly usage report
- Authoring report
- Create/Delete User
- User reactivate
- User admin permission toggles

**Comment by paynejd** [comment]
Moved this into a new requirements doc
https://docs.google.com/document/d/12HAjexQ2_BwbOOAj1NxK-N6g5pIBS6y8UNaKr_SdfFQ/edit

Closing out
