### ISSUE TITLE
SSO Timeout might have reverted?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1546]
Unless my browser just needs a hard refresh, the timeout on SSO tokens might have been reverted back to logging out the user every ~30-45 minutes. I noticed the change when Rafal was making some emergency changes while Sunny was out. It has happened to be on both Prod and QA. 

@snyaggarwal Can you check that this SSO token timeout is correct? I forget if we decided on 24 hours or if we decided on something longer but I think it was at least 24 hours before timing out.

**Comment by snyaggarwal** [comment]
@jamlung-ri this should be fixed now.
