### ISSUE TITLE
Duplicate concepts appearing on Prod in Global Search

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1547]
I am seeing multiples of the same concept appearing on global search on Production.

I had thought this was a browser cache issue, but I have been unable to fix it on my end.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/857977fd-a83a-4c2a-9e54-8b98c0e7cfb4)

**Comment by snyaggarwal** [comment]
Looks like this is happening for non-admin logged in users only.
I was able to reproduce this on local. I have added fix for this, will deploy everywhere tomorrow morning.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed

**Comment by jamlung-ri** [comment]
Looks good! Closing this out since it's already released on Prod.
