### ISSUE TITLE
Auto-assign ID Enhancement - Ability to switch scheme when editing a source

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1549]
Users sometimes want to change the auto-assign ID scheme that they are using on their source (e.g. switch from "Manually assigning Concept IDs" to "Sequentially assigning Concept IDs". 

Talking to @snyaggarwal, the main concern appeared to be when switching from Manual to Sequential - "the new auto 'ID' might clash with existing content. This will have to be left on user’s decision that the user is giving the correct 'start-from' value which is greater than last concept/mapping ID."

It sounds like we need a safeguard to ensure that this switch can be made reliable. For example, perhaps we look at the source's highest numeric value and restrict the user to starting at that value or higher when setting the Sequential starting number.

The other two situations (switching to or from Manual or UUID schemes) should be safe.

**Comment by mseaton** [comment]
This would be helpful.  As I've been trying to successfully create a source via REST with the right configuration, I've found that if I make a mistake the only remedy is to delete and recreate the source.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is available on QA

**Comment by jamlung-ri** [comment]
This has been mostly successful so far, but I'm hitting a bug in the UI form. When trying to change from UUID to Sequential scheme, I am told to "Please fill in mandatory fields", even though I already have this field filled in.

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/8a4c7ca4-00d5-4892-9b25-ec492980b70b)

**Comment by snyaggarwal** [comment]
@jamlung-ri Interesting, I just tried switching between uuid and sequential for the same source of yours on QA and it worked fine. Can you tell me the steps to reproduce it?

**Comment by snyaggarwal** [comment]
@jamlung-ri My apologies, but I already deployed this yesterday (accidentally!) on all environments with other changes that needed to go.

**Comment by jamlung-ri** [comment]
No prob!

**Comment by jamlung-ri** [comment]
> This has been mostly successful so far, but I'm hitting a bug in the UI form. When trying to change from UUID to Sequential scheme, I am told to "Please fill in mandatory fields", even though I already have this field filled in.

@snyaggarwal This bug is resurfacing again, and it looks like the UI is not submitting a value for 'autoid_concept_mnemonic_start_from', even though I put "100" in that box in the UI. This is causing an error "please fill in the mandatory fields"

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/75baf631-8126-4051-af01-c855bc21a62a)

**Comment by snyaggarwal** [comment]
@jamlung-ri  Added fix for this

**Comment by jamlung-ri** [comment]
Works great! I think it has already been deployed in Prod too but please reopen if needed.
