### ISSUE TITLE
Export throwing 500 error on staging and cannot delete/recreate

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1557]
Requesting this export results in a 500 error. A DELETE request is received (204 response), but it does not actually get deleted. POSTing to create a new export returns a 303. How do we get unstuck?

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-DAA-FY22/DAA-FY22.v0/export/

**Comment by snyaggarwal** [comment]
@paynejd this is fixed.
