### ISSUE TITLE
502 error (timeout) when adding 30 references

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1559]
Mike Seaton at PIH is testing out some scripting with the API on Staging, but when trying to PUT a cascaded set of references, it times out. 

Is it possible to do an asynchronous request, either manually (i.e. add a parameter in the PUT) or automatically (i.e. OCL recognizes that this will be too big and queues it up in the backend)?

```
PUT https://api.staging.openconceptlab.org/users/ocladmin/collections/test-pih-collection/references/

{
  "data": {
    "expressions": [
      "/orgs/PIH/sources/PIH/concepts/12754/",
      "/orgs/PIH/sources/PIH/concepts/12571/",
      "/orgs/PIH/sources/PIH/concepts/12892/",
      "/orgs/PIH/sources/PIH/concepts/12647/",
      "/orgs/PIH/sources/PIH/concepts/12656/",
      "/orgs/PIH/sources/PIH/concepts/10669/",
      "/orgs/PIH/sources/PIH/concepts/10473/",
      "/orgs/PIH/sources/PIH/concepts/10562/",
      "/orgs/PIH/sources/PIH/concepts/10846/",
      "/orgs/PIH/sources/PIH/concepts/12643/",
      "/orgs/PIH/sources/PIH/concepts/9531/",
      "/orgs/PIH/sources/PIH/concepts/13631/",
      "/orgs/PIH/sources/PIH/concepts/12503/",
      "/orgs/PIH/sources/PIH/concepts/11662/",
      "/orgs/PIH/sources/PIH/concepts/12751/",
      "/orgs/PIH/sources/PIH/concepts/12554/",
      "/orgs/PIH/sources/PIH/concepts/12752/",
      "/orgs/PIH/sources/PIH/concepts/12481/",
      "/orgs/PIH/sources/PIH/concepts/11676/",
      "/orgs/PIH/sources/PIH/concepts/10773/",
      "/orgs/PIH/sources/PIH/concepts/10563/",
      "/orgs/PIH/sources/PIH/concepts/10573/",
      "/orgs/PIH/sources/PIH/concepts/13604/",
      "/orgs/PIH/sources/PIH/concepts/13657/",
      "/orgs/PIH/sources/PIH/concepts/9362/",
      "/orgs/PIH/sources/PIH/concepts/12616/",
      "/orgs/PIH/sources/PIH/concepts/9779/",
      "/orgs/PIH/sources/PIH/concepts/13678/",
      "/orgs/PIH/sources/PIH/concepts/11397/"
    ]
  },
  "cascade": {
    "method": "sourcetoconcepts",
    "cascade_levels": "*",
    "map_types": "Q-AND-A,CONCEPT-SET",
    "return_map_types": "*"
  }
}
```

**Comment by mseaton** [comment]
Thanks @jamlung-ri and @snyaggarwal .  Note, I've also been getting 502 timeouts with some other synchronous calls as well.  For example, I have one call to create a source that typically returns a 502 (but the source is actually created in the end), and another that returns a proper 200 response containing the details of what was created in the response json.  So, in general, it would be helpful to either extend/avoid timeouts (in nginx or wherever the culprit is) or to allow any commands to be run asynchronously with a task id that can be queried for completion status.

**Comment by snyaggarwal** [comment]
@mseaton Could you also add details of the request here for Source create that throws 502?

**Comment by snyaggarwal** [comment]
@mseaton @jamlung-ri there is an option to trigger async references add via API. Just append `?async=true` in the PUT request URL and it will return the `task` ID. Then you query for task using `GET /tasks/<taskID>/` for completion

**Comment by snyaggarwal** [comment]
@mseaton Source creation should be fixed now. Collection references can be added async, will be discussing this flow via TB today in our dev call.

**Comment by snyaggarwal** [comment]
by default the process to add references is async now.
