### ISSUE TITLE
Sign-in hyperlink in 401 page is broken

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1560]
Low urgency. Nice-to-fix for professional experience.
Steps: 
1. Have a bookmarked page to OCL that is not the login page (e.g. I tend to start from https://app.openconceptlab.org/#/users/gpotma )
2. See this page with the 401 message: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67400059/233732512-47147739-c54a-43d2-b236-c60208f47c79.png">
3. Click the "Sign-in" hyperlink text in the 401 error message (hyperlink is: https://api.openconceptlab.org/users/login/?client_id=ocl&state=fj8o3n7bdy1op5&nonce=13sfaed52le09&redirect_uri=/users/gpotma
4. See: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67400059/233732581-cd38d07b-6dc3-40df-a183-eaf6ce3557c7.png">

Expected: Should see the same login page as you would by clicking the big Blue Sign-In button on the top right. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67400059/233732752-15188e98-5df9-43b1-8976-47a72613d1d2.png">

**Comment by snyaggarwal** [comment]
This is fixed and deployed on QA, will be deployed everywhere soon
