### ISSUE TITLE
TB/API async requests flow

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1561]
#### Current State:
- Some APIs have async behavior via appending `?async=true` but thats not known to TB. For example, add references
- Some APIs are by default async, for example -- delete org, but doesn't return task ID.
- Bulk Import APIs adds username in taskId and returns it.

#### Suggestions:
- All task ids to have username and existing queue-names -- `<uuid>-<username>-<queue>`
- All async API requests to return taskId, state, queue.
- TB to have option to make async request -- Toggle switch. In some places, selected by default and may be disabled
- TB to copy the taskId to clipboard from response if we can't show it in the UI.
- (new) API to return all user's tasks (from last 48 hours)

**Comment by jamlung-ri** [comment]
@snyaggarwal This all sounds good to me. Need any time on the Dev call to talk more about it? I will miss it but I think this could be a helpful fix.

**Comment by snyaggarwal** [comment]
Already added to the agenda

**Comment by snyaggarwal** [comment]
The flow that we agreed on for most user based requests that can be async:
- Request async by default (make task-id with user's username embedded)
- return the response from the async task if finishes in X-Seconds, or
- return task id/state/queue info as response
- copy the task-id in clipboard on response in TB

**Comment by snyaggarwal** [comment]
This is already done for:
- Collection References add
- Source Delete
- Collection Delete
- Org Delete (about to be deployed)

**Comment by jamlung-ri** [comment]
Potential thing to make this a bigger ticket: Having a space or screen for asynchronous tasks or jobs to be seen in OCL (blocker = Flower could not search by username, ID, etc.)

**Comment by snyaggarwal** [comment]
@paynejd Its not under development. This one now is a v3 ticket to have tasks UI.
