### ISSUE TITLE
Adding cascading reference fails if concept already exists in collection with OpenMRS validation schema

### ISSUE THREAD

**Issue by mseaton** [OpenConceptLab/ocl_issues#1563]
This may well be the intended behavior, but I was trying to create a Collection with a small number of references that were configured to cascade into their q-and-a and concept-set mappings, and ran into an error trying to do so.

1. I created a new Collection, and gave it a validation schema of OpenMRS
2. I added a reference to a Concept, with `method: "sourcetoconcepts", cascade_levels: "*", map_types: "Q-AND-A,CONCEPT-SET" and return_map_types: "*"`
3. I added a second reference to a different Concept (which presumably has some of the same associated Concepts as the first added Concept), and got the following error:  `Concept or Mapping reference name must be unique in a collection.`.  Another time (maybe with slightly different steps, I got this error:  `Concept fully specified name must be unique for same collection and locale.`)

I then deleted the Collection, and re-ran the above steps but did not set the OpenMRS validation schema from the Collection.  Without the OpenMRS validation scheme, things worked fine.

I would have expected this to be allowed if the two references were to the same Concept.

@snyaggarwal / @jamlung-ri not really a blocker for me, as I don't need to add the OpenMRS validation scheme to a Collection.  But FYI

**Comment by snyaggarwal** [comment]
@mseaton this is fixed for OpenMRS Schema.
