### ISSUE TITLE
Collection limited to 1024 references

### ISSUE THREAD

**Issue by mseaton** [OpenConceptLab/ocl_issues#1565]
I'm trying to create a Collection that contains most (but not all) of the concepts in my source, and to do so I have created a Concept that has concept-set references to other concepts, which may themselves have concept-set or q-and-a references, which themselves...etc.  I have then added that top-level Concept to the collection with cascade `"sourcetoconcepts", cascade_levels: "*", map_types: "Q-AND-A,CONCEPT-SET" and return_map_types: "*"`

I'm expecting around 6200 concepts in the Collection, but after it is created I am only seeing 1024 concepts.

The documentation here implies there may be a fixed limit to cascadeLevels to 1000 resources or a number set by a system administrator:  https://docs.openconceptlab.org/en/latest/oclapi/apireference/cascade.html

Is there a fixed limit that is being hit that I can bypass?  Or is there another issue that is causing the resulting Collection to only have 1024 concepts?

This is (currently) the Collection in question:

https://app.staging.openconceptlab.org/#/orgs/PIH/collections/PIHEMR_Concepts_From_Set/

@snyaggarwal / @jamlung-ri FYI.

**Comment by snyaggarwal** [comment]
with ?async=true, this limit can now be bypassed.
