### ISSUE TITLE
Term browser shows inconsistent numbers of concepts due to retired

### ISSUE THREAD

**Issue by mseaton** [OpenConceptLab/ocl_issues#1567]
In the term browser, I have a Collection which indicates that it contains 6262 concepts:

![image](https://user-images.githubusercontent.com/356297/234864513-bd5ed051-57b1-4686-9001-4eea1a6788ea.png)

However, when I navigate into this Collection, the data table shows 6267 concepts:

![image](https://user-images.githubusercontent.com/356297/234864650-867e6cb9-f658-48ff-8888-c33697852536.png)

This is - I believe - due to retired Concepts.  There are 5 retired Concepts in this Collection, and these are excluded from the totals in the first view, and included in the totals in the second view.  It would be preferable to be more consistent / clear.  Most likely this would mean that the first view should show 6267, maybe with an indication that 5 of these are retired if that's important.

Since the versions page shows 6267, I believe this is probably a bug in the first view above, where it is incorrectly excluding retired concepts from the count.

![image](https://user-images.githubusercontent.com/356297/234865585-11db1585-2671-4a55-9a7b-95bf27a5a0a6.png)

@jamlung-ri / @paynejd / @snyaggarwal

**Comment by snyaggarwal** [comment]
This was fixed.
