### ISSUE TITLE
Quick Add Tweak for Manual Mapping

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1575]
Overall, users are really enjoying the quick-add feature in TermBrowser where you can quickly add a mapping to a concept from the Concept Details sidebar. However, this restricts the user's options by only allowing them to map to sources that already exist and using concepts that already exist. Sometimes, people need to add mappings to a concept that doesn't exist.

For this reason, I mocked up a quick idea for how this might work. I don't necessarily love the UI components for it, but I want to just get the idea across. Recording: https://iu.mediaspace.kaltura.com/media/t/1_60h768v9

@snyaggarwal Can you comment on the technical feasibility?

@paulsonder This is, of course, a quick and dirty fix to the TermBrowser's Quick-add feature that is intended to help users e.g. MSF and PIH. The principles should carry over into the long term OCL design, but it doesn't need to be perfect quite yet. Can you comment on the design of it and if this is acceptable for users at this point? Totally open to changes in UI components, of course.

**Comment by snyaggarwal** [comment]
@jamlung-ri Looks good to implement, just wanted to check if @paulsonder has any inputs

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder I updated the design to look a little less clunky. Still may need some help though. https://iu.mediaspace.kaltura.com/media/t/1_qzl8ew5u

**Comment by jamlung-ri** [comment]
@paulsonder Are we at a place where we can move these designs forward? I lost track of this for a bit but it's certainly still relevant.

**Comment by paulsonder** [comment]
![Screenshot 2023-07-18 at 09.37.16.png](https://images.zenhubusercontent.com/62f2740361fc271207ca9fb3/5f90d467-794e-4f65-a6e0-6cbdd4f5b23a)

As a user, if I wish to map to a **Concept** from an **External Source**, then the **External Source** should be setup as a **Source** in OCL. The user then has the choice to select a **Code** from the **Action Menu**, or type a new **Code**, then type a **Concept Name** in the field that is revealed when adding a new **Code**.

**Comment by jamlung-ri** [comment]
@snyaggarwal When you're available, I'd like to reignite this topic. I lost track of it, but it looks like we might have a design in Paul's last comment. What are your thoughts? Are we in good shape to implement this?

**Comment by snyaggarwal** [comment]
@jamlung-ri With Paul's design, we will enable the user to map to a concept that doesn't exist in OCL yet. But the user won't be able to map to a concept and a source that doesn't exist in OCL yet. Is that intended?

**Comment by snyaggarwal** [comment]
@jamlung-ri Also may be we should always Name field while adding mapping.

**Comment by snyaggarwal** [comment]
@jamlung-ri deployed a version of this on QA.

**Comment by snyaggarwal** [comment]
@jamlung-ri Is this good for prod deployment?

**Comment by jamlung-ri** [comment]
@snyaggarwal This is good to deploy. I don't expect there to be any immediate changes suggested by the OpenMRS community.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere.

**Comment by jamlung-ri** [comment]
@snyaggarwal One tiny bit of feedback that was brought up in the OpenMRS call today - The "name" field in the Quick Add form is required and blocks the user from creating a mapping. The Name field is recommended but not technically required by OCL, and it's acceptable for someone to only include a Code without specifying a name. Can we make this field optional?

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/bf6e5cdf-f893-4842-8147-fa3b90e9f447)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA and Staging

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere. Please close this if everything looks good here.

**Comment by jamlung-ri** [comment]
Thanks Sunny, that behavior is working now. However, there is another bug (at least I think it's a bug). When I create a mapping using Quick Add, the UI is displaying my the name of my source in the Associations table, but it's supposed to be showing the target source for the mapping. 

Watch the behavior here: https://www.loom.com/share/f0ef9d86797f48529278af39f11ca601

Screenshot: 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/02a14930-5bd6-47c8-9ccb-57ceb8c99f31)

**Comment by snyaggarwal** [comment]
@jamlung-ri Made a typo. Fix is deployed

**Comment by jamlung-ri** [comment]
Awesome, now we're all good!
