### ISSUE TITLE
Add Concept -> Refresh Page

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1576]
A quick fix in Source pages that would help users: 
Currently, when a user adds a Concept, the page refreshes, and the new concept may or may not appear on the page somewhere. 

It would help a user if the concept they just created would immediately appear in the sidebar instead. Meaning, instead of refreshing to page to [my Source](https://app.qa.openconceptlab.org/#/users/jamlung/sources/id-manual2/), can OCL instead go to the URL of the newly created concept e.g. https://app.qa.openconceptlab.org/#/users/jamlung/sources/id-manual2/concepts/new/ ?

Even better, it'd be great if the concept appeared on the Concepts list on the left side, already checked/selected. That's not the highest priority right now but would be a plus.

**Comment by snyaggarwal** [comment]
@jamlung-ri On concept create/update success it will take you to the concept page which will open the concept split view. Deployed on QA

**Comment by jamlung-ri** [comment]
This is working well! I think it's ready to deploy on QA.
