### ISSUE TITLE
Ordering of Quick Add's Map Type 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1577]
Currently, the sort order of the Map Type (AKA Relationship Type) is pretty weird. Instead, could this list adopt the Summary API's Map type options? Similar to the Suggested Sources, it'd be good if people could select map types that they have already used. 

At the very least, maybe the sort order of the list of map types should be alphabetical.

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/6e7a1dc5-9470-4ed5-9168-4a1309269de6)

**Comment by snyaggarwal** [comment]
@jamlung-ri Added groups "Suggested" that comes from source summary and "Ordered" thats rest of the map types, also ordered alphabetically. Deployed on QA.

**Comment by jamlung-ri** [comment]
Looking good! Only potential issue I'm noticing is that it seems to require a page refresh before a map type is moved from the Ordered section to the Suggested section. This could be potentially be bothersome for a user who is trying to add 3 SAME-AS mappings to one of their first concepts, for example. Is there a simple solution for this, or should we leave it alone?

**Comment by snyaggarwal** [comment]
@jamlung-ri I will fix that

**Comment by snyaggarwal** [comment]
@jamlung-ri this is also fixed

**Comment by jamlung-ri** [comment]
Awesome, then I think this is good to deploy. The OpenMRS Squad really liked this. Heads up, I want to create a few more tickets where we do this same thing with Concept Class, Data Type, Language, and maybe some others too. Tickets to be written for those.

**Comment by snyaggarwal** [comment]
This is deployed everywhere. Closing this.
