### ISSUE TITLE
Fuzzy Matching 

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1578]

**Comment by paynejd** [comment]
https://docs.google.com/presentation/d/1eUE47I2TNn9laK7dA6Fw7lf4XHjMOXOotN3zGa8sQGg/edit#slide=id.g246323e2058_0_10

**Comment by paynejd** [comment]
This ticket resulted in a ton of search improvements that are documented in the gdoc link above. All future work related to this will go in other tickets/epics. Closing this ticket out.
