### ISSUE TITLE
Ordering of other fields in Concept Create/Edit form

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1584]
More quick quality of life fixes using the summary API, similar to what was done in #1577. Instead of adding to the Quick Add form, however, we should apply them to the Create/Edit Concept form.

The following fields should also have a "Suggested" section, based on what has already been used in the Source. For the values that have not been used in the source yet, ordering them alphabetically will be helpful.
* Concept Class
* Data Type
* Default/Supported Locales (in this case, the Default locale should be first, followed by Supported Locales, followed by other locales used in the source, then the alphabetical list) - This should apply to the locale fields for both Names and Descriptions

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/9066587b-d837-403b-b244-ae1615a30fd4)

**Comment by snyaggarwal** [comment]
@jamlung-ri Deployed on QA.

**Comment by jamlung-ri** [comment]
This is working great! I think it's ready to move forward.

**Comment by snyaggarwal** [comment]
This is deployed everywhere.

**Comment by jamlung-ri** [comment]
@snyaggarwal resolved a bug with this recently. Editing a concept was crashing the page for me. The bug was captured in this video: https://www.loom.com/share/e0a6d5b5e8184049b947ddafb646482d
