### ISSUE TITLE
Draft Search Optimization Plan

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1587]
This plan will include expanding concept search with map codes

Here are the notes from Architecture call:
* Expand concept search with map codes (https://github.com/openconceptlab/ocl_issues/issues/1583) 
* Note that we also may need to look into:
  * Overall concept search results optimization
  * Providing some indication to users why a search result is displayed
* Overall goal: Concepts appear if one or more of their mappings (which types?) match the search term
  * Need to index mappings’ code and name, at least?
  * Need to score appropriately so the search results aren’t diluted
* Potential requirements: 
  * Help users understand why something appears in the search results. Could highlight what made that particular concept return in the search results.
  * Elastic search can return the “context” for what it matched ([highlighting](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html))
* Example:
  * [Global Search for concepts: “A04.9”](https://app.openconceptlab.org/#/search/?q=A04.9&type=concepts)
  * [Search results for all mappings to ICD-10-WHO](https://app.openconceptlab.org/#/search/?q=&isTable=true&isList=false&page=1&exactMatch=off&type=mappings&facets=%7B%22toConceptSource%22:%7B%22ICD-10-WHO%22:true%7D%7D) (see A04.9 is in the list)

cc @jamlung-ri @snyaggarwal @bmamlin @rkorytkowski  -- Please add any initial ideas that you have to this ticket and I'll start to pull this together

**Comment by paynejd** [comment]
Some more thoughts:
* Expand concept search with map codes ([#1583](https://github.com/openconceptlab/ocl_issues/issues/1583)) - we want a concept search for “A04.9” to merge the results from these two current searches:
  * Global concept search for “A04.9”: https://app.openconceptlab.org/#/search/?q=A04.9&type=concepts 
  * Global Mapping search for “A04.9” with exact match on: https://app.openconceptlab.org/#/search/?q=A04.9&exactMatch=on&type=mappings 
* Map code search in the Mappings tab default to a tokenization that is not expected (have to turn on “Exact Match” in order to find mapping results for “A04.9”)
* The behavior of Exact Match is not very clear
* Exposing the new fuzzy search feature has the potential to introduce even more ambiguity in search behavior/results
* Global mapping search for “A04” (without exact match enabled) does not provide useful results at all and this needs lots of optimization – however, when enabling “exact match” the results are as expected

**Comment by rkorytkowski** [comment]
OpenMRS concept search: https://github.com/openmrs/openmrs-core/blob/58cf3a1d390129b375ec7ab96ebdeed0060671a2/api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java#L1407

**Comment by paynejd** [comment]
4 parts to our search optimization:
- Search Components, Criteria and Filters
- Improving search results (weights, indexed fields, etc.)
  - Weighting FSN higher than other name types
  - Searchable map codes, with SAME-AS weighted more highly
- Results display and explanation
- Search performance

**Comment by paynejd** [comment]
An example of **unclear** search behavior... Each of these returns different set of results. The results are probably accurate, but how these searches are different is not clear:
- "colono"
- "colono*"
- "colono" with exact match
- "colono*" with exact match

**Comment by paynejd** [comment]
Also see this Chat thread on "OCL Searches gone wrong": https://chat.openconceptlab.org/t/ocl-searches-gone-wrong/41

**Comment by paynejd** [comment]
NOTE: Implementing "Advanced search" (#1604) is out of scope for this plan

**Comment by paynejd** [comment]
Example search:
https://api.qa.openconceptlab.org/concepts/?q=5089&includeSearchMeta=true

**Comment by paynejd** [comment]
Considerations for what’s next?
- Indexing
  - Add concept descriptions with low weight
  - Replace [Concept Version] with [Combined Concept+Repo Version]
- Remove repo HEAD from global search --- only search HEAD when specifically searching this single repository version
- Mappings
  - Possibly match target concept name (in addition to target concept code)
  - Index inverse mappings (?) --- probably not
- Map types for concept search:
  - Ability to filter by map type (e.g. only search for concepts that have a specific map type)
  - Advanced search

**Comment by paynejd** [comment]
Feedback from OpenMRS squad: When matching a map code in concept search, need to show in the results the matched mapping summary (maptype, map code, and source)

**Comment by paynejd** [comment]
Content here moved into the above OCL Chat post and work will take place in this epic: #1694 and #1607
