### ISSUE TITLE
Bug when searching mappings?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1593]
It appears that, when searching for codes via CIEL's mappings tab, the query is not returning the expected mappings results from ICD-10.

See Loom for details: https://www.loom.com/share/2be728259dce479cb78cc7f458dd130a

Link to query that is NOT working properly: https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/mappings/?q=U07.1&isTable=true&isList=false&page=1&exactMatch=off
(even though [this concept](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165630/) shows that there is a mapping present with ICD-10's `U07.1`)

Link to query that does seem to be working properly: https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/mappings/?q=1494811653&isTable=true&isList=false&page=1&exactMatch=off

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed
