### ISSUE TITLE
Improve Auto-Generated Zip Export Name Convention

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1595]
Request:
[OrgName]_ [CollectionName]_ v[VersionName]_ [ExpansionName]_ [updated date as YYYY-MM-DD]_ [updated time as hhmm 24hr]

(^spaces added above just to avoid markdown formatting this as italics)

eg:
procedures_4.20230405085558.zip
would change to:
openmrs_procedures_v4_expansionname_2023-04-27_0835.zip

_From: Discussion day in Boston with PIH, Brown, OMRS, MSF representatives_
CC @jamlung-ri - we discussed this shortly after you and Andy had to drop off the call.

**Comment by paynejd** [comment]
@snyaggarwal Any blocker to implement this?

**Comment by snyaggarwal** [comment]
@paynejd The only issue with this is we have to rename all the existing cached exports on S3 to this new format. Putting this for small discussion with others in our Arch call.

**Comment by snyaggarwal** [comment]
This is done on QA. We have migrated all the existing exports to the new format.

**Comment by snyaggarwal** [comment]
@paynejd This is queued for deployment on all the env for this weekend. I have tested this on QA and its looking good to me. Can you please confirm if it has no effect on pepfar and/or other scripts?
Marking it as high priority.

**Comment by paynejd** [comment]
I tested out the PEPFAR IMAP integration scripts on QA and it works perfectly!

Please migrate to staging ASAP and will test there too. Just confirming- are you also updating the filenames for existing exports?

**Comment by snyaggarwal** [comment]
@paynejd This is done on Staging. Yes we are migrating existing exports also.

**Comment by snyaggarwal** [comment]
@paynejd @gracepotma This took a while due to some other features blocking deployment, but today this made it to Production. Closing this.

**Comment by snyaggarwal** [comment]
@paynejd It does affect local deployments, and the worst effect is all the repo versions export needs to be created again. There is an API to migrate existing cached imports (if using AWS S3) to new formats.
```
GET /orgs/MyOrg/sources/MySource/?migrate_export_path=true&move=true
GET /orgs/MyOrg/collections/MyColl/?migrate_export_path=true&move=true
```

This will move exports to new formats for all versions and it works only from Admin user.
