### ISSUE TITLE
Custom Attribute Summary API

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1598]
Would it be possible to build a Summary API for Custom Attributes that are in use in the source/collection? Specifically, for the Attribute Name, not the Attribute Value. This would allow the user to query previously used Attribute names in that source or collection, along with the number of concepts that utilize that Attribute name.

This would be in service to the following use case: I create a concept in TermBrowser, which is somewhat similar to a previous concept, but I want to make sure I use the same Custom Attribute names as previous concepts. When I add a Custom Attribute, the field could be a dropdown selector, rather than a free text, which recommends attribute names that were previously used. See image below for an example where my browser suggests Attribute names, based on the browser's Autofill. 

A follow-up ticket to this will be building a selector field into the Add/Edit Concept form when adding a Custom Attribute, using a similar "Suggestion" approach based on what Custom Attributes were previously used.

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/47b38d30-1684-4402-a5fd-78f2f430a1d1)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere

**Comment by snyaggarwal** [comment]
@jamlung-ri Close this if you are good with everything.

**Comment by jamlung-ri** [comment]
Closing for now since I see the feature in Production. Will reopen if needed

**Comment by paynejd** [comment]
Was this added to OCL Docs? Perhaps a new page for summary APIs?
