### ISSUE TITLE
Upgrade Google Analytics

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1600]
Our current Google Analytics approach is being retired next week! We need to update and roll this out ASAP. 

@snyaggarwal I'm assuming this is something that you will take on?

**Comment by snyaggarwal** [comment]
@paynejd Updated all env to use GA4.
We can clean up GA (don't think I have the delete access). There are some duplicate GA4 properties there (a couple of them were created by me to test).
- Universal properties (old ones) we should keep viewing old data unless GA decides to remove them. This data cannot be migrated to new GA4 properties. (They start with `UA-`)
- Can delete these: 
    - OCL QA v2 - GA4
    - OCL QA2 - GA4
    - OCL Staging2 - GA4

**Comment by paynejd** [comment]
@snyaggarwal added this to our next OCL Dev call to discuss and close this out
