### ISSUE TITLE
Retire WHO staging environment

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1601]
We no longer need this instance. Please go ahead and shut it down

**Comment by rkorytkowski** [comment]
Done! I kept the setup for now in case we would like to quickly recreate the environment. I kept DB snapshot and ES volume, which should cost less than a buck/m.

The setup and storage can be deleted any time.

**Comment by rkorytkowski** [comment]
@snyaggarwal FYI no more deployments to WHO stg.
