### ISSUE TITLE
Display Name of codes in ValueSets should auto-populate

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1609]
An OCL collection being represented as a FHIR ValueSet should have the codes' "display" attribute auto-populated. Currently, it shows null in this ValueSet: https://fhir.staging.openconceptlab.org/orgs/MER_SMART_Guidelines/ValueSet/art-medications/

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/0b247cb2-6757-4ee5-b073-09185348eed6)

**Comment by paynejd** [comment]
We need to have a conversation on this one -- adding for a future dev call

**Comment by jamlung-ri** [comment]
@rkorytkowski or @snyaggarwal It looks like this might be resolved? I'm seeing some great results in the latest content test load for Kenya (see links below) where the display name in the Compose statement is populating as needed. 
* https://fhir.staging.openconceptlab.org/orgs/Kenya_SMART_Guidelines/ValueSet/?url=https://path-global-health.github.io/MERindicators/ValueSet/DAKARTStop
* https://fhir.staging.openconceptlab.org/orgs/Kenya_SMART_Guidelines/ValueSet/?url=https://path-global-health.github.io/MERindicators/ValueSet/DAKONART
