### ISSUE TITLE
Estimate effort for OCL for OpenMRS launch

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#161]
Get clarity on what needs to happen before production deployment

- [ ] Lincoln is following up on some ticket - get confirmation from @paynejd  on where these tickets are
- [ ] Followup with Lincoln K
- [ ] Followup with Cintia
- [ ] Decide if we want a Milestone or a tag
- [ ] create a milestone or a tag in our issues repository
- [ ] create the needed issues and tag them in the milestone/tag created above 
 - [ ] send the above created task list to OpenMRS Talk to invite help and get everyone on the same page

**Comment by paynejd** [comment]
@karuhanga -- could you outline in this ticket remaining steps before we deploy "OCL for OpenMRS" to the OCL staging environment? Could you also describe any tests that we would want to perform in the staging environment before we push to production? Thanks!

**Comment by paynejd** [comment]
Also, see #74 for description of the production deployment process/requirements. I believe that much of what is described there has already been completed.

**Comment by Karuhanga** [comment]
@paynejd we should be good to. I'd like to share this on talk, but there seems to be a problem(https://github.com/OpenConceptLab/ocl_issues/issues/148#issuecomment-538775168) with retrieving mappings and concepts from released source versions that @rkorytkowski is still looking into.

**Comment by aprilcurrier** [comment]
@maurya  is this still relevant?

**Comment by aprilcurrier** [comment]
@bmamlin  Here is an older ticket related to OCL for OpenMRS rolling it over to you. The previous owner was @maurya  if you have any questions

**Comment by paynejd** [comment]
This is being tracked by the OpenMRS squad in Jira, so closing this out here
