### ISSUE TITLE
Lock down RDS maintenance window to once a week.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1611]

**Comment by rkorytkowski** [comment]
Set qa and demo to upgrade on:
Sat 2:00-2:30 UTC

Staging on:
Sat 3:00-3:30 UTC
Production on:
Sun 3:00-3:30 UTC

Staging and production are on different days to allow some time to abort maintenance on production (e.g. upgrade) if anything goes wrong on staging.
