### ISSUE TITLE
TermBrowser dashboard

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1612]
Version 3 includes a Dashboard for the TermBrowser. 

The Dashboard acts as the home screen for Users, it will have two modes:

- User is signed in
- User is not signed in

If a User is logged in, we can adapt the content they see based on behaviour. For example:

- Recently viewed repo's
- Recently edit repo's / concepts
- Recently updated repo's

We need to define what we feel is most useful to our users and write requirements to complete the designs.

**Comment by paulsonder** [comment]
![Dashboard.png](https://images.zenhubusercontent.com/62f2740361fc271207ca9fb3/0f3d630b-ba11-4ab2-a304-e34f73186a30)

**Comment by paulsonder** [comment]
@snyaggarwal Would you be able to document any technical questions for the `Dashboard` so we're able to prepare requirements? Thanks!

**Comment by jamlung-ri** [comment]
Ideally, we have some skeletons that can begin to be developed this sprint. Meanwhile, Paul, Jon, and I can continue putting together requirements to fill in components like the Feeds.

**Comment by paulsonder** [comment]
Hi @snyaggarwal 

You can find the designs for the TB Dashboard [here](https://zpl.io/p1DqwQQ).

There are two versions:

- User signed in
- User signed out / not signed in

Please let me know if you have questions about any of the components.

**Comment by jamlung-ri** [comment]
The Dashboard is feeling good on V3 QA! Obviously it's relatively basic for now, and I think we can benefit from an example feed being added (see #1708).

@snyaggarwal Another potential thing to try might be filling in the [News Feed](![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/00f35e1d-07dc-43b3-8957-684b81b02dcf)) (not sure if that's the right term). I'm not sure what the management strategy for that is but if it's something I could update with example content, it might be worth a try.

**Comment by paulsonder** [comment]
Looking great @snyaggarwal  - A few designs comments... 

- [ ] The search field has a border, but not in design
- [ ] Please add placeholder text to the search field
- [ ] Could we set a max-width on the context area (e.g. The Welcome text downwards...) - maybe 1024px?
- [ ] The icons in the design use color: 'on-secondray-fixed-variant' - they're a little lighter on the test env...

**Comment by snyaggarwal** [comment]
@paulsonder all of them are done, except the third point. I dint get it. Can you please explain a bit more

> Could we set a max-width on the context area (e.g. The Welcome text downwards...) - maybe 1024px?

**Comment by paulsonder** [comment]
I'm referring to this content area...

<img width="506" alt="Screenshot 2023-12-19 at 13 34 05" src="https://github.com/OpenConceptLab/ocl_issues/assets/95474174/528a282e-dc4c-499d-ae1e-7cd394f1d4b4">
