### ISSUE TITLE
Improve Monthly Usage Report

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1633]
Monthly usage reports are now automated, and with a few tweaks, they could start to be really useful. Below is a compilation of ideas from me and @jamlung-ri that hopefully can be completed with a low level of effort. If anything here is large, let's please discuss before spending a lot of time on it.

General feedback:
- Let's focus on getting the right data points, possibly even in CSV format -- let's worry about how to visualize it later
- Each data point would benefit from:
  - clear label and, whenever applicable, a date/date range
  - A definition (how was it calculated/queried?) so that it is unambiguous -- possibly list all of the definitions at the bottom of the report

Getting this table right seems like the top priority:
<img width="300" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/c4680583-7155-44ef-934c-7ada35d7b63d">

Specific feedback on the table:
- Add a "total" column -- total count of that resource type in OCL
- Define all columns, esp "active" and "inactive", for each set of resource types -- it looks like there are 4 different sets of definitions being used:
  - Users
  - Orgs + repos + repo versions
  - Collection references
  - Concepts + Mappings
- Can we clarify whether Concepts/Mappings is referring to Concept/Mapping Versions?
- For orgs/repos/repo versions, it appears that "Active" equals "Created", and that "Inactive" is undefined
- Add Expansions to the table

Other recommendations:
- **New Users:** Add a table listing all new users during the period, including username, name, company, location
- **New Orgs:** Add a table listing all new orgs during the period, including id, name, user who created it (and any other relevant columns)
- **New Sources/Collections:** Add a table listing all new sources/collections during the period, including id, name, org, user who created it, validation schema (and any other relevant details) -- eventually this might get too large and we'll instead summarize it
- **New Mappings Grouped by Target Source:** Add a table listing counts of new mappings during the reporting period grouped by target source (e.g. ICD-10, CIEL) sorted by counts descending -- restrict this to top _X_ results (e.g. 20 or 50 etc)
- **New References Grouped by Type:** Add a table of counts of new collection references grouped by type (e.g. static, dynamic, etc.) -- what values are possible here?

cc @jamlung-ri

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA and a report is triggered/mailed for July 1st to Aug 1st 2023. Please do add feedback here.

**Comment by paynejd** [comment]
Updated monthly report looks really good -- here's a sample report with the first round of feedback: https://docs.google.com/spreadsheets/d/11kg50-QpBo7cJh9NNrGhXQ77Oa0GAr_eB3cuNoU0GOM/edit#gid=1321491512

Next steps:
- discuss this on an upcoming dev call
- begin to draft definitions for queries, especially for active/retired resource counts

**Comment by snyaggarwal** [comment]
> I have one final change request and then I think we consider this ticket done:
> 
> * In the "Summary by Resource Type" table, move the "(excluding HEAD)" from the labels "Source Versions (excluding HEAD)" and "Collection Versions (excluding HEAD)" into the Notes column (i.e. simply "Excludes HEAD versions" is fine)

@paynejd this is done and you must have received a report on QA with this change.
