### ISSUE TITLE
Upgrade ElasticSearch to 7.17.10

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1634]
Upgrade ElasticSearch to 7.17.10 to utilize new features. This is urgent and required, as the local env is using ES 7.17.10 and the development on master has already used new features.
 
   - [x] Local/Dev setup to ES 7.17.10
   - [x] QA env to ES 7.17.10
   - [x] Staging env to ES 7.17.10
   - [x] Demo env to ES 7.17.10
   - [x] Production env to ES 7.17.10

**Comment by rkorytkowski** [comment]
Done!
