### ISSUE TITLE
Replace "UpdatedOn" with latest repo "Version" (and don't search HEAD) in concepts & mappings search

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1635]
We would like to have a switch that allows selected users to experiment with a modified approach to search:
- Only search the latest released version of each repository, and never search HEAD
- Replace the UpdatedOn column with the label of the repo version (e.g. `v2023-02-12` or `v1.2.0`) - We only want this behavior to be available for selected users (i.e. a new group or admins...)
- Ideally, we want a user to be able to easily enable/disable this behavior so that they can compare search results

**Comment by paynejd** [comment]
A few of the changes discussed...
- [ ] In global search, merge the "Version" column into the "Source" column, e.g. `CIEL v2023-02-12`, and apply a different formatting to the version (slightly smaller font and light-gray?) --- ultimately, we should have a consistent style for displaying repo versions
- [ ] In repo view, searching `HEAD` must be explicit
- [ ] In repo view, when browsing to a version-less repo URL, automatically redirect user to the latest released version -- we may change this behavior for a user with edit permissions, but this is a good default for now

**Comment by paynejd** [comment]
One more in addition to the items above:
- [ ] Move this change into its own "latest release" branch -- we'll be working on this branch for awhile before we merge into master
- [ ] Deploy this branch to the `dev` environment

**Comment by snyaggarwal** [comment]
@paynejd Tasks listed above are done and deployed on Dev environment. Please do give it a try

**Comment by paynejd** [comment]
This is now implemented in the dev environment (see screenshot below) -- closing this out

FYI @paulsonder -- v3 should follow this approach of displaying the repo version in search results (rather than the "updated on" timestamp)

<img width="1473" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/d3c7cb53-80d5-4f18-a97e-8fefcb7879ca">
