### ISSUE TITLE
Indexing Issue? NMRS

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1636]
The [Nigeria MRS (NMRS) source](https://app.openconceptlab.org/#/orgs/NMRS/sources/NMRS/concepts/) is going through mapping, but the concepts in their source are not being returned in search. See example where I search for "OTZ" and their multiple OTZ concepts are not returned.

Concepts without search (note that several "OTZ" concepts are visible):
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/94afc416-de97-4d17-b8b9-9ab47321e542)

Concepts when searching "OTZ":
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/d0e99cc0-4c06-4562-9f92-fe35d2dbad92)

**Comment by snyaggarwal** [comment]
Looked like indexing issue. I have re-indexed the sources concepts and mappings. Searched for "otz" and got results.

**Comment by jamlung-ri** [comment]
Looks good, thanks for the quick response Sunny! I'll reopen this ticket if any other issues arise.
