### ISSUE TITLE
Create calls for support for OpenMRS OCL

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#164]
- [ ]  @paynejd , what the purpose and structure of each is?
- [ ]  @paynejd what kind of support will Jennifer Antilla provide on this? Writing, Review or something else? 
- [ ] 1-page call for support to wrap up MVP
- [ ] 1-page call for support to provide continuing maintain MVP OpenMRS
- [ ] 1-page call for support to support MVP+

**Comment by paynejd** [comment]
Some of my notes on this:
    - 3 proposals:
        - Call on support for the launch of current MVP
        - Call for MVP+ team, including automating CIEL updates
        - Call for early adopters
    - OCL for OMRS MVP+ concept: https://docs.google.com/document/d/1C5W6d4z3rmn8fWiqaeULh3UQJe8vew6Ke41VjhRkCFI/edit#
    - https://wiki.openmrs.org/display/projects/Overview+Open+Concept+Lab+%28OCL%29+for+OpenMRS
    - https://wiki.openmrs.org/display/projects/Open+Concept+Lab+%28OCL%29+Client+for+OpenMRS
