### ISSUE TITLE
Add "Canonical URL" column for global & owner listings of Sources & Collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1644]
These can be really long -- suggest truncating with ellipsis and showing the full URL in a tooltip on mouseover

**Comment by paynejd** [comment]
Please implement this for OCLv2

@paulsonder Tagging you to also include this in OCLv3

**Comment by snyaggarwal** [comment]
@paynejd this is done.

**Comment by snyaggarwal** [comment]
@paynejd This is deployed everywhere, close this if things look good.

**Comment by paynejd** [comment]
Awesome. Should we actually combine the canonical into the `id` column, something like this?
<img width="1258" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/c969c3ba-fd71-4127-85b0-9ae31cc3630a">

Also, is it possible for the truncation to be dynamic based on the width of the column?

**Comment by paulsonder** [comment]
Hey @paynejd - what's the purpose of having this in the table / list view?

**Comment by jamlung-ri** [comment]
> Hey @paynejd - what's the purpose of having this in the table / list view?

Canonical URLs are an alternative identifier for terminology content, except it should hopefully be more powerful because it should be globally unique. The Canonical URL can be crucial for accessing content in a FHIR format too.

**Comment by paulsonder** [comment]
@jamlung-ri  The question is more why does it need to be in the list view, as opposed to in the header of the Source / Collection page, for example...

**Comment by jamlung-ri** [comment]
Oh sorry, I forgot to provide the context from this ticket: https://github.com/OpenConceptLab/ocl_issues/issues/1645

Basically, we will have HL7 FHIR users (and others) who want to find sources or collections by searching the canonical URL (or maybe just searching a substring of it?). I believe this Canonical URL column would serve the purpose of conveying how that source/collection appeared in the search results, but @paynejd please feel free to correct me or to add more color if needed.

**Comment by paynejd** [comment]
The canonical URL, when it's available, is actually the primary identifier
for a repository -- sometimes even more so than the identifiers that we use
now -- it's just new for OCL to treat it that way. I would guess that
anytime we show a repo ID we pair it with its canonical, if it's available
and the owner/namespace. The canonical+owner answers the question: "How do
I know that I'm looking at the right LOINC when there are many versions and
fragments of LOINC published across OCL?" This design paradigm will need to
work itself into the tables listing search results, but also into forms and
workflows across the TermBrowser. We want canonicals to be fully baked into
OCLv3.

**Comment by snyaggarwal** [comment]
> Awesome. Should we actually combine the canonical into the `id` column, something like this? <img alt="image" width="1258" src="https://user-images.githubusercontent.com/1189689/259396171-c969c3ba-fd71-4127-85b0-9ae31cc3630a.png">
> 
> Also, is it possible for the truncation to be dynamic based on the width of the column?

Thats a good idea to add canonical to ID. Should I just add it now?
I thought the truncation is dynamic upto the width of column, I will check

**Comment by paulsonder** [comment]
Could we try the URL at the next font size down in the type hierarchy?

**Comment by snyaggarwal** [comment]
> Could we try the URL at the next font size down in the type hierarchy?

@paulsonder Sorry I dint understand this.

**Comment by paulsonder** [comment]
@snyaggarwal 

Currently the font size of the URL is the same as the code above.

Given the importance of the info in the URL string, I wonder if by making the URL slightly smaller (by using the next size down in the type hierarchy), that we might present a more useful view of that information without needing to hover, which, at present, would probably be required for a lot of the URLs?

**Comment by snyaggarwal** [comment]
@paulsonder Got it. Adding it.

**Comment by snyaggarwal** [comment]
@paynejd this was done on all environments, please close this if everything looks good.

**Comment by paynejd** [comment]
Looks great!
