### ISSUE TITLE
Unable to find collection by canonical URL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1645]
A search for "http://terminology.hl7.org/ValueSet/diagnosis-role" has zero collection results, but it should match two collections which show up here: 

https://app.staging.openconceptlab.org/#/search/?q=diagnosis+role&isTable=true&isList=false&page=1&type=collections

**Comment by snyaggarwal** [comment]
This is fixed.

**Comment by snyaggarwal** [comment]
@paynejd This is deployed everywhere, close this if things look good.
