### ISSUE TITLE
Add References Bug 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1646]
I've been getting an "Invalid Filter Schema" error when trying to "Add References" and "Add Concepts/Mappings Expression". 

This is happening on Staging for this collection, among others: https://app.staging.openconceptlab.org/#/orgs/Kenya_SMART_Guidelines/collections/art_drugs_proofofconcept/

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/f6b975c7-1f9d-4ad6-b1d9-71876243b26a)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed

**Comment by snyaggarwal** [comment]
@jamlung-ri  This is deployed everywhere, close this if things look good.

**Comment by jamlung-ri** [comment]
This is working well now!
