### ISSUE TITLE
Sort Suggested Map Types by count, not by name

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1648]
Our Suggested Map Types dropdown in the Quick Add Mapping feature is currently sorting alphabetically, rather than sorting by frequency of use (i.e. what is displayed in the Summary tab). Instead, we should change the ordering of Suggested Map Types to be ordered by frequency instead of alphabetically. This is what the Summary tab does

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/5eff3fc4-77fd-4b8e-b4ab-45814b71884c)
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/6d86713b-52c0-403a-b735-767631a98a4e)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done and deployed everywhere.

**Comment by jamlung-ri** [comment]
Looking good!
