### ISSUE TITLE
Change OCL SSO/KeyCloak favicon

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1651]
Please change the favicon for OCL SSO/KeyCloak to match the favicon used for the TermBrowser.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVFVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59ddfd4c375bb145bd28aff8c9b6241c3b1b7cce/image.png)

**Comment by snyaggarwal** [comment]
This is duplicate of #1774
