### ISSUE TITLE
Urgent - Collection creation bug gets a 500 error

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1652]
There's a 500 error happening in both Staging and Production for new collections that are created. I can access existing collections but when I create a new one, I get a 500 error when accessing it. Some collections that I currently cannot access:
https://app.openconceptlab.org/#/users/jamlung/collections/testr/
https://app.staging.openconceptlab.org/#/users/jamlung/collections/testr/
https://app.openconceptlab.org/#/orgs/cidgoh/collections/test/

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/1e0c417d-36f7-4188-8982-2e7f02ec92b4)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed. 
@rkorytkowski this was failing due to celery once config. I have added [this fix](https://github.com/OpenConceptLab/oclapi2/commit/a46363973248b4138ccea66a2ee737e74b55026b)
