### ISSUE TITLE
Filter Pane showing irrelevant filters

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1656]
OCL is displaying incorrect facets/filters on Production. In the linked source below, there are lots of facets being displayed that are not part of the source. If you try to filter by them, OCL returns no results (as expected). It appears as if the facets from Global Search are populating here, perhaps.

Link: https://app.openconceptlab.org/#/orgs/MSF/sources/MSF/
See Summary tab for what Concept Classes actually should appear for this source.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU5UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74223dd3b14a15eb9f0f1dcd57d8383c61a94af5/image.png)

When you filter by a facet that does not exist in the source: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVZUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6355bafa09623ab2ab19f6a25f8d2111c6d0cdf3/image.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this should be fixed now everywhere.

**Comment by jamlung-ri** [comment]
Looks like things are good on Production!
