### ISSUE TITLE
Features for Auditing Content in a Source

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1659]
As a way of helping users monitor and review changes to content in their Sources, there are some quick changes that would help a user to identify content changes done by one or more users.

This should apply to the Concepts and Mappings tabs of a Source. As discussed in the [OCL Dev call](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.17wnukant3wr), this is intended for users who have editing access to the Source, but not for those only with viewing access. This likely will not apply to Collections unless we can find a straightforward and intuitive approach, so I am expecting Collections to be out of scope for this.

Changes:

- [x] New filter: `Updated By`
    - [x] Should leverage this Zeplin design for “Select panel” with Team Members: https://zpl.io/L4pQWBd - Edit: not using this right now
    - [x] Ideally, this should be a multi-select field if the API will allow it
    - [x] This can be populated using the Org's Members for now, unless the "Contributors" summary API is made, in which case that would be the ideal way to populate the filter options.
- [x] When comparing concept versions, the Compare window will only show mappings on the latest version of the concept, even if the previous version also had those mappings (see screenshot 1). This is resulting in an inaccurate comparison.
- [x] The "Updated on" date in the concepts list seems to be resolving to the "Created On" date for the concept, not the "Updated on" date (see screenshot 2)
- [x] (Optional) Display the "Updated By" username in the concepts list alongside the "Updated On" date if simple/convenient.
- [x] (Optional) Create a "Contributors" summary API that displays which users contribute to the source, with the most common contributors at the top

Screenshot 1: ([Link to concept comparison window](https://app.openconceptlab.org/#/concepts/compare?lhs=/users/jamlung/sources/Example-DAK-Source/concepts/2/3377097/&rhs=/users/jamlung/sources/Example-DAK-Source/concepts/2/3348812/))
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/afdbd224-410b-48d0-90a4-dde6a92c1c4d)

Screenshot 2: ([Link to concept](https://app.openconceptlab.org/#/users/jamlung/sources/Example-DAK-Source/concepts/2/))
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/989ef77f-118e-4ce6-b521-d25eef1f0141)

**Comment by jamlung-ri** [comment]
Things on QA are looking good so far! There are a couple of fixes and notes from our OCL Dev call today:

- [ ] When deploying: Old data needs to be migrated to fix the “updated by” bug. Will need a weekend to reindex Prod when we’re ready

- [ ] Bug: Mappings not appearing correctly in comparison window e.g. [link](https://app.openconceptlab.org/#/concepts/compare?lhs=/users/jamlung/sources/Example-DAK-Source/concepts/2/3377097/&rhs=/users/jamlung/sources/Example-DAK-Source/concepts/2/3348812/) (Note this is the same issue as the first comment in this ticket)

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! We're getting closer. We discovered a couple more quick bugs and proposed changes with the OpenMRS/OCL Squad:

- [ ] The Compare page uses green and red highlighting, which is confusing to users (they think it's like GitHubs add/delete code formatting). Can we do all highlighting in the Compare window in one color e.g. a light yellow?
- [ ] The UpdatedBy bug in the Concepts filter panel is fixed, but it appears to still be happening in the Mappings filter panel. (see screenshot, where many mappings were updated but the Filter panel shows only 1 updated)
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/1fea3a96-464e-4515-ad50-b57fb6a6f279)

**Comment by snyaggarwal** [comment]
@jamlung-ri I have re-indexed hiv-dak-test mappings but not all. I will queue re-index of all mappings on QA tomorrow morning first thing.

**Comment by jamlung-ri** [comment]
Great, please let me know when the indexing appears to be done. The Compare screen is looking great, although I am still seeing the mapping index issues in [the Mappings tab of this source](https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/sources/hiv-dak-test/mappings/):
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/3358bf6d-be11-4dc0-95e8-f4876b9d03a7)

**Comment by snyaggarwal** [comment]
@jamlung-ri this was done, and I can see it's reflecting correctly. Do let me know if you find any issues.

**Comment by jamlung-ri** [comment]
Same results, unfortunately. Facets on [this tab](https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/sources/hiv-dak-test/mappings/) returns "1" when there's more than 15 "jamlung"s in the UpdatedBy column 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/186e1297-23ba-4090-a99b-c5a49785c04f)

**Comment by snyaggarwal** [comment]
@jamlung-ri Seems like a specific flow is broken, these mappings were all created yesterday and its updated_at is not set correctly. Can you tell me how these mappings were created?

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere
