### ISSUE TITLE
Add Company and Location to user registration form

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1663]
Start by determining LOE

**Comment by snyaggarwal** [comment]
@paynejd This will require to have a custom theme for the registration form. I think we are planning to do that for v3 already. Its a medium level of change.

**Comment by paynejd** [comment]
Flagging this as `v3` for @paulsonder and @jamlung-ri to track -- this would be a "nice to have" (but not required) at launch

**Comment by snyaggarwal** [comment]
This is done on v3. Closing this.
