### ISSUE TITLE
Concept ID Bug

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1664]
When cloning a concept into my Source that uses the sequential auto-id, OCL gave the cloned concept an ID that already exists in my source.

Link to duplicative concept IDs (see the concepts with ID '1'): https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/sources/hiv-dak-test/concepts/?q=1&isTable=true&isList=false&page=1

This happened in a previous ticket (#[1647](https://github.com/OpenConceptLab/ocl_issues/issues/1647)), and we thought we had it resolved.

Recording link: (Start at 19:30 - https://iu.mediaspace.kaltura.com/media/t/1_1p6hh3c1)

**Comment by snyaggarwal** [comment]
@jamlung-ri This should have worked except in the case when the content was imported with ID in it. That will not set the sequence to next number and when you clone/create more concepts it will start with original sequence number (1 in this case). Do you have the import script?

**Comment by jamlung-ri** [comment]
Takeaways from today's [Dev call](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.5qkcfi5ug7rc):

- [ ] Sunny to test performance of approach #1: At the time of clone (or any concept creation), check verify the seq and update if needed
- [ ] If bad performance, consider approach #2: Update the seq at the end of bulk import to max “Id” - Likely will require a 'Processing' flag to signal the user to wait for import to finish before adding new content via TB.

**Comment by snyaggarwal** [comment]
@jamlung-ri I went with option 1 -- At the time of clone, we will verify the seq and reset it.
This is deployed on QA, please verify and let me know if it looks good.

**Comment by jamlung-ri** [comment]
No luck so far on QA :(

OCL is still creating concepts with duplicate IDs, both in the Clone and the Create Concept workflows. It may be worth noting that I am testing in the same [source](https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/sources/hiv-dak-test/concepts/) (which is using a combination of alphanumeric IDs) and I haven't made any changes apart from doing a browser refresh. 

Loom video to see the behavior if helpful: https://www.loom.com/share/5c14cb35b6ae46f3b00ce54cc2d51180

**Comment by snyaggarwal** [comment]
I didnt consider the source with both number and alphanumeric IDs. I have added the fix for this, can you give it a try one more time? 
Also, I have only done this in the clone process, and not in the normal create process yet.

**Comment by jamlung-ri** [comment]
Now it's working in that source! Seems that the fix for alphanumeric IDs worked with clone.

Would it be quick and straightforward to make this change in the Create Concept workflow too?

**Comment by snyaggarwal** [comment]
@jamlung-ri Added on concept/mapping create as well.

**Comment by jamlung-ri** [comment]
This worked well when testing on a newly created source. I was able to bulk import a concept, and then I would create a new concept via the UI, and OCL did a good job of not making duplicate IDs.

However, it's worth noting that this only seemed to be working when I created a [new source](https://app.qa.openconceptlab.org/#/users/jamlung/sources/testing-autoid/concepts/). When I tested in an [existing source](https://app.qa.openconceptlab.org/#/users/jamlung/sources/loinc2/concepts/), I still got the duplicate ID issue. @snyaggarwal Is this at all concerning to you?

**Comment by snyaggarwal** [comment]
@jamlung-ri I created a [new concept ](https://app.qa.openconceptlab.org/#/users/jamlung/sources/loinc2/concepts/47/) in your [existing source](https://app.qa.openconceptlab.org/#/users/jamlung/sources/loinc2/concepts/) and it worked as expected. Can you please check this once more.

**Comment by jamlung-ri** [comment]
Still happening in that existing source :( 

Loom video of what I'm doing, in case it helps: https://www.loom.com/share/7f6bf9a1aa824e229b78e59ee7cfda35

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere.

**Comment by snyaggarwal** [comment]
@jamlung-ri  Closing this, please reopen (or create new) if anything is pending
