### ISSUE TITLE
Failing DELETE Reference Endpoint on Swagger?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1667]
I have been trying to delete all the references from one collection so I could start fresh without needing to delete the whole collection and lose version history. I would think the `DELETE /users/{user}/collections/{collection}/references/` endpoint would do that, but I keep getting a "Bad Request" response.

Two things:
1. Is this the intended behavior of this endpoint?
2. If not, what is the right way to delete all references? And if yes, can this bug be easily fixed? 

Screenshot:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBditrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f619fc017c0dac83b24a626f87e06c08fbe55e2e/image.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Swagger is inaccurate here, this API demands list of refrences to be deleted.
You can use Postman (or similar, until I fix swagger) with list of references in body like:
{
  "expressions": "*"
}

**Comment by jamlung-ri** [comment]
Gotcha, I was able to make this work in Postman. Thanks! Feel free to close this ticket out if you don't have any use for it.

**Comment by snyaggarwal** [comment]
I have updated swagger to allow body in request. Closing this
