### ISSUE TITLE
Fix duplicate Q-AND-A concept showing up in MapTypes source

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1672]
https://app.openconceptlab.org/#/orgs/OCL/sources/MapTypes/

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDN2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f6547ab85f7122d3919e04393e547b97b341d9e/image.png)

**Comment by jamlung-ri** [comment]
Note that this is also happening with the value "Date" in the Datatypes source: https://app.openconceptlab.org/#/orgs/OCL/sources/Datatypes/

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/32341c16-0e06-46c5-9e9d-82baa47d0985)

**Comment by snyaggarwal** [comment]
This is fixed. Closing this
