### ISSUE TITLE
400 Error on Summary API

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1675]
The following link is returning a 400 error, which also causes the [PIH Summary tab](https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/summary) to fail. This appears to be occurring in other Summary tabs too e.g. [for this source](https://app.staging.openconceptlab.org/#/users/ocladmin/sources/clone_example/summary).

https://api.staging.openconceptlab.org/orgs/PIH/sources/PIH/summary/?verbose=true

**Comment by snyaggarwal** [comment]
@jamlung-ri This is an index issue. When we added updated_by last weekend, some concepts were created while the indexing was happening. Those new concepts didn't have the right ES schema. I have fixed the issue, but unfortunately will have to reindex this again this coming weekend

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed.

**Comment by jamlung-ri** [comment]
This is working well now!
