### ISSUE TITLE
Add Map Type filter

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1677]
There doesn't appear to be a Map Type filter when searching mappings in global search or in repos. Could this be added in easily? Not sure if it's already covered by OCL's facets.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFF0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40513af40dfbbc70d1572b309fdbee90d6ca2b8d/image.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri this was an issue with indexing and now fixed.

**Comment by jamlung-ri** [comment]
This is working well on Production!
