### ISSUE TITLE
Collection Bug: Concept still appears in collection HEAD after removing reference

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1679]
Sometimes when you remove a concept from the HEAD version of a collection, the Autoexpand-HEAD still shows the concept, even though it shows that there is no reference. Maybe OCL got ahead of itself when re-expanding the that collection? When I create a version of the collection, it appears correctly, but for some reason I can't get the concept out of the `autoexpand-HEAD` expansion.

Collection link: https://app.openconceptlab.org/#/users/jamlung/collections/facility-test/

Watch this happen in this video, starting at 35:20 to 35:50 - https://iu.mediaspace.kaltura.com/media/t/1_qabp15gu (which occurred at ~10:35 EDT on Wednesday Oct 25, 2023)

**Comment by jamlung-ri** [comment]
This appears to now be working well. I wasn't able to replicate the issue on QA. I think we can push this forward

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere.
