### ISSUE TITLE
Allow an organization's owner to delete their org

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#168]
Currently only a superadmin is able to delete organizations. This made sense early on, but OCL now has lots of junk orgs that people created for testing that they can't delete. We want to support "hard" deletes of org by their owners.

**Comment by Karuhanga** [comment]
- Would this mean a hard/ soft delete?
- What happens to resources owned by the org?

**Comment by snyaggarwal** [comment]
implemented

**Comment by paynejd** [comment]
Implemented in oclapi2 -- we will not modify the behavior in oclapi1. Closing this out.

@snyaggarwal Can you clarify whether any member of an org may delete the org or if only the user that created the org (e.g. the "owner") can delete the org?

**Comment by snyaggarwal** [comment]
any member can delete the org.

**Comment by paynejd** [comment]
This is correct behavior for now until we have implemented an upgraded permissions framework, when we will definitely want to restrict access to "org admins"
