### ISSUE TITLE
Auto-assign sort order

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1682]
Currently, when adding new mappings to a concept, OCL does not assign a sort weight and instead displays a subtle icon that their concept doesn't have a sort weight (see screenshot at bottom). This is creating some headaches for users though, so a quick solution would help. 

Proposed solution: Auto-assign a sort weight for newly created mappings if they will be part of a sorted list

1. When creating a mapping, OCL will check that "from" concept for other mappings of the same type to see if any of them have a sort weight
2. If step 1 is true, OCL will auto-assign a sort weight when creating that new mapping. The new mapping will be sorted at the end of the list i.e. it will be given a higher sort weight.

Note that this is a follow-up from [this ticket/comment](https://github.com/OpenConceptLab/ocl_issues/issues/1668#issuecomment-1747366211)

Questions for the group:

- [ ] To what concept creation methods will this apply? Example: Auto-assign a sort weight when creating individual concepts via TermBrowser or API but NOT when bulk importing
- [ ] (fill in with other questions as needed)

Screenshot of the subtle "unsorted" icon:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa99d67e10e2118c4ac165ac7328db9a8aad9afe/image.png)

**Comment by bmamlin** [comment]
If the API could be tweaked to assign `sort_weight` to `MAX(sort_weight)+1` for any mappings of the same map type, this would always sort mappings to the end of a sort list of map types, assign null if map types are not sorted, and presumably work with the existing UI (i.e., just vastly reduce the chance of there ever being an unassigned sort weight in the UI), and also apply to bulk imports.

**Comment by snyaggarwal** [comment]
@bmamlin @jamlung-ri Adding it to our Arch call for discussion.

**Comment by paynejd** [comment]
@paynejd This approach looks good to me and we can discuss on the dev call tomorrow if needed

**Comment by jamlung-ri** [comment]
@snyaggarwal Are you comfortable moving this forward, since Jon is good with the approach?

**Comment by snyaggarwal** [comment]
Yes, and just to confirm this is only for OpenMRS schema?

**Comment by jamlung-ri** [comment]
I don't think so, I think it's for everyone regarding validation schema. @bmamlin can confirm tomorrow but I believe it should apply to everyone.

**Comment by snyaggarwal** [comment]
@jamlung-ri @bmamlin this is deployed on QA

**Comment by jamlung-ri** [comment]
This is working great on QA! I created mappings via Quick Add, the Add Mapping form, and Bulk Import, and they always got the correct sort weight. This happened in a non-OpenMRS Schema source and still worked when I switched it to use the OpenMRS Schema. This is ready for deployment.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on Prod
