### ISSUE TITLE
Implement canonical url filter param for repos, sources, collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1701]
Canonical URL can be searched currently via full text (the `q` param)

We want to expose it as a dedicated search param `canonicalUrl`, for the repos, sources, and collection endpoints

Also add this param to swagger

**Comment by snyaggarwal** [comment]
`canonicalUrl` added on source/collection/repo list API and in swagger

**Comment by snyaggarwal** [comment]
Yes

**Comment by paynejd** [comment]
Is this ticket ready to close out?

**Comment by snyaggarwal** [comment]
I think yes
