### ISSUE TITLE
Search results templates

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1703]

**Comment by paulsonder** [comment]
Templates including side filters, table and card layout and split view were added to [Zeplin](https://zpl.io/9qBJqwW).

**Comment by paulsonder** [comment]
Hi @snyaggarwal 

After some user testing, it makes sense for most Global Search results use cases that filters are always open. So for that template, the user doesn't open and close them.

When viewing lists of resources in other templates, e.g. Repositories, the filters are closed by default and user can open them with a button in the top right of the table header.

Selected filters are checked in the left hand list and the user can 'clear all' using the control in at the top of the filters list.

Could we indicate how many filters are applied in that button? e.g. 'Clear 3 filters X'?

**Comment by snyaggarwal** [comment]
@paulsonder Ok make sense.
Yes we can indicate number of filters within clear button

**Comment by snyaggarwal** [comment]
Tasks:

- [ ] Search template
- [ ] Loader
- [ ] Search Filters
- [ ] Concepts
- [ ] Repositories
- [ ] Orgs
- [ ] Users
