### ISSUE TITLE
Searchlight component

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1704]
**1. User Story**
As a: a TermBrowser User,
I want: to be able to search inside a Repository or the whole of OCL from one search bar
So that: I don't need to use two components for similar tasks and to simplify my UX

**2. Acceptance Criteria** 
Given: I am inside a Repository and wishing to search for a Concept
When: I click into the Search component in the header, once a term is entered I should be able to arrow down to my preferred Search preference, e.g. inside the Repository or the whole of OCL.
Then: Either highlight the appropriate results inside the Repo itself or go to the Global search results template.

UI design can be found [here](https://zpl.io/wyL09DN).

**Comment by paulsonder** [comment]
@jamlung-ri I'm proposing we start here with the Searchlight component. Let me know if you're happy to proceed to Dev.

**Comment by jamlung-ri** [comment]
That works for me. @snyaggarwal Is this design pretty clear for you?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Looks good to me

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder this is deployed

**Comment by paulsonder** [comment]
This is looking **great**. One comment... could the highlighted row 'Search OCL for...' only appear once you start typing?

@snyaggarwal

**Comment by snyaggarwal** [comment]
@paulsonder Did you mean this:
<img width="796" alt="Screenshot 2024-01-25 at 5 51 33 PM" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/346a5ff9-20ca-479b-b710-eff2e4f5761c">
<img width="912" alt="Screenshot 2024-01-25 at 5 51 45 PM" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/e7bce19c-688a-4899-a726-c31629405aeb">

**Comment by paulsonder** [comment]
Another comment... if user has entered a search and they re-focus the search component, if they click the 'X' to clear the search the loading screen appears... could we drop that?
