### ISSUE TITLE
Implement "latest released" behavior in TBv3

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1710]
From the beginning, TBv3 will implement the new “latest released” search behavior, which includes:
- Global search shows results from latest released repo version instead of HEAD version
- Results include “Repo version” instead of "last updated"
- When navigating to a repo (with no version info), typically show latest released version (instead of HEAD)
- HEAD may not even be accessible to the public (still TBD)

**Comment by snyaggarwal** [comment]
@paynejd Can we close this one out? Can create following tickets separately?
