### ISSUE TITLE
Design for repo+version and repo+version+expansion

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1715]
There will be many places in TBv3 where we display a repo ID along with its version (e.g. `CIEL / v2023-01-12`), or a collection ID + version + expansion. Increasingly, repo IDs are interchangeable for canonical URLs, and we should consider standard displays that include canonical as well (or maybe canonical instead of repo ID?). It will often be required to view Repo-type as part of this --  e.g. when showing a list of results, it needs to be clear if we’re looking at a Code System or a Value Set or a Concept Dictionary (this could be an icon, color-coding, etc.?). Regardless, we'd like to have a consistent display of repo+version(+expansion)(+canonical)(+repo-type) throughout the application.

Search results is one place where this already shows up:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/1189689/6ece70ae-8520-4bd4-b5e1-683c317c8856)

**Comment by jamlung-ri** [comment]
Much of this seems to have been addressed in #1776. Can we close this out and use that ticket for any further discussion on this?

**Comment by paulsonder** [comment]
Maybe best to include the requirement to ensure it's signed off the the Repo epic @jamlung-ri

**Comment by jamlung-ri** [comment]
Good thought, and I just added it into #1625. Closing this out now, and this discussion will continue as appropriate in the epic and the ticket.
