### ISSUE TITLE
OpenMRS Validation Bug? (Concept-focused)

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1720]
Grace is unable to add a concept to her collection due to an OpenMRS validation schema rule, but none of us can figure out why it's happening. We can't find a single conflicting name between a particular CIEL concept and the collection in which it's being added to. I was able to recreate the issue in my own collection, which I recorded down below. @snyaggarwal Can you help us work through this and fix the OpenMRS validation schema if needed?

Link to the OpenMRS collection where this issue happens: https://app.openconceptlab.org/#/orgs/openmrs/collections/CCD/
Link to my collection where I recreated it: https://app.openconceptlab.org/#/users/jamlung/collections/OpenMRS-Bug-Test-20Dec23/
Link to the CIEL Concept: https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/116031/

See it in action here:
https://www.loom.com/share/d00c335e1f49443486b5d4953d52c0b9

**Comment by snyaggarwal** [comment]
Hey @jamlung-ri I have added some logs in this to get log the concept its conflicting with. Can you give it a try and I will check the logs to understand this better.

**Comment by jamlung-ri** [comment]
I just tried it again on Prod, and it worked fine. Not sure what changed - maybe a reindex was needed? I am going to reach out to Grace and ask her to try this again. See [my collection](https://app.openconceptlab.org/#/users/jamlung/collections/OpenMRS-Bug-Test-20Dec23/?q=116031&isTable=true&isList=false&page=1) where the concept got added successfully.

**Comment by snyaggarwal** [comment]
Yes I was suspecting that.

**Comment by snyaggarwal** [comment]
@jamlung-ri Can we close this?

**Comment by jamlung-ri** [comment]
Let's give Grace until the end of the week to test this out, and I will close it on Monday if there are no updates or concerns.
