### ISSUE TITLE
Concepts and mappings not correctly leaving collection after deleting references - Indexing issue?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1721]
Working with Grace on a Zoom recording today, we noticed that concepts were coming in and out of the collection when we would refresh it. For example, when we would try to remove a concept or mapping, it would leave the collection momentarily, then it would be back, then it would disappear again, then it'd be back again. This would generally happen when querying the collection, but we didn't really notice anything like that when we didn't query. It makes me think the indexing was doing something while we were working.

Collection link: https://app.openconceptlab.org/#/orgs/openmrs/collections/BasicLabTests/ 

Strange collection behavior (and probably some fumbling around) is throughout this recording if you want to watch: https://iu.mediaspace.kaltura.com/media/t/1_t6ce0j3u
* Look at 20:23 to see concepts not being removed from the collection (which might have just been that indexing wasn't caught up?)
* Take a look at 25:25 minutes into the recording - Concept seems to be removed from the collection but then it comes in and out again

**Comment by snyaggarwal** [comment]
@jamlung-ri this was due to indexing failures since we introduced the latest search in concepts/mappings indexes. Its fixed now, please give it a try once more.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal. Reaching out to Grace to test this out.

**Comment by snyaggarwal** [comment]
@jamlung-ri Can we close this?

**Comment by jamlung-ri** [comment]
@snyaggarwal Grace should be testing this out by the end of this week, so maybe we can close it out on Monday if we haven't heard anything.
