### ISSUE TITLE
Community website link

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1724]
As a user, I want to move from the TermBrowser app to the Community website when using OCL Online so that I can access information there.

Given that I know want to access the Community website, when I open the Account menu and click the 'Community website' link, I will open a new browser tab to view http://www.openconceptlab.org.

A design with icon can be found [here](https://zpl.io/O0Jz9rY).

**Comment by snyaggarwal** [comment]
@paulsonder I added this and its on QA. Is there anything pending on this?

**Comment by paulsonder** [comment]
Looks good @snyaggarwal !
