### ISSUE TITLE
Bulk import error on staging

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#173]
PEPFAR multi-stage import scripts that were working correctly on staging and production as of yesterday are now no longer working on staging due to the error below. It appears to me that it is an issue with the background processing of bulk imports.

Staging appears to be indicating that an import process is complete (and therefore sending that zero records were processed) even though the import is still underway. Meaning, the client is expecting a response like this:
```
{
    "state": "PENDING",
    "task": "2344a457-cfdf-4985-ae0f-b2797d33a1a2"
}
```
...but instead the client is receiving this response (a blank report of import results):
```
REPORT OF IMPORT RESULTS:
 
```
However, if I wait for several minutes and request the results, then I receive the correct response, like this:
```
REPORT OF IMPORT RESULTS:
/orgs/PEPFAR/sources/DATIM-MOH-FY19/:
  update 200:
    {"type": "Concept", "uuid": "5dceaf372d93b100424c2e12", "id": "disag-null-disag", "external_id": null, "concept_class": "Disaggregate", "datatype": "None", "display_name": "Null Disaggregate", "display_locale": "en", "names": [{"uuid": "ce1b4fb306d3479591795950dcb78b82", "external_id": null, "name": "Null Disaggregate", "locale": "en", "locale_preferred": true, "name_type": "Fully Specified", "type": "ConceptName"}], "descriptions": null, "retired": false, "source": "DATIM-MOH-FY19", "source_url": "/orgs/PEPFAR/sources/DATIM-MOH-FY19/", "owner": "PEPFAR", "owner_type": "Organization", "owner_url": "/orgs/PEPFAR/", "version": "5dceaf372d93b100424c2e12", "created_on": "2019-11-15T08:59:19.352", "updated_on": "2019-11-15T08:59:19.587", "version_created_on": "2019-11-15T08:59:19.352", "version_created_by": "datim-admin", "extras": null, "mappings": null, "is_latest_version": true, "locale": null, "version_url": "/orgs/PEPFAR/sources/DATIM-MOH-FY19/concepts/disag-null-disag/5dceaf372d93b100424c2e12/", "url": "/orgs/PEPFAR/sources/DATIM-MOH-FY19/concepts/disag-null-disag/"}  {"retired": false, "datatype": "None", "concept_class": "Disaggregate", "names": [{"locale": "en", "locale_preferred": "True", "name": "Null Disaggregate", "name_type": "Fully Specified"}], "id": "disag-null-disag", "descriptions": []}
/orgs/DATIM-MOH-DEMO-SS-FY19/sources/DATIM-Alignment-Indicators/:
  new 201:
    {"type": "Concept", "uuid": "5dceaf282d93b100424c2de6", "id": "de-HTS_TST", "external_id": null, "concept_class": "Data Element", "datatype": "Numeric", "display_name": "Total number of people tested for HIV in the reporting period (first time testers and repeat testers)", "display_locale": "en", "names": [{"uuid": "a3b612d8b1b84a5580c6dfc0c11095a2", "external_id": null, "name": "Total number of people tested for HIV in the reporting period (first time testers and repeat testers)", "locale": "en", "locale_preferred": true, "name_type": "Fully Specified", "type": "ConceptName"}], "descriptions": null, "retired": false, "source": "DATIM-Alignment-Indicators", "source_url": "/orgs/DATIM-MOH-DEMO-SS-FY19/sources/DATIM-Alignment-Indicators/", "owner": "DATIM-MOH-DEMO-SS-FY19", "owner_type": "Organization", "owner_url": "/orgs/DATIM-MOH-DEMO-SS-FY19/", "version": "5dceaf282d93b100424c2de6", "created_on": "2019-11-15T08:59:04.059", "updated_on": "2019-11-15T08:59:04.413", "version_created_on": "2019-11-15T08:59:04.059", "version_created_by": "datim-admin", "extras": null, "mappings": null, "is_latest_version": true, "locale": null, "version_url": "/orgs/DATIM-MOH-DEMO-SS-FY19/sources/DATIM-Alignment-Indicators/concepts/de-HTS_TST/5dceaf282d93b100424c2de6/", "url": "/orgs/DATIM-MOH-DEMO-SS-FY19/sources/DATIM-Alignment-Indicators/concepts/de-HTS_TST/"}  {"retired": false, "datatype": "Numeric", "concept_class": "Data Element", "names": [{"locale": "en", "locale_preferred": "True", "name": "Total number of people tested for HIV in the reporting period (first time testers and repeat testers)", "name_type": "Fully Specified"}], "id": "de-HTS_TST", "descriptions": []}
```

**Comment by rkorytkowski** [comment]
I couldn't reproduce the issue on the OCL side, but possibly it's an issue on the client side.

One thing, which might affect the client is that we started to respond with the STARTED state in addition to the PENDING state. PENDING is for queued tasks, whereas STARTED is for already running tasks. It's an internal Celery config change, which makes it easier to manage long running tasks. We could still make our API respond with PENDING for both cases if needed, but in my opinion it would be better to update the client to handle the STARTED state.

If it's not the case then, would it be possible to provide some example POST, which results in such misbehavior?

**Comment by paynejd** [comment]
Could you add the behavior for STARTED vs PENDING to the wiki?
https://github.com/OpenConceptLab/oclapi/wiki/Bulk-Importing

I will incorporate the new behavior into the client code.

Has this new behavior been deployed to production yet?

**Comment by rkorytkowski** [comment]
I'll update the wiki. No, it hasn't been deployed to production yet. There's a performance regression on staging when doing searches (related to privileges), which needs to be addressed before we can push anything to production. I'll work on that this week.

**Comment by paynejd** [comment]
If you can describe in email how STARTED and PENDING are used, I can add to
wiki too. I'd like to update my python script today if possible, but not
clear how these work. Thank you!

**Comment by paynejd** [comment]
Also, do not promote to production until the PEPFAR import scripts have
been updated according to the new bulk import behavior

**Comment by paynejd** [comment]
Note that I implemented a fix in the ocldev package to properly handle both the STARTED and PENDING status messages. We are preparing to test this. Will close this ticket after testing completed and wiki updated.

**Comment by rkorytkowski** [comment]
I see you updated the wiki, thanks!

**Comment by paynejd** [comment]
This appears to be working correctly -- closing this out!
