### ISSUE TITLE
Repo Version Permissions (featuring LOINC)

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1731]
We recently discovered that our [LOINC source on Production](https://app.openconceptlab.org/#/orgs/Regenstrief/sources/LOINC/) has Private saved versions but a Public HEAD version. I couldn't figure this out until I went into the source version itself.

Some actions here:

- [x] Change the visibility of the two LOINC versions to Public in the DB. Links:
      - 2.71.21AA: https://api.openconceptlab.org/orgs/Regenstrief/sources/LOINC/2.71.21AA/
      - 2.70.21AA: https://api.openconceptlab.org/orgs/Regenstrief/sources/LOINC/2.70.21AA/
- [x] Expose public/private information on Repo Version API(s) so that we can see this information, particularly when it differs from the HEAD version.
- [ ] (Later) Expose that information on TermBrowser (likely v3)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA/Staging

**Comment by jamlung-ri** [comment]
This is working well! I can see the different permissions on the LOINC versions in Staging, and I can also access the Prod LOINC source versions.
