### ISSUE TITLE
Implement URL registry API resource

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1732]
## Attributes:
* `id` - internally generated seq ID
* `url` (required) - canonical URL
* `namespace` (optional) - e.g. `/orgs/:org/` or `/users/:username/`; URL cannot be resolved to a repo unless a namespace is provided
* `name` (optional) - name of the repo
* `extras` (optional) - key-value pairs intended to store additional index terms to make it easy for users to find

## URL Registry API Specification
* Get/search list of URL registry entries, with paging
  * Search behavior:
    * Full-text should have namespace, url, name, and extras values
    * Namespace,
    * Url
    * Extras same as for other resources?

```
GET /url-registry/
GET /:ownerType/:owner/url-registry/
[{ “id”: “...”,
  “namespace”: “...”,  # e.g. “/orgs/CIEL/”
  “url”: <url>,
  “name”: <str>,
  “extras”: <json>,
  “created_at”: <datetime>,
  “updated_at”: <datetime>,
  “created_by”: <user>,
  “updated_by”: <user>,
  “Is_active”: <bool>,
}, …]
```

* Get registry entry
```
GET /url-registry/:url/
GET /:ownerType/:owner/url-registry/:id/
{ “id”: “...”,
  “namespace”: “...”,  # e.g. “/orgs/CIEL/”
  “url”: “”,
  “name”: “”,
  “extras”: {}
}
```

* Create new registry entry
```
POST /url-registry/
POST /:ownerType/:owner/url-registry/
{ “namespace”: “...”,  # e.g. “/orgs/CIEL/”
  “url”: “”,
  “name”: “”,
  “extras”: {}
}
```

* Update registry entry
```
PUT/PATCH /url-registry/:id/
PUT/PATCH /:ownerType/:owner/url-registry/:id/
```

* Delete registry entry
```
DELETE /url-registry/:id/
DELETE /:ownerType/:owner/url-registry/:id/
```

* Operation: Lookup a repository by URL -- returns the repo or returns no result/not found
```
POST /url-registry/$lookup/?url=:url
POST /:ownerType/:owner/url-registry/$lookup/?url=:url
```

## Future Requirements
* System-specific Canonical URL Formats: OCL does not need to know anything about system-specific canonical URL formats for now – a canonical URL is either a match to something defined in OCL, or its not (e.g. see SNOMED-specific handling of canonicals with FHIR)
* Ability to batch load/etc. – out of scope for MVP

**Comment by paynejd** [comment]
@snyaggarwal @bmamlin Please review this ticket to give any final feedback before Sunny starts with development!

Note: There are many workflows connected to how the registries are maintained and used that still need to be designed, however we don't anticipate these workflows leading to changes in the model specified above.

**Comment by snyaggarwal** [comment]
@paynejd This is deployed on QA. Do let me know any feedback

**Comment by paynejd** [comment]
Drafted documentation here:
https://docs.openconceptlab.org/en/latest/oclapi/apireference/urlregistry.html

**Comment by paynejd** [comment]
@snyaggarwal Quick feedback:
* `/url-registry/` returns 2 records, while `/url-registry/?q=f` returns 3 records (it is returning an entry owned by "CIEL")
* "owner" is missing in the global entries -- I get why, but do you have suggestions for a value we can assign to the "owner" field, or a way to indicate this?
  * One idea: Add the "owner_url" field (to all entries), and for `global` entries, the value of "owner_url" is `/`, and then "owner" and "owner_type" are both `null`?

**Comment by snyaggarwal** [comment]
@paynejd I have QA deployed everything except $lookup. Thats WIP.

**Comment by paynejd** [comment]
Feedback on `$lookup` operation:
* $lookup should only look at a single registry -- e.g. either global `/url-registry/$lookup/` or at a specific owner's namespace `/orgs/:org/url-registry/$lookup/`
  * the business logic that puts everything together (that uses the owner and global $lookup operations) will either go into `$resolveReference` or a new operation
* Should use POST instead of GET
* The response codes are important here: 200 if a resource is found, assuming 404 if not, although a 303 redirect to the specific repo isn't a bad option either -- thoughts?

The logic that puts everything together is documented here: https://docs.openconceptlab.org/en/latest/oclapi/apireference/urlregistry.html

**Comment by snyaggarwal** [comment]
1. Abstract out URL/URN interpret logic from $resolveReference into a parser
2. Global/Owner entries namespace must be considered to resolve to a repo version.
3. Redirect to repo? RepoVersions may have different canonicals. TBD

**Comment by snyaggarwal** [comment]
Operation: $resolveCanonical
Input params:
Url
Namespace
“/” global – only looks at the global registry
“/:ownerType/:owner/” – standard process: owner registry, owner repos, global registry
Version (?)
Response
Repo summary / Repo version summary?

**Comment by paynejd** [comment]
@snyaggarwal After reviewing the `$resolveReference` docs, I think that we incorporate the `$resolveCanonical` business logic directly into that, rather than introduce a new operation. Can you review the updated `$resolveReference` documentation and see if I got the technical specs right? If this is good to go, feel free to move forward with development: https://github.com/OpenConceptLab/ocl-docs/blob/main/docs/source/oclapi/apireference/resolveReference.md

Also, can you run the same query on QA and staging to determine how deploying updated behavior for $resolveReference will impact expansions in those environments?

**Comment by paynejd** [comment]
@snyaggarwal Next step is to get all of the new behavior deployed on QA with a toggle to have breaking changes disabled on other environments

**Comment by paynejd** [comment]
To summarize where we're at:
- URL Registries implemented (both global and namespace-specific)
- $lookup operation implemented
- $resolveReference updated to use URL registries
- All code committed and deployed with a toggle so that it is only enabled in QA

Next step is to expose this in TBv3 so that we can start to play with it in QA

**Comment by paynejd** [comment]
Closing this out -- all additional work on URL registries will be in new tickets
