### ISSUE TITLE
Total time of processing for Exports

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1735]
As a way of benchmarking performance on version exports, let's expose the total time of processing for export versions. Leaving it up to @snyaggarwal for the best way to implement this (i.e. is this time shown on the downloaded export only, in the GET API call for the version, etc.).

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA.
export file will have `"export_time"` with time taken in seconds.

**Comment by jamlung-ri** [comment]
This is working well on QA! @snyaggarwal Can you move this to Staging and let me know when it's ready? That's where the big content is, and I want to make sure it works well on something bigger.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on Staging

**Comment by jamlung-ri** [comment]
This worked well on [WHO ATC on Staging](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/WHOATC/versions)! This should be good to deploy on Prod.
