### ISSUE TITLE
Canonical URL registries in the TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1742]
We want to compile initial requirements and designs for the following:
* View global canonical URL registry (available to all users)
* View owner-specific (e.g. user or org) canonical URL registry (same permissions as the user or org)
* Add/Edit/Delete canonical URL registry entry

**Comment by paynejd** [comment]
@jamlung-ri and I discussed that we might take on the UI for canonical registries in stages something like this:
- Stage 1 - all users can view the global registry, and staff users can manage it
- Stage 2 - users can manage the registries in their own namespaces
- Stage 3 - canonicals integrated throughout the app – e.g. always have clarity on where a canonical is pointing; default workflows implemented for updating the global registry

**Comment by paynejd** [comment]
Requirements, mockups, and examples are here:
https://docs.google.com/presentation/d/1j49g6zNfwMag4gmoxEGfI0HG-6tQ4zEZpgwHooiUK4w/edit#slide=id.g2be25b8701d_1_34

@paulsonder Handing this over to you to for review and to turn into real designs for TBv3

**Comment by paulsonder** [comment]
![Test](https://github.com/OpenConceptLab/ocl_issues/assets/95474174/1a92fffd-8d08-418f-a228-b08452cc508a)

@paynejd 

Here's a proposal for the 'Test a Canonical' UI. 

The example above shows a result, which includes where the Canonical resolved to in text form and by showing the **Summary UI** of the **Repository** object. 

Let me know what you think and I can prepare the various states depending on the result.

**Comment by paulsonder** [comment]
@paynejd For 'add/edit/delete a canonical' - this only refers to URLs in a registry in a namespace I can edit? e.g. my User or an Org I admin?

**Comment by paynejd** [comment]
@paulsonder That's correct on edit privileges. Requirements for editing the global registry still need to be defined.

Is there an icon you could use for the Global registry (e.g. like a world icon?) since won't all of the users and orgs in the owner dropdown have an icon?

In the Test window, it's hard not to interpret `Owner` as the owner of the canonical, when it's supposed to be defining the namespace for the context of the request. What do you think of making this small change:
- In the registry tool, change the "Owner" label to "Registry Owner"
- In the test panel, change the "Owner" label to "Context"

**Comment by paynejd** [comment]
- [ ] Draft some helper text to introduce the "Test a Canonical URL"

**Comment by paulsonder** [comment]
![Test](https://github.com/OpenConceptLab/ocl_issues/assets/95474174/323d7dff-e6f4-480a-8a0f-5bb4610e5be1)

@paynejd Here's an updated version of the testing tool UI.

**Comment by paulsonder** [comment]
Hi @jamlung-ri + @snyaggarwal 

The latest designs for Canonical URL registry are [here](https://zpl.io/NEZXkwd).

I experimented with the testing tool in the same page, but ultimately it was a little crowded.

**Comment by jamlung-ri** [comment]
This is feeling good to me! I'd definitely like to see this implemented in TermBrowser v3 if everyone else feels good with it.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri @paulsonder Is this ready to be picked up?

**Comment by paynejd** [comment]
@snyaggarwal This is ready to go!

**Comment by snyaggarwal** [comment]
First version of this is deployed on QA

**Comment by paynejd** [comment]
"Test a Canonical URL" should use `$resolveReference` rather than `$lookup`.

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA v3

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Any feedback on this or can we close this?
