### ISSUE TITLE
Switch mappings to use $resolveReference to resolve repo references

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1747]
All logic in the API that resolves references to repos was already switched to use $resolveReference...except for mappings. The reason is because mappings generally do not resolve to version-less repos, which requires a minor modification to be supported by `$resolveReference`.

@snyaggarwal Can you outline the approach that you are thinking?

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA. The process is as follows:
1. Take source_url - could be `from_source_url` or `to_source_url`  or can come from `from_concept_url`  or `to_concept_url`
2. Pass this URL to `$resolveReference` operation with `version='HEAD'`. `$resolveReference` when given a version tries to resolves to that specific version (not latest).
3. Rest of the process is same, save it to `from_source` or `to_source` on mapping.

**Comment by paynejd** [comment]
Demo on upcoming architecture call

**Comment by snyaggarwal** [comment]
100% of the logic to find a repo is with $resolveReference now.
Closing this one.
