### ISSUE TITLE
Generate diff between 2 repo versions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1753]
@snyaggarwal has already started to develop a `diff` API operation that hits the database directly to generate a diff between 2 repo versions. The operation uses both standard & smart checksums, resulting in a list of new and removed concepts, as well as a list of changed concepts grouped by smart and standard. We want to expand on this functionality by incorporating mappings, and also using it to validate our checksum behavior. Ultimately, we probably want to support 2 formats:
* a computable/JSON diff
* a text/narrative that could be optionally added to a repo version’s description

This feature will give content managers more confidence in publishing a new release, since they can more easily validate the full set of changes.

**Comment by snyaggarwal** [comment]
Current API Signatures:

POST /sources/compare/
{
    "version1": "/orgs/CIEL/sources/CIEL/v2023-12-15/",
    "version2": "/orgs/CIEL/sources/CIEL/v2023-10-27/"
}

**Comment by paynejd** [comment]
Diff layers
- Resource-level diff (for concepts and mappings independently)
- Domain-object diff (for a from-concept plus its mappings) - evaluated based on the results of the resource-level diff?

Next goal is to finish the resource-level diff in the /compare/ endpoint, and then we'll consider how to evaluate the domain-object diff (and whether or not we persist that)

Next steps:
- [ ] Add summary field to the compare output (totals of resources, …)
- [ ] Analyze the 9 “smart” (smart but not standard) diff resources that changed
- [ ] Add resource-level diff for mappings
- [ ] Run a diff on the latest CIEL import

**Comment by paynejd** [comment]
With the current output structure, will `same` / `standard.same`  and `changed` / `smart.changed` always be equal? I think this is the case. If yes, what do you think of this simpler output structure:
```
{
  new
  removed
  same       # standard
  changed    # standard
  smart-same
  smart-changed
}
```

cc @snyaggarwal

**Comment by paynejd** [comment]
The change log for a CIEL release simply lists the names/descriptions of new concepts. CIEL's `v2023-12-15` change log includes 76 new concepts, which as expected matches exactly the count that Sunny generated with OCL data. An excerpt from the CIEL change log:
<img width="1006" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/fe85df71-eac7-4235-992c-73cc918954c6">

The data in OCL's `/compare/` operation is already sufficient to generate the above change log, and could be used to also annotate "significant changes" (`smart-changed`) to concepts and "minor changes" (`standard-changed`).

### Option for creating a change log
- Concepts
  - **New Concepts**: list ID, display name + synonyms, description(s)
  - **Removed Concepts** (if there are any): list ID, display name
  - **Major Concept Updates** (`smart changed`): list ID, display name, update_comment, changes
  - **Minor Concept Updates** (`standard changed`): list ID, display name, update_comment, changes
  - **Retired concepts**: list ID, display name, update_comment, concept that replaced it (if relevant mapping created)
- Mappings
  - **New Mappings**: list ID, from-source+concept, to-source+concept
  - **Removed Mappings**: list ID, from-source+concept, to-source+concept
  - **Major Mapping Updates**: list ID, from-source+concept, to-source+concept, update_comment, changes
  - **Minor Mapping Updates**: list ID, from-source+concept, to-source+concept, update_comment, changes
  - **Retired Mappings**: list ID, from-source+concept, to-source+concept, update_comment

Resources:
* Andy’s talk post with the change log: https://talk.openmrs.org/t/new-version-of-ciel-concept-dictionary-added-to-dropbox/1749/170?u=paynejd
* Spreadsheet with Andy’s change log: https://docs.google.com/spreadsheets/d/1SHVUPBsrn4Py5VRhPdJ295zMgFbatCx6KeXhoEj1JTo/edit#gid=928744150

**Comment by paynejd** [comment]
FYI the change log comment was moved into its own ticket: #1814

**Comment by snyaggarwal** [comment]
> With the current output structure, will `same` / `standard.same` and `changed` / `smart.changed` always be equal? I think this is the case. If yes, what do you think of this simpler output structure:
> 
> ```
> {
>   new            # count in repo2 NOT IN repo1
>   removed        # count in repo1 NOT IN repo2
>   same           # count that are the SAME in repo1 and in repo2 (using standard checksum)
>   changed        # count that are DIFFERENT in repo1 and in repo2 (using standard checksum)
>   smart-same     # count that are the SAME in repo1 and in repo2 (using smart checksum)
>   smart-changed  # count that are DIFFERENT in repo1 and in repo2 (using smart checksum)
> }
> ```
> 
> cc @snyaggarwal

@paynejd this is done

**Comment by snyaggarwal** [comment]
@paynejd Can we close this one?
