### ISSUE TITLE
User Profile Round 1

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1756]

**Comment by jamlung-ri** [comment]
See designs for [Viewing a User](https://zpl.io/q1mvlLZ) and [Editing a User](https://zpl.io/XKLWoYl).

**Comment by snyaggarwal** [comment]
@jamlung-ri User Profile/Details and Repo List within User view is deployed on QA.
I started on Edit User Profile. But not sure where is the edit profile action button that leads to edit form.

**Comment by snyaggarwal** [comment]
Also @paulsonder @jamlung-ri if you notice the [profile design](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb5e016ed139e67cde990)
it doesnt have left collapsed menu where we just show icons. Is this something that we are thinking to do?

**Comment by jamlung-ri** [comment]
> @jamlung-ri User Profile/Details and Repo List within User view is deployed on QA. I started on Edit User Profile. But not sure where is the edit profile action button that leads to edit form.

@snyaggarwal I will defer to Paul on the final decision here but how about we copy GitHub's method, at least for the time being? They put an edit button below the name/username.
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/4eae66e5-c905-438f-96ed-60873173086e)

**Comment by jamlung-ri** [comment]
> Also @paulsonder @jamlung-ri if you notice the [profile design](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb5e016ed139e67cde990) it doesnt have left collapsed menu where we just show icons. Is this something that we are thinking to do?
I think we'll want to keep it consistent across pages on the TB, so I think your current QA implementation is good with the icons on the left side.

> 
> Another thing is, the Organizations sections shows logo, what if Org has not uploaded Logo. How do we represent it. I have used one bad way to show that on QA.
GitHub's method is to generate a random placeholder image, which is distinctive but doesn't really convey helpful information. The on-hover tooltip helps though. I personally prefer your current implementation on OCL, which shortens the name to 2 characters, and that can include the on-hover peek tooltip. Thoughts?

**Comment by snyaggarwal** [comment]
@jamlung-ri Ya that makes sense. I would want @paulsonder to pitch in as well. 
Till that will keep it as is.

**Comment by snyaggarwal** [comment]
@jamlung-ri whats the difference between [user profile](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb5e016ed139e67cde990) and [user repositories](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb39b5edc2467493a2c00)

**Comment by jamlung-ri** [comment]
> @jamlung-ri whats the difference between [user profile](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb5e016ed139e67cde990) and [user repositories](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65bbb39b5edc2467493a2c00)

"My Repositories" will show any repos owned by the user or the orgs from which they are a member. User Profile will only show repos that are owned by the user directly. I don't think the User Profile will feature Pinned Repos either.

**Comment by snyaggarwal** [comment]
@jamlung-ri I dont think we have an API to get just the list of orgs owned by user. We always show list of orgs user is member of. Is this a new API/behaviour we should add?
cc @paynejd

**Comment by jamlung-ri** [comment]
> @jamlung-ri I dont think we have an API to get just the list of orgs owned by user. We always show list of orgs user is member of. Is this a new API/behaviour we should add? cc @paynejd

I'm thinking that yes, this is a new API that we'll need. It should list out the user's repos and the repo's owned by orgs in which the user is a member.

> /user/orgs/repos/ is my repositories and /user/repos/ are part of my profile.

Specifically about `/user/orgs/repos/ is my repositories`, the "My Repositories page also should show repos owned by the user, along with the user's own repos. The repo owned by "Me" at the bottom of [this design](https://zpl.io/jpj5R4r) shows a good example.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is ready for testing

**Comment by jamlung-ri** [comment]
Things are looking good to me! The only thing I might suggest changing is to remove the Owner field, since all repos on this User Profile page should be owned by me.

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri For most of the new users this page will be empty. Just after signup they may land on an empty page, might not be a good experience. We may need to put some static things like how to use OCL etc?
What do you guys think?

**Comment by paulsonder** [comment]
> @paulsonder @jamlung-ri For most of the new users this page will be empty. Just after signup they may land on an empty page, might not be a good experience. We may need to put some static things like how to use OCL etc? What do you guys think?

When a user signs up, I think we should direct to them their dashboard and have links to onboarding and guides etc there. I'll create a mock up.

Agree on the empty page being of little value. I'm looking a the empty state now - how about a feed of recent activity? How feasible is that?

<img width="800" alt="Screenshot 2024-02-22 at 13 44 38" src="https://github.com/OpenConceptLab/ocl_issues/assets/95474174/18c36c89-089c-431e-a65f-0d3be375d1ac">

@snyaggarwal @jamlung-ri

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder This first round of User Profile development is pretty good. Seems like next steps are to develop the "empty state" (incl. the activity feed) and to figure out the User summary statistics to include. I can make those tickets real quick.

@snyaggarwal One last piece of feedback: Can the list of Organizations in the User profile be scrollable? Currently I have to Zoom out to see all my orgs (when using my small-ish laptop screen) since I am a member of 4.

Zoomed in:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/59e2a831-3aa6-477a-a3b5-3d953a01618f)

Zoomed out:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/04dccbac-c330-414b-a52f-2e3167dc983c)
