### ISSUE TITLE
Subscription module not able to subscribe to specific version of user dictionary

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#176]
When attempting to subscribe to this user dictionary (https://api.openconceptlab.org/users/jdick/collections/jj/1.0/), receiving an error message saying it is not found, which is blocking the subscription process before it begins. It appears that this may be a permissions issue, but not clear.

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/430ae23f-de20-443f-9287-fcc3d4db091d)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/63637ea6-3c05-45fd-91d4-99eea04676c1)

**Comment by Karuhanga** [comment]
@paynejd Please get rid of the dictionary version number. This issue was raised previously().

**Comment by paynejd** [comment]
Thanks @Karuhanga. Rafal caught this too. Suggest that we change the label, add a hint, and validation so that this isn't an issue people run into in the future.

**Comment by Karuhanga** [comment]
> Thanks @Karuhanga. Rafal caught this too. Suggest that we change the label, add a hint, and validation so that this isn't an issue people run into in the future.

@paynejd I think we can actually get rid of the version number for now. I wonder if this should stay open though so that we can track that this needs to be supported by the api.

**Comment by Karuhanga** [comment]
My bad. Just been informed this was fixed.
