### ISSUE TITLE
Minor monthly report improvements

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1760]
These additional stats will help us to track our progress toward adoption of the new repo types and canonical URLs. We hope to have these in place by the time we run our next monthly report (i.e. end of Feb).

NOTE: The screenshots below are from the last report here: https://docs.google.com/spreadsheets/d/1VXIfhhh2zaIg1G59-_IOIPVvsy2RgHKN2UkaBNYM49s/edit#gid=257034767

- [x] Fix incorrect internal/between mappings counts
- [x] Add section summarizing repo types:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0F5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8fff01fbde2849f7d43a7e1db1a3571fd212849/image.png" alt="image.png" />

- [x] Add sections summarizing canonical URL usage for Mappings:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0l5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8759a55f1ecad6d93d8a9ff5fdbe10d32e536c28/image.png" alt="image.png" />

- [x] Add sections summarizing canonical URL usage for References:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM015QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f36975d0667bc9beaf22fb5a81d31edeccd25fb6/image.png" alt="image.png" />

**Comment by paynejd** [comment]
@snyaggarwal Can we squeeze this ticket in before the next monthly report (i.e. end of March)? I think these are minor updates...

**Comment by paynejd** [comment]
@snyaggarwal This looks good! Just one minor update: Can you move the section "New References" section, which is at the bottom of the report to just under the new "Summary of References" section? It's helpful to review both of these together. Also, the sample report that you shared ended after the "Summary of References" section -- I'm assuming that this is because it was just a sample report on Q/A, but wanted to confirm! Could you go ahead and re-run the Feb-2024 report in production after you deploy this? Thank you!

<img width="656" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/3c582b08-bfce-4b87-9f84-8b9c02f2d159">

**Comment by snyaggarwal** [comment]
@paynejd I have updated the order. And yes when the stats are not there the report doesnt show the section, QA doesn't have much numbers thats why the report is short.

**Comment by paynejd** [comment]
Everything looks good! Closing out.

A quick note:
Prior to these updates, the monthly report was useful for just tracking the quantity of content in OCL and new records created over the last month. These new new sections start to show how users are modeling their content — repo types, canonical URLs, static/dynamic, mapping targets, etc.
