### ISSUE TITLE
Update link to Roadmap in the TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1762]
Please update the "Community Roadmap" link (in the left nav) to point to the new 2024 roadmap: https://openconceptlab.org/2024-ocl-community-roadmap/

<img width="258" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/d54a7d0f-622f-4429-a731-8317096855c6">

**Comment by paynejd** [comment]
Hey @snyaggarwal - possible to tackle this one?

**Comment by snyaggarwal** [comment]
@paynejd this is deployed everywhere.

**Comment by jamlung-ri** [comment]
Confirmed that this has made it to all envs!
