### ISSUE TITLE
Change KeyCloak favicon to the new OCL logo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1774]
The user sign up/sign in pages use what looks like a KeyCloak favicon. Can we update this to use the new OCL logo? It's fine if this applies to v2 as well.

<img width="280" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/8edb8252-0f41-42c7-8e3e-459ed8ac92ac">

**Comment by paulsonder** [comment]
@paynejd @snyaggarwal 

The favicon I supplied was the blue dot - the larger logo is not legible at such a small size and the 'dot' will be used prominently in other places too.

I notice this was changed on the v3 dev server - please could we revert back.

Thanks!

**Comment by snyaggarwal** [comment]
@paulsonder I wanted to make sure its same as chat.openconceptlab.org. 
@jamlung-ri May be we should change both to dot version?

**Comment by paulsonder** [comment]
@jamlung-ri I would like to use the Dot version for the Fav icon across all OCL properties.

**Comment by snyaggarwal** [comment]
Yes, reverted to the original one.

**Comment by snyaggarwal** [comment]
@rkorytkowski Can you please change chat.openconceptlab.org favicon to match QAv3?

**Comment by snyaggarwal** [comment]
@rkorytkowski I have updated v3 theme to have ocl favicon. Can you please deploy this?

**Comment by rkorytkowski** [comment]
Deployed via https://ci.openmrs.org/deploy/viewDeploymentResult.action?deploymentResultId=285343750

**Comment by snyaggarwal** [comment]
@paynejd This is deployed. Closing this.
