### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1775]
### **User story**

**As a:** user of the OCL TermBrowser
**I want:** to quickly navigate to content I own, have edit access to, have bookmarked or collaborate on
**So that:** my 'work bench' has a simple, common navigation pattern that's easily accessible but has clear visual delineation from other content on the page.

### **Acceptance Criteria** 

**When:** a User clicks on the menu icon button in the header
**Then:** the modal drawer will appear (this ticket will mean removing the navigation rail and that the list of links will not persist as now).

### Background

To meet the user story and to allow for more iteration in future without complicating the overall user experience, I would like to propose an update that would move the left navigation into a modal drawer (as per M3 guidelines).

This change will also mean that links to user specific pages (my repo's, proposals, my organizations, my bookmarks etc) do not confuse users who are only browsing others content (terminology consumers).

### Design

https://zpl.io/0PejBJm

**Comment by paulsonder** [comment]
@jamlung-ri 

Before I update designs could you take a quick look at this to make sure you're OK with the update? Thanks!

**Comment by jamlung-ri** [comment]
@paulsonder Looking at the repos under the Bookmarks icon, are these a sub-item of the Bookmarks? I'm a bit confused if the Bookmarks icon is acting as a sort of dropdown, which would reveal the repos underneath, or if Bookmarks is its own separate thing that will take you to a page/menu if you click on it. 

In short, are the repos in your design tied to the Bookmarks icon?

**Comment by paulsonder** [comment]
> @paulsonder Looking at the repos under the Bookmarks icon, are these a sub-item of the Bookmarks? I'm a bit confused if the Bookmarks icon is acting as a sort of dropdown, which would reveal the repos underneath, or if Bookmarks is its own separate thing that will take you to a page/menu if you click on it.
> 
> In short, are the repos in your design tied to the Bookmarks icon?

I made a visual change, let me know if the design is clearer now.

**Comment by paulsonder** [comment]
@jamlung-ri 

The result of this ticket means we can simplify the links in the [Account menu component](https://zpl.io/O0Jz9rY) too.

**Comment by jamlung-ri** [comment]
Much clearer! Only thing that we might want to account for is when someone is part of a whole bunch of orgs, such as the OCL Admin account (which is currently a member of 70 organizations). Just a simple overflow method will probably be fine.
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/c4e2d150-f49e-4ee7-b5e1-b4b3ecf46d1a)

**Comment by paulsonder** [comment]
> Much clearer! Only thing that we might want to account for is when someone is part of a whole bunch of orgs, such as the OCL Admin account (which is currently a member of 70 organizations). Just a simple overflow method will probably be fine. ![image](https://private-user-images.githubusercontent.com/55999682/307107650-c4e2d150-f49e-4ee7-b5e1-b4b3ecf46d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTk3MDYsIm5iZiI6MTcwOTcxOTQwNiwicGF0aCI6Ii81NTk5OTY4Mi8zMDcxMDc2NTAtYzRlMmQxNTAtZjQ5ZS00ZWU3LWI1ZTEtYjRiM2VjZjQ2ZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEwMDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGRlYTU2N2FiYzhkNGI2YjRmMjYyZDRmM2U2MWI2YTAzYjZjZDA4MGYwYTUxYzBkMThkOGFjNjhmNjYyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20GPm2Hlkmj-ti_jdT0MNIECCCU9XM3FLXhhDN7iBHg)

Agreed. Maybe after 5 orgs we can include a '**Show all**' link in the next '**Nav item**'?

**Comment by paulsonder** [comment]
@snyaggarwal It'd be great to get your view on this ticket...

**Comment by snyaggarwal** [comment]
1. No collapse version of left menu
2. Left Menu is a drawer
3. Move orgs/repo/bookmarks in left menu from profile
4. logged out user will not have this menu

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder this is deployed

**Comment by snyaggarwal** [comment]
@paulsonder Close this if everything looks ok

**Comment by paulsonder** [comment]
Looks good @snyaggarwal - I'm going to create another ticket for a 'Following' empty state but this is good to close.
