### ISSUE TITLE
Following Organizations, Users, or Repositories (related to Events/Feeds)

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1780]
### Background and context
OCL currently does not have a method of following or 'bookmarking' content that's relevant to a User. I would like to explore how we might approach this topic and define technical requirements so I'm able to finalise designs.  

### User Story
As a: user with an OCL account
I want: to 'bookmark' resources
So that: I have a list to aid efficient navigation to them and to utilise in search to create a narrower set of results.

### Acceptance criteria
- User can view the activity feed for a repo when viewing the details of the repo (e.g. on an overview/about page?) or when viewing the overview page of its owner (e.g. org/user)
- User can view the activity feed for a bookmarked repo on my global dashboard
- Ability to bookmark/unbookmark a repo when viewing its detail

### Design: UX / UI documentation

<img width="467" alt="Screenshot 2024-02-22 at 14 09 03" src="https://github.com/OpenConceptLab/ocl_issues/assets/95474174/9ba91226-91a5-49e4-b594-81cee230ecb4">

> A list of a users 'bookmarks' in the left nav.

<img width="1079" alt="Screenshot 2024-02-22 at 14 09 52" src="https://github.com/OpenConceptLab/ocl_issues/assets/95474174/8d76100d-a311-4745-a957-06857556f2dc">

> The bookmark button in the top right of the repo header.

**Comment by paulsonder** [comment]
Question: Could 'Bookmarks' be how a User creates their 'walled garden'?

**Comment by jamlung-ri** [comment]
> Question: Could 'Bookmarks' be how a User creates their 'walled garden'?

I have wondered this too. I imagine that there could be multiple walled gardens, including the OCL default (i.e. what we designated as "trusted repos"), and a walled garden like "content that I follow". I feel like "Follow" is a more common thing nowadays as opposed to Bookmarks, since you can follow a lot of stuff but only Bookmark a select few repos. Thoughts?

**Comment by paynejd** [comment]
For technical reasons, the walled garden is going to start as a set of
content for all users of OCL. Meaning, the initial goal is to promote
globally recognized content line standard code systems. However, we
definitely want to explore other versions of the walled garden, for
example, prioritizing repositories or content that a user has access to or
manages or that they have bookmarked/followed. Agree with Joe that the
Following feature might be more what we are thinking than bookmarks.

**Comment by paulsonder** [comment]
OK! In that case, what kind of resources should we allow a user of OCL to follow?

In the designs so far it includes:

- Organisations
- Repositories (my assumption is the latest published version but is that correct @jamlung-ri ?)

Should there be any others?

**Comment by paynejd** [comment]
FYI GitHub let's you "Follow" orgs and users, and let's you "Star" (kind of
like bookmark?) and "Watch" (manage notifications?) of repos

**Comment by paulsonder** [comment]
@jamlung-ri Do you think we're ready to write the user sorry for this and I'll make sure designs are updated?

**Comment by jamlung-ri** [comment]
### User Story for Following Repositories

As a: user with an OCL account
I want: to 'follow' resources
So that (1): My dashboard feed will be populated with updated content that is most pertinent to me, e.g. when a new version is released. 
So that (2): I can filter my search results down to only the content that I deem relevant
So that (3): I can reserve my OCL bookmarked content for a select few repositories that I am constantly navigating to

**Comment by jamlung-ri** [comment]
@paulsonder What do you think about these above? Any other ideas?

**Comment by jamlung-ri** [comment]
Need to differentiate between Watched objects (users, orgs) vs. Bookmarked objects (repos)

**Comment by paulsonder** [comment]
@jamlung-ri Bookmarks appear in the right drawer, [here](https://zpl.io/dRxAQL7). 

When a user follows Users or Orgs, they see their updates in the Dashboard feed. They can unfollow from there, or go to the objects and unfollow from there.

**Comment by jamlung-ri** [comment]
@snyaggarwal I think we're really close to getting this ready for development, just a few design implications in other tickets e.g. #1627 and #1862. Do you feel like we have a strong enough understanding of Following to begin development? If not, let's queue this up for Tuesday's Dev call

**Comment by snyaggarwal** [comment]
@jamlung-ri Yes i think this can be picked.

**Comment by jamlung-ri** [comment]
@paulsonder Please let us know if you have anything to share with Sunny. Otherwise, let's get this one going in Dev!

**Comment by paynejd** [comment]
@snyaggarwal Do you want to add your thoughts to this ticket for how we will model the follower and bookmark API endpoints?

GitHub's REST API model for "following" could be a good place to start: https://docs.github.com/en/rest/users/followers?apiVersion=2022-11-28

**Comment by snyaggarwal** [comment]
@paynejd We already have `pins` resource. I was thinking of using that only. It works for bookmarks.
For followers, depending on what differences are there with Bookmarks we can follow a new model.

**Comment by paynejd** [comment]
We would need to support both pins and bookmarks, not replace pins with
bookmarks.
Pins are how a user highlights content they own (or how an org highlights
content it owns) to other viewers. Bookmarks/followers are how you tag any
owner/repo across OCL that you want to track/remember/follow, but that’s
only for yourself.

Sunny- I think it would need to be separate endpoints, is that right?

Paul- I don’t remember seeing pins in the current design. Did we lose that?

**Comment by snyaggarwal** [comment]
The model for Pins and BookMarks is similar -- who owns it and what they refer to.
I think we need to have a discussion on this on how they are different. May be the model remains same but the use case and behaviours can be different.

**Comment by paulsonder** [comment]
@paynejd We haven't lost the concept of 'pinning' Repositories. 

The user story is:

As a **Repository owner** (either User or Organization), I would like to **pin zero to two Repositories** to the top of my profile page (either User or Organization I am an admin of) so that I can call attention to those Repositories.

See this [design](https://zpl.io/RmMYBKz).

This does differ from the user stories for **Following** Orgs or Users or **Bookmarking** Repo's in terms of language, user need and interaction.

**Comment by snyaggarwal** [comment]
@paynejd 
Right now a `Pin` model is like below. In the below example, the CIEL Repo is pinned by the user.
```json
{
  "id": 1,
  "resource_type": "Source",
  "resource_uri": "/orgs/CIEL/sources/CIEL/",
  "uri": "/users/user/pins/1/",
  "order": 0,
  "created_at": "2024-06-26 08:05:03+00:00"
}
```
- `uri` can be relative to `user` or an `org`, which means the owner of this pin
- `resource_uri` and `resource_type` represents content of the pin

This model would fit with bookmarks and followers by doing few changes:
1. Call it something generic and not `Pin`
2. Add `type` field which will be either `Pin`, `Bookmark` or `Follow`
3. Add validations for each `type`

**Comment by jamlung-ri** [comment]
Putting the Events framework spreadsheet here: https://docs.google.com/spreadsheets/d/1idF7p-0lYizHTPhYgSoxigM9F9MJpzOUeq-TbR5-abI/edit 

@snyaggarwal I think the ball is in your court for this one, so if we need to have a group discussion before development begins, please let us know!

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Follow/Unfollow is deployed on QAv3

**Comment by paulsonder** [comment]
Hi there @snyaggarwal 

I think we can improve the user feedback by switching to using the **Input Chip**. I've updated and added two designs to Zeplin:

1. [A User you do not follow](https://zpl.io/kKDrLeG)
2. [A User you do follow](https://zpl.io/7Gwxv3q)

**Comment by snyaggarwal** [comment]
@paulsonder This is updated.

**Comment by jamlung-ri** [comment]
So far so good with regards to following users! It's harder to fully test this until the Dashboards/Activity Feeds are completed though. I don't know if we can close this ticket out yet until we have seen those. Putting the first Activity Feed into the User Profile is probably a good start.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Some of the events I have added (from user's perspective):
1. Org Create
2. Org Delete
3. Source Create
4. Source Version Create
5. Follow User
6. Unfollow User

**Comment by jamlung-ri** [comment]
Things I tested that worked on the User Profile page:
* Unfollow and follow a user
* Created and deleted an org (UI bug: for deleted org, OCL now shows "Created None" and "Deleted None")
* Created a source and source version
* Created then deleted a source and source version (UI bug: same as deleted org - a deleted source version shows "Created None")

Bugs or other notes (generally UI related, see gif below for examples):

- [ ] The User Profile currently displays a "0" if no actions have been taken. See [jon's profile](https://app.v3.qa.openconceptlab.org/#/users/jon/) as an example.
- [ ] I created and deleted an org, and now my events feed in OCL shows "Created None" and "Deleted None" (unless I recreate the organization with the same ID, in which case the org details appear again.) The same thing occurs with source versions.
- [ ] The scrollable area for Recent Activity on the User Profile could be bigger - it isn't using the entire white space

**Comment by jamlung-ri** [comment]
Things I tested that worked on the User Profile page:
* Unfollow and follow a user
* Created and deleted an org (UI bug: for deleted org, OCL now shows "Created None" and "Deleted None")
* Created a source and source version
* Created then deleted a source and source version (UI bug: same as deleted org - a deleted source version shows "Created None")

Bugs or other notes (generally UI related, see gif below for examples):

- [ ] The User Profile currently displays a "0" if no actions have been taken. See [jon's profile](https://app.v3.qa.openconceptlab.org/#/users/jon/) as an example.
- [ ] I created and deleted an org, and now my events feed in OCL shows "Created None" and "Deleted None" (unless I recreate the organization with the same ID, in which case the org details appear again.) The same thing occurs with source versions.
- [ ] The scrollable area for Recent Activity on the User Profile could be bigger - it isn't using the entire white space

**Comment by snyaggarwal** [comment]
@jamlung-ri  Fixed 1st and 2nd. 3rd I kept less space because I thought there will be recent updated repos or something below activity.

**Comment by jamlung-ri** [comment]
Awesome, this is all working now!

**Comment by snyaggarwal** [comment]
@jamlung-ri I think the next steps are to figure out different events for org and user. The framework is set to record events. May be we should move this ticket forward and create a new ticket with just events that we want to start recording. Also we need to create a ticket for just org events (I think this should be the next first ticket), what do you think?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Most of it is deployed on QA. Couple of things I need to work on:

- [ ] review additional changes in the [Events and Feeds spreadsheet](https://docs.google.com/spreadsheets/d/1idF7p-0lYizHTPhYgSoxigM9F9MJpzOUeq-TbR5-abI/edit?gid=0)
- [ ] Paginate Events in Recent Activity
