### ISSUE TITLE
UI Bug with Search Bar - OCL reruns search when clearing search bar

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1781]
From Slack: "If I enter a search term into the search field and return results then clear the term, the results then show all content in OCL." - Paul

"Yeah, I think the "x" button should only clear the text in the field, but unless the Enter button is used, OCL should not rerun the search." - Joe

This affects both v2 and v3 of TermBrowser

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done on v3. I dont think it should change this on v2.

**Comment by jamlung-ri** [comment]
This is working well on V3 QA! I'm okay with not changing the behavior on v2.
