### ISSUE TITLE
Add registry entry to $resolveReference response

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1788]
From the perspective of the canonical URL registry, `$resolveReference` can resolve a canonical URL in 3 ways: namespace registry, namespace repo, global registry. If a registry entry is used for resolution, we want `$resolveReference` to return the entry in the response.

@snyaggarwal My assumption is that this would simply be the relative URL to the registry entry, which would already include whether it is a global or namespace-specific registry. If there is no registry entry in the response header, then we can conclude one of the following:
- Registry not used to resolve the canonical URL (i.e. resolved to a repo in the namespace)
- Canonical URL could not be resolved
- No canonical URL was not used in the reference (i.e. OCL relative URL was used)

Note:
- [x] Need to add this to the docs after we decide on the approach

**Comment by snyaggarwal** [comment]
Response header -- `X-OCL-API-REGISTRY-ENTRY`

**Comment by snyaggarwal** [comment]
Hey @paynejd I just realised that $resolveReference operation can take multiple expressions:
![Screenshot 2024-03-07 at 9 11 59 AM](https://github.com/OpenConceptLab/ocl_issues/assets/1858162/d143b829-4293-4c29-ae12-f9524e0c7507)


a single response HEADER wont be able to accommodate that.
I think adding `url_registry_entry` in the response directly is better. What do you think?

**Comment by paynejd** [comment]
Tested on QA and works well! Also added to the docs here: https://docs.openconceptlab.org/en/latest/oclapi/apireference/resolveReference.html

**Comment by snyaggarwal** [comment]
@paynejd Can we close this one?
