### ISSUE TITLE
When Hyphen used in the Search, not returning Concepts

### ISSUE THREAD

**Issue by shakirairfaan** [OpenConceptLab/ocl_issues#1789]
###### 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/107749227/5c512bab-ef81-4c3b-823f-084edecee721)

![image](https://github.com/OpenConceptLab/ocl_issues/assets/107749227/76a2659c-4973-4ef0-9b28-70c3f560af34)

**Comment by snyaggarwal** [comment]
@shakirairfaan This is fixed. Can you please give it a try again. Please close this issue if everything looks good.

**Comment by shakirairfaan** [comment]
It works fine. Thanks
