### ISSUE TITLE
Create Similar bug for Mappings - External ID still carries over

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1790]
When trying to create a mapping using the Create Similar button in a source, the new mapping carries over the original mapping's external ID, even if the Auto-Assign setting for Mapping External IDs is on.

See this video where I recreated the bug:
https://www.loom.com/share/1e4b4bd6cfa941328ec9ca8cba84ad0e?sid=c1594d42-3bd9-4fa5-bfd5-a977fd86db5f

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed everywhere. Please test and close this if everything is looking good.

**Comment by jamlung-ri** [comment]
Fixed on Prod! Thanks!
