### ISSUE TITLE
Investigate why Add to Collection failed, failed, failed, then succeeded

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1795]
### Background and context
Relates to: https://github.com/OpenConceptLab/ocl_issues/issues/1720 (direct follow-up of this)

Between 10am PDT - 11am PDT today March 11, I was trying to add these 2 concepts to my OpenMRS "CIEL Conditions & Diagnoses" collection:
- https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/116031/
- https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/116030/

The first 2-3 times I tried adding 116031 to my collection, I received this message: 
> **1 Reference(s) listed below could not be added.** /orgs/CIEL/sources/CIEL/concepts/116031/:Concept fully specified name must be unique for same collection and locale.

Then I went to 116030 and tried to add that one. It succeeded!

Then I went back to 116031 and tried to add that again. It succeeded this time! (What the...)

My request is: Is it possible to i.d. why 116031 failed at first, and then succeeded?

Because, my takeaway from this is, if I get an error message when trying to add a concept to a collection, I should just try again and again and again....?

**Comment by snyaggarwal** [comment]
Yes, thats correct. 
The behavior for single dynamic reference is all or nothing. One reference resolving to 1+ Concepts/Mappings checks on every concept/mapping of that reference for validation and if any single one fails, that reference fails.
While static references check converts the single reference into multiple references, each reference representing one concept/mapping. That's why it's not all or nothing.

**Comment by jamlung-ri** [comment]
@gracepotma Does our discussion above make sense for you and match what you're encountering? If not, please let us know. And if yes, we can decide whether or not this is a "bug" that needs fixing or if the workaround of using static references will suffice.

**Comment by jamlung-ri** [comment]
I'll go ahead and close this ticket out for now, but @gracepotma please feel free to reopen it if an issue still arises. I think the current workaround is that, if you get a failure when adding a dynamic reference, you should try again but with the "Static Reference" box checked.
