### ISSUE TITLE
Community website

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1797]
- [x] Update designs with copy
- [x] Update any images in the designs
- [ ] Review stage with @paynejd and @kaalcumm 
- [ ] Review with Community focus group
- [ ] Create release plan
- [ ] Build out site in Webflow using corresponding Relume components

**Comment by paulsonder** [comment]
Hi @kaalcumm cc @paynejd 

Here a few outstanding tasks for the Community site content work...

- [ ] Review trademark / copyrights for FHIR, SNOMED etc
- [ ] Remove WHO logo and replace with ICD logo - as far as I can see, it doesn't have one. Is there one you had in mind?
- [ ] Quote from MSF or PIH for the OCL Online page - could we source a testimonial? I'm happy to reach out if you let me know who would be best
- [ ] Could we also get a quote from an Org who self hosts OCL tooling?

**Comment by paulsonder** [comment]
Secondly, around imagery.

@paynejd, on the you mentioned updating the two images. What would you like to communicate through these images? A particular feature or tool?

**Comment by paulsonder** [comment]
@kaalcumm How would you like to handle any community engagement (if any) pre-site launch?

**Comment by kaalcumm** [comment]
@paulsonder - Re: Review trademark / copyrights for FHIR, SNOMED etc:

I believe what we need is on this web page for reference: https://build.fhir.org/ig/HL7/fhir-ips/copyrights.html#:~:text=HL7%C2%AE%2C%20HEALTH%20LEVEL%20SEVEN,States%20Patent%20and%20Trademark%20Office. 

We could also confirm with these teams if we think it's needed as we're building the site. 

- HL7®, HEALTH LEVEL SEVEN®, FHIR® and the FHIR ®
- SNOMED CT® 
- SNOMED CT® Global Patient Set (GPS) 
- LOINC®

**Comment by kaalcumm** [comment]
@paulsonder - Here is the ICD-10 Logo: https://www.usfhealthonline.com/wp-content/uploads/sites/2/2017/02/icd-10-who-seal.jpg 

@paynejd - Do we have a contact with ICD-10 to confirm use of the image?

**Comment by kaalcumm** [comment]
@paulsonder  - Re: Quotes

- **Quote from PIH** (see Joe's email from 3/28) - will need to ask permission of Ellen Ball:                  "Partners In Health (PIH) is now managing our OpenMRS concept dictionary with OpenConceptLab (OCL) for implementations at 4 country sites (Haiti, Liberia, Mexico, Sierra Leone). This is a milestone in supporting many countries, multiple languages, and a global PIH team. It is a transparent and consistent way to share our dictionary, and will save deployment time.
It’s been a long process with much support along the way. It exemplified the power of open source, teamwork, and the international OpenMRS community. Our hope is that other community members are already using OCL or moving in that direction."


- **Additional Quotes** (documented in internal report - would need to ask permission of Italo and Beatriz:         OCL has invested in its FHIR service, making it unique and highly regarded as an open-source terminology service. Brazil has adopted OCL as its terminology service and has even contributed to the improvement of OCL’s FHIR Core.
"We could not have done terminology service without OCL. There was no budget." - Beatriz de Faria Leão, Brazilian Health Informatics Association
"We found out that everyone in the (Connectathon) room was using OCL and we didn't even realize it. Brazil, Argentina, and more." - Italo Macêdo, HL7 Brazil

**Comment by kaalcumm** [comment]
@jamlung-ri - With some of the above quotes and perhaps the ICD ten image. If Paul is happy with those for the website, could you help us get approval from the relevant persons to use them?

**Comment by paulsonder** [comment]
> @paulsonder - Here is the ICD-10 Logo: https://www.usfhealthonline.com/wp-content/uploads/sites/2/2017/02/icd-10-who-seal.jpg
> 
> @paynejd - Do we have a contact with ICD-10 to confirm use of the image?

I'm not sure if this is the official logo? It would also be really difficult to use this on the site, it's more of a banner than a logo.

Given a real lack of visual identity for the resource, my suggestion would be to use the publisher, WHO's logo instead. What do you think @paynejd ?

**Comment by paynejd** [comment]
I have never found logos specific to the WHO's terminologies (eg ICD10,
ICD11, ICHI, etc.) -- assuming that they do not exist.

**Comment by jamlung-ri** [comment]
WHO Logo: https://cdn.who.int/media/images/default-source/infographics/who-emblem.png?sfvrsn=877bb56a_2

**Comment by paulsonder** [comment]
@paynejd @kaalcumm 

Updated versions of the designs can be found [here](https://miro.com/app/board/uXjVN3w72wU=/).

I think the main outstanding issue to resolve is imagery, in particular the app screenshots. @paynejd , do you have anything in mind that's important to convey through these images? The images can be found on:

- Tools
- OCL Online
- TermBrowser
- Terminology Service

Thanks,
Paul
