### ISSUE TITLE
User (Detail view) - Empty State + Activity Feed

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1800]
When a user signs up, I think we should direct to them their dashboard and have links to onboarding and guides etc there. I'll create a mock up.

Agree on the empty page being of little value. I'm looking a the empty state now - how about a feed of recent activity? How feasible is that?

<img width="800" alt="Screenshot 2024-02-22 at 13 44 38" src="https://github.com/OpenConceptLab/ocl_issues/assets/95474174/18c36c89-089c-431e-a65f-0d3be375d1ac">

_Originally posted by @paulsonder in https://github.com/OpenConceptLab/ocl_issues/issues/1756#issuecomment-1959385574_

**Comment by paulsonder** [comment]
@jamlung-ri Feels like we're close to closing this, should we try figure out the outstanding requirements?

**Comment by jamlung-ri** [comment]
Sounds good! Here are some ideas that I can imagine for this:

Purely empty state (immediately after creating the profile):
* About Me section: We should encourage users to write a blurb about themselves, like that you did in your mockup. Even a simple "Tell us about yourself" with a way to input information right on screen could be good. 
* Activity Feed: We should be pretty clear about what activities would belong in this section. Here is what I am picturing:
     * "Joined OCL" - account was created (and verified?)
     * "Updated Profile" - Updated narrative information about themselves (i.e. About, email, company, location, )
     * "Created an Organization"
     * "Became a member of [organization]"
     * "Created a Repository [repo chip]"
     * "Published a Repository [repo chip]"
     * (Unsure but future) "Made comments in [repo chip]"
* Recently Updated Repositories: Show a message like "No repositories yet" and give a call to action to create something
     * Note that we should be clear about what this list is - is it only repos owned by that user, or is it all repos that the user owns and/or contributes to?

**Comment by paulsonder** [comment]
@jamlung-ri 

Updated designs can be found [here](https://zpl.io/eznmnPW).

**Comment by jamlung-ri** [comment]
@paulsonder Can we close this one out? I think the development of this is being captured in #1627

**Comment by paulsonder** [comment]
> @paulsonder Can we close this one out? I think the development of this is being captured in #1627

Yep :)
