### ISSUE TITLE
Show Export Time in User Interface

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1806]
We recently added an attribute to Source and Collection exports that says how long the export took. We should show this somewhere in the UI so that it is easily viewable.

How could we quickly incorporate this into the Version tab?
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/489c0f9d-ce43-4667-942d-fc8944fb52af)

**Comment by paulsonder** [comment]
@jamlung-ri 

What's the user story here? Who needs to see it and why?

**Comment by jamlung-ri** [comment]
The user story is from Ellen's perspective, specifically:

As a terminology implementer, I want to view the time it took OCL to make my version exports so that I can anticipate the length of time I should wait for future exports. (Currently, Ellen is unsure if she should be checking back in on a new export after 5 minutes, 5 hours, or 5 days).

**Comment by paulsonder** [comment]
Thanks @jamlung-ri !

Does that mean that the only user who should see this is the one who ran the export?

**Comment by jamlung-ri** [comment]
Yeah, it should only appear for users who have access to edit the content

On Mar 13, 2024 4:33 PM, Paul Adams ***@***.***> wrote:

Thanks @jamlung-ri<https://github.com/jamlung-ri> !

Does that mean that the only user who should see this is the one who ran the export?

**Comment by paulsonder** [comment]
@jamlung-ri I would suggest we include in the **Created by** meta data line...

**For example:**

`Created by jamlung on 00:00:00 • Export time 8 minutes`

**Comment by snyaggarwal** [comment]
@jamlung-ri We dont store this information anywhere. We need to first decide where it fits in the version model.

**Comment by snyaggarwal** [comment]
Add this info in `extras.__export_time` and exclude from checksums and document it

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA and Staging

**Comment by jamlung-ri** [comment]
Thanks, sounds good. Here are the collections I was testing with:
* https://app.qa.openconceptlab.org/#/users/jamlung/collections/dynamic_collection2/versions
* https://app.staging.openconceptlab.org/#/users/jamlung/collections/testr/versions

And here's where I thought I would see the export time:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/26a29619-acf2-4032-92b1-fb79526dfd38)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed on QA. You can see your collection version will now reflect Export Time. It was getting recorded but just not getting displayed.
This is getting deployed on Staging as I write this. So will reflect there as well soon

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed everywhere.
