### ISSUE TITLE
Quick-Add Mapping (in Concept Details) does not autoscroll

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1807]
When I use the Concept Details split view to add a mapping to a concept, the form appears at the bottom of the section, and I cannot see it if I have a concept with too many mappings. OCL should automatically (although maybe not instantly) scroll down to that form when opening it.

Video demonstrating the issue, where I had to manually scroll down to find this form:
https://iu.mediaspace.kaltura.com/media/t/1_0ka75iwy

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA

**Comment by jamlung-ri** [comment]
@snyaggarwal This is working for me on Chrome and Edge browsers, but not Firefox. Honestly I'm not sure if this counts as completed or not since OCL doesn't say what browsers we support, to my knowledge. What do you think?

**Comment by snyaggarwal** [comment]
@jamlung-ri Thats a good question. I think this one is very small, I have changed it to use universal browser scroll API (scrollIntoView) and not the latest one (scrollIntoViewIfNeeded)

**Comment by jamlung-ri** [comment]
Awesome, this is now working on both Chrome and Firefox on QA! This is good to deploy.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere
