### ISSUE TITLE
"Update Comment" should be near button for submitting updates to concept

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1808]
The "Update Comment" field is too high on the form, and if a user forgets to fill it in since it isn't near the submit button, they get a bit discombobulated. I propose that the Update Comment field should be the last field on the form before submitting an edited concept.

Video demonstrating the issue:
https://iu.mediaspace.kaltura.com/media/t/1_lxxlteo9

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA and done for Concept and Mapping forms

**Comment by jamlung-ri** [comment]
This is working great, apart from the bug I raised in another ticket (#1809). 

This should be good to deploy to Prod!

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere
