### ISSUE TITLE
Mapping Sort Weight changes are rejected by Checksum

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1809]
I was testing out a different feature and noticed that when I try to Edit Mapping and change the sort weight, the standard checksum doesn't change and so the update is not accepted by OCL. I don't know if sort weight should change the checksum, but I should at least be able to submit the change in the Edit Mapping form.

Noting that changing the sorting using the the Concept Details -> Associations section still works. It's only the Edit Mapping form that I see it not accepting the sort weight change.

cc: @paynejd @bmamlin

**Comment by paynejd** [comment]
Standard checksum for mappings should change with sort weight.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA

**Comment by jamlung-ri** [comment]
Great, this is now working as expected on QA!

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed everywhere
