### ISSUE TITLE
CSV Importer isn't accepting "canonical_url" attribute

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1817]
The following CSV successfully uploads via Bulk Import, but the canonical URL does not appear. Example repo where I loaded this into Staging but do not see the canonical URL: https://app.staging.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/collections/IMMZ.E0.DE15-values/

[SHORT - ocl-import-measles-value-sets.csv](https://github.com/OpenConceptLab/ocl_issues/files/14695726/SHORT.-.ocl-import-measles-value-sets.csv)

**Comment by snyaggarwal** [comment]
@jamlung-ri I dont think our CSV to JSON convertor reads canonical_url yet.
cc @paynejd

**Comment by snyaggarwal** [comment]
@paynejd I have raised a PR https://github.com/OpenConceptLab/ocldev/pull/17 for this

**Comment by snyaggarwal** [comment]
@jamlung-ri This is ready for testing

**Comment by jamlung-ri** [comment]
@snyaggarwal It didn't seem to work on QA. I will attach the CSV that I used for testing, plus the report which did not seem to include the `canonical_url` attribute.

* Org to load collections into: https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/collections/
* CSV to import: [SHORT - ocl-import-measles-value-sets.csv](https://github.com/OpenConceptLab/ocl_issues/files/14806935/SHORT.-.ocl-import-measles-value-sets.csv)
* JSON report from OCL's Bulk Import: [65ff79e6-42b7-4bd1-9918-f2a0f1fb13d5-jamlung~default.json](https://github.com/OpenConceptLab/ocl_issues/files/14806932/65ff79e6-42b7-4bd1-9918-f2a0f1fb13d5-jamlung.default.json)
* Example Collection (which does not have a canonical URL): https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/collections/IMMZ.E0.DE18-values/

**Comment by jamlung-ri** [comment]
Now it's working on QA! The example Value Set from above now has a canonical URL on it. Note that I had to delete the collection and reupload it for this to work since the bulk importer seems to not update collections without an explicit update

**Comment by snyaggarwal** [comment]
@jamlung-ri Thats correct. Close this ticket if everything is feels correct
