### ISSUE TITLE
Errbit Notifications not coming through to Slack

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1818]
Certificate verification failure

OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
/usr/local/lib/ruby/2.5.0/net/protocol.rb:44→ connect_nonblock
/usr/local/lib/ruby/2.5.0/net/protocol.rb:44→ ssl_socket_connect
/usr/local/lib/ruby/2.5.0/net/http.rb:981→ connect
/usr/local/lib/ruby/2.5.0/net/http.rb:920→ do_start
/usr/local/lib/ruby/2.5.0/net/http.rb:909→ start
/usr/local/lib/ruby/2.5.0/net/http.rb:1455→ request
httparty-0.16.3/lib/httparty/request.rb:145→ perform
httparty-0.16.3/lib/httparty.rb:573→ perform_request
httparty-0.16.3/lib/httparty.rb:507→ post
httparty-0.16.3/lib/httparty.rb:624→ post
[PROJECT_ROOT]/models/notification_services/slack_service.rb:52→ create_notification
mongoid-5.4.1/lib/mongoid/relations/proxy.rb:151→ method_missing
[PROJECT_ROOT]/models/error_report.rb:112→ services_notification
[PROJECT_ROOT]/models/error_report.rb:62→ generate_notice!
[PROJECT_ROOT]/controllers/api/v3/notices_controller.rb:24→ create

**Comment by rkorytkowski** [comment]
Upgraded errbit to the latest docker image tagged as latest (from 2 months ago) to see if it fixes the issue. Also adjusted smtp to be able to get e-mails for watched apps.

**Comment by snyaggarwal** [comment]
Still unable to send notifications to Slack.
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
Last Notice: Mar 26 01:05:18

**Comment by rkorytkowski** [comment]
Forked errbit to https://github.com/OpenConceptLab/errbit in order to address the underlying Slack issue. Built and deployed with https://ci.openmrs.org/browse/OCL-OER-3

Let's see if https://github.com/OpenConceptLab/errbit/commit/8ce00afce6ed822a596435fd8211e9a2492d702a fixes the issue.

**Comment by snyaggarwal** [comment]
errbit apps updated with new slack webhook URL.
