### ISSUE TITLE
DB new connection failures on all environments

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1819]
Related errbits -- https://errbit.openconceptlab.org/apps/61778931e685dd0007ed0158/problems/65d75252e426750016d39cad

**Comment by rkorytkowski** [comment]
It appears that db connection errors are caused by some tasks not closing connections properly, because we actually 410 connections limit on production db.
The pgbouncer pool is set to just 180 connections so the rest must have been used up by celery tasks, however in normal conditions celery tasks should not be using more than 12 connections… It’s one connection per thread.
I’m betting it’s the most recent task that we set not to use pgbouncer is misbehaving. Celery concurrent?

**Comment by rkorytkowski** [comment]
Added minimum connection pool to pgbouncer so that misbehaving worker does not block regular api requests...

It doesn't address the underlying issue with the worker. We need to investigate why it might have happened. @snyaggarwal looking for ideas... Maybe some recent changes in indexing or concurrent workers?

**Comment by snyaggarwal** [comment]
@rkorytkowski The most recent changes are around enabling direct connection from concurrent workers.

**Comment by rkorytkowski** [comment]
@snyaggarwal what was the reason to change it to direct connection? Is there any way to revert it back to use pgbouncer? How are connections handled by concurrent workers? Are they closed explicitly in our code or is it some django code that is responsible for doing it?

**Comment by snyaggarwal** [comment]
The reason was the `.iterator`. Batch iteration on queryset doesn't work with pgbouncer. Thats why we did direct connection in indexing worker as well to start with.
Well I think since we have direct connection in indexing worker, its eating up all the available connections and rest of the workers/api starve. We need to find the solution of pg_bouncer + iterator ([link](https://docs.djangoproject.com/en/5.0/ref/databases/#transaction-pooling-server-side-cursors)).

Django is responsible for closing the connection.

**Comment by snyaggarwal** [comment]
@rkorytkowski 
pg_bouncer Transaction Pooling mode reuses connections from a pool. Connections might be used by different Django requests.
Django Server-Side Cursors (queryset.iterator()) utilizes server-side cursors on the database to efficiently iterate through large datasets.
Now, Server-side cursors are tied to specific connections. In pg_bouncer's transaction pooling mode, a subsequent request might not get the same connection that opened the cursor with `iterator()`. This leads to the "server cursor does not exist" error because the new connection doesn't recognize the cursor opened by the previous one.

So we can do either of the two:
1. Disable Server-Side Cursors: `DISABLE_SERVER_SIDE_CURSORS = True` in settings. But this will disables the efficiency benefits of server-side cursors
2. Wrap every `iterator()` in Transaction -- This ensures the same connection is used throughout the iteration, avoiding the cursor issue. But this might not be ideal for performance due to frequent transaction overhead.

**Comment by snyaggarwal** [comment]
@rkorytkowski There are currently only 3 places (4 occurrences) where we use iterator.
1. Bulk indexing (new version creation/import/etc)
2. Bulk Delete (version/org/etc delete)
3. Bulk Checksums creation -- temp job

For now, I think we can move everything to pg_bouncer and alternatives of iterator like Paginator or custom chunking approach

**Comment by snyaggarwal** [comment]
@rkorytkowski Created a [PR](https://github.com/OpenConceptLab/oclapi2/pull/645) to replace `iterator()` with `Paginator`.

**Comment by snyaggarwal** [comment]
This is now deployed to QA DEV and Staging

**Comment by snyaggarwal** [comment]
@rkorytkowski This is deployed everywhere and it's been a week with no errors. Closing this, please reopen if you think something is missing.
