### ISSUE TITLE
API returning Duplicate results

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#182]
For example, https://api.demo.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?page=1&limit=50&q=*&sortAsc=id&datatype=Boolean&conceptClass=Drug&timestamp=1574710918960 returns 2 of each.

**Comment by harpatel1** [comment]
@Karuhanga are you workin on this one ?

**Comment by paynejd** [comment]
Not observing this behavior in the provided query. We will close this ticket out and continue to track this bug in a related ticket #303
