### ISSUE TITLE
Troubleshoot OCL Chat notifications not being sent

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1820]
It appears that OCL chat email notifications may not be going out anymore.

**Comment by rkorytkowski** [comment]
I've just checked it. The last e-mail I got is digest from March 20, which sounds right. Please check https://chat.openconceptlab.org/u/jon/preferences/emails for email preferences. Maybe an upgrade affected them for you. They seem right for my account.

**Comment by rkorytkowski** [comment]
E-mails queues at https://chat.openconceptlab.org/admin/email/sent also seem fine.

**Comment by paynejd** [comment]
Thank you for confirming!
