### ISSUE TITLE
Bug: Collection version page won't load concepts

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1826]
When I go to a collection version link like this: https://app.openconceptlab.org/#/orgs/openmrs/collections/CCD/9/concepts/

The Concepts tab does not load. I looked at the API query for this, and it appears to be loading a bad query: https://app.openconceptlab.org/#/orgs/openmrs/collections/CCD/9/concepts/

This appears to be happening in any collection version on Prod. @snyaggarwal did note that the current workaround is to select an expansion, which then allows the Concepts to load correctly e.g. https://app.openconceptlab.org/#/orgs/openmrs/collections/CCD/8/expansions/autoexpand-8/

**Comment by paynejd** [comment]
This kind of bug should have a test so that we never deploy the TB unless
it's working. This needs to be part of TBv3

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA and Staging

**Comment by jamlung-ri** [comment]
This is working on Staging!
