### ISSUE TITLE
index_not_found_exception After updating OCL from an old version (2.3.26) to a recent version (2.3.87)

### ISSUE THREAD

**Issue by italomacedo** [OpenConceptLab/ocl_issues#1832]
###### After updating OCL an old version (2.3.26) and updating it to a recent version (2.3.87), whenever I try to search for a source or collection, we're getting an index_not_found_exception error from OCLAPI2

```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [collections]","resource.type":"index_or_alias","resource.id":"collections","index_uuid":"_na_","index":"collections"}],"type":"index_not_found_exception","reason":"no such index [collections]","resource.type":"index_or_alias","resource.id":"collections","index_uuid":"_na_","index":"collections"},"status":"404"}
```

or 

```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [sources]","resource.type":"index_or_alias","resource.id":"sources","index_uuid":"_na_","index":"sources"}],"type":"index_not_found_exception","reason":"no such index [sources]","resource.type":"index_or_alias","resource.id":"sources","index_uuid":"_na_","index":"sources"},"status":"404"}
```

### User Story
As a: User,
I want: To query a source or collection
So that: I can access the given source or collection

### Acceptance Criteria
   - Given: When searching for a source/collection after updating the OCL to the latest version,
      When: Querying for a source/collection using any term,
      Then: I should see the list of source/collections that match the criteria.

**Comment by jamlung-ri** [comment]
Assigning @snyaggarwal - do you know of a fix for this?

**Comment by italomacedo** [comment]
A couple of updates. It seems that elasticsearch is not creating the indexes. Another thing I noticed is that I am incapable of doing custom searches for sources, collections, concepts, anything really.

```{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":"True","failed_shards":[{"shard":"0","index":"concepts","node":"0STtXXqxRhu6OkNtrEviYw","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":"400"}```

**Comment by italomacedo** [comment]
I'm running this on Docker, using the folowing docker-compose config:

```version: '3.4'

services:  
  es:
    image: elasticsearch:7.17.10
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    restart: "always"
    healthcheck:
      test: "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"```

**Comment by italomacedo** [comment]
Another update: In the concepts listing, within any source, whenever I start to access concepts individually they start appearing in the Search results in the concepts listing.  That's the behavior.

However, in the sources listing, even when I access the source for the first time, and I try to find it in the sources listing, I get an empty array as a result.

**Comment by italomacedo** [comment]
We're hosting our own instance here: https://oclweb2.ips.hsl.org.br/

**Comment by snyaggarwal** [comment]
@italomacedo Looks like the indexes needs to be rebuilt. You can do that using APIs:
1. [swagger](https://oclapi2.ips.hsl.org.br/swagger/) -- /indexes/apps/rebuild/ --
Provide `sources,collections,orgs,users` in apps one API request. And then `mappings` and `concepts` in separate requests.
2. This will trigger async tasks on "celery_indexing" worker, you can monitor that for completion.

This will recreate the indexes and re-index all resources.

**Comment by italomacedo** [comment]
@snyaggarwal Sunny, that fixed all my problems. Thank you so much! Have a good day!

**Comment by italomacedo** [comment]
This issue has been fixed.
