### ISSUE TITLE
FHIR Core ValueSet Import gives "Invalid filter schema" 400 error

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1834]
ValueSet resources like [this one](https://github.com/OpenConceptLab/fhir_imports/blob/main/HL7-Terminology-THO/ValueSet/HL7-ValueSets-25July2023/ValueSet-v3-ActCode.json) sometimes have a filter in the compose statement, but OCL doesn't seem to accept those well. It returns a 400 error when importing using teh `fhir_import` action.

Error log example:
`[400] b'{"http://terminology.hl7.org/CodeSystem/v3-ActCode/concepts/":["Invalid filter schema."]}'`

**Comment by rkorytkowski** [comment]
The issue is actually with https://raw.githubusercontent.com/OpenConceptLab/fhir_imports/main/HL7-Connectathon-Content-May2024/ValueSets/ValueSet-v3-ActEncounterCode.json

**Comment by snyaggarwal** [comment]
@rkorytkowski Removed any limitation on `filter['property']` value. Collection Reference evaluation will ignore any unsupported values

**Comment by jamlung-ri** [comment]
This appears to be working well on QA. Here's an example of a valueset with a filter that successfully imported but has no resources: https://app.qa.openconceptlab.org/#/orgs/fhir_imports/collections/v3-ActEncounterCode/references
