### ISSUE TITLE
OCL API returns wrong FHIR url

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1842]
All environments seem to be returning the wrong FHIR urls when querying OCL's base API endpoint: https://api.openconceptlab.org/

`"fhir_urls":"https://api.openconceptlab.org/fhir/ConceptMap/"`

It should be fhir.openconceptlab.org, not api.openconceptlab.org, and it should include all three FHIR endpoints, not just ConceptMap.

@rkorytkowski Please confirm, in case I'm misunderstanding. :)

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/1472531e-63fd-44e4-b247-dcb373b6216d)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed and deployed on QA and Staging

**Comment by jamlung-ri** [comment]
This is looking good and should be ready to deploy more broadly.
