### ISSUE TITLE
[Checksums] Test Import (using CIEL) with duplicate resources

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1844]
This ticket is a followup on #1746.

Goal is to test duplicate resources should not get created from import using checksums.

Tasks:
- [x] Regenerate concept/mapping checksums for HEAD CIEL version on QA
- [x] Import last CIEL version on QA and check number of updates, should be 0
- [x] Run a new CIEL version on QA and check number of updates, should match against changelog

**Comment by snyaggarwal** [comment]
#### Test 1: Same content upload should not create any new/duplicate resource versions

Import [v2023-07-12](https://app.qa.openconceptlab.org/#/orgs/CIEL/sources/CIEL/v2023-07-12/) again and should not create any new concepts/mappings versions.

Result: 
 - Concept Versions Created = 0
 - Mapping Versions Created = 0
 - Import Summary:
    Started: 2024-05-29 03:20:23.981880 | Processed: 56162/56162 | Created: 0 | Updated: 0 | Deleted: 0 | Existing: 0 | Permission Denied: 0 | Unchanged: 56162

#### Test 2: New content upload should not create any changed resource versions only and should tally up with $compare results

Import [v2023-09-11] should create few concepts/mappings versions and skip unchanged. This should match with $compare results

Result:

**Comment by bmamlin** [comment]
FWIW, here's [the diff my script created for CIEL v2023-09-11](https://pastebin.com/CfzSv6sH). Changes appear to match your findings (noting that I'm inferring and manually retiring mappings before bulk imports, so without that step QA is going to have some extra mappings compared to the actual content).
