### ISSUE TITLE
Collection Re-Evaluation Failing?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1848]
I was on a call with Grace Potma earlier today where we could not get a reference to evaluate properly, either in an auto-expansion or in a manually created expansion. I have trouble keeping straight how OCL evaluates references, so this very well might be user error, but I was unable to help Grace get the collection to work properly. 

I didn't get a full recording, but I did manage to talk through the steps we tried to take that seemed to fail.
* Video: https://iu.mediaspace.kaltura.com/media/t/1_bbseyi0h
* Link to source: https://app.openconceptlab.org/#/orgs/openmrs/sources/DeathCause/
    * Mapping link (with external ID): https://app.openconceptlab.org/#/orgs/openmrs/sources/DeathCause/mappings/2/
* Link to collection: https://app.openconceptlab.org/#/orgs/openmrs/collections/DeathCause/
    * Mapping link (no external ID): https://app.openconceptlab.org/#/orgs/openmrs/collections/DeathCause/mappings/2/

**Comment by snyaggarwal** [comment]
@jamlung-ri The latest version `2` of DeathCause Source is not released, so the reference is still pointing to version `1` which has old mappings (With external_id).
The quick way to check which version the reference is resolving to is by using [resolve reference API](https://api.openconceptlab.org/orgs/openmrs/collections/DeathCause/4/references/7087356/resolve/)

**Comment by snyaggarwal** [comment]
hey @jamlung-ri is this all good, can we close this?

**Comment by jamlung-ri** [comment]
Yeah let's go ahead and close it, and I'll work with Grace to fix the issue. What I'm less certain about is how we are managing these issues in v3 (if at all). Meaning, how are we educating users on why their collection references resolved in this way? Maybe we need to discuss how we can clarify the underlying $resolve process for users? @paulsonder @paynejd FYI
