### ISSUE TITLE
v3 Bug - Searching an Org for Repos

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1851]
When searching an OCLv3 organization for a repository, the search input keeps me on the Overview page, rather than taking me to the Repositories tab. It makes my search entry do nothing when I hit enter.

See this gif for a demo of the bug:
![Org Search for Repo Bug](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/bdde094d-b04f-459f-b8be-a6cbabfe7556)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed

**Comment by jamlung-ri** [comment]
Looks good on QA! Closing it out now

**Comment by jamlung-ri** [comment]
@snyaggarwal This came up again, but in the opposite direction. I went to the org's Repos tab, typed a search term, and it bumped me back to the About. I got it in the Gif below, but then I tried recreating it again and it worked as expected. Can you see if you get the result from this gif?

![Org Search Result](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/d4ed8d82-4546-47c3-aace-dfd0b6ee5e68)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed
