### ISSUE TITLE
Custom OCL account verification/reset password emails

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1858]
Account verification and reset password emails need to be customized for OCL and should indicate which environment

<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEIrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff1d8ee140d1e2339cd8930702319fbdcaf44398/image.png" alt="image.png" />

<img width="765" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/1d2f19a0-8bc5-41d1-8ad2-929ece88e3b4">

**Comment by paynejd** [comment]
Thanks @paulsonder for providing designs for these emails. Here they are:

# Verify email -- production
<strong>Subject:</strong> OCL - Verify your email address

<img width="667" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/7196ea60-85c9-4f64-b60f-e86fc8bb0db2">


# Reset password -- production
<strong>Subject:</strong> OCL - Reset password

<img width="658" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/03f23cd1-a417-4167-96b2-e576f8c0febc">


# Account Verification -- non-production environment
<strong>Subject:</strong> OCL-QA - Verify your email address

<img width="671" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/d54894e3-66a0-4057-b033-7e1f6e774771">

# Reset password -- non-production environment
<strong>Subject:</strong> OCL-QA - Reset password

<img width="650" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/01e13dda-6c21-4ca3-9a72-04cc3ad00e47">

**Comment by snyaggarwal** [comment]
@paynejd I have added an example of this on forgot password on QA.
The only problem is the logo. Gmail doesn't allow image embedding the way KeyCloak is stating. 
There is an open issue with [KeyCloak#26347](https://github.com/keycloak/keycloak/issues/26347) on this.

**Comment by snyaggarwal** [comment]
@paynejd this is deployed on QA

**Comment by paynejd** [comment]
@snyaggarwal Sounds good regarding the logo. A couple of missing items:
- Can you please update the email Subject lines as specified above?
- Is it possible to implement the styling also? The designs have a gray background in a white rounded rectangle, a different font, and the copyright text.

**Comment by snyaggarwal** [comment]
@paynejd Few problems and few successes:
1. Email subject cannot take variables -- Open issue keycloak/keycloak#11883
2. Done

**Comment by paynejd** [comment]
Thanks sunny. How about at least add the OCL to the beginning of the subject and ignore environment variable.

**Comment by snyaggarwal** [comment]
@paynejd Can this be closed?
