### ISSUE TITLE
Global Dashboard for Anonymous User

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1861]
Landing page for anonymous user that shows generic information while prompting them to explore content, begin searching, make an account, learn about OCL, etc.

User Story: As an anonymous user when I first navigate to the TermBrowser, I want to see a dashboard that helps me to start to use OCL (highlighted content, tour, registration/sign-in, etc.)

Acceptance Criteria:
- Access to global search
- Feed of content highlights (not personalized)
- OCL blog feed
- Sign-in/register
- Tour
- Nav menu
- Prepared for non-OCL Online implementation

Design link: https://zpl.io/1yoLRmE

Current Anonymous Dashboard:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/1f892f13-ef9b-4f56-9932-2312dfd3e71b)

**Comment by paulsonder** [comment]
@jamlung-ri Most of the comments in Zeplin have been addressed and re-uploaded.

**Comment by jamlung-ri** [comment]
Recent Highlights feed is documented here: https://docs.google.com/spreadsheets/d/1idF7p-0lYizHTPhYgSoxigM9F9MJpzOUeq-TbR5-abI/edit

**Comment by snyaggarwal** [comment]
Current logic to show Highlights (Events) for Guest Users is 
1. user = `ocladmin` + `superuser` or any `superuser`
2. Following any entity except another user 
3. `event_type` = `CREATED` or `RELEASED` or `FOLLOWED`

**Comment by paulsonder** [comment]
@snyaggarwal This was the intended state for users who are not signed in and are trying to look at content that requires authentication.

https://zpl.io/DplYYKe

**Comment by jamlung-ri** [comment]
@snyaggarwal Now that we have blog posts going, can we add a date next to each blog post too?

**Comment by paulsonder** [comment]
Sure @jamlung-ri  - what's the date format?

**Comment by jamlung-ri** [comment]
Open to input, since I am torn between what's already used on the page (e.g. "2 weeks ago") vs. OCL's blog format (e.g. "Oct 23, 2024"). I lean toward the full date format but don't have a strong opinion.

**Comment by snyaggarwal** [comment]
Added Published date and showing in logged in dashboard as well

**Comment by jamlung-ri** [comment]
Perfect, I can confirm that I'm seeing it both anonymously and as logged-in user, and the published date is there. 

I think the main outstanding thing here is the "Take a tour" which can probably be tracked in another ticket.

**Comment by snyaggarwal** [comment]
Closing this ticket. Lets create specific tickets for feedbacks and bugs.
