### ISSUE TITLE
Indicate the env in Sign In, Register, Forgot Password, Reset Password forms

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1863]
If not in production, all of these KeyCloak forms need to indicate the environment: Sign In, Register, Forgot Password, Reset Password

**Comment by snyaggarwal** [comment]
@paynejd I have tried few examples, let me know which one is better (1st one is deployed on QA)

<img width="536" alt="Screenshot 2024-06-25 at 16 20 15" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/691eb5e8-84a9-4290-b19c-f83516bc21c0">
<img width="449" alt="Screenshot 2024-06-25 at 16 20 25" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/676ddd25-eded-45a3-a0cd-c2065a1a855e">
<img width="506" alt="Screenshot 2024-06-25 at 16 21 49" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/c1714961-403a-4b32-9574-7d8968ad7864">
<img width="475" alt="Screenshot 2024-06-25 at 16 22 11" src="https://github.com/OpenConceptLab/ocl_issues/assets/1858162/629c675e-86b8-4157-b53a-b0398bec75e1">

**Comment by snyaggarwal** [comment]
This value is based on SSO Realm Display Name.

**Comment by snyaggarwal** [comment]
@paynejd Moving it to last option, thats what I like best. Do let me know here what you think

**Comment by paynejd** [comment]
@paulsonder Can you take a 30sec look at this? When in a non-production environment, we just want to display which environment a user is signing into.

@snyaggarwal -- What's the business logic for determining if non-production? This should be a configuration, I assume -- the approach needs to work with many deployments (e.g OCL Online, WHO, Kenya, Brazil, etc.)

**Comment by snyaggarwal** [comment]
@paynejd Each OCL environment is a separate KeyCloak Realm. A Realm has a name and a display name. Right now what you see "OCL QA" is the display name of OCL-QA Realm. Similarly "OCL Online" is the name for OCL-Prod Realm.
We don't have a configuration to tag a Realm as Prod or Non-Prod as such.

**Comment by paulsonder** [comment]
@snyaggarwal @paynejd 

How about something like [this](https://zpl.io/EdmA6xv)?

This uses an Alert inline, Sunny.

**Comment by snyaggarwal** [comment]
@paulsonder I like the styles but I am not sure if we want to say "Server".
@paynejd Should it rather say "Environment"?

**Comment by paulsonder** [comment]
I'll leave the label to you @snyaggarwal but updated to reflect your suggestion.

**Comment by snyaggarwal** [comment]
This is deployed on QA

**Comment by snyaggarwal** [comment]
@paulsonder I was able to do few:
1. Done to very close icon.
2. Done
3. Done
4. Its difficult to break out the card the way the current theme is setup. Will have to move a lot of things around for this. Also I couldn't find the icon in the allowed icon list.

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
@paulsonder I will defer to you on this one. I took a look last week and liked what I saw.

**Comment by paulsonder** [comment]
@snyaggarwal Yes, let's close it. I can create another ticket for point 4 when we've more time.
