### ISSUE TITLE
Feature request: Automatically trigger export export when bulk import succeeds

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1870]
For large imports (e.g., CIEL), it would be helpful if export generation could be automatically triggered after a bulk import succeeds. To avoid unnecessary export generation, perhaps this could be a "Generate export if import succeeds" opt-in feature for bulk imports

<img width="408" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/860834/ff849912-feeb-4702-83ad-0ab3a25ad1f6">

**Comment by paynejd** [comment]
If you add one more json line to the import file to create a temp version,
it will automatically create an export. Would that meet the need, rather
than implementing a feature?

**Comment by bmamlin** [comment]
> If you add one more json line to the import file to create a temp version, it will automatically create an export. Would that meet the need, rather than implementing a feature?

Sure, assuming the export only gets generated if the import was successful. What's that line?

**Comment by paynejd** [comment]
Example:
```
{"description": "Automatically generated repository version", "collection": "HTS-TST-N-MOH-Age-Sex-Result-NpsmKYKl0mt", "released": true, "owner": "DATIM-MOH-BI-FY19", "owner_type": "Organization", "type": "Collection Version", "id": "FY19.v0"}
```

**Comment by jamlung-ri** [comment]
CSV Example:
```
owner_id,collection,resource_type,id,description
WHO-Smart-Guidelines,IMMZ.C1.DE5-values,Collection Version,0.1.0,Initial Load
```

**Comment by snyaggarwal** [comment]
For Source:
```json
{"type": "Source Version", "id": "v1.0", "source": "DemoSource", "description": "First release", "released": true, "owner": "DemoOrg", "owner_type": "Organization"}
```

**Comment by bmamlin** [comment]
The trick in my case is that I'm creating an export for HEAD. I don't create a new version until it has been validated.

**Comment by bmamlin** [comment]
Ok. After discussion on today's architecture call, we agreed that a more scaleable approach for this would be to trigger a new unreleased version using an instruction at the end of the import like @paynejd suggested.

**Comment by bmamlin** [comment]
> @snyaggarwal, if the bulk import is split up and run in parallel jobs, is there a chance the new version could get triggered _before_ all of the other resources have been processed? For example, parallel workers happily adding concepts & mappings in parallel, and then one of the workers finds this version instruction and triggers a new version while a couple of its sibling are only halfway through their resources and we end up with a version missing a few dozen concepts or mappings?

For the record, @snyaggarwal clarified on a call that resources are processed in order by type, so even if concepts & mappings are split across parallel works, as long as the Source Version resource is at the end of the list (comes _after_ all concepts & mappings, all concepts/mappings will be completed before the version is created (so there shouldn't be a problem with concepts or mappings being left out of the version).

So, [adding a source version at the end of an import](https://github.com/OpenConceptLab/ocl_issues/issues/1870#issuecomment-2196819530) should suffice for the ability to automatically trigger an export for bulk imports, so closing this ticket.
