### ISSUE TITLE
API: Get current status of indexing for a repository, plus a method for restarting failed indexes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1884]
One issue that OCL users run into is not knowing that indexing is catching up for their repo, which may affect their search results. For example, I was on a call with Grace where we would search for a concept that we know is in the collection, but because indexing was behind, the search results returned nothing. But without a search query, OCL showed the concept in the list (we just had to use Ctrl + f to find it with the browser).

We should come up with an approach for showing indexing results to users. Additionally, if the index failed, we should have an approach for restarting it. That might include an auto-restart, or it might include giving the user a button to trigger re-indexing in that repository.

As a follow-up, we should think about how to expose this in the UI when viewing a repo as an editor.

**Comment by paynejd** [comment]
Scenarios when this is important:
- Importing
  - this can impact many repos at a time
  - index status of individual resources is tracked internally
- Impact one repo at a time:
  - Adding references (esp large cascades)
  - New repo version
  - New expansion

**Comment by snyaggarwal** [comment]
@jamlung-ri I added states in versions tab, this will go from gray (received/pending) to yellow (in-progress) to green (success) or failure (red).
![Screenshot 2024-08-30 at 11 38 44](https://github.com/user-attachments/assets/28d4d4e5-4503-47a3-8aeb-67ba874f556e)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA and Staging

**Comment by jamlung-ri** [comment]
Testing now! I made a source with lots of concepts and mappings, then created a version. I could see the orange then green indicators for Seeds and Export. I never did see anything related to Indexing, however. Should I have seen that?

Also note that this isn't implemented in collections yet, which is one of the bigger offenders that I have seen for indexing issues. That would probably be a good next step.

![image](https://github.com/user-attachments/assets/bd04853a-19cd-4ae9-b876-e928646ed541)
![image](https://github.com/user-attachments/assets/05da6e88-bbf5-478c-af63-3046af258d25)

**Comment by snyaggarwal** [comment]
Ya I think I added "indexing" part only for released versions. Will check that for non-released versions as well.
Will add this for collections as well.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA with Collection versions and Source versions.

**Comment by jamlung-ri** [comment]
Awesome, this is looking good on QA! Can we send this to Staging next? I want to try it on a massive Collection to see if I can see the indicators that are not in a Success status.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on Staging

**Comment by jamlung-ri** [comment]
Awesome, I'm getting the Started status for my massive collection. See image below for example. Things have worked as expected so far!

@snyaggarwal One last question - is this something that can be added to the HEAD version of repos too? I notice that it seems to be left off of all repos, but I could imagine there being technical considerations if we showed the statuses of the HEAD version.

![image](https://github.com/user-attachments/assets/ac78ebc0-ebf7-4d1a-af13-541ad75aba6d)

**Comment by snyaggarwal** [comment]
@jamlung-ri HEAD version is built as and when you add the content to it, there will be many content seed/index tasks against it. Will have to think of what specific states we should add to solve specific scenarios.

**Comment by jamlung-ri** [comment]
We talked about this in today's Architecture call. For now, we can push this work forward and think about how we handle task management in v3.

More notes:
* Short term fix (if needed): Add a Reindex button using the indexes (requires an API-level change) - could be done quickly
* Long term solution: Detect indexing issues and retrigger, or other TB work to show statuses, retriggering failed jobs, etc.

**Comment by snyaggarwal** [comment]
@jamlung-ri this was deployed everywhere. Closing this.
