### ISSUE TITLE
V3 Sidebar doesn't refresh?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1886]
This may have been an intentional decision, but I noticed that the sidebar in v3 (pictured below, which shows quick links, My organizations, and Following) does not refresh unless I sign out and sign back in to the TermBrowser. Will it be an issue to refresh that when we go to new pages?

<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bffc39fd6f18d73682cbfbb2276b31567d02dd55/image.png" alt="image.png" />

**Comment by snyaggarwal** [comment]
@jamlung-ri Good point. It should now refresh orgs/bookmarks on opening the left menu. 
Also updated the label to "Bookmarks" ("Following" was a typo).

**Comment by jamlung-ri** [comment]
Awesome, this is working great on v3 QA! I was able to open my sidebar, add myself to an organization using v2 TermBrowser, close the sidebar, then reopen it, and the new organization appeared seamlessly.
