### ISSUE TITLE
Bug: Repository list does not refresh when I navigate directly from one user to another

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1899]
When I go from another user's profile to my own e.g. [jon](https://app.v3.qa.openconceptlab.org/#/users/jon/) to [jamlung](https://app.v3.qa.openconceptlab.org/#/users/jamlung/) using Browser URL bar navigation or using the My Profile button, the repository list does not refresh, making it appear like I have no content. I have to click the browser's refresh button to see my repos.

Instead, this repo list should refresh when I enter another user's page.

See gif for example of where this goes wrong.
![User repo refresh bug](https://github.com/user-attachments/assets/79f1b5cb-6c7f-40f8-acf8-4d1821ffa0af)

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed and deployed

**Comment by jamlung-ri** [comment]
Perfect! This is now working in both test cases: whether I use the My Profile button or use URL navigation, the repo list refreshes as expected. I'll go ahead and close it out.
