### ISSUE TITLE
Add cascade=toConcepts with ability to filter by map_type

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#190]
Akin to how `cascade=sourcemappings` auto includes mappings with the current concept as the from concept, `cascade=toConcepts` would include internal toConcepts when adding the mapping to a collection.

Whether they would work together is an interesting question.

**Comment by paynejd** [comment]
+1 for this feature! I assume that this would add the mappings (same as `sourcemappings`) and also add the `toConcepts` for each of those mappings?

**Comment by Karuhanga** [comment]
Yes, that's the idea.

**Comment by paynejd** [comment]
Bumping this ticket as a top priority

**Comment by paynejd** [comment]
We discussed this further on our ocldev call -- proposed requirements:
* Add support for `cascade=toConcepts` -- this will mimic the behavior of `cascade=sourcemappings`, with the addition of adding the `to-concept` if it is defined in OCL (ie. if it is an internal mapping).
* Add support for `cascade=sourceToConcepts` -- same behavior as `toConcepts` except that it will only add the `to-concept` if it is stored in the same source as the `from-concept`
* Make the `cascade` parameter case insensitive, meaning we will accept both `sourcemappings` and `sourceMappings`
* Ability to optionally provide a `cascadeMapTypeFilter` parameter to filter the mappings that are added by their `mapping.mapType` attribute; default is to add all map types -- eg. `cascadeMapTypeFilter="Same As"` will only add `Same As` maps. We want to be able to support multiple map types, eg. `cascadeMapTypeFilter="Same As","Narrower Than"`, and to support commas or other special characters in a map type `cascadeMapTypeFilter="BROADER-THAN","Procedure Site, Direct`
* If a `from-concept` is already part of a collection, the current behavior is skip adding that reference regardless of whether the `cascade` parameter is used. However, if a valid `cascade` parameter is provided, we still want to process the fromConcept in case there are new mappings or toConcepts that need to be added.

@harpatel1 @rkorytkowski Can you please review and suggest any updates?

**Comment by paynejd** [comment]
Note @Karuhanga commented on the additional option of supporting recursively cascading to mutliple levels:
we could add a concept reference with `cascadeMappings=true&cascadeConcepts=true`, we would add the concept, its mappings and their to_concepts, potentially recursively until an n (specified by user) number of levels. Would need to add logic to avoid looping in the case of cyclical mappings.

@Karuhanga would welcome your feedback on the approach proposed above and the possibility of cascading to multiple levels

**Comment by Karuhanga** [comment]
This sounds good so far. I think it would be helpful to think of the two cascades(mappings and concepts) separately and then together. (I don't mean to duplicate any of your points earlier @paynejd but do bear with me :));

The simplest scenarios are when adding;
-  A concept/ a list of concepts, optionally cascade its/ their mappings(`cascade=sourcemappings`)
- A mapping/ a list of mappings, optionally cascade its/ their source concepts(`cascade=sourceconcepts`)

Combine the previous two;
- When adding a list with mixed concepts and mappings(`cascade=sourceconcepts|sourcemappings`)

The last point generalizes well into the recursive cascade;
- I don't think there's a usecase for a recursive cascade for only either of the two @paynejd do you think so? I'd go with `cascade=recursiveReferences`. Here's the quick and dirty approach we'd taken in the ocl client(https://github.com/openmrs/openmrs-ocl-client/blob/master/src/apps/dictionaries/logic.ts) with a max number of levels to cascade to avoid infinite loops.

**Comment by aprilcurrier** [comment]
Delayed due to data corruption work

**Comment by paynejd** [comment]
Closing out -- this has been addressed in other tickets
