### ISSUE TITLE
Add Register button to Account side menu

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1903]
_As a _User__, who does not have an OCL account, _I want to_ be able to Register efficiently _so that I_ am able to continue my tasks in the TermBrowser with minimal interruption.

**Design**
A 'Register' text button has been added to the My Account side menu that opens when a User clicks the Account avatar in the App Bar.

UI design can be found [here](https://app.zeplin.io/project/623204ca71595ab4a7e3f67e/screen/65685b06369d7b66e603532f).

**Comment by snyaggarwal** [comment]
@paulsonder This was done and deployed. Please close if everything looks good

**Comment by snyaggarwal** [comment]
@paulsonder Fixed
