### ISSUE TITLE
Bulk Import capability - Delete Reference

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1907]
Concepts and Mappings can be retired using a Bulk Import script, but collection references currently cannot. We would like to build this capability in OCL Bulk Importing, at least for JSON importing. CSV importing ideally should do this too, but I'm unsure how much extra work this would create.

Give the example below, I'm actually unsure if the "__cascade" line is necessary. We might only need "type", "collection_url", "data", and "__action" since the expressions can't be added into a collection twice, if I'm not mistaken.

Example line for Deleting a Reference from a collection:
```
{"type": "Reference", "collection_url": "/users/jamlung/collections/openmrs-demo/", "data": {"expressions": ["/users/jamlung/sources/CIEL-Example-OCL/concepts/1/5340299/"]}, "__cascade": {"method": "sourcetoconcepts", "map_types": "Q-AND-A,CONCEPT-SET", "cascade_levels": "*", "return_map_types": "*"}, "__action": "DELETE"}
```

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA. Please consider that the Reference Delete may result in hard delete and/or "exclude" reference creation depending on the type of "include" reference.
I also checked the CSV converter and I feel it's supported there.

**Comment by jamlung-ri** [comment]
@snyaggarwal I haven't had any luck yet, unfortunately. Here is the collection I'm deleting from: https://app.qa.openconceptlab.org/#/users/jamlung/collections/openmrs-demo/ and the reference that I'm trying to delete: https://api.qa.openconceptlab.org/users/jamlung/collections/openmrs-demo/references/1024699/. Please feel free to use this collection for testing as OCLadmin, if that would be helpful.

Here are the imports I have attempted (all of which return "successfully deleted" from Bulk Import report, but I don't see any actual results in the collection references):
* `{"collection_url": "/users/jamlung/collections/openmrs-demo/", "data": {"expressions": ["/users/jamlung/sources/CIEL-Example-OCL/concepts/1/5340299/"]}, "type": "Reference", "__action": "DELETE"}`
* `{"type": "Reference", "collection_url": "/users/jamlung/collections/openmrs-demo/", "data": {"expressions": ["/users/jamlung/sources/CIEL-Example-OCL/concepts/1/5340299/"]}, "__cascade": {"method": "sourcetoconcepts", "map_types": "Q-AND-A,CONCEPT-SET", "cascade_levels": "*", "return_map_types": "*"}, "__action": "DELETE"}`
* `{"collection_url": "/users/jamlung/collections/openmrs-demo/", "data": {"expressions": ["/users/jamlung/sources/CIEL-Example-OCL/concepts/1/"]}, "type": "Reference", "__action": "DELETE"}`

Example report results: 
[a7be5e28-e558-4b0c-a6aa-7c436b9df2f7-jamlung~bulk_import_0.json](https://github.com/user-attachments/files/16415081/a7be5e28-e558-4b0c-a6aa-7c436b9df2f7-jamlung.bulk_import_0.json)

**Comment by snyaggarwal** [comment]
@jamlung-ri The concept you are trying to delete `/users/jamlung/sources/CIEL-Example-OCL/concepts/1/` doesn't exist in the collection, or I couldn't find it.

**Comment by snyaggarwal** [comment]
@jamlung-ri After our discussion yesterday on dev call, we have changed this behaviour to strictly check for reference using expression/cascade/transform parameters and if the reference is found it will be deleted. No exclusions are done.
This is now deployed on QA.

**Comment by paynejd** [comment]
In addition to testing, need to add this to the documentation

**Comment by jamlung-ri** [comment]
> @jamlung-ri The concept you are trying to delete `/users/jamlung/sources/CIEL-Example-OCL/concepts/1/` doesn't exist in the collection, or I couldn't find it.

@snyaggarwal It's an unresolved reference in that collection. The concept doesn't show up in the expansion since it's not loaded into QA, but it's the reference that I'm trying to delete. Should I be trying a different method e.g. doing a Delete line in the Bulk Import File that instead points to the reference ID, rather than the concept ID? That would work fine for me if the Bulk Importer could handle it.

The reference to be deleted is here: https://api.qa.openconceptlab.org/users/jamlung/collections/openmrs-demo/references/1024699/

**Comment by snyaggarwal** [comment]
@jamlung-ri Can you try the same thing that you did earlier in bulk import with action delete. The concept expression should work.

**Comment by jamlung-ri** [comment]
There we go! Now it worked! I have some more testing to do before I can fully close this out, but I'm unblocked for now.

Side note: One of my Bulk Import Delete lines had a cascade that was not present in the original reference. This prevented the Delete from occurring since it appears that OCL was looking for a match with both the "expression" and the "cascade" attributes.

**Comment by snyaggarwal** [comment]
@jamlung-ri Can we close this?
