### ISSUE TITLE
TBv3 checkbox behavior (in search results) should mimic gmail

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1913]
In gmail, note the distinction between:
- Selecting a row highlights ("selects") the row, retrieves its details, and unchecks any checked boxes (selecting a row does not itself "check" a box)
- Checking a box also highlights the row (with a different highlight color than "selecting" the row) -- it does not retrieve details and it does not affect the state of any other checked boxes

Acceptance criteria:
- [ ] Match the behavior of gmail selection and checking -- note that the requirements above do not capture everything

**Comment by snyaggarwal** [comment]
@paynejd I added the following:

> Selecting a row highlights ("selects") the row, retrieves its details, and unchecks any checked boxes (selecting a row does not itself "check" a box)

@paulsonder Need your input on:

> Checking a box also highlights the row (with a different highlight color than "selecting" the row) -- it does not retrieve details and it does not affect the state of any other checked boxes

Any other recommendations from gmail?

**Comment by paulsonder** [comment]
Hi @snyaggarwal 

- For a clicked row (to open a detail view). I'm using color 'primary95'.
- For rows where the check box is checked, I'm using color 'primary80'.

**Comment by snyaggarwal** [comment]
@paulsonder I have added primary80 for checkbox selection and primary90 for row click. primary95 was looking too light in within the repo search results. Have a look at this and let me know

**Comment by snyaggarwal** [comment]
@paulsonder Can we close this?
