### ISSUE TITLE
Quick fix - Follow button appears on my Edit Profile page

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1914]
I noticed that when I edit my user profile on V3, the Follow button appears (even though it doesn't appear in the View my Profile page). This should be removed, even though it correctly fails due to "user can't follow themselves".

Image:
![image](https://github.com/user-attachments/assets/919e7a48-2fd7-43fd-8098-19a40451dfd4)

**Comment by snyaggarwal** [comment]
@jamlung-ri this was a bug, fixed.

**Comment by jamlung-ri** [comment]
This is fixed!
