### ISSUE TITLE
 Adding all concepts/ mappings to a collection from a source/ collection should be asynchronous

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#193]

**Comment by paynejd** [comment]
@Karuhanga are you working on this ticket?

**Comment by paynejd** [comment]
Does this operation happen in the OCL core or in the client?

**Comment by Karuhanga** [comment]
The plan is to use this for the client for the copy a collection use case.

I think I must have forgotten to close this given I merged my changes.

I am currently not using this functionality though because the index update takes a while.
