### ISSUE TITLE
OCL forms unresponsive due to HEAD summary numbers in a loading state

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1931]
When OCL is loading the Summary numbers for HEAD version (this happens on the [PIH source's](https://app.openconceptlab.org/#/orgs/PIH/sources/PIH/) Versions tab), Ellen is unable to use the Create Version form. OCL seems to get held up by the HEAD summary numbers and prevents her from inputting information. Instead, OCL somehow brings up the options to "Add Concept", "Add Mapping", and "Add Version" options, which also don't really work.

I recreated the issue in this video: https://www.loom.com/share/f62affe87f86453780732bb6f814e9a9

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed and deployed on QA/Staging

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on Prod

**Comment by jamlung-ri** [comment]
This is working on Prod and Staging!
