### ISSUE TITLE
Repository design

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1935]
### Introduction
The visual architecture of the **Repository** layout and design in V3 aims to give users efficient access to the information they need most as well as visually distinctive patterns to represent _owner information, metadata, content, versions, expansions_ and _summaries_.

The layout is designed to include the maximum amount of content a user may need to see when viewing a FHIR resource (part of OCL's drive to introduce new 'repo types' such as _CodeSystems_, _ValueSets_ and _ConceptMaps_ alongside the legacy 'Sources' and Collections'), meaning new thinking for attributes that V2 did not intuitively expose

### Header
The header patterns allows a user to identify the **Repo's** Code, Type, Version, Name and Owner. A number of CTA's allow them to change the _version_, navigate to the owners **Organization** page and _Follow_, _Export_ or _Share_ the **Repository**. For users with _Edit_ permissions, the menu on the top right of the header includes CTA's to manage the **Repository**.

<img width="1110" alt="Screenshot 2024-10-01 at 15 42 23" src="https://github.com/user-attachments/assets/7b2ed204-ad05-447c-8762-79db5abfbd7f">

### Summary panel
To the right of the main content area in the template the user can find the _Summary panel_. It currently consists of three sections:

**Chips:** This panel includes _chips_ to indicate attributes such as visibility, if the Repo is FHIR ready or it's content flagged as Experimental. 

**Summary:** The **Repository** summary is below, which brings the V2 summary up front in the UI and could be extended to include counts of new **Repository** attributes, such as '_Custom Attributes_'. Each attribute in the _Summary_ may have additional information to be displayed using the _Extended Tooltip_ component.

**Contributors:** The **Repository** _contributors_ are listed below, visualised using their avatars, which are clickable and lead to their **User** profile page. 

<img width="318" alt="Screenshot 2024-10-01 at 15 44 17" src="https://github.com/user-attachments/assets/87e4bae0-5161-48e2-96db-3f6f4522eb9a">

### Overview
The primary content area of the **Repository** template is a tabbed view of the **Repositories** content, including the _metadata_ and content itself (**Concepts**, **Mappings**, **References**).

The _Overview_ serves to house the **Repositories** metadata and some content from the OCL 'legacy' repo's, such as _About_. If a particular attribute is not mandatory and has not been added by the author, 'Approval date', for example, then it will not be included in this section.

This section was modelled on the metadata attributes of a FHIR resource. The groupings in the page have been created by the OCL team. These are: _Descriptions and Use_, _Publisher and contact_ and _Reviews and approvals_.

<img width="930" alt="Screenshot 2024-10-01 at 15 46 35" src="https://github.com/user-attachments/assets/0d5ec13a-499c-4aa2-a3b7-450c65110346">

### Content
The content of the **Repository** is organized into tabbed sections. These may change depending on the **Repository** _Type_. The tabs display content in _tabular_ or _card views_. Tabs include:

**Concepts:**
Both tables and cards can be filtered. The tabular display allows for a Hierarchical layout.

<img width="924" alt="Screenshot 2024-10-01 at 16 18 35" src="https://github.com/user-attachments/assets/a7d57fa5-b953-44ab-b040-11e4b0fa5c4f">

**Expansions:** You will notice that the Expansion picker is positioned closer to the content in the layout hierarchy. This proximity implies the relationship with the content and less the Repositories metadata and other versions. I'm interested to know what you think about this.

**Mappings:**
The revised tabular view of mappings uses the 'Group by' design that emerged as a useful mode of understanding **Mappings**. 

<img width="925" alt="Screenshot 2024-10-02 at 10 50 16" src="https://github.com/user-attachments/assets/5a387bc6-6113-47be-86be-f6cc3aaa13cc">

**References:**
When a user views a **Collection**, they should be able to understand the composition of the **Repositories** content, even if it has not been expanded. Here we utilise a '_Grouped by_' view, organised as default '_By source_'.

<img width="918" alt="Screenshot 2024-10-02 at 11 07 57" src="https://github.com/user-attachments/assets/4f98e654-1827-4a91-b813-f9ee0956f4c6">

### Versions
The current method of navigating versions in V3 is via the **Versions** menu accessible in the _header_. This list enables a user to understand some high level information and is the entry point into the Comparison tool. The position in the page hierarchy is intentional and designed so that the user is aware that all data may change below it, should a different version be selected.

<img width="676" alt="Screenshot 2024-10-02 at 11 16 16" src="https://github.com/user-attachments/assets/c058a3f8-fd48-49f8-afdc-02188f50953a">

**Question:** Is there a need for a more detailed 'list'? If so, could we capture the user stories below?

Full screens for all the design above can be found [here](https://zpl.io/3033kmy).

**Comment by jamlung-ri** [comment]
Overall I am feeling pretty good about this. I had some comments in my review of this earlier today, and I've divided them up by person:

For @paynejd and @jamlung-ri :

- Overview:
     - New attributes (e.g. CRMI attributes) might need to be placed here? Should we worry about that now? I lean towards no, but want to make sure. Might answer this on Friday’s Arch call. The attributes fit decently well into existing sections though.
- References:
     - What filters are appearing in the Group by Source view? Are we filtering only by references, or by concepts/mappings, or both? 
     - The “Group by Source” view only seems to show concepts (which is probably fine?), but mappings also can come from a reference. Jon/Joe should think about this.
- Version Selector and Summary: For repos that have references, do we need to show the count of references?
- (Paul asked this up above) Is there a need for a more detailed 'list'? If so, could we capture the user stories below?

For @paulsonder :

- Expansion selector:
     - Need to see this design - might be a light version of the Version selector but without Visibility or Status, but also has a way to view/summarize Parameters (might have OCL put tags or something
     - Being able to compare Expansions, just like we do Repo versions, will be important
     - Once an expansion is selected, should we somehow show that parameters are applied? Maybe just an icon that can be clicked on?
- Content > Concepts/Mappings: What ticket documents the different concept/mapping views we will support? The designs currently show “Hierarchy” and “Group by source”. What other views will we offer at launch?
     - Concept List (i.e. the default for non-hierarchical sources)

For @snyaggarwal :
- Mappings:
     - Just to check: How possible is this view from an API standpoint? Do we have Sunny’s approval for this?

**Comment by snyaggarwal** [comment]
@paulsonder In the grouped by results of mappings, how will the pagination work?

**Comment by paulsonder** [comment]
> @paulsonder In the grouped by results of mappings, how will the pagination work?

Hi Sunny. Given the nature of the datasets we display, the intention with our data tables in V3 is that they utilise 'infinite scroll / virtual scroll'. This feels more intuitive for hierarchical and grouped by lists.
