### ISSUE TITLE
Pre-populate events

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1936]
Now that OCL is recording events, there are some events that we want to pre-populate since they happened before we supported events:
- [user] joined OCL
- [user] joined organization [org name] --- (based on current membership, no date, and ideally this should appear in the events list after joining OCL and after the organization's creation date)
- [user] created organization [org name] --- (based on an org's created_by and created_on attributes)
- [user] created a [repo]

**Comment by snyaggarwal** [comment]
> [user] joined organization [org name] --- (based on current membership, no date, and ideally this should appear in the events list after joining OCL and after the organization's creation date)

@jamlung-ri Created Date is mandatory information on Event. And we don't maintain when a user joined the org. I don't see how we can achieve this closer to when it actually happened. Should we ignore this event?

**Comment by snyaggarwal** [comment]
@jamlung-ri This is implemented on QA with all events for all users/orgs/repos, except "[user] joined organization [org name]" event.

**Comment by jamlung-ri** [comment]
This is looking good on QA!
