### ISSUE TITLE
Change Recent Activity label

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1941]
Per [this design](https://zpl.io/DplDQ6O), the Recent Activity feed on the Dashboard(s) (i.e. both anonymous and logged in dashboards) needs to be renamed to What's New.

<img width="1831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfa8cb8f812952b952fc7d236ff9b2131533dfef/image.png" alt="image.png" />

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done
