### ISSUE TITLE
400 error requesting status of bulk import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#195]
This is a very large bulk import that takes ~5 hours to run

https://api.staging.openconceptlab.org/manage/bulkimport/?task=f15ef3a3-8070-470a-b5fc-68b82ecc5996-datim-admin&result=summary

```
{
    "exception": "argument of type 'int' is not iterable"
}
```

**Comment by paynejd** [comment]
Turns out that the import file had errors, specifically the first 3 lines were not valid JSON. Suggest that the error messages be revised to be more informative. It was not clear whether the issue was in fetching the status of the import or if it was in the import file itself. Thanks!

**Comment by paynejd** [comment]
This issue is not yet fixed, but it will be resolved by improving import script validation, which will be tracked in ticket #205. Closing this out.

**Comment by Karuhanga** [comment]
@paynejd I think part of this should involve reviewing whether retrieving any other `processing` status still works correctly.
