### ISSUE TITLE
Repo - Summary

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1950]
User interface can be found [here](https://zpl.io/DplNkR3).

The Summary sits in the right of the Repo template.

Please record any feedback that needs to be actioned **before** moving the Dev here.

For future requirements, let's capture in a separate ticket and prioritise accordingly.

**Comment by jamlung-ri** [comment]
@paulsonder I had one question that I commented on the design about being able to expand the Summary (or if we should put expanded features in a new sort of page or component), such as viewing the list of Map Types in the repo. 

If we can answer that question, then otherwise this design is ready to go to Dev!

**Comment by paulsonder** [comment]
Thanks @jamlung-ri 

The designs have been updated to include a link to 'View all'. My proposal is that we decide how many summaries to display in this list by default, then expand to see all once a user clicks the link.

If further work is required to improve the UX of this based on real insights, I would suggest that's something we can look at later? For example, using a modal...

**Comment by paulsonder** [comment]
@snyaggarwal Moving to **'Ready for dev'** - let me know if you would like to schedule some time to discuss.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder I have added this on QA. Need to understand more on "View All". Right now almost everything is listed without view all.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! Agreed that we need to be clear about View All. Putting feedback below:

- [ ] I wanted to check that each line is intended to be clickable (e.g. to open all mappings with Map Type "SAME-AS"). They appear to be clickable right now but with no action yet. My hope is that they will do an action upon click if possible.
- [ ] Canonical Registry is another line that isn't present - do you feel like you have a good idea of how to implement that part?
- [ ] Looks like the icons don't yet match the design. Is this anything that @paulsonder should help with?
- [ ] What should we do when the Summary is clearly wrong? See screenshot below for example where it says "0 Concepts" even though I can clearly see concepts. Should we offer a Refresh button or something? @paulsonder FYI
![image](https://github.com/user-attachments/assets/0e3b69fb-3214-4d5b-84b0-9ae6ae7b00de)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder 
1. The behavior needs to be defined for on click -- two features -- first is see concept_class/map_type/datatype/etc distribution and then on click of each stat it will apply as filter on left for concepts/mappings.
2. @jamlung-ri Need a bit of discussion on what that canonical registry line means
3. Will check icons
4. We can give recalculate button next to Summary, @paulsonder What do you think?

**Comment by paulsonder** [comment]
@snyaggarwal 

> Re: We can give recalculate button next to Summary, @paulsonder What do you think?

If the user needed to reload, should we show an error state rather than an incorrect summary, is that technically possible?

**Comment by snyaggarwal** [comment]
@paulsonder Its not always possible. There are two types of issues in this:
1. HEAD version not updating to latest concepts/mappings count -- that means it will show X count which is mostly lesser than the real number.
2. A new version is created and its concepts/mappings counts are not calculated (calculation job failed for some reason).

2nd situation is what happens 95%+ times and that's easy to identify but not the other one. I would suggest we somehow give an option to retrigger it (its there in v2) and also show some specific state that it failed to calculate.

**Comment by paulsonder** [comment]
I've updated the [Repo](https://zpl.io/AOmPyXn) designs to include a link to re-run the summary.

Let me know what you think.

**Comment by jamlung-ri** [comment]
This is looking good. I don't see any problems, but the Canonical Registry thing is still needed for discussion, it looks like.
