### ISSUE TITLE
V3 Bug: Page crashes on Concept Details

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1965]
Working on this collection in V3: https://app.v3.qa.openconceptlab.org/#/users/jamlung/collections/test-collection/

When I click on any concept, the page crashes.

Note that Jon also tried to access this collection (which is Private) and was able to see content and replicate the bug. This might be a permissions issue.

![Concept Crashing](https://github.com/user-attachments/assets/dbe29352-fb58-421d-bbf4-ad4a559c3127)

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed

**Comment by jamlung-ri** [comment]
Awesome, I'm not seeing this bug anymore. Closing this out!
