### ISSUE TITLE
Org/User Page: Pinned repos are shrinking too much

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1966]
Pinned Repos on the Org page are shrinking too much – implement fixed or minimum width for pinned repositories?

This is also happening on User page.

![image](https://github.com/user-attachments/assets/14b2b289-cf16-4cee-89d7-0095fa02fba3)

**Comment by paulsonder** [comment]
Design notes:

- Let's introduce a min-width and maximum of three per row before they break over a new line?

**Comment by snyaggarwal** [comment]
We allow max 4 pins for now. So putting 4 in one line.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA/STaging

**Comment by jamlung-ri** [comment]
I don't see any different at the moment but I might be missing something. Looking at my profile on QA: https://app.v3.qa.openconceptlab.org/#/users/jamlung/

![image](https://github.com/user-attachments/assets/de010114-0672-462e-8213-c3de3f421dff)

**Comment by snyaggarwal** [comment]
@jamlung-ri This should better now with a scroll

**Comment by jamlung-ri** [comment]
Great, this is working well now! Closing this out
