### ISSUE TITLE
Signed-in Dashboard Empty State not working properly

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1967]
The empty state for a logged-in user is not showing anything (highlights or OCL's drawing from [this design](https://zpl.io/vnMEY0P)), even though ocladmin is following content. This is occurring on V3 Staging, specifically.

![image](https://github.com/user-attachments/assets/6e0c3449-2202-404f-a408-d40984c5b92a)

**Comment by paulsonder** [comment]
Nothing further to add.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA/Staging

**Comment by jamlung-ri** [comment]
Nice, now it's looking better. Closing this out!

![image](https://github.com/user-attachments/assets/2ddd2d01-13eb-4c0b-8d09-80291a8a9e17)
