### ISSUE TITLE
Concept Details Quick Changes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1968]
- [x] Refreshing concept details (e.g. by clicking on a new concept) is pretty confusing – different sections of the details update at different times – need a visual indicator that the panel is being updated and update everything at once
- [x] Remove concept version ID – this should not be displayed
- [ ] Eliminate empty space between concept header and the tabs (between “Malaria” and “Metadata”)
- [x] Reduce vertical spacing in the properties panel
- [x] Associations font size should be the same as the font size used for names and properties

![image](https://github.com/user-attachments/assets/019d810b-aa7b-4ecf-a3cf-d0f3a97081c6)

**Comment by paulsonder** [comment]
Re: the vertical space. That row does have a 'Manage' button for things like 'Edit concept' - we can move this, I think it makes sense, but we'll need to work out where to put those CTA's in a position that makes sense.

**Comment by snyaggarwal** [comment]
@paulsonder Do we have design on where to move it?

**Comment by snyaggarwal** [comment]
@jamlung-ri Added skeleton on Concept Details
