### ISSUE TITLE
Repo Summary Label and other fixes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1969]
We need to make some super quick fixes to the Repo Summary labels.

- [x] Change “# active from # Concepts/Mappings” to “# active concepts/mappings (# retired)”
- [x] Change “# released from # Versions” to “# released Versions (# unreleased)”
- [x] (In the full repo view) Viewing repository details, the results count must be the actual number not “10,000+” (see big screenshot below)
- [x] Numbers are different on the summary panel and filter panel – rather than fix this, seems like we probably eliminate this functionality in the summary panel since it is duplicative of the filters panel?
- [x] For the “Summary” header, can we say what it is summarizing? Is it the repo version? The entire repo? E.g. “Repository Version Summary”
- [x] For a collection/value set, the summary panel should include number of references

![image](https://github.com/user-attachments/assets/6ee01e3c-41c7-453f-a251-ca6764574db8)
![image](https://github.com/user-attachments/assets/cfbc148b-cb57-40e3-9900-4afd06c44435)

**Comment by paulsonder** [comment]
Nothing further to add here.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA/STaging

**Comment by jamlung-ri** [comment]
@snyaggarwal One quick fix - it looks like Map Types is being shown twice.

Here's the CIEL COVID-19 Starter Kit collection as an example:
![image](https://github.com/user-attachments/assets/170892c8-5a69-4fb9-a4ba-8082b68b3f18)
