### ISSUE TITLE
Improve speed of adding new references using the "cascade=sourcemappings" option

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#198]
When `cascade=sourcemappings` is specified in the request URL to add references to a collection, it results in an enormous slowdown. The slow down is enough that it makes cascading almost unusable. It appears as if there are no indexes on the database queries associated with it.

**Comment by rkorytkowski** [comment]
The issue was with adding references to a collection, which was slow regardless of the cascade option. Fixed. Sped up to adding 5k ref/minute.
