### ISSUE TITLE
Introduce includeReferences param for collections

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#199]
Collections may have lots of references and it is slow to load them all by default. Make collection endpoints to return details without references unless includeReferences=True specified.

**Comment by rkorytkowski** [comment]
Awaiting tests...

**Comment by rkorytkowski** [comment]
Sped up the load time of the list of big collections > 1k so that it doesn't time out. There's still space for improvements.

**Comment by paynejd** [comment]
@rkorytkowski Did you already implement this?

**Comment by rkorytkowski** [comment]
@paynejd, it's been added to all envs, but I still need to add a test.

**Comment by paynejd** [comment]
@rkorytkowski, I know that you did some work on this ticket already, but I don't think that it was fully completed. Can you describe really quickly what you did and what else needs to be done? I'll add this to the roadmap for oclapi2. Thanks!
