### ISSUE TITLE
Fix internal server error when searching mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#2]
The error appears in logs, but does not show in the UI.

api_1 | ERROR 2018/02/05 11:32:47 [base.py:210 handle_uncaught_exception()] Internal Server Error: /mappings/
api_1 | Traceback (most recent call last):
api_1 | File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
api_1 | response = callback(request, *callback_args, **callback_kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
api_1 | return self.dispatch(request, *args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
api_1 | return view_func(*args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
api_1 | response = self.handle_exception(exc)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
api_1 | response = handler(request, *args, **kwargs)
api_1 | File "/code/mappings/views.py", line 309, in get
api_1 | return self.list(request, *args, **kwargs)
api_1 | File "/code/oclapi/mixins.py", line 90, in list
api_1 | results = serializer.data
api_1 | File "/code/oclapi/serializers.py", line 17, in data
api_1 | self._populate_headers_and_data()
api_1 | File "/code/oclapi/serializers.py", line 32, in _populate_headers_and_data
api_1 | page_fields = self.to_native(obj)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 306, in to_native
api_1 | value = field.field_to_native(obj, field_name)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 357, in field_to_native
api_1 | return [self.to_native(item) for item in value]
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 306, in to_native
api_1 | value = field.field_to_native(obj, field_name)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/fields.py", line 967, in field_to_native
api_1 | value = getattr(self.parent, self.method_name)(obj)
api_1 | File "/code/mappings/serializers.py", line 184, in get_url
api_1 | return Mapping.objects.get(id=obj.versioned_object_id).url
api_1 | File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
api_1 | return self.get_query_set().get(*args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
api_1 | self.model._meta.object_name)
api_1 | DoesNotExist: Mapping matching query does not exist.
api_1 | ERROR 2018/02/05 11:32:47 [base.py:210 handle_uncaught_exception()] Internal Server Error: /mappings/
api_1 | Traceback (most recent call last):
api_1 | File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
api_1 | response = callback(request, *callback_args, **callback_kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
api_1 | return self.dispatch(request, *args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
api_1 | return view_func(*args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
api_1 | response = self.handle_exception(exc)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
api_1 | response = handler(request, *args, **kwargs)
api_1 | File "/code/mappings/views.py", line 309, in get
api_1 | return self.list(request, *args, **kwargs)
api_1 | File "/code/oclapi/mixins.py", line 90, in list
api_1 | results = serializer.data
api_1 | File "/code/oclapi/serializers.py", line 17, in data
api_1 | self._populate_headers_and_data()
api_1 | File "/code/oclapi/serializers.py", line 32, in _populate_headers_and_data
api_1 | page_fields = self.to_native(obj)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 306, in to_native
api_1 | value = field.field_to_native(obj, field_name)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 357, in field_to_native
api_1 | return [self.to_native(item) for item in value]
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 306, in to_native
api_1 | value = field.field_to_native(obj, field_name)
api_1 | File "/usr/local/lib/python2.7/site-packages/rest_framework/fields.py", line 967, in field_to_native
api_1 | value = getattr(self.parent, self.method_name)(obj)
api_1 | File "/code/mappings/serializers.py", line 184, in get_url
api_1 | return Mapping.objects.get(id=obj.versioned_object_id).url
api_1 | File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
api_1 | return self.get_query_set().get(*args, **kwargs)
api_1 | File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
api_1 | self.model._meta.object_name)
api_1 | DoesNotExist: Mapping matching query does not exist.

It's only on staging due to missing Mapping object for MappingVersion. Not sure when it happened. I'll add logging to identify which MappingVersion causes the issue.

**Comment by rkorytkowski** [comment]
Added necessary logging and removed broken references.
