### ISSUE TITLE
Allow underscores, hyphens and periods in all resource IDs and standardize

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#200]
Source and collection IDs currently do not allow periods or underscores, but we want to allow these moving forward. While we are updating IDs, lets ensure that the valid syntax characters for all IDs are standardized (to the extent that makes sense) and that underscores, hyphens and periods are allowed in all resource IDs. Here's the list of resource types:
* users
* organizations
* sources
* collections
* source/collection versions
* concepts
* mappings

Suggested approach:
* Document the currently allowed characters/syntax for all IDs in the oclapi 
* Propose changes to IDs to support periods, underscores, and hyphens and to standardize
* Determine changes required in oclapi, in dependent systems (ocl_web, ocldev), and in online documentation
* Develop test scripts (discuss the best testing approach with Rafal)
* Implement new ID functionality in the oclapi core
* Implement required changes in dependent systems/docs -- Note that others will help with some of these

**Comment by paynejd** [comment]
FYI underscores are already allowed in concept IDs. See https://staging.openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH/concepts/TX_NEW_N_MOH_Age_Sex/

**Comment by aprilcurrier** [comment]
This is ready for deployment

**Comment by aprilcurrier** [comment]
Deployed to all environments
