### ISSUE TITLE
Add resource-level timing to bulk importer in full JSON output

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#201]

**Comment by paynejd** [comment]
@snyaggarwal - would this feature be valuable? Now that you're tracking performance of bulk imports, not clear to me if this is still useful

**Comment by snyaggarwal** [comment]
We have concepts/mappings/references timings separated as of now. May be we can close this

**Comment by paynejd** [comment]
No longer needed! closing out...
