### ISSUE TITLE
Implement mappings custom attribute support for CSV import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#2024]
This is already supported for concepts (and possibly other resources), and we want to extend this to mappings as well.

cc @jamlung-ri

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri This is added in ocldev-0.2.2 and updated in API on QA and Staging

**Comment by jamlung-ri** [comment]
It's working on QA now! See here for my bulk-imported source, where each mapping has extra attributes: https://app.qa.openconceptlab.org/#/orgs/WHO/sources/ICD-10-to-11-Maps-WHO/mappings/

I can work on loading this to Staging next.

**Comment by snyaggarwal** [comment]
Closing this
