### ISSUE TITLE
Implement faceted search for collections in oclapi/ocl_web

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#204]
Same as for sources

**Comment by paynejd** [comment]
@snyaggarwal oclapi1 with Solr is capable of returning faceted results (see here: https://github.com/OpenConceptLab/oclapi/wiki#facets). This was enabled for a number of different search types, but was never implemented for collections. Are facets implemented in oclapi2? Based on my tests of ocl_web in qa2, it appears that facets may not yet be implemented, or that they will at least need some additional work. Could you provide some insight here and I'll modify this ticket to reflect the work that we will actually do in oclapi2. Thanks!

**Comment by snyaggarwal** [comment]
This is implemented. Needs testing.
