### ISSUE TITLE
Bulk import API must handle large imports like CIEL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#210]
The bulk import API fails when processing very large import files like CIEL, though it works quite reliably for smaller import files.

**Comment by aprilcurrier** [comment]
Has been postponed due to data integration issues.

**Comment by paynejd** [comment]
We still want to complete this feature -- however, the OclResourceList now has a new `chunk()` method that allows a user to easily split a large bulk import file into multiple files.

We are also defining #253, which will also lower the priority of submitting a single large file in favor of a few smaller files.

Pushing this to the next sprint for now

**Comment by paynejd** [comment]
@snyaggarwal @rkorytkowski Bringing this ticket back to the top as we get ready for some big bulk imports

**Comment by snyaggarwal** [comment]
### Importers app now has the following additional routes:
#### for direct file upload 
`POST /importers/bulk-import/upload/` # Doesn't work with big files like CIEL (80+mb)
#### for direct file URL (HTTP(s) based URL from s3 or github or anywhere).
`POST /importers/bulk-import/file-url/` #Does work with bigger files like CIEL. Current limitation is at 100mb.

**Comment by paynejd** [comment]
@sny- can you clarify how these endpoints are different? Is `file_url`
streaming?

**Comment by snyaggarwal** [comment]
`file_url` is where you specify import file HTTP link e.g. - https://github.com/OpenConceptLab/oclapi2/blob/master/core/samples/ciel-2020-09-27.ndjson?raw=true

that avoids the issue of uploading the file from client or pasting content in the import call. So bigger imports can directly be passed to import API as HTTP link (s3 or anywhere) and the API will fetch it and start importing.

**Comment by aprilcurrier** [comment]
@rkorytkowski  please review

**Comment by aprilcurrier** [comment]
Accepting large import. The remaining issues are deployment related.
