### ISSUE TITLE
Add PUT support for in-place updates of orgs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#215]
Currently only POST is supported, which means that in order to update an org you have to include many other attributes or they are wiped clear.

**Comment by paynejd** [comment]
@snyaggarwal You mentioned this on our call today -- can you confirm that both PUT and POST are supported for orgs in oclapi2?

**Comment by paynejd** [comment]
Note this will not be changed in oclapi1.

**Comment by snyaggarwal** [comment]
Yes!
PUT /orgs/:org/ is supported.
POST /orgs/:org/ is also supported. (for backward compatibility with ocldev/ocl_web)
