### ISSUE TITLE
Expand Elastic Search querying capabilities exposed thru oclapi2

### ISSUE THREAD

**Issue by karuhanga** [OpenConceptLab/ocl_issues#216]
Filtering is currently limited to equality comparisons. This is very limiting, especially given we can support more powerful queries.

**Comment by paynejd** [comment]
@Karuhanga great idea. Do you have recommendations for how OCL would expose this functionality via its APIs?

**Comment by Karuhanga** [comment]
My immediate reaction would be to add an additional query param to keep backward compatibility. `raw_q`?

**Comment by paynejd** [comment]
Closing this out and will create more specific issues to address this in the future
