### ISSUE TITLE
Facets returning incorrect counts

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#217]
When viewing the list of sources for an org, the faceted search counts appear to be returning results for all sources rather than being restricted by the current view. See screenshot below

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/1189689/81318136-c3d28980-905b-11ea-977a-866e720ab3b6.png">

**Comment by paynejd** [comment]
@snyaggarwal Can you confirm that this is (or will be) addressed in oclapi2?

Note that this is related to support for facets in oclapi2, which is also referenced in #204

**Comment by snyaggarwal** [comment]
yes its fixed in oclapi2
