### ISSUE TITLE
Refactor OCL Web Login and Signup to use API

### ISSUE THREAD

**Issue by karuhanga** [OpenConceptLab/ocl_issues#220]
Quoting @rkorytkowski,
> Currently we need to manage user accounts in both ocl_web and oclapi.
There's some synchronization of accounts between ocl_web and oclapi,
but it fails at times. We need to get rid of user management in
ocl_web and rely entirely on the oclapi user management. Ocl_web needs
to do REST calls to oclapi to create/update/delete/authenticate users.
Ocl_web shouldn't be storing user accounts.

**Comment by paynejd** [comment]
Hi @Karuhanga - is this work complete and ready for deployment? Could you also add an estimate? Thank you for your work on this!

**Comment by aprilcurrier** [comment]
@Karuhanga  Any update on the status?

**Comment by Karuhanga** [comment]
:( Sorry guys, I'd started on this and got a little busy. Should have some time this week ti wrap up.

**Comment by aprilcurrier** [comment]
@Karuhanga  Is there an update on this?

**Comment by paynejd** [comment]
this work was completed by @snyaggarwal
