### ISSUE TITLE
Change owner of CIEL org on AWS to be askanter

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#226]
Currently only the "owner" of an org may manage its members, create repositories, and release new repository versions. The owner is the `created_by` user. Can we switch the owner of the CIEL org and source to be `askanter` at the database level in staging and prod so that Andy can manage the org?

**Comment by paynejd** [comment]
This is currently in progress

**Comment by jamlung-ri** [comment]
Andy has an account now and has been added as a member. @paynejd I don't really know how to change ownership at the database level though. Not sure if there is documentation on this.

**Comment by paynejd** [comment]
Yeah this was worded a bit aspirationally :)

Currently any org member is considered an owner, so if Andy is a member
then he is all set!
