### ISSUE TITLE
"System encountered an error" for org with no sources in ocl_web

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#228]
Browsing to http://openconceptlab.org/orgs/MSF/sources/ returns an error (if there are no sources). It should be possible to reproduce this error by simply creating a new org in ocl_web and browsing to the `Sources` tab.

**Comment by aprilcurrier** [comment]
Monitor to see if issue occurs again

**Comment by paynejd** [comment]
Issue resolved itself... will create new ticket if it happens again
