### ISSUE TITLE
Fork a concept or mapping (copy it, and save a pointer to the forked version)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#23]
This was already prototyped here: https://api.github.com/repos/OpenConceptLab/ocl_web/pulls/324

**Comment by paynejd** [comment]
Discuss in a future OCL Architecture call -- is this a feature we want to implement?

**Comment by jamlung-ri** [comment]
We might be able to close this out. I believe this is a main focus of the Concept Modification work (#746)

**Comment by paynejd** [comment]
this is addressed through cloning - closing this out
