### ISSUE TITLE
Fix AttributeError: 'NoneType' object has no attribute 'names'

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#240]
The issue is often reported by sentry (1k events - 1-2/day).

**Comment by paynejd** [comment]
@rkorytkowski Can you provide update on this? Was this an oclapi or ocl_web error?

**Comment by snyaggarwal** [comment]
This was fixed in oclapi2 as well.

**Comment by paynejd** [comment]
@rkorytkowski Can you confirm that this ticket was fixed in oclapi v1?

**Comment by aprilcurrier** [comment]
Not fixed in API 1. Errors reported by Century . Rolling over it needs to be fixed in API 1

**Comment by rkorytkowski** [comment]
I'm sorry it's actually been fixed. I've just verified that we no longer see those reported by sentry.
