### ISSUE TITLE
Allow users to filter for internal/ external sources and user/ ocl system sources

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#242]
Proposed approach;

add an attribute to every source to help us determine whether it's internal or external (I understand that for the permanent environments, prod and staging this would be a one time change, however for QA and demo if these attributes are not set in the data snapshot they'll be lost on redeploy, so we would like to add this to the snapshot data).

The convention has been to set external sources' source_type to `External`. We can mark the internal ones as `Internal` .
We'd also like to identify sources holding meta information, for example `NameTypes`, `MapTypes`, we can give these sources types of `MetaSource`.

Thoughts are welcome.

**Comment by Karuhanga** [comment]
Agreed on the ocldev call(18th June) to _for now_ limit this to just making sure the seeded data on demo and qa has the correct source types.

https://docs.google.com/spreadsheets/d/11T9g6iCkDLOhdjrzzYalwCTVcta4_r6OPfRWNVWAQCA/edit#gid=987322458

**Comment by Karuhanga** [comment]
** how will this be done in staging and prod?

**Comment by paynejd** [comment]
Note that the OCL team will need specific requirements if this ticket is to move forward. Keeping this in the icebox for now.
