### ISSUE TITLE
OCL import portal MVP

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#247]
MVP - upload and show results

- [x] 1. Should be able to load json and csv file
- [x] 2. Implement the `GET` status in Javascript with a sample task id - as working previously
- [x] 3. Should be able to display an error or success summary on the page with the sample task id
- [x] 3.1 Should have a status section in the HTML
- [x] 3.2 Should parse the JSON Response and display in the status section of HTML
- [x] 3.3 Example responses - 
```
{
    "state": "STARTED",
    "task": "dc4ef66f-449c-44de-9b83-c1e4a078c9eb-datim-admin"
}
```
For Completed -
```
Processed 28 of 28 -- 28 NEW (200:4, 201:24)
```
For exception -
```
{
    "exception": "task dc4ef66f-449c-44de-9b83-c1e4a078c9eb-datim-admi not found"
}
```
- [x] 4. Implement the `POST` request in Javascript
- [x] 5. Call the `POST`, read the response to capture task Id - send the taskid to status function and `GET` the status on the taskid.

Will be updated here - https://github.com/OpenConceptLab/ocl-file-import

**Comment by aprilcurrier** [comment]
40%  complete on rollover

**Comment by Gcarthy** [comment]
Loads CSV and JSON Files

Needs to display error and success summary

**Comment by aprilcurrier** [comment]
Working on implementing the API upon rollover

**Comment by aprilcurrier** [comment]
Starting import API on web interface

**Comment by maurya** [comment]
Updated the requirements

**Comment by harpatel1** [comment]
95% on roll over.

**Comment by maurya** [comment]
Prototype MVP functional. Presenting in OCL architecture call on 10/09 to decide next steps
