### ISSUE TITLE
Begin scoping for FHIR TS Work 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#248]
Will include mapping between OCL and FHIR

**Comment by aprilcurrier** [comment]
Will also determine what the epics under the FHIR project are

**Comment by aprilcurrier** [comment]
Still ongoing upon 7/10 rollover working on a strawman

**Comment by aprilcurrier** [comment]
Still in progress

**Comment by harpatel1** [comment]
Strawman Approach: https://docs.google.com/document/d/1SaRK0CNMEpKPb0OHXUhbtO5PABzlPi_dCTXKwJMkMmI/edit#heading=h.ersqotaeu521

**Comment by aprilcurrier** [comment]
Adding Jeff W onto the project
