### ISSUE TITLE
Create FHIR mapping document

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#254]
This would include creating mapping document and identifying any gaps between FHIR model and OCL model.

**Comment by harpatel1** [comment]
@aprilcurrier Considering the time constraint this would take about couple of weeks to complete.

**Comment by aprilcurrier** [comment]
Have mapped out 50% upon rollover. Will review with the group next week.

**Comment by harpatel1** [comment]
For CodeSystem, ValueSet and ConceptMap 75% complete on rollover.

**Comment by aprilcurrier** [comment]
Initial draft complete https://docs.google.com/spreadsheets/d/1lumg1d8FX5SPN0mYqZyqfTAvJdCQbngpcZ0FTB7P6bI/edit#gid=0
