### ISSUE TITLE
Update business logic for populating concept.display_name

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#264]
The `concept.display_name` attribute appears to return inconsistent results. For example, requesting a concept in CIEL typically returns the preferred English name, but for some concepts it instead returns a Creole preferred name. Let's use this ticket to define a new set of rules for populating the concept.display_name field.

**Comment by paynejd** [comment]
We want to populate `display_name` taking into consideration the dictionary locale settings, the user locale preferences, and system default settings. In the near-term, we will use dictionary locale settings and system default. We will implement user preferences (eg `accept-language` request header) at a later date.

The following rules for processing `display_name` based on dictionary and system locale settings were drafted on the OCL Dev Community call with input from the OCL for OpenMRS Squad.

**Rules for populating concept.display_name:**
Given a concept, populate `display_name` by processing these rules in order:
1. **Dictionary default locale:**
    * Locale-preferred name
    * First non-preferred name based on sorting order (see below)
2. **Dictionary supported locales (processed in the order listed):**
    * Locale-preferred name
    * First non-preferred name based on sorting order (see below)
3. **System default locales (processed in the order listed):**
    * Locale-preferred name
    * First non-preferred name based on sorting order (see below)
4. First locale preferred name, based on sorting order
5. First other name, based on sorting order

There are situations where multiple names will match a rule, in which case the names must be sorted in a consistent way so that OCL is consistent in the way that it processes display_name. 

**Proposed sort order for concept names matching a specific rule:**
1. Locale Preferred (True first, then False)
2. Locale (ascending)
3. Name Type (non-blank ascending first, then blank)
4. Name (ascending)

**Comment by snyaggarwal** [comment]
Pull request raised -- https://github.com/OpenConceptLab/oclapi/pull/590

**Comment by paynejd** [comment]
Confirming that this is now deployed to QA and staging? @snyaggarwal @harpatel1

**Comment by harpatel1** [comment]
@paynejd Yes, this is deployed in QA and Staging.

**Comment by paynejd** [comment]
Rolling over to next sprint due to delay in deployment from #303
