### ISSUE TITLE
Create docker container to automate CIEL import process

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#266]
Given a MySql database dump of CIEL, we want a docker container that semi-automates generation of the OCL import file.

**Comment by harpatel1** [comment]
@bmamlin Can you provide an update on this ticket ?

**Comment by paynejd** [comment]
Initial dockerization completed by @bmamlin here:
https://github.com/OpenConceptLab/ocl_omrs/pull/4
