### ISSUE TITLE
Create a Bamboo plan for releasing ocldev to PyPI

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#284]

**Comment by paynejd** [comment]
@harpatel1 Let's chat on Slack regarding credentials for publishing to PyPi

**Comment by aprilcurrier** [comment]
60% on rollover

**Comment by aprilcurrier** [comment]
Jon following up on purchase details with @harpatel1

**Comment by paynejd** [comment]
Shared credentials with @harpatel1 for pypi.org and test.pypi.org. Also provided Harsh with Access to the OCL Admin LastPass account so that he can access root accounts for various OCL services

**Comment by aprilcurrier** [comment]
Harsh to follow up with Cynthia waiting to install pkg in bamboo server

**Comment by harpatel1** [comment]
Build Plan - https://ci.openmrs.org/browse/OCL-OCLDEV/
Deploy Plan - https://ci.openmrs.org/deploy/viewDeploymentProjectEnvironments.action?id=189890561

Currently this plan configured to push artifacts to https://test.pypi.org/.

**Comment by harpatel1** [comment]
Update the Build plan to have another deploy option to push to Test and Prod.

**Comment by harpatel1** [comment]
Build plan is updated and now includes options to push to Test and Prod.

**Comment by paynejd** [comment]
@paynejd to test today

**Comment by aprilcurrier** [comment]
Waiting on Testing from @paynejd rolling over
