### ISSUE TITLE
Requesting collections in an org returns results from other orgs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#285]
The query below should only return collection results from the `PEPFAR-Test8` organization, however, there are multiple results from other organizations (`PEPFAR-Test7` and `PEPFAR-Test6`) in the list:
```
https://api.staging.openconceptlab.org/orgs/PEPFAR-Test8/collections/?limit=0&extras__Applicable+Periods=FY20*
```

This is an issue that was worked on before, but it looks like it has not yet been completely resolved.

**Comment by aprilcurrier** [comment]
50-60% complete upon rollover

**Comment by aprilcurrier** [comment]
@harpatel1  can we get an updated ETA on this?

**Comment by harpatel1** [comment]
@aprilcurrier its fixed in QA and Staging.

**Comment by aprilcurrier** [comment]
@harpatel1 So has it been deployed? (looking for which pipeline it falls in)

**Comment by harpatel1** [comment]
@aprilcurrier It is deployed in qa and staging but not in production. I am planning to deploy it in production tonight. I think this ticket is in correct pipeline.

**Comment by paynejd** [comment]
Rolling over to next sprint due to delay in deployment from #303
