### ISSUE TITLE
Indicators not appearing in API query when searching

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#290]
When searching for two indicators in OCL Staging or in the MSP, these two indicators do not appear in the search results. However, they do appear in OCL when using a single-resource query like `https://api.staging.openconceptlab.org/orgs/PEPFAR-Test8/sources/MER/concepts/rMs0q6Yaw0G/`.

The query that we are using is `https://api.staging.openconceptlab.org/orgs/PEPFAR-Test8/sources/MER/concepts/?verbose=true&conceptClass="Indicator"&limit=10&page=1&q=*TB_ART*`

The two indicators that we expect to see in PEPFAR Test 8 in OCL Staging when searching TB_ART: `COP19 Targets TB_ART 15+ : rMs0q6Yaw0G `and `COP20 Targets TB_ART (N) 15+ : RrBIFT7aQDh`.

**Comment by rkorytkowski** [comment]
#297 might have fixed this. @harpatel1, by chance have you rebuilt index to fix inconsistencies? If not, can you do that and verify?

**Comment by harpatel1** [comment]
@rkorytkowski I rebuilt solr indexes in staging as a part of fixing #297. Looks like that didn't fix this issue.

**Comment by aprilcurrier** [comment]
@harpatel1 has verified this is still an issue

**Comment by aprilcurrier** [comment]
Rolling over Rafal to work on in next Sprint

**Comment by rkorytkowski** [comment]
So it appears that there was inconsistency with the Solr index. I've manually saved 2 missing concepts and they started to appear in the search results. I'll rebuild the whole index once again and make sure it stays consistent.

**Comment by rkorytkowski** [comment]
I confirm that after rebuilding the index the search still has the expected results. I'll close this issue. Please feel free to reopen or create a new one if you hit any more discrepancies.

**Comment by paynejd** [comment]
@jamlung-ri FYI this is now fixed!
