### ISSUE TITLE
http post bulk import request is redirected to a get request

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#291]
To replicate the issue try sending a `POST` request to `http://api.qa.openconceptlab.org/manage/bulkimport/` and the response we get is the list of bulk import requests on that environment (behaviour of `GET` request on that same url)

cc: @paynejd

**Comment by paynejd** [comment]
Note that all requests to `http://`, regardless of which HTTP method is used, are automatically redirected to `https://` GET requests. This is expected behavior by oclapi1.

@snyaggarwal @rkorytkowski  Can you please describe what the behavior is for oclapi2 and whether we need to make any changes?

**Comment by snyaggarwal** [comment]
HTTP to HTTPS redirect will happen at the proxy level (aka Nginx).
There is nothing extra we will have to do at the Django level.
@rkorytkowski Please add if I missed anything.

**Comment by paynejd** [comment]
Is it standard to redirect http to https and to always change the method to
GET? It seems like we should update the proxy behavior to be more standard.
For example, perhaps we should only redirect GET/HEAD requests to http and
block all other requests to http. What is standard practice here?

**Comment by paynejd** [comment]
Default behavior is to redirect from HTTP to HTTPS, and this typically is only applicable for GET and HEAD. Other HTTP methods are automatically changed to GET, and we can consider disabling the redirect for methods that are not GET and HEAD in the future. solution to this ticket is to just use `https`
