### ISSUE TITLE
/users/:user/orgs returns all organizations

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#295]
`GET /users/:user/orgs` is expected to return the user's organizations (orgs to which the user is a member); however, it appears to be returning all orgs.

I believe the associated code is [here](https://github.com/OpenConceptLab/oclapi/blob/d36d286a931064b8275f224f1f6212327ae65827/ocl/orgs/views.py#L48-L54).

This is a blocker for the OCL for OpenMRS MVP release.

**Comment by snyaggarwal** [comment]
I believe its happing because of is_staff flag -- https://github.com/OpenConceptLab/oclapi/blob/d36d286a931064b8275f224f1f6212327ae65827/ocl/orgs/views.py#L45

**Comment by bmamlin** [comment]
Testing in QA it appears that I am a member of no orgs, yet my org list includes 21 orgs.
```
http https://api.qa.openconceptlab.org/users/burke/ "Authorization: Token xxxx"
HTTP/1.1 200 OK

{
  "organizations_url": "/users/burke/orgs/",
  "orgs": 0,
  ...
}
```

```
http https://api.qa.openconceptlab.org/users/burke/orgs/ "Authorization: Token xxxx"
HTTP/1.1 200 OK
next: https://api.qa.openconceptlab.org/users/burke/orgs/?page=2
num_found: 21
num_returned: 10

[
  ...
]
```

The same behavior is seen on staging & production. I am not a member of any orgs, yet a query for my orgs (`/users/burke/orgs/`) returns ~140 orgs.

**Comment by harpatel1** [comment]
I have identified the issue. Looks like filters are causing this behavior.
https://github.com/OpenConceptLab/oclapi/blob/master/ocl/orgs/filters.py#L17

**Comment by snyaggarwal** [comment]
Can you please list down the expectations for following URLs:
GET /orgs/ -- unauthenticated user
GET /orgs/ -- authenticated user
GET /orgs/ -- superadmin (or is_staff) user
GET /users/:user/orgs/

**Comment by harpatel1** [comment]
Here is what I think behavior should be:

GET /orgs/ 
- Anonymous user - Return all Public orgs
- Authenticated user (not is_staff) - Return all Public orgs + any orgs that user is member of
- Superuser - Returns all orgs regardless public or private

GET /users/:user/orgs/ 
- Authenticated user (not is_staff) - Only return orgs that user is member of

**Comment by snyaggarwal** [comment]
Cool, I will update that in oclapi2

**Comment by harpatel1** [comment]
@bmamlin Fix is deployed in QA and Staging.

**Comment by bmamlin** [comment]
@harpatel1 QA is working as expected, but staging still returns all orgs.
```
$ http -h https://api.qa.openconceptlab.org/users/burke/orgs/ "Authorization: Token $OCL_QA_TOKEN" | grep num_found:
num_found: 0

$ http -h https://api.staging.openconceptlab.org/users/burke/orgs/ "Authorization: Token $OCL_STAGING_TOKEN" | grep num_found:
num_found: 153
```

**Comment by harpatel1** [comment]
@bmamlin I checked the database and looks like you are a staff user (is_staff : True), that's why you are seeing all orgs.

**Comment by paynejd** [comment]
Rolling over to next sprint due to delay in deployment from #303
