### ISSUE TITLE
Export of sources/collections are not returning zip results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#3]
Broken endpoints:
https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-T-Operating-Unit-Level-IM-FY17/v2017-10-02T101905.267394/export/

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/Mechanisms/v2018-01-13T004813.005885/export/

https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/SIMS3-Facility/v2017-10-11T175154.910319/export/

**Comment by rkorytkowski** [comment]
The issue was with active_concepts and active_mappings being 0 due to an error while running data_integrity_checks. Instead of failing early on an error, I'm now logging it and processing further. Committed in https://github.com/OpenConceptLab/oclapi/commit/b1d2b47f2874582455957b7e1770c9ac08b1e69f

**Comment by rkorytkowski** [comment]
Pushed to staging and production.
