### ISSUE TITLE
Resolve CIEL concept dictionary discrepancies

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#302]
Observations and next steps based on analysis by @bmamlin in #292 -- next step is to outline specific tasks.

## "Orphaned" concepts and mappings:
**Problem:** There are some concepts and mappings in CIEL v2020-07-20 that exist in OCL on prod/staging, but are not associated with the HEAD or v2020-07-20 source versions

**Solution:**
* For CIEL: Manually add these concepts & mappings to the CIEL HEAD and v2020-07-20 source versions on both prod & staging
* For the entire OCL system: Run a query to identify other concepts & mappings that are defined in a source, but that are not part of the HEAD source version -- document this list and we will come up with the right solution for this

## CIEL Mappings pointing to nonexistent concepts
This is an issue in the Mysqldump itself, not caused by OCL

**Solution**: Andy will fix in next CIEL release

## Unhandled CIEL mapping updates/deletions
**Problem:** OpenMRS does not allow retiring of concept maps, only updates & deletions. The _OpenMRS concept dictionary importer_ for OCL will create a new mapping if it runs across a new from-concept + to-concept + map-type combination even though the concept map's UUID in OpenMRS is the same, and the _OpenMRS concept dictionary importer_ doesn't know to retire the older mapping in OCL because it doesn't do a diff. So we now have a lot of CIEL mappings in OCL that should be retired.

**Solution:**
* For CIEL: In all OCL environments, retire CIEL mappings that are in OCL but not in the CIEL v2020-07-20 source.
* For the entire OCL system: No work needed -- no other OpenMRS concept dictionaries are published in OCL production. We will need to make sure that this is handled correctly in MSF, PIH and other OpenMRS concept dictionaries moving forward.
* For the OpenMRS Concept Dictionary Importer: Add optional feature to compare the new OpenMRS JSON with an export from OCL to generate JSON for retiring old mappings.

## Unhandled retired concept reference terms in CIEL
**Problem:** OpenMRS allows retiring of concept reference terms, and it may also be possible to update or delete a concept reference term. The _OpenMRS concept dictionary importer_ does not consider any of these possibilities. So now we may have CIEL mappings in OCL that are pointing to retired or deleted external reference terms or to previous versions of reference terms.

**Solution:**
* For CIEL: Retire CIEL mappings that point to retired concept reference terms.
* For the entire OCL system: N/A
* For the OpenMRS Concept Dictionary Importer: Incorporate business logic to set `retired=true` for mappings pointing to retired concept reference terms.

## Handling deleted concepts
**Problem:** The _OpenMRS concept dictionary importer_ for OCL already handles retired concepts, but it does not do anything if a concept was previously imported into OCL that is no longer included (even as retired) in the Mysql concept dictionary. While this does not happen with CIEL, we could certainly imagine this happening in the future especially as other organizations begin to use this toolset. In this case, we would want to retire the concept in OCL.

**Solution:**
* For CIEL: N/A
* For the entire OCL system: N/A
* For the OpenMRS Concept Dictionary Importer: Add optional feature to compare the new OpenMRS JSON with an export from OCL to generate JSON for retiring concepts that are in the export from OCL but not in the OpenMRS JSON.

**Questions:**
* Should we also retire mappings that are internal to CIEL (eg for Q/A, concept set, etc.) that involve retired concepts?

**Comment by maurya** [comment]
As per discussion on 09/18/2020 Architecture call - @bmamlin  to write comparison script to find resources in OCL CIEL JSON export against the latest CIEL mysqldump

**Comment by aprilcurrier** [comment]
There is a new release of CIEL which fixes some of the issues. Will implement within the next couple weeks. 

Loading new CIEL in tix # TBD

**Comment by snyaggarwal** [comment]
@paynejd do we need to close this one?
