### ISSUE TITLE
OCL Roadmap and Deliverables Submission Procedure for DS

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#304]
Link to roadmap document: https://docs.google.com/document/d/1VBrH4oUM6QDnGLsV5rSrs63zfcj__tXhgo3vnWeWmLs/edit#heading=h.k2hetpm48rme

**Comment by paynejd** [comment]
Resources to support this:
* Spreadsheet with Work Plan: https://docs.google.com/spreadsheets/d/1iR5xsNVW5M7qbffc5B5wUiYc5Uk0Ju0H62HmlnOkhvs/edit#gid=123326958
* OCL Maturity Assessment: https://docs.google.com/spreadsheets/d/1g8p6o_0YtFCzxEefvRWsgcoNTHvr7ZDGpJDcSRCldsM/edit#gid=0

**Comment by aprilcurrier** [comment]
Submitted to DS on Sept 29

**Comment by aprilcurrier** [comment]
the September 30 deliverables the DS DSMR award below:

-	Detailed work plan – Link 
-	Technical Roadmap for development across OCL tools related to the work package – Link 
-	Documentation of kick-off – Link 
-	Documentation of progress on completed core OCL API Technology stack upgrades  - Link (Document), Link 1 (API Reference Documentation Evidence), Link 2 (API Code Documentation Evidence)
