### ISSUE TITLE
Testing for ocldev python3 upgrade

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#305]
@snyaggarwal upgraded ocldev for python3 and to maintain backwards compatibility with python 2.7. This ticket will capture testing activities by the OCL team.

**Comment by paynejd** [comment]
Next step is to get `pytest` working. Jon and Sunny to discuss on Wednesday.

**Comment by snyaggarwal** [comment]
pytest is passing now with python3 and python2.

Steps to test:
For python2 - 
1. virtualenv venv -p python2
2. source venv/bin/activate
3. pip install -r requirements.txt
4. pytest

For python3 - 
1. virtualenv venv -p python3
2. source venv/bin/activate
3. pip install -r requirements.txt
4. pytest

**Comment by snyaggarwal** [comment]
branch for this is `2to3`

**Comment by aprilcurrier** [comment]
Rolling over no work completed

**Comment by paynejd** [comment]
Completed testing - code is working as expected. Ran into one issue during installation: the `setuptools` package had an issue that required manually installing a version of setuptools <46, otherwise `pip3 install -r requirements.txt` would throw an error. I resolved by doing this:
```
virtualenv venv3 -p python3
source ./venv3/bin/activate
pip3 install setuptools==45
pip3 install -r requirements.txt
```

@snyaggarwal Is there an easy fix for this? Should we just specify the version number in `requirements.txt`?

**Comment by harpatel1** [comment]
90% complete on rollover.

**Comment by snyaggarwal** [comment]
setuptools is not required in requirements.txt. And I did not see this error while running things on local. Is it required for publishing the package to pypi?

**Comment by snyaggarwal** [comment]
This is fixed

**Comment by paynejd** [comment]
Thanks @sny! Are we ready to merge into master?

**Comment by snyaggarwal** [comment]
Yes.

**Comment by paynejd** [comment]
Merged!
