### ISSUE TITLE
Plan oclapi2 dev team testing

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#306]
@snyaggarwal is getting close to completing the oclapi2 upgrade. This ticket will capture activities by the team to support testing.

**Comment by paynejd** [comment]
Test bugs on oclapiv1 does not exist in colapi2
Migrate oclapi new changes to oclapi2
Bulk Import performance
CIEL dictionary
Test for Mandatory/Optional fields
Set up OpenMRS and PEPFAR client to point to oclapi2 in QA
Jon to run msp_metadata scripts to prepare PEPFAR content for import -- and to run import (tests ocldev2 and oclapi2 import)
Manual API testing
Example: what happens if there are 2 concepts with the same ID in a collection /orgs/:org/collections/:collection/concepts/:concept/

**Comment by aprilcurrier** [comment]
Rolling over to address follow-ups during next Sprint planning

**Comment by aprilcurrier** [comment]
This will occur once deployed to AWS.

**Comment by aprilcurrier** [comment]
Jon adding to Arch and Dev agenda for further discussion/work

**Comment by harpatel1** [comment]
Need to create specific tickets for this work.

**Comment by paynejd** [comment]
https://docs.google.com/document/d/1HhuRlbGFU_-0bDq_vXocwwodMw4GqEunFcI79mdcOyA/edit#heading=h.unkpp7np1sq3

**Comment by aprilcurrier** [comment]
Jon to create a timeline to review with the team

**Comment by aprilcurrier** [comment]
Expect to be complete next week

**Comment by aprilcurrier** [comment]
To discuss on tomorrows Dev call

**Comment by aprilcurrier** [comment]
Jon to create additional follow up tickets. May become an Epic
