### ISSUE TITLE
Setup Google Analytics for OCL Wordpress site

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#316]
This is fully integrated in Wordpress and we need to create a google analytics account with the admin@openconceptlab.org email address to make this happen.

**Comment by paynejd** [comment]
Done for my personal email. Next step is to link this with the admin@openconceptlab.org site.

**Comment by aprilcurrier** [comment]
tracking is enabled. Need to add a set of emails and think through tracking of analytics.

**Comment by paynejd** [comment]
Added admin@openconceptlab.org to the analytics account

**Comment by paynejd** [comment]
After changing the theme, we will need to set up tracking in Wordpress again.

**Comment by harpatel1** [comment]
80% complete on rollover.

**Comment by paynejd** [comment]
Tim added the API key to wordpress so traffic is now being tracked! will test to confirm
