### ISSUE TITLE
oclweb2 Refactor

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#319]

**Comment by maurya** [comment]
The estimate for the expected work is ~6-8 weeks. A more detailed list of changes in the following document.
https://docs.google.com/document/d/192q_eaaZFQDFpp-F0WVApHgoSggTCXqKD3wOoHgXPIA/edit
Actual “launch” consists of changing DNS to point to WordPress site - URL and subdomain for ocl web

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Should this be closed?

**Comment by jamlung-ri** [comment]
From my perspective, this can be closed. @paynejd Thoughts?

**Comment by paynejd** [comment]
Closed!
