### ISSUE TITLE
Create OCL infrastructure ansible scripts for AWS in new ocl infrastructure repo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#325]
- [X] Give ocl admin team access to `ocl_infrastructure` repo (Jon)
- [X] Create OCL admin AWS account (Jon)
- [ ] Write OCL infrastructure Ansible scripts (Sunny)

**Comment by paynejd** [comment]
@snyaggarwal You now have access to the `ocl_infrastructure` repo and I sent credentials to sign into AWS account via Slack. Please let me know if anything else needed to support this process.

**Comment by aprilcurrier** [comment]
Duplicate of AWS work being completed by Rafal
