### ISSUE TITLE
Create Functionality Catalog and Templates

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#334]
Create a first draft of the catalog. This document will function as a list of options, common components, and templates for the Metadata Browser.

[Functionality Catalog and Templates](https://docs.google.com/document/d/1CvMUuANGeI9I5cnLtAN3OR4YcO4H3LJYWvaYkAfPcmE/edit)

**Comment by aprilcurrier** [comment]
Closing out will plan to have Joe work with Jon to present findings
