### ISSUE TITLE
Add "mappings_url" attribute to sources

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#34]
Based on REST API best practices, resources should contain URLs to all of their sub-resource endpoints. Sources are currently missing the `mappings_url` field. Verify that collections already have this attribute. For example:

```
"mappings_url": "/orgs/WHO/sources/ICD-10/mappings/"
```

**Comment by paynejd** [comment]
@snyaggarwal can you verify that this behavior is addressed in oclapi2?

**Comment by snyaggarwal** [comment]
Added in oclapi2
