### ISSUE TITLE
CIEL Mockup for Metadata Browser

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#345]
Using metadata browser components, mockup a display for CIEL as if it were configured by an OCL Browser configuration file.

**Comment by jamlung-ri** [comment]
A first draft at a CIEL mockup has been created, although some refinement and finishing touches are required to complete it. Another next step is to specify a mockup "configuration" for the CIEL mockup to bridge the gap between the Template/Functionality Catalog and the mockup.

**Comment by harpatel1** [comment]
90% complete on rollover.

**Comment by jamlung-ri** [comment]
A first draft of this is complete and is ready for internal feedback.

**Comment by jamlung-ri** [comment]
Jon to review this: https://framer.com/share/Metadata-Clearinghouse--onB59TV7OytQ2Urr6McM?highlights=0

**Comment by aprilcurrier** [comment]
Joe to create additional metadata browser mockup review
