### ISSUE TITLE
Designing the common components and their content across Wordpress and oclweb

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#352]
- [ ] Menu and submenu structure - define common Header and Footer (both content and style)
- [ ] Identify where to integrate search

**Comment by paynejd** [comment]
What does it mean to provide access to the OCL Web Authoring Interface in the OCL Wordpress site:
* Search bar in the header - this simply submits the text entered via an HTML form to the search address, eg: `https://openconceptlab.org/?q=my-search-criteria-here`
* A menu item to navigate to the hosted instance of OCL -- this is just a link

Optional:
* Slider on the home page that highlights the hosted instance of OCL --- "Search the OCL Metadata Clearinghouse" with a search box and/or a link
* Create a dedicated informational page about the hosted instance of OCL that also includes links to it

I think the biggest challenge here is "branding" -- OCL has always been synonymous with our hosted instance, but moving forward OCL means "community", "open source tools" and our "hosted instance", so we run the risk of confusing users who come to our website expecting to start searching terminology. We need to decide if now is the time to begin branding the hosted instance as the "Metadata Clearinghouse"

**Comment by maurya** [comment]
Metadata Clearinghouse to go to the link -  openconceptlab.org (currently)
About OCL - to have the language of the Metadata Clearinghouse
Also See if this can be added to the FAQ's

**Comment by harpatel1** [comment]
60% complete on rollover.

**Comment by maurya** [comment]
Metadataclearing house content page, sign in page, search bar to head to Openconceptlab search added to the website

**Comment by aprilcurrier** [comment]
To be continued with the design
