### ISSUE TITLE
OCL Documentation

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#354]
https://docs.google.com/spreadsheets/d/13OBb_lnajroEx8h8yJEk0E88RNf_OwPz67TJtcj3JM4/edit#gid=1081423030

- [ ] Review the list in Dev call
- [ ] Create  tickets for approved list in the issues

### 9/18/20

> - Working through CIEL import documentation
> -- Importing CIEL into OCL 
> -- Tix- being tracked in CIEL Epic 
> - CSV Import functionality Documentation
> -- @maurya will work on next week
> - DevOps documentation
> -- Encompassing technical docs we are working towards. Tix in repo. 
> - Work with OCL for OpenMRS squad to document their use case
> -- @maurya  is reaching out. Not getting much traction so will work with Burke. 
> -- Have gotten one presentation and am looking for updated documentation.

**Comment by aprilcurrier** [comment]
## Prioritizing ##

FAQ/Getting started
Content loading

**Comment by aprilcurrier** [comment]
Improve community support - document help desk approach; streamline community forums; implement separate OCL community/marketing site (e.g. wordpress/github pages); add landing page for devs describing how to contribute/policies/etc.; publicly post development roadmap and user documentation; implement policy for and refresh technical and API documentation

Create a framework draft
document help desk approach
streamline community forums
implement separate OCL community/marketing site (e.g. wordpress/github pages)
add landing page for devs describing how to contribute/policies/etc.
publicly post development roadmap and user documentation
implement policy for and refresh technical and API documentation
