### ISSUE TITLE
Community review of OCLweb2 

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#355]
Goal: Redevelop what we have in a new code base - React js Material UI and add a small set of improvements.

- [ ] Identify key stakeholders from OpenMRS, PEPFAR, Apelon, Ethiopia, Malawi, WHO, OpenHIE, and define the best strategy to get feedback from them.
- [ ] Do a community engagement to see if there are any features that are  needed

**Comment by aprilcurrier** [comment]
Will need a plan around this.

**Comment by paynejd** [comment]
We've been doing a lot of this passively rather than thru a larger solicited feedback session. Reduced the level of effort and closing
