### ISSUE TITLE
Implement ocldev features to import an OclExport via OCL bulk importer

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#356]
Update ocldev to convert an export of a repo version to a resource list that can be imported by the OCL bulk importer -- including the repo itself, the version, and all resources. `ocldev.OclExport.to_resource_list` (https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclexport.py#L156) is already implemented, which returns all concepts/mappings, but mappings have `type` of `MappingVersion` and the repo and repo versions are missing. Also, resources may need to be "cleaned" so that attributes are all structured properly for the bulk importer.

Note that there is a bug in OCL exports in OCL API v1 where `type` is set to `MappingVersion` for all mappings (this is documented in #261), when it should be simply `Mapping`. We will handle this seamlessly in `ocldev.OclExport.to_resource_list` rather than fixing the bug in OCL API v1

**Comment by paynejd** [comment]
Plan: add a few optional params to this method that will do a few things:
* clean the resource attributes in preparation for bulk import
* change MappingVersion to Mapping (this is to address a bug in oclapi v1, and the code will be able to handle oclapi v2 as well)
* include the `Source` and `Source Version` resources

This requires that an org with the expected ID already exists

**Comment by paynejd** [comment]
Committed changes to `2to3` branch of `ocldev` repo and shared details with @snyaggarwal for testing

**Comment by harpatel1** [comment]
80% complete on rollover.

**Comment by aprilcurrier** [comment]
Need to extract out info related to course owner or collection we are exporting. @paynejd  and @snyaggarwal  to discuss.

**Comment by aprilcurrier** [comment]
@snyaggarwal  is there further work to do on this or should it be closed out?

**Comment by snyaggarwal** [comment]
This can be closed out. @paynejd will create a new card for mongo to postgres export-import one time script.
