### ISSUE TITLE
Create Website content for OpenMRS x OCL MVP

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#360]
Burke to work on creating content on OCL for OpenMRS that will be included I the new OCL website. 
Include feature list of OpenMRS MVP with screenshot  and narrative 
Burke to share what is created with Community team

**Comment by aprilcurrier** [comment]
@kaalcumm Hi is anything else needed from Burke on this page currently?

**Comment by kaalcumm** [comment]
@aprilcurrier It appears we have all the content indicated on the sitemap and nothing appears to be incomplete. I have a few notes in the feedback document (under Content for the WP site) for general strategy for the page.

**Comment by aprilcurrier** [comment]
Complete per comment above closing ticket
