### ISSUE TITLE
Website Launch marketing 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#363]
Email or market when site goes live (what groups do you want to let know? How will we communicate?)

**Comment by jburnsthomas** [comment]
Major user groups as well as funders and partners. Think we should ask Jon if there are certain organizations he knows of and then we can figure out was method of communication is best.

- **Someone Interested in OCL** -- interested in “marketing” info about OCL; home page should cater to this group
- **Terminology Consumers** -- largest group of users who want to search/browse terminology published by others; maybe somewhat technical or clinical (analyst skills); primary interest in OCL is terminology published in the Metadata Browser; home page should also cater to this group
- **Terminologists/Administrators** -- smaller set of highly technical users who want to access TS or admin tools; technical docs; updating terminology in the Authoring Interface; configuring the presentation of their terminology in the Metadata Browser (administrative); this group should have some type of “dashboard” available when they have logged into the site; the home page should provide access to the user’s dashboard, but doesn’t need to highlight much more than that
- **Developers **-OCL Implementers & integrators, OCL core contributor
-**Funders** - Digital Square
_**Partnes** - Regenstrief, Apelon
