### ISSUE TITLE
OCL Journey Mapping - Draft Starting Document

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#369]
Mapping out the different stakeholders and their paths from getting started with OCL to having a working terminology service in place.

[Starting document](https://docs.google.com/document/d/1sEXWysXVAfgA4Z3qlxs5FlCxrfxu5iHEjL2iVHHi3Oc/edit#)

**Comment by jamlung-ri** [comment]
An example of one of these journey maps is available here. More journey maps can be created after planning out with others.

https://docs.google.com/presentation/d/11USGD0sfsnyfvNEJmmYEdoyoHm96YQXFfNZfHxayHUo/edit#slide=id.g9a43e2a46b_0_0

**Comment by aprilcurrier** [comment]
Next steps to review Journey mappings with the broader group prior to drafting.

**Comment by jamlung-ri** [comment]
Journey mapping work has continued, with an additional journey map being created, along with a "Terminology Management Cycle". The first draft of all of these journey maps should be completed in the next sprint, at which point more communuity feedback can be obtained.
