### ISSUE TITLE
ICD and Clearinghouse Mockup for Metadata Browser - Create Wireframes

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#370]
Follow-up from #329 - Draft ICD Mockups in wireframing software Framer, using React components where possible.

**Comment by aprilcurrier** [comment]
@jamlung-ri  any update here?

**Comment by jamlung-ri** [comment]
Initial wireframes are completed, although I need a little bit of help with the search feature. Wireframes can be accessed [here](framer.com/share/Metadata-Clearinghouse--onB59TV7OytQ2Urr6McM/gaA2Wq1I2?fullscreen=1&highlights=0) or from the Metadata Clearinghouse wireframe.

**Comment by aprilcurrier** [comment]
Will review this information with Jon next week and create additional ticket(s) as appropriate.
