### ISSUE TITLE
OCLAPI2 | Collection concept conflicting resource get

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#371]
In oclapi2 GET /collections/:collection/concepts/:concept/ is supported. 
If multiple concepts (from different sources) with the same mnemonic are added in a collection then above API needs to have means to resolve conflicts.

Expected behavior:
Given a collection has multiple concepts with the same mnemonics.

1. GET /collections/:collection/concepts/:concept/
    Response: 409

2. GET /collections/:collection/concepts/:concept/?uri=concept-uri
    Response: 200

**Comment by snyaggarwal** [comment]
@paynejd this is implemented in oclapi2. Let me know if anything needs to change

**Comment by paynejd** [comment]
Example request:
```
GET /collections/:collection/concepts/:concept/?uri=/orgs/CIEL/sources/CIEL/concepts/1394/
```
