### ISSUE TITLE
Global Search - Sort resources other than concepts not working

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#372]
Right now there is no way to sort on anything by anything except concepts.

**Comment by snyaggarwal** [comment]
https://github.com/OpenConceptLab/ocl_web/pull/345 fixes this.

**Comment by paynejd** [comment]
@snyaggarwal - did you already fix this for oclweb v1? and assuming you will also implement this in oclweb2?

**Comment by snyaggarwal** [comment]
yes this is fixed in v1
