### ISSUE TITLE
Plan permissions for oclapi2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#373]
User types to consider:
* Anonymous
* Authenticated
* Superuser - django user model; user that should be able to do everything
* Staff - django user model; someone helping to manage OCL
* `ocl_admin` - oclapi2 creates this as a superuser
* `admin` - ocl_web creates this account when launched
* `root` - ocl_web creates this account when launched
* demo user

Gathering requirements here: https://docs.google.com/document/d/1exxJWRdLlAKbsfTA6njd8L1aiSIRBQ5CCkSznmfwZHo/edit

**Comment by paynejd** [comment]
See also: #78

**Comment by snyaggarwal** [comment]
see also #203

**Comment by paynejd** [comment]
Refer to #139 for some older permissions issues in oclapi1/oclweb1
