### ISSUE TITLE
Integrate Bamboo with Slack

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#374]
This is supported in both systems, just need to set it up

**Comment by paynejd** [comment]
@maurya - would you be able to help out with the bamboo/slack integration? This would allow us to get a notification of build status after committing code without having to sign in to bamboo to track it

**Comment by maurya** [comment]
There is no direct integration for Slack and Bamboo as Slack doesn't support XMPP protocol that Bamboo uses https://confluence.atlassian.com/bamkb/using-slack-for-bamboo-notifications-940217744.html. 

One possible solution is using  an app for bamboo  - https://marketplace.atlassian.com/apps/1213289/slack-notifications-for-bamboo?hosting=server&tab=overview that can send notifications to Slack.

**Comment by maurya** [comment]
ITSM-1237 created in OpenMRS helpdesk to add the application to bamboo

**Comment by maurya** [comment]
50% completed rollover

**Comment by maurya** [comment]
75% completed and rolling over - Got feedback from OpenMRS team that the plugin has been installed, will test and confirm

**Comment by maurya** [comment]
integration with two deployments `ocl api 2` and `ocl web 2` in `ocl-dev` slack channel for testing. Will add all other deployments after monitoring builds for a couple of days

**Comment by maurya** [comment]
Configured all OCL project bamboo builds with `ocl_builds` slack channel
