### ISSUE TITLE
Add Slack Notifications for Bamboo to ci.openmrs.org

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#375]
@bmamlin and @rkorytkowski --

Is it possible to install the Slack Notifications for Bamboo widget into ci.openmrs.org?

https://marketplace.atlassian.com/apps/1213289/slack-notifications-for-bamboo?hosting=server&tab=overview

**Comment by bmamlin** [comment]
Now that we're migrating to AWS, is this still needed?
