### ISSUE TITLE
Embed OCL Release Notes in Technical Documentation Page 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#377]
![image](https://user-images.githubusercontent.com/58441201/94045644-b9f8bb00-fd9d-11ea-8c70-c32060fd276a.png)

**Comment by maurya** [comment]
Added to the 10/08 community planning call. To confirm if we plan to directly post the release notes to the page.

**Comment by maurya** [comment]
To be added as a link under documentation

**Comment by aprilcurrier** [comment]
No longer relevant closing
