### ISSUE TITLE
Remove like buttons

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#378]
![image](https://user-images.githubusercontent.com/58441201/94047739-84a19c80-fda0-11ea-9822-2548d3ec8deb.png)

Throughout the site, there are hanging like buttons at the bottom of the pages 

- [ ] Documentation > End user 
- [ ] Documentation > Latest Release Notes 
- [ ] OCL Tools
- [ ] OCL Tools > Terminology Service 
- [ ] OCL Tools > Metadata Browser 
- [ ] OCL Tools > Authoring Interface 

etc.

**Comment by maurya** [comment]
Done.
