### ISSUE TITLE
Add ability to filter search results by "updatedSince" parameter in the UI

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#38]
Could use a text box with a very simple javascript date selector for this. Refer to the API documentation for the required format of the date when sent to the API.

**Comment by paynejd** [comment]
FYI @snyaggarwal

**Comment by aprilcurrier** [comment]
Can only be tested once the deployment has occurred for OCL Web2

**Comment by aprilcurrier** [comment]
Waiting to import content. WebUI

**Comment by paynejd** [comment]
This works as expected based on requirements, however users are typically more concerned with the business revision date (which is a new manually set field of a source/collection version) rather than the specific resource updated timestamp. I'll close this ticket out and create a new ticket in the backlog to support this new feature.
