### ISSUE TITLE
CSV import documentation

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#380]

**Comment by maurya** [comment]
20% done on rollover

**Comment by aprilcurrier** [comment]
imported into Spinix needs further refinement. Maurya to define further refinement in next sprint. Rolling over.

**Comment by aprilcurrier** [comment]
- [ ] Reach out to MSF team to see if they have a sample spreadsheet and instructions.

**Comment by maurya** [comment]
Reached out to MSF team twice - no response.  

@paynejd is going to talk with @bmamlin and Grace from OpenMRS to see if they have any update

**Comment by aprilcurrier** [comment]
Need to set up working time to work on in-house

**Comment by maurya** [comment]
api.qa.aws.openconceptlab.org 

Follow - https://docs.openconceptlab.org/en/latest/oclapi/technical/csvimport.html 
Run CSV import and create the technical documentation
And have different spreadsheets to demonstrate functionality.

2 simple examples:
Add/update concepts & mappings for an existing source
( The listed example)Load all resources — org + source + concepts/mappings + collection + references + source/collection versions

Output:

- 2 example CSV google sheets
- Updated wiki page
Outline:

- Overview
- Example running from API (to be implemented)
- Example running from Python — this allows you to work with the import as JSON before loading
- Use case 1: Simple use case of adding concepts/mappings to existing source
- Use case 2: Advanced use case — loading a complete set of starter content
- CSV Import Reference — description of syntax, each resource type, and their columns

https://github.com/OpenConceptLab/ocldev/blob/2b81580fd84faf14524c796be7f1a1c7ca1a35c2/ocldev/oclcsvtojsonconverter.py#L764 
cc: @paynejd

**Comment by maurya** [comment]
Got requirements identified in Sprint 1, will be completed in Sprint 2

**Comment by maurya** [comment]
Completed and sent to Jon for review at https://docs.openconceptlab.org/en/latest/oclapi/technical/csvimport.html

**Comment by paynejd** [comment]
looks great! Made a few minor updates and we'll continue to revise as part of our documentation work. Thanks @maurya !
