### ISSUE TITLE
Review OCL Community site metadata content and make suggestions 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#382]

**Comment by jamlung-ri** [comment]
![image](https://user-images.githubusercontent.com/55999682/94143905-75712c00-fe3e-11ea-9329-f314f37781c9.png)

Good content here, but it needs something about how users can access the data dictionaries via APIs so that their systems are always using the most up-to-date dictionaries.

Also, does the API support editing concepts and mappings? That's new to me but I might just not be aware of it.

**Comment by jamlung-ri** [comment]
![image](https://user-images.githubusercontent.com/55999682/94144567-4effc080-fe3f-11ea-8c7f-8fd87f9005b2.png)

There seems to be a random search bar at the bottom of the homepage, just a heads up.

**Comment by jamlung-ri** [comment]
Thoughts about the top toolbar:

 - Home
    - May want to consider renaming this since I think it's more about the organizations that are involved. Maybe instead of "Featured Metadata Browser Domains", we change that to something about Participating Organizations, which will include WHO, PEPFAR, etc. and probably link to their respective content in OCL. 
 -  OCL Tools -> Metadata Browser
    - Love this page, but we'll need to change the slides since they're PEPFAR-branded. Not a super high priority, but just wanted to put that out there.
    - It also looks like this is really heavily MSP-focused, so we'll just want to make it more generic. The [Metadata Browser Starter Document](https://docs.google.com/document/d/1tgJb5nPxzsKefk0LhAfJ-kgM8TUo__c7CD-MzLSBymI/edit?usp=sharing) can give some insight into that.

Overall, I think the toolbar's organization is pretty good.

**Comment by aprilcurrier** [comment]
To include a broad overview on the Metadata browser as coming soon  page on the site as the MEtadata browser will not be available until later on

**Comment by jamlung-ri** [comment]
>       * It also looks like this is really heavily MSP-focused, so we'll just want to make it more generic. The [Metadata Browser Starter Document](https://docs.google.com/document/d/1tgJb5nPxzsKefk0LhAfJ-kgM8TUo__c7CD-MzLSBymI/edit?usp=sharing) can give some insight into that.

Here is another slide deck (not finalized) that might be helpful with describing some Metadata Browser aspects: https://docs.google.com/presentation/d/1gATpxCHC7GOoXFQsYniu5VnSo4jgRlb3bLyTWWqO20I/edit

**Comment by paynejd** [comment]
We tackled this in other tickets -- closing out
