### ISSUE TITLE
Create webpage content content for Authoring Interface and Terminology Services 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#383]
- [ ] @paynejd  to gather  Screenshot, description and link (code, hosted version, any additional info)  for Authoring Interface 
- [ ] @paynejd  to gather Screenshot, description and link (code, hosted version, any additional info)  for  TS
- [ ] Load TS content into site
- [ ] Load AI content into site

**Comment by paynejd** [comment]
Started content for authoring interface

**Comment by harpatel1** [comment]
Initial content is included in website.
