### ISSUE TITLE
Publish public version of OCL Technical Roadmap on new marketing site

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#388]
To include graphics and very high-level information: 

Original Available at: 
https://docs.google.com/document/d/1VBrH4oUM6QDnGLsV5rSrs63zfcj__tXhgo3vnWeWmLs/edit#heading=h.k2hetpm48rme 

Deck slides 5 and 6: 

https://docs.google.com/presentation/d/11liOAi2ZidvDsndA1WAZWLBFmf9oZPxmuIGD7XdxF_4/edit#slide=id.g993ff0de5d_0_1

**Comment by aprilcurrier** [comment]
To work on OCL COmmunity Call

**Comment by paynejd** [comment]
See #158 for additional materials -- this was an older ticket

**Comment by aprilcurrier** [comment]
Link to the Document: https://docs.google.com/document/d/1dsD_PFnpqHip-cdAYBMA4YN5Ho9S4cmtlihsPPzeOLk/edit#

**Comment by paynejd** [comment]
Full draft of public 2021 OCL Roadmap is available here: https://docs.google.com/document/d/1E7-mzdjnokvoksMKnm_JR801H_5aFE8nMkanoI7QlDQ/edit#

This is now ready to be ported into the OCL wordpress site and shared for public comment.

As discussed, this presents milestones as planned during the first 6 months of 2021. We will fill in gaps over the coming weeks
