### ISSUE TITLE
AWS deployment for QA2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#393]
Overview of AWS approach -- this ticket just covers the QA deployment onto AWS:
- EC2:
  - 2x t4g.xlarge 4 CPU, 16 GB RAM 62 USD + 100 GB EBS storage 10 USD = 144 USD / month (for production and staging environments) in 2 different zones
  - 1x t4g.large 2 CPU, 8 GB RAM 30 USD + 50 GB EBS storage 5 USD = 35 USD / month (for QA and Demo environment)
  - ECS or Kubernetes (+72 USD / month)
- DB:
  - 2x t3.medium 2 CPUs 4GB RAM 50GB instances of RDS for PostgreSQL for production including one replica multi-zone 180 USD / month (3-yr upfront: 123 USD / month)
  - 1x t.3 small 2 CPUs 2GB RAM 50GB for staging (single-zone) 30 USD / month
  - PostgreSQL in a container for QA and demo (free)
- Amazon's Load Balancer for api and web 32 USD / month
- CloudFront for caching API and WEB?
- S3 for storage of exports and backups
- Note: The commitments can be 1 or 3 years with further divisions on payment schedule to be -- No upfront/Partial/All Upfront. Each combination varies in discount.

**Comment by aprilcurrier** [comment]
- To be completed: Need to deploy Web V2 and connect to API and Web to Bamboo

**Comment by paynejd** [comment]
Remaining steps:
* Update Bamboo plan
* Deploy FHIR (#433)
* Deploy MSP (#438)
* Update docker compose to support multiple workers and celery queues (see #122)

**Comment by aprilcurrier** [comment]
Aiming for completion next week

**Comment by rkorytkowski** [comment]
Remaining:
Deploy FHIR (#433)
Update docker compose to support multiple workers and celery queues (see #122)

**Comment by aprilcurrier** [comment]
follow up tix for staging and environment
