### ISSUE TITLE
OCL Community Site Feedback 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#396]
A place to capture feedback on the OCL website for future iterative changes

**Comment by jburnsthomas** [comment]
@aprilcurrier are you looking to feedback to be captured on the site or are you talking about tracking feedback changes?

**Comment by kaalcumm** [comment]
[Feedback Document](https://docs.google.com/document/d/1k8J02ABtooCYzISsGi8WmARQfNcihs10ST1wi2v4ki4/edit?usp=sharing) to share at 10/22 meeting. 

I have also made a few updates to the Site Map by categorizing more sections to indicate they need content created.
