### ISSUE TITLE
Concept Count in Collections

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#397]
I've seen a couple of strange issues related to the number of concepts being reported by the OCL API v1. Hopefully these can be fixed for v2.

Steps:

I created a collection (through the OCL for OpenMRS client) to which I added 4 custom concepts. I also added a mapping to a single CIEL concept, although two of my custom concepts map to this concept (one as the SAME AS, one as NARROWER THAN). Because of an issue in the OCL for OpenMRS client, this creates a reference to the CIEL concept, which adds it to my collection. That issue can be resolved on our end. The problem is that having this reference to a CIEL concept seems to cause some unexpected behaviour from the OCL API.

1. When I make a GET request to https://api.qa.openconceptlab.org/users/ibacher/collections/T/?verbose=true, I get back a response that says `"active_concepts": 5`. This is probably fine as there are 5 concepts in my concept source: 4 custom and 1 CIEL. However, the "references" block only contains 4 concepts (3 of my custom concepts and the CIEL concept), which is unexpected. The missing concept is my first custom concept which is one of the two concepts mapped to the CIEL concept.

2. When I view the collection in the OCL UI, I *only* see my 4 custom concepts. I do not see the imported reference to CIEL at all. When I pull the list of concepts in my collection (https://api.qa.openconceptlab.org/users/ibacher/collections/T/concepts) from the API, however, the CIEL concept is still listed there.

I haven't tested this against the v2 API.

**Comment by paynejd** [comment]
Thanks for reporting this @ibacher!
@bmamlin -- do we have a version of the OMRS client running against qa2? Can we test this there?

**Comment by aprilcurrier** [comment]
@bmamlin any further update here?

**Comment by aprilcurrier** [comment]
@bmamlin is this bug fixed in OCL API 2?

**Comment by aprilcurrier** [comment]
@snyaggarwal  is this complete?

**Comment by snyaggarwal** [comment]
This is working fine in oclapi2

**Comment by aprilcurrier** [comment]
@paynejd  can this be closed?

**Comment by aprilcurrier** [comment]
@bmamlin  can you confirm for OpenMRS client?

**Comment by aprilcurrier** [comment]
@bmamlin an update?

**Comment by aprilcurrier** [comment]
will be included in #466 and #503
