### ISSUE TITLE
Eliminate user accounts on the web side

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#40]
Web creates its own user accounts that mirror the API user accounts, which creates the possibility of the accounts lists getting out of sync. We should eliminate the web side user accounts and expose any necessary functionality needed to allow for user account creation, management, and authentication using API only

**Comment by paynejd** [comment]
This will be implemented as part of the oclweb2 refactor. FYI @snyaggarwal

**Comment by snyaggarwal** [comment]
@paynejd we can close this.
