### ISSUE TITLE
Level 3 Material Gathering and Discussion Facilitation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#401]
To ensure that the idea of "Level 3 Content" is well understood and that everyone is using the term the same, we need to bring together materials and hold discussions with OCL's partner organizations, the Data Exchange and Interoperability group, etc. The end goal of this is to understand exactly how OCL can support this, and possibly more importantly, what OCL will NOT support for Level 3 content.

Adding this ticket in mid-sprint since Jon and I have put a decent chunk of our time into this already.

**Comment by jamlung-ri** [comment]
We held a discussion in the Data Exchange and Interoperability Group call, which appears to have helped the group better understand the idea of Level 3, what materials sit in it, and what the next steps are with it.

**Comment by harpatel1** [comment]
35% complete on rollover.

**Comment by jamlung-ri** [comment]
Next steps:

- Level 3 Artifact gathering with PLM group
- Prepare for TS Community Call with Mike and Garrett
- Mike and Garrett speak on TS Community Call
- Host a follow-up discussion with Mike, Garrett, OCL team, Bryn Rhodes, Apelon, etc.
- Identify what roles OCL needs to play in Level 3

**Comment by jamlung-ri** [comment]
>     * Level 3 Artifact gathering with PLM group

This is currently taking place in [this slide deck](https://docs.google.com/presentation/d/1fdiYwvVwlA5j-MTAgnbrwYCLXiaqvl4fp3Vp4bZPAg0/edit), where Vlad and Jorge have helped us identify some of the L3 and L4 artifacts specfic to PEPFAR.

>     * Prepare for TS Community Call with Mike and Garrett
> 
>     * Mike and Garrett speak on TS Community Call
This was completed at the 21 October 2020 TS Call. Notes: https://wiki.ohie.org/display/resources/2020-10-21+Terminology+Service+Call 
>     * Host a follow-up discussion with Mike, Garrett, OCL team, Bryn Rhodes, Apelon, etc.
> 
>     * Identify what roles OCL needs to play in Level 3

These steps are still in progress.

**Comment by jamlung-ri** [comment]
Gathering further information here: https://docs.google.com/presentation/d/1fdiYwvVwlA5j-MTAgnbrwYCLXiaqvl4fp3Vp4bZPAg0/edit

**Comment by jamlung-ri** [comment]
A follow-up ticket for this has been created in #450.
