### ISSUE TITLE
Compile MER v2.5 Reference Indicators (FY21)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#403]
https://datim.zendesk.com/hc/article_attachments/360071630231/FY21_MER_2.5_Indicator_Reference_Guide.pdf

**Comment by aprilcurrier** [comment]
@jamlung-ri  to see if @miclcox  is able to assist wit this again this year.

**Comment by jamlung-ri** [comment]
Michelle has been informed and has started compiling the MER guidance in [this spreadsheet](https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit). The goal is to have this done by November 6th.

**Comment by jamlung-ri** [comment]
Michelle has finished compiling these. I will do a quick spot check on the spreadsheet, but this will be complete after that.

**Comment by paynejd** [comment]
Loading MER v2.5 Reference Indicators will be continued here:
https://github.com/pepfar-datim/DATIM-OCL/issues/821

Updating Key Updates/Changes will be continued in #449
