### ISSUE TITLE
Define requirements for common mapping model

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#408]
Using this to track requirements gathering for this -- see notes from Oct 2 architecture discussion: https://docs.google.com/document/d/157ChmfmYLGLEg_fO4cE7oMqtGpL4PchUkEhNfUUMxdo/edit#heading=h.czc0hkco3jwj

**Comment by bmamlin** [comment]
Per FHIR's [Coding](https://www.hl7.org/fhir/datatypes.html#Coding) datatype, a reference to a concept includes:
* Code System (uri)
* Version (optional version, if blank defaults to latest)
* Code
* Display (a display name, useful for the humans & to show the code to humans without having to lookup a display name)

Importantly, from FHIR documentation: "**If two codings have the same system, version and code then they have the same meaning**. If the version information is missing, or the system, version or the code elements differ, then how the codes are related can only be determined by consulting the definitions of the system(s) and any mappings available."

**Comment by aprilcurrier** [comment]
Have been continuing to discuss on Arch call

**Comment by paynejd** [comment]
Current model treats internal and external mappings differently, which means lots of things:
- Clients must implement additional logic to handle them as the OCL API expects
- It prevents a user from deleting content that someone else has mapped to or referenced in a collection
- If content is loaded that a user has made an “external” mapping to, the OCL API isn’t smart enough to know that the mapping should now be “internal” without posting an update to the mapping

![image](https://user-images.githubusercontent.com/1189689/99807565-ae134600-2b0d-11eb-9ef3-24f4cc609e3c.png)

**“Global sources”**
- Good “global source” management is important otherwise mappings will become a mess
- Potentially define a “global namespace” for canonical sources -- OCL team would curate this list but others can submit 

**Requirements**
- Must be able to support FHIR’s Using Codes
- Consistent representation of “internal” and “external” mappings, and OCL can provide additional information about those that are internal
  - Whether a mapping is internal/external should be based on a source’s property, not the mapping itself
- Both the “from” and “to” concepts should not have to be stored in OCL → ability to handle canonical URLs?
- Reducing restriction that sources must have an org (some would have an org and some not)
  - There are many sources that exist regardless of whether they have been published in OCL -- if OCL enumerated these external sources, we could provide additional lookup, validation, etc.
  - If at all possible, we would want to be able to have more information available about a source regardless of whether an organization has been created to “own” it
  - The rights to update information about these sources would probably fall on the OCL administrators
- Mappings should not have to change when new content is imported, ie by using canonical URI
- The owner of a source should be able to delete it even if others have mapped to or referenced it

**Comment by paynejd** [comment]
MVP goals:
* Support FHIR round 1
  * Support specifying version of a CodeSystem/ValueSet in a mapping
* Move toward dropping internal/external, incl. support for referring to CodeSystems/ValueSets using canonical url
* MVP approach should not introduce breaking changes

MVP+ goals:
* Support FHIR round 2 - full CRUD for ConceptMaps, plus introducing lots of new FHIR capabilities

**Comment by aprilcurrier** [comment]
To be discussed on Arch call

**Comment by paynejd** [comment]
**FHIR Concept Maps**
* Goal:
  * Support a common way to work with both internal & external mappings
  * Support mappings that point to specific source versions (FHIR)
  * Support for mappings that point to canonical URLs and that point to codes that are not defined in OCL (FHIR)
  * Maintain (and deprecate) current approach for internal/external mappings
* Requirements:
  * To create, POST:
    * from_source_url, to_source_url (both required) - Version-less or versioned URL; must exist in OCL (confirm this); must support 3 URL types, resolved in this order:
      * Canonical URL (eg http://loinc.org) - this corresponds with the new `source.canonical_url` field
      * OCL on FHIR URL:
        * Relative (/orgs/Regenstrief/CodeSystem/LOINC/)
        * Absolute (https://fhir.openconceptlab.org/orgs/Regenstrief/CodeSystem/LOINC/)
      * OCL API URL:
        * Relative (/orgs/Regenstrief/sources/LOINC/)
        * Absolute (https://api.openconceptlab.org/orgs/Regenstrief/sources/LOINC/)
    * from_concept_code, to_concept_code (both required) - Does not have to exist in OCL (what if it should?)
    * from_concept_name, to_concept_name (both optional) - OCL will populate with default display name if none provided (do this on creation or dynamically when requesting?)
  * 
  * from
  *  and default "version-less" mappings to resolve to HEAD
  * Remove requirement that from_concept is defined in OCL
  * Remove requirement that from_source or to_source 
* Questions:
  * Do we support mappings that point to Code Systems not defined anywhere in OCL?


**Canonical Repositories**
* Definition: A `canonical repository` is a placeholder for a source/codeSystem or collection/valueSet that is shared across OCL with a recognized canonical URL but with no designated "maintainer"/owner in OCL
* Requirements:
  * Allow source or collection to be defined without an owner --- or that has a shared reserved "Canonical" org as an owner with special permissions
  * A Canonical repo must have its `source type` or `collection type` set to "Canonical"
* Questions:
  * Are canonical repositories required to be empty? Or should OCL allow non-empty canonical repos that are more than just placeholders?
  * Who can create, update, delete a canonical repo? Assuming OCL administrators only?
  * Can non-admin users propose a new canonical source or updates to an existing one?
  * Is there a use case for an org to create its own "canonical repo" that is "owned" by that org?

**Comment by paynejd** [comment]
These fields are always available regardless of the concepts/sources:
```
{
    "type": "Mapping",
    "id": "daa51dc0-d72f-4345-a780-e7d484e671c7",
    "uuid": "5fc8bb03b9e0f10001a97fb8",
    "external_id": "a9d93ffjjen9dnfekd9",
    "retired": "false",

    "source": "loinc2",
    "owner": "Regenstrief",
    "owner_type": "Organization",
    "owner_url": "/orgs/Regenstrief/",
    "url": "/orgs/Regenstrief/sources/loinc2/mappings/8d492ee0-c2cc-11de-8d13-0010c6dffd0f/",
    "version_url": "/orgs/Regenstrief/sources/loinc2/mappings/8d492ee0-c2cc-11de-8d13-0010c6dffd0f/1/",

    "map_type": "Same As",
    "extras": {},

    "created_on": "2008-01-14T04:33:35Z",
    "created_by": "johndoe",
    "updated_on": "2008-02-18T09:10:16Z",
    "updated_by": "johndoe",
}
```

NOTE: The rules below use examples with only the `from_source` and `from_concept`, but the rules apply to both the `from` and `to` concepts and sources.

Rules:
1. If a version-less `from_concept_url` is provided, then OCL converts it to `from_source_url` and `from_concept_code`:
* Input:
```
"from_concept_url": "/orgs/PEPFAR-Test8/sources/MER/concepts/ndREbLzsBVY/"
```
* Validation:

* What is saved?
```
"from_source_url": "/orgs/PEPFAR-Test8/sources/MER/concepts/",
"from_concept_code": "ndREbLzsBVY"
```

2. If a versioned `from_concept_url` is provided, then OCL converts it to `from_source_url`, `from_source_version`, and `from_concept_code`:
* Input:
  * Option A:
```
"from_concept_url": "/orgs/PEPFAR-Test8/sources/MER/v2.4/concepts/ndREbLzsBVY/"
```
  * Option B:
```
"from_concept_url": "/orgs/PEPFAR-Test8/sources/MER/concepts/ndREbLzsBVY/"
"from_source_version": "v2.4"
```
* What is saved?
```
"from_source_url": "/orgs/PEPFAR-Test8/sources/MER/concepts/",
"from_source_version": "v2.4",
"from_concept_code": "ndREbLzsBVY"
```

3. Using canonical URL
* Input:
```
"from_source_url": "http://loinc.org"
"from_concept_code": "32700-7"
```
```
"from_source_url": "http://loinc.org|2.56"
"from_concept_code": "32700-7"
```
```
"from_source_url": "http://loinc.org"
"from_source_version": "2.56"
"from_concept_code": "32700-7"
```
* What is saved?
```
"from_source_url": "http://loinc.org",
"from_source_version": "2.56",
"from_concept_code": "32700-7"
```

4. Using OID or other IDs in the future? Example:
```
"from_source_url": "2.16.840.1.113883.6.1",
"from_source_version": "2.56",
"from_concept_code": "32700-7"
```



* Validation options
  * Source in OCL
  * Source version in OCL
  * Concept code in OCL
  * Concept name in OCL





The from/to sources & concepts may or may not be stored in OCL.
```
{
    "from_source_owner": "Regenstrief",
    "from_source_owner_type": "Organization",
    "from_source_name": "loinc2",
    "from_source_url": "/orgs/Regenstrief/sources/loinc2/",
    "from_source_version": "2.56",
    "from_source_canonical_url": "http://loinc.org",

    "from_concept_code": "32700-7",
    "from_concept_name": "Malarial Smear",
    "from_concept_url": "/orgs/Regenstrief/sources/loinc2/concepts/32700-7/",
    "from_concept": {},

    "to_source_owner": "WHO",
    "to_source_owner_type": "Organization",
    "to_source_name": "ICPC-2",
    "to_source_url": "/orgs/WHO/sources/ICPC-2/",
    "to_source_version": "v11",
    "to_source_canonical_url": "http://who.int/ICPC-2",

    "to_concept_code": "A73",
    "to_concept_name": "Malaria",
    "to_concept_url": "/orgs/WHO/sources/ICPC-2/concepts/A73/",
    "to_concept": {}
}
```

**Comment by paynejd** [comment]
When a mapping is created/updated, it should save what the user included in the body of the request with only some processing and normalization. For example, `from_concept_url` would be split into `from_source_url`, `from_concept_code` and possibly `from_source_version`.

It should also perform a lookup of the from/to sources and from/to concepts and save references to these objects if they are defined in OCL (eg `_from_source`, `_from_concept`, `_to_source`, `_to_concept`). If an object reference is not stored in a mapping, it cannot be assumed that the referenced object does not exist in OCL. A lookup must be performed in order to determine that.

We may also want to store key values from the sources and concepts with the mapping, such as the source relative and canonical URLs, the resolved source versions (eg a version-less `from_source_url` may have resolved to version `2.56` at the time it was created), preferred concept names, along with a timestamp of when the from/to URLs were resolved. These stored values must remain separate from the values provided by the user, unless a user states that they want the core mapping fields to be auto-populated, for example, through a user interface prompt.

**Comment by aprilcurrier** [comment]
75% complete upon rollover

**Comment by paynejd** [comment]
Scenarios:
* Flexible from/to_source_urls can support OCL relative URL, canonical URL, and in the future other IDs (like OIDs)
* "typed" from/to_source_url and from/to_source_canonical_url

----

1. Normalize input fields to `from_source_url`, `from_source_version`, `from_concept_code`, and `from_concept_name` and `to_source_url`, `to_source_version`, `to_concept_code`, and `to_concept_name` -- these are what is saved in OCL
    * Input format may be:
        * Version-less `from_source_url` as relative or canonical URL; `from_concept_code`; (optional) `from_source_version`; (optional) `from_concept_name`
        * Versioned `from_source_url` as relative or canonical URL; `from_concept_code`; (optional) `from_concept_name`
        * Version-less `from_concept_url` as relative URL (canonical not supported); (optional) `from_source_version`; (optional) `from_concept_name`
        * Versioned `from_concept_url` as relative URL (canonical not supported); (optional) `from_concept_name`
    * Saved format:
        * `from_source_url` - version-less relative or canonical URL (whatever the user submitted)
        * `from_concept_code` - whatever the user submitted
        * `from_source_version` - if the user submitted a version (otherwise `None`)
        * `from_concept_name` - if the user submitted a concept name (otherwise `None`)
    * Questions:
        * If a canonical URL is defined for a source, does OCL replace a relative from_source_url with a canonical form?
            * JP: No, because relative URL means "source that exists at this location in OCL regardless of how else it is identified". That is different from canonical URL, which means "source that is identified by a particular URI regardless of whether or where it lives in OCL"
            * JP: Users should be warned in OCL web that if they use relative URLs, that if a source is deleted or replaced with an entirely different source, then their mappings will possibly have different meaning or become invalid
            * JP: Provide URL parameter to auto-replace relative source URLs with canonicals? We expect that this will be the primary way of referencing sources in the future
        * Should OCL instead require separate fields for relative and canonical URLs? (eg `from_source_url` and `from_source_canonical_url`)
2. Lookup and save object references for the from/to sources and concepts saved in OCL
3. When requested, optionally return from/to sources/concepts and generate remaining fields for backwards compatibility (most generated fields will be deprecated)
    * New request URL params:
        * `lookupConcepts`, `lookupFromConcept`, `lookupToConcept` - `false` (default) or `true`; if `true`, OCL populates `from_concept`/`to_concept` fields with the details of the concept, or `None` if the reference cannot be resolved
        * `lookupSources`, `lookupFromSource`, `lookupToSource` - `false` (default) or `true`; if `true`, OCL populates `from_source`/`to_source` fields with the details of the source, or `None` if the reference cannot be resolved
    * Generated fields (to support backwards-compatibility):
        * `from_source_owner`, `to_source_owner`, `from_source_owner_type`, `to_source_owner_type` - these should be marked as deprecated; populated if the source is defined in OCL, otherwise empty string (`""`)
        * `from_source_name`, `to_source_name` - these should be marked as deprecated; populated by the source ID (not name!) if the source is defined in OCL, otherwise empty string (`""`)
        * `from_concept_name`, `to_concept_name` - Returns only the originally saved concept name; this field is no longer automatically populated by OCL; return empty string if nothing was saved with the mapping, because client systems may still expect this field to be present
        * `from_concept_url` - this field should be marked as deprecated; if `from_source_url` is a relative URL or if the `from_concept` is defined in OCL, then OCL can generate this field, otherwise the field is omitted
        * `to_concept_url` - this field should be marked as deprecated; if `to_concept` is defined in OCL, then this field must be populated, otherwise the field is omitted; note that `to_concept_url` is different than `from_concept_url` due to backwards-compatibility

Things to figure out:
* Still need to support queries
* Alignment between map_types in OCL and FHIR

What does OCL do that FHIR does not:
* Atomic handling of concepts and mappings (individual concepts and maps do not exist as entities in FHIR)

**Comment by snyaggarwal** [comment]
@paynejd Below is what I interpreted from all the above comments and is the direction that I am headed towards. Please let me know if I missed anything. Also, I need some clarity on some of the questions mentioned below, we can discuss this in the upcoming call:

1. from/to source/concept may or may not exists in OCL.
2. from/to source URL can be relative or canonical.
3. Mapping will be created after resolving:
    - `from_source_url`
    - `from_source_version` (optional)
    - `from_concept_code`
    - `to_source_url`
    - `to_source_version` (optional)
    - `to_concept_code`
4. Mapping creation will not resolve the following and will only save the user provided values (in both cases where concept exists or not in OCL):
    - `to_concept_name` (optional)
    - `from_concept_name` (optional)
5. On retrieval following will be resolved (considering the query params):
     - `from_source` using `from_source_version` and `from_source_url` (if absolute then it will search via canonical_url in sources?)
     - `to_source` using `to_source_version` and `to_source_url` (if absolute then it will search via canonical_url in sources)
     - `to_concept` using `to_source` (above) and `to_concept_code` 
     - `from_concept` using `from_source` (above) and `from_concept_code`
     
 Questions:
 1. Validations:
      - While creating a mapping we can just assign `from_source_url`, `from_source_version` and `from_concept_code` and `to_source_url`, `to_source_version` and `to_concept_code` from inputs without any need of validations. At the time of retrieval, we can try to resolve to/from source/concept relations if they exist. Is that ok?

Schema Changes:
1. Add fields from_source_url, from_source_version, from_concept_code, from_concept_name, to_source_url, to_source_version, all optional for now (to_concept_code &  to_concept_name are already there)
2. Data Migration -- Populate the following for existing mappings:
     - `from_source_url` -- from `from_source.uri`
     - `to_source_url` -- from `to_source.uri`
     - `from_source_version` --  all `latest` or `HEAD`?
     - `to_source_version` --  all `latest` or `HEAD`?
     -  `from_concept_code` -- from `from_concept.mnemonic`
     -  `from_concept_name` -- leave it empty or populate from `from_concept.display_name`?
     -  `to_concept_code` -- if empty from `to_concept.mnemonic`
     -  `to_concept_name` -- if empty leave it empty or populate from `to_concept.display_name`?
3. Drop `from_concept`, `to_concept` and `to_source` FK relations from Mapping.

**Comment by snyaggarwal** [comment]
@paynejd in addition to the last comment, following are additional things for performance reasons:
1. added `from_concept_name_resolved` and `to_concept_name_resolved` in response -- loads from from/to-concept relations
(will be adding more, if anything else comes up)

**Comment by paynejd** [comment]
Testing this functionality as part of testing the PEPFAR integration scripts against oclapi2 on AWS. Rolling over to continue in the next sprint.

**Comment by snyaggarwal** [comment]
@paynejd should we close this and create new tickets as feedback/bugs/missing-things ?
