### ISSUE TITLE
[OCLWeb2] Implement search

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#413]
Assumptions:
1. Keeping the layout and color schemes the same as v1

Features (New + Existing):
- [x] Search results in tabular format
- [x] Sorting on each table column
- [x] Search results updatedSince filter
- [x] Ability to change results per page (25/50/100)
- [ ] Table rows to expand inline (and collapse) to reveal more information
   - Concepts Tabs:
      - [x] versions
      - [ ] Mappings
   - Mapping Tabs:
      - [x] versions
      - [ ] others?
   - Source/Collections Tabs:
      - [x] versions
      - [ ] others?
   - Orgs/Users -- @paynejd do we need to expand/collapse these? If yes then what will be the information to show?

**Comment by paynejd** [comment]
Started some ideas below -- will complete after screenshots are posted

* Sources/Collections
  * Columns
  * Tabs
    * (?) Details - 
    * Versions
* Concepts:
  * Columns: 
  * Tabs:
    * (?) Details - Synonyms, Descriptions, Custom Attributes
    * Synonyms
    * Mappings
    * History
* Mappings
  * Columns
  * Tabs
    * History
* Orgs/Users
  * Columns
  * Tabs
    * Repositories

**Comment by snyaggarwal** [comment]
### Screenshots:
  Concepts (default search landing page):
      Columns:
         <img width="1438" alt="Screenshot 2020-10-28 at 11 04 47 AM" src="https://user-images.githubusercontent.com/1858162/97397727-f6c15000-190f-11eb-9e24-fc3787b40367.png">
      Expanded Row:   
      Versions:
         
<img width="1044" alt="Screenshot 2020-10-28 at 11 21 46 AM" src="https://user-images.githubusercontent.com/1858162/97397975-69323000-1910-11eb-930a-de8968fc23c7.png">
      Synonyms:

<img width="1035" alt="Screenshot 2020-10-28 at 11 22 00 AM" src="https://user-images.githubusercontent.com/1858162/97397774-0b9de380-1910-11eb-94d5-98350c243757.png">         
      Descriptions:

<img width="1055" alt="Screenshot 2020-10-28 at 11 22 08 AM" src="https://user-images.githubusercontent.com/1858162/97397771-0a6cb680-1910-11eb-8f26-958ce47d32b7.png">

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

  Mappings:
     Columns:
<img width="1416" alt="Screenshot 2020-10-28 at 11 27 23 AM" src="https://user-images.githubusercontent.com/1858162/97398243-dba31000-1910-11eb-8897-60f703c090bb.png">
     Expanded Row:
<img width="1436" alt="Screenshot 2020-10-28 at 11 28 28 AM" src="https://user-images.githubusercontent.com/1858162/97398302-f83f4800-1910-11eb-89d7-782fd4d392a5.png">

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

  Sources:
      Columns:
<img width="1421" alt="Screenshot 2020-10-28 at 11 30 59 AM" src="https://user-images.githubusercontent.com/1858162/97398471-50764a00-1911-11eb-82f5-07792716b9d9.png">
     Expanded Row:    Nothing yet!     

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

  Collections:
    Columns:
<img width="1429" alt="Screenshot 2020-10-28 at 11 33 13 AM" src="https://user-images.githubusercontent.com/1858162/97398540-6be15500-1911-11eb-852f-a2c2ef2d6870.png">
    
Expanded Row: Nothing Yet!

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

 Orgs:
      Columns:
<img width="1420" alt="Screenshot 2020-10-28 at 11 34 31 AM" src="https://user-images.githubusercontent.com/1858162/97398631-8f0c0480-1911-11eb-8ff4-16b47765f276.png">
      
Expanded Row: Nothing yet!

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

 Users:
     Columns:
<img width="1439" alt="Screenshot 2020-10-28 at 11 35 07 AM" src="https://user-images.githubusercontent.com/1858162/97398716-af3bc380-1911-11eb-90bb-fc1015a2c76a.png">
  Expanded Row: Nothing Yet!

**Comment by aprilcurrier** [comment]
@paynejd  to add more requirements

**Comment by paynejd** [comment]
## Mappings
* Columns
    * **Owner** (eg `user: admin` OR `org: OCL` -- using org/user icons as in oclweb1 to identify these without spelling it out
    * **Source** (instead of "Parent")
    * **From Concept**
    * **Map Type**
    * **To Concept**
    * **Release** - same as concept
    * Updated On
* Tabs
  * **History** - same as concept, should display mapping history alongside the source versions; key question that this tab should answer is "In which version of this source was this mapping first published?"

## Sources/Collections
* Columns
  * **Owner** - same as concept
  * **ID** - the source/collection mnemonic
  * **Name**
  * **Source/Collection Type**
* Tabs
  * **Summary** - source/collection description, and other core attributes
  * **Versions** - list of most recent source/collection versions, release dates, descriptions, etc

## Orgs/Users
* Columns
  * **ID**
  * **Name**
  * Created On
* Tabs
  * Repositories

**Comment by aprilcurrier** [comment]
Initial Implementation complete. New work to be continued in an additional ticket
