### ISSUE TITLE
Import CIEL Dec-2020 release

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#414]
Creating this in advance to track progress on the CIEL Nov-2020 import -- hoping to track all CIEL imports via tickets moving forward

**Comment by bmamlin** [comment]
CIEL v2020-11-30 was validated and successfully released on staging and production OCL environments on 8 Dec 2020. Andy expects to have another release to quickly follow, so we can leave this ticket open to track one more (imminent) Dec-2020 release.

**Comment by bmamlin** [comment]
CIEL v2020-12-18 was validated and successfully released on staging & production. Last week, we noticed that `precise` extras had not made it onto OCL and this was fixed. Staging has been updated, re-validated, and re-released. Production has updated, re-validated, and its re-release is almost done (not processing as expected; Slack message sent on ocl-dev channel for help getting the re-released version on production processed.
