### ISSUE TITLE
oclapi2 failing on request for concepts within a collection

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#415]
API 2 is failing with call for concepts within a collection when using the OCL for OpenMRS client. This request:

https://api.qa2.openconceptlab.org/users/burke/collections/burketest/concepts/?page=1&limit=10&q=*&sortAsc=id&timestamp=1603290338578&includeRetired=true

responds with a `500 Internal Server Error` ([full error message](https://pastebin.com/TMVfpsiU)). The corresponding call to API v1 works as expected, returning `200 OK` along with the requested list of concepts.

### Recreating the error
Simply clicking on the link above shows the error. It was discovered by:
1. Authenticating to [openmrs.qa2.openconceptlab.org](https://openmrs.qa2.openconceptlab.org)
2. Creating a dictionary
3. Clicking on the link to view the concepts for the new dictionary (page fails to render to the error above)

**Comment by snyaggarwal** [comment]
This is fixed. This error was due to changes in ElasticSearch Schema for making few fields sortable. Rebuilding schema fixed it.

**Comment by bmamlin** [comment]
Confirmed that it is working as expected now. Thanks @snyaggarwal!
