### ISSUE TITLE
oclapi2 error when creating a concept

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#416]
When trying to create my first concept using the OCL for OpenMRS client against API 2, I was unable to submit the form due to an error.

```
POST https://api.qa2.openconceptlab.org/users/burke/sources/burketest/concepts/
{
  "concept_class": "Test",
  "datatype": "N/A",
  "descriptions": [
    {
      "description": "Number of nose hairs per square millimeter",
      "locale": "en",
      "external_id": "1f6a9d78-d5eb-47fb-8d33-82cb4239165f",
      "locale_preferred": true
    }
  ],
  "external_id": "4627405f-00c9-46e3-85c2-c7f63d26b618",
  "id": "1",
  "names": [
    {
      "name": "Nose hair density",
      "locale": "en",
      "external_id": "f04cf4b0-fb5e-42af-a553-84dc1c7d8385",
      "locale_preferred": true,
      "name_type": "FULLY_SPECIFIED"
    }
  ],
  "retired": false,
  "extras": {}
}
```

Returns a `400 Bad Request` with:
```
{
  "descriptions": [
    {
      "description_type": [
        "This field is required."
      ]
    }
  ]
}
```

The same POST (differing only by UUIDs and source) succeeds on API v1.

Also, the error response seems to be formatted differently than API v1. For example, trying to create a concept with an existing OCL ID against API v1 returns a `400 Bad Request` with:
```
{
  "__all__": [
    "Concept with this Mnemonic and Parent id already exists."
  ]
}
```
If the error responses are going to be formatted differently in API v2 than they were in API v1, then we need to know, since the OCL for OpenMRS client parses these error responses to display the error to the user. In the example above (the error from API v2), the error shows up in the client as "[object Object]" (since the client is trying to display `{"description_type": ["This field is required."]}` as a string.

**Comment by snyaggarwal** [comment]
description_type (and name_type) is not mandatory now in v2. This was a bug.
The structure for success and error responses ideally should be the same, but due to changes in the Django framework, it may be slightly different. Having said that I have fixed this to return the same error format as v1, the only difference is the error message itself, hope that's ok.
With v2 now you will get error for duplicate concept as"
{
  "__all__": [
    "Concept ID must be unique within a source."
  ]
}

Checking in this, all of this will be available on QA2 soon

**Comment by bmamlin** [comment]
Confirmed to be fixed within OpenMRS for OCL client, so closing ticket. Thanks @snyaggarwal!
