### ISSUE TITLE
Add ability to copy the subscription URL for a source/collection

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#418]
The subscription URL for a repo is the version-less URL, eg:
* https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/

**Comment by snyaggarwal** [comment]
@paynejd Should the subscription URL be the URL from web perspective like -- https://openconceptlab.org/orgs/CIEL/sources/CIEL/
or should it be from API perspective -- https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/ ?

**Comment by snyaggarwal** [comment]
Example implementation:
<img width="1421" alt="Screenshot 2020-11-02 at 10 22 45 PM" src="https://user-images.githubusercontent.com/1858162/97895677-1c0fed00-1d5a-11eb-9fdf-7a1df0917916.png">

**Comment by paynejd** [comment]
@snyaggarwal I think it's the API URL, so let's go with that for now.

Instead of a dedicated "copy URL"  button in the search results, I would think that we'd have a button on a source/collection details page that can grow to include a lot of additional functionality, like one of these: ![image](https://user-images.githubusercontent.com/1189689/97986420-aaf72680-1da7-11eb-9e80-8fd092e7318f.png)
