### ISSUE TITLE
Prepare list of content from all OCL environments that need to be migrated and re-imported

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#420]
Some content will be imported from scratch and some we will migrate the entire repository. Need to determine if there are repositories where we must maintain the interim resource updates or if we can ignore those during migration.

@snyaggarwal - could you outline the list of "starter content" that is imported into a new environment? Please include users too

**Comment by paynejd** [comment]
Discussed with Sunny- there is very little starter content in the repo, so we need to decide what it is, starting with the content under the OCL repo. Expect we will need to make a CSV of CIEL starter content as part of this.

**Comment by snyaggarwal** [comment]
currently in oclapi2:
1. lookup values
2. OCL org and ocladmin user (superuser)
3. OCLweb creates admin and root user on startup.

**Comment by aprilcurrier** [comment]
@paynejd  working on moving this forward

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski user passwords are transportable.
Tried following test:
1. Fired up oclapi and ocl_web (both v1)
2. Copied encrypted password from db for a user (with known password)
3. created a user in oclapi2 and assigned the same raw encrypted password from v1
4. logged in to oclweb2 with the unencrypted password and it was a success!

**Comment by aprilcurrier** [comment]
To be finished next week

**Comment by aprilcurrier** [comment]
50-75% complete upon rollover SUnny to review google doc and get sense of data that will not be apart of the imports

**Comment by jamlung-ri** [comment]
Rolling over to sprint 4

**Comment by paynejd** [comment]
Completed this list here:

https://docs.google.com/document/d/1Y2ahAGgZITA_f99fYYMuYFk_nmjWEyFb0Cbyt_pKxCE/edit#

**Comment by jamlung-ri** [comment]
This work is complete, and the work will be done in #412
