### ISSUE TITLE
FAQ on OCL website

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#422]
- [ ] Use FAQ created for Ethiopia as a starting point, 
will need help from Jon, Harsh and Rafal 
- [ ] What is OCL?
- [ ] How to contribute to OCL

 # Link to document- https://docs.google.com/document/d/1xImweb9V39pSeOkKYd3i8JB_f0KNcw-V/edit #

**Comment by aprilcurrier** [comment]
50% complete upon roll over

**Comment by aprilcurrier** [comment]
Presentation of initial draft given to OCL community call week of Nov 30. Additional comments from the team needed to complete.

**Comment by kepishelf** [comment]
Consolidated all team comments. Harsh and Maurya were asked to review .
see comments in Draft document - https://docs.google.com/document/d/1xImweb9V39pSeOkKYd3i8JB_f0KNcw-V/edit

**Comment by maurya** [comment]
@kepishelf I've reviewed and added comments for changes. Apart from the consolidated comments, looks good to me.

**Comment by aprilcurrier** [comment]
@kepishelf  is there an update here?

**Comment by aprilcurrier** [comment]
@kepishelf  is there an update here?

**Comment by aprilcurrier** [comment]
rolling over

**Comment by jamlung-ri** [comment]
Present this to community call on 18 Feb 2021

**Comment by jamlung-ri** [comment]
Working on this post-launch
