### ISSUE TITLE
Difference in verbose collection between API v1 and v2

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#432]
While testing the OCL for OpenMRS client against API v2, I discovered a difference in the response to

`GET /users/burke/collections/test/?verbose=true`

Here is how the responses differ:

```diff
-v1
+v2
 {
     "active_concepts": 2,
     "active_mappings": 0,
+    "canonical_url": null,
     "collection_type": "",
     "concepts_url": "/users/burke/collections/test/concepts/",
     "created_by": "burke",
     "created_on": "2020-10-30T12:00:53.489673Z",
-    "custom_resources_linked_source": "",
     "custom_validation_schema": "OpenMRS",
     "default_locale": "en",
     "description": "",
@@ -21,19 +21,7 @@
     "owner": "burke",
     "owner_type": "User",
     "owner_url": "/users/burke/",
-    "preferred_source": "CIEL",
     "public_access": "View",
-    "references": [
-        {
-            "expression": "/orgs/CIEL/sources/CIEL/concepts/test444/5f5fc10e529cc101a1964dca/",
-            "reference_type": "concepts"
-        },
-        {
-            "expression": "/users/burke/sources/test/concepts/3/5f925837529cc1006a45b844/",
-            "reference_type": "concepts"
-        }
-    ],
-    "repository_type": "Collection",
     "short_code": "test",
     "supported_locales": null,
     "type": "Collection",
@@ -41,6 +29,7 @@
     "updated_on": "2020-10-30T12:04:40.631658Z",
     "url": "/users/burke/collections/test/",
     "uuid": "1",
+    "version": "HEAD",
     "versions": 1,
     "versions_url": "/users/burke/collections/test/versions/",
     "website": ""
```

I assume the missing `preferred_source` is because CIEL doesn't exist on QA for API v2 right now, so can't be added as a preferred source in testing. I believe the primary issue for the client is the lack of the `references` property, which the OCL client uses to show information on its dictionary summary page (e.g., counts of concept & custom concepts).

**Comment by snyaggarwal** [comment]
custom_resources_linked_source, preferred_source, respository_type and references added in response.
They were missed.

**Comment by aprilcurrier** [comment]
Looking for confirmation from @bmamlin  to close

**Comment by bmamlin** [comment]
Thanks @snyaggarwal. It's closer; however, it looks like `references` isn't getting populated as expected.

`GET https://api.qa2.openconceptlab.org/users/burke/collections/test/?verbose=true`

```json
{
    "active_concepts": 2,
    "active_mappings": 0,
    "canonical_url": null,
    "collection_type": "",
    "concepts_url": "/users/burke/collections/test/concepts/",
    "created_by": "burke",
    "created_on": "2020-11-02T14:52:57.990478Z",
    "custom_resources_linked_source": "",
    "custom_validation_schema": "OpenMRS",
    "default_locale": "en",
    "description": "",
    "external_id": "2504088a-9f9a-4b6a-bcd5-6a2246a42129",
    "extras": {
        "source": "/users/burke/sources/test/"
    },
    "full_name": "Test",
    "id": "test",
    "mappings_url": "/users/burke/collections/test/mappings/",
    "name": "Test",
    "owner": "burke",
    "owner_type": "User",
    "owner_url": "/users/burke/",
    "preferred_source": "CIEL",
    "public_access": "View",
    "references": [],
    "repository_type": "Collection",
    "short_code": "test",
    "supported_locales": null,
    "type": "Collection",
    "updated_by": "burke",
    "updated_on": "2020-11-02T15:46:19.913064Z",
    "url": "/users/burke/collections/test/",
    "uuid": "1",
    "version": "HEAD",
    "versions": 1,
    "versions_url": "/users/burke/collections/test/versions/",
    "website": ""
}
``` 

Specifically, here, I would expect `references` to be populated with the two custom concepts I created, but I'm getting an empty list.

**Comment by paynejd** [comment]
In v1, references being returned when requesting a collection was actually
a bug. References should only be returned when explicitly requested using
the "includeReferences=true" parameter or with the references endpoint, eg "
/users/burke/collections/test/references/".

**Comment by snyaggarwal** [comment]
Yes @paynejd is right -- this works -- https://api.qa2.openconceptlab.org/users/burke/collections/test/?verbose=true&includeReferences=true

**Comment by paynejd** [comment]
@snyaggarwal - Does this query also work? `/users/burke/collections/test/references/`

**Comment by snyaggarwal** [comment]
yes /references/ works as well
