### ISSUE TITLE
Deploy FHIR app in QA

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#433]
https://github.com/OpenConceptLab/oclfhir

**Comment by aprilcurrier** [comment]
Rafal is working on it

**Comment by rkorytkowski** [comment]
Hit an issue with DB connection. I should address it today.

**Comment by rkorytkowski** [comment]
Done: https://fhir.qa2.aws.openconceptlab.org/fhir/CodeSystem
Made a couple of adjustments in FHIR: https://github.com/OpenConceptLab/oclfhir/commit/75c8c18c5fa65681dd5ba8b348a5adab2d128efb
and
https://github.com/OpenConceptLab/oclfhir/commit/045490b17881b6231eea507a5c388c86e86f2519

**Comment by rkorytkowski** [comment]
@harpatel1 please verify if it works as expected

**Comment by paynejd** [comment]
Confirmed that this is deployed - further work to take place in separate tickets
