### ISSUE TITLE
Deploy staging/production to AWS

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#434]
Refer to #393 for deployment plan in QA

Deploy FHIR to staging only

**Comment by aprilcurrier** [comment]
Expect to be completed sprint beginning week of 11/30

**Comment by aprilcurrier** [comment]
Memory issues in QA have pushed out this timeline

**Comment by aprilcurrier** [comment]
Deployment is complete need  - 90% complete upon rollover

**Comment by aprilcurrier** [comment]
Will continue this work (clustering and health check)  in an additional ticket
