### ISSUE TITLE
Import CIEL into AWS QA2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#437]
we need some data in qa2.aws to test out the API - we can load via the bulk import api, save a snapshot, and restore for new deployments

**Comment by aprilcurrier** [comment]
@snyaggarwal  running PEPFAR import today. In QA now small dictionary with 107 concepts in QA now, CIEL with 9k mappings

**Comment by aprilcurrier** [comment]
This is part of fixing large bulk imports. rolling over

**Comment by aprilcurrier** [comment]
Has been tested on local
