### ISSUE TITLE
Fix source export on QA2

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#443]
Exporting a source on QA2 does not work. There's no sing of failure in logs, yet nothing is written to the S3 bucket. An exception must be eaten.

**Comment by snyaggarwal** [comment]
This is fixed.

**Comment by snyaggarwal** [comment]
@rkorytkowski Can we close this?

**Comment by aprilcurrier** [comment]
@rkorytkowski  please review and close if appropriate

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski can this be closed?

**Comment by paynejd** [comment]
fixed!
