### ISSUE TITLE
Add core fields in OCL api

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#445]
We need to add core attributes in OCL to make it FHIR compliant. 

See mapping document here:
https://docs.google.com/spreadsheets/d/1lumg1d8FX5SPN0mYqZyqfTAvJdCQbngpcZ0FTB7P6bI/edit#gid=0

**Comment by harpatel1** [comment]
### Source
#### Round 1:

```
identifier - JSON
revision_date - Date
publisher - Text
contact - JSON
jurisdiction - JSON
purpose - Text
copyright - Text
```

#### Round 2:
```
experimental - boolean
case_sensitive - boolean
collection_canonical_url - Text
hierarchy_meaning - Text
compositional - boolean
version_needed - boolean
content_type - Text
supplements - Text
filters - JSON
properties - JSON
```

### Collection

#### Round 1
```
identifier - JSON
revision_date - Date
publisher - Text
contact - JSON
jurisdiction - JSON
purpose - Text
copyright - Text
immutable - boolean
```

#### Round 2
`experimental - boolean`

**Comment by paynejd** [comment]
@harpatel1 - could you add your suggestion for if/how each field should be indexed? eg. which should be individually indexed? available as facets? included in full text search?

**Comment by snyaggarwal** [comment]
@harpatel1 Added all the round 1 fields. Please verify.

**Comment by harpatel1** [comment]
I have verified fields for round 1.
