### ISSUE TITLE
Prepare WHO Core/FP/STI Code System Import

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#446]
Prepare WHO Extended Code System from Core, FP, and STI implementation guides for import into OCL.

Import Spreadsheet: https://docs.google.com/spreadsheets/d/1Llweofs4DLhDTA2Ea71p8jDuDwed5rQ1Eyh_XgtdZwM/edit

IGs:
- Core: http://build.fhir.org/ig/who-int/core/
- FP: http://build.fhir.org/ig/who-int/fp-cds/index.html
- STI: http://build.fhir.org/ig/who-int/sti-cds/index.html

**Comment by paynejd** [comment]
Next steps:
* @paynejd to review/revise
* @paynejd & @jamlung-ri to document approach and gaps
* @paynejd to convert to JSON

@jamlung-ri other next steps for this task?

**Comment by jamlung-ri** [comment]
> 
> 
> Next steps:
> 
>     * @paynejd to review/revise
> 
>     * @paynejd & @jamlung-ri to document approach and gaps
> 
>     * @paynejd to convert to JSON
> 
> 
> @jamlung-ri other next steps for this task?

None from me, so long as the documentation in the spreadsheet is correct and adequately detailed. There will likely be a follow-up ticket for the actual import of this content, so I think that'll put us in good shape.
