### ISSUE TITLE
Implement custom attribute searching in oclapi2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#448]
oclapi v1 implementation of custom attribute searching was completed in this ticket: https://github.com/OpenConceptLab/ocl_issues/issues/39

This functionality is not well documented currently, but we'll capture full requirements here: https://github.com/OpenConceptLab/oclapi/wiki/Custom-Attribute-Filters

Need input from @rkorytkowski on oclapi1 implementation

@jamlung-ri could you add into this ticket any queries in MSP that use `extras` filters so that we can make sure they are supported in oclapi2? You should be able to search the MSP code base for `extras` to find these

@paynejd to add related queries from other PEPFAR integration scripts

**Comment by paynejd** [comment]
There are 3 files in the `ocl_datim` repo that use `extras` queries:

```
/ocl_datim/common.py:
   50          'limit': '0',
   51          'verbose': 'true',
   52:         'extras__datim_moh_object': 'true'
   53      }
   54      if period_filter:
   55:         request_params['extras__datim_moh_period'] = ','.join(period_filter)
   56      if country_code_filter:
   57:         request_params['extras__datim_moh_country_code'] = ','.join(country_code_filter)

/ocl_datim/getqmaprepos.py:
   60:     url_all_orgs = '%s/orgs/?limit=0&verbose=true&extras__qmap_org=true' % ocl_env_url

/ocl_datim/oclPassThroughRequests.py:
   75:     mohCodelistsDetailsURL = '%s/orgs/PEPFAR/sources/?extras__datim_moh_codelist=true&verbose=true' % (ocl_env_url)
```

**Comment by jamlung-ri** [comment]
Here is a list of the MSP queries that contain `extras__` :

- extras__source
- extras__codelists__id
- extras__resultTarget
- extras__Reporting+frequency
- extras__indicator
- extras__pepfarSupportType
- extras__numeratorDenominator
- extras__Applicable+Periods
- extras__indicatorGroups__id

@paynejd Is this what you're looking for? If you need more context or anything, let me know!

**Comment by paynejd** [comment]
* Does an attribute exist?
* Case sensitivity
* Spaces in a value/search criteria (eg `extras__Applicable+Periods="FY18 19" FY17`)
* Space in the attribute name (eg `extras__Applicable+Periods`)

Changed from `__` to `.`
Changed `!=` to `=!`

**Comment by snyaggarwal** [comment]
# Below works:

### Attribute Exists:
`/sources/?extras.exists=datim_moh_country_code` # single attr exists
`/sources/?extras.exists=datim_moh_country_code,datim_moh_period` # multiple attrs exists
`/sources/?extras.exists=datim_moh_country_code,datim_moh_period&extras.datim_moh_object=false` # multiple attrs exists with extra attr value search

### Space in attribute name:
`/sources/?extras.foo bar=foobar` 
`/sources/?extras.foo+bar=foobar` 
`/sources/?extras.exists=foo bar`
`/sources/?extras.exists=foo bar,datim_moh_country_code`

### Space in attribute value/search criteria
`/sources/?extras.foo bar=foo bar foo` # will find extras["foo bar"] = "foo" or "foo bar" and similar

**Comment by aprilcurrier** [comment]
Jon to capture on the wiki continued in #471

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri 

For exact search:
`/orgs/PEPFAR-Test10/sources/MER/concepts/?extras.exact.Reporting+frequency=Annually`

Let me know if the syntax needs to be changed
