### ISSUE TITLE
FHIR Terminology Bindings - Plan how OCL will publish

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#455]
In WHO Smart Guidelines implementation guides (IGs) and other FHIR IGs, there are references to value sets and code systems that were NOT explicitly defined for the IG, but instead have their own purpose and are simply reused in the IGs. In some cases, OCL will need to have this content loaded.

Three ways we have currently identified:

Approach | Pros | Cons
-- | -- | --
Import the   entire Code System (eg ICD10)
Import only   specific codes referenced
Don't load   anything at all (eg due to licensing) and simply make external references

The pros and cons of each approach need to be filled out before making decisions.

**Comment by paynejd** [comment]
No work to be done here -- reference vocab publication is handled in other tickets
