### ISSUE TITLE
Compile a proposed list of value sets to import from HL7

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#457]
Need to determine criteria for the code systems and value sets that we will import.

Short term:
- [x] Terminology bindings from WHO IG (Joe)
- [x] Referenced by PLM resources (Jon)

Medium to long term
- [x] Normative value sets from FHIR? (Medium term?)
- [ ] All? (Long term?) (https://www.hl7.org/fhir/terminologies-systems.html, https://www.hl7.org/fhir/terminologies-valuesets.html)

Once this is complete, next steps are to work on HL7 content modeling and loading.

**Comment by jamlung-ri** [comment]
Terminology bindings for WHO Smart Guidelines and for PLM have been compiled in this spreadsheet in the "Pivot" tab. https://docs.google.com/spreadsheets/d/1g1PfEkwmiK7fg3Okn2npZa7_f_LM5mz8xj8X8eurb8o/edit?usp=sharing

This includes terminology bindings found in the WHO [Core](http://build.fhir.org/ig/who-int/core/), [FP](http://build.fhir.org/ig/who-int/fp-cds/index.html), and [STI](http://build.fhir.org/ig/who-int/sti-cds/index.html) profiles, along with bindings from the [PLMProfile](https://github.com/pepfar-datim/PLM/tree/master/PLMProfile) folder in GitHub.

**Comment by jamlung-ri** [comment]
Next step - List out normative FHIR value sets

**Comment by jamlung-ri** [comment]
Some minor changes are needed but this is otherwise complete. Follow-up needed: repeat this process with Code Systems.

**Comment by aprilcurrier** [comment]
to be continued in an additional ticket
