### ISSUE TITLE
Summarize all new features/breaking changes in oclapi2/oclweb2 & infrastructure as release notes and change log

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#463]
We need to compile a complete list of new features in oclapi2, oclweb2 and our new AWS infrastructure. 
cc @snyaggarwal @rkorytkowski @harpatel1 @maurya @bmamlin

@aprilcurrier - if you could put together a list of completed tickets from ZenHub related to these epics, that may be a huge help

Bullet points can be brief, but we want to cover as much of the new features as possible.

#### oclapi2
* OpenAPI Swagger support (https://api.qa2.aws.openconceptlab.org/swagger)
* Redoc automatic code documentation (https://api.qa2.aws.openconceptlab.org/redoc)
* Ability to retrieve concepts and mappings in a collection by ID (eg /orgs/:org/collections/:collection/concepts/:concept). All sub-endpoints have been implemented as well (eg /mappings, /names, /extras). Note that if two resources in the collection have the same ID, a `409 Conflict` is returned.
#### OCL infrastructure
* Implemented Elastic Search (ES) as a replacement to Solr

## Breaking Changes
* New mapping model
* Search for custom attributes changed to support Elastic Search - full details here: https://github.com/OpenConceptLab/oclapi/wiki/Custom-Attribute-Filters
  * Use `.` instead of `__` for nested queries (eg `extras.my_custom_attribute`)
  * Use `=!` instead of `!=` for negation queries
* `references` are no longer returned when retrieving a collection, unless they are explicitly requested (eg. `/orgs/MyOrg/collections/MyCollection/?includeReferences=true`) or at the references endpoint (eg. `/orgs/MyOrg/collections/MyCollection/references/`)
* `url` and `version_url` changed for some some responses, eg mappings (see #65) -- **FULLY DESCRIBE THIS HERE**
* `limit=0` is disabled for most/all requests -- **FULLY DESCRIBE THIS HERE**

**Comment by aprilcurrier** [comment]
Doc with Closed Tix https://docs.google.com/document/d/1H-mD6N0Tg2NEW_hzEM_F4X5V3i5irefPS_jpNwsgizA/edit

**Comment by snyaggarwal** [comment]
### New features so far:
1. API for listing mappings for a concept version #16 
2. Delete cached exports when deleting repos/repo versions/orgs #101 
3. Async org delete (to handle large org delete, 504 timeout) #136 
4. Allow staff or org member to delete their org #168 
5. Collection concept conflicting resource get #371 
6. Add canonical_url field to source and collection #419 
7. Update API root to respond with something meaningful #442 
8. Auto-redirect repository "export" endpoint when using the "latest" keyword #57 
9. Add ability to copy the subscription URL for a source/collection #418

**Comment by paynejd** [comment]
API for uploading/updating user, org, source, collection logos
New bulk import endpoints for direct file upload
Entirely refactored bulk import processing engine that bypasses the UI

**Comment by snyaggarwal** [comment]
GET `/users/<str:username/?includeSubscribedOrgs=true`
will also include user's subscribed orgs in response.

**Comment by snyaggarwal** [comment]
Description field added in Org. Currently its not searchable (just like Source/Collection)

**Comment by paynejd** [comment]
#408 introduces major modifications to mapping model

**Comment by aprilcurrier** [comment]
Sunny to update this  week- gap of API

**Comment by snyaggarwal** [comment]
`GET /references/` # also returns id of reference, needed for Web2.

**Comment by snyaggarwal** [comment]
Breaking/New Change in Source/Collection:
1. (breaking) In verbose responses --  `versions, active_concepts, active_mappings` are not going to be returned.
2. (new) `/summary/` or `?includeSummary=true&verbose=true` will return `versions, active_concepts, active_mappings`

API support (same for collections):
`GET /orgs/PEPFAR-Test10/sources/?verbose=true&includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/summary/`
`GET /orgs/PEPFAR-Test10/sources/MER/versions/?verbose=true&includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/v1/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/v1/summary/`
`GET /orgs/PEPFAR-Test10/sources/MER/latest/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/latest/summary/`

**Comment by aprilcurrier** [comment]
Will rollover keep tix until testing

**Comment by paynejd** [comment]
`extras.about` replaced with `text` (in line FHIR) for orgs, sources, and collections

**Comment by paynejd** [comment]
* GET export returns 208 if processing is underway (formerly it was 204 or 200 depending on the request)
* Added API endpoints for indexing with its own namespace
* Health checks: https://api.qa.aws.openconceptlab.org/healthcheck/
* `extras.about` is now `text` to align with FHIR

**Comment by jamlung-ri** [comment]
Keep open until launch

**Comment by paynejd** [comment]
For mapping model:
?lookupConcepts=true for both from and to concepts
?lookupFromConcept=true for from concept only
?lookupToConcept=true for to concept only
?lookupSources=true for both from and to sources
?lookupFromSource=true for from source only
?lookupToSource=true for to source only

**Comment by snyaggarwal** [comment]
GET APIs for healthcheck:
_(all the APIs respond with a UI by default and by adding query `?format=json` or header `Accept: application/json` it will return json responses)_

- `/healthcheck` # Returns status of every service -- db(critical)/redis(critical)/es/redis/celery-queues
- `/healthcheck/db`
- `/healthcheck/redis`
- `/healthcheck/es`
- `/healthcheck/flower`
- `/healthcheck/celery` # Returns status of every celery queue -- default queue being the critical one.
- `/healthcheck/celery@default` # Returns status of every celery@default queue
- `/healthcheck/celery@concurrent` # Returns status of every celery@concurrent queue
- `/healthcheck/celery@bulk_import_0` # Returns status of every celery@bulk_import_0 queue
- `/healthcheck/celery@bulk_import_1` # Returns status of every celery@bulk_import_1 queue
- `/healthcheck/celery@bulk_import_2` # Returns status of every celery@bulk_import_2 queue
- `/healthcheck/celery@bulk_import_3` # Returns status of every celery@bulk_import_3 queue
- `/healthcheck/celery@bulk_import_root` # Returns status of every celery@bulk_import_root queue

**Comment by jamlung-ri** [comment]
Based on a quick scan of the MSP commits since December 2020, here are the breaking API changes that affected MSP between API v1 and v2.

Category | Description | Old Syntax | New Syntax
-- | -- | -- | --
Attribute name changes | Needed to change which attribute the MSP pointed towards | to_concept_name | to_concept_name_resolved
  |   | conceptClass= | concept_class=
Filtering | Quotations no longer used when specifying filters | conceptClass="Reference+Indicator" | concept_class=Reference+Indicator
  | Separation between extra attributes is now a period instead of two   underscores | extras__Applicable+Periods =FY20 | extras.Applicable+Periods=FY20
  | Spaces between characters in API queries must be represented by + | conceptClass="Reference Indicator" | concept_class=Reference+Indicator
  | OR logic used to use "+OR+" within quotes but now uses a comma   between values (no quotes) | datatype="Percentage"+OR+"Ratio" | datatype=Ratio,Percentage
Searching | q= parameter used to use quotes and +OR+ between multiple search terms   but now use +OR+ between values (no quotes) | q="AT1GyM3oaZd"+OR+"b6D2WY2Po5B" | q=qiVMjGimk0Y+OR+ld31ltXbC38
Limits | "limit=0" disabled | limit=0 | limit=999
Exact Match | Previously, exact matching was done by default, but now an exact   parameter is needed. (Not 100% sure about this) | extras.Reporting+frequency= | extras.exact.Reporting+frequency=

**Comment by snyaggarwal** [comment]
New -- Collection version export will also have references in JSON #605

**Comment by jamlung-ri** [comment]
Rolling over until launch

**Comment by snyaggarwal** [comment]
@paynejd Below is a comprehensive list after going through all the Tickets. Next, I will go through all the commits to list out anything missed:

### Changes
#### Fixes:
- Boolean URL parameters should properly handle "false" values and not activate #8
- Concept mappings disagreement depending on method of querying and wrong response headers #26 
- Concept name and description locale_preferred not saved on import when using boolean values #25
- Implement extras API endpoint for Organizations #30
- **(breaking)** Rename 3 camelCase source version fields to underscore_spaced #33 
- Fix duplicate set of source extras #35
- 500 error when attempting to retrieve concepts under a logged in user's collection #111
- Retrieving concepts from a collection's HEAD returns some previously removed concept references #115
- Facets returning incorrect counts #217
- Confusing error message when assigning duplicate OCL ID #309


#### Web2:
- Eliminate user accounts on the web side #40
- Support "extras" for the mapping resource #113
- Add ability to copy the subscription URL for a source/collection #418
- Basic Customization Features #498
- Configuration Interface for Orgs #524
- Customized Attribute Display on Source and Collection Tabs and Pages #525
- Develop concept comparison view in oclweb2 #500, #579 
- Basic Resource Download #529
- **(breaking)** OCL Default Landing Page. #539
- Captcha on Signup and Forgot Password. #554
- Additional Download Functionality #561
- Superuser and org owner can edit org membership  #573
- Source/Collection Version Exports #587
- Password Rules/Strength - Signup & Forgot Password #593
- Delete concepts/mappings directly from a collection #600

#### API2:
- Add "website" field to user object #42
- **(breaking)** Switch URL attributes for mappings #65 
- **(breaking)** API and UI should be consistent on requiring default_locale, supported_locales or full_name in source/collection #96
- Delete cached exports when deleting repos/repo versions/orgs #101
- Apply privacy rules to error message when deleting source with referenced content #103 
- Support "extras" for the mapping resource #113 
- 504 Gateway Timeout when deleting large org #136 
- Allow staff or org member to delete their org #168
- Add PUT support for in-place updates of orgs #215 
- Collection concept conflicting resource get #371
- New Mapping model #408
- Add canonical_url field to source and collection #419
- Update API root to respond with something meaningful #442
- Add core fields in OCL api #445
- Implement custom attribute searching in oclapi2 #448
- Source/Collection (initial) Summary -- https://github.com/OpenConceptLab/ocl_issues/issues/467#issuecomment-768138149
- Record Login time for a user. #493
- Multi-thread bulk imports in oclapi2 #502
- APIs for Source/Collection/Org UI Configurations -- #524, #498, #525 
- healthcheck/system-status #566
- Password Rules #593
- **(breaking)** Include references attribute in collection exports #605

**Comment by jamlung-ri** [comment]
Next step for this is to create a summary in a change log format and a release notes format

**Comment by paynejd** [comment]
Preparing formal release notes here: https://docs.google.com/document/d/1UBt74g7WQcG5sJqKqNWEa2ly6g_lNcIWoYz9cnexZR8/edit#

**Comment by snyaggarwal** [comment]
Another one on extras query syntax change -- https://github.com/OpenConceptLab/ocl_issues/issues/637#issuecomment-800911585

**Comment by jamlung-ri** [comment]
Moving over to next sprint since this document will continue being updated.

**Comment by snyaggarwal** [comment]
More updates;
**Web2:**
  - Mapping Details/listing -- indicators for concepts in or not in OCL -- #633 
  - Can Create new collection while adding selected concepts/mappings references -- #652 
  - Feedback Option -- #653 
  - **(breaking)** Removed mappings tab from concepts home (details)
  - OCL Server Switch option for OCL Staff/Admin users
  - FHIR Connector and CodeSystem support -- #659 
  - Source/Collection | FHIR fields added in UI -- #689 
  
**API2:**
  - Source/Collection | added customValidationSchema as facet -- #690 
  - users list can be filtered by isSuperuser/isAdmin/isStaff -- #693

**Comment by jamlung-ri** [comment]
Now that we have done soft launch, [this document](https://docs.google.com/document/d/1UBt74g7WQcG5sJqKqNWEa2ly6g_lNcIWoYz9cnexZR8/edit) (also linked above) needs to be available on docs.openconceptlab.org

**Comment by snyaggarwal** [comment]
New:
 - Ability to get concepts/mappings within a source that are or are not part of a collection - #728

**Comment by jamlung-ri** [comment]
This ticket could be open for a lifetime, so we should consider treating it differently. Let's keep it open for another sprint, but we should consider automating the changelog. A follow-up ticket will be made for that. #828 

Also, we need this to be more automated since we don't have a person/resource specifically for this. Currently, we can automate the changelog to make a list of changes needed for release. This would be a list of detailed commits.

**Comment by paynejd** [comment]
After all this time, we're shutting this ticket down so that we open up 2022 with a clean slate.
