### ISSUE TITLE
Initial OCL Web Design 

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#465]
Tim to work on the design of OCL website

**Comment by jburnsthomas** [comment]
Tim is working transition and build out branding docuemnt. This week he worked on loading Divi Builder into WordPress that will make editing content and working in the WP theme easier. There was a loading issue which he will need to do some research on. He also created a “child theme” that inherits the Hestia theme. Is on track to finish this initial set of work next week; homepage, a sub-page, header and footer design to give feedback. There will need to be a review, probably after Thanksgiving and then some back and forth when it comes to likes or dislikes. Jon is aware of all of this and we will do our best to match up with the release coming in Dec or Jan.

**Comment by aprilcurrier** [comment]
Tim's schedule has changed anticipating more work in the next sprint rolling over

**Comment by aprilcurrier** [comment]
Need to follow up later in the week

**Comment by aprilcurrier** [comment]
Initial design completed
