### ISSUE TITLE
Implement source/collection summary tab on their details page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#467]
Let's implement a source/collection summary tab on the source/collection details pages. Let's start with something simple that does not require significant effort to create. We can improve iteratively over time.
 
Here's a basic example from the CIEL dictionary that Andy Kanter recently presented:
![image](https://user-images.githubusercontent.com/1189689/99191793-0aa4e880-273d-11eb-9162-4994f75c528b.png)

Suggestions for where we start:
* Source/Collection Versions (Releases)
  * Counts of versions by released, retired, other
* Mappings (based on most recent release):
  * Counts grouped by map_type (from most recent release)
  * Counts grouped by to_source
* Concepts (based on most recent release):
  * Counts by class & datatype
  * Counts of concept names by locale and name_type
  * Counts of concept descriptions by locale and description_type

Note that these stats could potentially be cached for each source/collection version

**Comment by snyaggarwal** [comment]
1. (breaking) In verbose responses -- versions, active_concepts, active_mappings are not going to be returned.
2. (new) /summary/ or ?includeSummary=true&verbose=true will return versions, active_concepts, active_mappings

API support (same for collections):

`GET /orgs/PEPFAR-Test10/sources/?verbose=true&includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/summary/`
`GET /orgs/PEPFAR-Test10/sources/MER/versions/?verbose=true&includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/v1/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/v1/summary/`
`GET /orgs/PEPFAR-Test10/sources/MER/latest/?includeSummary=true`
`GET /orgs/PEPFAR-Test10/sources/MER/latest/summary/`

**Comment by snyaggarwal** [comment]
@paynejd Initial summary is live for quite some time now. Let's close this and create specific tickets on how to enhance it.
