### ISSUE TITLE
MOH OCL IMAP mediator status 404

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#477]
PH- Hi @Maurya when a country uploads a file in the Data Import app but the country has not submitted any mappings, a status code 404 should be returned from the ocl-imap meditator, but we are getting 500 instead.  Would you please have a look?
Response body
```
{
  "x-mediator-urn": "urn:mediator:openhim-mediator-authenticator",
  "status": "Failed",
  "response": {
    "status": 500,
    "headers": {
      "content-type": "application/json"
    },
    "body": {
      "status": "Error",
      "message": "404 Client Error: NOT FOUND for url: https://api.staging.openconceptlab.org/orgs/DATIM-MOH-VNM-FY20/sources/DATIM-Alignment-Indicators/versions/?limit=100",
      "type": "HTTPError"
    },
    "timestamp": "2020-11-18T18:42:09.464Z"
  }
}
```
MK - Hi @pinghuang, yes, I saw that earlier, it needs a mediator code change, I will update the mediator and deploy the changes to show the correct status code in test, but will need @chuq to run the ansible scripts in production once verified.

PH  - Would you please update test.geoalign first once fixed so I can test? Thanks Maurya
MK - @pinghuang, I’ve update the status code and deployed it in test.ohie.datim.org, please verify and confirm

Next Steps - 

- [ ] Get confirmation from Ping that fix is working in test
- [ ] Get Chuq to deploy in Production

**Comment by maurya** [comment]
fix updated in https://github.com/pepfar-datim/openhim-mediator-imap-import

**Comment by maurya** [comment]
Done but not clear if this will be installed in this iteration

**Comment by aprilcurrier** [comment]
Closing out to be continued in another ticket when this is deployed in March 2021
