### ISSUE TITLE
MOH FY 20 SSD data discrepency error 

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#478]
AS - @Jonathan Payne/ @Maurya Tom is unavailable and I am not sure if you can help me to resolve this issue. South Sudan reported that the mappings for PMTCT status did not change after they clicked the submit button. I tried clicking the submit button again to verify if I can submit it for them, but when I checked again, all the mappings disappeared. Can we reload the mappings back in OCL before they disappeared as a workaround to prevent the user from reentering them? Also, why were they deleted?

TZ - (I’m actually available :slightly_smiling_face:). @Jonathan Payne @Maurya @Alicia Smith: to clarify: the mappings aren’t deleted in the Indicator Mapping App, but it looks like they are not available in OCL because the current submission is blocking their availability: {"x-mediator-urn":"urn:mediator:openhim-mediator-authenticator","status":"Failed","response":{"status":409,"headers":{"content-type":"application/json"},"body":{"status":"Error","message":"Cannot export IMAP because an import is being processed for this country and period: DATIM-MOH-SSD-FY20","type":"ImapCountryLockedForPeriodError"},"timestamp":"2020-11-19T14:27:39.476Z"}} 

TZ - Hi @Jonathan Payne @Maurya: it looks like there’s a discrepancy between the last submission to OCL for South Sudan and what’s now in OCL.
The submission (https://ohie.datim4u.org/iol/#!/transactions/5fb6805770d49348476a8a5c) was successful and included this item for PMTCT_STAT:
{"DATIM_Indicator_ID":"PMTCT_STAT_N_MOH_Age_Sex_KnownNewPosNewNegRecNeg","MOH_Indicator_Name":"Known Positive 50+","DATIM_Indicator_Category":"PMTCT_STAT","MOH_Disag_ID":"","MOH_Indicator_ID":" PMTCT_STAT_KnownPositive_Female_50andMore","DATIM_Disag_ID":"Yv4sfg9PYy2","MOH_Disag_Name":"","DATIM_Disag_Name":"Known Positive | 50+ | Female","Operation":"ADD"}
When I check what’s coming back from OCL now (https://ohie.datim4u.org/iol/#!/transactions/5fb683e570d49348476a8d2b), this is missing, so the country’s mappings aren’t fully submitted

JP - Hi Tom and Alicia, catching up on this. Regarding the deletion, that is the expected behavior: when submitting an IMAP, the existing one is wiped before the new one is imported. It will appear again as soon as the import is complete. Does resubmitting the South Sudan IMAP fix the problem?

TZ - Hi Jon. Alicia already tried resubmitting (that’s the submission I’m referencing), so no it did not fix the issue
10:42
Also, with regards to the mappings being down, they were down for about 20 minutes following Alicia making the submission, so I guess we’re a bit surprised about the time delay
JP - Yeah it should take just a minute for an IMAP import — let me and Maurya look into this
TZ-  Sounds good. Thanks! I think the first priority would be to figure out why the one mapping item isn’t in OCL as that will prevent them from finishing their submission, but @Alicia Smith can weigh in if she disagrees

**Comment by paynejd** [comment]
Turns out that this error occurred due to a preceding space in MOH Indicator ID. The import works as expected if the space is removed. Tickets have been created to add validation to catch this in the mAppr app and in the OCL IMAP import script.
