### ISSUE TITLE
includeMappings & includeConcepts parameters do not work on collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#48]
Sources and collections should both allow you to see details of their concepts and mappings by using the `includeConcepts` and `includeMappings` parameters. For example, this works as expected at the `sources` endpoint:
```
https://api.staging.openconceptlab.org/orgs/MOH/sources/HMIS-Indicators/?includeMappings=true&includeConcepts=true
```
However, this is not working on the `collections` endpoint:
```
https://api.staging.openconceptlab.org/orgs/MOH/collections/HTS-TST-POSITIVE-F-15/?incluceMappings=true&includeConcepts=true
```
The above query is identical to what is contained in exports, so if this is not working it might also mean that the collections exports are not working -- please also check that.

**Comment by paynejd** [comment]
Did #53 fix this in collections as well as sources? If yes, this is a duplicate and we can close it out.

**Comment by rkorytkowski** [comment]
It needs to be addressed separately.

**Comment by rkorytkowski** [comment]
From what I see includeMappings and includeConcepts have never been implemented for the collections endpoint.

**Comment by paynejd** [comment]
Wow, I did not know that! LOE for implementing?

**Comment by rkorytkowski** [comment]
I've already started working on that. I'll complete it this week.
