### ISSUE TITLE
Explore Branding Requirements for Metadata Browser

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#480]
Features for custom branding of the Metadata Browser need to be documented so they can later be grouped and prioritized.

An initial document for this has been started [here](https://docs.google.com/document/d/1aquJzkRdtZ-OtDl_KfIk_RRs5yx32lJBalKqXWLuCac/edit).

**Comment by jamlung-ri** [comment]
Ideas and documentation can be found in the [notes of slide 5](https://docs.google.com/presentation/d/17MJ6qZ_LbdZv68GkEz_U3AS-QR2Fm_qwkCjOU6AuyvI/edit#slide=id.ga58a1ef761_0_6), along with some mockups elsewhere in the presentation.

**Comment by jamlung-ri** [comment]
Some basic configuration related to branding has been defined in #498. This ticket can probably be closed.

**Comment by aprilcurrier** [comment]
Tickets have been created for OCL branding
