### ISSUE TITLE
Testing and feedback on read-only portions of oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#488]
An initial version of all read-only portions of the new oclweb2 client have been implemented. We are ready for the team to begin testing and providing feedback. Testing and feedback should be comprehensive with respect to functionality, and we are also interested in collecting feedback on the site design, including theme, styles, layout, user experience etc.

**Comment by aprilcurrier** [comment]
Team to continue to review and  provide feedback

**Comment by aprilcurrier** [comment]
@harpatel1 @maurya  @bmamlin  to review and provide additional feedback

**Comment by snyaggarwal** [comment]
All the existing feedback for readonly portion in the [sheet](https://docs.google.com/document/d/16Ielv5lkuYcJZblPiLDcbi-2aU3NV3UXfpsWMyQcAzA/edit#) is done. Closing this.
