### ISSUE TITLE
AWS funding plan

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#489]
Currently AWS hosting is being funded out of pocket and not through any grant mechanism. This is a short-term strategy, and this ticket will be used to track progress on making a long-term decision.

**Comment by aprilcurrier** [comment]
No movement working to schedule meeting with Michelle rolling over

**Comment by aprilcurrier** [comment]
Jon working toward backchanneling. % unknown upon rollover

**Comment by paynejd** [comment]
This conversation is now moving forward actively in a separate thread -- closing this ticket
