### ISSUE TITLE
Record Login time for a user.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#493]
using django user model `last_login`

**Comment by aprilcurrier** [comment]
@snyaggarwal  any update here?

**Comment by snyaggarwal** [comment]
This is done. After testing we can close this

**Comment by aprilcurrier** [comment]
Who is responsible for testing?

**Comment by snyaggarwal** [comment]
@paynejd can you verify this and close.

**Comment by paynejd** [comment]
works as expected! closing out
