### ISSUE TITLE
OCLweb2: Basic Customization Features

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#498]
Jon and I started to put together a list of basic customization features so managing users can personalize and brand an OCL organization a little bit more. This list can be found here: https://docs.google.com/document/d/1kW1riEJfi-9wQAe3Q0HtEj0HRajRw-AtDumswV0XXRY/edit

The Immediate Changes section contains ideas that can be immediately implemented, while the section below is still being worked on by Jon and me. We will continue editing ideas in that lower section. 

Please feel free to make comments or ask questions, either in this ticket or in the Google doc.

**Comment by snyaggarwal** [comment]
The only one left from Immediate changes is -- Editable About page for Org/Source/Collection (Markup)
Rest are done and deployed on qa2

**Comment by jamlung-ri** [comment]
Thanks Sunny! Looking really good! I do have one question about the Pin feature. When signed in as ocladmin and looking at its user page, I can see pinned orgs and sources, which is great. But when signed out and looking at the ocladmin user page, I don't see the pins that were pinned by ocladmin. @snyaggarwal is this behavior expected?

@paynejd Correct me if I'm wrong, but I think the intention is that other users and non-signed-in users should be able to see the pins too. That would allow an organization to pin a source or collection for all users to see and quickly navigate to.

**Comment by snyaggarwal** [comment]
Ya, that was the intent, but I messed up the permissions, and that's why the pins dint load.
Fixed, soon to be deployed.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd  -- _“About” page in an OCL org/source/collection can be changed to give a longer description of the resource using markup"_
Currently "about" is picked from `extras.about` will it going to be the same or should we add a new field `about` in source/collection/org? Or will it use the existing `description` field?

**Comment by paynejd** [comment]
`description` should be reserved for a shorter description shown in the resource header. FHIR uses an attribute called `text`, intended to be used to provide a narrative description of a resource (see example https://www.hl7.org/fhir/codesystem-snomedct.json.html). We should plan to support the `text` attribute, but there may be separate use cases for `text` and `about`. How we approach this should be based on how we plan to support the Metadata Browser requirements. Let's have this discussion on a future dev call.

@harpatel1 was `text` already added as part of the FHIR round 1 core updates? if not, please include in the round 2 updates

**Comment by harpatel1** [comment]
@paynejd The field **text** was not included in round 1, I'll add it in round 2.

**Comment by aprilcurrier** [comment]
Sunny to continue work this upcoming week - rolling over

**Comment by aprilcurrier** [comment]
20% complete upon rollover

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Added about RTE in source/collection/org edit. It will reflect in about tab.
`text` field storing this markup at the API side for source/collection/org
Please review and close this ticket

**Comment by jamlung-ri** [comment]
I was able to edit the About page for OCL and for a [test source](https://qa.aws.openconceptlab.org/#/orgs/OCL/sources/test-sny-source1/). It seems to work well with the API, although I had a little trouble inputting text into the About text box (e.g. it did not respond to my backspace or return keys).

**Comment by snyaggarwal** [comment]
@jamlung-ri 
It should be hidden for all if it's empty. That's the feedback that I implemented. Looks like I broke it for orgs. Will fix that.
Also I will check on editing in rich text editor.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Fixed

**Comment by jamlung-ri** [comment]
Everything in [this list](https://docs.google.com/document/d/1kW1riEJfi-9wQAe3Q0HtEj0HRajRw-AtDumswV0XXRY/edit) has been completed!
