### ISSUE TITLE
Develop concept comparison view in oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#500]
Given two concepts, compare core fields, mappings, and custom attributes side-by-side, highlighting fields with differences. Should be available as an "Action" when 2 concepts are selected. In the future, we may expand this approach to also compare 2 resources of any type (eg 2 source versions, 2 collections, 2 mappings)

Should there be a corresponding API-level comparison? Or should this all happen in the UI?

See live example here (the design of this version is not great):
https://msp.qa.openconceptlab.org/indicators/compareIndicators?id1=rMs0q6Yaw0G&id2=RrBIFT7aQDh
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/64df33e9-0ebb-4eee-9f54-5778084cb202)

Nicer looking comparison mockup:
https://docs.google.com/presentation/d/1KPLnfOVTYL9xDJsv7JeTLwNRlNxaBpwyKBWUE_FmmUk/edit#slide=id.g8c7b17ef2b_1_0
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/8f0951b0-49a8-48f6-85bc-43ccf9849d9f)

**Comment by snyaggarwal** [comment]
@paynejd Deployed on qa2. Ready for feedback.

**Comment by snyaggarwal** [comment]
Added customization of fields for comparison, can include/exclude fields and order them for comparison

**Comment by paynejd** [comment]
This feature is working great - closing out. Additional work on comparing resources will be tracked in new tickets (eg #213)
