### ISSUE TITLE
Journey Map - Continue refining

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#501]

**Comment by jamlung-ri** [comment]
[TS Journey Maps](https://docs.google.com/presentation/d/11USGD0sfsnyfvNEJmmYEdoyoHm96YQXFfNZfHxayHUo/edit) have been updated. @paynejd and I need to review.

**Comment by aprilcurrier** [comment]
Next step to share with a broader audience

**Comment by aprilcurrier** [comment]
To continue in a future ticket
