### ISSUE TITLE
Multi-thread bulk imports in oclapi2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#502]
Code is in place to run bulk imports using multiple threads, but updates are needed (in environment config and oclapi2 code) to improve memory management.

**Comment by snyaggarwal** [comment]
Performance metrics --
https://docs.google.com/document/d/1m9YYXRqEZyLcKueqqxa5OrwiNTKjmVNJEOxd8-kvCJw/edit?usp=sharing

**Comment by snyaggarwal** [comment]
Tasks done:
1. Fixed - parallel tasks requeues after certain time interval (an hour) making redundant tasks and hence consuming memory exponentially -- celery.broker_transport_options.visibility_timeout
2. Infrastructure updates to add more resources (16GB/4CPU)
3. celery concurrent running with 30 prefork threads.
4. Tried pepfar 20K concepts with 10 threads finished in 10977.758521795273seconds (~3hours)
5. Add retrying of ES indexing job that fails for whatever reasons at most two times at an interval of 2 seconds

Ongoing:
1. CIEL import with 30 concurrent threads
2. PEPFAR import with 30 concurrent threads

**Comment by aprilcurrier** [comment]
Need to run on staging

**Comment by aprilcurrier** [comment]
Rolling over to be continued next sprint

**Comment by jamlung-ri** [comment]
Some work left in mapping import performance. ~80% complete upon rollover.

**Comment by snyaggarwal** [comment]
This is done. Closing this.
