### ISSUE TITLE
oclapi2 Testing for Launch

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#503]
Testing plan drafted; details in #306 -- plan is here:
https://docs.google.com/document/d/1HhuRlbGFU_-0bDq_vXocwwodMw4GqEunFcI79mdcOyA/edit#heading=h.unkpp7np1sq3

More tickets to be created under here

**Comment by paynejd** [comment]
See #96

**Comment by jamlung-ri** [comment]
Still active, need more tickets for this. Will be closed upon launch.

**Comment by paynejd** [comment]
We completed the OCL v2 soft launch over the weekend.

**MOH Alignment:** We have just finished verifying that MOH alignment is good in staging (the duplicates issue that we ran into on Friday is also addressed) — we’re ready for final integration testing on staging before pushing the new configuration to the production OpenHIM mediators. Maurya will coordinate next steps on this.
- [ ] MOH integration testing in staging environment
- [ ] Deploy updated `ocl_datim` code to production and update production mediator configuration
- [ ] Verify mediators in production

The DASH mediators/scripts, which are only in staging, are tested and working. However, @pinghuang will need to reload the DASH aggregation directives. Note DASH is not currently used in production
- [ ] Load DASH aggregation directives in staging
- [ ] ICF testing of DASH workflow

MSP is available in the new staging environment here: https://msp.staging.openconceptlab.org — we are doing some final testing here but it is in good shape
- [ ] Complete validation of `PEPFAR-Test10b` content in staging

**Comment by maurya** [comment]
MOH integration testing done by me, requested Puneet to start testing

**Comment by paynejd** [comment]
From @maurya: Updated mediators and ocl_datim code tested and prepped the configs to be ready for deployment. Next this needs to be approved by Vlad/Alicia to be deployed in Production. A ticket is currently assigned to them and I think it will get deployed in the next Tuesday deployment cycle
