### ISSUE TITLE
TS Role in L3 - Finalize Presentation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#504]
Following up from #450, finalize the [L3 slide deck](https://docs.google.com/presentation/d/1r3J_JpUvS5r2ur5WgsMZwRw3yuhnKhsC_q_oT3QuqFs/edit) and present to Data Exchange Community and others for feedback.

**Comment by jamlung-ri** [comment]
Associated with #508

**Comment by aprilcurrier** [comment]
Closing to be continued in a follow-up ticket
