### ISSUE TITLE
System Categorization Form - FISMA

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#510]
Link to form: https://docs.google.com/spreadsheets/d/17d7J-SBY7XwD0bGmhQO9W119xHtupRDi/edit#gid=570389155

**Comment by aprilcurrier** [comment]
No work completed upon rollover 0%

**Comment by jamlung-ri** [comment]
Meeting being set up for this with Alicia Smith

**Comment by paynejd** [comment]
Note: we also need AWS security documentation

**Comment by paynejd** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security.html
