### ISSUE TITLE
[OCLWEB2] 404/403/500 Generic Error Pages (or just handling)

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#513]
React Error Boundaries.
@paynejd oclweb v1 has an error message which is very generic "System encountered some error". We can make things more informative for the user, 404 and 500 can have their separate pages with some actions. React helps big in this way to setup umbrella handling for all components. So not much work. Any design in mind?

**Comment by snyaggarwal** [comment]
404 is done

**Comment by snyaggarwal** [comment]
Moved 404 to #656 and closed it

**Comment by snyaggarwal** [comment]
Added handling of 500s

**Comment by jamlung-ri** [comment]
Still need to test 403.

**Comment by snyaggarwal** [comment]
403 are handled in similar way as 500. If there is more needed on this will create new tickets. Closing this for now.
