### ISSUE TITLE
Requirements for round 2 of oclweb2 resource comparison

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#516]
* Save comparison configurations matching specific criteria
* Compare a concept's mappings
* Compare mappings

We want admins to be able to "save" multiple configurations for concept/mapping comparisons that meet certain rules (eg “concept_class=Diagnosis”) to meet our requirements for the Metadata Browser. If comparing two concepts from the same source, then the comparison tool should first check if that source has defined a default comparison configuration that matches the selected concepts.

For example,MSP would define a rule for like `from_concept.concept_class == "Data Element" && to_concept.concept_class == "Data Element"` (and maybe additional criteria for different sources, like DATIM, PDH/iHUB, etc.) to provide a custom layout.

**Comment by jamlung-ri** [comment]
Requirements for this are being compiled in [this slide deck](https://docs.google.com/presentation/d/1xdZvvgWAB8yem4xLWC5kMOouQHeFE_c3F4cR2uQBDXo/edit#slide=id.gb35ad0a6da_0_27). See the Basic Resource Comparison section.

**Comment by jamlung-ri** [comment]
Round 2 of Comparisons will likely involve some sort of configuration. See [this slide](https://docs.google.com/presentation/d/1xdZvvgWAB8yem4xLWC5kMOouQHeFE_c3F4cR2uQBDXo/edit#slide=id.gb4fd7ce096_0_22) and the ones that follow for details.
