### ISSUE TITLE
Plan OCL Core Enhancements for 1st half of 2021

### ISSUE THREAD

**Issue by aprilcurrier** [OpenConceptLab/ocl_issues#517]

**Comment by paynejd** [comment]
* Multi-hierarchy support
* Support for "owner-less" sources/collections (to reserve important canonical URLs)
* Support for non-breaking Concept/mapping customizations via collection references

**Comment by jamlung-ri** [comment]
To address post-launch

**Comment by paynejd** [comment]
Capturing here: https://docs.google.com/document/d/1c57MJkqHVDjOVQcxQtqVEeiTJK6XaWKmQT5VSjdDzQw/edit#

**Comment by paynejd** [comment]
Made good progress on this -- plan to wrap up next sprint

**Comment by paynejd** [comment]
This is now complete. Covered in a number of planning documents, including here: https://docs.google.com/document/d/1c57MJkqHVDjOVQcxQtqVEeiTJK6XaWKmQT5VSjdDzQw/edit#heading=h.ksiirzkfqjk4
