### ISSUE TITLE
[OCLWEB2] Content Creation/Editing

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#518]

**Comment by snyaggarwal** [comment]
@paynejd Any specific enhancements from v1 UI? I was thinking of using [drawers](https://material-ui.com/components/drawers/) for creation/editing

**Comment by snyaggarwal** [comment]
1. Concept:
    - [ ] Create
    - [ ] Edit (Create Version)
    - [ ] Delete
2. Mapping:
    - [ ] Create
    - [ ] Edit (Create Version)
    - [ ] Delete
3. Source:
    - [ ] Create
    - [ ] Edit
    - [ ] Delete
4. Source Version:
    - [ ] Create
    - [ ] Edit
    - [ ] Release
    - [ ] Delete
5. Collection:
    - [ ] Create
    - [ ] Edit
    - [ ] Delete
6. Collection Version:
    - [ ] Create
    - [ ] Edit
    - [ ] Release
    - [ ] Delete
7. Collection Reference:
    - [ ] Create
    - [ ] Edit
    - [ ] Delete
8. Org:
    - [ ] Create
    - [ ] Edit
    - [ ] Delete
9. User:
    - [ ] Create
    - [ ] Edit
    - [ ] Delete

**Comment by aprilcurrier** [comment]
Rolling over ETA another week to complete

**Comment by snyaggarwal** [comment]
Creating a new issue for advanced mapping form #552.
@paynejd This can be verified and closed

**Comment by aprilcurrier** [comment]
Closing feedback to be addressed in #466
