### ISSUE TITLE
Deleting an org prevents a new org with the same ID from being created

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#52]
For example:
1. Create new org with ID "abc123"
2. Add some content to org "abc123"
3. Delete org "abc123"
4. Create new org with ID "abc123"

Step 4 will result in an error: `Organization with mnemonic "abc123" already exists`

**Comment by paynejd** [comment]
@rkorytkowski I believe this error with deleting orgs is the same as the one that you just fixed for sources. Note that there may be some corrupt data on staging for an org that I deleted that does not show up any more -- I think it was named `PEPFAR-MOH-UG`. Please clear out any corrupt data that might be there if you find any!

**Comment by paynejd** [comment]
This also just occurred with the org on staging named "DATIM-MOH-RW".

We are doing the final demonstration to PEPFAR on Wednesday, Sep 5, and want to use this org for that meeting -- so the sooner it's ready the better!

**Comment by rkorytkowski** [comment]
User superuser account (root) and send request to: DELETE /orgs/org_to_be_deleted/

**Comment by rkorytkowski** [comment]
I will shortly deploy to staging...

**Comment by rkorytkowski** [comment]
It's been deployed to staging! @paynejd let me know, if you experience any issues.

**Comment by paynejd** [comment]
Thank you Rafal! Will test this in about an hour and let you know.

**Comment by rkorytkowski** [comment]
@paynejd, did it work? Can we close this one?

**Comment by paynejd** [comment]
Yes, this worked great! I have relied on it heavily over the weekend.

If you haven't already, can you update the wiki documentation with details
about how to purge vs. deactivate?

**Comment by rkorytkowski** [comment]
Actually deactivation is not possible for now until #67 is done.

Documented at https://github.com/OpenConceptLab/oclapi/wiki/orgs#deactivate-an-organization
