### ISSUE TITLE
Specification of the Input Format for Bulk Imports

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#522]
Specification of the Input Format for Bulk Imports
Create a JSON schema that is available for users to validate against
https://json-schema.org/ 
https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclvalidator.py

**Comment by maurya** [comment]
Pushing to next week awaiting a response from Apelon

**Comment by paynejd** [comment]
This is now a duplicate of #551 - closing out
