### ISSUE TITLE
Configuration Interface for Orgs

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#524]
Create a place in the OCL Web Interface for configurers to access customization options for a user, organization, source, or collection page, likely using a Settings tab/button that contains input fields for configuration options.

An example mockup for the org config settings is available here: https://docs.google.com/presentation/d/1xdZvvgWAB8yem4xLWC5kMOouQHeFE_c3F4cR2uQBDXo/edit#slide=id.gb2d103c5e1_0_24

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri 

### How it works currently:
1. Visit any org details like usual -- http://localhost:4000/#/orgs/DATIM-MOH-BI-FY19/
2. By default it will load OCL default theme and there is no option to change the layout or apply any template.
3. Add `?configs=true` in the URL -- http://localhost:4000/#/orgs/DATIM-MOH-BI-FY19/?configs=true
4. It should start showing an orange button (with name of the current configs applied) on the right to change/create/edit configuration
5. The config button has three functions:
   - Displays the name of the current applied config (OCL Default or User specified default for this org)
   - DropDown to list/change all the user created configurations for this.
   - Settings icon (at the start of the button) to edit/view the selected configs or to create a new configuration.
6. Details of configuration:
```
{
  tabs: [
    {
      type: 'sources',
      label: 'Dictionaries',                  // Tab label
      filters: {                               // context filters
        source_type: 'Dictionary'
      },
      fields: {                             // to be displayed in listing, short_code column to be labeled as Code (default is ID), etc
        short_code: 'Code',
        name: 'Name',
        source_type: 'Source Type'
      },
      page_size: 25
    },
    {
      type: 'sources',
      label: 'Sources',
      filters: {
        source_type: '!Dictionary'
      },
      page_size: 25                                     // omit this and it will fallback to page_size 25
    },
    {
      type: 'collections',
      label: 'Collections',
      default: true,                                      // auto selected tab on load of this org details
      page_size: 10                                     // different page_size (default is 25)
    }
  ]
}
```
(Pending layout, table/list, setting in above)
@paynejd @jamlung-ri -- Please provide feedback, as everything going to be reused in Source/Collections configuration.

**Comment by jamlung-ri** [comment]
This is awesome! I'll list out issues that I am having:
* When I try to filter by extras.Applicable+Periods, it always returns 0 results, presumably because of the '+' sign in there. I can see that it makes the [query itself](https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10/collections/?q=&page=1&exact_match=off&limit=10&includeRetired=false&verbose=true&extras.Applicable%2BPeriods=FY20&sortDesc=last_update) wrong, but if the query was a + instead of a %2B, it works. I am able to filter by extras.resultTarget too, so I'm pretty sure the issue is the +.

**Comment by jamlung-ri** [comment]
I also want to document some key validation points that we should highlight in the UI as we develop this:
* There cannot be two "default: true" lines. 
*

**Comment by jamlung-ri** [comment]
Configuration that does not get updated when submitting a new configuration

Previous config:
> {
  tabs: [
    {
      type: 'collections',
      label: 'Result',
      fields: {
        name: 'Name',
        type: 'Test',
        short_code: 'Code'
      },
      default: true,
      filters: {
        'extras.resultTarget': 'Result'
      },
      page_size: 20
    },
    {
      type: 'collections',
      label: 'Target',
      default: false,
      filters: {
        'extras.resultTarget': 'Target'
      },
      page_size: 20
    }
  ]
}

New config (changed the fields parameter short_code to type)
> {
    tabs: [
      {
        type: 'collections',
        label: 'Result',
        default: true,
        filters: {
          'extras.resultTarget': 'Result'
        },
        page_size: 20,
        fields: {                             
            short_code: 'Code',
            name: 'Name',
            type: 'Test'
          }
      },
      {
        type: 'collections',
        label: 'Target',
        default: false,
        filters: {
          'extras.resultTarget': 'Target'
        },
        page_size: 20
      }
    ]
  }

**Comment by jamlung-ri** [comment]
Here is the test configuration that I did, if anyone is interested in seeing it: https://app.qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10/?configs=true

**Comment by snyaggarwal** [comment]
@jamlung-ri 
1. "extras.Applicable Periods" -- you dont need to apply any special character to perform this search. Below one works:
`https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10/collections/?q=&page=1&exact_match=off&limit=10&includeRetired=false&verbose=true&extras.Applicable%20Periods=FY20&sortDesc=last_update`
2. I am looking into the switch configuration one. I agree, I could only reproduce it once in 5 attempts.
3. Working on supporting more attributes to show in the display.
4. Started displaying the config errors, below are configured so far:
  - EMPTY_TABS_CONFIG = 'At least one tab config is mandatory.'
  - NOT_LIST_TABS_CONFIG = 'Tabs config must be a list.'
  - ONE_DEFAULT_TAB = 'Exactly one of the Tabs must be default.'

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Added more to the configuration (mainly *layout* and *any field* support)
```
{
  tabs: [
    {
      type: 'sources',
      label: 'Dictionaries',                  // Tab label
      filters: {                               // context filters
        source_type: 'Dictionary'
      },
      fields: {                             // to be displayed in listing, short_code column to be labeled as Code (default is ID), etc
        short_code: 'Code',
        name: 'Name',
        source_type: 'Source Type',
        public_access: 'Access',  // can add any field like "extras.datim_moh_period": "DATIM MOH PERIOD"
      },
      page_size: 25,
      layout: 'list'               // default is table
    },
    {
      type: 'sources',
      label: 'Sources',
      filters: {
        source_type: '!Dictionary'
      },
      page_size: 25                                     // omit this and it will fallback to page_size 25
    },
    {
      type: 'collections',
      label: 'Collections',
      default: true,                                      // auto selected tab on load of this org details
      page_size: 10                                     // different page_size (default is 25)
    }
  ]
}
```

**Comment by jamlung-ri** [comment]
@snyaggarwal One other quick thing that I am noticing: When I submit a configuration with specified fields, it seems to be changing the order of the fields. I'll put an example below.

Fields that I am submitting:

> fields: {
        external_id: 'Test',
        name: 'Name',
        short_code: 'Code'

Fields that display and returned config (note the different order):
![image](https://user-images.githubusercontent.com/55999682/107370879-8c44b200-6ab1-11eb-8172-f2c332e5b282.png)

> fields: {
        name: 'Name',
        short_code: 'Code',
        external_id: 'Test'

**Comment by snyaggarwal** [comment]
TIL: 
> the order of insertion into dictionary is not maintained and highly dependent on browsers and can also change any time

@jamlung-ri We might have to change the structure of the fields. Just defining a dictionary can't guarantee the order of fields.
we might have to use an array of dictionaries, like, 
```
fields: [{external_id: 'Test'}, {blah: 'Second Column'}]
```

I am looking for possible ways of avoiding this. Will get back to you if we certainly have to change the structure of `fields`

**Comment by jamlung-ri** [comment]
One additional idea, which isn't super high priority yet:

In the List View, I am not seeing the attributes defined in the config, though they are showing as columns in the Table View. Maybe we can add those fields (if they are not already showing e.g. display_name) to the subtext for each row (see circled area in image). They can just show as text, similar to how the Collection Type attribute is showing.

![image](https://user-images.githubusercontent.com/55999682/107394404-d5a0fb80-6ac9-11eb-8cfa-c12e187b2a70.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Row layout now shows fields defined in configs (that are already not displayed)

**Comment by snyaggarwal** [comment]
@jamlung-ri the field order is fixed now.
if you try saving it as `fields: {source_type: 'foo', blah: 'foobar'}` it will be converted to `fields: [{source_type: 'foo'}, {blah: 'foobar'}]`

**Comment by jamlung-ri** [comment]
Closing because config testing was done this week. Next steps are to copy the same features in sources and collections (#525).

**Comment by jamlung-ri** [comment]
Sorting Syntax available here: https://github.com/OpenConceptLab/ocl_issues/issues/647#issuecomment-804007095
