### ISSUE TITLE
Customized Attribute Display on Source and Collection Tabs and Pages

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#525]
Allow a configurer to change the attributes displayed in the source or collection table from an organization or user page, or the concepts or mappings table from a source or collection.

This can be done from the configuration page. There can be a default table layout until a user has configured the table to display differently.

Examples of this are available in slides 2-4 of this deck: https://docs.google.com/presentation/d/1xdZvvgWAB8yem4xLWC5kMOouQHeFE_c3F4cR2uQBDXo/edit#slide=id.gb2d103c5e1_0_0

**Comment by jamlung-ri** [comment]
Just noting that much of the discussion and information for this is going on in #524, and this ticket will likely be closed once that ticket is complete.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri This is available on QA now. Please try this and provide feedback here.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd this works the same way as Org configs described at https://github.com/OpenConceptLab/ocl_issues/issues/524#issuecomment-775751379

**Comment by snyaggarwal** [comment]
Example Configuration Defined below for **PEPFAR-Test10** Source:
```
{
  tabs: [
    {
      type: 'concepts',
      label: 'Indicators',
      fields: [          // Custom Fields in order with corresponding labels to display
        {
          id: 'Code'
        },
        {
          display_name: 'Name'
        },
        {
          concept_class: 'Class'
        },
        {
          'extras.Period': 'Period'
        },
        {
          'extras.Reporting frequency': 'Reporting Frequency'
        }
      ],
      layout: 'table',          // default layout is table only
      default: true,          // Default tab to be selected
      filters: {          // Custom fixed filters to apply on this
        concept_class: 'reference indicator,indicator'
      },
      page_size: 50,          // custom page size
      query_params: {          // (custom) query_params to include in search.
        includeExtras: true
      }
    },
    {
      type: 'concepts',
      label: 'Data Elements',
      layout: 'list',          // custom layout (default is table)
      default: false,
      filters: {
        concept_class: 'data element'
      },
      page_size: 25,
      query_params: {
        includeExtras: true
      }
    },
    {
      type: 'concepts',
      label: 'Other Concepts',
      filters: {
        concept_class: '!data element,reference indicator,indicator'
      }
    },
    {
      type: 'mappings',
      label: 'Mappings',
      layout: 'table',
      page_size: 25
    },
    {
      type: 'versions',
      label: 'Versions',
      layout: 'table',
      page_size: 25
    },
    {
      type: 'about',
      label: 'About'
    }
  ]
}
```

**Comment by jamlung-ri** [comment]
Listing out any issues I see:

- [ ] If the configuration has an extras attribute in the Fields list, then the query would need to use verbose=true to get those attributes. Currently, the query for concepts seems to have verbose=false, which is adequate if no extra attributes are needed.

**Comment by snyaggarwal** [comment]
@jamlung-ri 
1. verbose in listing might affect the performance of the search results. So for this reason only I added the ability in concept/mapping APIs to return extras attributes by passing `?includeExtras=true`. And you can use this via configuration as I have mentioned in the previous comment https://github.com/openconceptlab/ocl_issues/issues/525#issuecomment-784018138.
Where ever you are using extras fields (in filters or fields) you have to add `query_params: {includeExtras: true}`. This way you should be able to add any other query param for that specific tab. Let me know if you have any trouble using this.
2. I will fix this!

**Comment by jamlung-ri** [comment]
Example Config being used for PEPFAR's MSP (initially): 

{
  tabs: [
    {
      type: 'about',
      label: 'Home',
      default: true
    },
    {
      type: 'concepts',
      label: 'Reference Indicators',
      fields: [
        {
          display_name: 'Name'
        },
        {
          'extras.Guidance Version': 'Version'
        }
      ],
      layout: 'list',
      default: false,
      filters: {
        concept_class: 'reference indicator'
      },
      page_size: 100,
      query_params: {
        includeExtras: true
      }
    },
    {
      type: 'concepts',
      label: 'Data Elements',
      fields: [
        {
          display_name: 'Name'
        },
        {
          id: 'UID'
        },
        {
          'extras.source': 'Source'
        },
        {
          concept_class: 'Type'
        }
      ],
      layout: 'list',
      default: false,
      filters: {
        concept_class: 'data element'
      },
      page_size: 25,
      query_params: {
        includeExtras: true
      }
    },
    {
      type: 'concepts',
      label: 'DATIM Indicators',
      fields: [
        {
          display_name: 'Name'
        },
        {
          id: 'UID'
        },
        {
          concept_class: 'Type'
        }
      ],
      layout: 'list',
      default: false,
      filters: {
        concept_class: 'indicator'
      },
      page_size: 25,
      query_params: {
        includeExtras: true
      }
    }
  ]
}
Image Version:
![image](https://user-images.githubusercontent.com/55999682/111185860-cf9ab080-8588-11eb-9180-9a8017721705.png)
