### ISSUE TITLE
Basic Resource Download

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#529]
Selected resources can be exported as JSON file

**Comment by jamlung-ri** [comment]
An example of this is available in [this slide](https://docs.google.com/presentation/d/1xdZvvgWAB8yem4xLWC5kMOouQHeFE_c3F4cR2uQBDXo/edit#slide=id.gb4fd7ce096_0_4).

**Comment by snyaggarwal** [comment]
this is done for mappings/concepts in JSON/CSV format.

**Comment by jamlung-ri** [comment]
Looks great, @snyaggarwal! The basic functionality is all there for JSON and CSV formats. 

The only potential thing we might want to add (not necessarily now but definitely in the future) is adding a "verbose" sort of option that allows download of extra attributes, mappings, etc.

Also, we may want to add a download button to the individual concept page, but we can probably save that for another time too.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Can we close this one and create new specific requirement tickets?

**Comment by jamlung-ri** [comment]
@snyaggarwal Yeah we can do that. I'll open up a new ticket with these ideas.
