### ISSUE TITLE
[Oclweb2] OCL Default Landing Page.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#539]

**Comment by paynejd** [comment]
Some thoughts on this (more to come)...
* openconceptlab.org and home.openconceptlab.org should point to the OCL wordpress site
    * Should home.*.openconceptlab.org (for non-production environments) also point to wordpress site?
* app.openconceptlab.org and app.*.openconceptlab.org should point to oclweb2

**Comment by snyaggarwal** [comment]
Landing Page:
1. Logged in user -- User Home - `/users/:username`
2. Anonymous user -- Public Org Listing (Search) Page

**Comment by paynejd** [comment]
Works great!
