### ISSUE TITLE
500 when deleting a source

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#54]
Deletion of a source may end with 500 error due to broken data. The delete operation should succeed even if there are some data inconsistencies as a way to recover from a bad state.

Deletion should be done in a form of raw queries, which is much more performant and does not complain about bad state.

**Comment by paynejd** [comment]
FYI it appears that the DELETE operation is what actually broke the data in
these 2 sources, because I had been using both sources prior to the delete.

I'm wondering if it is the order of operations that is messed up -- it
appears that some of the concepts were deleted before their corresponding
mappings, because several of the mappings now have a to-concept of "None".

**Comment by rkorytkowski** [comment]
I see. I haven't investigated further, just rewritten the code in the proper way using faster queries. It's been already deployed to staging, so you can test it.

**Comment by paynejd** [comment]
Hey, I just tried deleting this source and received the error message in the image below:
https://staging.openconceptlab.org/orgs/DATIM-MOH-LS/sources/DATIM-Alignment-Indicators/ 

However, the delete did complete successfully and I was able to recreate an empty source with the same name. Not sure if the error was just lingering from the previously corrupted data, but looks like the fix worked!

![image](https://user-images.githubusercontent.com/1189689/40991030-86d0a496-68c0-11e8-8eda-3175c3d12633.png)

**Comment by rkorytkowski** [comment]
I've checked the error and it is due to solr not being properly updated after executing raw queries. I need to trigger solr removal as well. I'll do a follow up commit.

**Comment by paynejd** [comment]
Ah, that makes sense! Glad you found this one...

**Comment by rkorytkowski** [comment]
Needed to revert it in https://github.com/OpenConceptLab/oclapi/commit/45d6cabc284627d5ce3f76be17351810218db6ec due to failing tests. I'll work on a proper fix.
