### ISSUE TITLE
Resolve Source Version export inconsistencies between oclapi1 and v2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#541]
When downloading an export of the same source version in oclapi1 and oclapi2, there are differences in the returned JSON file. Some of these are expected, but some need to be resolved to avoid breaking changes. We'll use this ticket to document the differences and the solutions.

Here are 4 sample JSON files used to analyze differences:
[https://app.zenhub.com/files/122384560/dcbd2f5f-b5f7-4d89-8f03-c5ef972d1e27/download](https://app.zenhub.com/files/122384560/dcbd2f5f-b5f7-4d89-8f03-c5ef972d1e27/download)

* In oclapi2, the top-level attributes in the export are the source or collection resource, whereas in oclapi1 the top-level resource type is `Source Version` or `Collection Version` with the `source` and `collection` returned as child attributes. We need to shift oclapi2 to return source/collection versions as well
    * Also, source extras are empty in the export, even though the source has multiple custom attributes: https://api.staging.aws.openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY20/ (this may be resolved by addressing the above issue though)
* Concepts in the exports have just a few minor issues:
    * `concept.names.type` is null -- should be `Concept Name`
    * `concept.descriptions.type` is null -- should be `Concept Description`
    * `concept.source_url` incorrectly provides the `owner_url` instead of the `source_url`
    * `concept.is_latest_version` is incorrect (`false` instead of `true` -- there is only one version of the concept, so this must be `true`)
* Mappings have several differences:
    * Mappings have `created_at` and `updated_at` fields, whereas all other resources have `created_on` and `updated_on` -- Mappings should be updated to be consistent with other resources

**Comment by snyaggarwal** [comment]
This is fixed. Will be deploying this next on qa

**Comment by snyaggarwal** [comment]
@paynejd can we close this one?
