### ISSUE TITLE
PEPFAR AWS Testing

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#545]
Testing MOH Alignment and IMAP import with Staging AWS server and test.ohie.datim.org

https://docs.google.com/document/d/1BygMB5qON8P65tOzxFV5Vz0O519Bnf8Wnq6XCKAS4Xg/edit

**Comment by aprilcurrier** [comment]
Rolling over as the work has just been started

**Comment by maurya** [comment]
Prepared testing documentation and added details on how to do testing for each work stream

**Comment by maurya** [comment]
MOH and DATIM endpoints functional. Changes to support the new model for IMAP and QMAP endpoints to work

**Comment by paynejd** [comment]
Testing is still underway - moving this to next sprint

**Comment by jamlung-ri** [comment]
Requests appear to be working, per Maurya. Just waiting to improve timing on IMAP export (30-60 seconds). A follow-up ticket will be created to address this. The whole process should get down to ~10 seconds.
