### ISSUE TITLE
Final import to MSP round 10 import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#546]
Round 10 import was completed in #547. This ticket is to address feedback received and to update with the final iHUB extract.

**Comment by jamlung-ri** [comment]
Reached out to Stephanie on 12 Feb 2021 for the latest import

**Comment by paynejd** [comment]
See #547

**Comment by paynejd** [comment]
Testing results from Puneet:

Hey Guys, there are two indicators that does not match the ocl to zendesk codelist: `MER-R-COMMUNITY-BASED-DOD-ONLY-FY2018Q4` & `MER-R-COMMUNITY-BASED-FY2018Q4`

Zendesk have records but the OCL are blank in the `categorycombo`, `categoryoptioncombocode`, `categoryoptioncombouid`

https://github.com/pepfar-datim/DATIM-OCL/tree/master/OCL-API-Testing/ocl-API/TestCases/API/DATIM/ZenDesk-OCL-Codelist-Comparsion

Verify codelist CSV is in up-to-date

**Comment by paynejd** [comment]
**COMPLETED AS PART OF ROUND 10 IMPORT:**
* Updated to MER v2.5 / FY21 content:
    * FY21 MER v2.5 Reference Indicators spreadsheet
    * FY21 Codelists spreadsheet
    * DATIM metadata exports retreived 2021-01-06 (DEs, indicators, COCs, dataset)
    * iHUB Derived Data Elements extract from 2021-02-18
    * Modified settings.py for FY21
* Replaced all occurences of PDH with iHUB
* Applied MSP_ORG_ID to codelist file so that this no longer has to be updated manually
* Added canonical URLs to MER CodeSystem, Reference Indicator Value Sets, and all DATIM Codelists
* Modified rules for generating links between a ref indicator and its corresponding data elements
  and DATIM indicators (some ref indicator codes are in the middle of the resource labels, not the beginning)
* Generated new "Central Support" PEPFAR Support Type attribute for applicable data elements (same as DSD/TA)
* Removed unnecessary codelist_collections['extras']['dhis2_codelist'] attribute before saving
  (this attribute is only used during processing)
* Generated round 10 bulk import script and validated
* Generated ref indicator collection versions at the end of processing each period instead of at the end
  (this fixed a bug where a collection sometimes returned a newer version of a concept)
* ETL script processing updates:
    * Removed chunking of bulk import file now that oclapi2 can handle large bulk imports
    * Improved log summary of OCL resource types in the final import script to simplify validation
    * Updated to latest ocldev package release

**NOT COMPLETED AS PART OF ROUND 10 (BUMPING THESE TO ROUND 11):**
* Update how codelist references are generated:
    * 840:msp.build_codelist_references -- this refers to COC IDs and new custom mapping IDs,
      which the method is not yet able to validate
* Review the addition of Reporting Frequency attribute from Reference Indicators to relevant
  DATIM/iHUB DEs and address any issues. This was included in Rnd8 but needs to be reviewed.
* Include Mechanism name in DATIM indicator formulas with 3 UIDs

**Comment by paynejd** [comment]
What's remaining for round 10?
* Compare build report from 2021-01-08 to 2021-03-09 to make sure everything looks good:
  * Count of ref indicators to DATIM indicators is lower -- double check this
* Share with Sunny to run the bulk import and monitor performance
* Test with MSP

**Comment by paynejd** [comment]
`PEPFAR-Test10b` now loaded into qa.aws and staging.aws
