### ISSUE TITLE
Validate MSP round 10 import using the updated web application

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#547]
Round 10 is available on qa2.aws and will be available soon on qa.aws and staging.aws.

We want to validate the round 10 content, which added MER v2.5, using the actual MSP web application.

**Comment by paynejd** [comment]
Validation Issues:
* MER_REFERENCE_INDICATORS_* collections include definitions from the wrong periods: https://api.qa2.aws.openconceptlab.org/orgs/PEPFAR-Test10/collections/MER_REFERENCE_INDICATORS_FY21/concepts/?limit=0&verbose=true

Next Steps:
* Remove MER_REFERENCE_INDICATORS_* collections

Impact on MSP:
* Replace all queries to the MER_REFERENCE_INDICATOR_* collections with custom attribute filter queries

**Comment by jamlung-ri** [comment]
* I am guessing that some FY21 concepts were loaded into OCL QA twice, based on the results from this query: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10/sources/MER/concepts/TX_ML/versions/?verbose=true&includeMappings=true
* It does not look like the FY21 reference indicators have mappings to data elements and indicators. 
    * FY21 example: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10/sources/MER/concepts/TX_ML/1491/?verbose=true&includeMappings=true
    * FY17 example with mappings: https://api.staging.openconceptlab.org//orgs/PEPFAR-Test8/sources/MER/concepts/TB_PREV/5eea8df5debb3d007da6484a/?verbose=true&includeMappings=true

**Comment by jamlung-ri** [comment]
> Next Steps:
> 
>     * Remove MER_REFERENCE_INDICATORS_* collections
> 
@paynejd I think we discussed that we aren't ready for this step, unless we can somehow query older concept versions using extra attributes.

**Comment by paynejd** [comment]
Correct- we are going to stick with using those collections

**Comment by jamlung-ri** [comment]
One change that @paynejd made: 

> Updated the round10 build scripts so that ref indicator codes in the middle of a resource name would have a corresponding indicator attribute, so the TX_ML issue that we saw will be resolved with the next import

**Comment by jamlung-ri** [comment]
Rolling over so Jon can take care of this content change and incorporate the latest iHUB content.

**Comment by jamlung-ri** [comment]
Validation is done, following up on issues in #546
