### ISSUE TITLE
Document AWS infrastructure

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#550]
Please separate into one public and one private document. Feel free to draft each of these in the private `ocl_infrastructure` wiki and we'll shift the public document to the correct place when ready.

Create two different documentation versions 

- [ ] One public facing 
- [ ] One private facing

**Comment by aprilcurrier** [comment]
Rolling over - 50% complete upon rollover

**Comment by jamlung-ri** [comment]
Rolling over - to address on OCL Dev call

**Comment by rkorytkowski** [comment]
Added public facing one here: https://github.com/OpenConceptLab/ocl-docs/blob/main/docs/source/index.rst#ocl-infrastructure
And internal one here: https://github.com/OpenConceptLab/oclinfrastructure#infrastructure

**Comment by jamlung-ri** [comment]
@maurya  to review.
