### ISSUE TITLE
Revise documentation for bulk import syntax

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#551]
Need documentation of syntax & semantics of target someone could use to ETL their content into that target form for bulk import.

@bmamlin @harpatel1 @snyaggarwal @rkorytkowski How is this typically documented?

**Comment by aprilcurrier** [comment]
@jamlung-ri  to follow up with Jess to provide a use case to provide further guidance to the team on how to proceed

**Comment by paynejd** [comment]
If using JSON Schema, here's a possible online tool that we could use that helps to generate JSON schemas from a JSON sample:
https://github.com/jackwootton/json-schema

**Comment by jamlung-ri** [comment]
Jon and Joe to talk with Jess at Apelon

**Comment by jamlung-ri** [comment]
We spoke with Jess at Apelon yesterday, who is doing a use case for terminology transformation between their data model and OCL's. Here are some things to note:
* It seems like we need some kind of hierarchy schema to help with that (see ticket #585)
* We should think about how Role Groups (i.e. attributes for grouping concepts) can be represented in OCL
* Think about how we should be handling multiple versions of SNOMED or other vocabularies

**Comment by jamlung-ri** [comment]
Update with Apelon: 
* Since hierarchy is the only real blocker, Apelon will start with some basic transformation
* There are some issues (documented [here](https://docs.google.com/document/d/10lCCNIPvMMA2wDyFsbMt58tjiJfRsA5PJJPMv-efkD4/edit)) that we will need to address.

**Comment by paynejd** [comment]
Bumping this to next sprint as we'll get started on documentation after the mapping work with Apelon has made more progress

**Comment by jamlung-ri** [comment]
@paynejd should we be working on this now that SNOMED was successfully loaded, or should we wait for LOINC to be loaded first?

**Comment by jamlung-ri** [comment]
We have new features, syntax, the bulk import UI, etc. Refreshing this documentation would be good. 

Specifics:
* Hierarchy syntax and root url
* CSV support
* Import methods (Parallel, hierarchy, HTTP URL, file upload, JSON, CSV, etc.)
* Number of workers for parallelization

@jamlung-ri to create a skeleton, and @snyaggarwal will help fill in details

**Comment by jamlung-ri** [comment]
Other ideas: Monitoring status, cancelling reports (and other things that are available in Swagger)

**Comment by jamlung-ri** [comment]
This documentation has been started here:https://docs.google.com/document/d/1QrpOLVGew1kNufi0A0c8huQQWBKk5_QnTwa-qRFRUiM/edit#

Adding Sunny to the ticket to fill in more technical details. Some of these are designated by comments, so start by addressing those where applicable.

I still have a little more to do here, so Sunny and I can start putting everything together.

**Comment by jamlung-ri** [comment]
Next step: Put this on the wiki and continue enhancing it.

**Comment by jamlung-ri** [comment]
This has been updated in the documentation. See the [Docs page](https://docs.openconceptlab.org/en/latest/oclapi/apireference/bulkimporting.html) and [GitHub](https://github.com/OpenConceptLab/ocl-docs/blob/main/docs/source/oclapi/apireference/bulkimporting.md). A follow-up ticket will be created to continue this work.
