### ISSUE TITLE
[OCLWEB2] Advanced Mapping Form - Resource lookups

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#552]

**Comment by jamlung-ri** [comment]
@paynejd and @jamlung-ri to discuss with Sunny

**Comment by jamlung-ri** [comment]
Seems to be working since no one has complained about being able to add mappings. Let's put it in the Backlog for now and check in later.

**Comment by snyaggarwal** [comment]
@jamlung-ri May be we reuse this ticket for new quick add associations or close/delete this?

**Comment by jamlung-ri** [comment]
I think this is probably separate from the Quick-Add mappings work. This is more about what a revamped Mapping Creation/Editing form will look and act like. I think we can close this for now and start up a fresh set of tickets for when that work starts.
