### ISSUE TITLE
Requesting mappings from API v2 slow to respond

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#553]
Some mapping requests to API v2 are slow to respond.

#### Example
`GET` https://api.qa.aws.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/?fromConcept=1067,162625,1065&limit=0

#### Observed Behavior
Response time is currently ~16 seconds. The same request in API v1 responds in ~300 ms.

#### Expected Behavior
Response time less than 300 ms.

**Comment by snyaggarwal** [comment]
Can you try following:
GET https://api.qa.aws.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/?fromConcept=1067,162625,1065&limit=0&q=

**Comment by bmamlin** [comment]
Adding the `&q=` to the end makes it work (quick response with expected results). It looks like omitting `&q=` not only makes the response incredibly slow, but returns seemingly random results (e.g., `?fromConcept=1226&limit=0` eventually returns ~25 seemingly random results with `from_concept_code` something other than 1226 in most cases instead of – with `&q=` added – instantly responding with the 6 mappings from CIEL 1226).

Can you make the omission of `&q=` behave the same as having it there?

**Comment by snyaggarwal** [comment]
yes. Just working on that only. Should be available after the next deployment today.

**Comment by snyaggarwal** [comment]
@bmamlin this is deployed now on qa.
https://api.qa.aws.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/?fromConcept=1067,162625,1065&limit=0
works (without `q` param)

**Comment by snyaggarwal** [comment]
@bmamlin Let me know if this can be closed.

**Comment by paynejd** [comment]
tested - looking good!
