### ISSUE TITLE
Implement final touches on the OCL AWS infrastructure

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#559]
Remaining items:

- [ ] Clustering for redis and ES
- [x] Add more health checks (eg celery workers)
- [ ] Backup configuration for elastic search

**Comment by paynejd** [comment]
switch to reserved instances

**Comment by jamlung-ri** [comment]
May be able to do this after soft-launch?

**Comment by jamlung-ri** [comment]
We will create separate tickets for these later on. They are on the roadmap. Rafal has done many smaller tweaks, however.
