### ISSUE TITLE
Additional Download Functionality

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#561]
To do:

- [x] Add a "verbose" sort of option that allows download of extra attributes, mappings, etc.

- [x] Add a download button to the individual concept page

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/529#issuecomment-765377646_

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done for mappings and concepts as well (org/source/collections already had this). Please review this.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! The download button has been added on concept details pages and on long search pages. What are your thoughts on the "Verbose" option? For PEPFAR content, in particular, which has lots of Extra attributes, it'll be most useful to be able to have those attributes in the export too.

**Comment by snyaggarwal** [comment]
@jamlung-ri By default all should be verbose downloads with extras and mappings

**Comment by jamlung-ri** [comment]
Oh, I'm not getting that. When I was downloading some concepts from [here](https://app.qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10/sources/MER/), I received these JSON and CSV files. 

`[
  {
    "uuid": "153037",
    "id": "LAB_PTCQI",
    "external_id": null,
    "concept_class": "Reference Indicator",
    "datatype": "None",
    "url": "/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/",
    "retired": false,
    "source": "MER",
    "owner": "PEPFAR-Test10",
    "owner_type": "Organization",
    "owner_url": "/orgs/PEPFAR-Test10/",
    "display_name": "LAB_PTCQI",
    "display_locale": "en",
    "version": "153037",
    "update_comment": null,
    "locale": null,
    "version_created_by": "ocladmin",
    "version_created_on": "2021-01-22T09:57:18.847326Z",
    "mappings": [],
    "is_latest_version": true,
    "versions_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/versions/",
    "version_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/153037/"
  },
  {
    "uuid": "153034",
    "id": "TX_RTT",
    "external_id": null,
    "concept_class": "Reference Indicator",
    "datatype": "None",
    "url": "/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/",
    "retired": false,
    "source": "MER",
    "owner": "PEPFAR-Test10",
    "owner_type": "Organization",
    "owner_url": "/orgs/PEPFAR-Test10/",
    "display_name": "TX_RTT",
    "display_locale": "en",
    "version": "153034",
    "update_comment": null,
    "locale": null,
    "version_created_by": "ocladmin",
    "version_created_on": "2021-01-22T09:57:18.506545Z",
    "mappings": [],
    "is_latest_version": true,
    "versions_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/versions/",
    "version_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/153034/"
  },
  {
    "uuid": "153017",
    "id": "HTS_RECENT",
    "external_id": null,
    "concept_class": "Reference Indicator",
    "datatype": "None",
    "url": "/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/",
    "retired": false,
    "source": "MER",
    "owner": "PEPFAR-Test10",
    "owner_type": "Organization",
    "owner_url": "/orgs/PEPFAR-Test10/",
    "display_name": "HTS_RECENT",
    "display_locale": "en",
    "version": "153017",
    "update_comment": null,
    "locale": null,
    "version_created_by": "ocladmin",
    "version_created_on": "2021-01-22T09:57:16.214557Z",
    "mappings": [],
    "is_latest_version": true,
    "versions_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/versions/",
    "version_url": "/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/153017/"
  }
]`

`"uuid","id","external_id","concept_class","datatype","url","retired","source","owner","owner_type","owner_url","display_name","display_locale","version","update_comment","locale","version_created_by","version_created_on","mappings","is_latest_version","versions_url","version_url"
"153037","LAB_PTCQI","null","Reference Indicator","None","/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/","false","MER","PEPFAR-Test10","Organization","/orgs/PEPFAR-Test10/","LAB_PTCQI","en","153037","null","null","ocladmin","2021-01-22T09:57:18.847326Z","[]","true","/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/versions/","/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/153037/"
"153034","TX_RTT","null","Reference Indicator","None","/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/","false","MER","PEPFAR-Test10","Organization","/orgs/PEPFAR-Test10/","TX_RTT","en","153034","null","null","ocladmin","2021-01-22T09:57:18.506545Z","[]","true","/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/versions/","/orgs/PEPFAR-Test10/sources/MER/concepts/TX_RTT/153034/"
"153017","HTS_RECENT","null","Reference Indicator","None","/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/","false","MER","PEPFAR-Test10","Organization","/orgs/PEPFAR-Test10/","HTS_RECENT","en","153017","null","null","ocladmin","2021-01-22T09:57:16.214557Z","[]","true","/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/versions/","/orgs/PEPFAR-Test10/sources/MER/concepts/HTS_RECENT/153017/"
`

**Comment by jamlung-ri** [comment]
Oh now I see. I did get the verbose export from the [individual concept details page](https://app.qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10/sources/MER/concepts/LAB_PTCQI/). I was doing multi-select exports on other pages, like in my comment above. Do you think it'd be okay to make those multi-select exports also use verbose and mappings?

**Comment by snyaggarwal** [comment]
I understand. Let me look at the multi select verbose downloads.

**Comment by snyaggarwal** [comment]
Done

**Comment by jamlung-ri** [comment]
This is now working as expected across resource types.
