### ISSUE TITLE
[oclapi2] healthcheck/system-status

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#566]
Using [https://github.com/KristianOellegaard/django-health-check](https://github.com/KristianOellegaard/django-health-check)

`curl -X GET "http://localhost:8000/healthcheck/" -H "accept: application/json"`
```
Returns 200 (or 500 if not good)
{
   "DatabaseBackend":"working", (critical)
   "ElasticSearch":"working", (critical)
   "Flower":"working",
   "RedisHealthCheck":"working",, (critical)
   "celery@bulk_import_0":"unavailable: No worker for Celery task queue bulk_import_0",
   "celery@bulk_import_1":"unavailable: No worker for Celery task queue bulk_import_1",
   "celery@bulk_import_2":"working",
   "celery@bulk_import_3":"working",
   "celery@bulk_import_root":"unavailable: No worker for Celery task queue bulk_import_root",
   "celery@concurrent":"unavailable: No worker for Celery task queue concurrent",
   "celery@default":"working"
}
```
Will return 500 if any of the critical health check(s) fails.

Also there is a UI for this at `/healthcheck/` which can serve as system status screen

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski 
Please try https://api.qa.aws.openconceptlab.org/healthcheck/
and `curl -X GET "http://localhost:8000/healthcheck/" -H "accept: application/json" | jq`
Let me know if this should be enough

**Comment by paynejd** [comment]
This is great! Let's discuss on Friday's arch call for sure

**Comment by snyaggarwal** [comment]
@paynejd can we close this?
