### ISSUE TITLE
Searching user collections returns results that user does not own

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#567]
While testing the OCL Client for OpenMRS against OCL API v2, I noticed all public collections were being shown within a section that should only show the user's collections. The client is making a request like this:

```
/user/collections/q=*
```

#### Expected behavior
A query to `/user/collections/?q=:query` should return the subset of user's collections that match `:query`. If the query is omitted/blank or `*`, then all of the user's collections should be returned.

#### Observed behavior
A query to API v2 `/user/collections/?q=:query` is returning a filtered list of _all public collections_ (presumably all collections for which the user has read access, including collections the user does not own).

**Comment by snyaggarwal** [comment]
@bmamlin I tried reproducing this on my local, but couldn't. Can you give me an example of this? On which env I can reproduce this?

**Comment by paynejd** [comment]
https://api.qa.aws.openconceptlab.org/user/collections/?limit=20&page=1&q=*&customValidationSchema=OpenMRS&timestamp=1612530995986

**Comment by snyaggarwal** [comment]
@bmamlin this is fixed and deployed on staging and qa

**Comment by bmamlin** [comment]
Confirmed this is fixed. Thanks @snyaggarwal!
