### ISSUE TITLE
Auto-redirect repository "export" endpoint when using the "latest" keyword

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#57]
Retrieving the latest released export of a repo is currently a 2-step process and it could be easily simplified to one step, which would really assist some people that are developing scripts to integrate with OCL. For example, here are the two steps you would currently do:
1. https://openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/latest/
2. https://openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/[version]/export/

Instead we could simply support the following through a redirect:
https://openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/latest/export/

**Comment by paynejd** [comment]
Adding this to the roadmap for oclapi2 after launch

**Comment by snyaggarwal** [comment]
this is implemented for both source and collection

**Comment by paynejd** [comment]
will not implement in oclapi v1 -- closing out

**Comment by aprilcurrier** [comment]
@snyaggarwal what is the process for doing reviews (e.g. something you are doing or would like to involve others)?

**Comment by snyaggarwal** [comment]
I think ideally the creator of the issue should close it. The review should be done by someone other than the implementor.

**Comment by aprilcurrier** [comment]
Harsh to test

**Comment by harpatel1** [comment]
Here is what I've noticed:
https://api.qa2.aws.openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY19/FY19.v0/export
https://api.qa2.aws.openconceptlab.org/orgs/PEPFAR/sources/DATIM-MOH-FY19/latest/export

Both urls redirects to s3 bucket file but running into **Access Denied** error.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>73C2C50C69AFD16F</RequestId>
<HostId>88CxuxCrRpdhcq3PqkxDLjNWKfdNPwufCUBigdGnCKLKiCpKaw8ZSPAsvsqFoGjol/xANw/Ky4o=</HostId>
</Error>

```

**Comment by aprilcurrier** [comment]
No longer happening.  Harsh to verify.

**Comment by harpatel1** [comment]
@rkorytkowski @snyaggarwal 

I created sample data and tried to get export of source using `https://api.qa2.aws.openconceptlab.org/orgs/TestOrg/sources/source1/v1.0/export/` .


However, I am still receiving following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>31465B9CC7628AC8</RequestId>
    <HostId>aeEs9jN0/9D7+j5TAT7lBiBUgkVddewDGTKzc0aaUan0QGAigjx/tcRVIL1jrAyf+Ezt8ePWCKA=</HostId>
</Error>
```

**Comment by snyaggarwal** [comment]
This was caused due to lack of AWS configs with celery default service. I have added the env vars in terraform and deployed.
Tested this and its working fine now.
@harpatel1 You can verify this now. It should work fine now for new exports.
