### ISSUE TITLE
Unexpected missing FSN error when putting concept with OCL API v2

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#571]
While testing the OCL for OpenMRS client against OCL API v2, I tried to add a mapping (`test/2` _associated with_ `CIEL/5018`) and received an unexpected error stating "A concept must have at least one fully specified name."

This is the `PUT` request:
```
curl 'https://api.qa.aws.openconceptlab.org/users/test/sources/test1/concepts/2/' \
   -X 'PUT' \
   -H 'accept: application/json' \
   -H 'authorization: Token <api-token-for-qa-test>' \
   -H 'content-type: application/json;charset=UTF-8' \
   --data-raw '{"names":[{"uuid":"389970","name":"Projectile diarrhea","external_id":"871ff8e1-ff19-495a-a691-16e55cc5d090","type":"ConceptName","locale":"en","locale_preferred":true,"name_type":"FULLY_SPECIFIED"}],"descriptions":[],"type":"Concept","uuid":"153182","id":"2","external_id":"0450b07b-84ef-4d64-983c-001d6fc0b43a","concept_class":"Diagnosis","datatype":"N/A","display_locale":"en","extras":{},"retired":false,"source":"test1","source_url":"/users/test/sources/test1/","owner":"test","owner_name":"test","owner_url":"/users/test/","version":"153182","created_on":"2021-01-26T06:00:19.740177Z","updated_on":"2021-02-03T14:58:53.210939Z","version_created_on":"2021-01-26T06:00:19.740177Z","version_created_by":"test","is_latest_version":true,"locale":null,"url":"/users/test/sources/test1/concepts/2/","owner_type":"User","version_url":"/users/test/sources/test1/concepts/2/153182/","previous_version_url":null}'
```

<details><summary>Click for JSON submitted in pretty format</summary>

```json
{
    "concept_class": "Diagnosis",
    "created_on": "2021-01-26T06:00:19.740177Z",
    "datatype": "N/A",
    "descriptions": [],
    "display_locale": "en",
    "external_id": "0450b07b-84ef-4d64-983c-001d6fc0b43a",
    "extras": {},
    "id": "2",
    "is_latest_version": true,
    "locale": null,
    "names": [
        {
            "external_id": "871ff8e1-ff19-495a-a691-16e55cc5d090",
            "locale": "en",
            "locale_preferred": true,
            "name": "Projectile diarrhea",
            "name_type": "FULLY_SPECIFIED",
            "type": "ConceptName",
            "uuid": "389970"
        }
    ],
    "owner": "test",
    "owner_name": "test",
    "owner_type": "User",
    "owner_url": "/users/test/",
    "previous_version_url": null,
    "retired": false,
    "source": "test1",
    "source_url": "/users/test/sources/test1/",
    "type": "Concept",
    "updated_on": "2021-02-03T14:58:53.210939Z",
    "url": "/users/test/sources/test1/concepts/2/",
    "uuid": "153182",
    "version": "153182",
    "version_created_by": "test",
    "version_created_on": "2021-01-26T06:00:19.740177Z",
    "version_url": "/users/test/sources/test1/concepts/2/153182/"
}
```
</details>

And here is the response:
```json
{
    "names": [
        "A concept must have at least one fully specified name"
    ],
    "non_field_errors": [
        "An error occurred while saving new concept version."
    ]
}
```

I'm confused because the JSON submitted _does_ appear to have a fully specified name (the returned error doesn't appear correct) and the mapping I added isn't mentioned anywhere (I assume this is because the client stops at this error and doesn't get to the next step of adding the new mapping).

When I perform a `GET` on `/test/sources/test1/concepts/2/` and compare it to the `PUT` JSON, I see `display_name` and `name` properties that aren't in the `PUT` resource. I tried adding these into the `PUT` request, but it didn't help.

**Comment by snyaggarwal** [comment]
Found the issue. Its the confusion between `name_type` and `type`. Fixed this and deployed on QA. Can you please try and let me know if everything is ok.

**Comment by bmamlin** [comment]
@snyaggarwal you seemed to fix the name error and I can now save a mapping, but I can't update a description. I added a description to `test/2` as "A thing you do not want." This was saved successfully. Then I tried changing this description text to "Something you do not want." but the update is rejected.

```
curl 'https://api.qa.aws.openconceptlab.org/users/test/sources/test1/concepts/2/' \
   -X 'PUT' \
   -H 'accept: application/json, text/plain, */*' \
   -H 'authorization: Token <api-token-for-user-test>' \
   -H 'content-type: application/json;charset=UTF-8' \
   --data-raw '{"names":[{"uuid":"389989","name":"Projectile diarrhea","external_id":"871ff8e1-ff19-495a-a691-16e55cc5d090","type":"ConceptName","locale":"en","locale_preferred":true,"name_type":"FULLY_SPECIFIED"}],"descriptions":[{"uuid":"389990","description":"Something you do not want.","external_id":"918582b0-e5d0-4259-b966-956c87ecad76","type":"ConceptDescription","locale":"en","locale_preferred":true,"description_type":null}],"type":"Concept","uuid":"153198","id":"2","external_id":"0450b07b-84ef-4d64-983c-001d6fc0b43a","concept_class":"Diagnosis","datatype":"N/A","display_locale":"en","extras":{},"retired":false,"source":"test1","source_url":"/users/test/sources/test1/","owner":"test","owner_name":"test","owner_url":"/users/test/","version":"153198","created_on":"2021-02-09T03:24:33.859513Z","updated_on":"2021-02-09T03:24:34.226642Z","version_created_on":"2021-02-09T03:24:33.859513Z","version_created_by":"test","is_latest_version":true,"locale":null,"url":"/users/test/sources/test1/concepts/2/","owner_type":"User","version_url":"/users/test/sources/test1/concepts/2/153198/","previous_version_url":"/users/test/sources/test1/concepts/2/153197/"}'
```

<details><summary>Click for JSON submitted in pretty format</summary>

```json
{
    "concept_class": "Diagnosis",
    "created_on": "2021-02-09T03:24:33.859513Z",
    "datatype": "N/A",
    "descriptions": [
        {
            "description": "Something you do not want.",
            "description_type": null,
            "external_id": "918582b0-e5d0-4259-b966-956c87ecad76",
            "locale": "en",
            "locale_preferred": true,
            "type": "ConceptDescription",
            "uuid": "389990"
        }
    ],
    "display_locale": "en",
    "external_id": "0450b07b-84ef-4d64-983c-001d6fc0b43a",
    "extras": {},
    "id": "2",
    "is_latest_version": true,
    "locale": null,
    "names": [
        {
            "external_id": "871ff8e1-ff19-495a-a691-16e55cc5d090",
            "locale": "en",
            "locale_preferred": true,
            "name": "Projectile diarrhea",
            "name_type": "FULLY_SPECIFIED",
            "type": "ConceptName",
            "uuid": "389989"
        }
    ],
    "owner": "test",
    "owner_name": "test",
    "owner_type": "User",
    "owner_url": "/users/test/",
    "previous_version_url": "/users/test/sources/test1/concepts/2/153197/",
    "retired": false,
    "source": "test1",
    "source_url": "/users/test/sources/test1/",
    "type": "Concept",
    "updated_on": "2021-02-09T03:24:34.226642Z",
    "url": "/users/test/sources/test1/concepts/2/",
    "uuid": "153198",
    "version": "153198",
    "version_created_by": "test",
    "version_created_on": "2021-02-09T03:24:33.859513Z",
    "version_url": "/users/test/sources/test1/concepts/2/153198/"
}
```
</details>

Here is the `400 Bad request` response:

```json
{
    "descriptions": [
        "Invalid description type"
    ],
    "non_field_errors": [
        "An error occurred while saving new concept version."
    ]
}
```

It looks like this is a similar problem (I see `"description_type":null` and `"type":"ConceptDescription"`). Perhaps v1 used `description_type` and this was changed to `type` in v2? Is that something that should be added to the list of breaking changes or was it an oversight?

**Comment by snyaggarwal** [comment]
@bmamlin this was again just the bug with v2 (openMRS validator). Fixed this.

**Comment by snyaggarwal** [comment]
@bmamlin can we close this?

**Comment by bmamlin** [comment]
Well, almost. I tried to go test and hit another problem: the concept I was editing isn't showing in the collection. But, when I call the API directly, I see it. I tracked it down to this issue:

When the client invokes this `GET` request, the response does _not_ include the concept I was testing for this ticket (id: 2):
https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/?page=1&limit=10&q=*&sortAsc=id&timestamp=1613145015173&includeRetired=true

If you remove the `q=*` parameter from the request URL, the response _does_ include the concept (id: 2):
https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/?page=1&limit=10&sortAsc=id&timestamp=1613145015173&includeRetired=true

So, I figured I could write that up as a separate issue and validate this issue is fixed using another concept, but...

When I tried adding a description to another concept (id: 1), I now get a "field cannot be null" error. Looking at the payload, I guessed it might be the null `update_comment`, so tried manually re-submitting the update with a manually added `"update_comment": "adding description"`. As expected, the update request was accepted. However, now this concept (id: 1) is missing from the collection too.

So:
* Updating a concept appears to make it effectively "disappear" from the collection if the `q` parameter is included in the collection request
* Can't update a concept with a null `update_comment` (is this a new requirement/breaking change with v2?)

Do you want me to make separate tickets for these are handle them here? I haven't yet been able to confirm that this particular issue (missing FSN error) is fixed.

**Comment by jamlung-ri** [comment]
Looks like there is still some additional work to do here, so let's roll this over and try to address it early next week.

**Comment by snyaggarwal** [comment]
@bmamlin fixed both the issues. Please verify

**Comment by bmamlin** [comment]
@snyaggarwal,

Something still seems amiss. This call:

https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/?page=1&limit=10&q=*&sortAsc=id&timestamp=1613572847566&includeRetired=true

(with the `q=*` parameter) is 4 concepts, which is missing concepts `id=1` and `id=2`. I thought there might be some side effects from my trying to add mappings to these missing concepts before your fix, so I tried re-adding them to the collection, but that didn't help. If I make the same call without the `q=*` parameter:

https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/?page=1&limit=10&sortAsc=id&timestamp=1613572847566&includeRetired=true

the response contains 8 entries. I can see concepts `id=1` and `id=2` in the response; however, the concept with `id=2` is listed twice (`uuid`s differ, so maybe this is an artifact from my repeated attempts to get the concept to show up).

I would expect `q=*` to return everything (the same as `q=` or omitting `q` altogether).

**Comment by snyaggarwal** [comment]
@bmamlin I found the issue for search results (`?q=`) and fixed it. Now I can see its returning 7 results in concepts (matching the references).
The only thing I couldn't figure out is the multiple versions `id=2` in without `?q=` response. I tried to reproduce it from different ways at my end but couldn't. Can you please explain a bit more how you reached to this state? Did you try re-adding the same concept (different version) to the collection?

**Comment by bmamlin** [comment]
I'm still getting a `400 Bad Request` when attempting to add a description or mapping to a concept. The response says `{"update_comment":["This field may not be null."]}`, suggesting `update_comment` is now required. I didn't see this in the [list of breaking changes](https://github.com/OpenConceptLab/ocl_issues/issues/463#issue-741791698).

Is `update_comment` required now?

> The only thing I couldn't figure out is the multiple versions id=2 in without ?q= response. I tried to reproduce it from different ways at my end but couldn't. Can you please explain a bit more how you reached to this state? Did you try re-adding the same concept (different version) to the collection?

It's probably the result of multiple attempts to add the concept to the collection while not knowing the concept was already in the collection (because it wasn't included when the `q` param was included). Hopefully, with the `q` param bug fixed, this shouldn't be a problem going forward.

**Comment by snyaggarwal** [comment]
`update_comment` optional is now finally checked-in.

**Comment by bmamlin** [comment]
Confirmed concepts can be edited now. Thanks @snyaggarwal! Closing this issue.
