### ISSUE TITLE
Superuser and org owner can edit org membership (in API and oclweb2)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#573]

**Comment by jamlung-ri** [comment]
@paynejd and @jamlung-ri to review

**Comment by jamlung-ri** [comment]
@snyaggarwal Things mostly look good here. I added my own account to the PEPFAR membership using the superuser account, and I appear in the Members list and can edit the sources and collections.

However, on my user page, PEPFAR does not appears in the Organization Membership list. I don't know if it should, but it's something I noticed.
![image](https://user-images.githubusercontent.com/55999682/107980599-9160a000-6f8e-11eb-9fe9-ea49f9c62546.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri -- ES indexes were not updated on member remove/add. This is now fixed.

**Comment by jamlung-ri** [comment]
@paynejd Feel free to review further, but this is all looking good to me.
