### ISSUE TITLE
Create generic OCL overview/demo deck using v2 services

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#578]
Internally, we talk about our new tools as oclweb2 + the metadata browser, oclapi2, fhir, the new AWS infrastructure, and the new community/docs site. Externally, though, the messaging should be much simpler. We want a deck that we can pull out whenever asked and use without customization if needed.

We have a decent start of a demo deck from this presentation given to PEPFAR here:
* https://docs.google.com/presentation/d/175DBVJ5jaooF-w1pVoSOeCT7cOXLzeZKq0fG4TUNmzI/edit#slide=id.p
* https://docs.google.com/presentation/d/16yAS6zckClJRFcQHSZDdlK9jyoHwAMsQUdG0ZEdYu4g/edit#slide=id.gae5babf565_0_189

**Comment by jamlung-ri** [comment]
@paynejd I could use some help with key talking points about OCL Documentation/Website, OCL's AWS Infrastructure, and OCL API. Are you wanting to draft out these points real quick with me, or should we get others involved? Maybe we can talk about this in a 1:1 session.

**Comment by jamlung-ri** [comment]
Some notes and ideas for this are being collected here: https://docs.google.com/document/d/135GycK_fkNna0NHw85DKf0hkLjk-UU5a5BT1Gdh47xg/edit

**Comment by jamlung-ri** [comment]
This will be done in a later sprint since there is still some learning going on

**Comment by jamlung-ri** [comment]
A first draft of this deck has been completed and will be presented on the OHIN call on April 26th, 2021. The deck can be found here: https://docs.google.com/presentation/d/175DBVJ5jaooF-w1pVoSOeCT7cOXLzeZKq0fG4TUNmzI/edit?usp=sharing
