### ISSUE TITLE
Basic Resource Comparison - Development

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#579]
- [x] Formatting changes:
    - [x]  Remove unnecessary characters like "[" and "}" that start and end the value , e.g. _Applicable Periods: ["FY20"]_ should show as _Applicable Periods: FY20_ (note that there will still be some values that contain these characters)
    - [x]  Columns for each resource should stay in a consistent width. [Example link](https://web2.qa2.aws.openconceptlab.org/#/concepts/compare?lhs=/orgs/PEPFAR-Test10/sources/MER/concepts/p1OMag94BGr/&rhs=/orgs/PEPFAR-Test10/sources/MER/concepts/MfrBHKsEZAF/) where the extras.numeratorParsedFormula gets too wide
    - [x]  Attribute name can be listed one time on the left of the screen, rather than being listed with each column ([example](https://docs.google.com/presentation/d/1KPLnfOVTYL9xDJsv7JeTLwNRlNxaBpwyKBWUE_FmmUk/edit#slide=id.g8c7b17ef2b_1_0))
    - [x]  Listing elements, which start with "[" can be listed in comma- or line-separated format. Example: [FY19, FY20] could display as FY19, FY20
- [x] Empty lists or attributes should show as "--", rather than "[]"

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/528#issuecomment-761178748_

**Comment by jamlung-ri** [comment]
@snyaggarwal Looks great for the most part! I tested with a few concepts from PEPFAR and from CIEL. Listing out issues below:

- [ ] **Column spacing** 

One set of attribute text can take up a lot of horizontal space rather than the text wrapping to a new line.

Example link: https://app.qa.aws.openconceptlab.org/#/concepts/compare?lhs=/orgs/CIEL/sources/CIEL/concepts/165854/&rhs=/orgs/CIEL/sources/CIEL/concepts/165565/

Here is what I'm seeing:
![image](https://user-images.githubusercontent.com/55999682/107981043-662a8080-6f8f-11eb-9882-da735464615f.png)

- [ ] **Description Concatenating**
It looks like description text seems to be concatenating, removing spaces in the description attributes. If I look in the API call ([example that corresponds with example below](https://api.qa.aws.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/164817/)), the descriptions have spaces between words, but the Comparison screen does not.
Example link: https://app.qa.aws.openconceptlab.org/#/concepts/compare?lhs=/orgs/CIEL/sources/CIEL/concepts/164817/&rhs=/orgs/CIEL/sources/CIEL/concepts/165328/

What I'm seeing:
![image](https://user-images.githubusercontent.com/55999682/107981559-4c3d6d80-6f90-11eb-92c4-91d21c05234c.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Both above are fixed.

**Comment by jamlung-ri** [comment]
Everything seems to be working well, so I will close out this ticket.
