### ISSUE TITLE
Implement multi-hierarchy support

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#585]
We want to implement native “hierarchy” support in OCL. Currently, OCL has used mappings to define both semantic relationships and hierarchy, but mappings are an inefficient model for just capturing “parent-child” relationships within a source. We need to support “multi-hierarchy”, where a resource can have multiple children and multiple parents, meaning we will have to be smart about how we query the hierarchy to avoid endless loops. We want to optimize for fast queries, including for fast "subsumption" queries.

**Comment by paynejd** [comment]
cc @jamlung-ri 

Assigning this ticket to sprint 5 to at least address requirements. Each concept should have a property that defines its `parent_concepts` that live in the same source. `child_concepts` are then inferred from the `parent_concepts` field in other concepts in the source. Since the concepts must all live in the same source, this field only needs to store a list of concept IDs, eg:
```
{"parent_concepts": [
    "1234",
    "73",
    "39393"
] }
```

However, if it makes more sense to align with how we store relative URLs in other fields, we could also do it this way:
```
{"parent_concepts": [
    "/orgs/MyOrg/sources/MySource/1234/",
    "/orgs/MyOrg/sources/MySource/73/",
    "/orgs/MyOrg/sources/MySource/39393/"
] }
```

Open questions:
* Does order matter? (I think no)
* Is it possible for a parent-child relationship to have additional attributes/qualifiers associated with it?

**Comment by paynejd** [comment]
Additional requirement:
* Option to define one or more "root concepts" for a source -- these would be presented to a user when navigating a source as a hierarchical tree

**Comment by jamlung-ri** [comment]
Jess gave a little insight about the order of parents/children, plus other info:
- We approach it the opposite way. So when defining the child, we specify what that concept's parent(s) are.
​[3/5 12:02 PM] Jessica Bota (Guest)
- Take a brief read through the following links: https://confluence.ihtsdotools.org/display/DOCANLYT/6.2+Subsumption , https://en.wikipedia.org/wiki/Is-a#:~:text=In%20knowledge%20representation%2C%20object%2Doriented,is%20a%20superclass%20of%20A).
- As far as naming the attribute used for the relationship, we may want to consider "is-a".
- Order does not matter. But the order of adding the concepts in general will matter. You can't point to a parent that doesn't already exist.

**Comment by paynejd** [comment]
cc @snyaggarwal @jamlung-ri 
Proposed attributes for representing a single hierarchy (i.e. only one root) in an OCL source and its concepts:

**source:**
```json
{
  "hierarchy_root": "my-concept-id-1123",
  "hierarchy_meaning": "is-a",
}
```
**concept:**
```json
{
  "parent_concepts": [
    "my-parent-concept-id-1239",
    "another-parent-id-393"
  ]
}
```

When `GET`ing a concept:
```json
{
  "parent_concepts": [
    "my-parent-concept-id-1239",
    "another-parent-id-393"
  ],
  "child_concepts": [
    "another-concept-id-939"
  ]
}
```

* Some more details on the attributes:
  * `hierarchy_root` - a concept ID from the same source that serves as the highest level concept in a hierarchy
  * `hierarchy_meaning` - is-a (default) | grouped-by | part-of | classified-with; must be a value from this ValueSet: https://www.hl7.org/fhir/valueset-codesystem-hierarchy-meaning.html
  * `parent_concepts` - a hierarchy is defined by specifying a concept's parents (not the other way around), meaning that we `POST`/`PUT` with `parent_concepts`,  and we `GET` both `parent_concepts` and `child_concepts`
  * `child_concepts` - this is inferred from the `parent_concepts` field of other concepts in the same source

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Following can be reviewed:
  
- Source - `hierarchy_root`:
  - `hierarchy_root_url = concept.url` within the same source.
  - Can do this via UI as well.
- Concept - `parent_concepts` & `child_concepts`:
  - POST/PUT api supports `parent_concept_urls` - a list of concept URIs.
  - Can do this via UI as well
  
Let me know here any feedback. Thanks

**Comment by jamlung-ri** [comment]
Initial basic testing:
* Parent concept: https://api.qa.openconceptlab.org/users/jamlung/sources/test/concepts/parent/
* Child concept: https://api.qa.openconceptlab.org/users/jamlung/sources/test/concepts/child/

This might be expected, but I notice that the `parent_concept_urls `only shows a single URL 
(i.e. `parent_concept_urls : "/users/jamlung/sources/test/concepts/parent/"`), 

while the `child_concept_urls `show two URLs 
(i.e. `child_concept_urls : ["/users/jamlung/sources/test/concepts/child/201502/","/users/jamlung/sources/test/concepts/child/"]`)

**Comment by snyaggarwal** [comment]
@jamlung-ri I am looking into this.

**Comment by jamlung-ri** [comment]
Additional ideas:

- [ ] Enable Hierarchy
- [ ] Validation of Parent Concept URLs
- [ ] Ability to filter concepts by "Orphaned" i.e. concepts without parent concepts defined.

**Comment by jamlung-ri** [comment]
One issue that @snyaggarwal is aware of is Bulk Importing with a hierarchy attribtue. The attached import file for an HL7 CodeSystem (original available [here](https://app.staging.openconceptlab.org/#/orgs/Apelon-FHIR-Authority/sources/N32773/), test import available [here](https://app.staging.openconceptlab.org/#/orgs/Apelon-FHIR-Authority/sources/N32773-test/)) was used to attempt to POST concepts with hierarchy attributes, but the hierarchy attributes are not showing properly. Sunny and I will troubleshoot this.

[AddressUse-ocl-v3-hierarchy.txt](https://github.com/OpenConceptLab/ocl_issues/files/6359876/AddressUse-ocl-v3-hierarchy.txt)

**Comment by jamlung-ri** [comment]
> 
> 
> One issue that @snyaggarwal is aware of is Bulk Importing with a hierarchy attribtue. The attached import file for an HL7 CodeSystem (original available [here](https://app.staging.openconceptlab.org/#/orgs/Apelon-FHIR-Authority/sources/N32773/), test import available [here](https://app.staging.openconceptlab.org/#/orgs/Apelon-FHIR-Authority/sources/N32773-test/)) was used to attempt to POST concepts with hierarchy attributes, but the hierarchy attributes are not showing properly. Sunny and I will troubleshoot this.
> 
> [AddressUse-ocl-v3-hierarchy.txt](https://github.com/OpenConceptLab/ocl_issues/files/6359876/AddressUse-ocl-v3-hierarchy.txt)

This has been resolved, and the hierarchical test file was successfully loaded into OCL. See [this OCL source](https://api.staging.openconceptlab.org/orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/?verbose=true) for the results, and see the attached file for the new import file.

[AddressUse-ocl-v3-hierarchy.txt](https://github.com/OpenConceptLab/ocl_issues/files/6365003/AddressUse-ocl-v3-hierarchy.txt)

Note that, for the hierarchy attribute to work, the parent concepts need to be loaded in first, and then the child concepts can properly get their parent_concept_urls.

**Comment by jamlung-ri** [comment]
Keeping this ticket open since @snyaggarwal will be working on some hierarchy versioning, along with some other bugs we are noticing.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri I have added versioning support with hierarchy. I have tested locally with the few scenarios and also added some integration tests around those.
Also I have added parent/child_concept_urls as part of concept comparison screen.
This should be available on QA (in few)

**Comment by jamlung-ri** [comment]
The Parent/Child URLs on the comparison screen are looking good.

I did a little bit of testing on my own source with this [concept](https://api.qa.openconceptlab.org/users/jamlung/sources/hierarchytest/concepts/child/versions/?verbose=true), where I would add new concepts and make this concept their parent and then watch the concept get updated with a new child each time. It seems to be working well to me!

**Comment by jamlung-ri** [comment]
A little more testing done: this time I watched the parents as children were added and removed from them. This also appears to be working well.
