### ISSUE TITLE
Update CIEL bulk import on AWS for new mapping model

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#586]
The new mapping model does not require that an org and source be defined for the target of external mappings. We need to decide how we want these external org/sources to be defined in OCL, if at all, and modify the CIEL bulk import script as needed.

**Comment by paynejd** [comment]
to discuss on OpenMRS squad call on March 3, 2021

**Comment by paynejd** [comment]
Based on discussions with Andy, the big updates to the CIEL model are going to wait until after launch. For the time being, Rafal is updating liquibase scripts so that all "same as" SNOMED NP maps will now be "narrower than" SNOMED CT maps.

**Comment by kimoraw** [comment]
hoe

**Comment by kimoraw** [comment]
,
