### ISSUE TITLE
Design - Improve presentation of mappings throughout oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#589]
Presentation of mappings in oclweb2 was mostly brought over from v1 and would benefit from a complete redesign. We'll use this ticket to track design decisions and requirements.

**Comment by jamlung-ri** [comment]
Basic mockups have been drafted here: https://framer.com/share/Metadata-Browser--onB59TV7OytQ2Urr6McM/S1LkaRiYB

These are mostly to let people have reactions and iterate on the different potential mapping views.

**Comment by jamlung-ri** [comment]
@snyaggarwal, @jamlung-ri , and @paynejd  to review in our weekly meeting

**Comment by jamlung-ri** [comment]
We reviewed this earlier today, and some tweaks need to be made to the mockups. We will need a ticket for development.

**Comment by snyaggarwal** [comment]
@paynejd I tried to fix this. Take a look at the new formatting

**Comment by jamlung-ri** [comment]
The mappings formatting is now looking good. There is likely additional design work to be done on mappings, so a follow-up ticket will be created.
