### ISSUE TITLE
Automatic import of test subset of CIEL concepts/mappings into QA with each deploy?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#59]
@rkorytkowski Could you estimate the level of effort to automatically import the CIEL test metadata (a subset of concepts and mappings) into QA with each deployment? I can quickly create the import scripts.

**Comment by rkorytkowski** [comment]
I'm skipping mappings referencing external sources, which are not present in OCL. @paynejd do you have an import json file with external sources, which I could add in?

**Comment by rkorytkowski** [comment]
@paynejd ping :)
