### ISSUE TITLE
Long-running DELETE source request

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#590]
When deleting a source on staging.aws, it was successfully deleted, but the request took 1 min and 4 seconds to complete. Is there a way to speed this up from the user's perspective? Keep in mind that the user may want to create a new source with the same name immediately after the delete, which may impact the implementation approach.

**Comment by paynejd** [comment]
@snyaggarwal We may be able to close this now since we now support the `inline` delete option (which I tested and it works great). Thoughts?

**Comment by jamlung-ri** [comment]
Moving to Sprint 10 since it is not quite the highest priority

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Now you can delete a source in an async way. This is useful for bigger sources. This can be triggered with `?async=true` in DELETE source request

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?
