### ISSUE TITLE
Support for rich text tabs in oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#592]
Currently, oclweb2 displays an `About` tab on an org/source/collection page if its `text` field is populated. The `text` field support rich text and there is a rich text editor already implemented for that. We want admins to be able to configure additional "Rich text" tabs that point to an arbitrary attribute for a resource. Example: the `PEPFAR` org could have an attribute called "key-updates" with rich text data and want to add a tab to the org called "Key Updates and Changes" presenting the contents of that attribute.

Ideally, we would allow an admin to edit one of these Key Updates pages using a rich text editor directly on the corresponding tab, though for a first pass it is fine if we have them edit it simply as a custom attribute.

**Comment by jamlung-ri** [comment]
I think we have this covered in #800. Maybe we can close this?
