### ISSUE TITLE
[OCLWEB2] Password Rules - Signup & Forgot Password

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#593]
Indicators:
1. Min 8 characters
2. atleast one Number
3. at least one Character a-Z
4. must be atleast "good"!

More Validations:
1. Common Passwords (django 10k+ list)

More:
1. Password view as text option in signup and forgot password (just like login)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is done and deployed. Please verify

**Comment by jamlung-ri** [comment]
It seems to be working well! I just have a couple of quick adjustments to the password prompt text, and I think this is in good shape.
* "Must be min 8 Characters" -> "Must be 8 or more characters"
* "Must have atleast one alphabet (a-zA-Z)" -> "Must have at least one letter (a-z, A-Z)"
* "atleast" -> "at least"

**Comment by snyaggarwal** [comment]
@jamlung-ri Done. Should be available in few minutes on QA (deployment underway!)
