### ISSUE TITLE
Fix server responses for bad bulk import requests

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#596]
`DELETE` (and other weird verbs like "PURGE") to /manage/bulkimport responds the same as `GET`
`POST` and `PUT` respond with 500 errors if there is no body in the request

Desired behavior:
* GET should respond as it is
* POST if there is a body provided should submit a bulk import; POST if no body provided should respond with a valid error message
* All other requests to this endpoint should be disallowed (unless I'm missing one?)

Assume that we should apply the same approach to the new importer endpoints as well?

**Comment by snyaggarwal** [comment]
@paynejd `/manage/bulkimport/` currently only responds to GET and POST. For DELETE/PUT/etc it returns 405.
And POST without body returns `400 - {"exception":"No content to import"}`
Am I missing something?

**Comment by paynejd** [comment]
@snyaggarwal I realized that I tested this without the final backslash: `/manage/bulkimport` -- responses with the backslash included worked as expected.

Not a priority, but we probably need to improve our handling of requests with no backslash, either so it works the same (which I know is tricky with django) or that requests are all rejected consistently.

**Comment by paynejd** [comment]
this is not an actual issue - closing it out
