### ISSUE TITLE
Delete concepts directly from a collection

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#600]
Right now, you can only do this from the References tab, but it would be good if it showed up in these multi-select options too.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/3b40a90f-dc72-4016-80dd-a9aa1ff89a90)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done! Please try it on QA and provide feedback here.

**Comment by jamlung-ri** [comment]
Looks good! I was able to delete both concepts and mappings.
