### ISSUE TITLE
Update resource types for cached exports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#602]
Cached exports of source/collection versions have a type of `Source` or `Collection`. However, it may be more accurate for these to have a type of `Source Version` or `Collection Version`. Let's confirm this as a group.

**Comment by paynejd** [comment]
Changing source/collection versions and exports to be structured like this:
```
{
  "type": "Source Version",
  "source": {
    "type": "Source",
  },
}
```

Need to test ocldev and pepfar integration scripts after this change is made

**Comment by snyaggarwal** [comment]
@paynejd This is done.

**Comment by jamlung-ri** [comment]
@paynejd will do some testing, and @maurya will do some IMAP testing

**Comment by paynejd** [comment]
API update works as expected, however we now have a lot of exports already
cached that have the incorrect resource type. @sny should we trigger all of
them to be deleted?

Also need to test the PEPFAR scripts. That will be next

**Comment by snyaggarwal** [comment]
@paynejd We can delete all the exports from S3 directly to save time. Let me know if that needs to be done.
