### ISSUE TITLE
Include references attribute in collection exports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#605]
The collection export should include the `references` attribute, but it is currently missing

**Comment by snyaggarwal** [comment]
@paynejd references were not part of the collection export in v1.

**Comment by snyaggarwal** [comment]
@paynejd This is done and recorded as a new change in the export collection JSON at https://github.com/openconceptlab/ocl_issues/issues/463#issuecomment-786567602

**Comment by paynejd** [comment]
Updated title so that this doesn't look like a bug -- I thought we had this in v1, but apparently not! Just tested and this is working great.
