### ISSUE TITLE
Update logic for calculating the timestamp of a cached export

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#607]
Exports are sometimes recreated even when they don't need to be resulting in a slow export request. This appears to be happening because of the way the `last_updated` timestamp is calculated on exports.

We can use the PEPFAR IMAP import/export scripts to test this -- after running the import script, the first two export requests in the IMAP export script always have to be regenerated, adding another 20seconds to the script runtime.

**Comment by paynejd** [comment]
last concept `updated_at`
last mapping `updated_at`
resource `updated_at`

Source A
Source B

- creating a new mapping in source B with from concept in source A -- results in source A's export being treated as out-of-date

**Comment by paynejd** [comment]
The first change to make will be so that when a mapping is created/updated, that its source/target concepts will be re-indexed directly rather than re-saved, which triggers a re-index but also updates their last-updated timestamp. This update should have a noticeable improvement on the export performance for PEPFAR IMAPs/QMAPs

**Comment by snyaggarwal** [comment]
> The first change to make will be so that when a mapping is created/updated, that its source/target concepts will be re-indexed directly rather than re-saved, which triggers a re-index but also updates their last-updated timestamp. This update should have a noticeable improvement on the export performance for PEPFAR IMAPs/QMAPs

@paynejd This is done.

**Comment by paynejd** [comment]
The update worked great! This one change reduced IMAP import/export average processing time by 10 seconds

**Comment by maurya** [comment]
This is great. The exports for both new and existing have been taking ~ 6 seconds (compared to ~30 seconds earlier).
