### ISSUE TITLE
Update ocl_datim to python3

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#609]
Use this branch: https://github.com/OpenConceptLab/ocl_datim/tree/oclapi2-update

**Comment by jamlung-ri** [comment]
~50% done, can focus on after launch

**Comment by snyaggarwal** [comment]
@paynejd Please add here anything left on this. Will keep this ticket until python3 branch is merged in master.

**Comment by snyaggarwal** [comment]
@paynejd Closing this out. Since python3 branch is merged.
