### ISSUE TITLE
Find and resolve data integrity issues

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#61]
We need to have a task, which will discover any broken references and resolve them appropriately. To start with I'll list here all references in our model and then implement checks.

It should be possible to run the new data integrity task periodically.

**Comment by paynejd** [comment]
Can we also keep a log of broken references that are found so that we can
analyze this in the future and hopefully begin to resolve the root of any
problems that are found?

**Comment by rkorytkowski** [comment]
Yes, I'm planning to do that as well.

**Comment by rkorytkowski** [comment]
Checks implemented. There's a new endpoint at /manage/brokenreferences/, which lists all broken references. Next, I'm planning to indicate, which broken objects can be safely deleted i.e. which are not referenced elsewhere and implement a POST request to do the actual deletion.

**Comment by paynejd** [comment]
@rkorytkowski Have you added this new endpoint to the API wiki?
