### ISSUE TITLE
Loading all PEPFAR metadata into AWS environment

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#611]

**Comment by paynejd** [comment]
Current state:
* MOH:
  * FY19 and FY20 MOH codelists are loaded on staging.aws
  * Test IMAPs are loaded into staging.aws
* DASH:
  * Aggregation directives loaded onto staging.aws
  * Test QMAPs loaded onto staging.aws
* MSP:
  * Initial round 10 import loaded onto staging.aws

What's next:
* Create `datim_admin` user on AWS production
* MOH
  * Load results of imapbackup.py on api.v1.openconceptlab.org into api.staging.aws.openconceptlab.org
  * Load FY19 and FY20 codelists onto production aws
  * When we're ready to launch and the above step is validated, load results of imapbackup.py on api.v1.openconceptlab.org into api.aws.openconceptlab.org
* DASH: n/a (no further content needed on staging, and not promoting to production yet)
* MSP: n/a (tracking this in separate tickets: #546 and #547)

**Comment by jamlung-ri** [comment]
Sunny did a PEPFAR load on QA AWS, which needs to be verified. Will create a follow-up ticket for verification.
