### ISSUE TITLE
PEPFAR IMAP performance improvement with new parallel bulk import endpoint

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#613]
Follow up of #545 
 
 Currently, an export is taking 50 seconds and a subsequent export is taking 30 seconds. 
 
 Should improve the initial export to at least 30 seconds.

**Comment by paynejd** [comment]
Note that #615 is the first ticket we are taking on related to this

**Comment by paynejd** [comment]
#607 closed and tested on staging.aws using the PEPFAR IMAP import/export scripts, resulting in an average of 10 seconds reduction in process time for each of these operations.

#615 was also completed (currently in review/testing pipeline), which means that we are now ready to modify the PEPFAR IMAP and QMAP import scripts to use the new bulk import endpoints, which do parallel processing of resources, and then test this out in staging.aws.

**Comment by paynejd** [comment]
https://api.qa.aws.openconceptlab.org/swagger/ —
POST /importers/bulk-import-parallel-inline/

**Comment by paynejd** [comment]
the IMAP/QMAP scripts take advantage of OCL's bulk import queue feature, which is not available in the inline/parallel versions. We'll discuss this on a future architecture call, but putting this ticket into the backlog for now since this is now a bigger undertaking.

**Comment by paynejd** [comment]
ocldev was updated (v0.1.87) to allow posting bulk imports to either the standard importer (the same as before) or to the parallel importer. Final step is to test out the new importer method in `ocl_datim`

**Comment by paynejd** [comment]
This was tested against ocldev v0.1.88 and it works as expected. IMAP import times were improved from 120 seconds to <30 seconds using the new parallel bulk import process.
