### ISSUE TITLE
Final OpenMRS Client Testing for oclapi2

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#614]
To be completed by other OpenMRS people

**Comment by jamlung-ri** [comment]
Potential future requirement: Ordering mappings (i.e. having a primary mapping, a secondary, etc.)

**Comment by paynejd** [comment]
@bmamlin Assigning this ticket to you so that we can track any remaining testing items

**Comment by bmamlin** [comment]
Defined oclclient-stg2 to run at openmrs.staging2.openconceptlab.org [here](https://github.com/openmrs/openmrs-contrib-ansible-docker-compose/commits/master) and [here](https://github.com/openmrs/openmrs-contrib-itsmresources/commit/8a1ce42239efa2d169b62e1a2ce6d22b0f0693fe).

- [ ] I need someone to add `openmrs.staging2.openconceptlab.org` to OCL's DNS (pointing to nakuru.openmrs.org at 149.165.157.84)
- [ ] Once it's working, I'll add this to CI to update automatically with client changes

**Comment by paynejd** [comment]
@bmamlin- Added openmrs.staging2 to OCL DNS

**Comment by paynejd** [comment]
@bmamlin are we ready to close this ticket?
