### ISSUE TITLE
[oclapi] Wrong organisations returned for users

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#616]
I'll preface this with the note that AFAICT this only affects v1 of the API. It is, however, a blocker for us being able to deploy organisation-related features for the OCL for OpenMRS client.

In the OCL for OpenMRS client, to discover what organisations a user is a member of, we make an authenticated request to `/user/orgs`. When I make this request to the backend for production using my own OCL account, I get this response:

```json
[
    {
        "id": "MUDHC",
        "name": "Mekelle University Digital Health Center",
        "url": "/orgs/MUDHC/"
    },
    {
        "id": "MSF",
        "name": "Médecins Sans Frontières / Doctors Without Borders (MSF)",
        "url": "/orgs/MSF/"
    },
    {
        "id": "MU",
        "name": "Mekelle University",
        "url": "/orgs/MU/"
    },
    {
        "id": "MUDH",
        "name": "Mekelle University Digital Health Center",
        "url": "/orgs/MUDH/"
    },
    {
        "id": "nproto",
        "name": "prototipo",
        "url": "/orgs/nproto/"
    },
    {
        "id": "MSFTW",
        "name": "MSFTW",
        "url": "/orgs/MSFTW/"
    },
    {
        "id": "TWABC",
        "name": "TWABC",
        "url": "/orgs/TWABC/"
    },
    {
        "id": "Dumby",
        "name": "Kuunika Test",
        "url": "/orgs/Dumby/"
    },
    {
        "id": "sample-test-dev-kuunika",
        "name": "Kuunika Testers Org",
        "url": "/orgs/sample-test-dev-kuunika/"
    },
    {
        "id": "kuunika-registries",
        "name": "Kuunika Data For Action",
        "url": "/orgs/kuunika-registries/"
    }
]
```

Now, I'm not a member of *any* of these organisations, nor, to the best of my knowledge, is my account marked as either a staff or superuser account (and if it is, it definitely shouldn't be).

To make matters worse, if I instead request `/user/orgs/?limit=0`, I now appear to be a member of a whole host of organisations for which I am not a member, including the OCL and CIEL organisations. Even more strange, if I change the limit parameter to `?limit=20` (for example), I not only get the list of organisations above, but then the backend returns even more organisations, enough to pad this returned list out to 20 organisations.

To be clear, this doesn't effect actual backend permissions. For example, I cannot actually modify CIEL concepts. It does, however, make it impossible for our client application to work out which organisations a user is actually a member of (which affects how we display certain properties to the user).

To work around this issue, there is a second URL we can use, e.g. `/users/ibacher/orgs`. This URL appears to work correctly for either the raw case or where `limit=0`, but when we add the `sortAsc=name` parameter (to sort the organisations alphabetically, it now doesn't filter the returned organisations based on user at all, so that e.g., `/users/ibacher/orgs?sortAsc=name` is just an alphabetical list of all organisations (this also happens when using the `?sortAsc=name` parameter on 	`/user/orgs/`.

**Comment by paynejd** [comment]
Ian- have you by chance tested this in v2?

**Comment by ibacher** [comment]
Yes. None of this applies to v2, except that `sortAsc=name` doesn't seem to do anything, e.g., https://api.qa.aws.openconceptlab.org/orgs?sortAsc=name.

**Comment by paynejd** [comment]
We'll discuss this on tomorrow's dev call -- the approach depends on the timeline for launching ocl api v2.

**Comment by snyaggarwal** [comment]
@paynejd @ibacher The sort is fixed in v2.

**Comment by paynejd** [comment]
@ibacher Do we need to fix this in v1 or want to just confirm that the new organisation-related features in the OMRS client work with v2?

**Comment by ibacher** [comment]
@paynejd I actually think it's probably safe to close this. We can work around the issue by doing the sorting on the frontend and I'm hoping v2 will be the version we're using soon.
