### ISSUE TITLE
Add license to all current code repositories

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#620]
All code repositories need to have the appropriate code license. We use the MPL v2.0 with Healthcare Disclaimer, which is the same license as OpenMRS. Suggest that we look at the OMRS code repos to see how they include this license there.

**Comment by snyaggarwal** [comment]
@paynejd The openmrs license -- https://github.com/openmrs/openmrs-core/blob/master/LICENSE has a footer in the end 
https://github.com/openmrs/openmrs-core/blob/352f3d5d727503543a2a74bc69cedb0fb702a323/LICENSE#L400.

Do we want to change that to say OCL?

**Comment by paynejd** [comment]
I think no need for copyright in the license. Let's just remove it

**Comment by snyaggarwal** [comment]
Added in ocldev/oclapi2/oclweb2

**Comment by harpatel1** [comment]
Added in oclfhir

**Comment by snyaggarwal** [comment]
Added in oclinfrastrucure
