### ISSUE TITLE
Implement OpenAPI / Swagger for OCL on FHIR

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#621]
We'd like to expose the FHIR APIs via swagger/OpenAPIs in the same way that the oclapi2 is. This also means that we won't have to manually update a postman collection for this!

Assigned to sprint 6 for now, but we can modify that based on what makes sense...

**Comment by paynejd** [comment]
Here's a good non-OCL example:
https://id.who.int/swagger/index.html

**Comment by harpatel1** [comment]
https://fhir.qa.aws.openconceptlab.org/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

**Comment by harpatel1** [comment]
Application root will be redirected to swagger document - https://fhir.qa.aws.openconceptlab.org/
