### ISSUE TITLE
CIEL Content Feedback and Issues

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#622]
Andy will list out any bugs he finds while looking through CIEL content on [AWS Staging](https://app.staging.aws.openconceptlab.org/#/orgs/CIEL/).

**Comment by askanter** [comment]
On the mapping tab, the maps show the FROM source and not the TO source (i.e., they have CIEL with the SNOMED code listed)

**Comment by askanter** [comment]
When creating a custom tab, the customizations do not appear to show on the filters:
{
      type: 'concepts',
      label: 'Problems',
      layout: 'List',
      default: false,
      filters: {
        concept_class: 'Diagnosis'
      },
      page_size: 25
    },

1) the List or Row parameter for layout doesn't apply.
2) how do I create a filter for two concept_classes together (OR)?
3) how do I set default sort (Name, alpha ascending)

**Comment by askanter** [comment]
When Changing sort to "Name" the default sort is descending Z->A . Default for name should be ascending.

**Comment by askanter** [comment]
When editing a CIEL concept in the browser, all names/descriptions do not have a type and therefore cannot be saved. The UI appears to default a null type to FULLY SPECIFIED, but that does not apply when saving an edited version. Correct behavior should be to convert null types to fully specified upon editing.

**Comment by jamlung-ri** [comment]
>     1. the List or Row parameter for layout doesn't apply.
@askanter Is this still happening? I was looking at the CIEL Default config, and it seemed to reflect the JSON config file. The Problems tab and the Drugs tabs appear as List View. Maybe I am misunderstanding the issue.

>     2. how do I create a filter for two concept_classes together (OR)?
To set a filter for concept_class = "123" or concept_class = "abc",  you can use 
`filters: {
        concept_class: '123,abc'
      },`

(Note that there is NOT a space after the comma. A space will make the filter not work.)

>     3. how do I set default sort (Name, alpha ascending)
Default sort is being addressing in ticket #647

**Comment by askanter** [comment]
Awesome. The default view seems to work now. How do I set a config file to be the default for the source?

-------------------- 
Andrew S. Kanter, MD MPH FACMI FAMIA

Asst. Prof. of Clinical Biomedical Informatics and Clinical Epidemiology
Columbia University
Email: ***@***.*** / ***@***.***
Mobile: +1 (646) 469-2421
Skype: akanter-ippnw
Yahoo: andy_kanter 

    On Tuesday, March 16, 2021, 6:56:32 AM CDT, Joseph Amlung ***@***.***> wrote:  
 
 


1. the List or Row parameter for layout doesn't apply.


@askanter Is this still happening? I was looking at the CIEL Default config, and it seemed to reflect the JSON config file. The Problems tab and the Drugs tabs appear as List View. Maybe I am misunderstanding the issue.

2. how do I create a filter for two concept_classes together (OR)?


To set a filter for concept_class = "123" or concept_class = "abc", you can use
filters: { concept_class: '123,abc' },

(Note that there is NOT a space after the comma. A space will make the filter not work.)

3. how do I set default sort (Name, alpha ascending)


Default sort is being addressing in ticket #647

**Comment by askanter** [comment]
There is no way for me to create a new collection in the UI (permission issue)? If so, please fix.

**Comment by jamlung-ri** [comment]
> 
> Awesome. The default view seems to work now. How do I set a config file to be the default for the source?

Under the Manage View Configurations screen, the Default button makes your view the default (see example image).

![image](https://user-images.githubusercontent.com/55999682/111325174-d1747a80-8641-11eb-9f88-23a0391bd5a6.png)

**Comment by jamlung-ri** [comment]
> 
> 
> There is no way for me to create a new collection in the UI (permission issue)? If so, please fix. Same is true for adding mappings and concepts (from the appropriate screens. I can only add concepts and mappings from the source screen.

@askanter Since you're a member of CIEL, then you should be able to make concept, mappings, collections, etc. Just to make sure, you are not seeing these prompts on OCL?

On https://app.staging.aws.openconceptlab.org/#/orgs/CIEL :
![image](https://user-images.githubusercontent.com/55999682/111325996-945cb800-8642-11eb-8620-e62322f8d065.png)

On https://app.staging.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/ : 
![image](https://user-images.githubusercontent.com/55999682/111326065-a179a700-8642-11eb-8b84-5bce8410af22.png)

**Comment by askanter** [comment]
Yes, but I would want to be able to add a new collection when I have selected concepts like in the old UI. Add to Collection should provide a way to create and add at the same time. For mappings, they should be added at the concept level with the from concept pre-determined.

**Comment by jamlung-ri** [comment]
> Yes, but I would want to be able to add a new collection when I have selected concepts like in the old UI. Add to Collection should provide a way to create and add at the same time. For mappings, they should be added at the concept level with the from concept pre-determined.

Oh, I understand now. I think that's on our radar but I'll make sure there's a ticket.

**Comment by askanter** [comment]
Also, when assigning a locale to a collection, there are multiple duplicates in the list (en, es, fr, etc.)

**Comment by snyaggarwal** [comment]
Fixed -- Multiple locales https://github.com/OpenConceptLab/ocl_issues/issues/622#issuecomment-800318005

Will be available in next Staging deployment

**Comment by jamlung-ri** [comment]
> 
> 
> Yes, but I would want to be able to add a new collection when I have selected concepts like in the old UI. Add to Collection should provide a way to create and add at the same time. For mappings, they should be added at the concept level with the from concept pre-determined.

This was completed in #652 and should be deployed soon.

**Comment by snyaggarwal** [comment]
> When Changing sort to "Name" the default sort is descending Z->A . Default for name should be ascending.

This is done

**Comment by jamlung-ri** [comment]
@askanter just FYI, default sort has been addressed in ticket #647

**Comment by askanter** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/24284566/113587590-9e942580-95f4-11eb-984b-91fb394349d3.png">

Not positive, but I think the locales are not meant to be sentence cased. ISO standard is lower case.

**Comment by askanter** [comment]
Not sure what is happening here with the display of the first few lines of mappings in CIEL:
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/24284566/113587747-d9965900-95f4-11eb-8880-0396b5683525.png">

**Comment by askanter** [comment]
Please add askanter to the CIEL organization so that I can test editing capabilities.

**Comment by askanter** [comment]
Low priority but on editing a mapping, the preferred concept name does not appear on this screen:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/24284566/113589864-84a81200-95f7-11eb-985a-7ef246269983.png">

**Comment by askanter** [comment]
Duplicate sources appearing in edit mapping:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/24284566/113590079-ccc73480-95f7-11eb-9a97-73659396b7b2.png">

**Comment by askanter** [comment]
BTW--a possible suggestion, when editing a mapping, the mapping type is not the first thing you should see. It seems that what you care about is the TO CONCEPT and the mapping type (in that order). The FROM CONCEPT should be obvious, but if we are going to be able to see the full information, the easiest way to edit this is just use the same layout as displayed but allow for changing the data (drop down for mapping type, replace button for the TO CONCEPT, etc.

**Comment by jamlung-ri** [comment]
> 
> 
> Please add askanter to the CIEL organization so that I can test editing capabilities.

@askanter I just added you to https://app.staging.aws.openconceptlab.org/#/orgs/CIEL/

**Comment by askanter** [comment]
Search results are inexplicable. See below search for "breast malignant"
![image](https://user-images.githubusercontent.com/24284566/113619919-3ad32200-961f-11eb-9199-4d2409844560.png)

**Comment by jamlung-ri** [comment]
Closing this out for now since we have addressed this, but feel free to create a new ticket or reopen this ticket if more issues arise. We will be documenting other CIEL needs here: https://docs.google.com/document/d/1kwC-AOi_tkzWGw33G5ieLz9i6wSimh8RzXzCl-NRg_M/edit#
