### ISSUE TITLE
[OCLAPI2] Make sure all query parameters are present in Swagger

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#623]

**Comment by jamlung-ri** [comment]
Sunny has done some work but not fully complete since the code is still being worked.

**Comment by jamlung-ri** [comment]
This is another perpetual ticket that should be done with each API ticket.

**Comment by jamlung-ri** [comment]
@snyaggarwal Is Swagger pretty much up to date with regard to query parameters? If so, we can probably close this out.

**Comment by snyaggarwal** [comment]
Will create new ticket to manage this for future features. Closing this out,
