### ISSUE TITLE
Create OCL Branding page in docs.ocl

### ISSUE THREAD

**Issue by kaalcumm** [OpenConceptLab/ocl_issues#624]
Hi Sunny,

Would you be able to add branding items to docs.openconceptlab.org (logos fonts, styles, colors, etc.)? Would you be able to do this by the end of the week?

Let me know if you have any questions! 

Thank you!

**Comment by snyaggarwal** [comment]
#### COLORS:
- WHITE = '#FFF';
- BLACK = '#000'; # secondary color
- BLUE = 'rgb(51, 115, 170)';  #  primary color, as well as concept/mapping color
- GREEN = '#5cb85c';  # source/collection color
- ORANGE = 'rgb(253, 164, 41)';  # user/org color
- DARKGRAY = 'rgb(119, 119, 119)';  # tertiary 
- COLOR_ROW_SELECTED = 'rgba(119, 119, 119, 0.16)';  # row selection
- RED = '#c33';  # retired color
- ERROR_RED = '#f44336';  # error color
- DIFF_BG_RED = '#ffeef0';  # comparison color
- DIFF_HIGHLIGHT_RED = '#fdb8c0';   # comparison color
- DIFF_BG_GREEN = '#e6ffed';  # comparison color
- DIFF_HIGHLIGHT_GREEN = '#acf2bd';  # comparison color

#### FONT:
- Font Family -- "Roboto", "Helvetica", "Arial", sans-serif
- Font Weight -- 400;
- Line-height: 1.43;
- Letter-spacing: 0.01071em;

#### Design Guideline:
- [Material Design](https://material.io/design)

#### Icons:
- [Material Icons](https://material.io/resources/icons/)

**Comment by paynejd** [comment]
@kaalcumm @jburnsthomas do you have a link to the branding/style google doc that Tim put together? Can we merge these into that?

**Comment by kaalcumm** [comment]
@paynejd  - Is this the document you're referring to? https://docs.google.com/drawings/d/1wjZb49gApgvNU7YzkDU-26-5kWHUjywSaCzIyePXgOA/edit

**Comment by paynejd** [comment]
@kaalcumm that's the one!

**Comment by kaalcumm** [comment]
@maurya - Would you be able to take the branding information in this and create a document in the OCL readthedocs for these branding guidelines? 

I think it would also be helpful to have the two current logos in there as well (attached). Please let me know what you need from me! 
![OCL-MainLogo-TransparentBackground](https://user-images.githubusercontent.com/71408554/111494657-0ac9ea80-8715-11eb-9ef1-47cf4c6acf2a.png)
![OCL-MainLogo-WhiteBackground](https://user-images.githubusercontent.com/71408554/111494660-0b628100-8715-11eb-8c16-2a50b0c1bb0f.png)
![OCL-SmallBoxLogo-TransparentBackground](https://user-images.githubusercontent.com/71408554/111494661-0b628100-8715-11eb-9031-1163c5bcd7f7.png)

**Comment by maurya** [comment]
added the page here - https://docs.openconceptlab.org/en/latest/ocl/branding.html
