### ISSUE TITLE
[OCL UI 2] View Concept Details shows no hint that some mappings are hidden

### ISSUE THREAD

**Issue by djazayeri** [OpenConceptLab/ocl_issues#629]
I looked at the new OCL UI for the first time, and peeked at a concept (Hypertension, https://app.qa.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/117399/details/) and then clicked on the inverse mapping to get to Reference Application Allergic Reactions (https://app.qa.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/162555/details/).
I was then confused that I didn't see Hypertension in the list of mappings.

The problem is that the set has many more mappings than are visible, but there's no visual hint of this.

Using Chrome on a Mac, I have to do a two-finger scroll over that panel in order to even see a scrollbar.

**Comment by snyaggarwal** [comment]
@djazayeri I have added counts on the label of mappings to indicate that there are more.
