### ISSUE TITLE
Update internal/external mapping logic in oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#633]
Mappings are incorrectly being labeled as "external" in `oclweb2` -- actually, it appears that _all_ mappings are labeled as external, or at least all that I have looked at. Take a look at these two examples:
* https://app.qa.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/117399/details/
* https://app.qa.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/162555/

All of the mappings that are pointing from a CIEL concept to another CIEL concept are labeled "External" but they are actually internal.

Assuming that this is due to the change in the underlying mapping model and easy to address, but we can add to discussion on upcoming Architecture call if useful

**Comment by snyaggarwal** [comment]
@paynejd Right now any mapping with external_id is marked as external mapping on UI.
Let me know what it should be.

**Comment by paynejd** [comment]
Ah, that makes sense! That flag should work a little differently--
"Internal" means that the mapping is pointing to a concept that is defined
in OCL. "External" means that it points to a concept that is not defined in
OCL. If OCL can generate a link to the concept's details, then it's an
internal mapping.

**Comment by snyaggarwal** [comment]
@paynejd Great! Going into bit more details:

External mapping rules:
1. When from_concept and to_concept both are not defined in OCL -- YES
2. When one of from/to_concept is defined in OCL and the other is not?
3. When from/to_source are defined in OCL but either of from/to_concept not defined or they are both not defined (kind of like point 1)?

**Comment by paynejd** [comment]
We're getting rid of the idea of "internal" and "external" mappings -- instead, the interface should visually indicate whether the from and/or to concept is available on OCL. Or "resolvable" on OCL. Verified, validated.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri I have added Icon indicators (with tooltip) for this. Please take a look at it on QA, and provide feedback.

**Comment by jamlung-ri** [comment]
This looks good to me!

**Comment by paynejd** [comment]
Logic looks good. Couple of thoughts:
* Under "Mappings", the tooltip for the icon should read "Target concept is/is not defined in OCL"
* Under "Inverse mappings", the tooltip for the icon should read "Source concept is/is not defined in OCL"
* Suggest using `Link` and `LinkOff` material icons instead of the current ones
* On concept details page, mouse-over of a mapping to a concept that exists should underline the text to make it clear that it will click thru to the concept
* Add a tooltip to the magnifying glass - "View mapping details"

**Comment by snyaggarwal** [comment]
@paynejd https://github.com/OpenConceptLab/ocl_issues/issues/633#issuecomment-800322286 is done.
