### ISSUE TITLE
[oclapi2] [bug] [ES] Resources with extras schema different from other not indexed.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#637]
https://github.com/elastic/elasticsearch-dsl-py/issues/1492

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski @jamlung-ri  As per our discussion in the last dev call, the exact fields are flattened and converted to strings. _(Reindexing running in QA/Staging at the time of writing this)_

The queries have changed a bit: (notice the **double underscore** `__`)
`?extras.exists=questionnaire_choice_value.code` --> `?extras.exists=questionnaire_choice_value__code`
`?extras.exact.questionnaire_choice_value.code=foobar` --> `?extras.exact.questionnaire_choice_value__code=foobar`
`?extras.questionnaire_choice_value.code=foobar` --> `?extras.questionnaire_choice_value__code=foobar`

**Comment by paynejd** [comment]
@jamlung-ri @paynejd 
The new syntax requires changes to MSP and PEPFAR integration scripts. Added to architecture call for discussion

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri 
fixed the syntax -- 
Both works now `.` and `__`, so ideally now you dont have to change anything in the scripts. Examples:
`?extras.exists=questionnaire_choice_value.code` & `?extras.exists=questionnaire_choice_value__code`
`?extras.exact.questionnaire_choice_value.code=foobar` & `?extras.exact.questionnaire_choice_value__code=foobar`
`?extras.questionnaire_choice_value.code=foobar` & `?extras.questionnaire_choice_value__code=foobar`

**Comment by jamlung-ri** [comment]
Will create a follow-up ticket for testing in case issues come up from this.
