### ISSUE TITLE
OCL CI builds crashing openmrs bamboo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#639]
@Sny @Jon @Rafal Korytkowski We’ve been having issues lately were our build agents are less stable than they’ve normally been. The issue seems to be related to the build for OCL API 2. There seems to be an intermittent issue where sometimes while starting the docker containers as part of the job, the Bamboo heartbeat to the agent fails. When this happens, Bamboo abandons the job and the containers are left running on the build agent. Agents with these containers running then seem to fail jobs, presumably because of memory constraints on the agent.

Some example builds that seem to have caused this issue are https://ci.openmrs.org/browse/OCL-OCLAPI2-436 and https://ci.openmrs.org/browse/OCL-OCLAPI2-430.

I suppose the constructive ask here would be whether it’s possible to modify the containers run in the CI environment so they use up less memory… our CI agents are not terribly beefy machines (2 CPUs, 254 MB - 432 MB of memory)

**Comment by rkorytkowski** [comment]
It seems to be worth trying running a build task within Docker so that cleanup can be easily handled by the agent...

I've tried enabling Docker as a runtime for a build task on Bamboo, but it fails with: 
```
/tmp/runInDocker7138736884600095077.sh: line 4: /home/bamboo-agent/bamboo-agent/temp/OCL-OCLAPI2-BO-440-ScriptBuildTask-6065981184565491527.sh: not found
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
https://ci.openmrs.org/browse/OCL-OCLAPI2-440

Apparently the agent is not configured to use Docker as runtime (bamboo user needs access to /var/run/docker.sock, see https://community.atlassian.com/t5/Bamboo-questions/Cannot-connect-to-the-Docker-daemon/qaq-p/310527)

@cintiadr could you please check that for us?

**Comment by cintiadr** [comment]
So, if my suspicious is correct, adding that build into a docker container _will not_ fix the problem. 

If the build is using too much memory, to the point of the bamboo agent becoming unresponsive, it will _not_ clean a previously created docker container. Bamboo will assume that the machine went down. 

I'd ask the first question is: can we limit the amount of memory those containers are using, and get them to run under 1.5GB? 
If not, I think  I will have to increase size on at least one container. 

Docker installation is pretty normal (socket is in /var/run/docker.sock, but that file is owned by root as it needs), BUT running docker _inside_ docker is a little bit hard. Usually those containers are running as root as well. 

Let me grant you access to the bamboo agents.

**Comment by cintiadr** [comment]
@rkorytkowski , you should be able to ssh and sudo onto any bamboo agent. 

This is some info on how to restart and some relevant folders: https://github.com/openmrs/openmrs-contrib-itsmresources/wiki/Service-Bamboo

**Comment by rkorytkowski** [comment]
@snyaggarwal my guess is that the easiest way to reduce memory usage would be to lower the concurrency limit in celery workers for running tests / development? Am I right?

**Comment by snyaggarwal** [comment]
@rkorytkowski tests only need api and db containers. Nothing else.

**Comment by cintiadr** [comment]
You might want to put hard limits in docker-compose, both in CPU and memory as well.

**Comment by rkorytkowski** [comment]
Adjusted the build to only fire up api and db containers for tests and set memory limit for api container to 400 MBs. The RAM consumption is down to 350 MB. It used to be 600 MBs more. Hopefully it is enough to resolve the issue.

**Comment by snyaggarwal** [comment]
@rkorytkowski Can we close this?
