### ISSUE TITLE
Update API Reference Documentation

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#645]
Update Manual docs in Read the docs for V2 API
Add the new mapping model

**Comment by jamlung-ri** [comment]
Tied to mapping model testing #545. Will do post-launch

**Comment by jamlung-ri** [comment]
To discuss during OCL Dev call since this topic will take more time to address

**Comment by jamlung-ri** [comment]
In Sprint 9 - expectations (assignees TBD on Dev call on 27 April 2021):
* OCL v2 Release Notes
* Bulk Import API documentation updated -

**Comment by paynejd** [comment]
closing this old ticket
