### ISSUE TITLE
Org/Source Configuration - Add "default sort" feature

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#647]
A user should be able to specify an attribute by which to sort the results list. "Best Match" should be one of the available options too.

Also, the default alphabetical sort for the "default sort" attribute should be A->Z (ascending) rather than Z->A.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! It looks like there are now more sorting options in the UI. Are there any examples of the _default sort_ syntax to test in the config file?

**Comment by snyaggarwal** [comment]
@jamlung-ri Yes, I have added all the sort options supported by API for each resource.
Default sort option is pretty similar to what's API used to:
within each tab config --
```
tabs: [
    {
      type: 'concepts',
      label: 'Other Concepts',
      filters: {
        concept_class: '!data element,reference indicator,indicator'
      },
      sortAsc: 'score'
    },
    {....}
    ]
```

1. `sortAsc: name` for default sorting on the name in ascending order and `sortDesc: name` for default sorting on the name in descending order
2. `sortAsc: score` and `sortDesc: score` for sorting on "Best Match"

**Comment by jamlung-ri** [comment]
Perfect! This works great! I tested it with several sort patterns, and it all seems to work well.

**Comment by snyaggarwal** [comment]
@jamlung-ri Great! Can we close this?

**Comment by jamlung-ri** [comment]
Whoops, thought I did. Closing!

**Comment by jamlung-ri** [comment]
@snyaggarwal There seems to be a bug at the moment with SortAsc and SortDesc. I am able to update the MSP configuration with it, and it shows properly on the screen, but when I try to update the config itself (i.e. PUT), I get an error that says Invalid Sort Configuration.

![image](https://user-images.githubusercontent.com/55999682/160121071-ffcbde83-c9f0-463e-9174-11751a3d50ee.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri for concepts the attribute for name to sort is `_name`.
I have just updated the configuration and it worked fine. Probably need to work on error notifications

**Comment by snyaggarwal** [comment]
@jamlung-ri The reason for `_name` is because we have to index `name` attributes in multiple ways for full/partial text search and sort doesn't work on text attributes in ES world. So we index it again as keywords under `_name` attribute.

**Comment by jamlung-ri** [comment]
Ah okay, that makes sense. This is working in the TermBrowser now, and I fixed the documentation to reflect this too. Thanks!
