### ISSUE TITLE
Optimize weighting of concept search results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#649]
We want to optimize weighting of all search results, but getting concepts right is the most critical, so we'll start there.

The biggest test is this: If I search for "Malaria" an exact match of "Malaria" on a fully specified name should be result number 1.

Let's discuss weighting on an upcoming dev/architecture call

@rkorytkowski I recall that you helped tweak search weighting in OpenMRS, so we'd welcome your input

**Comment by askanter** [comment]
I can start putting examples of bad search results here. I searched for 'covid vaccine' in CIEL and did not get ANY COVID results. "COVID-19 vaccine" is in numerous CIEL concepts. Tried searching '"COVID-19" vaccine' and still did not get any results (the entire dataset was returned)

**Comment by askanter** [comment]
When you search for something with a filter on (I had forgotten) and get no results, when you open filters, you do not see the filter that was selected (and preventing results) shown. I think it still should be shown and then it is clear what needs to be removed.

**Comment by askanter** [comment]
'severe headache' returns to results. There is a CIEL concept for Severe headache.

**Comment by paynejd** [comment]
search results should be sorted by "best match" rather than "last update" (which is the current default)

2 examples:
* Searching for “problem” - exact name match is on page 3 of results: https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/128461/ 
* Searching for “2000” - exact ID match is on page 6 of results: https://api.openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/concepts/2000/

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski 
1. I have added best match sorting option on UI. By default its sorted with best match.
2. Search query on ES uses wildcard query but gives more weight to id and name matches with exact results.
As a result of this:
1. Searching for "problem" will show "problem" exact name as first result
2. Searching for "2000" will show "2000" exact ID as first result.

**Comment by askanter** [comment]
Is this on production yet?

**Comment by snyaggarwal** [comment]
@askanter Yes this is deployed on all environments.

**Comment by rkorytkowski** [comment]
@snyaggarwal thanks! Another quick optimization to what you implemented here is boosting terms matched with "match_phrase", which will score higher documents matching terms in the exact order as provided by the user.

Also could you please create a separate issue to use n-gram tokenizers instead of wildcard queries which are inefficient?

**Comment by askanter** [comment]
I am still not getting results I would expect. For example
' vaccine' gives different results than 'vaccine' and none of the top ones are good
'COVID vaccine' returns nothing of consequence
'COVID-19 vaccine' returns none of the COVID-19 vaccines

The individual searches for Malaria or Headache severe are better!

**Comment by rkorytkowski** [comment]
@snyaggarwal I also noticed you get different results for lowercase and uppercase queries e.g. coivd and COVID. 

Do you want me to play with these now or are you still working on that?

**Comment by snyaggarwal** [comment]
@rkorytkowski 
1. lower/upper case and with/without leading/trailing spaces queries should now give same results if exact match is not on.
2. I am looking into 'match_phrase'

**Comment by snyaggarwal** [comment]
@askanter Added some optimizations. "Covid-19 vaccine" with exact match returns correct results.
"Exact Match" option is to the right of search button (magnifying glass icon) as highlighted below:
<img width="273" alt="Screenshot 2021-04-26 at 6 03 26 PM" src="https://user-images.githubusercontent.com/1858162/116083066-cf2e2300-a6b9-11eb-8fa0-0ab858175522.png">

The search results for "Covid-19 vaccine" (case insensitive) with exact match are below:
<img width="1413" alt="Screenshot 2021-04-26 at 6 01 04 PM" src="https://user-images.githubusercontent.com/1858162/116083167-f2f16900-a6b9-11eb-9b4f-6d5a7ed887c2.png">

**Comment by snyaggarwal** [comment]
@paynejd for match_phrase #745 is created. Closing this.
