### ISSUE TITLE
Switch URL attributes for mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#65]
Let's not do this right now, because it may break things, especially in the OCL-UI....

BUT, the `url` and `versioned_object_url` attributes for mappings need to be switched. See the results below:
```
{
u'to_source_owner': u'PEPFAR', u'retired': False, 
u'from_concept_code': u'TX_CURR_N_MOH_Age_Sex', 
u'versioned_object_url': u'/orgs/PEPFAR/sources/DATIM-MOH/mappings/5aa19fc5a08353004a634666/',
u'to_concept_name': u'15+, Male', 
u'to_source_url': u'/orgs/PEPFAR/sources/DATIM-MOH/', 
u'owner': u'PEPFAR', u'id': u'5aa19fc5a08353004a634667', 
u'versioned_object_id': u'5aa19fc5a08353004a634666', 
u'to_concept_code': u'RFKoE51NKAq', 
u'from_concept_name': u'TX_CURR (N, MOH, Age/Sex): Receiving ART', 
u'created_by': u'datim-admin', 
u'source': u'DATIM-MOH', 
u'version': u'1', 
u'type': u'MappingVersion', 
u'to_source_name': u'DATIM-MOH', 
u'updated_by': u'datim-admin', 
u'updated_at': u'2018-03-08T15:40:37.662', 
u'update_comment': None, 
u'to_source_owner_type': u'Organization', 
u'map_type': u'Has Option', 
u'owner_type': u'Organization', 
u'from_source_owner': u'PEPFAR', 
u'from_concept_url': u'/orgs/PEPFAR/sources/DATIM-MOH/concepts/TX_CURR_N_MOH_Age_Sex/', 
u'url': u'/orgs/PEPFAR/sources/DATIM-MOH/mappings/5aa19fc5a08353004a634666/1/', 
u'created_at': u'2018-03-08T15:40:37.603', 
u'from_source_owner_type': u'Organization', 
u'extras': None, u'is_latest_version': True, 
u'from_source_name': u'DATIM-MOH', 
u'external_id': None, 
u'from_source_url': u'/orgs/PEPFAR/sources/DATIM-MOH/', 
u'to_concept_url': u'/orgs/PEPFAR/sources/DATIM-MOH/concepts/RFKoE51NKAq/'}
```

**Comment by paynejd** [comment]
@snyaggarwal Was this resolved in oclapi2?

Note that this will not be resolved in oclapi1

**Comment by paynejd** [comment]
@snyaggarwal Can you confirm that this was resolved in v2?

**Comment by snyaggarwal** [comment]
Not yet, will be doing this in the current week.

**Comment by snyaggarwal** [comment]
Currently we have:

mapping.url --> latest version url
mapping.versioned_object_url --> mapping.uri

For example -- 
a Mapping exists inside `/users/admin/sources/s1/` with id (custom mnemonic) `solar-mapping`.
GET /users/admin/sources/s1/mappings/solar-mapping/
{
  "url": "/users/admin/sources/s1/mappings/solar-mapping/1815/",   # 1815 is the id of latest version of mapping, or this is latest version's uri
  "versioned_object_url": "/users/admin/sources/s1/mappings/solar-mapping/"
}

For version:
GET /users/admin/sources/s1/mappings/solar-mapping/1815/     # 1815 version id
{
  "url": "/users/admin/sources/s1/mappings/solar-mapping/1815/",
  "versioned_object_url": "/users/admin/sources/s1/mappings/solar-mapping/"
}

@paynejd This makes sense to me, why do we need to switch?

**Comment by paynejd** [comment]
For most mapping requests, `url` is incorrectly set to the versioned URL, and they are generally missing `version_url`. Here's how the "url" fields are supposed be used, and this needs to be consistent across the OCL API in v2:
* `url` -- This is the parent URL with no version stem: `/users/admin/sources/s1/mappings/solar-mapping/1815/`
* `version_url` -- This is the URL to a specific resource version: `/orgs/CIEL/sources/CIEL/concepts/654/5f7c58950055580001e15ac5/`
* `versioned_object_url` -- This is not a valid field in the API; remove this
* `previous_version_url` -- This should be returned when requesting a list of resource versions; note that it is missing for mappings

---
Here are the "url" fields in all concept/mapping queries below from oclapi v1:

https://api.openconceptlab.org/concepts/
```
    "version_url": "/orgs/OCL/sources/Classes/concepts/Test/5821802445b0130007aaa65b/",
    "url": "/orgs/OCL/sources/Classes/concepts/Test/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/
```
    "version_url": "/orgs/CIEL/sources/CIEL/concepts/21/5f7c588e0055580001e15abd/",
    "url": "/orgs/CIEL/sources/CIEL/concepts/21/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/653/
```
  "version_url": "/orgs/CIEL/sources/CIEL/concepts/653/5f7c58950055580001e15ac4/",
  "url": "/orgs/CIEL/sources/CIEL/concepts/653/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/653/versions/
```
    "url": "/orgs/CIEL/sources/CIEL/concepts/653/5e7b950dbc5919000193770f/",
    "previous_version_url": "/orgs/CIEL/sources/CIEL/concepts/653/5821b9a883ac240007c3c56b/",
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/653/5e7b950dbc5919000193770f/
```
  "version_url": "/orgs/CIEL/sources/CIEL/concepts/653/5e7b950dbc5919000193770f/",
  "url": "/orgs/CIEL/sources/CIEL/concepts/653/"
```

https://api.openconceptlab.org/mappings/
```
    "url": "/orgs/MOH/sources/DHIS2/mappings/5d53d4780e08cc00696a9782/",
    "versioned_object_url": "/orgs/MOH/sources/DHIS2/mappings/5d53d4780e08cc00696a9782/",
    "version_url": "/orgs/MOH/sources/DHIS2/mappings/5d53d4780e08cc00696a9782/1/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/
```
    "url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/",
    "versioned_object_url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/",
    "version_url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/1/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/
```
  "url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/",
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/versions/
```
    "url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/1/",
    "versioned_object_url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/"
```

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/1/
```
  "url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/1/",
  "versioned_object_url": "/orgs/CIEL/sources/CIEL/mappings/27e7c3c6-d2d2-44d8-859e-51f04a1cd9b0/"
```

**Comment by snyaggarwal** [comment]
Following is done for concepts/mappings:
1. url - to always point to resource URL (without version)
2. version_url - to always point to exact resource URL or the exact URL of the resource you are looking at
3. url and version_url to be always there in all responses
4. previous_version_url - to be there in /versions/ response
5. versioned_object_url - same as url not removed yet.

@paynejd If the above is ok, we can close this ticket.

**Comment by paynejd** [comment]
Added this into #436 as a potentially breaking change that requires further testing outside of the scope of this ticket. Closing this one out.
