### ISSUE TITLE
Add re-captcha to oclweb v1 to stop the spam

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#651]
We have lots of spam accounts being created on oclweb v1 and it resulted in Google suspending our no-reply@openconceptlab.org account. We should be able to stop most of this by adding re-captcha to v1.

cc @snyaggarwal

**Comment by jamlung-ri** [comment]
@snyaggarwal and @paynejd to chat about this, may be closed out.

**Comment by paynejd** [comment]
Based on discussions with team, we are not going to implement a fix for this since the launch is right around the corner
