### ISSUE TITLE
Create New Collection when Selecting Concepts and "Add to Collection"

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#652]
Should be able to create a new collection when selecting concepts. Add to Collection should provide a way to create and add at the same time. For mappings, they should be added at the concept level with the from concept pre-determined.

_Originally posted by @askanter in https://github.com/OpenConceptLab/ocl_issues/issues/622#issuecomment-800313832_

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done

**Comment by jamlung-ri** [comment]
We noted in our meeting earlier that the Create Collection button should either be stickied or moved to the top. Otherwise, it's looking good so far!

**Comment by jamlung-ri** [comment]
@snyaggarwal will work on this and close out ticket

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done! Should be available in few on QA. Closing this.
