### ISSUE TITLE
Incorporate feedback form into oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#653]
@snyaggarwal you mentioned that incorporating a simple feedback form into oclweb2 would be really easy -- that would be a great thing to add before launch if it's a small level of effort. Ideally, we could use a component that could also be implemented in wordpress.

**Comment by snyaggarwal** [comment]
Yes. What would be the end action of feedback? Send mail to someplace? or something else?

**Comment by snyaggarwal** [comment]
0. Use recpatcha v2.
1. Send it to: 
to - community@openconceptlab.org
subject - [ENV] [Feedback] From: guest or user-id
cc - sender (if the user is logged in?)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed on QA. Try it out and let me know if there is any feedback on Feedback :)

**Comment by jamlung-ri** [comment]
@snyaggarwal I'm using Firefox. It works well when I'm already signed in, and I got a confirmation email about my feedback. 

However, when I signed out and tried it, there were a couple of things I noticed:
* There was no captcha.
* It ran a bit slower than when I was signed in. (I'm working on Firefox, but it ran faster on Edge. Not sure what to think about that.)
* It might be good to add an email address to the form so OCL can get in contact with the feedback submitter.

**Comment by paynejd** [comment]
Suggest requiring email + name if not signed in

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri -- 
Added name, email, captcha for non-logged-in users.
Also @jamlung-ri  I tested it on Firefox and I got usual result.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal, it seems to be working better on Firefox today. Everything looks good, although the name and email entry fields just look a little short in terms of height. Just a small visual thing though, and everything else is good.
![image](https://user-images.githubusercontent.com/55999682/111986055-ce670780-8ae3-11eb-9939-9c7502325fab.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed

**Comment by jamlung-ri** [comment]
This seems to be fixed, although there sill may be some performance issues on Firefox. @snyaggarwal and I have discussed it though, so I will close out this ticket for now.
