### ISSUE TITLE
Convenient searching of concepts based on their mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#654]
From Andy: "We should make it easy to search for CIEL codes based on ICD-10 maps and add them to a collection. We also need to make sure that there is nearly full coverage for ICD-10-WHO in CIEL."

**Comment by jamlung-ri** [comment]
1. Design how user can interact with this data
2. Develop on API gaps as needed
3. Implement into TermBrowser

**Comment by jamlung-ri** [comment]
#1259 covers this
