### ISSUE TITLE
FHIR Filter Support - Status and Content

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#657]
To start us off with some basic CodeSystem filtering, we want to support the status and content attributes when filtering a list of code systems.

Examples from HAPI:
* https://hapi.fhir.org/baseR4/CodeSystem?status=draft 
* https://hapi.fhir.org/baseR4/CodeSystem?content-mode=not-present

**Comment by harpatel1** [comment]
Also added filter support for version and publisher.
