### ISSUE TITLE
FHIR Connector Development (plus connect to other OCL servers)

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#659]
Ability to connect to multiple servers, including FHIR and OCL, and switch between them using a dropdown in the user interface.

In Scope for this ticket:
* Single page per server, which has the following: 
    * Header with server info
    * List of CodeSystem resources on that server
    * Each row can be expanded to see details, versions, copyright, etc.

Next ticket will involve doing the same with ValueSet and ConceptMap resource. After that will be screens to dig into each type of resource (i.e. view a single CodeSystem, ValueSet, or ConceptMap).

**Comment by jamlung-ri** [comment]
Started, but need to do sub-tabs and pagination

**Comment by jamlung-ri** [comment]
Discussion needed on Tuesday Dev Call.

**Comment by snyaggarwal** [comment]
Tasks (and status):

- [ ] fhir server configurations (ocl-qa-fhir/ocl-staging-fhir/hapi-fhir)
- [ ] Default header
- [ ] Code System Tab and listing
- [ ] Copyright subtab
- [ ] Details subtab
- [ ] Versions subtab
- [ ] Pagination

**Comment by snyaggarwal** [comment]
@jamlung-ri This now has pagination for OCL FHIR CodeSystem -> codes

**Comment by jamlung-ri** [comment]
Documentation: https://docs.google.com/document/d/1ZKFabSxL1Tc9hsw2n3FadwiRBmwBWeTwTyEPR8R2jIs/edit

**Comment by jamlung-ri** [comment]
This is looking good to me, so we can close it out.
