### ISSUE TITLE
Can't export CIEL mappings from API at api.openconceptlab.org

### ISSUE THREAD

**Issue by wrighth-omics** [OpenConceptLab/ocl_issues#66]
Hello,
I'm trying to hook up an OpenMRS instance to the OpenConceptLab module subscription service, or, failing that, dump the CIEL dictionary from the OCL using the API export function, but I am unable to do so. I've tried from both Postman and Chrome and am able to properly access e.g. 

http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/v2016-10-09/

but attempting either GET or POST actions to start the export per the OCL documentation doesn't work

http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/v2016-10-09/export

returning an empty result. I noticed there were similar issues posted recently so wasn't sure if this was related to those or is something I'm doing wrong. Any help would be appreciated

**Comment by paynejd** [comment]
Looks like there is an issue. I just tried GET, POST, DELETE and HEAD on
this export and all of them returned 204 No Content.

**Comment by paynejd** [comment]
flagging this is priority
