### ISSUE TITLE
Need ability to delete an existing source that other sources/collections are referencing

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#661]
Specifically, we are getting ready for when we will delete the PIH source on staging

Will also need to implement proper handling of mappings/references after deletes
How do we handle deletes of content that others have mapped/referenced? What happens if an updated source is uploaded after it was deleted?
From_concept = /orgs/CIEL/sources/CIEL/v2021-03-23/concepts/123/
From_concept = /orgs/CIEL/sources/CIEL/concepts/123/139493/

**Comment by snyaggarwal** [comment]
@paynejd @bmamlin current behaviours:
1. On a concept hard delete, its collection references and mappings will stay as is, that means the mappings and references will show the unresolved reference to the deleted concept.
2. Same for source hard delete, its collection references and mappings will stay as-is.

The only rule right now is you cant delete a source/version which has its concepts/mappings referred to in a private collection (public_access=None).

**Comment by bmamlin** [comment]
> The only rule right now is you cant delete a source/version which has its concepts/mappings referred to in a private collection (public_access=None).

Can this be fixed? There are (not unexpectedly) references to PIH from private collections (anyone working on a personal collection with CIEL content could have mappings to PIH), so I still cannot hard delete the PIH source.

**Comment by snyaggarwal** [comment]
> > The only rule right now is you cant delete a source/version which has its concepts/mappings referred to in a private collection (public_access=None).
> 
> Can this be fixed? There are (not unexpectedly) references to PIH from private collections (anyone working on a personal collection with CIEL content could have mappings to PIH), so I still cannot hard delete the PIH source.

@paynejd This feature was added recently because of #103. Now I think we have references and mappings that may exist even if their referred content doesn't. So is it ok if we revert this?

**Comment by paynejd** [comment]
Hi @sny, can you say more what you mean by revert this? We definitely want
to support references and mappings that point to content that doesn't exist
in OCL. We also want to be able to delete content that has references and
mappings that point to it.

**Comment by snyaggarwal** [comment]
I meant should we revert #103 ?

**Comment by paynejd** [comment]
For now, we agreed to revert #103, which means that we will be able to delete a source that has content that is mapped/referenced by other resources, regardless of whether it is public or private. This will make it so that the behavior for public/private resource links are consistent.

However, a concept/mapping that is referenced in a collection will be removed from existing collection versions, even though the reference will still remain. As part of the upcoming dynamic reference/expansion work, we are planning to save certain attributes from concepts/mappings that have been evaluated in an expansion, so that we'll retain the info that a concept/mapping was part of the expansion, but the user will no longer be able to follow that concept/mapping reference to lookup all of the remaining details.

Need a new ticket for this.

**Comment by bmamlin** [comment]
Hey @snyaggarwal ... any ETA when this might be available on staging?

**Comment by snyaggarwal** [comment]
@bmamlin Its available on all environments

**Comment by bmamlin** [comment]
> @bmamlin Its available on all environments

Thanks @snyaggarwal. When I'm logged in as `ocladmin` on staging looking at [/orgs/PIH/sources/PIH/](https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/), click the trash can, and type "PIH" to confirm deletion, the browser makes the request `DELETE https://api.staging.openconceptlab.org/orgs/PIH/sources/PIH/`. This runs for a minute and then returns a `502` error with this brief toast appearing in the UI:

<img src="https://user-images.githubusercontent.com/860834/142974428-5aea3b22-783e-4ce9-8afb-2e206862ebf2.png" width="300" />

This is the same behavior I've been seeing. Is it supposed to work through the UI? It looks like it's making the same RESTful DELETE call that I'd be making manually anyway.

**Comment by snyaggarwal** [comment]
@bmamlin the UI is trying to do synchronous delete which is causing timeout due to the size of source. This needs to be fixed.
Meanwhile, you can try async delete by adding `?async=true` to the DELETE request and it should queue it for async delete.

**Comment by snyaggarwal** [comment]
Created ticket for this #1128

**Comment by snyaggarwal** [comment]
closing this as #1128 is more latest
