### ISSUE TITLE
Fix inactivation (soft delete) of objects

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#67]
It is possible to inactivate any object (soft delete it). It will no longer appear in searches, however it will still be present in mongo and can be activated again, if needed. There are a number of issues with inactivation:

1) inactivated objects are still considered when validating other objects, e.g. you cannot create a new org with the same name, if there's another inactive org with that name. Same may apply to sources/collections/concepts/mappings.
2) when a container like org or source is inactivated, all objects within that container should be inactivated.
3) when a collection is inactivated, all references should be inactivated, but not the referenced objects

**Comment by paynejd** [comment]
Work related to this ticket will be addressed in #323  - closing this out
