### ISSUE TITLE
Plan for MSP production deployment

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#671]
_Copied from DATIM-OCL_
- [ ] FISMA approval
- [ ] Determine deployment timeline
- [ ] Plan incorporation of MSD/SSD metadata sources
- [ ] User validation of content
- [ ] User access plan - public?
- [ ] Identify and address dependencies on oclapi2 upgrade
- [ ] Identify and address dependencies on generic metadata browser development
- [ ] Document remaining development work prior to deployment
- [ ] Draft MSP documentation
- [ ] Document deployment procedures

**Comment by paynejd** [comment]
Old ticket --  Closing this out
