### ISSUE TITLE
Extras Schema Validation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#677]
Document any issues related to Extras attributes after changes made in #637

**Comment by jamlung-ri** [comment]
@snyaggarwal I'm not having any luck using the "." syntax for an extras attribute (I might not be using it correctly though). Here are two queries where I am noticing it (see the last parameter with codelist id for the difference):
* _ example (works): https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras__codelists__id=BPEyzcDb8fT
* . example (does not work): https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras__codelists__id=BPEyzcDb8fT

**Comment by jamlung-ri** [comment]
Another example:
* _ (works): https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Indicator&limit=10&page=1&extras__indicatorGroups__id=rEMeS5Yexdi
* . (does not work): https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Indicator&limit=10&page=1&extras.indicatorGroups.id=rEMeS5Yexdi

**Comment by snyaggarwal** [comment]
@jamlung-ri 
the two right syntaxes are:
`extras.codelists.id=` or `extras.codelists__id=`

with `__` --  https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras.codelists__id=BPEyzcDb8fT -- No results
with `.` --  https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras.codelists.id=BPEyzcDb8fT -- No results

I think there are no concepts with `extras.codelists.id`
I did an empty search as well `/concepts/?extras.exists=codelists.id` it returned 0.

To test this further I created a concept:
https://app.qa.aws.openconceptlab.org/#/users/ocladmin/sources/test-sny-s1/concepts/test-sny-s1-c1/
with 
```
extras = {
  "foo": "bar",
  "test": {
    "nested": "level1"
  }
}
```
And Following works:
1. https://api.qa.aws.openconceptlab.org/concepts/?extras.test.nested=level1&includeExtras=true (with `.`)
2. https://api.qa.aws.openconceptlab.org/concepts/?extras.test__nested=level1&includeExtras=true (with `__`)
3. https://api.qa.aws.openconceptlab.org/concepts/?extras.exists=test.nested&includeExtras=true  (exists query)

**Comment by jamlung-ri** [comment]
@snyaggarwal I've tried using that syntax but haven't had any luck yet.  

Here are some concepts that do have the extras.codelists.id attribute: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.source=DATIM&extras.Applicable+Periods=FY21

But no luck when adding the filter: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.source=DATIM&extras.Applicable+Periods=FY21&extras.codelists.id=ey0IaQ5wJ0b

**Comment by snyaggarwal** [comment]
@jamlung-ri 
the `extras.codelists` is a list and not a dict, so that's not indexed for path `extras.codelists.id`, and that's why it's not appearing in any query.

List fields are indexed as string -- `[{foo: bar, id: foobar}....]`

Following works -- 

https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.source=DATIM&extras.Applicable+Periods=FY21&extras.codelists=ey0IaQ5wJ0b

**Comment by jamlung-ri** [comment]
Gotcha, the filters work with that logic in MSP. Should be a small change. 

It's also worth noting that I was also able to filter using attributes other than the ID. The code and name fields also filtered the results list when putting the string in quotes. Example: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.source=DATIM&extras.Applicable+Periods=FY21&extras.codelists=%22MER-R-NARRATIVES-IM%22
