### ISSUE TITLE
API Search Query ignores terms when searching more than 4 terms

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#679]
Something odd seems to be happening with the API when searching multiple (e.g. 4 or more) terms. From the [OCL search page](https://app.qa.aws.openconceptlab.org/#/search/?q=&type=concepts&isTable=true), `1067 1068 1072 1073` ([API results](https://api.qa.aws.openconceptlab.org/concepts/?q=1067+1068+1072+1073&page=1&limit=25&includeRetired=false&verbose=false&sortDesc=last_update)) seems to be returning the same results as `1067 1068 1072 1074 1073` ([API results](https://api.qa.aws.openconceptlab.org/concepts/?q=1067+1068+1072+1074+1073&page=1&limit=25&includeRetired=false&verbose=false&sortDesc=last_update)), even though searching [1074](https://api.qa.aws.openconceptlab.org/concepts/?q=1074&page=1&limit=25&includeRetired=false&verbose=false&sortDesc=last_update) returns many of its own results. It seems like the API is ignoring search terms in the middle of the query.

**Comment by snyaggarwal** [comment]
@jamlung-ri the fix for this deployed on QA

**Comment by jamlung-ri** [comment]
Great, this is working perfectly now!
