### ISSUE TITLE
Speed up creation or update of a concept or mapping in a source

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#68]
Currently this takes 10-20 seconds per resource, and it should be able to be much faster.

**Comment by paynejd** [comment]
I can provide test code to import a test DATIM country into OCL that takes up to 2 hours (for ~500 resources). If we say that it currently takes 15 seconds per resource, after reviewing possible approaches, we should be able to set a goal of 1 or 3 or 5 seconds.

**Comment by rkorytkowski** [comment]
@paynejd, yes please do provide the test code you mentioned.

**Comment by rkorytkowski** [comment]
Fixed! It takes less than a second on my machine now for a newly created source (may very on depending on the source size)...

The issue was that we were counting all concepts in a source with every creation of a concept. The count operation is very slow on Mongo. Rather than counting each time we are now simply incrementing the count atomically, which is much faster.

**Comment by rkorytkowski** [comment]
Awaiting to be deployed to staging and production...

**Comment by paynejd** [comment]
Does the same speed up occur also for mappings?

**Comment by rkorytkowski** [comment]
Yes, it's both for concepts and mappings. It also improves both creation and update time.

**Comment by paynejd** [comment]
I just completed a fresh import of Namibia's FY18 country mappings and the performance difference was enormous! This import consisted of ~450 resources

**Import before Rafal implemented the fix:**
```
[2018-09-09 01:13:59.335484] **** STEP 1 of 12: Download PEPFAR/DATIM-MOH metadata export for specified period from OCL 
...
[2018-09-09 02:01:30.786473] **** IMAP import process complete! 
```

**Import after the fix:**
```
[2018-10-15 12:06:39.140989] **** STEP 1 of 12: Download PEPFAR/DATIM-MOH metadata export for specified period from OCL
...
[2018-10-15 12:12:14.036677] **** IMAP import process complete! 
```

**Summary:**
* Before the fix: 47min 31sec
* After the fix: 5min 35sec
* Difference: 88% reduction in import time (41min 56sec faster)
  * Or, 0.74 seconds per resource vs. 6.3 seconds per resource

**Comment by wluyima** [comment]
Wow! Good job Rafal!

**Comment by rkorytkowski** [comment]
Thanks @paynejd  for testing! Closing the issue.
