### ISSUE TITLE
Codelist Mediator Issue

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#680]
It appears that the Codelist download links used in MSP ([example](https://test.ohie.datim.org:5000/ocl-etl/msp/MER-R-COMMUNITY-BASED?format=HTML)) are not showing enough data elements. This codelist should be showing [76 data elements](https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/collections/MER-R-COMMUNITY-BASED/concepts/?concept_class=Data+Element), but there only seem to be 2 in the Codelist download link.

It's worth noting that OCL recently showed only 2 data elements but the codelists were updated to have the right number of data elements.

**Comment by maurya** [comment]
@jamlung-ri  the mediator is configured with staging AWS OCL - https://api.staging.aws.openconceptlab.org/orgs/PEPFAR-Test10/collections/MER-R-COMMUNITY-BASED/concepts/?concept_class=Data+Element is still showing only 2 data elements. The 76 data elements are from QA OCL AWS server.

**Comment by jamlung-ri** [comment]
Ahh okay, then it looks like OCL Staging will need to be updated with the latest PEPFAR content. @paynejd is that expected soon? If so, then we don't need to do anything further with this ticket.

**Comment by jamlung-ri** [comment]
@maurya One quick change I forgot to inform you about: The most up to date PEPFAR codelist content is now in org PEFPAR-Test10b. Examples:
* PEPFAR-Test10b, which has many data elements (correct): https://api.staging.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras.codelists=BPEyzcDb8fT
* PEPFAR-Test10, which only shows 2 data elements (incorrect): https://api.staging.aws.openconceptlab.org/orgs/PEPFAR-Test10/sources/MER/concepts/?verbose=true&q=&concept_class=Data+Element&limit=10&page=1&extras.Applicable+Periods=FY21&extras.codelists=BPEyzcDb8fT

@maurya Can you point the mediator to PEPFAR-Test10b instead?

**Comment by maurya** [comment]
@jamlung-ri , I've updated the mediators to the new organization `PEFPAR-Test10b` please confirm and close the ticket

**Comment by jamlung-ri** [comment]
Looks good! Thanks!
