### ISSUE TITLE
Additional Sort Pattern Option?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#685]
[CIEL](https://app.staging.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/) uses numeric IDs instead of alphabetical. When sorting by ID, however, it will show 1 -> 10 -> 100 (the alphabetical way) instead of 1 -> 2 -> 3 (the numeric way). Is there any way we could either adjust the sort pattern to either recognize the need for numeric sorting or to add a numeric sort pattern option in the configuration interface?

**Comment by snyaggarwal** [comment]
@jamlung-ri Can we close this?
