### ISSUE TITLE
create FHIR related fields in OCL backend

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#689]
- Source
  - experimental              [optional]   [boolean default None]                               [searchable]     [Faceted]
  - case_sensitive            [optional]   [boolean default None]                               [searchable]  
  - collection_reference  [optional]   [Text max 100 characters default None]
  - hierarchy_meaning     [optional]   [Text max 50 characters default None]      [searchable]     [Faceted]
  - compositional             [optional]   [boolean default None]                                [searchable]  
  - version_needed          [optional]   [boolean default None]                                [searchable]  
- Collection:
  - experimental              [optional]   [boolean default None]                                  [searchable]     [Faceted]
  - locked_date               [optional]   [timestamp default None]                              [searchable]

**Comment by snyaggarwal** [comment]
@harpatel1 Are any of these fields searchable?

**Comment by harpatel1** [comment]
Apart from collection_reference, they all are searchable. Also updated description to reflect the same.

**Comment by snyaggarwal** [comment]
@harpatel1 Can you also add couple of other info for fields:
1. Do we need facets?
2. Default values (especially for boolean fields, default False or None?)
3. All optional?
4. For `hierarchy_meaning` and `collection_reference`, string fields, there any set values it can take or just open strings with some max-length or they can be big text fields?

**Comment by harpatel1** [comment]
@snyaggarwal 

1. Do we need facets? **For hierarchy_meaning and experimental** see ^^
2. Default values (especially for boolean fields, default False or None?) **None for all**
3. All optional? **All optional**
4. For hierarchy_meaning and collection_reference, string fields, there any set values it can take or just open strings with some max-length or they can be big text fields? see ^^

**Comment by snyaggarwal** [comment]
@harpatel1 This is done on API. Please verify this and close this.
@paynejd @harpatel1 - Should we add these fields on OCL WEB2 UI?

**Comment by snyaggarwal** [comment]
Added Fields in Web UI

**Comment by snyaggarwal** [comment]
@harpatel1 Can you please verify this and close.
