### ISSUE TITLE
Allow mappings to optionally have IDs that are manually set by users (similar to other resources)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#69]
Currently, all mappings have IDs that are automatically generated by the system. This makes sense because all mappings are uniquely identified by the combination of their from_concept, to_concept, and map_type. However, that is a fairly complicated identifier for many use cases, and furthermore many of the more mature reference vocabularies (like SNOMED) have a coding system for the mappings too that we eventually need to support. Finally, writing scripts to create collections based on newly imported content that includes mappings is a challenging process when you can't set the IDs, because you have to first import the concepts & mappings, then query/find your resources again so that you have the IDs that you need to generate the collection references. 

There are 2 solutions that would help to address this, and this ticket is focused on the first one.:
* Allow mapping references to have user-set IDs
* Allow mapping references to be created using a combination of from_concept, to_concept, and map_type as an alternative to providing the fully specified URL (which includes the ID)

**Comment by Karuhanga** [comment]
This seems to be a breaking change @paynejd. Does this mean an `id` is required going forward?

**Comment by paynejd** [comment]
@Karuhanga IDs for mappings will still be optional. If you do not provide an ID, the behavior is the same as it used to be. Moving forward, though, you will optionally be able to provide an ID for a mapping. This should not break any existing functionality.

**Comment by paynejd** [comment]
Update: Pulling back this commit as it was implemented in a way that IDs are now required. This will be revised so that a mapping ID is auto-generated the same way it has been if no ID is provided. If an ID is provided, the API will verify that it is unique within the source and utilize that instead.

@harpatel1 please provide an update here on progress to pull back this change and resolve. thanks!

**Comment by harpatel1** [comment]
I have created pull request to make the Mapping id optional and fixed integration tests.

**Comment by rkorytkowski** [comment]
@paynejd it's been deployed to QA and is ready for your tests.

**Comment by aprilcurrier** [comment]
Need final approval from @paynejd  99% done on roll over

**Comment by paynejd** [comment]
This new functionality worked as expected based on my testing in QA! @rkorytkowski @harpatel1 Let's deploy to staging as soon as we are confident that it will not result in any data corruption issues.

**Comment by paynejd** [comment]
This works as expected on QA/staging and is ready for deployment to production

**Comment by aprilcurrier** [comment]
Waiting on fix from Rafal for data corruption
