### ISSUE TITLE
[OCLAPI2] Source/Collection filterable by customValidationSchema

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#690]

**Comment by snyaggarwal** [comment]
@paynejd this is done for both source and collection. The value is case-insensitive, following works:
`?customValidationSchema=OpenMRS`
`?customValidationSchema=openmrs`

**Comment by paynejd** [comment]
Just tested with this query and the new parameter has no effect:
https://api.qa.aws.openconceptlab.org/sources/?customValidationSchema=OpenMRS&limit=5&verbose=true

**Comment by snyaggarwal** [comment]
This is deployed on Staging and QA. Should work now.

**Comment by paynejd** [comment]
Works!
