### ISSUE TITLE
Migrate these OMRS Dictionaries & Orgs to API2 in Production

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#695]
The following Dictionaries (Collections) will be needed in the Production environment of the OCL for OpenMRS webapp when we start using API2:  (the "user" listed here is not necessarily the owner in the DB; just listed these to give you an idea of additional groups already using the OCL client in production)

- SPATestResults  (user: Grace/MFE Squad/3.0 Demo envi)
- ClinicalConcepts  (user: Grace/MFE Squad/3.0 Demo envi)
- EXAMPLEohri  (user: OHRI)
- CBSDataset  (user: OHRI)
- OMRSCOVIDVaccination  (user: OMRS Covid Squad)

Orgs needed:
- OHRITechGroup
- OMRSCOVIDSquad

Thank you! Contact me for any questions.

**Comment by paynejd** [comment]
Added to data migration list here: https://docs.google.com/document/d/1Y2ahAGgZITA_f99fYYMuYFk_nmjWEyFb0Cbyt_pKxCE/edit#

**Comment by snyaggarwal** [comment]
@paynejd Should we close this?
