### ISSUE TITLE
Migrate these OMRS Dictionaries to API2 in QA

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#696]
I would like to have this Dictionary (Collection) in the QA environment of the OCL for OpenMRS webapp when we formally switch over to only using API2 (only because it took a while to make this):

- MegaMega ("Mega Mega Dictionary")

Thank you! Contact me for any questions.

**Comment by paynejd** [comment]
Added to data migration list here: https://docs.google.com/document/d/1Y2ahAGgZITA_f99fYYMuYFk_nmjWEyFb0Cbyt_pKxCE/edit#
