### ISSUE TITLE
Users are incorrectly shown as members of organizations they don't actually work with

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#697]
Found in production on https://openconceptlab.org/. Steps:
1. Go to https://openconceptlab.org/
2. Search for 3 users: [gpotma](https://openconceptlab.org/users/gpotma/?tab=Organizations), [alaboso](https://openconceptlab.org/users/alaboso/?tab=Organizations), and [jteich](https://openconceptlab.org/users/jteich/?tab=Organizations)
3. Notice that gpotma is part of 2 organizations (this is showing as expected)
4. Notice that jteich is showing as part of _many_ orgs that they are not actually a member of (e.g. MSFTW)
5. Notice that alaboso is also showing as part of _many_ orgs that they are not actually a member of (e.g. MSFOCP, even CIEL). This case is especially confusing because alaboso is actually a member of the Org "OHRITechGroup" in the OCL Client [here](https://openmrs.openconceptlab.org/orgs/OHRITechGroup/)
![image](https://user-images.githubusercontent.com/67400059/113615912-53384200-9609-11eb-865e-8acdae96da3e.png)

Seems like there might be 2 related things happening:

1) New users without an organization are being recognized as members of many random organizations
2) When a user account gets into this funky state, the UI for their Org Membership page doesn't update even if the user is added to an organization through the OCL Client UI, as shown in this GIF example for user jteich (this is a replication; this was originally seen with user alaboso and remains the case days later):
![Add user to org in OCL Client UI doesn't update in OCL UI](https://user-images.githubusercontent.com/67400059/113616635-381a0200-960a-11eb-92e9-274d72eb3992.gif)

**Comment by paynejd** [comment]
Thanks for reporting! Given that we are launching the new service shortly and this bug is already fixed there, we are not planning to resolve this bug in v1.
