### ISSUE TITLE
Do not modify references into versioned resource expressions by default

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#702]
Modify collection behavior so that expressions are saved in the collection as they are submitted, rather than as an expression that was already resolved to a specific concept version. Expressions for a single concept (and same applies for mappings) may be submitted in 3 ways: version-less, source versioned (eg /CIEL/v2021-03-12/) or concept versioned. These should be resolved upon request if in HEAD or resolved when saved to a collection version.

See more details in #684

**Comment by snyaggarwal** [comment]
@paynejd There is a lot more work done on this, this ticket is now duplicate and incomplete. Can we close this?
