### ISSUE TITLE
Identify gaps for loading HL7/WHO CodeSystems in OCL FHIR

### ISSUE THREAD

**Issue by harpatel1** [OpenConceptLab/ocl_issues#707]

**Comment by harpatel1** [comment]
Required change to support HL7 FHIR Normative CodeSystem:

- Add Extension (JSON) as core field for Source
- Add Extension (JSON) as core field for Concept
- Add Meta (JSON) as core field for Source [We'll need to add it to Collection too.] 
- Concept Name Type
      - FHIR requires Coding Type of concept's designation.use field
      - Coding usually have four fields - system, code, version, display
       - We need to store concept name type as Coding JSON resource or create new json field in LocallizedText table to store
          Coding JSON resource

**Comment by harpatel1** [comment]
No changes are required to support WHO codesystems:

- http://build.fhir.org/ig/who-int/core/CodeSystem-extended-content-codes.json.html
- http://build.fhir.org/ig/who-int/fp-cds/CodeSystem-extended-content-codes.json.html
- http://build.fhir.org/ig/who-int/sti-cds/CodeSystem-extended-content-codes.json.html

**Comment by harpatel1** [comment]
Requirements document - https://docs.google.com/document/d/1kExqfiL7_-XboZHtrFXEqDP6Rjjf_4I2RwhVwDJTt3U/edit

**Comment by jamlung-ri** [comment]
One gap that might not be documented yet: FHIR IDs allow any character, whereas OCL Mnemonics are more restrictive. Might need to handle specific characters.

**Comment by paynejd** [comment]
Complete - gaps will be addressed as part of the concept modification work #746
