### ISSUE TITLE
Fix search bar on openconceptlab.org

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#715]
The search field on openconceptlab.org currently sends the request to https://app.openconceptlab.org/search/?q=<search term>. This gives a 404 error; the actual URL should be https://app.openconceptlab.org/#/search?q=<search term>, which works as expected.

**Comment by snyaggarwal** [comment]
This is fixed now.

**Comment by ibacher** [comment]
@snyaggarwal Thanks!
