### ISSUE TITLE
to_concept_name no longer populated for CIEL

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#716]
This is probably more a request for information than a bug in OCL, but it looks like the `to_concept_name` field on mappings is no longer populated (at least for CIEL), though the `to_concept_name_resolved` field (which didn't exist in v1) is. Should we change the OCL for OpenMRS client to look at the `to_concept_name_resolved` field? Also what is the intended difference between these two fields?

**Comment by paynejd** [comment]
FYI this was discussed on an OpenMRS squad call - this is a documented breaking change in OCL v2. No work will be done on this.
