### ISSUE TITLE
Explore performance enhancement options related to DATIM IMAP imports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#72]
The time to complete an IMAP import was just reduced from 45min to 5min based on a fix that Rafal implemented -- this was huge! However, the IMAP imports are still relatively small, consisting of several hundred imports and maybe 50+ export/read requests, and PEPFAR has asked that we further explore options for performance improvements in preparation for much larger synchronization processes in production. There are 4 components to this:

1) Profiling timing/performance of IMAP imports -- Jon to do this
2) Profiling read vs. write performance -- let's discuss the best way to do this one
3) Identifying options for technical solutions resulting in significant performance improvements
4) Estimate relative performance improvement and level of effort for each technical solution

**Some potential options:**
* Parallel requests (when no dependencies)
* API-based batch importing
* Caching IMAP exports
* Improving link between Mongo and Solr (Django Haystack module)
* MongoDB improvements

Currently at ~600 ms per request, and limit for REST API requests is typically around 2-300ms per request. Meaning reducing the number of requests is the biggest bang for our buck.

**Comment by rkorytkowski** [comment]
Let's see. Right now you do 500 requests to create 500 resources in 5 min. It's only ~0.6s per request. It's going to be very hard to go under 0.3s per request, which means you will still need 2.5min. I say that you either need to execute requests in parallel (if they don't depend on one another) or do imports in batches. Batches will be more performant and we will be able to get the time down from 5 min to seconds for creating 500 resources.

**Comment by paynejd** [comment]
Since this was created, import and export times have been reduced to under 1 or 2 minutes in most circumstances. The biggest change was to parallelize certain import and export requests. There are 2 other major improvements that have been captured in other tickets: Speeding up creation of new repo versions (#120) and Upgrading to Python/Django v3 (#87). Additional performance improvements will be addressed in other tickets, so we are closing this out.
