### ISSUE TITLE
Add index on external id attribute

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#720]
ability to do exact match on this field is important

**Comment by paynejd** [comment]
How do we test this?

**Comment by jamlung-ri** [comment]
Burke requested this feature. External ID is now part of the full text search. You can also specifically search by this field using a filter. Let's try to test this today and close out by end of day.

**Comment by paynejd** [comment]
Works as expected! Here's an example:
https://app.openconceptlab.org/#/search/?q=160851AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&type=concepts&isTable=true
