### ISSUE TITLE
FHIR Connector Development - Round 2

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#723]
Continuing from #659 

In scope for this ticket:
* ValueSet List Display
* Individual ValueSet View

Documentation for this is available here: https://docs.google.com/document/d/1ZKFabSxL1Tc9hsw2n3FadwiRBmwBWeTwTyEPR8R2jIs/edit#heading=h.o5ivpcba5hhy

Mockups are available here: https://framer.com/share/Metadata-Browser--onB59TV7OytQ2Urr6McM/CCdeAQEYf

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done. Should be available on QA.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! It looks like a good start for the HAPI FHIR side (using [allergy-intollerance-code](https://app.qa.openconceptlab.org/#/fhir/ValueSet/b92c14eb-d67d-421b-9cfd-60f04900dfc3) as my example since it has codes). One thing that is missing is the compose.include.system attribute. On this [Framer mockup](https://framer.com/share/Metadata-Browser--onB59TV7OytQ2Urr6McM/CCdeAQEYf#F97lakvOD), it is shown as a collapsible header. Also, keep in mind that, at some point, there should be some kind of $expand button (also on the Framer mockup), which performs the $expand operation on the ValueSet.

Of course, the OCL side is not currently working, which I believe @harpatel1 is working on since [this request](https://fhir.staging.aws.openconceptlab.org/fhir/ValueSet/) is not working at the moment.

**Comment by jamlung-ri** [comment]
Decision from OCL Dev call today:

> FHRI UI ValueSet Decision: Since HAPI does not do the $expand operation, we will not do $expand in the OCL FHIR UI yet. We can finish the first iteration of FHIR UI for CodeSystem, ValueSet, ConceptMap, then come back to $expand

> Note: $expand should appear as a tab where a user can specify parameters and then hit the $expand button.

**Comment by snyaggarwal** [comment]
@jamlung-ri All the tasks for OCL/HAPI FHIR are done. Should be available on QA. Please try this out and provide feedback.

**Comment by jamlung-ri** [comment]
@snyaggarwal The only big thing that's missing for ValueSets is the `compose.include.system` attribute. On this [Framer mockup](https://framer.com/share/Metadata-Browser--onB59TV7OytQ2Urr6McM/CCdeAQEYf#F97lakvOD), it is shown as a collapsible header. Not sure if it's possible in this sprint to support multiple headers for `compose.include.system` and `compose.include.version`, but note that it is possible for there to be multiple `compose.include.system` and `compose.include.version` attributes for a single ValueSet. Can this be implemented this sprint?

Future To-Dos: 
* Value Set searching/filtering in OCL
* Value Set expansion as a tab with inputs for parameters
* View versions of CodeSystem/ValueSet
* Add Value Set count tags to OCL (when available)

**Comment by snyaggarwal** [comment]
@jamlung-ri Can you point me to a ValuSet on HAPI or OCL FHIR that has multiple codes inside ValueSet version.
I looked at https://fhir.staging.aws.openconceptlab.org/orgs/MSFOCP/ValueSet/demo-bd-km. 
It has  3 versions -- 1.0, 2.0 and test2 (latest, I think).
All four requests below returns the same response with single compose.include.system
https://fhir.staging.aws.openconceptlab.org/orgs/MSFOCP/ValueSet/demo-bd-km
https://fhir.staging.aws.openconceptlab.org/orgs/MSFOCP/ValueSet/demo-bd-km?version=test2
https://fhir.staging.aws.openconceptlab.org/orgs/MSFOCP/ValueSet/demo-bd-km?version=2.0
https://fhir.staging.aws.openconceptlab.org/orgs/MSFOCP/ValueSet/demo-bd-km?version=1.0

Maybe I am missing something.

**Comment by jamlung-ri** [comment]
@snyaggarwal It took some digging but I was able to find some good examples of HAPI ValueSets that have more than one compose.include.system:
* Example with multiple systems but not multiple versions: http://hapi.fhir.org/baseR4/ValueSet/security-role-type
* Examples with multiple versions of the same system: http://hapi.fhir.org/baseR4/ValueSet/2044734
* Another example with multiple systems but no codes in them: http://hapi.fhir.org/baseR4/ValueSet/1854515 (For this one, I would think we simply display the headers without codes underneath)

**Comment by snyaggarwal** [comment]
@jamlung-ri Added the compose system header.

**Comment by jamlung-ri** [comment]
This is looking good!
