### ISSUE TITLE
Test OCL TermBrowser in other browsers

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#729]
Especially Safari and firefox. Most of our current testing is done in Chrome

**Comment by jamlung-ri** [comment]
I have been consistently doing my testing in Firefox, and I also tried out some basic features today using Microsoft Edge. I was unable to find any issues so far.

**Comment by jamlung-ri** [comment]
This has been done, but we need to think about how we can continually do this in the long term. In tickets that involve UI, we should either have a checklist or tags to show that we have tested in multiple browsers.
