### ISSUE TITLE
Collection exports contain multiple copies of a resource

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#73]
The following exports each appear to have multiple copies of some resources:
* https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Mini/v1.1/export/ 
* https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/v1.1/export/ 
* https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Extended/v1.1/export/

For example take a look at the following:
* Mini: (concept) id 2052
* Compact: (concept) id 2054
* Extended: (concept) id 13

**Comment by paynejd** [comment]
Please take a look at this one next. This is a blocker for the Ethiopia mobile app... Always have a fire somewhere :)

**Comment by rkorytkowski** [comment]
I've verified that these concepts have been added multiple times to the mentioned collections. I think it is, because some expressions may evaluate to the same concept, thus it gets added multiple times. The fix is to change the list of concepts/mappings to be a set instead. One will have to create a new version of a collection to have it fixed. We will not go through all existing versions to eliminate duplicates. Would you find it acceptable?

**Comment by rkorytkowski** [comment]
BTW #1 should deal with eliminating duplicates from existing versions, but I'll have to verify that...

**Comment by rkorytkowski** [comment]
Committed in 5f408a7f1a3bce466d0c8570643f5a769e344557

**Comment by rkorytkowski** [comment]
Deployed to staging...

**Comment by paynejd** [comment]
ThoughtWorks put checks in place that should have prevented a collection from ever having duplicates, even if it is technically supported within the Mongo list object. When you submit an API request to add a reference to a collection, it is supposed to reject the request if any version of the concept already exists in the collection. Is that not happening correctly?

The change to a Mongo set seems fine, but let's also make sure that this is working on the curation side.

**Comment by paynejd** [comment]
One more thing -- I don't have an easy way to test this on staging since I do not know of any collections that have duplicates. I'll have to wait until it goes into production.

**Comment by rkorytkowski** [comment]
Is it possible that those collections were created before the checks? I saw some of the checks, but not sure, if they cover all edge cases e.g. adding a mapping depending on a concept to be added first.

I'll deploy to production on Monday.

**Comment by paynejd** [comment]
It is possible, though on the latest update (about 1 month ago) I actually
deleted all references in those collections and created all new references
from scratch. Seems like the checks are not catching everything

**Comment by rkorytkowski** [comment]
Deployed to production.

Using a set is the easiest way to avoid duplicates. I could test some edge cases though...

**Comment by paynejd** [comment]
Unfortunately exports are still producing duplicates. To verify, I deleted the export and recreated it to make sure an old export file wasn't cached on AWS -- but the duplicates were still there. Here's the one I'm using to test:
* NCoD Mini Collection: https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Mini/v1.2/export/

My initial guess was that duplicates were actually 2 different versions of the same concept, because that would get around the uniqueness requirement of the new `set` that you implemented, but it's actually the same exact concept version showing up twice in the export. I pasted an example below, but this happened for at least 5 different concepts that I've found so far.

```JSON
{"type": "Concept", "uuid": "5bc8c7e4ff9616006226f0b3", "id": "665", "external_id": null, "concept_class": "Diagnosis", "datatype": "None", "display_name": "Arrhythmias (Other cardiac arrhythmias)", "display_locale": "en", "names": [{"uuid": "3fc58ee1f4d747d3b90c4b03255ec927", "external_id": null, "name": "Arrhythmias (Other cardiac arrhythmias)", "locale": "en", "locale_preferred": true, "name_type": "Fully Specified", "type": "ConceptName"}], "descriptions": [{"uuid": "601188a32823497b8f848ecd829ee312", "external_id": null, "description": "any of a large and heterogeneous group of conditions in which there is abnormal electrical activity in the heart. The heartbeat may be too fast or too slow, and may be regular or irregular.", "locale": "en", "locale_preferred": true, "description_type": "Description", "type": "ConceptDescription"}], "retired": false, "source": "NCoD", "source_url": "/orgs/EthiopiaNHDD/sources/NCoD/", "owner": "EthiopiaNHDD", "owner_type": "Organization", "owner_url": "/orgs/EthiopiaNHDD/", "version": "5bc8c7e4ff9616006226f0b3", "created_on": "2018-10-18T13:50:28.231", "updated_on": "2018-10-18T13:50:29.307", "version_created_on": "2018-10-18T13:50:28.231", "version_created_by": "ethiopianhddadmin", "extras": {"ICD10Chapter": "Circulatory System", "ICD10Block": "I30"}, "mappings": null, "is_latest_version": true, "locale": null, "version_url": "/orgs/EthiopiaNHDD/sources/NCoD/concepts/665/5bc8c7e4ff9616006226f0b3/", "url": "/orgs/EthiopiaNHDD/sources/NCoD/concepts/665/"}
```

**Comment by paynejd** [comment]
Marking this as a blocker for the planned NHDD mobile app pilot testing in Ethiopia for next week (~Dec 10)

**Comment by rkorytkowski** [comment]
I'm sorry John, but I've reverted the change in pursuit for fixing #79 and forgot to deploy it again. I will do it right now.

**Comment by paynejd** [comment]
Would it be possible to implement a test script for exports that verifies the concepts and mappings exactly match the references?

**Comment by rkorytkowski** [comment]
It happened to be another issue. A few collection versions had references to unexsiting concepts and the iteration logic did not expect that and made a loop. Again we do not have a way to track down when/how that happened. I added a check on each startup to identify and resolve such issues in the future. If they happen again, I will be notified.
The reported issues were:
celery_1  | [2019-01-08 02:53:38,293: ERROR/Worker-4] tasks.data_integrity_checks[be5434a5-d969-41df-ac0a-85bbeb6171ec]: Removing 2057 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Extended/HEAD/
celery_1  | [2019-01-08 02:53:38,852: ERROR/Worker-4] tasks.data_integrity_checks[be5434a5-d969-41df-ac0a-85bbeb6171ec]: Removing 1851 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Compact/HEAD/
celery_1  | [2019-01-08 02:53:39,271: ERROR/Worker-4] tasks.data_integrity_checks[be5434a5-d969-41df-ac0a-85bbeb6171ec]: Removing 616 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Mini/HEAD/

**Comment by rkorytkowski** [comment]
Awaits deployment to staging and production...

**Comment by rkorytkowski** [comment]
Deployed to staging. Reported and resolved issues:
`[2019-01-08 03:06:33,426: INFO/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Checking for broken concept and mapping references in collection versions
celery_1  | [2019-01-08 03:06:34,893: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /users/leahgatt/collections/LGTC/HEAD/
celery_1  | [2019-01-08 03:06:34,972: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 10 broken concept references from collection version /users/leahgatt/collections/1.2/HEAD/
celery_1  | [2019-01-08 03:06:34,983: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 10 broken concept references from collection version /orgs/FMOH-DD/collections/ANC-reg/HEAD/
celery_1  | [2019-01-08 03:06:35,025: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 9 broken concept references from collection version /users/leahgatt/collections/testing/HEAD/
celery_1  | [2019-01-08 03:06:35,053: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 4 broken concept references from collection version /orgs/EthiopiaMOH/collections/NCoD-Mini/HEAD/
celery_1  | [2019-01-08 03:06:35,083: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken concept references from collection version /users/paynejd/collections/MyCollection/HEAD/
celery_1  | [2019-01-08 03:06:35,091: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken mapping references from collection version /users/paynejd/collections/MyCollection/HEAD/
celery_1  | [2019-01-08 03:06:35,103: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken mapping references from collection version /users/paynejd/collections/MyCollection/v0.9/
celery_1  | [2019-01-08 03:06:35,113: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken concept references from collection version /users/djazayeri/collections/TEST/HEAD/
celery_1  | [2019-01-08 03:06:35,124: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken concept references from collection version /users/anshuagg/collections/c1/HEAD/
celery_1  | [2019-01-08 03:06:35,134: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken concept references from collection version /users/anjali.wadhwa1/collections/C1/HEAD/
celery_1  | [2019-01-08 03:06:35,147: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 11 broken concept references from collection version /users/rocket/collections/rsk-collection1/HEAD/
celery_1  | [2019-01-08 03:06:35,158: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken concept references from collection version /users/djazayeri/collections/OMRS/HEAD/
celery_1  | [2019-01-08 03:06:35,177: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 2 broken concept references from collection version /orgs/openmrs/collections/reference-application/HEAD/
celery_1  | [2019-01-08 03:06:35,194: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /users/djazayeri/collections/DxStart/HEAD/
celery_1  | [2019-01-08 03:06:35,203: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken mapping references from collection version /users/djazayeri/collections/DxStart/HEAD/
celery_1  | [2019-01-08 03:06:35,227: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 10 broken concept references from collection version /users/djazayeri/collections/OMRS16/HEAD/
celery_1  | [2019-01-08 03:06:35,234: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 1 broken mapping references from collection version /users/djazayeri/collections/OMRS16/HEAD/
celery_1  | [2019-01-08 03:06:56,726: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 17 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Total/HEAD/
celery_1  | [2019-01-08 03:06:56,739: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-lt-15-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,749: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-lt-15-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,766: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-15-plus-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,777: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-15-plus-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,787: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-lt-15-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,798: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-lt-15-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,809: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-15-plus-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,819: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-15-plus-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,830: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-ART-N-MOH-Total/HEAD/
celery_1  | [2019-01-08 03:06:56,840: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-Total/HEAD/
celery_1  | [2019-01-08 03:06:56,850: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 2 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-KnownPositives/HEAD/
celery_1  | [2019-01-08 03:06:56,859: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 2 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-NewlyTestedPositives/HEAD/
celery_1  | [2019-01-08 03:06:56,869: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-NewNegatives/HEAD/
celery_1  | [2019-01-08 03:06:56,879: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-lt-15-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,889: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-lt-15-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,900: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-15-plus-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,910: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-15-plus-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,922: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-lt-15-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,931: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-lt-15-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,940: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-15-plus-Female/HEAD/
celery_1  | [2019-01-08 03:06:56,949: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-15-plus-Male/HEAD/
celery_1  | [2019-01-08 03:06:56,959: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 17 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Total/FY17/
celery_1  | [2019-01-08 03:06:56,970: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-lt-15-Female/FY17/
celery_1  | [2019-01-08 03:06:56,980: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-lt-15-Male/FY17/
celery_1  | [2019-01-08 03:06:56,991: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-15-plus-Female/FY17/
celery_1  | [2019-01-08 03:06:57,002: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Positive-15-plus-Male/FY17/
celery_1  | [2019-01-08 03:06:57,012: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-lt-15-Female/FY17/
celery_1  | [2019-01-08 03:06:57,023: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-lt-15-Male/FY17/
celery_1  | [2019-01-08 03:06:57,034: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-15-plus-Female/FY17/
celery_1  | [2019-01-08 03:06:57,045: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 6 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/HTS-TST-N-MOH-Age-Sex-Result-Negative-15-plus-Male/FY17/
celery_1  | [2019-01-08 03:06:57,056: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-ART-N-MOH-Total/FY17/
celery_1  | [2019-01-08 03:06:57,066: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-Total/FY17/
celery_1  | [2019-01-08 03:06:57,077: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 2 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-KnownPositives/FY17/
celery_1  | [2019-01-08 03:06:57,087: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 2 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-NewlyTestedPositives/FY17/
celery_1  | [2019-01-08 03:06:57,096: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/PMTCT-STAT-N-MOH-KnownPosNeg-NewNegatives/FY17/
celery_1  | [2019-01-08 03:06:57,107: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-lt-15-Female/FY17/
celery_1  | [2019-01-08 03:06:57,117: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-lt-15-Male/FY17/
celery_1  | [2019-01-08 03:06:57,128: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-15-plus-Female/FY17/
celery_1  | [2019-01-08 03:06:57,138: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 3 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-CURR-N-MOH-Age-Sex-15-plus-Male/FY17/
celery_1  | [2019-01-08 03:06:57,148: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-lt-15-Female/FY17/
celery_1  | [2019-01-08 03:06:57,159: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-lt-15-Male/FY17/
celery_1  | [2019-01-08 03:06:57,169: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-15-plus-Female/FY17/
celery_1  | [2019-01-08 03:06:57,179: ERROR/Worker-3] tasks.data_integrity_checks[4b508653-8a87-4100-8c4a-b758122da336]: Removing 5 broken concept references from collection version /orgs/DATIM-MOH-RW/collections/TX-NEW-N-MOH-Age-Sex-15-plus-Male/FY17/`

**Comment by rkorytkowski** [comment]
The production was much healthier. The only reported issues were:

[2019-01-08 03:15:18,576: ERROR/Worker-1] tasks.data_integrity_checks[dd6e30ef-e734-487f-ac65-84adb39746ed]: Removing 2057 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Extended/HEAD/
celery_1  | [2019-01-08 03:15:19,360: ERROR/Worker-1] tasks.data_integrity_checks[dd6e30ef-e734-487f-ac65-84adb39746ed]: Removing 1851 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Compact/HEAD/
celery_1  | [2019-01-08 03:15:19,421: INFO/MainProcess] Events of group {task} enabled by remote.
celery_1  | [2019-01-08 03:15:19,949: ERROR/Worker-1] tasks.data_integrity_checks[dd6e30ef-e734-487f-ac65-84adb39746ed]: Removing 616 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Mini/HEAD/
celery_1  | [2019-01-08 03:15:26,142: ERROR/Worker-1] tasks.data_integrity_checks[dd6e30ef-e734-487f-ac65-84adb39746ed]: Removing 2057 broken concept references from collection version /orgs/EthiopiaNHDD/collections/NCoD-Extended/v1.3/

**Comment by paynejd** [comment]
Unfortunately the export still contained duplicate records.

These two exports should have identical concepts and mappings, and they do
when you browse via the web interface or the API, but the collection export
has ~1k more concepts and mappings. Note that the number of references in
the collection is correct (meaning it matches the number of concepts and
mappings that are supposed to be in v1.2 of the collection export).

* https://openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/v1.2/export/
*
https://openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Extended/v1.2/export/

**Comment by rkorytkowski** [comment]
I'm sorry I haven't checked an export content. I assumed it was ok as it was much smaller. I'll look into that.

**Comment by rkorytkowski** [comment]
Fixed pagination logic.

**Comment by rkorytkowski** [comment]
Deployed to staging and production...

**Comment by paynejd** [comment]
fixed!!! thank you
