### ISSUE TITLE
Update syntax for concept codes

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#737]
The FHIR specification has very few restrictions on the allowed characters in a concept code:

> Technically, a code is restricted to a string which has at least one character and no leading or trailing whitespace, and where there is no whitespace other than single spaces in the contents
> Regex: `[^\s]+(\s[^\s]+)*`

We are aiming to publish code systems from the WHO soon that use characters that are not currently allowed by the OCL API.

OCL historically restricted concept IDs to characters that could easily be represented in a URL, however we will need to support any code that FHIR allows.

At the database and index level, this should be a quick fix, but we need to understand how this impacts all API requests where a concept ID is embedded in a URL.

Note that FHIR writes directly to the OCL postgres database and FHIR API requests already support the syntax described here, so there probably are not any changes that need to be made there to support this.

cc @harpatel1

**Comment by paynejd** [comment]
additional info:

OCL needs to allow basically any character for a concept ID. See example below of the use of a forward slash in an ID, which we'll need to handle as a special case. There may be other characters that need to get handled as a special case as well. Note that FHIR allows any character whatsoever in a code, except for leading/trailing whitespace.

It turns out there are fourteen PIH concepts that contain one or more forward slashes (/) in the concept's code, which leads to to_concept_url properties like "/orgs/PIH/sources/PIH/concepts/HOUSEWORK/FIELDWORK/". OCL only uses the code up to the first forward slash. For example, Housework/Fieldwork (273) is mapped to "HOUSEWORK" instead of "HOUSEWORK/FIELDWORK".

@jon – I assume the OCL API and any clients using it should probably URL encode forward slashes, so HOUSEWORK/FIELDWORK would become HOUSEWORK%2FFIELDWORK within a URL, right?

HOUSEWORK/FIELDWORK
Daytime asthma symptoms for more than a few minutes more than once/week
Insulin 70/30
Radiology images of musculoskeletal system (non-cranial/spinal)
ABSENCE OF S3/S4 MURMUR
Unplanned intubation for respiratory/cardiac failure
Obstetrics/Gynecology
Dirty/Infected
Clean/Contaminated
YES, AFTER EDUCATION AND/OR ASSIGNING A COMMUNITY HEALTH WORKER
2S+RHEZ / 1RHEZ / 5RH+E
2RHZ / 4RH
2RHEZ / 4RH
Malaria in Mother Complicating Pregnancy, Childbirth and/or Puerperium

**Comment by paynejd** [comment]
Open question: Should we apply this to all resources and not just concepts?

**Comment by snyaggarwal** [comment]
@paynejd -- Notes from our last dev call discussion
 - Will start with concepts only, and test/try it out, then we can take a call if we want to extend it to all (or some) other resources
 - While requesting a concept from a URL, the user needs to encode the concept id, 
   - concept id `Foo/Bar` needs to be requested as `/orgs/MyOrg/sources/MySource/Foo%2FBar/`
 - the `url` in concept response will be `/orgs/MyOrg/sources/MySource/Foo%2FBar/`
 - UI can show decoded id `Foo/Bar`
 - Search term should work for `Foo/Bar`(encoded) and `Foo%2FBar`(decoded) both.
 
 @paynejd Let me know if there is anything missing from this.

**Comment by jamlung-ri** [comment]
Some testing needed here but mostly completed.

**Comment by snyaggarwal** [comment]
@paynejd `ocldev` replaces any special characters (except, `_` and `.`) with `-`. 
We need to change this behavior. New Parallel bulk import is already handling this.

**Comment by paynejd** [comment]
@snyaggarwal to update csv converter with a switch to determine whether IDs encode special characters or replace with hyphens
Then we'll retest with the new parallel import method

**Comment by snyaggarwal** [comment]
@paynejd This should be working now for CSV as well in both import modes.
added `allow_special_characters` in `OclCsvToJsonConverter` with default value `False`

**Comment by jamlung-ri** [comment]
Waiting on FHIR, so let's assign Rafal but keep in mind that there may be some OCL work to be done too.
