### ISSUE TITLE
Effort involved in deploying ReactJS app in JetStream environment?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#74]
Hi there, we have a new ReactJS app that is evolving into the "OCL Browser", which will be the primary front-end for users that are only browsing existing terminology. You can check it out here: https://codepen.io/paynejd/full/zMqwjQ/

It is not ready for deployment yet, but it is the right time to scope out what this will take.

@rkorytkowski could you provide a brief description and estimate of work level for this? or is there more information that you need?

**Comment by rkorytkowski** [comment]
We need to:
1. Dockerize the app by adding a Dockerfile and creating a docker-compose file
2. Create a CI build, which pushes a docker image to dockerhub
3. Create CI deployment plans for staging and production
4. Update CI plan for demo env to deploy the app as well
5. Create DNS entries for the new app e.g. browser.openconceptlab.org, browser.qa.openconceptlab.org, ...
6. Add docker-compose files to https://github.com/openmrs/openmrs-contrib-ansible-docker-compose/tree/master/files
7. Setup ansible to provision new app on all envs

It should be < 8h of work.
