### ISSUE TITLE
Design/fix hierarchy in oclweb2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#741]
Followup ticket to #585 -- create mockups for navigating hierarchy in oclweb2

**Comment by jamlung-ri** [comment]
Basic Ideas:
* May need to free up vertical space, potentially by collapsing the header for a Source
* [ICD-like](https://icd.who.int/browse10/2019/en#/) tree view seems like the low-hanging fruit ([React Component](https://material-ui.com/components/tree-view/#customized-tree-view)). This includes:
    * Tree navigation view on the left
    * Concept details on the right
    * Maybe allow adjusting left/right window sizes?
    * Search features: TBD
    * Allow multi-select for comparison
* [Map-like](https://athena.ohdsi.org/search-terms/terms/4299326/graph?levels=10&standardsOnly=false&zoomLevel=4) view seems doable, although we will need to determine how far back and forward to go from a particular concept
   * Ability to switch between map details like OHDSI allows? (Options include Maximum, Minimum, Vocab, etc.)
* Features NOT available(?):
   * Row expansion for more details on a concept (e.g. Mappings, Synonyms, etc.)
   * Filtering? 
   * Sorting? 
*

**Comment by jamlung-ri** [comment]
Moving to next sprint, and the mockup work will be reflected in #770.

**Comment by jamlung-ri** [comment]
Initial mockups for hierarchy-aware views are found here: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/M1uSIRRcj

**Comment by jamlung-ri** [comment]
Changes that will be needed to OCL's hierarchy display in the long run:
* Retired concepts need to be hidden by default and loaded upon request. Maybe the hierarchy API needs to be sensitive to retired=true and retired=false?
* One of two ways to show or not show hierarchy:
    * a. Hierarchy should be hidden by default if its source does not have a hierarchy_root_url, and it should be shown by default if the source does have hierarchy_root_url
    * b. Hierarchy can be shown or hidden at the beginning. If the user chooses to hide or show it, it should stay that way when the user goes to other sources or concepts.

**Comment by jamlung-ri** [comment]
Note that #916 is tracking the slight revamp of resource details page, which should include additional hierarchy features

**Comment by jamlung-ri** [comment]
Working on this in the Associations section, in addition to the existing hierarchy sidebar. Mockups in progress: https://docs.google.com/presentation/d/1nkGq1Zx_SDJa-8NblyaHIr5Ot33xKWem-vyTtLjQu1k/edit#slide=id.geec45cc76a_0_0

**Comment by jamlung-ri** [comment]
The first iteration of this has been handled by Paul as part of the Split View design. Closing this out, and we can create new tickets where maintenance and UI changes are needed.
