### ISSUE TITLE
FHIR Connector Development - Round 3

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#743]
Continuing from #659 and #723

In scope for this ticket:
* ConceptMap List Display
* Individual ConceptMap View

Documentation for this is available here: https://docs.google.com/document/d/1ZKFabSxL1Tc9hsw2n3FadwiRBmwBWeTwTyEPR8R2jIs/edit#heading=h.o5ivpcba5hhy

Mockups are available here: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/VMDa3wJDj

**Comment by snyaggarwal** [comment]
### Tasks:

#### HAPI FHIR:
 - [x] Listing
     - [x] Pagination
     - [x] Sorting
     - [x] Search
 - [x] Details
     - [x] Groups
   
#### OCL FHIR:
 - [x] Listing
     - [x] Pagination
     - [x] Sorting
     - [x] Search
 - [ ] Details
     - [x] Groups
     - [ ] Pagination

**Comment by snyaggarwal** [comment]
@jamlung-ri This is good to review on QA.

**Comment by jamlung-ri** [comment]
This is a great start! Overall, I think it might be good to have a layout that is a little more tabular. I do like that the map_types can be collapsed, but it might be better if there are more lines to add separation between concepts and map types. An example of this from Framer is shown in the image below, where there are lines between each row.
![image](https://user-images.githubusercontent.com/55999682/118130173-13643780-b3cb-11eb-9c1c-29629ca85dc0.png)

Some other feedback:

- [ ] When looking at https://app.qa.openconceptlab.org/#/fhir/ConceptMap/ndc-cvx on Firefox, I notice lots of horizontal lines on the right side of the screen (see image)
![image](https://user-images.githubusercontent.com/55999682/118129461-3215fe80-b3ca-11eb-99d4-5faf6d1c6732.png)

- [ ] When a ConceptMap resource only has a Source and Target URI but no `group` attribute (e.g. https://hapi.fhir.org/baseR4//ConceptMap/584854 shown at [this link](https://app.qa.openconceptlab.org/#/fhir/ConceptMap/584854)), these URI attributes should still be displayed, maybe in a header like what is shown [here](https://app.qa.openconceptlab.org/#/fhir/ConceptMap/absence-to-snomed-uv-ips) but the Count can be 0 and the header can simply not be expandable.

**Comment by jamlung-ri** [comment]
We can save the Expand/Collapse button for a later iteration, if needed. Everything else is looking good on this though.
