### ISSUE TITLE
Planning for Concept Modification

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#746]
Documentation for this is available here: https://docs.google.com/document/d/1uhnnKxB_X_XLGeO7KSEN1obdL-UpkD82BraYE_ZpTzY/edit

We will be meeting multiple times this sprint to discuss this major topic.

Checklist:

- [x] Identify interrelated categories of work
- [x] High-level requirements for each category of work
- [x] Identify dependencies and quick wins (“low-hanging fruit”)
- [x] Unified requirements
- [x] Technical requirements for a common OCL/FHIR approach
- [x] Define high-level approach
- [x] Define epics and tickets
- [x] Create timeline for concept modifications based on OpenMRS requirements

**Comment by jamlung-ri** [comment]
Moving this into the next sprint since we still have more discussion to do. We are somewhere around halfway done at this point, if not a little more.

**Comment by paynejd** [comment]
We made a lot of progress here and additional work will be completed in new tickets, beginning with #792
