### ISSUE TITLE
Start documentation on UI configuration

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#748]
This will go into ReadTheDocs. Can start as a gdoc

**Comment by jamlung-ri** [comment]
Documentation for this has been started here but still requires more work from me. https://docs.google.com/document/d/1wIEj48Kx4WllTQl_Zk5qPrnjvNdQ04U9M9VUaFzIAvU/edit#

**Comment by jamlung-ri** [comment]
This documentation is complete as of now, although it will require maintenance when new features are added to the TermBrowser.

**Comment by jamlung-ri** [comment]
Next steps:
* Release TermBrowser customization publicly
* Put this documentation on ReadTheDocs
* Maintain and update this documentation as more features are added.
