### ISSUE TITLE
Create OCL demo server that is automatically reset daily

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#75]
It's time that we provide a demo server -- especially because have a training and demo taking place in Lesotho the week of Nov 26 and participants are going to want to play with the tool.

We previously set up "dev.openconceptlab.org" -- can we change that to "demo.openconceptlab.org"? (or we can set up a new instance if that is easier) And can we set it up to reset daily using whatever code is in production?

To begin with, it can have the same starter content as the QA server, which is all of the OCL sources.

Soon after, we should have the CIEL sample dictionary available.

In the future, we may want to create a Demo organization and content that maps to training materials.

**Comment by rkorytkowski** [comment]
Ready! It gets reset nightly by https://ci.openmrs.org/browse/OCL-OD
