### ISSUE TITLE
Compile all OpenMRS validation rules/code applied in OCL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#750]
In the long-long term, we want the OpenMRS validation schema (and validation schemas created in the future) to be managed in a transparent manner, ideally outside of our python code, that business users can update and version along with their sources.

As a very early first step, can we compile all of the rules and locations in the code that are involved in the OpenMRS validation schema? We would like for the OpenMRS community to be able to review and eventually start to manage this directly.

Hoping that there is a way to pull this together really easily -- any format is okay to start, a list of github links to locations in the code, etc.

**Comment by snyaggarwal** [comment]
### Code references
 - Concept Validator -- https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/custom_validators.py#L17
 - Mapping Validator -- https://github.com/OpenConceptLab/oclapi2/blob/master/core/mappings/custom_validators.py#L7
 - Concept Reference Validator -- https://github.com/OpenConceptLab/oclapi2/blob/master/core/mappings/custom_validators.py#L7

**Comment by bmamlin** [comment]
We plan to discuss in the OCL for OpenMRS Squad, but from an initial review:
* I assume [must_have_exactly_one_preferred_name](https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/custom_validators.py#L24) actually means exactly one preferred name _per locale_ (i.e., for each locale with names, there should never be more than one preferred name within the locale).
* The [fully_specified_name_should_be_unique_for_source_and_locale](https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/custom_validators.py#L33) should ignore short names and index terms.

**Comment by jamlung-ri** [comment]
There are related follow-up tickets to discuss this topic. Related tickets will be linked here.
