### ISSUE TITLE
Compile spreadsheet that lists out WHO codes by codesystem

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#752]
To know what ICD, SNOMED, etc. codes will be needed for WHO FP/STI terminology content in OCL

**Comment by jamlung-ri** [comment]
@paynejd @harpatel1 Here is a spreadsheet of value sets and codes that exist in the [WHO Core/FP/STI IGs](http://build.fhir.org/ig/who-int/core/): https://drive.google.com/file/d/1-sRnMMeyMIgB8OLkZ0764TCYyDdyDVWS/view?usp=sharing

This list shows what value sets there are across all three IGs, in addition to what codes come from each system. If we are going to load dummy codes into OCL, this is the list of codes to load. If we instead are going to make references to these codes, that is fine too. We just need to decide what the best approach is. 

This loading will likely be dependent on getting the WHO Extended Content Codesystem loaded into OCL. (#451)

**Comment by paynejd** [comment]
this is now unblocked on OCL QA -- ready to load
