### ISSUE TITLE
[UI][FHIR] Add Actions on CodeSystem/ValueSet/ConceptMap Details

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#755]
#### Actions:
 - [x] Copy FHIR URL 
 - [x] Download JSON

**Comment by snyaggarwal** [comment]
@jamlung-ri Created this to make sure we have some actions on FHIR resource details screen (similar to OCL resources).
For now, I have added Copy URL and Download as JSON. Let me know if you think we can add more.

**Comment by jamlung-ri** [comment]
Awesome, this is great! Some quick changes:

- [ ] When copying a URL in HAPI, it looks like there is an extra "/". It doesn't break the link, but if possible, it would be good to remove it. Example: https://hapi.fhir.org/baseR4//CodeSystem/CRReasonForTest is what link is copied when using this page (see image below).
- [ ] When clicking the download button, the tooltip says "Download JSON" and then requires you to select JSON. Maybe the tooltip can instead just say "Download"? That leaves the door open for us later on when we add more download formats (hopefully).


![image](https://user-images.githubusercontent.com/55999682/118128761-57eed380-b3c9-11eb-9176-030e0731145d.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Both the above suggestions are added

**Comment by jamlung-ri** [comment]
Looks good!
