### ISSUE TITLE
Export Content-Type header

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#758]
In OCL API v1, running an export resulted in a ZIP file sent with the `Content-Type` header set to `application/zip`. In API v2, the ZIP file is returned with the `Content-Type` header set to `binary/octet-stream`. We were using this header to properly process the file in the openconceptlab module, so this change breaks all imports for us. Is it possible to return to using the `application/zip` content type or should we adjust our code?

**Comment by snyaggarwal** [comment]
@ibacher The fix to this is deployed on QA. You can verify this on QA and it will be available on all the other env by EOD.

**Comment by snyaggarwal** [comment]
@ibacher FYI this will work for new imports and not the existing ones.

**Comment by ibacher** [comment]
@snyaggarwal Thanks for the quick fix! LGTM!
