### ISSUE TITLE
API token not appearing on profile page on staging server

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#76]
Several users have reported this issue (including today by user `jedmiston`) and I am experiencing it myself frequently on the staging server -- I have not experienced the issue on production and QA and no one has reported it, but it's possible it may be happening there too. This may be an unintended consequence of the new API endpoint for requesting the API token? (see `POST https://api.openconceptlab.org/users/login/`)

**Comment by rkorytkowski** [comment]
I had experienced the issue myself in the past before the API endpoint was fixed. I thought it was due to some old and broken user account I used, because I was able to see if for a newly created user account. It needs to be investigated.

**Comment by paynejd** [comment]
Did we remove the functionality where an API token is displayed on a user's profile page? Or are we requiring that they use the new API endpoint `/users/login/` for retrieving their token?
