### ISSUE TITLE
FHIR UI - Server Header Configuration

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#760]
Currently, it looks like the OCL QA server in the FHIR UI is hard-coded to say "PEPFAR" and "The US President's...". 

When looking at a CodeSystem, ValueSet, etc., the header should be updating to show the resource owner's info and the organization namespace, rather than displaying just the server info.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd 
What should be the default value of the header on Fhir Landing pages? Currently they are all hardcoded to PEPFAR.
You can look at the [Server Configs](https://github.com/OpenConceptLab/oclweb2/blob/master/src/common/serverConfigs.js#L47). The `org` parameter is used to populate the header for each FHIR server UI, currently all FHIR (including HAPI) servers has the same information in `org`

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri for OCL FHIR UI, I have added org/user namespaces.
Now you should be able to see specific org's CodeSystem/ValueSets/ConceptMaps.

**Comment by jamlung-ri** [comment]
The org/user namespaces seem to be working well in QA. I was able to navigate through FHIR and PEPFAR/MER resources using the namespace, which was nice. The only thing is that the route to get to those spaces is a little difficult, so I wonder if we can put some time into designing a better way to get there.

There is no header on those individual pages, but I don't know a great way to get those. Maybe we don't need it right now though, since we are envisioning an integrated OCL/FHIR experience in the future.

**Comment by jamlung-ri** [comment]
For now, the easiest way to get to an org is to use the URL in the UI. There isn't really a good way to get to the org for now, unless we develop an API in FHIR that lists out orgs that have a CodeSystem, ValueSet, or ConceptMap.

Closing this for now but may follow up on this idea in the future, especially once we start integrating more between FHIR and OCL UIs
