### ISSUE TITLE
Add version number to API

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#766]
Related to #110 

We need to add a way to include a version number. We can do it the python way:
https://legacy.python.org/dev/peps/pep-0396/

The version needs to be be available from django settings.py and included in all response headers as a custom header:
X-OCL-API-VERSION: 1.0.0-asd35sas

The version will be in format: major.minor.maintenance-git_short_commit_hash, where major, minor and maintenance are ints

The build script should read git hash and put it in the __init__.py file. The "git_short_commit_hash" should not be committed to the repo. It should stay "dev" in the repo. The major.minor.maintenance part will be adjusted manually.

The CI build should be adjusted to use git commit hash as well for release versioning when doing deployments.

**Comment by snyaggarwal** [comment]
Merged with master. Change in bamboo CI script is remaining
