### ISSUE TITLE
Add version number to WEB

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#767]
Related to #110.

Follow similar versioning approach as in #766.

Use the JS preferred way of defining a version and display it in the page footer. There's no need to include it in the http header.

In addition to that display api version in the page footer as well.

**Comment by snyaggarwal** [comment]
Merged with master. Change in bamboo CI script is remaining

**Comment by rkorytkowski** [comment]
CI script is ready. We are waiting for openmrs-bot to accept an invitation from us to be able to push tags to github.
