### ISSUE TITLE
Reusable View Mockup

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#770]
Follow-up from #733

Each view should be able to be hierarchy-aware. I am also mocking up a new view to go with this.

**Comment by jamlung-ri** [comment]
There are two aspects of this that we are dealing with, which I want to make clear here before sharing documents and links:

1. **Configuration Templates** - When an organization has created a set of configured views in the TermBrowser, that set can be saved so that other organizations, sources, etc. can reuse that same set of configured views. 
    * Once a set of configured views has been created, it can be saved both locally and globally. Local templates are available as templates for the owner organization when configuring new views. Global templates are available as templates for all organizations.
    * Since data models can be different across resources (e.g. some concepts have an extras.source attribute that gets used in configurations), some configuration templates will not be directly applicable to a source, organization, etc. but should still be available for adaptation.
2. **View Layouts** - Layouts for individual pages that can be selected for a single tab during configuration in the TermBrowser. 
    * OCL's existing Table and List views are examples of View Layouts.

**Comment by jamlung-ri** [comment]
Jon, Sunny, and I talked about a preliminary design for this work. The notes for this can be found [here](https://docs.google.com/document/d/17FU2Whbj3rlk_VEHrfVUK3bt3V65q3t4UAXUobojNsY/edit#heading=h.4y81qcm1a1vi), along with a super basic [Framer mockup](https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/iZGKWScfq).

**Comment by jamlung-ri** [comment]
@snyaggarwal I can provide examples of the custom config in this comment. 

Org Level:
[PEPFAR Custom Config - 02Jun2021.txt](https://github.com/OpenConceptLab/ocl_issues/files/6585527/PEPFAR.Custom.Config.-.02Jun2021.txt) - Applies to https://app.qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true

Source/Collection Level

**Comment by snyaggarwal** [comment]
@jamlung-ri Do you want to make more updates on this after the changes made https://github.com/OpenConceptLab/ocl_issues/issues/574#issuecomment-853578558 ?

**Comment by jamlung-ri** [comment]
@snyaggarwal Updated!
