### ISSUE TITLE
Username Validation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#773]
I just asked a few people to create OCL accounts in Staging, and one put their email as their username, which ends up failing in OCL. https://app.staging.openconceptlab.org/#/users/hiwot.chichaybelu@icf.com/

Can there be some basic validation to only allow alphanumeric/underscore characters when creating a username? Or whatever the allowed characters are.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is a bug in UI. "@" character is not allowed in routes. Fixed this. In next deployment the username that you added above should work fine.
Also I have added regex pattern on username field in signup form.

**Comment by jamlung-ri** [comment]
This now works in QA. I was able to create an account with an email address as the username, and it works properly.
