### ISSUE TITLE
Review and Update documentation for Matches Deployment

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#776]
https://github.com/pepfar-datim/mAtches

**Comment by maurya** [comment]
Reviewed https://github.com/pepfar-datim/mAtches and updated documentation and added troubleshooting steps. Added to issues for non-functional settings and tool tips icons.

**Comment by maurya** [comment]
Request to set this up with a local HAPI FHIR server using the https://github.com/pepfar-datim/mAtches-ig documentation.

**Comment by jamlung-ri** [comment]
Waiting on Vlad and Felix to do some updates. Moving to Sprint 15

**Comment by jamlung-ri** [comment]
@maurya Any updates here?

**Comment by maurya** [comment]
still waiting on Vlad and Felix - followed up here - https://github.com/pepfar-datim/mAtches/issues/138

**Comment by jamlung-ri** [comment]
Sounds good. Let's move this into the next sprint while we wait for that.

**Comment by maurya** [comment]
Felix made the changes. I will review and update this week

**Comment by maurya** [comment]
Reviewed ticket and requested few other changes.

**Comment by jamlung-ri** [comment]
@maurya Any updates on this? We might close this out if appropriate.

**Comment by maurya** [comment]
The PEPFAR ticket was closed out. Closing this
