### ISSUE TITLE
Load SNOMED into OCL Staging

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#778]
We have a large import file that should be monitored for performance while it is loading. This file is ~500,000 rows, so it may be the largest file that OCL has done to date.

Note that this file has hierarchical data, so the rows need to be processed sequentially.

The zip file has been shared with @snyaggarwal via Google Drive.

**Comment by jamlung-ri** [comment]
Related to #772. This has been started but needs more time to continue.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri This is available on Staging

**Comment by jamlung-ri** [comment]
Since there is a ticket for testing this already (#772), I think this ticket can be closed out.
