### ISSUE TITLE
Create admin user with demo data in oclapi

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#78]
Currently admin user is being created only by the web. We need to create it in API so that if only API is redeployed with a new database we still get an admin user.

**Comment by paynejd** [comment]
Does this change how ocl_web should be deployed? If yes, is the readme updated to reflect this?

**Comment by rkorytkowski** [comment]
Nothing changed here regarding deployment. I just tweaked the logic. We have the IMPORT_DEMO_DATA env variable on oclapi and ocl_web and it must be set to true on both, but it's documented already in READMEs.
