### ISSUE TITLE
to_concept_url not being populated as expected

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#781]
When importing the PIH dictionary into OCL, I noticed mappings to CIEL were not clickable in the app. It turns out this is because the `to_concept_url` of mappings is unexpectedly `null`.

For example, [PIH 193](https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/concepts/193/) contains a mapping to [CIEL 159392](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/159392/), but the mapping is not clickable:
![image](https://user-images.githubusercontent.com/860834/119992093-2fa1d000-bf98-11eb-8314-87e5318dc493.png)

Looking at an excerpt of [/orgs/PIH/sources/PIH/concepts/193/?includeMappings=true](https://api.staging.openconceptlab.org/orgs/PIH/sources/PIH/concepts/193/?includeMappings=true):
```json
{
  "external_id": "e0095dbf-7244-4005-8caf-0cf751d20f71",
  "from_concept_code": "193",
  "from_concept_name": null,
  "from_concept_url": "/orgs/PIH/sources/PIH/concepts/193/",
  "to_concept_code": "159392",
  "to_concept_name": null,
  "to_concept_url": null,
  "from_source_name": "PIH",
  "to_source_owner": "CIEL",
  "to_source_owner_type": "Organization",
  "to_source_url": "/orgs/CIEL/sources/CIEL/",
  "to_source_name": "CIEL",
  "url": "/orgs/PIH/sources/PIH/mappings/1450082/",
  "id": "1450082",
  "internal_reference_id": "1450082"
}
```
I believe the `to_concept_url` property is supposed to be populated by the OCL API with `/orgs/CIEL/sources/CIEL/159392/`.

**Comment by snyaggarwal** [comment]
@bmamlin this is now fixed

**Comment by snyaggarwal** [comment]
This is fixed and deployed. Closing this one.
