### ISSUE TITLE
Locale Issue in TermBrowser

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#783]
Looking at some concepts that we have loaded in recently, and it looks like they are all showing as Achinese locales instead of English. It looks like many locales in the UI are appearing with the EN locale. 
Example concept with Achinese [en] locales: 

See screenshots below for example: https://api.qa.openconceptlab.org/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/concepts/129984005/

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/4479761c-449e-4d59-b040-7c0bbd8508fa)
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/2ca22d03-daf9-4562-a189-fd82ab5b807e)

**Comment by snyaggarwal** [comment]
Fixed

**Comment by jamlung-ri** [comment]
Looking good in QA!
