### ISSUE TITLE
Add link to "Compare" feature into list of mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#785]
For "internal mappings" (where both from and to concepts are defined in OCL), let's add a link to make it easy to open up the Compare tools. I'd prefer to have a vertical 3-dots icon at the right side of each mapping that opens up a menu of actions that can be performed, including "Open Mapping Details", "Compare Concepts", "Open from/to concept details", etc.

**Comment by snyaggarwal** [comment]
@paynejd Added the following:
1. Concept Home -> Mapping Listing
    - 3 dots menu on the right (where the lense icon used to be to navigate to mapping details)
    - Options:
        - Open Mapping Details
        - Open From or To Concept Details (based on direct or indirect mapping)
        - Compare Concepts
2. Mapping Home -> Header
    - Added Compare Concepts option (next to download option)

**Comment by snyaggarwal** [comment]
@paynejd Do we want to add these options in Mapping Listing inside source/collection/global? Right now we have an expand row button which lists versions (only), don't think that's very useful for mapping.
Let me know, it will be a quick change.

**Comment by paynejd** [comment]
@snyaggarwal The change works great!
Good idea to add to the mapping lists as well

**Comment by snyaggarwal** [comment]
Added to all mapping lists

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?
