### ISSUE TITLE
Reusable Views Development

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#786]
Using the resources in #770, we are ready to start developing reusable configuration templates. These are OCL-curated configuration JSON files, which are available as templates to get started with when an admin is configuring their content views using OCL TermBrowser's "configs=true" setup interface. 

Note that at least one more config file will be provided after the initial batch in #770.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd The templates for source/collection/org are added on QA.

**Comment by jamlung-ri** [comment]
@snyaggarwal I believe you were planning to write this out a little bit, but I explored it a little and thought I might try describing it here. Let me know if I'm understanding this correctly.

Right now, any time you go to configure the look of any org, source, or collection by opening up the configuration interface, you can select from a list of configs. This list includes the OCL Default and any configs already created for that resource, PLUS the templates that are available (marked with "Template"). The templates can be selected and viewed to see how one's content might look with it, and then you can "Create Similar" to start making it your own. 

Example:
![image](https://user-images.githubusercontent.com/55999682/121057037-da7e6f00-c78c-11eb-9333-28511657d48e.png)

I think this approach works for now, but in the long term, we probably need a more sophisticated interface, particularly that can organize the templates by owner or other attributes.

One next step will be to define the API call needed to create/post a new template.

**Comment by snyaggarwal** [comment]
@jamlung-ri yes you are right!
This was a very quick way to throw everything together in UI, and I agree that we need more info and may be better flow to make decision making easier.
And we do have API to create/update/delete templates in swagger, I will add the details here on how to use it.

**Comment by snyaggarwal** [comment]
Templates API:
POST /client-configs/orgs/templates/
POST /client-configs/sources/templates/
POST /client-configs/collections/templates/
```
{
  "name": "Org Template1",
  "description": "Description",
  "config": {
  "tabs": [
    {
      "type": "sources",
      "label": "Sources",
      "layout": "table",
      "default": true,
      "page_size": 25
    },
    {
      "type": "collections",
      "label": "Code Lists",
      "fields": [
        {
          "full_name": "Name"
        },
        {
          "extras.resultTarget": "Result/Target"
        }
      ],
      "layout": "list",
      "filters": {
        "collection_type": "Code List",
        "extras.resultTarget": {
          "name": "Type",
          "options": [
            "Result",
            "Target"
          ]
        },
        "extras.Applicable Periods": {
          "name": "Period",
          "options": [
            "FY16",
            "FY17",
            "FY18",
            "FY19",
            "FY20",
            "FY21"
          ]
        }
      },
      "page_size": 25
    },
    {
      "type": "about",
      "label": "Key Updates and Changes"
    },
    {
      "type": "about",
      "label": "About"
    }
  ]
  }
}
```

**Comment by snyaggarwal** [comment]
Templates API:
- Update Template (or any config)
   PUT /client-configs/<id>/ 
   ```
   {
      "name": "new-name",
      "description": "new-description",
      "config" : {"tabs": [{...}, {....}]}
   }
   ```

- Delete Template (or any config)
 DELETE /client-configs/<id>/

**Comment by jamlung-ri** [comment]
I tested the configuration API in QA, and I was able to create a new template, update its name, and delete an outdated template. If anyone wants access to the Postman space where I have my queries, just let me know!
