### ISSUE TITLE
Compare names and descriptions by locale

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#787]
Names & descriptions should only be compared within the same locale. Currently, the comparison tool appears to be comparing names as a list without regard to the locale.

At the moment, there is an example [here](https://app.qa.openconceptlab.org/#/concepts/compare?lhs=/users/burke/sources/test1/concepts/1/&rhs=/orgs/CIEL/sources/CIEL/concepts/116128/). In this example, all names were manually Here's a screenshot in case the example is lost:
![image](https://user-images.githubusercontent.com/860834/120651442-c95ff600-c44c-11eb-918b-d5785fa74d10.png)

**Comment by snyaggarwal** [comment]
@bmamlin This is fixed! Should be available on QA in few

**Comment by snyaggarwal** [comment]
@bmamlin Can we close this?
