### ISSUE TITLE
Complete requirements to allow references that OCL is not able to resolve

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#792]
We made a lot of progress on concept modification requirements in #746. We are now focusing in specifically on allowing references that OCL is not able to resolve. These are being specified in the **Round 1 Work** section of the requirements document:

https://docs.google.com/document/d/1uhnnKxB_X_XLGeO7KSEN1obdL-UpkD82BraYE_ZpTzY/edit#heading=h.xts14qvp1zp2

**Comment by jamlung-ri** [comment]
First round can make references toward any enumerated resource, and later we can work on reference that refer to multiple resources e.g. collection of collections.

**Comment by jamlung-ri** [comment]
Question: what happens when we split HEAD and don't automatically resolve references?

**Comment by jamlung-ri** [comment]
@paynejd and @jamlung-ri to make examples of JSON for "collection of collections" and make sure we are separating out the workflow from defining the references.

**Comment by jamlung-ri** [comment]
A first round of this has been done here: https://docs.google.com/document/d/1uhnnKxB_X_XLGeO7KSEN1obdL-UpkD82BraYE_ZpTzY/edit#heading=h.7zoq2ojuyu2u

More discussion is needed on OCL Dev and Arch calls.

**Comment by jamlung-ri** [comment]
Complete, now we need a ticket to implement this work.
