### ISSUE TITLE
Add hierarchy support to CSV converter

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#798]
If this is a quick fix, this would help a lot with importing ICD10

**Comment by paynejd** [comment]
cc @jamlung-ri

**Comment by snyaggarwal** [comment]
@paynejd this should work with CSV now. Updated ocldev in oclapi2.
Haven't updated the ocldev version yet.

**Comment by jamlung-ri** [comment]
This is now working in QA. I was able to load hierarchical test content via CSV.
