### ISSUE TITLE
Show hierarchy in TermBrowser (when applicable)

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#799]
We want a way to view parent and child concepts in OCL, and although we will definitely have a more intuitive way to do that in the future, we need a quick way to view hierarchy in the TermBrowser when looking at an individual concept. 

I envision something in the Header that is similar to the Custom Attributes button. This "Hierarchy" button would appear only if the concept has either parent or child concepts, and it would just show them in a list, same as how the Custom Attributes button does it.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/0b7800e1-55e0-4ab7-b89d-2e6f60f8c209)

@snyaggarwal Can you let us know if this doesn't make sense or if it's more work than I am expecting? If so, we can rework the idea.

Note: Another potential implementation idea could be to include hierarchy (where available) in the expansion for a concept. We could add a tab next to History that also lists out the parent and child concepts.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/0f6c8472-5121-48d1-b2a7-20b99774b01f)

**Comment by jamlung-ri** [comment]
@snyaggarwal For the more advanced display of hierarchy, here are the mockups from our discussion today:
* Hierarchy mockups: https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/M1uSIRRcj
* ICD-10 Page (example of search behavior): https://icd.who.int/browse10/2019/en#/
* Other Split View Mockups (might not be relevant): https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/AByzZ6PYw

**Comment by jamlung-ri** [comment]
Should I create a separate ticket for those more advanced hierarchy views?

**Comment by snyaggarwal** [comment]
@jamlung-ri Ya! It will be great if you can create separate tickets for each view

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri The first hierarchy view is available. Its ICD like left panel for traversing hierarchy. This doesn't have a search yet.

**Comment by snyaggarwal** [comment]
APIs to support hierarchy UI:

- GET /orgs/Apelon-FHIR-Authority/sources/N32773-test/hierarchy/
  ```
  {
    "id": "MySource" 
    "count": 1,
    "children": [
    {
      "uuid": "11095",
      "id": "_TelecommunicationAddressUse",
      "url": "/orgs/Apelon-FHIR-Authority/sources/N32773- test/concepts/_TelecommunicationAddressUse/",
      "children": [
        "/orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/BAD/",
        "/orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/CONF/",
       ],
        "name": "_TelecommunicationAddressUse"
    },
    {
      "root": True,
      "uuid": "11000",
      "id": "_GeneralAddressUse",
      "url": "/orgs/Apelon-FHIR-Authority/sources/N32773- test/concepts/_GeneralAddressUse/",
      "children": [
        "/orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/AS/",
        "/orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/PG/",
      ],
      "name": "_GeneralAddressUse"
    },
    {...}
    ]
  }
  ```
- GET /orgs/Apelon-FHIR-Authority/sources/N32773-test/concepts/AS/?includeHierarchyPath=true
  ```
  {
    "id": "MyConcept",
     .....,
     "hierarchy_path": ["/orgs/Apelon-FHIR-Authority/sources/N32773- test/concepts/_GeneralAddressUse/"]
  }
  ```

**Comment by jamlung-ri** [comment]
@snyaggarwal One high value (and hopefully low effort) change in the hierarchy view is that the Root Hierarchy concept should be at the top, followed by its child concept tree. After those concepts, there should be the non-hierarchy concepts. Even better, it might be good to have two distinct sections: hierarchy and non-hierarchy concepts.

**Comment by jamlung-ri** [comment]
Also, one bug: When I click on the SNOMED header, it breaks the page by going to https://app.qa.openconceptlab.org/#/undefined .
![image](https://user-images.githubusercontent.com/55999682/122783504-9fe1ff80-d27f-11eb-8d6c-f9c4752b1675.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri I have added search and load more options in Hierarchy. Please try this out on QA

**Comment by jamlung-ri** [comment]
Thanks Sunny! The search bar is working great! The Load More button seems to work well too. This isn't the highest priority since we have deliverables due next week, but here is my feedback so far:

- [ ] The Load More button works well, but it might need to be both at the top and bottom of the list (same with the "loading" circle icon thing). I get to the bottom, see that there isn't enough content, so I have to scroll up to the top to press the Load More button.
- [ ] It looks like the Sorting of results in the hierarchy is still backwards e.g. listing with Chapter 22 at the top and Chapter 1 at the bottom. (See screenshot). Since this happens when getting children concepts (e.g. /orgs/WHO-ICD-Test/sources/ICD-10-Test/concepts/V34/children/), I wonder if the right approach would be to implement a Sort feature in the Hierarchy API? Not sure how possible that is.
![image](https://user-images.githubusercontent.com/55999682/123440953-56f0ba80-d5a1-11eb-9c94-08057c31442b.png)

- [ ] I noticed in [QA](https://app.qa.openconceptlab.org/#/orgs/WHO-ICD-Test/sources/ICD-10-Test-Small/) (which has a small subset of ICD content with many concepts without parents) that ICD-10 Root is still appearing in the middle of the list, rather than at the top. I think the ideal sort pattern would be:

    1. Root Concept
    2. Active concepts without parents
    3. Retired concepts without parents (Note that retired concepts WITH parents should appear under its parent, as per normal)

    - Note that this is majorly affecting [SNOMED](https://app.qa.openconceptlab.org/#/orgs/International-Health-Terminology-Standard-Development-Organisation-IHTSDO-/sources/SNOMED/concepts/100177001/), since you need to "Lead More" just to get to the Root Concept. That list is full of retired concepts that alphabetically appear before the root SNOMED concept.  

- [ ] One quick bug that I noticed: this error keeps occurring on a loop. I don't really notice it in the UI, but it keeps attempting to use this function with no success.
![image](https://user-images.githubusercontent.com/55999682/123439835-24928d80-d5a0-11eb-9529-14c6cafab303.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri In order to make a concept appear on top, you have to to make it as a root concept by editing source and assigning that concept url in Hierarchy Root URL field

**Comment by jamlung-ri** [comment]
Ahhh okay, I thought that had already been assigned. Now that there is a Hierarchy Root URL defined, the sorting is working better.

**Comment by jamlung-ri** [comment]
Closing since we have #805 to work on more advanced display
