### ISSUE TITLE
View Configuration | Allow tabs to pull information from other orgs/sources/collections

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#801]
Examples:
1. Org Home to have tab(s) to pull sources/collections/members from other Org
2. Source Home to have tab(s) to pull concepts/mappings from other Source
3. Collection Home to have tab(s) to pull concepts/mappings/references from other Collection

Upcoming:
1. Org home showing concepts/mappings tabs from anywhere (same env)
2. Cross environment tabs

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri 
Example 1: Org Home tabs config to pull Sources/Collections from another org
```
tabs: [
...,
{
      uri: '/orgs/OCL/',
      type: 'sources',
      label: 'OCL Sources',
      layout: 'table',
      default: false,
      page_size: 25
    }
]
```
Example 2: Source/Collection Home tabs config to pull concepts/mappings from another org
```
tabs: [
...,
{
      uri: '/orgs/OCL/sources/Locales/',
      type: 'concepts',
      label: 'OCL Locales',
      layout: 'table',
      page_size: 25
    }
]
```

**Comment by jamlung-ri** [comment]
This appears to be working well! I made a few test tabs in the 'testing' config here: https://app.qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true

One quick validation that I think would be worth adding: if no URI is present, then it allows submission of the config file but will crash when navigating to that tab. We don't necessarily need to validate the URI itself, but we could at least check that it is present when submitting the file (if the tab is not a usual tab type for that resource, of course).

**Comment by snyaggarwal** [comment]
@jamlung-ri Now if the `uri` is not provided for concepts/mappings tabs in Org Home then the UI will not break and it will just show "Invalid Tab Configuration Error".
Same goes for Source/Collection homes.

**Comment by jamlung-ri** [comment]
Perfect! I think we're all done on this ticket then.
