### ISSUE TITLE
View Configuration | allow any tab types to be present on any Resource View

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#802]
Right now we have:
1. Source Home aware of concepts/mappings
2. Collection Home aware of concepts/mappings/references
2. Org Home aware of sources/collections/users

We want any tab type to be configured on any resource home with a custom `uri` to pull data from. 
This requires #801 to be finished.

**Comment by jamlung-ri** [comment]
@snyaggarwal Can you help me understand the difference between this ticket and #801? Is the difference that I could now configure a tab for a source and also use content from another organization?

**Comment by snyaggarwal** [comment]
@jamlung-ri #801 was just to pull the same types of tabs (content from different source/collection/org) while #802 is about any tab in any view (concepts in org home, etc). Unintentionally #801 code covered #802. So This can be closed if #801 is closed.

**Comment by jamlung-ri** [comment]
Perfect, I think this is all working well, so I'm closing it.
