### ISSUE TITLE
Add roadmap to OCL community site

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#811]
As soon as #812 is completed, we want to add the new roadmap directly to the OCL Community site, probably under the Community menu.

In a separate ticket, @maurya will add a link to the new roadmap to OCL Docs.

**Comment by jamlung-ri** [comment]
It looks like this is done on the Wordpress site. However, it doesn't have an icon, and it's also not in the TermBrowser.

**Comment by jamlung-ri** [comment]
Follow-up tickets to be created for this.
