### ISSUE TITLE
ICD-10 Next Steps - Overview Page

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#814]
The work for this ticket itself is done, but there are necessary next steps.

Next steps:

- [x] Test in OCL TermBrowser once hierarchy display is available
- [ ] Engage an ICD-10 expert to check the modeling and ability to use it
- [x] Address localization? (Synonyms, etc.)
- [x] Add other languages (Spanish, French, Russian) See #995.
- [x] Import into production
- [x] Test with validation script (see #928)
- [ ] Create an Overview page for the WHO organization in OCL

Each of these should be given their own ticket if not already done.

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/456#issuecomment-864082751_

**Comment by jamlung-ri** [comment]
@paynejd An Overview page for ICD-10 has been loaded into OCL Staging (see [here](https://app.staging.openconceptlab.org/#/orgs/WHO-ICD-Test)). Can you review this and let me know what changes might be needed before transitioning this to Production?

**Comment by paynejd** [comment]
Regarding branding: Logo and banner look great!

Regarding content: Focus should probably be on the group within the WHO
that maintains classifications --
https://www.who.int/standards/classifications. Something like...

The World Health Organization maintains a Family of International
Classifications and Terminologies including:

   - the International Statistical Classification of Diseases and Related
   Health Problems (ICD),
   - the International Classification of Functioning, Disability and Health
   (ICF),
   - and the International Classification of Health Interventions (ICHI).

These Reference Classifications serve as the global standards for health
data, clinical documentation and statistical aggregation.


Regarding formatting (create new tickets for Sunny?):

   - Mouseover the WHO logo (the edit icon) on the Org Overview page has
   messed up formatting -- the logo basically disappears and the banner shows
   up
   - Org logo is squashed on the other tabs -- should maintain aspect ratio

**Comment by jamlung-ri** [comment]
@paynejd Good feedback! I just updated the content to include information about WHO and the terminology page you linked. Can you check again and see what you think? And if there's any quick changes you want to make, feel free to edit the Org if it's convenient.

And I'll make a ticket for these formatting changes.

**Comment by jamlung-ri** [comment]
The formatting changes are now in place on Staging, so this Org overview is about ready to post in Production, I think. @paynejd to confirm

**Comment by jamlung-ri** [comment]
ICD-10 is now available on Production.
