### ISSUE TITLE
Markdown File Integration in TermBrowser Configs

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#819]
Burke suggested that we, in addition to allowing values and text attributes to appear in Text Tabs, allow linkage to a Markdown file, which could be hosted locally, in GitHub, etc. This file would describe in Markdown format what should appear in the Text Tab. The configuration would just need to point to the file to display it.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd @bmamlin In addition to this, now html the text tab can now accept text or md formats as well.
```
type: "text",
label: "Info",
fields: [
  {value: "Some plain text", format: "text"},
  {value: "<h1>Some Markup</h1>", format: "html"},  # default is html, no need for format attribute here
  {value: "# Hello, *world*!", format: "md"}
]
```
(this should be available in few on QA)

**Comment by snyaggarwal** [comment]
@jamlung-ri @bmamlin @paynejd 
You can now specify the `url` to read from. It can read text/html/md formats right now. It works the same way as `value` described in the previous comment:
```
type: "text",
label: "Info",
fields: [
  {url: "https://text.com", format: "text"},
  {url: "https://html.com", format: "html"},  # default is html, no need for format attribute here
  {url: "https://raw.githubusercontent.com/OpenConceptLab/oclweb2/master/README.md", format: "md"}
]
```

**Comment by jamlung-ri** [comment]
Awesome! This appears to be working well. I even tried to give it a super long markdown file, and it was able to accept that and display it.
