### ISSUE TITLE
Allow Collection Reference from outside OCL

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#820]

**Comment by jamlung-ri** [comment]
We have been testing this using the OCL Smart Guidelines Value Sets (#822). Sunny has already done some work to work on the resolving of references if the concept is available. The two test cases have been [gender](https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/collections/gender-values/) and [cigarettes](https://app.qa.openconceptlab.org/#/orgs/WHO-Smart-Guidelines/collections/cigarettes-smoked-per-day-values/concepts/).

There is one issue that is better shown on tomorrow's Arch call.
