### ISSUE TITLE
Markdown Table Support in TermBrowser Configs

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#825]
Following up on #819, we noticed that markdown files in the TermBrowser are not displaying correctly. Examples below show the input, what it should look like, and how it looks in TermBrowser.

```
Input (from https://github.com/jamlung-ri/Misc-tests/blob/main/test2.md):
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |


Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

Should look like:
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/0ca6df39-9587-4f79-bb49-c78a59b21fe2)

TermBrowser appearance: 
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/e310c806-89ce-4e9e-9934-a84bc0b6bbfc)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed

**Comment by jamlung-ri** [comment]
Perfect! This is working now!
