### ISSUE TITLE
Disable hierarchy view by default

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#835]
Especially for OCL Production environment, the UI's hierarchy pane should not be appearing since it is still experimental/under development and may be confusing to users. The hierarchy icon should only show up for an Admin and the label should include "Beta" in it, eg `Hierarchy View (Beta)`. For other users, the hierarchy pane and button should be disabled or hidden.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done

**Comment by jamlung-ri** [comment]
This is working well in QA, so Hierarchy is not appearing by default. It also looks like Production now does not show hierarchy at all.
