### ISSUE TITLE
Inactivate users that have never signed into OCL v2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#836]
There were many fake user accounts that were migrated from v1 that we can easily identify by the date they last signed in. It is possible that there are legitimate user accounts that still have never signed into OCL v2. To be safe, let's first run a query to determine if a user has any content associated with their account, and we can handle these on a case-by-case basis.

This applies to all environments

**Comment by jamlung-ri** [comment]
We have been discussing this here: https://docs.google.com/document/d/17FU2Whbj3rlk_VEHrfVUK3bt3V65q3t4UAXUobojNsY/edit#heading=h.2tla5zbye9o7

**Comment by jamlung-ri** [comment]
I believe this is also being addressed in #712

**Comment by paynejd** [comment]
Combining this work into #712. Closing this out.
