### ISSUE TITLE
Ability to filter users by date joined

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#838]
We'd like to be able to periodically create a report of users who haver joined in the past x days. This can be accomplished with a filter on `users.date_joined`. This is similar to #829.

**Comment by snyaggarwal** [comment]
@paynejd Following can be used to filter users on date joined:
`?dateJoinedBefore=YYYY-MM-DD`
`?dateJoinedSince=YYYY-MM-DD`
