### ISSUE TITLE
What's needed to deploy and manage new OCL instance in different server environment?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#84]
@rkorytkowski We have request from potential partner to deploy OCL on a new server environment. There are multiple options under consideration, but unfortunately the preferred environment is Azure. If we assume that the OCL team will primarily manage the server, could you help draft what is required to both deploy and support it? Are there new OCL features that need to be developed in order to support this in a sustainable way? Here are the 3 scenarios under consideration:

1. Deploy on external Microsoft Azure server environment
2. Deploy on external server environment that more closely matches JetStream (assuming that the org will agree to this)
3. Deploy new instance on existing servers

**Comment by rkorytkowski** [comment]
Microsoft Azure supports docker deployments so it should be possible to deploy OCL there. It's best to spike on doing the deployment to see, if there's any work needed on the OCL side to support it. My expectation is that little or no changes should be needed.

Providing support is another story. We'd need to determine what kind of support is expected by the org. What would be the SLA? I could automate deployments of new code, backups, etc. However, handling any issues specific to the new environment manually would be too much on my plate with my current dedicated time.
