### ISSUE TITLE
Bulk import queue entries disappearing

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#844]
When submitting a bulk import, the importer shows up in the queue beautifully with useful detail (e.g., updating count of what portion of entries have been processed); however, after several minutes, the queue listing begins reloading rapidly and then the entry disappears altogether.

Environment: **staging** (I've seen the same behavior on prod)
Source: **CIEL**
User: burke
Queue name: **ciel**
Queue settings: update **existing, parallel**

Joe had mentioned he was able to capture the importer ID and continue check on its progress after it disappears from the app's queue; however, I tried this with a recent CIEL import and the importer (while still presumably processing somewhere) was no longer accessible even via the API – e.g.,

```
$ http -b "https://api.staging.openconceptlab.org/importers/bulk-import/?task=29cf675d-ba2f-4794-8902-9647cefa0d4c-burke~ciel"  authorization:"token $OCL_API_TOKEN"
{
    "exception": "task 29cf675d-ba2f-4794-8902-9647cefa0d4c-burke~ciel not found"
}
```

**Comment by bmamlin** [comment]
I repeated the bulk import for CIEL v2021-07-05 on production and saw the same behavior. It took about 45 seconds to upload the import and I was able to see the entry (`3fb99543-f9eb-4725-b94f-45f835990c35-burke~ciel`) in the existing import(s) queue in less than a minute. The queue entry appears to work as expected for a couple of minutes, but then the API starts returning 404 errors and the queue begins updating erratically (repeatedly reloading, sometimes showing the queue entry and sometimes empty). After about 3 minutes, the queue stays empty and the browser console shows only 404 responses from the API. I saved a HAR file from Chrome just in case it might help, but – while I masked the API token within it – I'm not going to share it here just in case there might be other sensitive info I failed to mask.

**Comment by jamlung-ri** [comment]
Some dependency on having a stable Flower version

**Comment by paynejd** [comment]
Expect a ~2 weeks more work on this

**Comment by snyaggarwal** [comment]
This was done sometime back.
