### ISSUE TITLE
TermBrowser should request concept/mapping details from the collection scope

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#847]
When browsing a collection in the TermBrowser, resource details are requested from the source scope, rather than from the collection's scope. This means that concepts will not include any modifications and that a concept's mappings will reflect the mappings in the source rather than the mappings in the collection

**Comment by jamlung-ri** [comment]
@snyaggarwal or @paynejd to test this, but it should be closable

**Comment by jamlung-ri** [comment]
Related to #823 but not quite the same. We don't have collection concept details. This will be needed for expansions.

**Comment by jamlung-ri** [comment]
Looking an our [example collection](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY20/concepts/) from yesterday, I am now seeing the correct versions of the concepts. This is working well!
