### ISSUE TITLE
Prepare comprehensive JSON & CSV import test files

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#85]
Need a test file that contains all types of resources

**Comment by paynejd** [comment]
@rkorytkowski Are there certain types of import files that you think we will want for testing? Currently we have a really small one called "TestOrg" and we have a huge one for PEPFAR. Both of these have a variety of resource types. Are there others that would be helpful to have for testing purposes?

**Comment by rkorytkowski** [comment]
I wanted to use the file for automated testing. The PEPFAR is unnecessarily big to run it periodically. Ideally we would use a subset of PEPFAR, but is that okay to be used for testing i.e. commit to a public repo and import to a public test server?

**Comment by paynejd** [comment]
Okay- I'll keep this as an open ticket then. Better to come up with a test
import that isn't attached to any organization.

**Comment by paynejd** [comment]
Makes sense to complete this along with #551

**Comment by jamlung-ri** [comment]
Link to a more comprehensive JSON file, with concepts, sources, collections, references, etc.: https://drive.google.com/file/d/1n1wC5-w4fYKNDx5uViQ5MaaAokHuBOn8/view?usp=sharing

I will need some help with getting this into CSV format though, since I don't exactly know the syntax for things like name attributes.

**Comment by jamlung-ri** [comment]
Link to a more comprehensive CSV import file: https://drive.google.com/file/d/1lmK0qDlDJU4Mth__gCeSkPkiON0c0I02/view?usp=sharing

There are some things that I am less sure of, however, such as:
* Can CSV imports make References?
* Can CSV imports do hierarchy?
* What should we do with attributes that OCL CSV does not currently support but JSON does support (e.g. FHIR attributes or hierarchy_root_url)? Maybe just note it in the documentation?

**Comment by paynejd** [comment]
@jamlung-ri 
* CSV does support references, both as a standalone row in the CSV or as part of a concept row.
* CSV does not currently support hierarchy -- can you create a lower priority ticket for this?
* For attributes available in JSON but not in CSV, please document any that you find in a ticket

**Comment by jamlung-ri** [comment]
I will need to continue working on this to get references working. Moving to next sprint.

**Comment by jamlung-ri** [comment]
>     * CSV does support references, both as a standalone row in the CSV or as part of a concept row. EDIT: This is not fully functional, though there is a ref_collection column to add concepts to a collection e.g. `ref_collection:MyCollectionId`. This should support brackets e.g. `ref_collection[1]`, which should be in URL format.

@paynejd I tried this out but didn't have any luck. Maybe we can try it again together, or we can have Sunny take a look.

**Comment by jamlung-ri** [comment]
>     * For attributes available in JSON but not in CSV, please document any that you find in a ticket

See Epic #855 for this list.

**Comment by jamlung-ri** [comment]
To finalize this, need to put onto Google Sheets, then ew can close this out and create follow up tickets

**Comment by jamlung-ri** [comment]
This has been updated and linked in the documentation. See the [Docs page](https://docs.openconceptlab.org/en/latest/oclapi/apireference/bulkimporting.html) and [GitHub](https://github.com/OpenConceptLab/ocl-docs/blob/main/docs/source/oclapi/apireference/bulkimporting.md). A follow-up ticket will be created to continue this work.
