### ISSUE TITLE
Org/Source/Collection Header Customization

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#851]
Similar to how we can edit the About page for an Organization, Source, or Collection, there should be a way to customize what content appears in the header of that resource. 

This should at least include the ability to write out what text, links, OCL attributes, etc. should appear in the header of the organization.

This should include the following abilities:
* Allow org description to optionally include markdown (and/or potentially to link to a markdown file)
* Optional ordered list of attributes (core and custom) to show/hide in the header, potentially changing the label of that attribute -- with hidden attributes available by clicking on "Additional Attributes: Show"
* Optionally auto-collapse the header

Note that these features will also be applied to sources and collections.

**Comment by jamlung-ri** [comment]
Adjacent next step:
Improved default header view that requires less customization for relevant attributes, maybe a dynamic header that recognizes what key attributes are available for the resource

**Comment by paynejd** [comment]
Also see: https://github.com/OpenConceptLab/ocl_issues/issues/981

**Comment by jamlung-ri** [comment]
> 
> 
> @snyaggarwal has done some development work on this, which is being deployed to QA soon:
> 
>     * Background and Styling: Can use a background image and specify colors for text in the header
> 
>     * Hide Attributes: Certain default OCL attributes for the header can be hidden, e.g. Company and Custom Attributes
> 
>     * Hide Actions: The source controls e.g. Download can be hidden.
> 
> 
> Next steps (documented [here](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.722gehjn6l2d)):
> 
>     * Add tab-level configuration for a “collapsed” header (i.e. only show org ID and tabs)
> 
>     * Add option for an overlay above the image with configurable CSS (eg transparency) — not a priority, but would good to match the current PEPFAR MSP styling
> 
>     * Provide feedback on how to show MER Key Updates — one idea was to only show key updates for the current version (eg MER v2.4 to v2.5) and then move the rest of the updates to other pages
> 
> 
> Please feel free to add anything I missed!

The last two steps will be taken care of in another ticket.
