### ISSUE TITLE
Make first monthly usage report

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#852]
Hoping to have a first draft version of this report by Friday if possible. Initial metrics we'd like to see:

- Total OCL user accounts
- List of new users in OCLv2 by month
- Count of active/inactive users
- Count of Last login by month?
- Counts of new content by month -- orgs, sources, etc
- New users created (count and details) by date range
- Other actions?
  - Track API usage (later)
  - Sunny to create an API to get the result and share with everyone and we can take a call to automate this (by celery-beat) or make it bespoke
  - Expand on Cloudwatch logs to run insight like (token/masked, referrer-url, etc)

**Comment by snyaggarwal** [comment]
- GET `/users/report/`
- Works only for Admin users
- by default returns stats for the last 6 months
- response structure:
```
{
"total": 2071,
"active": 2071,
"inactive": 0,
"new_users": [],
"users_last_login": [],
"new_organizations": [],
"new_sources": [],
"new_collections": [
  {
"Jul 2021": 2
},
  {
"Jun 2021": 3
},
  {
"May 2021": 1
},
  {
"Apr 2021": 400
}
],
}
```
- can define date boundaries in the format `?start=2020-12-31&end=2021-06-30` 
- can use verbose mode `?verbose=true` to get concepts/mappings/source-versions/collection-versions/collection-references stats

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?

**Comment by paynejd** [comment]
Final thoughts:
* Can we shift to a different endpoint, eg `/admin/reports/`?
* Can we add total counts for each resource type?

**Comment by snyaggarwal** [comment]
@paynejd Couple of things:
1. Can we name this as the Monthly Usage Report? That would mean the URL can be `/admin/reports/monthly-usage/`
2. Should the total count be affected by the date range that's applied on monthly distribution?

**Comment by paynejd** [comment]
@snyaggarwal Yes to the endpoint you suggested

Total count should probably be just current date right? Want to include attributes with timestamp and date ranges for each section of the report?

I think let's close this out this out after this change and all additional changes can go into new tickets

**Comment by jamlung-ri** [comment]
To close out by the end of this week.

**Comment by snyaggarwal** [comment]
@paynejd Can you please give me an example of timestamp and date ranges, how should it look in JSON to make it more clear for me.

**Comment by jamlung-ri** [comment]
@paynejd To verify by end of the day.
