### ISSUE TITLE
TermBrowser Sidebar Link Update

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#854]
It looks like there have been some minor changes to links between the TermBrowser sidebar and the OCL Wordpress Site.

Here is a list of what the TermBrowser links to and what it actually should link to:

| Icon/Spot                  | Current (incorrect )Link                                        | Correct Link                                           |
|----------------------------|-----------------------------------------------------------------|--------------------------------------------------------|
| TermBrowser                | https://openconceptlab.org/ocl-tools/metadata-browser/          | https://openconceptlab.org/termbrowser/                |
| OpenMRS Dictionary Manager | https://openconceptlab.org/community-resources/ocl-for-openmrs/ | https://openconceptlab.org/openmrs-dictionary-manager/ |

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done

**Comment by jamlung-ri** [comment]
This is looking good on all environments.
