### ISSUE TITLE
Frequent 504 gateway timeout when requesting exports on staging

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#857]
Staging is regularly responding with 504 gateway timeout when requesting exports on staging. This is a top priority to fix.

**Comment by rkorytkowski** [comment]
It should be fixed now. The query does no longer fetch any concepts or mappings to determine filename... just the last updated date.

**Comment by rkorytkowski** [comment]
It's been deployed to QA and Staging.
