### ISSUE TITLE
CSV Bulk Import - Hierarchy Support

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#859]
* CSV does not currently support hierarchy -- can you create a lower priority ticket for this?

_Originally posted by @paynejd in https://github.com/OpenConceptLab/ocl_issues/issues/85#issuecomment-889082375_

**Comment by snyaggarwal** [comment]
ocldev supports parent_concept_urls in a concept row, this was done [last year] (https://github.com/OpenConceptLab/ocldev/commit/4b82440e5f2b42e09520c2d210b4fb07ed892d68) as part of #798 

@jamlung-ri @paynejd This looks like a duplicate, can we close this?
