### ISSUE TITLE
Implement "includeReferences" parameter on collection & collection version endpoints

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#86]
Currently, the detailed view of a request for a collection or collection version returns the list of all references. These endpoints should treat references the same way they treat concepts and mappings -- references should only be returned if an "includeReferences" URL parameter is set to true in the request.

For example, these two requests should not include references:
```
https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/
```
```
https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/v1.2/
```

But these two requests should include references:
```
https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/?includeReferences=true
```
```
https://api.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Compact/v1.2/?includeReferences=true
```

**Comment by rkorytkowski** [comment]
As part of this issue we will not only include references conditionally in response, but also we will not store them in a single document in DB rather change to the way we store concepts and mappings in Collections i.e. store them in separate documents. It should further speed up handling of collections with 1k+ references.

**Comment by paynejd** [comment]
+1

Also note that paging may need to be implemented as well as I believe it is
for concepts and mappings, but would need to refer to code to verify. I
think that this feature is not well documented.

**Comment by paynejd** [comment]
this feature was implemented by @snyaggarwal in oclapi2 in a separate ticket. closing out here
