### ISSUE TITLE
Inconsistent response while searching on the endpoint https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?q=m&limit=0&verbose=true

### ISSUE THREAD

**Issue by Mrshinezee** [OpenConceptLab/ocl_issues#89]
When the endpoint ``` https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?q=m&limit=0&verbose=true```  runs
<img width="712" alt="screen shot 2019-02-07 at 11 18 38 am" src="https://user-images.githubusercontent.com/20081126/52405338-525c0200-2acb-11e9-9fd1-b1f28cf0198f.png">

You can see that we have a concept called LIVER FUNCTION TEST, when the same endpoint is ran with the query = li, the LIVER FUNCTION TEST DOES not come up.

<img width="770" alt="screen shot 2019-02-07 at 10 33 16 am" src="https://user-images.githubusercontent.com/20081126/52405570-e037ed00-2acb-11e9-948b-5148f8cde05c.png">

What could the reason be?

**Comment by rkorytkowski** [comment]
"q=m" matches concepts having a word "m" in name in any language
If you want to match on partial words use "q=li*".
