### ISSUE TITLE
Disable direct source query 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#898]
https://api.openconceptlab.org/sources/Locales/concepts/?limit=500&is_latest=true&brief=true

The above query works because “Locales” is currently unique in this OCL environment -- however the approach is not very RESTful, as the query will fail as soon as any other user or org creates a “Locales” source -- we’ll want to disable this functionality in the future, but low priority

**Comment by snyaggarwal** [comment]
@jamlung-ri This is addressed as part of #971
