### ISSUE TITLE
Implement API to retrieve orgs with no members

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#911]
- [x] Compile list of orgs with no members for each environment
- [x] During an architecture call, decide how we want to handle this (added to agenda for Sep 14)

**Comment by jamlung-ri** [comment]
API is done, this just needs some discussion about deployment

**Comment by jamlung-ri** [comment]
Will need a new ticket for next steps

**Comment by snyaggarwal** [comment]
GET `/orgs/?noMembers=true` should return list of orgs that have no members.
