### ISSUE TITLE
Change Versions tab for Sources & Collections to use the same components as search

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#912]

**Comment by jamlung-ri** [comment]
For discussion in this sprint. Need an API to search versions. Akhil has already started on this.

**Comment by jamlung-ri** [comment]
This will require back end work since there is not a search version API.

**Comment by snyaggarwal** [comment]
Scope of work:
1. Source/Collection Version indexes in ES with searchable fields, to start with, name, released, retired, date
2. Support search in Versions
3. UI to use Search component

**Comment by paynejd** [comment]
@PatrickCmd This might be a good ticket for you to pick up. Want to take a look and let us know?

**Comment by jamlung-ri** [comment]
Should discuss this on a Dev call. Not clear if this is still the right approach.

**Comment by jamlung-ri** [comment]
No longer relevant
