### ISSUE TITLE
OCL Community Site - Add icons to menu

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#920]
It looks like the Community Site now has the OCL Technical Roadmap linked to it. There are now a couple of icons missing, however. The Community -> Technical Roadmap option should have the "Map" icon ([from here](https://material-ui.com/components/material-icons/)), and the OpenMRS Dictionary Manager should have the OpenMRS icon.

@kaalcumm Can you or Tim get these icons added in? Thanks!

**Comment by kaalcumm** [comment]
This is done!
