### ISSUE TITLE
Add Technical Roadmap link to the TermBrowser sidebar

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#921]
To align with the sidebar on the [OCL Wordpress site](https://openconceptlab.org/), the TermBrowser should add a new option under the Community menu that links to this page: https://openconceptlab.org/technical-roadmap/. Its text should say "Technical Roadmap" and it should display the "Map" icon ([from here](https://material-ui.com/components/material-icons/)).

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done

**Comment by jamlung-ri** [comment]
One quick change: can you reorder the menu to match what is on the [community site](https://openconceptlab.org/)? Meaning, the order should be:
1. Architecture Community Call
2. Developer Community Call
3. OpenHIE Terminology Service Call
4. GitHub
5. Documentation
6. **Technical Roadmap**
7. OCL Mailing List

**Comment by jamlung-ri** [comment]
@snyaggarwal I forgot to mention you above so I just want to make sure you've seen [this](https://github.com/OpenConceptLab/ocl_issues/issues/921#issuecomment-899448041)

**Comment by snyaggarwal** [comment]
@jamlung-ri Done
