### ISSUE TITLE
Question: Redirect qa, demo, staging domains to TermBrowser instead of Community Site?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#929]
Currently all of these URLs redirect to the OCL Community Site at openconceptlab.org:
* qa.openconceptlab.org
* staging.openconceptlab.org
* demo.openconceptlab.org

This can be confusing, because it takes you straight to the production environment.

Should we instead redirect the above URLs to the TermBrowser within the same environment (and leave production unchanged)?

@snyaggarwal @jamlung-ri @rkorytkowski

**Comment by jamlung-ri** [comment]
I agree, this makes sense to me. Probably should do the same behavior as we have now i.e. if logged in, go to the profile page, or if not, go to the global search page.

**Comment by jamlung-ri** [comment]
There was some confusion regarding this on a user testing call - the OCL logo referring to the OCL website. I think it would be good to make the proposed change above.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done

**Comment by jamlung-ri** [comment]
Awesome, the OCL logo aspect of this is done. As for Jon's DNS issue noted in the [first comment](https://github.com/OpenConceptLab/ocl_issues/issues/929#issue-973696475) of this ticket, I think the DNS changes still need to happen.

**Comment by jamlung-ri** [comment]
Closing this out, will create a follow-up ticket for DNS changes
