### ISSUE TITLE
(High Priority) FHIR CodeSystems and ValueSets not appearing in OCL API queries when using search parameters

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#934]
We are trying to show FHIR resources (i.e. Sources/CodeSystems and Collections/ValueSets) that have been loaded into OCL Production. However, I noticed an issue that was keeping the FHIR resources from being displayed in the UI:
https://api.openconceptlab.org/orgs/HL7/sources/ yields all of the FHIR sources that I just loaded in
https://api.openconceptlab.org/orgs/HL7/sources/?q= yields none of the FHIR sources that I loaded in (and this is what the UI uses to query for sources)

It appears that the UI is using search parameters in its queries, and FHIR concepts and sources aren't returning when search parameters are being used in OCL Production.

This is affecting collections/valuesets in the same way it's affecting sources.

It is worth noting that this content has also been loaded into QA and is displaying this correctly there (see [here](https://app.qa.openconceptlab.org/#/orgs/HL7/)). 

@sny can you look into this? Hopefully Production is simply just not using the latest code somewhere.

**Comment by snyaggarwal** [comment]
@jamlung-ri This was an indexing issue. I have indexed this. I can see the same counts now in both the APIs

**Comment by jamlung-ri** [comment]
Perfect, this is done! Thank you!
