### ISSUE TITLE
Bulk import issues: mapping ID case sensitivity and update vs. create

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#935]
https://api.staging.openconceptlab.org/importers/bulk-import/?task=eca79204-335e-47ba-b936-bfcb86c021a7-datim-admin~DATIM-MOH-DEMO-DAA-FY21&result=json

Take a look at the above bulk import results. All of these are new resources, but it is showing up as 36 “updated” resources. There are 2 issues I’m seeing:
1. New source versions are being added to the “updated” list instead of the “created” list
2. There is one mapping that is getting updated because the ID comparison is case insensitive — see below. The from_concept_id and the mapping ID has either an upper-case or lower-case T, but only the upper-case resource was created: https://app.staging.openconceptlab.org/#/orgs/DATIM-MOH-DEMO-DAA-FY21/sources/DATIM-Alignment-Indicators/mappings/MAP-MOH-ADD-OPERATION-de-Test-2-null-disag/details/

```
        {
            "retired": false,
            "from_concept_url": "/orgs/DATIM-MOH-DEMO-DAA-FY21/sources/DATIM-Alignment-Indicators/concepts/de-Test-2/",
            "source": "DATIM-Alignment-Indicators",
            "owner": "DATIM-MOH-DEMO-DAA-FY21",
            "map_type": "ADD OPERATION",
            "owner_type": "Organization",
            "type": "Mapping",
            "id": "MAP-MOH-ADD-OPERATION-de-Test-2-null-disag",
            "to_concept_url": "/orgs/PEPFAR/sources/DATIM-MOH-DAA-FY21/concepts/null-disag/"
        },
        {
            "retired": false,
            "from_concept_url": "/orgs/DATIM-MOH-DEMO-DAA-FY21/sources/DATIM-Alignment-Indicators/concepts/de-test-2/",
            "source": "DATIM-Alignment-Indicators",
            "owner": "DATIM-MOH-DEMO-DAA-FY21",
            "map_type": "ADD OPERATION",
            "owner_type": "Organization",
            "type": "Mapping",
            "id": "MAP-MOH-ADD-OPERATION-de-test-2-null-disag",
            "to_concept_url": "/orgs/PEPFAR/sources/DATIM-MOH-DAA-FY21/concepts/null-disag/"
        },
```

**Comment by snyaggarwal** [comment]
@paynejd fixed both the issues. Should be good in next deployment

**Comment by paynejd** [comment]
Tested on staging and this is working great! Thank you @snyaggarwal!
