### ISSUE TITLE
API profiling tool

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#937]
Introduce some API profiling tool. I found:
https://github.com/jazzband/django-silk

Please note the it records all requests and responses in DB, which may lead to security issues. We should be using that only in a dev/local environment for now, until we fully understand the risks and we can set it up in a way that is safe.

@snyaggarwal is there a way to have it only in dev/local environment? It needs to store data in DB so we would need some way to run certain migrations only locally.

**Comment by jamlung-ri** [comment]
Need tot hink about next steps: deployment? We should have a demo sometime this week.

**Comment by jamlung-ri** [comment]
Will try a demo for this in the next couple of weeks.

**Comment by snyaggarwal** [comment]
@rkorytkowski Added this in dev env. Updated readme
