### ISSUE TITLE
Issue when a dictionary is selected on Tradictional OCL

### ISSUE THREAD

**Issue by Mrshinezee** [OpenConceptLab/ocl_issues#94]
On https://qa.openconceptlab.org/users/admin/ while login we have this view
<img width="1440" alt="screen shot 2019-03-05 at 5 10 49 pm" src="https://user-images.githubusercontent.com/20081126/53819173-a989b100-3f69-11e9-9eb1-e025c28c92a6.png">

Let us select Mulago hospital Dictionary from the list and we get an error page
<img width="1440" alt="screen shot 2019-03-05 at 5 13 58 pm" src="https://user-images.githubusercontent.com/20081126/53819386-1f8e1800-3f6a-11e9-83aa-a4f32f3f1ccc.png">
Any suggestion on what could be the issue @rkorytkowski ?

**Comment by rkorytkowski** [comment]
Thanks for reporting. Looking into that.
