### ISSUE TITLE
Add request headers into CloudWatch Logs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#941]
CloudWatch is already enabled for OCL API and FHIR, but is capturing minimal data. We want to also capture request headers in preparation for using CloudWatch Insights

For staging, also change load balancer timeout to 2min and put a notification in place at 1min so that we can still track slow-running requests

**Comment by jamlung-ri** [comment]
@rkorytkowski Can you take a look at this and then address the Response Header follow-up ticket (#942)?

**Comment by snyaggarwal** [comment]
Added request user in Response headers as `X-OCL-REQUEST-USER`

**Comment by snyaggarwal** [comment]
Created #1116 to add response time in logs. There is no default Django way to do this, will have to write a custom middleware for this.
The rest of the tasks are done in this.
@rkorytkowski Please advise if we can close this out.
