### ISSUE TITLE
Prepare first monthly report from CloudWatch Insights

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#942]

**Comment by snyaggarwal** [comment]
Added the following queries:
1. Active Users = Users making maximum requests
2. Most Used APIs
3. Most Used APIs by Users

These can be seen from Cloudwatch Dashboard.

**Comment by paynejd** [comment]
Closing this out -- new work on cloudwatch reporting will be in the #1365 epic
