### ISSUE TITLE
Data changing when using CSV import

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#943]
@michaelbontyes was recently trying out the CSV import feature and came across a few issues I'll let him detail, but one thing that lept out to me. It appears that when he imported the single concept in the attached file, the value of the `extras:precise` field was changed. In the file, the value is `true`. But when this was imported into OCL the value was changed from `true` to `yes` [TEST129](https://api.openconceptlab.org/orgs/MSFOCP/sources/Implementationtest/concepts/TEST129/). That value should definitely remain `true`.

[MSF Concept Subset](https://github.com/OpenConceptLab/ocl_issues/files/7041576/msf-ocp-source-concepts-v0.0.1.csv)

We use the `precise` field in the extras in OCL to indicate whether the `precise` attribute should be set on the concept in the OpenMRS Concept Dictionary; this value helps us differentiate numeric concepts which should only have integer values from those that can allow a decimal point; unfortunately, our JSON parser probably isn't going to understand that "yes" should be treated as `true`—the former is a JSON string, the latter is a JSON boolean value.

**Comment by jamlung-ri** [comment]
@ibacher Sunny and I have both attempted to replicate this issue of "true" to "yes" but couldn't. This will hopefully be resolved when we allow boolean variable importing (See #954).

**Comment by ibacher** [comment]
Yeah, I think what I was worried about was not the case. Thanks @jamlung-ri!
