### ISSUE TITLE
Implement "Apps" menu in top-right of TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#945]
This will be a new shared component across the OCL TermBrowser and OpenMRS Dictionary Manager. This menu will be where we can provide more shared apps in the future. We also want to add the "Bulk Importer" as third "app" here, and remove the Bulk Importer from under the "Accounts" menu. See linked slidedeck for full mockups and a small screenshot below.

https://docs.google.com/presentation/d/1QvmABtnS86ttQ9h8O-GZIjtFjHqM9M8sNJdJJrGe3l4/edit#slide=id.geb576cd82b_0_9

![image](https://user-images.githubusercontent.com/1189689/130813653-db05fa0a-3f41-431f-b9dd-0d1e37427feb.png)

**Comment by jamlung-ri** [comment]
This is working well in QA, although a follow-up effort will be for the OpenMRS Dictionary Manager to also add this app menu.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Can we close this?

**Comment by jamlung-ri** [comment]
Closed! I made a follow-up ticket for the OpenMRS Dictionary Manager side.
