### ISSUE TITLE
CSV Import Encoding Support

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#946]
Certain characters cannot be read when importing a file by CSV. See example below with french names that prevent loading the CSV into OCL via bulk import.

resource_type | name | name_type |  name[fr] | name_type[fr] | name_locale[fr] | concept_class | datatype
-- | -- | -- | -- | -- | -- | -- | -- |
Concept | Middle name | FULLY_SPECIFIED | 2e prŽnom | FULLY_SPECIFIED | fr | Misc | Text
Concept | Estimated | FULLY_SPECIFIED | EstimŽe | FULLY_SPECIFIED | fr | Misc | N/A
Concept | Additional address | FULLY_SPECIFIED | Adresse supplŽmentaire | FULLY_SPECIFIED | fr | Misc | Text
Concept | Sister | FULLY_SPECIFIED | SÏur | FULLY_SPECIFIED | fr | Misc | N/A
Concept | Unanticipated return to surgery | FULLY_SPECIFIED | RŽintervention non programmŽe | FULLY_SPECIFIED | fr | Diagnosis | N/A

**Comment by jamlung-ri** [comment]
Helpful note from Ian Bacher: 
At least one quick thing: there are two kinds of UTF-8 encoding, one which includes a few bytes before the text (sometimes called UTF-8 with BOM) and one without. UTF-8 without a BOM works while UTF-8 with a BOM does not. The example UTF-8 file you used has the BOM

**Comment by jamlung-ri** [comment]
A good example of a CSV with a variety of characters is available here: https://github.com/DWB-eHealth/msfocp-source/blob/main/OCL_SourceImport_TestCases.csv

**Comment by jamlung-ri** [comment]
@snyaggarwal One note/question from the OpenMRS team: 
"The CSV format is well imported, but not the CSV UTF-8 (which is required for those translations). Is it a limitation within the bulk import or is there another encoding format to use?"

**Comment by snyaggarwal** [comment]
@jamlung-ri I imported this (with OpenMRS validation schema) and everything worked fine. All special characters were imported correctly. 
4 concepts didnt make it through from the CSV because of valid failures of unknown NameType SYNONYM
