### ISSUE TITLE
API fails to load pages for items above 10k

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#947]
I hit this issue trying to paginate via UI: https://app.qa.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts?q=&isTable=true&isList=false&isSplit=false&page=2097&exactMatch=off

The API request is https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?q=&page=2097&exact_match=off&limit=25&includeRetired=false&verbose=false&sortDesc=_score

The response says:
RequestError at /orgs/CIEL/sources/CIEL/concepts/
RequestError(400, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [52425]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')

**Comment by jamlung-ri** [comment]
@snyaggarwal Could you give a quick update on the current state of this? Is the 10000 limit still in place? It'd be great if this is fixed, but if not, we will need to have a discussion.

**Comment by jamlung-ri** [comment]
We discussed this on [today's Arch call](https://docs.google.com/document/d/157ChmfmYLGLEg_fO4cE7oMqtGpL4PchUkEhNfUUMxdo/edit#heading=h.krmzivcjn431).

Next steps to be done in follow-up ticket:
* To inform API users, specify in Docs what his Elastic Search and what limits there are
* To inform UI users, add a URL to these docs to inform why the ES queries are failing after 10k concepts
* Add a log if someone encounters the error, along with what they are querying
