### ISSUE TITLE
Fix slow running DB queries

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#949]
A) `2021-08-26 13:26:34 UTC:10.1.12.93(47084):postgres@postgres:[10693]:LOG: duration: 26820.206 ms statement: SELECT (1) AS "a" FROM "mappings" INNER JOIN "concepts" ON ("mappings"."from_concept_id" = "concepts"."id") INNER JOIN "sources" ON ("mappings"."parent_id" = "sources"."id") INNER JOIN "organizations" ON ("sources"."organization_id" = "organizations"."id") INNER JOIN "concepts" T6 ON ("mappings"."to_concept_id" = T6."id") WHERE (UPPER("concepts"."uri"::text) LIKE UPPER('%/orgs/U.S.-National-Library-of-Medicine/sources/RXNORMR/concepts/1236081/%') AND "mappings"."id" = "mappings"."versioned_object_id" AND "mappings"."map_type" = 'isa' AND "sources"."mnemonic" = 'RXNORMR' AND "organizations"."mnemonic" = 'U.S.-National-Library-of-Medicine' AND UPPER(T6."uri"::text) LIKE UPPER('%/orgs/U.S.-National-Library-of-Medicine/sources/RXNORMR/concepts/1155444/%')) LIMIT 1`

(possibly from bulk import)

Possible improvements:
1. Don't query with LIKE
2. Consider if all joins are necessary
3. Consider if the query can be split up in subqueries

B) `2021-08-26 13:00:14 UTC:10.1.12.93(52394):postgres@postgres:[10362]:LOG: duration: 542729.121 ms statement: SELECT "concepts"."id", "concepts"."internal_reference_id", "concepts"."public_access", "concepts"."created_at", "concepts"."updated_at", "concepts"."created_by_id", "concepts"."updated_by_id", "concepts"."is_active", "concepts"."extras", "concepts"."uri", "concepts"."version", "concepts"."released", "concepts"."retired", "concepts"."is_latest_version", "concepts"."name", "concepts"."full_name", "concepts"."default_locale", "concepts"."supported_locales", "concepts"."website", "concepts"."description", "concepts"."external_id", "concepts"."concept_class", "concepts"."datatype", "concepts"."comment", "concepts"."parent_id", "concepts"."versioned_object_id", "concepts"."mnemonic" FROM "concepts" INNER JOIN "concepts_sources" ON ("concepts"."id" = "concepts_sources"."concept_id") LEFT OUTER JOIN "concepts_hierarchicalconcepts" ON ("concepts"."id" = "concepts_hierarchicalconcepts"."child_id") WHERE ("concepts_sources"."source_id" = 1135 AND "concepts"."id" = "concepts"."versioned_object_id" AND "concepts_hierarchicalconcepts"."parent_id" IS NULL AND NOT ("concepts"."mnemonic" = 'ICD-10-CM')) ORDER BY "concepts"."mnemonic" ASC LIMIT 100`

Possible improvements:
Don't join concepts_sources. It's a single source we are interested in so use a subquery instead with a limit.

C) `2021-08-26 13:00:58 UTC:10.1.11.186(47126):postgres@postgres:[20203]:LOG: duration: 153187.007 ms statement: SELECT COUNT(*) AS "__count" FROM "mappings" INNER JOIN "mappings_sources" ON ("mappings"."id" = "mappings_sources"."mapping_id") WHERE ("mappings_sources"."source_id" = 746 AND "mappings"."is_active" AND NOT "mappings"."retired" AND "mappings"."is_latest_version")`
and
`2021-08-26 13:02:20 UTC:10.1.11.186(41156):postgres@postgres:[13448]:LOG: duration: 145315.597 ms statement: SELECT COUNT(*) AS "__count" FROM "concepts" INNER JOIN "concepts_sources" ON ("concepts"."id" = "concepts_sources"."concept_id") WHERE ("concepts_sources"."source_id" = 746 AND "concepts"."is_active" AND NOT "concepts"."retired" AND "concepts"."is_latest_version")`

Possible improvements:
Let's consider moving or duplicating is_active, retired and is_latest_version to mappings_sources and concepts_sources to avoid the join.

**Comment by rkorytkowski** [comment]
Count queries seem to be the only ones that are putting extra load on the DB now. We should prioritize this.

**Comment by jamlung-ri** [comment]
To discuss in Tuesday's Dev call. If appropriate, we can close this out and start creating individual tickets as needed.

**Comment by snyaggarwal** [comment]
moved count queries to #1008. Closing this one
