### ISSUE TITLE
URGENT: PEPFAR bulk import stuck in production

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#951]
I’m running an import in production for PEPFAR of 2,055 resources (`{Sources: 2, Concepts: 780, Mappings: 1271, Source Versions: 2}`) that has been stuck at 1,675 for several minutes now. Bulk import script is attached. Details of the stalled import from the API here:
```
{
    "details": {
        "summary": "Started: 2021-08-27 15:46:36.922648 | Processed: 1675/2055 | Time: 1129.1105535030365secs"
    },
    "task": "e4386aed-29dd-4a6d-91d7-8617ea573759-datim-admin~default",
    "state": "STARTED",
    "username": "datim-admin",
    "queue": "default"
}
```

[https://app.zenhub.com/files/122384560/33c5595d-73ed-4c2f-b9a7-678273084a2b/download](https://app.zenhub.com/files/122384560/33c5595d-73ed-4c2f-b9a7-678273084a2b/download)

**Comment by snyaggarwal** [comment]
@paynejd  Looks like the workers restarted that were performing this import but not the main process that was orchestrating it, and hence you were still getting the status update. I have killed the job, you would want to delete the org/source and restart this. I am looking into the issue

**Comment by paynejd** [comment]
After deleting content from the failed import, it was re-imported without issue (see #840). Will continue to test and monitor imports in #953, and closing this ticket out
