### ISSUE TITLE
API and UI should be consistent on requiring default_locale, supported_locales or full_name in source/collection

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#96]
The UI marks these fields as required, but API marks them as optional. What's worse the UI fails when trying to display a collection/source without supported_locales set.

@paynejd, should we make these fields optional on the UI side or enforce them on the API side? When enforcing them we would need to fix existing data:
1) Copy name to full name if missing
2) Set default locale to en if missing
3) Copy default locale to supported locales if missing

Also we need to decide if we want to apply the same behavior to newly created items or fail if missing.

**Comment by rkorytkowski** [comment]
@paynejd, ping.

**Comment by paynejd** [comment]
Name behavior is different for sources and collections and it should not be. Internally, there are 4 fields: id, short_code, name, and full_name. short_code is identical to ID, and is actually duplicative. In the future we would probably remove short_code.

Name and Full_name were intended to be different, where name is essentially the "short name" that is used by default in most places and full_name is the fully specified version of the name, probably with no acronyms or anything. For some reason, the source forms in OCL-WEBG only expose the full_name field and appear to automatically copy short_code into the name field. Collections show both name and full_name fields.

Desired behavior for names:
* Both name and full_name fields for sources/collections should be independent and editable for both ocl-web and ocl-api
* Both name and full_name should be required in the API, though it is fine for the web client to copy the value of name into the full_name field

For locales, we do not take advantage of the repository locale fields yet, but let's go ahead and set up the correct behavior.

Desired behavior for repository locales:
* default_locale should be required -- set to 'en' where empty
* supported_locales should be optional -- some repositories may not restrict locales

**Comment by aprilcurrier** [comment]
@rkorytkowski  can you provide a status update on this?

**Comment by rkorytkowski** [comment]
I didn't get a chance to start implementing it. Moving to backlog for now.

**Comment by paynejd** [comment]
@snyaggarwal Can you verify that this behavior is addressed in oclapi2?

**Comment by snyaggarwal** [comment]
This would need changes in ocl_web. Will wait for that to be done.

**Comment by aprilcurrier** [comment]
@snyaggarwal  any update?

**Comment by snyaggarwal** [comment]
This will be part of oclweb2. Will have to wait for web2 to reach that stage.

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski following is done on this for both Source/Collection:
1. `name` and `full_name` are independent and editable for both oclweb2 and oclapi2
2. `name` and `full_name` are required in oclweb2.
3. `name` is required in oclapi2 and `full_name` defaulted to `name` if not provided.
4. `default_locale` is required in web2 and defaulted to `en` in api.
5. `supported_locales` are required in web2 and defaulted to `default_locale` if not provided

Let me know if anything needs to change in this

**Comment by aprilcurrier** [comment]
Will reference in testing ticket #503 #466
