### ISSUE TITLE
[WEB] Common Comparison Component

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#961]
Goals:

- [x] Common Comparison component should not have anything specific to the resource (concept/mapping/etc)
- [x] Each Resource needs to have its own wrapper Comparison component (like ConceptComparison, MappingComparison, etc) that should be injecting resource specifics into the common comparison component.
- [x] Common Comparison component should have formatters for list/JSON/boolean values and any specific formatters should be injected from resource components.

**Comment by snyaggarwal** [comment]
@paynejd Can we close this and create separate tickets for more on comparison?

**Comment by paynejd** [comment]
Hi @snyaggarwal - I'm not actually sure how to test this one. Probably makes sense to close out and create new tickets for more comparison work

**Comment by snyaggarwal** [comment]
@paynejd Yes let's create separate tickets for comparison feature(s).
