### ISSUE TITLE
OpenMRS Validation external_id

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#963]
Is it possible to add a validation to the OpenMRS custom validation scheme to ensure that the `external_id` field is not longer than 36 characters? We use this field to store the UUID of fields for OpenMRS and fields more than 36 characters long cause issues.

**Comment by snyaggarwal** [comment]
hey, @ibacher is this validation only for Concept and Mapping or for Source/Collection/Org as well?

**Comment by snyaggarwal** [comment]
@ibacher Got it. Will get this done soon.
