### ISSUE TITLE
Mismatch between references between index and mongo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#97]
Requesting this collection's mappings via the `mappings` endpoint returns only 3 mappings. If you look at the references directly, though, there are 51 mappings in the collection. I believe this can be fixed with a simple re-index, but it also happens frequently (with both mappings and concepts), so potentially worth uncovering why it is happening.

Here's the request that returns 3 mappings:
```
https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-MOH-Facility/mappings/
```

This returns the references directly and works as expected:
```
https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-MOH-Facility/references/?limit=100
```

**Comment by rkorytkowski** [comment]
The staging index was in bad shape since the issue of not properly deleted sources/collections. I've cleaned everything up using the new /manage/brokenreferences endpoint and rebuilding the solr index now.

**Comment by rkorytkowski** [comment]
Re-indexing completed. I see 51 mappings in both now.
