### ISSUE TITLE
RxNorm Validation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#973]

**Comment by jamlung-ri** [comment]
The automated export file shows that the concepts and mappings are correct. However, there may be something wrong with the Index for the mappings since the [mappings page in the TermBrowser](https://app.staging.openconceptlab.org/#/orgs/U.S.-National-Library-of-Medicine/sources/RXNORMR/mappings/?q=&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off&includeRetired=true) shows the wrong number of mappings. I will do further investigation once #977 is complete.

**Comment by jamlung-ri** [comment]
Seems like there might be an index issue with RxNorm. Not sure how to go about rebuilding it, but it's pretty clear that the facets and total number of mappings are both incorrect. There should be 812,275 mappings, based on both the import and export files, but [RxNorm in the TermBrowser](https://app.staging.openconceptlab.org/#/orgs/U.S.-National-Library-of-Medicine/sources/RXNORMR/mappings/?q=&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off&includeRetired=true) is showing 812,227 mappings in total and 812,247 mappings in the facets. @snyaggarwal Any thoughts on this?

**Comment by snyaggarwal** [comment]
@jamlung-ri rebuilding index for just RxNorm's mappings.

**Comment by snyaggarwal** [comment]
@jamlung-ri Indexing is done and now its showing correct 812,275 mappings count

**Comment by jamlung-ri** [comment]
This is looking good! I think we're all done with this!
