### ISSUE TITLE
Handle orgs created by ocladmin that have no members

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#976]
In #911 and #972, we added an API to get a list of orgs with no members and then assigned the org creator as a member for any of these orgs where the org creator was no `ocladmin`. Now, we have a small set of orgs remaining that still have no member that were have `ocladmin` as the `created_by` user.

**Comment by paynejd** [comment]
@snyaggarwal did we already finish this one up?

**Comment by snyaggarwal** [comment]
Yep this is done
