### ISSUE TITLE
500 error when getting facets

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#977]
The query below seems to be consistently giving a 500 error. It disables filters, which would be useful for breaking down mapping types.

https://api.staging.openconceptlab.org/mappings/?q=&page=1&exact_match=off&limit=25&includeRetired=true&verbose=false&facetsOnly=true

**Comment by snyaggarwal** [comment]
@jamlung-ri this is happening on staging only. And I am not sure whats the reason since we don't have logs.
@paynejd Did you get any email alert for 500?
@rkorytkowski Can we do #966 on priority? Currently, I am blind :)

**Comment by snyaggarwal** [comment]
This is fixed. Closing this out.
