### ISSUE TITLE
Search tokenizing not working as expected - support multiple partial search tokens?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#98]
If trying to find "Acquired Immunodeficiency Syndrome", OCL search is very limited in how you specify the search criteria. If a user enters a single partial token (e.g. "acq" or "imm"), OCL will return the expected concepts (plus a lot of others). Ideally, we want a user to be able to enter 2 partial search tokens, such as "acq imm", but it appears that the API or Solr is not currently set up to support that. Could you estimate the LOE to implement? And is this a feature we could implement within the next 4-6 weeks?

Links:
* https://qa.openconceptlab.org/search/?q=acq
* https://qa.openconceptlab.org/search/?q=imm
* https://qa.openconceptlab.org/search/?q=acq+imm

**Comment by rkorytkowski** [comment]
For partial searches in the current solr configuration one needs to add '*' at the end of each word, e.g. https://qa.openconceptlab.org/search/?q=acq*+imm*

A quick fix is to append '*' to all words (< 4h) before sending a query to solr. A wildcard query is rather slow, but not noticeably at the current server load. A better fix is to rebuild a proper index optimized for partial searches (< 16h).

**Comment by rkorytkowski** [comment]
Implemented quick fix. Note that previously the search was modified from "some search phrase" to "*some search phrase*", which didn't make much sense, because it was tokenized into words and searched as follows: "*some" AND "search" AND "phrase*", meaning find all terms containing words, which end with "some" as well as start with "phrase" and match exactly "search".
I've modified it to "some*" AND "search*" AND "phrase*", which finds all terms with words starting with "some" and "search" and "phrase".

**Comment by rkorytkowski** [comment]
@paynejd, deployed to staging. Please let me know, if it's acceptable. The search still feels close to instant so I wouldn't yet implement changes to the index.

**Comment by paynejd** [comment]
based on my quick testing, the search operates much more intuitively now!
nice work on a quick fix!

**Comment by askanter** [comment]
How could I test it? Thanks!

**Comment by paynejd** [comment]
You can test it directly on OCL: https://staging.openconceptlab.org/search/

It has been deployed to QA and staging -- not sure about demo and
production yet

**Comment by askanter** [comment]
This is awesome

-------------------- 
Andrew S. Kanter, MD MPH FACMI FAMIA

Asst. Prof. of Clinical Biomedical Informatics and Clinical Epidemiology
Columbia University
Email: andrew.kanter@columbia.edu / ask2164@cumc.columbia.edu
Mobile: +1 (646) 469-2421
Skype: akanter-ippnw
Yahoo: andy_kanter 

    On Tuesday, April 30, 2019, 8:55:17 AM CDT, Jonathan Payne <notifications@github.com> wrote:  
 
 You can test it directly on OCL: https://staging.openconceptlab.org/search/

It has been deployed to QA and staging -- not sure about demo and
production yet
