### ISSUE TITLE
Ability to customize an org header background/foreground

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#981]
We want to implement the ability for an org admin to customize an org's header background/foreground in the following ways:
* Background color or image
* Foreground color -- either a single color, or break it up into the following:
  * foreground color for title (org.name)
  * foreground color for description (org.description)
  * foreground color for tabs (eg Sources, Collections, etc)
* Tab highlight formatting - eg. the blue bottom border for the selected tab

Note that this ticket should be done along with #982 and #983 

Working our way toward this:
![image](https://user-images.githubusercontent.com/1189689/134013727-79fd4b4a-b5cf-459f-9d4d-2d7c77856a11.png)
![image](https://user-images.githubusercontent.com/1189689/134013839-441daab9-b0b0-46e7-9ec9-e2254a929912.png)

**Comment by jamlung-ri** [comment]
This is working properly in QA. I created a "Testing Visuals" configuration [here](https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true&new=true) as an example.
