### ISSUE TITLE
Add icons to org tabs

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#982]
We want to add icons to each of the default org tabs. Ideally, an admin could customize the icon for a custom tab, possibly restricting to material icons if that keeps the requirements simple.

Let's start by using the icons that we already use for each of the tabs, same as in the user profile page. Here are 2 examples:
![image](https://user-images.githubusercontent.com/1189689/134010731-f55b345b-23d6-4be6-a835-0fff641ce683.png)
![image](https://user-images.githubusercontent.com/1189689/134010639-bcc69328-7e52-4d9f-a401-557cdabc6166.png)

**Comment by jamlung-ri** [comment]
This seems to be working in QA. I also tested it with configurations and seem to be having luck with it. See screenshot.

![image](https://user-images.githubusercontent.com/55999682/134670580-606f5e38-daf3-494c-bc74-eb1f7c30a056.png)
