### ISSUE TITLE
Move org tabs to inside the org header section

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#983]
Note that this ticket should be done along with #981 and #982 

See examples here:
![image](https://user-images.githubusercontent.com/1189689/134013488-a7fcb1ea-c625-4638-be0a-2a86e213af3c.png)
![image](https://user-images.githubusercontent.com/1189689/134013449-0d079e55-9c8f-4dd8-883b-e6fcc165c3bb.png)

**Comment by jamlung-ri** [comment]
This is working properly in QA.
