### ISSUE TITLE
Incorrect Facet Query being used on Source page

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#987]
Looking at PIH on OCL Staging, it appears to be using the wrong query to get facets, which gives incorrect filters.

Example: I am on this [PIH source page](https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/) or this [CIEL source page](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/), and the More Filters button shows Collections for PEPFAR's MER content. It appears that the facets query is not looking at the source page, but is instead looking at OCL as a whole. Query in use: https://api.staging.openconceptlab.org/concepts/?q=&page=1&exact_match=off&limit=25&includeRetired=false&verbose=false&facetsOnly=true

See screenshot below:
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/285fda3f-dde5-4655-b98c-a1decd229af2)

**Comment by snyaggarwal** [comment]
Fixed

**Comment by jamlung-ri** [comment]
Looks good!
