### ISSUE TITLE
Add unique constraint on concept and mapping external ID in OpenMRS Validation Schema

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#989]
Currently, the OpenMRS validation schema requires that `concept_version.id` is unique in a specific dictionary for non-retired concepts.

The OpenMRS squad requested that we also require that `concept_version.external_id` and `mapping_version.external_id` are unique in a dictionary for non-retired resources.

**Comment by snyaggarwal** [comment]
@paynejd Similar issue raised by Ian - https://github.com/OpenConceptLab/ocl_issues/issues/963

**Comment by paynejd** [comment]
duplicate! closing out
