### ISSUE TITLE
Load full CIEL into demo environment

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#99]
https://demo.openconceptlab.org should contain the full CIEL dictionary

**Comment by rkorytkowski** [comment]
@paynejd, what's the way to load the full CIEL into an empty server instance?

**Comment by rkorytkowski** [comment]
@paynejd, never mind I got it.

https://demo.openconceptlab.org has now the full CIEL dictionary and it's being reset every 24h.

I still need to implement a proper way to store the demo db backup somewhere. I've contacted Cintia to verify my approach.

**Comment by paynejd** [comment]
Hey Rafal- is there a way to see how long it took to do the full CIEL
import on an empty server?

**Comment by rkorytkowski** [comment]
I did it locally and created a backup, which is now used by the demo server to reset daily.

I haven't measured precisely, but I started the import before breakfast and it was done after ;) It's still faster to restore from a backup, which takes just under a minute, thus I chose that approach for the demo server.
