### ISSUE TITLE
Update mappings pane in a concept details page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#991]
This should be the new default view on the concept details page -- this should be available to all by default without any configuration.

Requirements:

- [x] Rename to "Associations"
- [x] include the count of associations to the right of the header
     * Edit: Partially done but also addressing this in #1013  
- [x] include hierarchical relationships in the list using the map_type defined by the source
     * Edit: Looking at this [ICD test concept](https://api.qa.openconceptlab.org/orgs/WHO-ICD-Test/sources/ICD-10-Test-Small/concepts/B18.1/), I am not seeing the hierarchy in there. 
- [x] combine "direct" and "inverse" mappings into the same section -- use an icon after the map_type to indicate that it is inverse (eg "inverse" in math is a `-1` superscript, or it could just be a label of `Inverse`)
- [x] sort mappings by internal/external (where internal means pointing to a concept in the same source), then by map_type, then by direct/inverse
- [x] group mappings by map_type + direct/inverse and only show the map_type + direct/inverse once -- no need to repeat it for each row
- [x] Action icon (the 3-dots) should only appear on mouseover
     * Edit: I believe we decided not to do this, although it may be good to reduce the size of the dots.

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/13297222-ed1d-45cb-9a8b-9bae1b0c1a12)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/396c0ede-85b6-4bf7-9fa8-685ffe1f50b3)

![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/0a73dabe-790c-4731-adc8-a30289920a85)

**Comment by jamlung-ri** [comment]
@snyaggarwal I reviewed these and put edits into the checklist above where applicable. A few more small changes, and we can close this one out.

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri I will work on the remaining points. 
Just on the hierarchy -- if you want to see the hierarchy attributes you will have to ask for it using query params:
`includeParentConceptURLs=true`, `includeChildConceptURLs=true`, `includeParentConcepts=true`, `includeChildConcepts=true`, `includeHierarchyPath=true`

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri In order to show hierarchy in associations, should we show both children and parents (as the inverse)?

**Comment by paynejd** [comment]
Agree with Joe -- just please include the source.hierarchy_meaning in the
relationship as well. Something like this:

Has child
(Is a -1)

Has parent
(Is a)

**Comment by snyaggarwal** [comment]
Done

**Comment by jamlung-ri** [comment]
Awesome! Looks good in QA, looking at this [ICD concept](https://app.qa.openconceptlab.org/#/orgs/WHO-ICD-Test/sources/ICD-10-Test-Small/concepts/B18.1/).
