### ISSUE TITLE
Add Collection Membership section to concept details under the mappings/associations

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#992]
We want to display a list of collection that a concept is a member of on the concept details page.

* Collection membership section should go underneath the mappings/association section
* Include just a list of the collection IDs/names/versions - clicking on one will navigate to that collection version
* Restrict the list to the same org/user namespace as the concept that is being viewed
  * In the future, we'll likely provide options to look at other namespaces, but we'll start with just this

**Comment by jamlung-ri** [comment]
Noting some things we discussed in the [Dev Call on 28 Sep 2021](https://docs.google.com/document/d/102y4F9fHlTQyrq0CGm85xHWDTzqJPnon_edXJIWW504/edit#heading=h.e9zlacihzyr7):

- [ ] Create a tooltip that says you will only see internal collections i.e. collections from the same owner. 
- [ ] Adopt a Grouped Table style that shows what collections and versions the resource belongs to.

@snyaggarwal ^

In the future, we will also want to show what collections for other owners are using a concept/mapping.

**Comment by snyaggarwal** [comment]
@jamlung-ri Added the last two points
