### ISSUE TITLE
Expansion/Dynamic Reference testing

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#997]
Once @snyaggarwal has given us a demonstration on the Expansions within the new environment, we need to do some testing to feel out what all it can do.

We should be able to Create old and new-style collections and collection versions.

Follow-up from #818

**Comment by jamlung-ri** [comment]
Some testing was done in a call yesterday. Sunny has since made changes to the UI to accommodate the issues we noticed. Testing will continue in the next sprint.

**Comment by jamlung-ri** [comment]
UI feedback has been incorporated, so @paynejd and @jamlung-ri need to continue testing.

**Comment by jamlung-ri** [comment]
Some expansion testing has occurred as a result of the DDCC content import testing. A couple of videos of issues or potential behavior changes have been posted in the ocl-dev Slack channel.

**Comment by snyaggarwal** [comment]
That looked like a bug. Will fix this

**Comment by snyaggarwal** [comment]
@jamlung-ri this is fixed and deployed on QA.
This would mean if you create an expansion where the version has a reference with `?includeRetried` it should get retired concepts in the expansion

**Comment by jamlung-ri** [comment]
Awesome, I was able to get that working! I discovered another bug in the meantime, however. 

When I try to Add a reference via URL, it starts to bring up the "Add Mappings?" prompt, which quickly disappears. Then I have to click Add again, and it works properly. This might be because OCL runs the background query for "Found XX results with this expression". Quick video example: https://www.loom.com/share/47d54948e99040afa9bc1f160dd35099

**Comment by snyaggarwal** [comment]
@jamlung-ri these both should be fixed on QA

**Comment by paynejd** [comment]
Final QA testing for this was blocked due to receiving inconsistent results on the MOH IMAP import/export test. We discussed this on the 2/1/2022 Dev call, and @snyaggarwal determined that a postgres connection issue was at the bottom of it. This issue is a result of the infrastructure configuration (e.g. resources available) for the QA/dev environments.

@snyaggarwal to resolve so that we can finish the MOH Alignment tests in QA before moving this functionality on to staging.

**Comment by paynejd** [comment]
Testing for IMAP/MOH is complete in staging!

@paynejd to finalize testing of the OpenMRS Dictionary Manager this sprint.

**Comment by paynejd** [comment]
Found a potential issue with migration of collections to the new model on QA -- see here that the HEAD collection version has 44 references but v1.0 collection version has 0 references:
https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY19/v1.0/expansions/autoexpand-v1.0/versions

The same is true for many other collections on QA in the PEPFAR-Test10b organization-- see `MER_REFERENCE_INDICATORS_FY17` and `MER_REFERENCE_INDICATORS_FY18` also.

**Comment by snyaggarwal** [comment]
@paynejd  I suspect [v1.0](https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY19/v1.0/) of [MER_REFERENCE_INDICATORS_FY19](https://api.qa.openconceptlab.org/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY19/) was create before the references were added to HEAD. 
I created a test version on this and the references were copied correctly. (I deleted that version)
The migration from the old style to the new style doesn't touch references, so it can't be that.
