### ISSUE TITLE
Move Custom Attributes to its own section in Resource Details

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#999]
Following the design in [this slide](https://docs.google.com/presentation/d/1nkGq1Zx_SDJa-8NblyaHIr5Ot33xKWem-vyTtLjQu1k/edit#slide=id.ged79dac051_0_37), when using the Concept Details page, we want Custom Attributes to appear in its own section.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is done
